### PR TITLE
Image refresh for fedora-39

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-39
 * [x] image-refresh fedora-39

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-39 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-39-20231223-225738

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-39-20231223-225757.log

**Comment by martinpitt** [comment]
This is blocked on releasing https://bodhi.fedoraproject.org/updates/FEDORA-2023-733d984cc3 to fix the libssh regression.

**Comment by martinpitt** [comment]
libssh 0.10.6-2 is available on the mirrors now, so let's re-do this.

**Pull request closed without merging**
