### PR TITLE
images: Put back intltool on fedora-30

### PR DESCRIPTION
**Pull request by martinpitt**
Dropping it broke all fedora-30 based tests of stable rhel-* branches
(container/bastion and selenium/*). Put it back until we retire these
branches.

 * [x] image-refresh fedora-30
 * [x] Adjust obsolete abrt-ccpp.service: https://github.com/cockpit-project/cockpit/pull/13117

Example: https://logs-https-cockpit.apps.ci.centos.org/logs/pull-220-20191108-075353-30e205e2-cockpit-project-cockpit-rhel-8.1-fedora-30-container-bastion/log.html

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-01.
Log: https://209.132.184.41:8493/logs/image-refresh-220-20191108-071313/

**Comment by cockpituous** [comment]
image-refresh fedora-30 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-30-20191108-075252

**Comment by martinpitt** [comment]
[testContainerProblems](https://209.132.184.41:8493/logs/pull-220-20191108-091717-51ca5d02-cockpit-project-cockpit--fedora-30/log.html#36-2) shows an abrt-ccpp.service failure. Let's retry to see if it is a flake.

**Comment by martinpitt** [comment]
That [repeats](https://209.132.184.41:8493/logs/pull-220-20191108-143939-51ca5d02-cockpit-project-cockpit--fedora-30/backup.99dw81/log.html#36-2), so abrt-cccp got broken. *sigh*

**Comment by marusak** [comment]
@ernestask do you have any idea why `sudo systemctl start abrt-ccpp` might started to fail in Fedora 30?

**Comment by ernestask** [comment]
https://github.com/abrt/abrt/commit/77653d7a367a756e796f5b820d9bea3c8feb117e

**Comment by martinpitt** [comment]
@ernestask : Ah, does that mean we should stop installing the abrt-addon-ccpp package in Fedora?

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-29pbs.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-220-20191109-104646/

**Comment by martinpitt** [comment]
Added a commit that drops abrt-addon-ccpp and rebuilding, let's see how far this gets with the abrt tests.

**Comment by ernestask** [comment]
Well, no, you want to install the package if you want to test something ABRT, but you want to make sure that the `abrt-journal-core` service is used, instead.

**Comment by martinpitt** [comment]
Ack, putting back the previous rebuild then, and I'll send a cockpit PR for changing the started service. Thanks!

**Comment by cockpituous** [comment]
image-refresh fedora-30 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-30-20191109-110909

**Comment by martinpitt** [comment]
I sent PR #13177 for the abrt issue, that needs to land before this can become green.

**Comment by martinpitt** [comment]
Yay, all green except for the two bogus contexts. Can someone please land this?

**Pull request merged**
