### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing
 * [ ] Let https://tracker.debian.org/pkg/nftables 1.1.0-2 go into testing, then try again

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20240723-225047

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-debian-testing-cd9a325b-20240723-223752/log.html

**Review by martinpitt — APPROVED** [review]

**Comment by martinpitt** [comment]
Firewall/nftables has serious problems, errors like

ERROR: 'python-nftables' failed: internal:0:0-0: Error: Could not process rule: No such file or directory

**Comment by martinpitt** [comment]
Looks like https://tracker.debian.org/news/1547419/accepted-nftables-110-2-source-into-unstable/ very probably fixes this, so le's retry in a few days when that goes into testing.

**Comment by martinpitt** [comment]
The fixed version has entered debian-testing. :game_die:

**Pull request closed without merging**
