### PR TITLE
images: disable GPG check on centos-10

### LINKED ISSUE #6452: Image refresh for centos-10
Image refresh for centos-10
 * [ ] FAIL: image-refresh centos-10

### PR DESCRIPTION
**Pull request by martinpitt**
The development compose lost its GPG signatures recently [1]. Apparently this is by design. Work around this by disabling GPG check.
    
Drop the lone `--nogpgcheck` for the initial update. This isn't desirable for RHEL (or any other) image in the first place, and it wasn't clear why it even exists.

Fixes #6452

[1] https://issues.redhat.com/browse/CS-2243

----

 * [x] image-refresh centos-10
 * [x] image-refresh rhel-9-5 (not landing, just successful build is proof enough)
 * [x] https://github.com/cockpit-project/cockpit/pull/20558

I'm rebuilding rhel-9-5 as well to make sure the GPG check works for `dnf update`. I don't expect it to fail  as all other `dnf` commands had gpg enabled -- but let's be sure.

### CODE REVIEW

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-3620e151-20240606-074325/log.html

**Comment by cockpituous** [comment]
image-refresh rhel-9-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-5-20240606-081104

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-5-3620e151-20240606-075430/log.html

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240606-091231

**Comment by martinpitt** [comment]
This [grafana/pcp failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6474-1dcd8e4e-20240606-144742-centos-10-other-cockpit-project-cockpit/log.html) seems persistent, trying locally.

**Comment by martinpitt** [comment]
This reproduces locally in half of the runs. In the others I get

> WARNING: Waiting for !ph_is_present("#pcp-settings-modal:first-child") took 28.5 seconds, which is 94% of the timeout.

Our nested-kvm CI could easily be a tad slower. I sent https://github.com/cockpit-project/cockpit/pull/20558 to fix that.

**Comment by martinpitt** [comment]
This is apparently intentional, see https://issues.redhat.com/browse/CS-2243 . I'll do that differently.

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-b7a04844-20240607-052711/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-b7a04844-20240607-054557/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-b7a04844-20240607-060119/log.html

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240607-064932

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-b7a04844-20240607-063259/log.html

**Review by jelly — APPROVED** [review]

**Pull request merged**
