### PR TITLE
images: Remove old kernels from Debian/Ubuntu images

### PR DESCRIPTION
**Pull request by martinpitt**
This reduces image size, and also avoids wasting time on rebuilding
initrds for old kernels.

This must happen very late, as `podman` and other things might still
want to load modules for the running kernel.

Move zero-disk.setup to the very end for maximum efficiency.

 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-2004
 * [x] image-refresh ubuntu-2204

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-ffj4t.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3269-20220421-101818/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20220421-103535

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-ffj4t.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3269-20220421-103535/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2004 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2004-20220421-105353

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-4vfck.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3269-20220421-105353/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2204 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2204-20220421-110909

**Comment by martinpitt** [comment]
The [debian-testing](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3269-20220421-101818/log) log shows that this works. Initiallly there's the new kernel from the upgrade:
```
The following NEW packages will be installed:
  linux-image-5.16.0-6-cloud-amd64 [...]
```

and at this new step, the old kernel gets cleaned up:
```
+ eatmydata apt-get -y -o Dpkg::Options::=--force-confold autoremove --purge
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be REMOVED:
  libcbor0* libldap-2.4-2* liburing1* linux-image-5.10.0-13-cloud-amd64*
```

I locally checked that image, it only has one kernel (the new 5.16 one).

All green :green_heart:

**Pull request merged**
