### PR TITLE
images: Update fedora-testing to Fedora 38

### LINKED ISSUE #4675: Image refresh for fedora-testing
Image refresh for fedora-testing
 * [ ] image-refresh fedora-testing

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh fedora-testing

Closes #4675

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20230420-132814

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-testing-20230420-132828.log

**Comment by martinpitt** [comment]
The [machines failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4674-20230420-135518-74c4e407-fedora-testing-cockpit-project-cockpit-machines/log.html) is simple -- we have this hack in fedora.setup, which needs to be applied to `fedora-testing` as well, or better, look at the os-release variable `$VERSION_ID` instead:

```sh
# HACK: https://bugzilla.redhat.com/show_bug.cgi?id=2170110    
if [ "$IMAGE" = "fedora-38" ]; then    
    COCKPIT_DEPS="$COCKPIT_DEPS qemu-audio-spice"    
fi    
```

@mvollmer, does the stratis failure ring a bell? You were looking at several issues recently. If not, I can investigate tomorrow.

**Comment by mvollmer** [comment]
> @mvollmer, does the stratis failure ring a bell?

Yes, that is very likely https://github.com/stratis-storage/stratisd/issues/3324, worked around by https://github.com/cockpit-project/cockpit/pull/18679

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20230425-104453

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-testing-20230425-104444.log

**Comment by martinpitt** [comment]
The [machines failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4674-20230425-105203-1e26067d-fedora-testing-cockpit-project-cockpit-machines/log.html#29-2) is known issue #4308. This was already fixed, but apparently came back.

**Comment by martinpitt** [comment]
Let's rebuild and test the latest stratis 3.5.4, maybe that will fix the regression.

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20230430-045215

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-testing-20230430-045252.log

**Comment by martinpitt** [comment]
Nice, new stratis works! I just forgot to add the naughty for c-machines.

**Comment by martinpitt** [comment]
Even easier, the naughty/fedora-testing symlink just needed to move to fedora-38.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
