### PR TITLE
Image refresh for fedora-rawhide-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-boot
 * [x] image-refresh fedora-rawhide-boot

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-boot done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-boot-20231103-223926

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-boot-20231103-223939.log

**Comment by martinpitt** [comment]
```
test/prepare-updates-img: line 15: scripts/makeupdates: cannot execute: required file not found
```

Uh, what? @KKoukiou @M4rtinK does that ring a bell?

**Comment by KKoukiou** [comment]
> ```
> test/prepare-updates-img: line 15: scripts/makeupdates: cannot execute: required file not found
> ```
> 
> Uh, what? @KKoukiou @M4rtinK does that ring a bell?

Please ignore that ;) It's the new repository that I am still setting up.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
