### PR TITLE
Image refresh for ubuntu-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for ubuntu-stable
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by jelly** [comment]
Apparmor broke:

```
audit: type=1400 audit(1665749791.896:55): apparmor="DENIED" operation="open" class="file" profile="libvirt-d60d9bd9-dc70-4a76-80b7-2510b8a41440" name="/sys/devices/system/cpu/possible" pid=7922 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
audit: type=1400 audit(1665749797.972:61): apparmor="DENIED" operation="open" class="file" profile="libvirt-e13fdc10-5f60-49fd-a4e2-c228624db9f7" name="/sys/devices/system/cpu/possible" pid=7994 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
```

**Comment by jelly** [comment]
https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1989073

**Comment by jelly** [comment]
Seems there is a new apparmor issue:

```
audit: type=1400 audit(1665763257.372:71): apparmor="DENIED" operation="getattr" class="file" profile="libvirt-928f7de5-cf2b-4735-9a1e-0feaf61d57a1" name="/sys/bus/usb/devices/usb1" pid=6776 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
```

**Comment by jelly** [comment]
naughty: TestMachinesSettings.testDomainMemorySettings =>
                 audit: type=1400 audit(1665763257.372:71): apparmor="DENIED" operation="getattr" class="file" profile="libvirt-928f7de5-cf2b-4735-9a1e-0feaf61d57a1" name=  "/sys/bus/usb/devices/usb1" pid=6776 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
              audit: type=1400 audit(1665763257.372:72): apparmor="DENIED" operation="getattr" class="file" profile="libvirt-928f7de5-cf2b-4735-9a1e-0feaf61d57a1" name=  "/sys/bus/usb/devices/1-0:1.0" pid=6776 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0

naughty: TestMachinesNetworks.testNetworkAddStaticDCHPHosts
```
audit: type=1400 audit(1665763333.088:67): apparmor="DENIED" operation="open" class="file" profile="virt-aa-helper" name="/var/lib/cockpittest/vm_one/mydisk3" pid=9618 co  mm="virt-aa-helper" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

Can't reproduce it locally with:

```
TEST_OS=ubuntu-stable ./test/common/run-tests -vt TestMachinesSettings.testDomainMemorySettings
```

**Comment by jelly** [comment]
machines should succeed now after the naughty pattern was fixed.

**Review by marusak — APPROVED** [review]
Thank you!

**Pull request merged**
