### PR TITLE
images: Fix cleanup of packages on Debian images

### PR DESCRIPTION
**Pull request by martinpitt**
Add missing verb to apt invocation for cleaning up unnecessary packages.
In particular, this gets rid again of cloud-init, which causes frequent
boot failures and long boot times in our offline setup.

---

The [previous image build log](https://209.132.184.41:8493/logs/image-refresh-512-20200210-021818/log) shows the problem:
```
+ eatmydata apt-get -y -o Dpkg::Options::=--force-confold --auto-remove lxd
E: Sense auto is not understood, try true or false.
+ true
```
So these were silently ignored, and cloud-init crept back into the packages.

 * [x] image-refresh debian-stable
 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-1804
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-532-20200216-213434/

**Comment by martinpitt** [comment]
I noticed that when trying to run `image-prepare debian-stable` locally, which keeps failing with

    dpkg: error: dpkg frontend lock is locked by another process

because cloud-init mucks around with the system still. Our tests assume that they have full control over the VM as soon as ssh is ready.

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/bots/commits/image-refresh-debian-stable-20200216-215858

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-532-20200216-215858/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/bots/commits/image-refresh-debian-testing-20200216-222929

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-532-20200216-222929/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1804 done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-1804-20200216-225252

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-532-20200216-225252/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-stable-20200216-232121

**Comment by martinpitt** [comment]
The debian-testing refresh has an [awful lot of xftables crashes](https://logs.cockpit-project.org/logs/pull-532-20200217-072121-d7ba954f-debian-testing-cockpit-project-cockpit), they were already detected in the automatic image refresh in PR #518. This still needs handling.

**Comment by martinpitt** [comment]
The main effect of this is that [debian-stable](https://logs.cockpit-project.org/logs/pull-532-20200217-071313-d7ba954f-debian-stable-cockpit-project-cockpit/log.html) now has zero retries! With the current image there usually plenty ([example with 30 boot failures](https://logs.cockpit-project.org/logs/pull-13549-20200216-202121-e7fbd154-debian-stable/log.html))

**Pull request merged**
