### PR TITLE
Image refresh for centos-10

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-10
 * [x] image-refresh centos-10
 * [x] Stop paying attention to random SELinux messages https://github.com/cockpit-project/cockpit/issues/20542

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240614-225430

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-7200affa-20240614-223733/log.html

**Comment by martinpitt** [comment]
Lots of SELinux fallout. Let's stop this, see https://github.com/cockpit-project/cockpit/issues/20542

**Comment by martinpitt** [comment]
This is now much more manageable, but this still [breaks TLS cert auth](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6502-3bdf1517-20240616-083928-centos-10-networking-cockpit-project-cockpit/log.html#57-2)

**Comment by martinpitt** [comment]
This is genuinely broken. I reported https://issues.redhat.com/browse/RHEL-43259 and naughty tracker https://github.com/cockpit-project/bots/issues/6518 , I'll push it here.

**Review by jelly — APPROVED** [review]

**Pull request merged**
