### PR TITLE
Image refresh for fedora-39

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-39
 * [x] image-refresh fedora-39
 * [x] https://github.com/cockpit-project/cockpit/pull/19462

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-39-20231004-225454.log

**Comment by martinpitt** [comment]
[testNetworkingPage failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5346-20231005-034834-e55095d5-fedora-39-networking-cockpit-project-cockpit/log.html#20-2). The arch refresh in #5345 already had the same issue. It was likely fixed by https://github.com/cockpit-project/cockpit/pull/19428 , so retrying.

**Comment by martinpitt** [comment]
@KKoukiou Without having checked this further, smells like https://github.com/rhinstaller/anaconda/pull/5231 needs to be applied to teh f39 branch?

**Comment by martinpitt** [comment]
... and testNetworking still fails, back to needswork.

**Comment by martinpitt** [comment]
f-39-boot was removed in #5357, so this is down to the firewall regression

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
