### PR TITLE
Image refresh for fedora-36

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-36
 * [x] image-refresh fedora-36

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-36-20230102-225555.log

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20230103-013126

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-36-20230103-013131.log

**Comment by cockpituous** [comment]
Completed. Log: Error accessing /repos/cockpit-project/bots/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value":4233,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}

**Comment by martinpitt** [comment]
Ah, the cockpit-ws package updated to a new font on the image, so all the pixels for c-machines, podman etc. need updating. There are [two](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4233-20230102-225629-97bdf4f0-fedora-36-devel-cockpit-project-cockpit/log.html#205) [other](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4233-20230102-225631-97bdf4f0-fedora-36-cockpit-project-cockpit/log.html) failures which are likely flakes, though. Retrying.

**Comment by marusak** [comment]
`fedora-36@cockpit-project/cockpit-podman` succeeded in https://github.com/cockpit-project/cockpit-podman/pull/1173

**Review by KKoukiou — APPROVED** [review]
Assuming cockpit repo tests also green

**Pull request merged**
