### PR TITLE
images: Update rhel-8-2 to z-stream

### LINKED ISSUE #797: Image refresh for rhel-8-2
Image refresh for rhel-8-2
 * [ ] FAIL: image-refresh rhel-8-2

### PR DESCRIPTION
**Pull request by marusak**
Fixes #797

 * [x] image-refresh rhel-8-2

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-799-20200427-104040/

**Comment by cockpituous** [comment]
image-refresh rhel-8-2 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-2-20200427-111111

**Comment by martinpitt** [comment]
[boot failure in vmware lorax test](https://logs.cockpit-project.org/logs/pull-799-20200427-124049-b1a5617b-rhel-8-2-vmware-weldr-lorax-rhel8-branch/log.html), retrying

**Comment by marusak** [comment]
Had to rebase due to conflict, so once more

**Pull request merged**
