### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing
 * [x] update https://bugs.debian.org/1032990 with a proper reproducer, and fix/workaround if possible (like fixing subuid range)

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-testing-20230313-163939.log

**Comment by jelly** [comment]
```
Copying blob sha256:d2421964bad195c959ba147ad21626ccddc73a4f2638664ad1c07bd9df48a675
time="2023-03-13T16:42:03Z" level=error msg="While applying layer: ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 65534:65534 for /home): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /home: invalid argument exit status 1"
Error: payload does not match any of the supported image formats:
 * oci: initializing source oci:/var/tmp/podman1382592762:: open /var/tmp/podman1382592762/index.json: not a directory
 * oci-archive: loading index: open /var/tmp/oci2507371789/index.json: no such file or directory
 * docker-archive: writing blob: adding layer with blob "sha256:d2421964bad195c959ba147ad21626ccddc73a4f2638664ad1c07bd9df48a675": ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 65534:65534 for /home): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /home: invalid argument exit status 1
 * dir: open /var/tmp/podman1382592762/manifest.json: not a directory
Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2201', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-1191', 'set -e;', '/var/tmp/vm.install']' returned non-zero exit status 125.
```

Podman is still really bork, this needs a proper bug report or finding an existing one.

**Comment by jelly** [comment]
`# testSocket (__main__.TestConnection.testSocket)` => known curl naughty https://github.com/cockpit-project/bots/issues/4468

**Comment by jelly** [comment]
```
root@debian:~# podman save quay.io/libpod/busybox | sudo -i -u admin podman load
ERRO[0000] cannot find UID/GID for user admin: cannot read subids - check rootless mode in man pages.
WARN[0000] Using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding sub*ids if not using a network user
Getting image source signatures
Copying blob d2421964bad1 done
ERRO[0000] While applying layer: ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 65534:65534 for /home): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /home: invalid argument exit status 1
Error: payload does not match any of the supported image formats:
 * oci: initializing source oci:/var/tmp/podman2255309755:: open /var/tmp/podman2255309755/index.json: not a directory
 * oci-archive: loading index: open /var/tmp/oci2122902342/index.json: no such file or directory
 * docker-archive: writing blob: adding layer with blob "sha256:d2421964bad195c959ba147ad21626ccddc73a4f2638664ad1c07bd9df48a675": ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 65534:65534 for /home): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /home: invalid argument exit status 1
 * dir: open /var/tmp/podman2255309755/manifest.json: not a directory
```

```
admin@debian:~$ cat /etc/subgid
debian:165536:65536
admin:100000:65536
admin@debian:~$ cat /etc/subuid
debian:165536:65536
admin:100000:65536
admin@debian:~$ id admin
uid=1002(admin) gid=1003(admin) groups=1003(admin),27(sudo)
````

**Comment by jelly** [comment]
Old image also already had the debian user:

```
ii  dpkg           1.21.20      amd64        Debian package management system
root@debian:~# cat /etc/subuid
debian:165536:65536
admin:100000:65536
root@debian:~# cat /etc/subgid
debian:165536:65536
admin:100000:65536
```

**Comment by skobyda** [comment]
So my guess is that podman cannot use users since its uid and gid mapping is limited in size

**Comment by martinpitt** [comment]
@skobyda : This feels too broken to handle as a naughty. Wouldn't it be better to fix /etc/sub[ug]id in the .setup?

**Comment by skobyda** [comment]
> @skobyda : This feels too broken to handle as a naughty. Wouldn't it be better to fix /etc/sub[ug]id in the .setup?

That fix doesn't work here now. 

How about just using  `podman save  $img | podman load`? [Comment](https://github.com/cockpit-project/cockpit-podman/blob/main/test/vm.install#L49) says that podman insists on user session, but why? I have just tried it locally without switching to admin user, and it seems to work fine.

**Comment by skobyda** [comment]
> How about just using `podman save $img | podman load`? [Comment](https://github.com/cockpit-project/cockpit-podman/blob/main/test/vm.install#L49) says that podman insists on user session, but why? I have just tried it locally without switching to admin user, and it seems to work fine.

oh no wait, this seems to make some tests pass and some fail, so also not ideal solution

**Comment by martinpitt** [comment]
@skobyda Not sure what you mean -- that is supposed to "copy" the system podman image to the user podman for admin. That needs a running admin logind session (hence the `enable-linger`), otherwise user podman doesn't work.

**Comment by skobyda** [comment]
@martinpitt Matej recommended that maybe we can run `sudo -i -u admin podman pull` instead of `podman save $img | sudo -i -u admin podman load` and just have the same image twice (on system and session)? Can we do that? vm.install runs without network right, can we maybe prepare it beforehand?

**Comment by jelly** [comment]
> @skobyda : You can do the `podman pull` in the .setup (here in bots), but not in cockpit-podman's tests anywhere, as that is (and really should stay) offline. But I'm not sure how that even helps? I remember some error message about "not enough UIDs available" or so, and the cockpit failed tests are certainly unrelated to `admin`'s container images.

Indeed, the cockpit tests which start a user container will still fail I suppose.

**Comment by KKoukiou** [comment]
Trying to update this image - as this is quite old and maybe things got fixed in the meantime.

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20230327-110040

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-testing-20230327-110000.log

**Comment by martinpitt** [comment]
@KKoukiou Sorry, I think I cleaned up that built image, as it was just floating around without being attached to a PR. This occasionally happens.

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20230329-140134

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-testing-20230329-140101.log

**Comment by martinpitt** [comment]
Still "potentially insufficient UIDs or GIDs available in user namespace (requested 65534:65534 for /home): Check /etc/subuid and /etc/subgid if configured locally". I still can't quite believe that this wouldn't be related to https://bugzilla.redhat.com/show_bug.cgi?id=2144558 ..

**Comment by marusak** [comment]
The reproducer is as simple as:
```
$ podman pull debian
Resolved "debian" as an alias (/etc/containers/registries.conf.d/shortnames.conf)
Trying to pull docker.io/library/debian:latest...
Getting image source signatures
Copying blob 3e440a704568 done  
ERRO[0004] While applying layer: ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/gshadow): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /etc/gshadow: invalid argument exit status 1 
Error: copying system image from manifest list: writing blob: adding layer with blob "sha256:3e440a7045683e27f8e2fa04000e0e078d8dfac0c971358ae0f8c65c13321c8e": ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/gshadow): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /etc/gshadow: invalid argument exit status 1

```
$ whoami
admin

```

```

**Comment by martinpitt** [comment]
The difference between the images is in /etc/nsswitch.conf. The new image / new sssd adds this:

    subid:  sss

which is either bogus (missing "files") or sssd can't actually do this and relay that information. Commenting it out or adding "files" makes things work, so we have a simple workaround. I'll investigate this a bit more on the sssd package side, then update the Debian bug and apply a workaround here.

**Comment by marusak** [comment]
Yes @martinpitt I had it just opened but could not finish it.

podman works, then doing this:

```
$ cat /etc/nsswitch.conf
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         files
group:          files
shadow:         files
gshadow:        files

hosts:          files dns myhostname mymachines
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis


admin@debian:~$ sudo apt-get install sssd-tools sssd-dbus
[sudo] password for admin: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  ldap-utils libbasicobjects0 libc-ares2 libcollection4 libdhash1 libini-config5 libipa-hbac0 libldb2 libnss-sss libpam-pwquality libpam-sss libref-array1 libsasl2-modules
  libsasl2-modules-gssapi-mit libsmbclient libsss-certmap0 libsss-idmap0 libsss-nss-idmap0 libtdb1 libtevent0 libwbclient0 python3-sss python3-systemd samba-libs sssd sssd-ad
  sssd-ad-common sssd-common sssd-ipa sssd-krb5 sssd-krb5-common sssd-ldap sssd-proxy
Suggested packages:
  libsasl2-modules-ldap libsasl2-modules-otp libsasl2-modules-sql adcli libsss-sudo
The following NEW packages will be installed:
  ldap-utils libbasicobjects0 libc-ares2 libcollection4 libdhash1 libini-config5 libipa-hbac0 libldb2 libnss-sss libpam-pwquality libpam-sss libref-array1 libsasl2-modules
  libsasl2-modules-gssapi-mit libsmbclient libsss-certmap0 libsss-idmap0 libsss-nss-idmap0 libtdb1 libtevent0 libwbclient0 python3-sss python3-systemd samba-libs sssd sssd-ad
  sssd-ad-common sssd-common sssd-dbus sssd-ipa sssd-krb5 sssd-krb5-common sssd-ldap sssd-proxy sssd-tools
0 upgraded, 35 newly installed, 0 to remove and 0 not upgraded.
Need to get 8741 kB of archives.
After this operation, 37.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://deb.debian.org/debian testing/main amd64 ldap-utils amd64 2.5.13+dfsg-5 [144 kB]
Get:2 http://deb.debian.org/debian testing/main amd64 libbasicobjects0 amd64 0.6.2-1 [6256 B]
Get:3 http://deb.debian.org/debian testing/main amd64 libc-ares2 amd64 1.18.1-2 [102 kB]
Get:4 http://deb.debian.org/debian testing/main amd64 libcollection4 amd64 0.6.2-1 [22.8 kB]
Get:5 http://deb.debian.org/debian testing/main amd64 libdhash1 amd64 0.6.2-1 [9064 B]
Get:6 http://deb.debian.org/debian testing/main amd64 libref-array1 amd64 0.6.2-1 [7692 B]
Get:7 http://deb.debian.org/debian testing/main amd64 libini-config5 amd64 0.6.2-1 [43.4 kB]
Get:8 http://deb.debian.org/debian testing/main amd64 libipa-hbac0 amd64 2.8.2-3 [12.8 kB]
Get:9 http://deb.debian.org/debian testing/main amd64 libtdb1 amd64 1.4.8-2 [44.5 kB]
Get:10 http://deb.debian.org/debian testing/main amd64 libtevent0 amd64 0.14.1-1 [37.9 kB]
Get:11 http://deb.debian.org/debian testing/main amd64 libldb2 amd64 2:2.6.1+samba4.17.6+dfsg-1 [157 kB]
Get:12 http://deb.debian.org/debian testing/main amd64 libnss-sss amd64 2.8.2-3 [25.5 kB]
Get:13 http://deb.debian.org/debian testing/main amd64 libpam-pwquality amd64 1.4.5-1+b1 [12.9 kB]
Get:14 http://deb.debian.org/debian testing/main amd64 libpam-sss amd64 2.8.2-3 [41.9 kB]
Get:15 http://deb.debian.org/debian testing/main amd64 libsasl2-modules amd64 2.1.28+dfsg-10 [66.6 kB]
Get:16 http://deb.debian.org/debian testing/main amd64 libsasl2-modules-gssapi-mit amd64 2.1.28+dfsg-10 [32.9 kB]
Get:17 http://deb.debian.org/debian testing/main amd64 libwbclient0 amd64 2:4.17.6+dfsg-1 [50.1 kB]
Get:18 http://deb.debian.org/debian testing/main amd64 samba-libs amd64 2:4.17.6+dfsg-1 [5640 kB]
Get:19 http://deb.debian.org/debian testing/main amd64 libsmbclient amd64 2:4.17.6+dfsg-1 [79.0 kB]
Get:20 http://deb.debian.org/debian testing/main amd64 libsss-idmap0 amd64 2.8.2-3 [17.2 kB]
Get:21 http://deb.debian.org/debian testing/main amd64 libsss-nss-idmap0 amd64 2.8.2-3 [24.1 kB]
Get:22 http://deb.debian.org/debian testing/main amd64 python3-sss amd64 2.8.2-3 [41.9 kB]
Get:23 http://deb.debian.org/debian testing/main amd64 python3-systemd amd64 235-1+b2 [39.3 kB]
Get:24 http://deb.debian.org/debian testing/main amd64 libsss-certmap0 amd64 2.8.2-3 [40.8 kB]
Get:25 http://deb.debian.org/debian testing/main amd64 sssd-common amd64 2.8.2-3 [1238 kB]
Get:26 http://deb.debian.org/debian testing/main amd64 sssd-ad-common amd64 2.8.2-3 [76.8 kB]
Get:27 http://deb.debian.org/debian testing/main amd64 sssd-krb5-common amd64 2.8.2-3 [81.2 kB]
Get:28 http://deb.debian.org/debian testing/main amd64 sssd-ad amd64 2.8.2-3 [133 kB]
Get:29 http://deb.debian.org/debian testing/main amd64 sssd-ipa amd64 2.8.2-3 [211 kB]                                                                                                       
Get:30 http://deb.debian.org/debian testing/main amd64 sssd-krb5 amd64 2.8.2-3 [17.8 kB]                                                                                                     
Get:31 http://deb.debian.org/debian testing/main amd64 sssd-ldap amd64 2.8.2-3 [36.0 kB]                                                                                                     
Get:32 http://deb.debian.org/debian testing/main amd64 sssd-proxy amd64 2.8.2-3 [43.7 kB]                                                                                                    
Get:33 http://deb.debian.org/debian testing/main amd64 sssd amd64 2.8.2-3 [7976 B]                                                                                                           
Get:34 http://deb.debian.org/debian testing/main amd64 sssd-dbus amd64 2.8.2-3 [102 kB]                                                                                                      
Get:35 http://deb.debian.org/debian testing/main amd64 sssd-tools amd64 2.8.2-3 [94.4 kB]                                                                                                    
Fetched 8741 kB in 8s (1123 kB/s)                                                                                                                                                            
Extracting templates from packages: 100%
Selecting previously unselected package ldap-utils.
(Reading database ... 91978 files and directories currently installed.)
Preparing to unpack .../00-ldap-utils_2.5.13+dfsg-5_amd64.deb ...
Unpacking ldap-utils (2.5.13+dfsg-5) ...
Selecting previously unselected package libbasicobjects0:amd64.
Preparing to unpack .../01-libbasicobjects0_0.6.2-1_amd64.deb ...
Unpacking libbasicobjects0:amd64 (0.6.2-1) ...
Selecting previously unselected package libc-ares2:amd64.
Preparing to unpack .../02-libc-ares2_1.18.1-2_amd64.deb ...
Unpacking libc-ares2:amd64 (1.18.1-2) ...
Selecting previously unselected package libcollection4:amd64.
Preparing to unpack .../03-libcollection4_0.6.2-1_amd64.deb ...
Unpacking libcollection4:amd64 (0.6.2-1) ...
Selecting previously unselected package libdhash1:amd64.
Preparing to unpack .../04-libdhash1_0.6.2-1_amd64.deb ...
Unpacking libdhash1:amd64 (0.6.2-1) ...
Selecting previously unselected package libref-array1:amd64.
Preparing to unpack .../05-libref-array1_0.6.2-1_amd64.deb ...
Unpacking libref-array1:amd64 (0.6.2-1) ...
Selecting previously unselected package libini-config5:amd64.
Preparing to unpack .../06-libini-config5_0.6.2-1_amd64.deb ...
Unpacking libini-config5:amd64 (0.6.2-1) ...
Selecting previously unselected package libipa-hbac0.
Preparing to unpack .../07-libipa-hbac0_2.8.2-3_amd64.deb ...
Unpacking libipa-hbac0 (2.8.2-3) ...
Selecting previously unselected package libtdb1:amd64.
Preparing to unpack .../08-libtdb1_1.4.8-2_amd64.deb ...
Unpacking libtdb1:amd64 (1.4.8-2) ...
Selecting previously unselected package libtevent0:amd64.
Preparing to unpack .../09-libtevent0_0.14.1-1_amd64.deb ...
Unpacking libtevent0:amd64 (0.14.1-1) ...
Selecting previously unselected package libldb2:amd64.
Preparing to unpack .../10-libldb2_2%3a2.6.1+samba4.17.6+dfsg-1_amd64.deb ...
Unpacking libldb2:amd64 (2:2.6.1+samba4.17.6+dfsg-1) ...
Selecting previously unselected package libnss-sss:amd64.
Preparing to unpack .../11-libnss-sss_2.8.2-3_amd64.deb ...
Unpacking libnss-sss:amd64 (2.8.2-3) ...
Selecting previously unselected package libpam-pwquality:amd64.
Preparing to unpack .../12-libpam-pwquality_1.4.5-1+b1_amd64.deb ...
Unpacking libpam-pwquality:amd64 (1.4.5-1+b1) ...
Selecting previously unselected package libpam-sss:amd64.
Preparing to unpack .../13-libpam-sss_2.8.2-3_amd64.deb ...
Unpacking libpam-sss:amd64 (2.8.2-3) ...
Selecting previously unselected package libsasl2-modules:amd64.
Preparing to unpack .../14-libsasl2-modules_2.1.28+dfsg-10_amd64.deb ...
Unpacking libsasl2-modules:amd64 (2.1.28+dfsg-10) ...
Selecting previously unselected package libsasl2-modules-gssapi-mit:amd64.
Preparing to unpack .../15-libsasl2-modules-gssapi-mit_2.1.28+dfsg-10_amd64.deb ...
Unpacking libsasl2-modules-gssapi-mit:amd64 (2.1.28+dfsg-10) ...
Selecting previously unselected package libwbclient0:amd64.
Preparing to unpack .../16-libwbclient0_2%3a4.17.6+dfsg-1_amd64.deb ...
Unpacking libwbclient0:amd64 (2:4.17.6+dfsg-1) ...
Selecting previously unselected package samba-libs:amd64.
Preparing to unpack .../17-samba-libs_2%3a4.17.6+dfsg-1_amd64.deb ...
Unpacking samba-libs:amd64 (2:4.17.6+dfsg-1) ...
Selecting previously unselected package libsmbclient:amd64.
Preparing to unpack .../18-libsmbclient_2%3a4.17.6+dfsg-1_amd64.deb ...
Unpacking libsmbclient:amd64 (2:4.17.6+dfsg-1) ...
Selecting previously unselected package libsss-idmap0.
Preparing to unpack .../19-libsss-idmap0_2.8.2-3_amd64.deb ...
Unpacking libsss-idmap0 (2.8.2-3) ...
Selecting previously unselected package libsss-nss-idmap0.
Preparing to unpack .../20-libsss-nss-idmap0_2.8.2-3_amd64.deb ...
Unpacking libsss-nss-idmap0 (2.8.2-3) ...
Selecting previously unselected package python3-sss.
Preparing to unpack .../21-python3-sss_2.8.2-3_amd64.deb ...
Unpacking python3-sss (2.8.2-3) ...
Selecting previously unselected package python3-systemd.
Preparing to unpack .../22-python3-systemd_235-1+b2_amd64.deb ...
Unpacking python3-systemd (235-1+b2) ...
Selecting previously unselected package libsss-certmap0.
Preparing to unpack .../23-libsss-certmap0_2.8.2-3_amd64.deb ...
Unpacking libsss-certmap0 (2.8.2-3) ...
Selecting previously unselected package sssd-common.
Preparing to unpack .../24-sssd-common_2.8.2-3_amd64.deb ...
Unpacking sssd-common (2.8.2-3) ...
Selecting previously unselected package sssd-ad-common.
Preparing to unpack .../25-sssd-ad-common_2.8.2-3_amd64.deb ...
Unpacking sssd-ad-common (2.8.2-3) ...
Selecting previously unselected package sssd-krb5-common.
Preparing to unpack .../26-sssd-krb5-common_2.8.2-3_amd64.deb ...
Unpacking sssd-krb5-common (2.8.2-3) ...
Selecting previously unselected package sssd-ad.
Preparing to unpack .../27-sssd-ad_2.8.2-3_amd64.deb ...
Unpacking sssd-ad (2.8.2-3) ...
Selecting previously unselected package sssd-ipa.
Preparing to unpack .../28-sssd-ipa_2.8.2-3_amd64.deb ...
Unpacking sssd-ipa (2.8.2-3) ...
Selecting previously unselected package sssd-krb5.
Preparing to unpack .../29-sssd-krb5_2.8.2-3_amd64.deb ...
Unpacking sssd-krb5 (2.8.2-3) ...
Selecting previously unselected package sssd-ldap.
Preparing to unpack .../30-sssd-ldap_2.8.2-3_amd64.deb ...
Unpacking sssd-ldap (2.8.2-3) ...
Selecting previously unselected package sssd-proxy.
Preparing to unpack .../31-sssd-proxy_2.8.2-3_amd64.deb ...
Unpacking sssd-proxy (2.8.2-3) ...
Selecting previously unselected package sssd.
Preparing to unpack .../32-sssd_2.8.2-3_amd64.deb ...
Unpacking sssd (2.8.2-3) ...
Selecting previously unselected package sssd-dbus.
Preparing to unpack .../33-sssd-dbus_2.8.2-3_amd64.deb ...
Unpacking sssd-dbus (2.8.2-3) ...
Selecting previously unselected package sssd-tools.
Preparing to unpack .../34-sssd-tools_2.8.2-3_amd64.deb ...
Unpacking sssd-tools (2.8.2-3) ...
Setting up libsss-idmap0 (2.8.2-3) ...
Setting up libbasicobjects0:amd64 (0.6.2-1) ...
Setting up libtdb1:amd64 (1.4.8-2) ...
Setting up libsasl2-modules:amd64 (2.1.28+dfsg-10) ...
Setting up libpam-pwquality:amd64 (1.4.5-1+b1) ...
Setting up libc-ares2:amd64 (1.18.1-2) ...
Setting up ldap-utils (2.5.13+dfsg-5) ...
Setting up libwbclient0:amd64 (2:4.17.6+dfsg-1) ...
Setting up libsss-certmap0 (2.8.2-3) ...
Setting up libdhash1:amd64 (0.6.2-1) ...
Setting up libtevent0:amd64 (0.14.1-1) ...
Setting up libcollection4:amd64 (0.6.2-1) ...
Setting up libipa-hbac0 (2.8.2-3) ...
Setting up libref-array1:amd64 (0.6.2-1) ...
Setting up libldb2:amd64 (2:2.6.1+samba4.17.6+dfsg-1) ...
Setting up libsss-nss-idmap0 (2.8.2-3) ...
Setting up libsasl2-modules-gssapi-mit:amd64 (2.1.28+dfsg-10) ...
Setting up libpam-sss:amd64 (2.8.2-3) ...
Setting up python3-systemd (235-1+b2) ...
Setting up libnss-sss:amd64 (2.8.2-3) ...
Setting up libini-config5:amd64 (0.6.2-1) ...
Setting up samba-libs:amd64 (2:4.17.6+dfsg-1) ...
Setting up python3-sss (2.8.2-3) ...
Setting up libsmbclient:amd64 (2:4.17.6+dfsg-1) ...
Setting up sssd-common (2.8.2-3) ...
Creating SSSD system user & group...
adduser: Warning: The home directory `/var/lib/sss' does not belong to the user you are currently creating.
Warning: found usr.sbin.sssd in /etc/apparmor.d/force-complain, forcing complain mode
Warning from /etc/apparmor.d/usr.sbin.sssd (/etc/apparmor.d/usr.sbin.sssd line 60): Caching disabled for: 'usr.sbin.sssd' due to force complain
Created symlink /etc/systemd/system/sssd.service.wants/sssd-autofs.socket → /lib/systemd/system/sssd-autofs.socket.
Created symlink /etc/systemd/system/sssd.service.wants/sssd-nss.socket → /lib/systemd/system/sssd-nss.socket.
Created symlink /etc/systemd/system/sssd.service.wants/sssd-pam-priv.socket → /lib/systemd/system/sssd-pam-priv.socket.
Created symlink /etc/systemd/system/sssd.service.wants/sssd-pam.socket → /lib/systemd/system/sssd-pam.socket.
Created symlink /etc/systemd/system/sssd.service.wants/sssd-ssh.socket → /lib/systemd/system/sssd-ssh.socket.
Created symlink /etc/systemd/system/sssd.service.wants/sssd-sudo.socket → /lib/systemd/system/sssd-sudo.socket.
Created symlink /etc/systemd/system/multi-user.target.wants/sssd.service → /lib/systemd/system/sssd.service.
sssd-autofs.service is a disabled or a static unit, not starting it.
sssd-nss.service is a disabled or a static unit, not starting it.
sssd-pam.service is a disabled or a static unit, not starting it.
sssd-ssh.service is a disabled or a static unit, not starting it.
sssd-sudo.service is a disabled or a static unit, not starting it.
Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 145.
Setting up sssd-proxy (2.8.2-3) ...
Setting up sssd-dbus (2.8.2-3) ...
sssd-ifp.service is a disabled or a static unit, not starting it.
Setting up sssd-ad-common (2.8.2-3) ...
Created symlink /etc/systemd/system/sssd.service.wants/sssd-pac.socket → /lib/systemd/system/sssd-pac.socket.
sssd-pac.service is a disabled or a static unit, not starting it.
Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 145.
Setting up sssd-krb5-common (2.8.2-3) ...
Setting up sssd-krb5 (2.8.2-3) ...
Setting up sssd-ldap (2.8.2-3) ...
Setting up sssd-ad (2.8.2-3) ...
Setting up sssd-tools (2.8.2-3) ...
Setting up sssd-ipa (2.8.2-3) ...
Setting up sssd (2.8.2-3) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for dbus (1.14.6-1) ...
Processing triggers for libc-bin (2.36-8) ...


admin@debian:~$ cat /etc/nsswitch.conf
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         files sss
group:          files sss
shadow:         files sss
gshadow:        files

hosts:          files dns myhostname mymachines
networks:       files

protocols:      db files
services:       db files sss
ethers:         db files
rpc:            db files

netgroup:       nis sss
automount:  sss
subid:  sss

```

Now podman does not work.

**Comment by martinpitt** [comment]
I reassigned https://bugs.debian.org/1032990 to the root cause (sssd-common) with some more analysis, made it release-critical, and added a workaround here.

**Comment by martinpitt** [comment]
podman is fine now, but there is a new [TestConnection.testSocket regression](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4515-20230404-190048-b801c784-debian-testing-cockpit-project-cockpit/log.html#24-2). This feels like a curl regression -- it's supposed to connect to the unix port, not TCP port 443.

     curl (7.87.0-2 -> 7.88.1-7)

This already failed [in the old original retry](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4515-20230313-164016-8fedc6a3-debian-testing-cockpit-project-cockpit/log.html) from three weeks ago, where curl was already updated. This is #4468, so I'll copy the naughty. But I'll also file a Debian bug, as the next release is close and this shouldn't be released.

**Review by marusak — APPROVED** [review]
Thank you!

**Pull request merged**
