### PR TITLE
images: test anaconda payload updates

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by allisonkarlitskaya** [comment]
If someone can furnish me with a copy of `fedora-rawhide-anaconda-payload-b9cab41ceb8b52f530d090fa62aa34e8e00f093c078f388244eb9bd9cec4d371.tar.gz` then I'd be able to upload it to the server again....

**Comment by martinpitt** [comment]
So that still looks like a boot failure with the previous image/payload?

**Comment by KKoukiou** [comment]
> So that still looks like a boot failure with the previous image/payload?

Indeed - so the payload update was not the reason  for our broken CI. Debugging this now.

**Comment by martinpitt** [comment]
@KKoukiou what's the current status of that? I had the impression that the thing which broke the test was the recent firefox update, which you pinned back. Should this work now?

**Comment by KKoukiou** [comment]
> @KKoukiou what's the current status of that? I had the impression that the thing which broke the test was the recent firefox update, which you pinned back. Should this work now?


Yes -  but currently the anaconda test suite is extremely flaky (since end last week). I am waiting for some reviews on test improvements and I will re-run the tests here later today once the anaconda test fix PRs are in.

**Review by martinpitt — APPROVED** [review]
Cheers!

**Pull request merged**
