### PR TITLE
Image refresh for centos-9-stream

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-9-stream
 * [x] image-refresh centos-9-stream

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20240529-225509

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-9-stream-9f412c93-20240529-223744/log.html

**Comment by martinpitt** [comment]
@jkozol I retried this once already, and this [testCreateAndDeleteBlueprint failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6443-c359eb35-20240602-151746-centos-9-stream-osbuild-cockpit-composer/log.html#3-2) seems stable. Recent composer PRs went green, so this does smell like a change in the image triggered this. The test expects some `li[data-testid='openssh-server']`, but the [screenshot](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6443-c359eb35-20240602-151746-centos-9-stream-osbuild-cockpit-composer/TestBlueprintWizard-testCreateAndDeleteBlueprint-centos-9-stream-127.0.0.2-2401-FAIL.png) shows nothing related to packages. Any idea?

**Comment by martinpitt** [comment]
@jkozol gentle reminder

**Comment by martinpitt** [comment]
This has been known for a long time already, https://github.com/osbuild/cockpit-composer/issues/1995 and tracked in https://github.com/cockpit-project/bots/issues/6180

**Pull request merged**
