### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos
 * [x] https://github.com/cockpit-project/cockpit/pull/17018

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-k7std.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-2950-20220217-021515/

**Comment by cockpituous** [comment]
image-refresh fedora-coreos done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-coreos-20220217-022424

**Comment by martinpitt** [comment]
Whoops, no mount any more in container?
```
+ /bin/mount --bind /host/etc/cockpit /etc/cockpit
/container/atomic-install: line 67: /bin/mount: No such file or directory
Error: `/proc/self/exe run --rm --privileged -v /:/host -e IMAGE=localhost/cockpit/ws:latest localhost/cockpit/ws:latest /container/atomic-install localhost/cockpit/ws:latest` failed: exit status 127
```

**Comment by martinpitt** [comment]
I filed https://github.com/cockpit-project/cockpit/pull/17018 to fix the container. Once we published a new one, we need to rebuild this.

**Comment by martinpitt** [comment]
cockpit/ws container is fixed, let's rebuild.

**Pull request closed without merging**
