### PR TITLE
Image refresh for fedora-eln-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-eln-boot
 * [ ] image-refresh fedora-eln-boot

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-eln-boot done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-eln-boot-20240122-224013

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-eln-boot-20240122-224040.log

**Comment by martinpitt** [comment]
Commit 76e5c7ffa33276f5e622cc5df430bacbafc22474 disabled that anaconda test, so there's currently no test left for the ELN image. Somehow this refresh [broke anaconda completely](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5823-20240123-140024-d662a2b3-fedora-eln-boot-rhinstaller-anaconda-webui/log.html) - that still needs to be investigated.

**Comment by KKoukiou** [comment]
There is a coredump:


```
Jan 23 14:16:29 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com systemd-coredump[9465]: Process 9318 (gnome-kiosk) of user 0 dumped core.
                                                                                                
                                                                                                Module libspa-journal.so from rpm pipewire-1.0.1-1.eln134.x86_64
                                                                                                Module libspa-support.so from rpm pipewire-1.0.1-1.eln134.x86_64
                                                                                                Module libpciaccess.so.0 from rpm libpciaccess-0.16-9.eln133.x86_64
                                                                                                Module libdrm_intel.so.1 from rpm libdrm-2.4.120-1.eln134.x86_64
                                                                                                Module libdrm_nouveau.so.2 from rpm libdrm-2.4.120-1.eln134.x86_64
                                                                                                Module libelf.so.1 from rpm elfutils-0.190-4.eln133.x86_64
                                                                                                Module libdrm_amdgpu.so.1 from rpm libdrm-2.4.120-1.eln134.x86_64
                                                                                                Module libdrm_radeon.so.1 from rpm libdrm-2.4.120-1.eln134.x86_64
                                                                                                Module swrast_dri.so from rpm mesa-24.0.0~rc2-2.eln134.x86_64
                                                                                                Module libtinfo.so.6 from rpm ncurses-6.4-9.20240113.eln134.x86_64
                                                                                                Module libedit.so.0 from rpm libedit-3.1-48.20230828cvs.eln133.x86_64
                                                                                                Module libXxf86vm.so.1 from rpm libXxf86vm-1.1.5-4.eln133.x86_64
                                                                                                Module libxcb-glx.so.0 from rpm libxcb-1.16-2.eln133.x86_64
                                                                                                Module libGLX_mesa.so.0 from rpm mesa-24.0.0~rc2-2.eln134.x86_64
                                                                                                Module libxshmfence.so.1 from rpm libxshmfence-1.3.2-1.eln133.x86_64
                                                                                                Module libxcb-sync.so.1 from rpm libxcb-1.16-2.eln133.x86_64
                                                                                                Module libxcb-present.so.0 from rpm libxcb-1.16-2.eln133.x86_64
                                                                                                Module libxcb-dri3.so.0 from rpm libxcb-1.16-2.eln133.x86_64
                                                                                                Module libwayland-client.so.0 from rpm wayland-1.22.0-2.eln133.x86_64
                                                                                                Module libxcb-xfixes.so.0 from rpm libxcb-1.16-2.eln133.x86_64
                                                                                                Module libxcb-dri2.so.0 from rpm libxcb-1.16-2.eln133.x86_64
                                                                                                Module libglapi.so.0 from rpm mesa-24.0.0~rc2-2.eln134.x86_64
                                                                                                Module libEGL_mesa.so.0 from rpm mesa-24.0.0~rc2-2.eln134.x86_64
                                                                                                Module libdconfsettings.so from rpm dconf-0.40.0-9.eln133.x86_64
                                                                                                Module libbrotlicommon.so.1 from rpm brotli-1.1.0-1.eln133.x86_64
                                                                                                Module libogg.so.0 from rpm libogg-1.3.5-6.eln133.x86_64
                                                                                                Module libvorbis.so.0 from rpm libvorbis-1.3.7-8.eln133.x86_64
                                                                                                Module libdatrie.so.1 from rpm libdatrie-0.2.13-7.eln133.x86_64
                                                                                                Module libbrotlidec.so.1 from rpm brotli-1.1.0-1.eln133.x86_64
                                                                                                Module libbz2.so.1 from rpm bzip2-1.0.8-16.eln133.x86_64
                                                                                                Module libexpat.so.1 from rpm expat-2.5.0-3.eln133.x86_64
                                                                                                Module libmtdev.so.1 from rpm mtdev-1.1.6-6.eln133.x86_64
                                                                                                Module libuuid.so.1 from rpm util-linux-2.39.3-2.eln134.x86_64
                                                                                                Module libxcb-xkb.so.1 from rpm libxcb-1.16-2.eln133.x86_64
                                                                                                Module libxcb-util.so.1 from rpm xcb-util-0.4.1-3.eln133.x86_64
                                                                                                Module libltdl.so.7 from rpm libtool-2.4.7-9.eln134.x86_64
                                                                                                Module libtdb.so.1 from rpm libtdb-1.4.9-1.eln133.x86_64
                                                                                                Module libvorbisfile.so.3 from rpm libvorbis-1.3.7-8.eln133.x86_64
                                                                                                Module libevdev.so.2 from rpm libevdev-1.13.1-2.eln133.x86_64
                                                                                                Module libGLX.so.0 from rpm libglvnd-1.7.0-1.eln133.x86_64
                                                                                                Module libgraphite2.so.3 from rpm graphite2-1.3.14-13.eln133.x86_64
                                                                                                Module libthai.so.0 from rpm libthai-0.1.29-6.eln133.x86_64
                                                                                                Module libxcb-shm.so.0 from rpm libxcb-1.16-2.eln133.x86_64
                                                                                                Module libxcb-render.so.0 from rpm libxcb-1.16-2.eln133.x86_64
                                                                                                Module libXrender.so.1 from rpm libXrender-0.9.11-4.eln133.x86_64
                                                                                                Module libfreetype.so.6 from rpm freetype-2.13.1-2.eln133.x86_64
                                                                                                Module libpixman-1.so.0 from rpm pixman-0.43.0-1.eln134.x86_64
                                                                                                Module libxml2.so.2 from rpm libxml2-2.12.4-1.eln134.x86_64
                                                                                                Module libjpeg.so.62 from rpm libjpeg-turbo-2.1.4-3.eln133.x86_64
                                                                                                Module libpng16.so.16 from rpm libpng-1.6.40-1.eln133.x86_64
                                                                                                Module libblkid.so.1 from rpm util-linux-2.39.3-2.eln134.x86_64
                                                                                                Module libzstd.so.1 from rpm zstd-1.5.5-4.eln133.x86_64
                                                                                                Module liblzma.so.5 from rpm xz-5.4.5-1.eln133.x86_64
                                                                                                Module liblz4.so.1 from rpm lz4-1.9.4-4.eln133.x86_64
                                                                                                Module libcap.so.2 from rpm libcap-2.69-1.eln133.x86_64
                                                                                                Module libdrm.so.2 from rpm libdrm-2.4.120-1.eln134.x86_64
                                                                                                Module libgbm.so.1 from rpm mesa-24.0.0~rc2-2.eln134.x86_64
                                                                                                Module libinput.so.10 from rpm libinput-1.25.0-1.eln134.x86_64
                                                                                                Module libSM.so.6 from rpm libSM-1.2.4-1.eln133.x86_64
                                                                                                Module libXau.so.6 from rpm libXau-1.0.11-4.eln133.x86_64
                                                                                                Module libxcb-res.so.0 from rpm libxcb-1.16-2.eln133.x86_64
                                                                                                Module libxcb-randr.so.0 from rpm libxcb-1.16-2.eln133.x86_64
                                                                                                Module libX11-xcb.so.1 from rpm libX11-1.8.7-1.eln133.x86_64
                                                                                                Module libxkbcommon-x11.so.0 from rpm libxkbcommon-1.6.0-1.eln133.x86_64
                                                                                                Module libxkbfile.so.1 from rpm libxkbfile-1.1.2-1.eln133.x86_64
                                                                                                Module libXcursor.so.1 from rpm libXcursor-1.2.1-5.eln133.x86_64
                                                                                                Module libICE.so.6 from rpm libICE-1.1.1-1.eln133.x86_64
                                                                                                Module libXinerama.so.1 from rpm libXinerama-1.1.5-4.eln133.x86_64
                                                                                                Module libpipewire-0.3.so.0 from rpm pipewire-1.0.1-1.eln134.x86_64
                                                                                                Module libgudev-1.0.so.0 from rpm libgudev-238-2.eln133.x86_64
                                                                                                Module libeis.so.1 from rpm libei-1.2.0-2.eln133.x86_64
                                                                                                Module libxkbcommon.so.0 from rpm libxkbcommon-1.6.0-1.eln133.x86_64
                                                                                                Module liblcms2.so.2 from rpm lcms2-2.16-2.eln134.x86_64
                                                                                                Module libcolord.so.2 from rpm colord-1.4.6-6.eln133.x86_64
                                                                                                Module libwacom.so.9 from rpm libwacom-2.9.0-1.eln133.x86_64
                                                                                                Module libXi.so.6 from rpm libXi-1.8.1-3.eln133.x86_64
                                                                                                Module libXtst.so.6 from rpm libXtst-1.2.4-4.eln133.x86_64
                                                                                                Module libXrandr.so.2 from rpm libXrandr-1.5.4-1.eln133.x86_64
                                                                                                Module libXcomposite.so.1 from rpm libXcomposite-0.4.6-1.eln133.x86_64
                                                                                                Module libXdamage.so.1 from rpm libXdamage-1.1.6-1.eln133.x86_64
                                                                                                Module libXfixes.so.3 from rpm libXfixes-6.0.1-1.eln133.x86_64
                                                                                                Module libXext.so.6 from rpm libXext-1.3.5-5.eln134.x86_64
                                                                                                Module libGL.so.1 from rpm libglvnd-1.7.0-1.eln133.x86_64
                                                                                                Module libEGL.so.1 from rpm libglvnd-1.7.0-1.eln133.x86_64
                                                                                                Module libwayland-server.so.0 from rpm wayland-1.22.0-2.eln133.x86_64
                                                                                                Module libgraphene-1.0.so.0 from rpm graphene-1.10.6-6.eln133.x86_64
                                                                                                Module libfontconfig.so.1 from rpm fontconfig-2.15.0-1.eln134.x86_64
                                                                                                Module libpangoft2-1.0.so.0 from rpm pango-1.51.0-1.eln133.x86_64
                                                                                                Module libpangocairo-1.0.so.0 from rpm pango-1.51.0-1.eln133.x86_64
                                                                                                Module libfribidi.so.0 from rpm fribidi-1.0.13-2.eln133.x86_64
                                                                                                Module libharfbuzz.so.0 from rpm harfbuzz-8.3.0-2.eln133.x86_64
                                                                                                Module libpango-1.0.so.0 from rpm pango-1.51.0-1.eln133.x86_64
                                                                                                Module libcairo.so.2 from rpm cairo-1.18.0-1.eln133.x86_64
                                                                                                Module libcairo-gobject.so.2 from rpm cairo-1.18.0-1.eln133.x86_64
                                                                                                Module libatk-1.0.so.0 from rpm at-spi2-core-2.50.1-1.eln134.x86_64
                                                                                                Module libmutter-mtk-14.so.0 from rpm mutter-46~alpha-2.eln134.x86_64
                                                                                                Module libmutter-cogl-pango-14.so.0 from rpm mutter-46~alpha-2.eln134.x86_64
                                                                                                Module libmutter-cogl-14.so.0 from rpm mutter-46~alpha-2.eln134.x86_64
                                                                                                Module libxcb.so.1 from rpm libxcb-1.16-2.eln133.x86_64
                                                                                                Module libGLdispatch.so.0 from rpm libglvnd-1.7.0-1.eln133.x86_64
                                                                                                Module libseccomp.so.2 from rpm libseccomp-2.5.3-6.eln133.x86_64
                                                                                                Module libudev.so.1 from rpm systemd-255.2-2.eln134.x86_64
                                                                                                Module libxkbregistry.so.0 from rpm libxkbcommon-1.6.0-1.eln133.x86_64
                                                                                                Module libgdk_pixbuf-2.0.so.0 from rpm gdk-pixbuf2-2.42.10-6.eln134.x86_64
                                                                                                Module libpcre2-8.so.0 from rpm pcre2-10.42-2.eln133.x86_64
                                                                                                Module libffi.so.8 from rpm libffi-3.4.4-5.eln134.x86_64
                                                                                                Module libselinux.so.1 from rpm libselinux-3.6-2.eln134.x86_64
                                                                                                Module libmount.so.1 from rpm util-linux-2.39.3-2.eln134.x86_64
                                                                                                Module libz.so.1 from rpm zlib-ng-2.1.6-1.eln134.x86_64
                                                                                                Module libgmodule-2.0.so.0 from rpm glib2-2.79.0-6.eln134.x86_64
                                                                                                Module libsystemd.so.0 from rpm systemd-255.2-2.eln134.x86_64
                                                                                                Module libmutter-14.so.0 from rpm mutter-46~alpha-2.eln134.x86_64
                                                                                                Module libmutter-clutter-14.so.0 from rpm mutter-46~alpha-2.eln134.x86_64
                                                                                                Module libX11.so.6 from rpm libX11-1.8.7-1.eln133.x86_64
                                                                                                Module libGLESv2.so.2 from rpm libglvnd-1.7.0-1.eln133.x86_64
                                                                                                Module libibus-1.0.so.5 from rpm ibus-1.5.29~rc2-6.eln134.x86_64
                                                                                                Module libgnome-desktop-4.so.2 from rpm gnome-desktop3-44.0-9.eln133.x86_64
                                                                                                Module libglib-2.0.so.0 from rpm glib2-2.79.0-6.eln134.x86_64
                                                                                                Module libgobject-2.0.so.0 from rpm glib2-2.79.0-6.eln134.x86_64
                                                                                                Module libgio-2.0.so.0 from rpm glib2-2.79.0-6.eln134.x86_64
                                                                                                Module gnome-kiosk from rpm gnome-kiosk-45.0-2.eln134.x86_64
                                                                                                Stack trace of thread 9318:
                                                                                                #0  0x000000000027e890 n/a (n/a + 0x0)
                                                                                                #1  0x00007ff93b3f38f0 _cogl_driver_gl_flush_framebuffer_state (libmutter-cogl-14.so.0 + 0x238f0)
                                                                                                #2  0x0000000000000002 n/a (n/a + 0x0)
                                                                                                ELF object binary architecture: AMD x86-64
Jan 23 14:16:29 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com brltty[9044]: unsupported generic resource identifier: bluetooth:
Jan 23 14:16:29 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com systemd[1]: systemd-coredump@0-9463-0.service: Deactivated successfully.
Jan 23 14:16:29 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com anaconda[9135]: anaconda: exception: running handleException
Jan 23 14:16:29 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com anaconda[9135]: anaconda: exception: Traceback (most recent call last):
                                                                                        
                                                                                          File "/sbin/anaconda", line 576, in <module>
                                                                                            anaconda.intf.run()
                                                                                        
                                                                                          File "/usr/lib64/python3.12/site-packages/pyanaconda/ui/webui/__init__.py", line 107, in run
                                                                                            self._run_webui()
                                                                                        
                                                                                          File "/usr/lib64/python3.12/site-packages/pyanaconda/ui/webui/__init__.py", line 133, in _run_webui
                                                                                            proc.wait()
                                                                                        
                                                                                          File "/usr/lib64/python3.12/subprocess.py", line 1264, in wait
                                                                                            return self._wait(timeout=timeout)
                                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                                                        
                                                                                          File "/usr/lib64/python3.12/subprocess.py", line 2046, in _wait
                                                                                            (pid, sts) = self._try_wait(0)
                                                                                                         ^^^^^^^^^^^^^^^^^
                                                                                        
                                                                                          File "/usr/lib64/python3.12/subprocess.py", line 2004, in _try_wait
                                                                                            (pid, sts) = os.waitpid(self.pid, wait_flags)
                                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                                                        
                                                                                          File "/usr/lib64/python3.12/site-packages/pyanaconda/core/process_watchers.py", line 117, in _sigchld_handler
                                                                                            cls._raise_exit_error(exit_statuses)
                                                                                        
                                                                                          File "/usr/lib64/python3.12/site-packages/pyanaconda/core/process_watchers.py", line 81, in _raise_exit_error
                                                                                            raise ExitError(", ".join(exn_message))
                                                                                        
                                                                                        pyanaconda.errors.ExitError: gnome-kiosk exited on signal 11
```

This needs to be reported. I will do it, probably not today.

**Comment by martinpitt** [comment]
image-download: image-download: couldn't find file anywhere: fedora-eln-814b80687c7c1e43fc012e5038fd4e7828b798c4525f71a4624d06c0a136dae7.qcow2

This needs a rebase, pushing.

**Comment by martinpitt** [comment]
@KKoukiou does this ring a bell?
```
Last metadata expiration check: 0:00:01 ago on Tue 06 Feb 2024 03:26:46 PM EST.
No package pykickstart available.
```

**Comment by KKoukiou** [comment]
> @KKoukiou does this ring a bell?
> 
> ```
> Last metadata expiration check: 0:00:01 ago on Tue 06 Feb 2024 03:26:46 PM EST.
> No package pykickstart available.
> ```

I added this yesterday in the extra packages to install. I think we just need python3-kickstart. I will revert anyhow when https://github.com/cockpit-project/bots/pull/5860 is merged.

**Comment by martinpitt** [comment]
Since there's no current interest in these images, I disabled their refresh in #6002

**Pull request closed without merging**
