### PR TITLE
Add additional machines dependencies in the Arch image

### PR DESCRIPTION
**Pull request by jelly**
The image was missing edk2 firmware for qemu and requires networkmanager
to be running for certain machines tests.

 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-2525-20211015-133131/

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20211018-073232

**Comment by marusak** [comment]
@jelly How does it look like with machines? This PR is blocking arch refresh for two weeks already, which is not great. Do you think that we should test this on podman and land it, or close this and get fresh arch image and then get another refresh with these changes?

**Comment by jelly** [comment]
> @jelly How does it look like with machines? This PR is blocking arch refresh for two weeks already, which is not great. Do you think that we should test this on podman and land it, or close this and get fresh arch image and then get another refresh with these changes?

It should be fairly done, so I'll mark it as ready for review tomorrow.

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-2525-20211101-082121/

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20211101-083232

**Review by marusak — APPROVED** [review]
Thank you!
Please land once podman test is green

**Pull request merged**
