### PR TITLE
images: add gettext & desktop-file-utils in RHEL/Fedora mock

### PR DESCRIPTION
**Pull request by martinpitt**
Pull them so it is possible to build gettext translations, and to
validate desktop files

gettext was already implicitly pulled by something else, so this makes
it simply explicit.

----

 * [x] image-refresh fedora-36
 * [x] image-refresh fedora-35
 * [x] image-refresh rhel-9-0
 * [x] image-refresh rhel-8-6
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20220321-150505

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-md9t4.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3119-20220321-150505/

**Comment by cockpituous** [comment]
image-refresh fedora-35 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-35-20220321-152222

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3119-20220321-152222/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3119-20220321-154242/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3119-20220321-160606/

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20220321-163737

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3119-20220321-164141/

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20220321-170000

**Comment by martinpitt** [comment]
The [rhel-9-0 sub-man regression](https://logs.cockpit-project.org/logs/pull-3119-20220321-182531-9465bb9c-rhel-9-0-candlepin-subscription-manager/log.html) is not known issue #3050 nor #3042, but something new again:

    avc:  denied  { getattr } for  pid=21760 comm="insights-client" path="/var/lib/insights/last_stable.egg" dev="vda4" ino=58764268 scontext=system_u:system_r:insights_client_t:s0 tcontext=unconfined_u:object_r:var_lib_t:s0 tclass=file permissive=0

This doesn't seem to break the tests, so let's file a bz and naughty it. 

@ptoscano FYI

**Comment by martinpitt** [comment]
And on [rhel 8.6](https://logs.cockpit-project.org/logs/pull-3119-20220321-182518-9465bb9c-rhel-8-6-distropkg-cockpit-project-cockpit/log.html#227-2), the kvdo module is once again out of sync with the kernel. Needs another bz and naughty. *sigh*

**Comment by ptoscano** [comment]
> The [rhel-9-0 sub-man regression](https://logs.cockpit-project.org/logs/pull-3119-20220321-182531-9465bb9c-rhel-9-0-candlepin-subscription-manager/log.html) is not known issue #3050 nor #3042, but something new again:

I think it might be yet another effect of the aforementioned issues: SELinux issues with the insights-client tool. If you check both the bz's mentioned in the issues, the SELinux denial appear in both.

@mvollmer proposed recently a workaround in sub-man to disable SELinux for one specific test: https://github.com/candlepin/subscription-manager/pull/3005
Since this seems critical and annoying enough, I just merged this in. Can you please retrigger sub-man/main on rhel-9-0?

**Comment by martinpitt** [comment]
@ptoscano : Retriggered, but note that the test *only* failed on the unexpected SELinux messages. These won't go away, it will just change `permissive=0` to `1`. So we still need the naughty.

**Comment by martinpitt** [comment]
Oops, yes -- the [9.0 SELinux denial](https://logs.cockpit-project.org/logs/pull-3119-20220321-182531-9465bb9c-rhel-9-0-candlepin-subscription-manager/log.html#5) *is* issue #3042, but that was filed against 8.6. So it needs the naughty copied, I'll push that on the next round.

I filed https://bugzilla.redhat.com/show_bug.cgi?id=2066566 about missing kvdo, and added a naughty.

**Comment by martinpitt** [comment]
This is as good as it gets. composer's testOstreeCommit has been broken for months, and everything else is green at last :green_circle:

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
