### PR TITLE
naughty: add pattern for selinux denials on gssproxy breaking some NFS operations

### PR DESCRIPTION
**Pull request by KKoukiou**
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2152848
Known issue #4160

### CODE REVIEW

**Comment by KKoukiou** [comment]
Really weird, as TestStorageNfs.testNfsMountWithoutDiscovery locally fails on the rawhide image, but here not: https://cockpit-logs.us-east-1.linodeobjects.com/pull-4161-20221213-100234-86a07214-fedora-rawhide-cockpit-project-cockpit/log.html#290

I checked the image hash and it's the same one used here and locally.

**Comment by KKoukiou** [comment]
Example failure: https://artifacts.dev.testing-farm.io/dae6e9f4-7259-4530-b96d-c88edc56c91b/

**Comment by KKoukiou** [comment]
Tested locally with `./tests-policy --simple fedora-rawhide < /tmp/failure.txt` where /tmp/failure.txt is the falure from the link above

**Comment by marusak** [comment]
Just for the record, `./tests-policy` is old and unused (except for rhel-7 branch) and we should be always using  `./test-failure-policy`.

**Comment by marusak** [comment]
Oh and one more thing, when we find some regression in Cockpit and report bugzilla we add `CockpitTest` into `Whiteboard` for tracking purposes. Can you please add that to the new BZ you opened? Thanks!

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
