### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20231120-225005

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20231120-225012

**Comment by cockpituous** [comment]
Completed. Log: Error accessing /repos/cockpit-project/bots/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value":5571,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/pulls/pulls#create-a-pull-request"}

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20231120-225050.log

**Comment by martinpitt** [comment]
This is supposed to match https://github.com/cockpit-project/bots/blob/main/naughty/arch/5494-libvirt-snapshot-revert-crash-2 but doesn't. Pattern says
```
wait_js_cond(!ph_is_present("#vm-subVmTest1-snapshot-1-current")): condition did not become true
```
but log says
```
wait_js_cond(!ph_is_present("#vm-subVmTest1-snapshot-1-current")): Uncaught (in promise) Error: condition did not become true
```

I'll adjust it.

**Review by marusak — APPROVED** [review]
Danke!

**Pull request merged**
