### PR TITLE
testmap: Test fedora-34 instead of fedora-32

### PR DESCRIPTION
**Pull request by marusak**
We don't release into fedora-32 anymore, but we do to fedora-34.
Also moving `firefox` context to fedora-33 as that is our current
default OS.

### CODE REVIEW

**Comment by marusak** [comment]
I've introduced a new context `fedora-33/firefox` without going through `manual` first so I'll scan this directly.

**Review by martinpitt — DISMISSED** [review]
Thanks! (Assuming tests pass)

**Review by martinpitt — APPROVED** [review]
:tada:

**Comment by marusak** [comment]
```# enableAxe: axe is not installed, skipping```

bummer.

**Comment by marusak** [comment]
Wait, how can that happen? On F33 it should just work.

**Comment by marusak** [comment]
Sent https://github.com/cockpit-project/cockpit/pull/15497 to fix this up

**Pull request merged**
