### PR TITLE
testmap: Drop Fedora-33 cockpit-composer test

### PR DESCRIPTION
**Pull request by henrywang**
Let's use this PR to drop Fedora-33 and add Fedora-34/firefox.

### CODE REVIEW

**Comment by jkozol** [comment]
Thanks for making this change. Could you move the fedora-34/firefox test from manual to main?

**Comment by henrywang** [comment]
@jkozol Sure, just waiting for `fedora-34/firefox` test passed.

**Comment by martinpitt** [comment]
It passed, thanks! Agreed to moving f34 to main right here, to avoid losing tests.

**Comment by henrywang** [comment]
@martinpitt, Push another commit to Move fedora-34/firefox test from _manual to main.

**Review by martinpitt — APPROVED** [review]
Thanks!

**Pull request merged**
