### PR TITLE
Image refresh for fedora-39

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-39
 * [x] image-refresh fedora-39

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-39 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-39-20231228-230143

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-39-20231228-230101.log

**Comment by martinpitt** [comment]
libssh is still broken, but for a different reason. Meh..

**Comment by martinpitt** [comment]
This reproduces easily with just updating libssh-devel in our normal cockpit/tasks env, and running `./test-sshbridge  -p /ssh-bridge/ssh-config-home`. Skipping the four config* tests with `-x /ssh-bridge/ssh-config` then works okay.

I sent a PR to get along with libssh 0.10.6's stricter host name parsing: https://github.com/cockpit-project/cockpit/pull/19790

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
