### PR TITLE
Image refresh for rhel-9-5

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-5
 * [x] image-refresh rhel-9-5
 * [x] https://github.com/cockpit-project/cockpit/pull/20595

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-9-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-5-20240613-225155

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-5-9bdccd45-20240613-223716/log.html

**Comment by jelly** [comment]
```
Error: pasta failed with exit code 1:
No external routable interface for IPv4
External interface not usable

Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-metrics", line 1072, in testMemory
    admin_s.execute(f"""
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 327, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2901', '-o', 'BatchMode=yes', '-o', 'IdentitiesOnly=yes', '-o', 'PKCS11Provider=none', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=ERROR', '-l', 'admin', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-28250', '127.0.0.2', 'set -e;', "\n                podman run --rm -d --name user-mem-hog localhost/test-busybox /bin/sh -c '\n                head -c 300m /dev/zero | tail | sleep infinity'\n            ")' returned non-zero exit status 126.
```

Needs some pasta fixing

**Comment by jelly** [comment]
For this we have:
```
        # hack around https://github.com/containers/podman/issues/21896 for our offline test VMs
        if not m.execute("ip route show default").strip() and "5.0" in m.execute("podman version"):
            m.execute("nmcli con add type dummy con-name fake ifname fake0 ip4 1.2.3.4/24 gw4 1.2.3.1")
            self.addCleanup(m.execute, "nmcli con delete fake")
```

but somehow it does not work?

**Comment by martinpitt** [comment]
This has the dreaded "No external routable interface for IPv4" podman issue, we need to extend the workaround.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
