### PR TITLE
Image refresh for fedora-39

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-39
 * [x] image-refresh fedora-39

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-39 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-39-20240114-230319

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-39-20240114-230303.log

**Comment by allisonkarlitskaya** [comment]
hmm

```
Process 15359 (virtinterfaced) of user 1000 dumped core.
```

hmm

```
  libvirt-client (9.7.0-1.fc39 -> 9.7.0-2.fc39)
  libvirt-daemon-common (9.7.0-1.fc39 -> 9.7.0-2.fc39)
  libvirt-daemon-config-network (9.7.0-1.fc39 -> 9.7.0-2.fc39)
  libvirt-daemon-driver-interface (9.7.0-1.fc39 -> 9.7.0-2.fc39)
  libvirt-daemon-driver-network (9.7.0-1.fc39 -> 9.7.0-2.fc39)
  libvirt-daemon-driver-nodedev (9.7.0-1.fc39 -> 9.7.0-2.fc39)
  libvirt-daemon-driver-qemu (9.7.0-1.fc39 -> 9.7.0-2.fc39)
  libvirt-daemon-driver-storage-core (9.7.0-1.fc39 -> 9.7.0-2.fc39)
  libvirt-daemon-driver-storage-disk (9.7.0-1.fc39 -> 9.7.0-2.fc39)
  libvirt-daemon-driver-storage-iscsi (9.7.0-1.fc39 -> 9.7.0-2.fc39)
  libvirt-daemon-driver-storage-iscsi-direct (9.7.0-1.fc39 -> 9.7.0-2.fc39)
  libvirt-daemon-driver-storage-logical (9.7.0-1.fc39 -> 9.7.0-2.fc39)
  libvirt-daemon-log (9.7.0-1.fc39 -> 9.7.0-2.fc39)
  libvirt-libs (9.7.0-1.fc39 -> 9.7.0-2.fc39)
```

Looks like a candidate for a naughty, but let's see what retrying does...

**Comment by allisonkarlitskaya** [comment]
@jscotka you might want to take a look at this one, if you're just interested in the mechanics of the process.  It should be pretty straight-forward.

**Comment by jscotka** [comment]
@allisonkarlitskaya Hi Lis, sure I'll look at this issue.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
