### PR TITLE
Image refresh for rhel-7-9

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-7-9
 * [x] image-refresh rhel-7-9

### CODE REVIEW

**Comment by marusak** [comment]
tests are stuck indefinitely after 17 tests :man_shrugging: needs work

**Comment by martinpitt** [comment]
I looked at the current log, and it crashes indeed:
```
cockpit-tasks-3[2015068]: INFO:root:Consuming message with command: ./s3-streamer --repo cockpit-project/bots --test-name pull-3487-20220623-114834 --github-context rhel-7-9@cockpit-project/cockpit/rhel-7.9 --revision 258f52114bd18a530747261ada2b78e136ed3eaa -- /bin/sh -c "PRIORITY=0005 ./make-checkout --verbose --repo=cockpit-project/cockpit rhel-7.9 && cd make-checkout-workdir && TEST_OS=rhel-7-9 BASE_BRANCH=rhel-7.9 COCKPIT_BOTS_REF=258f52114bd18a530747261ada2b78e136ed3eaa ../tests-invoke --pull-number 3487 --revision 258f52114bd18a530747261ada2b78e136ed3eaa --repo cockpit-project/bots"
podman[2014657]: INFO:root:Consuming message with command: ./s3-streamer --repo cockpit-project/bots --test-name pull-3487-20220623-114834 --github-context rhel-7-9@cockpit-project/cockpit/rhel-7.9 --revision 258f52114bd18a530747261ada2b78e136ed3eaa -- /bin/sh -c "PRIORITY=0005 ./make-checkout --verbose --repo=cockpit-project/cockpit rhel-7.9 && cd make-checkout-workdir && TEST_OS=rhel-7-9 BASE_BRANCH=rhel-7.9 COCKPIT_BOTS_REF=258f52114bd18a530747261ada2b78e136ed3eaa ../tests-invoke --pull-number 3487 --revision 258f52114bd18a530747261ada2b78e136ed3eaa --repo cockpit-project/bots"
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:GitHub repo cockpit-project/bots context rhel-7-9@cockpit-project/cockpit/rhel-7.9 link https://cockpit-logs.us-east-1.linodeobjects.com/pull-3487-20220623-114834-258f5211-rhel-7-9-cockpit-project-cockpit-rhel-7.9/log.html
podman[2014657]: DEBUG:s3-streamer:GitHub repo cockpit-project/bots context rhel-7-9@cockpit-project/cockpit/rhel-7.9 link https://cockpit-logs.us-east-1.linodeobjects.com/pull-3487-20220623-114834-258f5211-rhel-7-9-cockpit-project-cockpit-rhel-7.9/log.html
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:Uploading attachment log.html
podman[2014657]: DEBUG:s3-streamer:Uploading attachment log.html
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:POST statuses/258f52114bd18a530747261ada2b78e136ed3eaa pending Testing in progress [3-ci-srv-05]
podman[2014657]: DEBUG:s3-streamer:POST statuses/258f52114bd18a530747261ada2b78e136ed3eaa pending Testing in progress [3-ci-srv-05]
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-services-127.0.0.2-3002-FAIL.log
podman[2014657]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-services-127.0.0.2-3002-FAIL.log
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.log
podman[2014657]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.log
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:Uploading attachment TestSubscriptions-testSubAndInAndFail-services-127.0.0.2-2702-FAIL.log
podman[2014657]: DEBUG:s3-streamer:Uploading attachment TestSubscriptions-testSubAndInAndFail-services-127.0.0.2-2702-FAIL.log
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.core/core.curl.0.f0bd46a22c1843b7abe900b29eb4223b.1735.1655985804000000.xz
podman[2014657]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.core/core.curl.0.f0bd46a22c1843b7abe900b29eb4223b.1735.1655985804000000.xz
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.core/.#core.curl.0.f0bd46a22c1843b7abe900b29eb4223b.1755.1655985816000000.xz940c81860269648b
podman[2014657]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.core/.#core.curl.0.f0bd46a22c1843b7abe900b29eb4223b.1755.1655985816000000.xz940c81860269648b
cockpit-tasks-3[2015068]: DEBUG:s3:PUT https://cockpit-logs.us-east-1.linodeobjects.com/pull-3487-20220623-114834-258f5211-rhel-7-9-cockpit-project-cockpit-rhel-7.9/TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.core/.#core.curl.0.f0bd46a22c1843b7abe900b29eb4223b.1755.1655985816000000.xz940c81860269648b {'content-type': 'text/plain', 'x-amz-acl': 'public-read', 'host': 'cockpit-logs.us-east-1.linodeobjects.com', 'x-amz-content-sha256': 'efe7b1fff66525b3aefeaa7efae614590ce9ea37b4878bd740378bcb8c61b6e8', 'x-amz-date': '20220623T120350Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=YX0BE5CGRW5W1TBB4APX/20220623/any/s3/aws4_request,SignedHeaders=content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date,Signature=d3031bcf072d6afa212b747bdc9c57b5dc7bd0290b01f4f70f92b398ba88a612'} → 403:
podman[2014657]: DEBUG:s3:PUT https://cockpit-logs.us-east-1.linodeobjects.com/pull-3487-20220623-114834-258f5211-rhel-7-9-cockpit-project-cockpit-rhel-7.9/TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.core/.#core.curl.0.f0bd46a22c1843b7abe900b29eb4223b.1755.1655985816000000.xz940c81860269648b {'content-type': 'text/plain', 'x-amz-acl': 'public-read', 'host': 'cockpit-logs.us-east-1.linodeobjects.com', 'x-amz-content-sha256': 'efe7b1fff66525b3aefeaa7efae614590ce9ea37b4878bd740378bcb8c61b6e8', 'x-amz-date': '20220623T120350Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=YX0BE5CGRW5W1TBB4APX/20220623/any/s3/aws4_request,SignedHeaders=content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date,Signature=d3031bcf072d6afa212b747bdc9c57b5dc7bd0290b01f4f70f92b398ba88a612'} → 403:
cockpit-tasks-3[2015068]: DEBUG:s3:  b'<?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><RequestId>tx00000000000000bcce224-0062b456a7-1946d691-default</RequestId><HostId>1946d691-default-default</HostId></Error>'
podman[2014657]: DEBUG:s3:  b'<?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><RequestId>tx00000000000000bcce224-0062b456a7-1946d691-default</RequestId><HostId>1946d691-default-default</HostId></Error>'
cockpit-tasks-3[2015068]: Traceback (most recent call last):
cockpit-tasks-3[2015068]:   File "/work/bots/./s3-streamer", line 351, in <module>
podman[2014657]: Traceback (most recent call last):
podman[2014657]:   File "/work/bots/./s3-streamer", line 351, in <module>
podman[2014657]:     main()
podman[2014657]:   File "/work/bots/./s3-streamer", line 337, in main
podman[2014657]:     attachments_directory.scan()
podman[2014657]:   File "/work/bots/./s3-streamer", line 158, in scan
cockpit-tasks-3[2015068]:     main()
podman[2014657]:     self.destination.write(name, data)
podman[2014657]:   File "/work/bots/./s3-streamer", line 118, in write
podman[2014657]:     self.destination.write(filename, data)
podman[2014657]:   File "/work/bots/./s3-streamer", line 97, in write
podman[2014657]:     with s3.urlopen(self.url(filename), data=data, method='PUT', headers=headers) as _:
podman[2014657]:   File "/work/bots/lib/s3.py", line 117, in urlopen
podman[2014657]:     response = urllib.request.urlopen(request, context=host_ssl_context(url.netloc))
podman[2014657]:   File "/usr/lib64/python3.10/urllib/request.py", line 216, in urlopen
cockpit-tasks-3[2015068]:   File "/work/bots/./s3-streamer", line 337, in main
cockpit-tasks-3[2015068]:     attachments_directory.scan()
cockpit-tasks-3[2015068]:   File "/work/bots/./s3-streamer", line 158, in scan
cockpit-tasks-3[2015068]:     self.destination.write(name, data)
cockpit-tasks-3[2015068]:   File "/work/bots/./s3-streamer", line 118, in write
cockpit-tasks-3[2015068]:     self.destination.write(filename, data)
cockpit-tasks-3[2015068]:   File "/work/bots/./s3-streamer", line 97, in write
cockpit-tasks-3[2015068]:     with s3.urlopen(self.url(filename), data=data, method='PUT', headers=headers) as _:
cockpit-tasks-3[2015068]:   File "/work/bots/lib/s3.py", line 117, in urlopen
cockpit-tasks-3[2015068]:     response = urllib.request.urlopen(request, context=host_ssl_context(url.netloc))
cockpit-tasks-3[2015068]:   File "/usr/lib64/python3.10/urllib/request.py", line 216, in urlopen
cockpit-tasks-3[2015068]:     return opener.open(url, data, timeout)
cockpit-tasks-3[2015068]:   File "/usr/lib64/python3.10/urllib/request.py", line 525, in open
podman[2014657]:     return opener.open(url, data, timeout)
podman[2014657]:   File "/usr/lib64/python3.10/urllib/request.py", line 525, in open
cockpit-tasks-3[2015068]:     response = meth(req, response)
podman[2014657]:     response = meth(req, response)
podman[2014657]:   File "/usr/lib64/python3.10/urllib/request.py", line 634, in http_response
cockpit-tasks-3[2015068]:   File "/usr/lib64/python3.10/urllib/request.py", line 634, in http_response
cockpit-tasks-3[2015068]:     response = self.parent.error(
podman[2014657]:     response = self.parent.error(
podman[2014657]:   File "/usr/lib64/python3.10/urllib/request.py", line 563, in error
cockpit-tasks-3[2015068]:   File "/usr/lib64/python3.10/urllib/request.py", line 563, in error
cockpit-tasks-3[2015068]:     return self._call_chain(*args)
cockpit-tasks-3[2015068]:   File "/usr/lib64/python3.10/urllib/request.py", line 496, in _call_chain
podman[2014657]:     return self._call_chain(*args)
podman[2014657]:   File "/usr/lib64/python3.10/urllib/request.py", line 496, in _call_chain
cockpit-tasks-3[2015068]:     result = func(*args)
cockpit-tasks-3[2015068]:   File "/usr/lib64/python3.10/urllib/request.py", line 643, in http_error_default
podman[2014657]:     result = func(*args)
podman[2014657]:   File "/usr/lib64/python3.10/urllib/request.py", line 643, in http_error_default
podman[2014657]:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
cockpit-tasks-3[2015068]:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
cockpit-tasks-3[2015068]: urllib.error.HTTPError: HTTP Error 403: Forbidden
podman[2014657]: urllib.error.HTTPError: HTTP Error 403: Forbidden
cockpit-tasks-3[2015068]: ERROR:root:./s3-streamer --repo cockpit-project/bots --test-name pull-3487-20220623-114834 --github-context rhel-7-9@cockpit-project/cockpit/rhel-7.9 --revision 258f52114bd18a530747261ada2b78e136ed3eaa -- /bin/sh -c "PRIORITY=0005 ./make-checkout --verbose --repo=cockpit-project/cockpit rhel-7.9 && cd make-checkout-workdir && TEST_OS=rhel-7-9 BASE_BRANCH=rhel-7.9 COCKPIT_BOTS_REF=258f52114bd18a530747261ada2b78e136ed3eaa ../tests-invoke --pull-number 3487 --revision 258f52114bd18a530747261ada2b78e136ed3eaa --repo cockpit-project/bots" failed with exit code 1
podman[2014657]: ERROR:root:./s3-streamer --repo cockpit-project/bots --test-name pull-3487-20220623-114834 --github-context rhel-7-9@cockpit-project/cockpit/rhel-7.9 --revision 258f52114bd18a530747261ada2b78e136ed3eaa -- /bin/sh -c "PRIORITY=0005 ./make-checkout --verbose --repo=cockpit-project/cockpit rhel-7.9 && cd make-checkout-workdir && TEST_OS=rhel-7-9 BASE_BRANCH=rhel-7.9 COCKPIT_BOTS_REF=258f52114bd18a530747261ada2b78e136ed3eaa ../tests-invoke --pull-number 3487 --revision 258f52114bd18a530747261ada2b78e136ed3eaa --repo cockpit-project/bots" failed with exit code 1
```

**Comment by martinpitt** [comment]
I was watching the logs on ci-srv-02, and same crash again. Apparently our signature computation fails with the funny names like

    https://cockpit-logs.us-east-1.linodeobjects.com/pull-3487-20220628-063920-258f5211-rhel-7-9-cockpit-project-cockpit-rhel-7.9/TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-2501-FAIL.core/.#core.curl.0.bcee2fb1597b435c9400e2e8770a4b3d.1844.1656399156000000.xzbe9b94700088d65b

So that might need some quoting. As a quick fix, we could disable core file uploads on that branch?

**Comment by marusak** [comment]
Sent https://github.com/cockpit-project/cockpit/pull/17511

**Comment by marusak** [comment]
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-compilation-targets@^7.18.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

```

:man_shrugging:

**Comment by martinpitt** [comment]
[lolwut](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3487-20220629-134035-3de59f41-rhel-7-9-cockpit-project-cockpit-rhel-7.9/log.html#242-1) curl crashes? in RHEL 7.9, for $deity's sake??

**Comment by jelly** [comment]
Can't reproduce it here:

```
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
[root@localhost ~]# for x in $(seq 1 300); do sleep 1; curl -s https://services.cockpit.lan:8443/candlepin; done
[root@localhost ~]# for x in $(seq 1 100); do sleep 1; curl -s https://services.cockpit.lan:8443/candlepin; done
```

**Comment by martinpitt** [comment]
> So maybe I need to run the whole test suite for it to fail :(

Not really -- nondestructive things were not a thing yet on this branch; also, these tests are using `provision =`, so they run in a fresh VM anyway (i.e. are destructive).

I checked out this bots branch, linked it into my rhel-7.9 branch checkout, did `test/image-prepare -q rhel-7-9`, ran `TEST_OS=rhel-7-9 ./test/verify/check-subscriptions  -vst`, and it surely enough reproduces these curl crashes.

**Comment by martinpitt** [comment]
```
# gdb --args curl -s https://services.cockpit.lan:8443/candlepin
#0  0x00007ffff73d29d1 in CERT_FilterCertListByCANames () from /lib64/libnss3.so
#1  0x00007ffff791a202 in NSS_GetClientAuthData () from /lib64/libssl3.so
#2  0x00007ffff7bb3248 in SelectClientCert () from /lib64/libcurl.so.4
#3  0x00007ffff79239f4 in ssl3_CompleteHandleCertificateRequest () from /lib64/libssl3.so
#4  0x00007ffff79296d3 in ssl3_HandleHandshakeMessage () from /lib64/libssl3.so
#5  0x00007ffff792c8a3 in ssl3_HandleNonApplicationData () from /lib64/libssl3.so
#6  0x00007ffff792cfd8 in ssl3_HandleRecord () from /lib64/libssl3.so
#7  0x00007ffff79334ff in ssl3_GatherCompleteHandshake () from /lib64/libssl3.so
#8  0x00007ffff793a3cb in SSL_ForceHandshake () from /lib64/libssl3.so
#9  0x00007ffff7bb3f73 in nss_connect_common () from /lib64/libcurl.so.4
#10 0x00007ffff7baad8e in Curl_ssl_connect_nonblocking () from /lib64/libcurl.so.4
#11 0x00007ffff7b817ae in https_connecting () from /lib64/libcurl.so.4
#12 0x00007ffff7ba4728 in multi_runsingle () from /lib64/libcurl.so.4
#13 0x00007ffff7ba5641 in curl_multi_perform () from /lib64/libcurl.so.4
#14 0x00007ffff7b9c853 in curl_easy_perform () from /lib64/libcurl.so.4
#15 0x0000000000409f46 in operate ()
#16 0x000000000040239e in main ()
```

`bt full` doesn't show anything more, as there are no debug symbols. systemd-coredump collects all the cores, see e.g. `coredumpctl info`. Here is one: [core.curl.gz](https://github.com/cockpit-project/bots/files/9028326/core.curl.gz)

- `curl -k https://localhost:9090` works (after starting cockpit.service)
- `curl -k https://services.cockpit.lan:8443/candlepin` crashes.

**Comment by martinpitt** [comment]
So judging by the backtrace and the changed packages, my bet is on this:

  nss (3.67.0-4.el7_9 -> 3.79.0-2.el7_9)

**Comment by jelly** [comment]
> I'd be awesome to have a part of the backtrace in the pattern, but I think we can't do that, right?

Doens't look too trivial, let's hope it get's fixed soon.

**Pull request merged**
