### PR TITLE
Image refresh for centos-8-stream

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-8-stream
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/centos-8-stream-20230525-230707.log

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20230525-231446

**Comment by cockpituous** [comment]
Completed. Log: Error accessing /repos/cockpit-project/bots/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value":4806,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}

**Comment by martinpitt** [comment]
[vdo regression](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4806-20230525-230855-07c59978-centos-8-stream-pybridge-cockpit-project-cockpit/log.html#237-2) from kernel update? Retrying once to compare

**Review by martinpitt — APPROVED** [review]
OK, worked now.

**Pull request merged**
