### PR TITLE
images: Move ubuntu-stable to noble devel series

### PR DESCRIPTION
**Pull request by martinpitt**
The current devel series will become 24.04 LTS, thus a major/important release again. Let's avoid repeating a regression catastrophe like 23.10 mantic, and start testing on it early, so that we have a chance to fix up everything by the final release.

 * [x] image-refresh ubuntu-stable
 * [x] https://github.com/cockpit-project/cockpit-machines/pull/1487
 * [x] https://github.com/cockpit-project/cockpit-machines/pull/1491
 * [x] https://github.com/cockpit-project/cockpit/pull/20156

I created a calendar reminder for me on Apr 25 to revert the hack and enable -proposed.

### CODE REVIEW

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-stable-108f9ef6-20240308-135200/log.html

**Comment by martinpitt** [comment]
openssh install is broken. Need to report to launchpad (didn't find it quickly), and block.

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20240311-074439

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-stable-dacd919f-20240311-072424/log.html

**Comment by martinpitt** [comment]
[machines failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6048-20240311-075348-286b981d-ubuntu-stable-cockpit-project-cockpit-machines/log.html#86): Most are due to a single AppArmor denial:
```
apparmor="DENIED" operation="open" class="file" profile="virt-aa-helper" name="/etc/gnutls/config" pid=1537 comm="virt-aa-helper" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```
This wasn't reported yet, so I sent https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/2056739 .

The other failures are because ubuntu-stable now supports external snapshots. I'll think about how to adjust the tests to work without a lockstep change.

**Comment by martinpitt** [comment]
Cockpit fails very often on
```
apparmor="DENIED" operation="open" class="file" profile="/usr/sbin/chronyd" name="/etc/gnutls/config" pid=885 comm="chronyd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

which is very similar to https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/2056739. Filed as https://bugs.launchpad.net/ubuntu/+source/chrony/+bug/2056747

Others are known naughties.

This leaves just two specific failures:
 - [ ] [TestConnection.testCockpitDesktop](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6048-20240311-075346-286b981d-ubuntu-stable-other-cockpit-project-cockpit/log.html#20-2)
 - [ ] [TestJournal.testLogLevel](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6048-20240311-075346-286b981d-ubuntu-stable-other-cockpit-project-cockpit/log.html#118) (another AppArmor violation)

**Review by jelly — APPROVED** [review]
Thanks!

**Pull request merged**
