### PR TITLE
Image refresh for rhel-9-2

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-2
 * [x] image-refresh rhel-9-2

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-2-20221214-230000.log

**Comment by martinpitt** [comment]
An SELinux regression *and* an LVM crash? Who can say no to this joy? :smirk:

**Comment by KKoukiou** [comment]
The storage failure is probably https://bugzilla.redhat.com/show_bug.cgi?id=2141837

**Comment by KKoukiou** [comment]
Reported upstream https://bugzilla.redhat.com/attachment.cgi?bugid=2141837&action=enter

**Comment by martinpitt** [comment]
That image is stale, and one bug got already fixed. Let's re-do this.

**Pull request closed without merging**
