### PR TITLE
Image refresh for fedora-rawhide-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-boot

 * [ ] FAIL: image-refresh fedora-rawhide-boot

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-boot done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-boot-20240208-131916

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-boot-20240208-131919.log

**Comment by KKoukiou** [comment]
The package is in the mirrors for downloading but not in boot.iso yet.

**Comment by martinpitt** [comment]
[These need attention](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5887-20240208-132030-298b9309-fedora-rawhide-boot-rhinstaller-anaconda-webui/log.html)

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-boot-20240209-103131.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-boot-20240209-135555.log

**Comment by martinpitt** [comment]
I cleaned up rhos-01-14, retrying.

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-boot-20240209-145050.log

**Comment by martinpitt** [comment]
I manually ran `./image-create -v fedora-rawhide-boot` on ci-srv-06 4 (like the most recent failure), and it worked just fine. Trying once more, to see a pattern in /cache/images/.. I deleted all `*rawhide* in there before, I figure that somehow "fixed" it.

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-boot-20240209-160808.log

**Comment by martinpitt** [comment]
This also most probably happens because this was triggered from a PR which already refreshes the image. Let's start from scratch.

**Pull request closed without merging**
