### PR TITLE
images: Fix fedora-35 cloud URL, add nodejs to Fedora mock

### LINKED ISSUE #2896: Image refresh for fedora-35
Image refresh for fedora-35
 * [ ] FAIL: image-refresh fedora-35

### PR DESCRIPTION
**Pull request by martinpitt**
It was released a long time ago, and the /development links disappeared
now.

Fixes #2896

--- 

I also took the chance to add nodejs to the mock, see commit message for details.

 * [x] image-refresh fedora-35
 * [x] image-refresh fedora-34

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-2897-20220205-065151/

**Comment by cockpituous** [comment]
image-refresh fedora-35 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-35-20220205-071111

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-pl65v.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-2897-20220205-071212/

**Comment by cockpituous** [comment]
image-refresh fedora-34 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-34-20220205-073030

**Comment by martinpitt** [comment]
Fun, [podman failed a pixel test](https://logs.cockpit-project.org/logs/pull-2897-20220205-071154-915a68b9-fedora-35-rawhide-cockpit-project-cockpit-podman/pixeldiff.html#TestApplication-testBasicSystem-overview) and [anaconda failed to build](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-2897-20220205-071204-915a68b9-fedora-35-rawhide-rhinstaller-anaconda/log.html) on the *current* image. Pushing refreshed images now, let's see how these compare.

**Comment by martinpitt** [comment]
[anaconda fails again](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-2897-20220205-074016-32a8cfdc-fedora-35-rawhide-rhinstaller-anaconda/log.html), but that's already happening on the current image. @KKoukiou , @jkonecny, any idea about that?

There's also a new [SELinux violation](https://logs.cockpit-project.org/logs/pull-2897-20220205-074019-32a8cfdc-fedora-35-firefox-cockpit-project-cockpit-machines/log.html#38):

    audit: type=1400 audit(1644047661.743:13546): avc:  denied  { execute } for  pid=57884 comm="chpasswd" name="sss_cache" dev="vda5" ino=39569 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
