### PR TITLE
images: Add stratis-cli and stratisd to the Fedoras

### PR DESCRIPTION
**Pull request by mvollmer**
* [ ] FAIL: image-refresh fedora-33
 * [ ] FAIL: image-refresh fedora-34

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-2273-20210803-103030/

**Comment by cockpituous** [comment]
Command '('git', 'push', 'https://github.com/cockpit-project/bots', '+HEADNone/heads/image-refresh-fedora-33-20210803-104848')' returned non-zero exit status 1.: https://logs.cockpit-project.org/logs/image-refresh-2273-20210803-103030/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-2273-20210803-104848/

**Comment by cockpituous** [comment]
Command '('git', 'push', 'https://github.com/cockpit-project/bots', '+HEADNone/heads/image-refresh-fedora-34-20210803-110505')' returned non-zero exit status 1.: https://logs.cockpit-project.org/logs/image-refresh-2273-20210803-104848/

**Comment by mvollmer** [comment]
Can't make image refreshing PRs from personal forks, I guess.

**Comment by martinpitt** [comment]
@mvollmer: You can, your fork is just *really* out of date.

**Pull request closed without merging**
