### PR TITLE
images: Adjust build-deps.sh to recent cockpit spec reorg

### PR DESCRIPTION
**Pull request by martinpitt**
[1] changed cockpit's template spec format and location quite
profoundly. Compute the rpmspec-parseable spec independently for the
main and rhel-7.9 branches; the latter continues to use the same
approach as before, for main make use of the new BUILD_ALL template and
just disable all other templates -- we don't need them for build
dependencies.

Also fix the curl command to actually fail on 404s and other errors.

[1] https://github.com/cockpit-project/cockpit/pull/16853

------

This fixes the failure in issue #2838. But let's start with Fedora 35 first, as that's by far the most urgent image refresh that we currently have.

 * [x] image-refresh fedora-35
 * Must land in lockstep with https://github.com/cockpit-project/cockpit/pull/16848

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-2839-20220121-053434/

**Comment by martinpitt** [comment]
This looks reasonable:
```
❱❱❱ images/scripts/lib/build-deps.sh "fedora 35" 
"/usr/bin/python3" "autoconf" "automake" "docbook-style-xsl" "gcc" "gdb" "gettext >= 0.19.7" "glib-networking" "glib2-devel >= 2.50.0" "gnutls-devel >= 3.4.3" "krb5-devel >= 1.11" "krb5-server" "libssh-devel >= 0.8.5" "libxslt-devel" "make" "openssh-clients" "openssl-devel" "pam-devel" "pcp-libs-devel" "pkgconfig(gio-unix-2.0)" "pkgconfig(json-glib-1.0)" "pkgconfig(polkit-agent-1) >= 0.105" "sed" "selinux-policy" "selinux-policy-devel" "systemd-devel >= 235" "xmlto" "zlib-devel" 
```

Also still works for the old branch, I diffed the before/after:
```
❱❱❱ images/scripts/lib/build-deps.sh "centos 7" 2>/dev/null
"/usr/bin/python3" "autoconf" "automake" "docbook-style-xsl" "gcc" "gdb" "glib-networking" "glib2-devel >= 2.37.4" "golang-bin" "golang-src" "intltool" "krb5-devel" "krb5-server" "libssh-devel >= 0.7.1" "libxslt-devel" "openssh-clients" "openssl-devel" "pam-devel" "pcp-libs-devel" "pkgconfig(gio-unix-2.0)" "pkgconfig(json-glib-1.0)" "pkgconfig(polkit-agent-1) >= 0.105" "sed" "systemd-devel" "xmlto" "zlib-devel" 
```
(that produces a few rpmspec warnings on stderr, but it has always done that)

I also wdiff'ed the two, diff looks intented and correct:

```
"/usr/bin/python3" "autoconf" "automake" "docbook-style-xsl" "gcc" "gdb" {+"gettext >= 0.19.7"+} "glib-networking" "glib2-devel >= [-2.37.4" "golang-bin" "golang-src" "intltool" "krb5-devel"-] {+2.50.0" "gnutls-devel >= 3.4.3" "krb5-devel >= 1.11"+} "krb5-server" "libssh-devel >= [-0.7.1"-] {+0.8.5"+} "libxslt-devel" {+"make"+} "openssh-clients" "openssl-devel" "pam-devel" "pcp-libs-devel" "pkgconfig(gio-unix-2.0)" "pkgconfig(json-glib-1.0)" "pkgconfig(polkit-agent-1) >= 0.105" "sed" [-"systemd-devel"-] {+"selinux-policy" "selinux-policy-devel" "systemd-devel >= 235"+} "xmlto" "zlib-devel" 
```

**Comment by martinpitt** [comment]
> selinux-policy                         noarch 35.11-1.fc35       updates  70 k

Yes! :v: that's the [good one](https://bodhi.fedoraproject.org/updates/FEDORA-2022-87a0b7e8d0)!

**Comment by cockpituous** [comment]
image-refresh fedora-35 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-35-20220121-055252

**Comment by martinpitt** [comment]
The [testSELinuxRestrictedUser](https://logs.cockpit-project.org/logs/pull-2839-20220121-062249-10dfbfe6-fedora-35-firefox-cockpit-project-cockpit/log.html#166-2) failures here are expected - this gets adjusted in https://github.com/cockpit-project/cockpit/pull/16848 and this PR needs to land in lockstep.

**Review by marusak — APPROVED** [review]
Nice, thanks!

**Comment by marusak** [comment]
Succeeded in https://github.com/cockpit-project/cockpit/pull/16848

**Pull request merged**
