### PR TITLE
naughty: Add a pattern for broken rootless podman on rhel-8

### PR DESCRIPTION
**Pull request by mvollmer**
For https://github.com/cockpit-project/bots/issues/1436

### CODE REVIEW

**Comment by mvollmer** [comment]
This is needed for https://github.com/cockpit-project/cockpit-podman/pull/617

**Review by marusak — APPROVED** [review]
`rootless-smootless` :)

**Comment by marusak** [comment]
Triggered `rhel-8-4@bots#1437` context in https://github.com/cockpit-project/cockpit-podman/pull/617 just to make sure it is caught.

**Comment by martinpitt** [comment]
Seems it [needs an alternative pattern](https://logs.cockpit-project.org/logs/pull-617-20201203-200210-746ad9cf-rhel-8-4-bots-1437/log.html#11-2), as in that test the error is shown in the dialog instead of the console? Or, preferably, we patch up cockpit-podman to show it in both places.

**Pull request merged**
