### PR TITLE
Image refresh for fedora-rawhide-anaconda-payload

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-anaconda-payload
 * [x] image-refresh fedora-rawhide-anaconda-payload

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-anaconda-payload done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-anaconda-payload-20240616-224741

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-anaconda-payload-cf4f9a79-20240616-223835/log.html

**Comment by martinpitt** [comment]
@M4rtinK @KKoukiou are these generally [known to be broken](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6511-8a952127-20240617-035616-fedora-rawhide-boot-rhinstaller-anaconda-webui/log.html)? I've retried it already, and I saw the same [in a different recent PR](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19401-90e585ab-20240616-141321-fedora-rawhide-boot-cockpit-pr-19401-rhinstaller-anaconda-webui/log.html)

**Comment by jelly** [comment]
Could be some Python 3.13 fallout?

**Comment by KKoukiou** [comment]
> @M4rtinK @KKoukiou are these generally [known to be broken](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6511-8a952127-20240617-035616-fedora-rawhide-boot-rhinstaller-anaconda-webui/log.html)? I've retried it already, and I saw the same [in a different recent PR](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19401-90e585ab-20240616-141321-fedora-rawhide-boot-cockpit-pr-19401-rhinstaller-anaconda-webui/log.html)

Our main branch is currently broken, https://github.com/rhinstaller/anaconda-webui/pulls , testing now what regression slipped in,.

**Comment by martinpitt** [comment]
I'm curious how this broke -- [318-1](https://bodhi.fedoraproject.org/updates/FEDORA-2024-292dcb3686) isn't even visible in `dnf` right now, the latest version is 317-2 (which is the py 3.13 rebuild). Anyway, I uploaded another rebuild against py 3.13, as our 318-1 upload stomped over that: https://bodhi.fedoraproject.org/updates/FEDORA-2024-65b42deac5

Once this is visible (tomorrow-ish?) we can rebuild this and the tests should be happy again. Sorry @KKoukiou !

**Comment by martinpitt** [comment]
Should have been fixed in https://github.com/rhinstaller/anaconda-webui/pull/306 , rebasing/retrying.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
