### PR TITLE
Image refresh for fedora-rawhide

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide
 * [x] image-refresh fedora-rawhide
 * [ ] https://github.com/rhinstaller/anaconda/pull/5232

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-20230928-225757.log

**Comment by jelly** [comment]
The Fedora logo is gone now, I've pinged the Anaconda team on Slack.

**Comment by martinpitt** [comment]
@jelly any response so far?

**Comment by jelly** [comment]
> @jelly any response so far?

No, I think @allisonkarlitskaya was trying to do a diff of the old and the new image to figure out why the logo file is gone as it seems it is actually on the iso.

**Comment by KKoukiou** [comment]
> The Fedora logo is gone now, I've pinged the Anaconda team on Slack.

It's not gone, it's just a flaky test. The logo is an image and it takes more time to load. I added some ignore for the .logo class, I missed this test.

**Comment by martinpitt** [comment]
@KKoukiou ah, and there's no DOM change once the image finished loading? I think in this case I would accept a sleep(1) or so -- I find it slightly preferable to make sure the logo is where we expect it.

**Comment by KKoukiou** [comment]
> @KKoukiou ah, and there's no DOM change once the image finished loading? I think in this case I would accept a sleep(1) or so -- I find it slightly preferable to make sure the logo is where we expect it.

ACK, checking the tests now.

**Comment by martinpitt** [comment]
Rebased, as this [old rawhide-boot image is not available any more](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5322-20231009-045921-c3052b04-fedora-rawhide-boot-rhinstaller-anaconda/log).

**Review by martinpitt — APPROVED** [review]
Green now. The race is fixed in https://github.com/rhinstaller/anaconda/pull/5232 and affects the current image as well. Don't let these bitrot so much.

**Pull request merged**
