### PR TITLE
Image refresh for fedora-rawhide-anaconda-payload

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-anaconda-payload
 * [x] image-refresh fedora-rawhide-anaconda-payload

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-anaconda-payload done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-anaconda-payload-20240926-224946

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-anaconda-payload-773bac5b-20240926-224045/log.html

**Comment by martinpitt** [comment]
Uh, [lots of failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6923-21630381-20240926-225056-fedora-rawhide-boot-expensive-rhinstaller-anaconda-webui/log.html#1-2) with `OSError: [Errno 98] Address already in use`. These are destructive tests, so not due to an unclean VM. Plus, `TestFedoraPlansEraseAll.testGuidedMultiSelect` has a different root cause.

I'll do a retry to compare, so that we have two logs.

**Review by martinpitt — APPROVED** [review]
Worked now :man_shrugging:

**Pull request merged**
