### PR TITLE
naughty: Rhel-9 does not show crash function anymore

### PR DESCRIPTION
**Pull request by marusak**
@martinpitt Do you think that we rather should adjust `DefaultLimitCORE` in `/etc/systemd/system.conf` to get more verbose logs instead?

rhel-9 disables by default any coredumps. That also means that journal
does not contain any information about crashing program. We see in
journal only:
```
systemd[1]: Started Process Core Dump (PID 132747/UID 0).
systemd-coredump[132753]: Resource limits disable core dumping for process 616 (polkitd).
systemd-coredump[132753]: Process 616 (polkitd) of user 998 dumped core.
systemd[1]: polkit.service: Main process exited, code=dumped, status=5/TRAP
systemd[1]: polkit.service: Failed with result 'core-dump'.
systemd[1]: polkit.service: Consumed 7.744s CPU time.
systemd[1]: systemd-coredump@0-132747-0.service: Deactivated successfully.
```

Only after I enabled `DefaultLimitCORE` in `/etc/systemd/system.conf` I
get backtrace in journal that also contains `polkit_system_bus_name_get_creds_sync`.

See https://github.com/redhat-plumbers/systemd-rhel8/pull/149
See https://bugzilla.redhat.com/show_bug.cgi?id=1905582

 * [x] image-refresh rhel-9-0
 * [x] image-refresh rhel-8-6
 * [x] image-refresh rhel-7-9

### CODE REVIEW

**Comment by martinpitt** [comment]
Yes, I think we should do that. It will help us with other crashes as well. On debian/ubuntu we do this:

    images/scripts/debian.setup:printf 'DefaultLimitCORE=infinity\n' >> /etc/systemd/system.conf

so let's do this on RHEL as well then? It's also fine to do that in the *.install scripts, then the images themselves are "pure" and it's easier to change.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-2878-20220201-103838/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-2878-20220201-103838/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2878-20220201-103333/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-2878-20220201-103333/

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20220201-105454

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-2878-20220201-105555/

**Comment by martinpitt** [comment]
I honestly think that tweaks like this belong into the *.install scripts, and *not* affect/require image refreshes.

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20220201-111616

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-2878-20220201-111616/

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-7-9-20220201-114343

**Comment by martinpitt** [comment]
The rhel-9 refresh was an infra flake, retrying

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-2878-20220201-155656/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20220201-174949

**Comment by martinpitt** [comment]
I pushed the images and triggered tests.

**Comment by martinpitt** [comment]
Somehow the new rhel-7-9 image lost the Go compiler. I figure that's fallout from my recent build-deps.sh adjustments from commit d365e9d1a8258 . I'll drop the refreshed rhel-7-9 image from here, land as-is, and investigate this separately.

**Review by martinpitt — APPROVED** [review]

**Comment by martinpitt** [comment]
rhel-7-9 image investigation:

  - There is *no* difference in generated output for `images/scripts/lib/build-deps.sh 'rhel 7'` before/after commit d365e9d1a8258edf (I already checked that in the corresponding PR), and the output *does* include `"golang-bin" "golang-src"`.
  - The [image build log](https://logs.cockpit-project.org/logs/image-refresh-2878-20220201-111616/log) confirms that the golang packages get installed into the mock.
  - The [test log](https://logs.cockpit-project.org/logs/pull-2878-20220201-180742-e11e9386-rhel-7-9-cockpit-project-cockpit-rhel-7.9/log.html) confirms "Already installed : golang-bin-1.16.13-2.el7.x86_64", and ./configure says "checking for go... /usr/bin/go".
  - So this `package cockpit-kube-auth is not in GOROOT (/usr/lib/golang/src/cockpit-kube-auth)` is most likely some fallout from an  updated Go compiler in RHEL 7? The new image has golang-bin.x86_64 0:1.16.13-2.el7 , The [previous successful refresh](https://logs.cockpit-project.org/logs/image-refresh-2856-20220127-053939/log) (6 days ago) had golang-bin.x86_64 0:1.15.14-1.el7, so definitively a version bump.

**Pull request merged**
