### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240118-225023

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20240118-225050.log

**Comment by martinpitt** [comment]
The [testRaidRepair failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5804-20240118-225140-c08d7672-arch-storage-cockpit-project-cockpit/log.html#37-2) with "losetup: /var/tmp/loop.gAT7: failed to set up loop device: Device or resource busy" and the subsequent cleanup failure is similar to the failures that now often happen in rawhide, e.g. in https://github.com/fedora-selinux/selinux-policy/pull/1998 with [this log](https://artifacts.dev.testing-farm.io/e17c1218-e4c6-49fe-a48a-408c7bf39461/), or the gating tests in [yesterday's rawhide release](https://bodhi.fedoraproject.org/updates/FEDORA-2024-695570fcc8) with [this log](https://artifacts.dev.testing-farm.io/1f3a7e4e-519c-4446-b6ef-115f90941ca7/). That failure has some catastrophic effect on the test VM which doesn't let it recover.

**Comment by martinpitt** [comment]
That actually feels very similar to the `testMaxLayoutSizes()` [failure](https://artifacts.dev.testing-farm.io/a9a2841b-f21d-48fa-a26a-38fa1145194d/) from two weeks ago which also caused the busy loop devices and broken VM. That's been on our pilot board for two weeks, but we didn't look into that yet either.

**Comment by martinpitt** [comment]
Let's try this again after https://github.com/cockpit-project/cockpit/pull/19875

**Comment by jelly** [comment]
It seems that the kernel was updated `linux (6.6.10.arch1-1 -> 6.7.arch3-1)` so that might be related.

**Comment by martinpitt** [comment]
Superseded by #5861, let's continue debugging there.

**Pull request closed without merging**
