### PR TITLE
images: Drop rhel-7-9 and centos-7

### PR DESCRIPTION
**Pull request by martinpitt**
RHEL 7.9 reaches end-of-maintenance at the end of June [1]. We haven't actually done any updates in years, at this point it's just dead weight.

Move testing of the services image to cockpit's RHEL 8 branch, which is still active.

https://github.com/cockpit-project/cockpit/pull/20368 dropped centos-7 usage in cockpit's tests (it doesn't use rhel-7-9).

[1] https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/rhel-7-end-of-maintenance

### CODE REVIEW

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit/pull/20368 landed, so we can drop c7 now as well.

**Review by marusak — APPROVED** [review]
Yes, I think it is very much the time to drop these, thanks!

**Comment by martinpitt** [comment]
test failures are #6271

**Comment by martinpitt** [comment]
Rebased to pick up the mypy fix.

**Review by allisonkarlitskaya — APPROVED** [review]
check check checkity check check

**Pull request merged**
