### PR TITLE
Image refresh for rhel-8-6

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-6
 * [x] image-refresh rhel-8-6

### CODE REVIEW

**Comment by marusak** [comment]
[podman](https://logs.cockpit-project.org/logs/pull-2462-20210930-051153-01854ed8-rhel-8-6-cockpit-project-cockpit-podman/TestApplication-testRunImageSystem-rhel-8-6-127.0.0.2-2301-FAIL.png) has some interesting failures.

**Comment by marusak** [comment]
Reported the obvious one, looking now at the other two: https://bugzilla.redhat.com/show_bug.cgi?id=2009264

**Comment by marusak** [comment]
Ok, the other one was also easy to reproduce, reported: https://bugzilla.redhat.com/show_bug.cgi?id=2009296

I'll make naughty for both. It a bit annoying as 4 of 11 tests are broken due to this version :/

**Review by martinpitt — APPROVED** [review]
Huh, what? How can podman v4 be in RHEL 8 when it's not even in Rawhide? https://bodhi.fedoraproject.org/updates/?packages=podman

**Comment by marusak** [comment]
> Huh, what? How can podman v4 be in RHEL 8 when it's not even in Rawhide?

Asking the right questions! I have no idea how it ended up in 8-6 but anywhere else, not even in github tags :man_shrugging:

**Pull request merged**
