### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing
 * [x] https://github.com/cockpit-project/cockpit/pull/19799
 * [x] https://github.com/cockpit-project/cockpit/pull/19803

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20231229-230027

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-testing-20231229-230000.log

**Comment by martinpitt** [comment]
I would have bet my lunch that it was the libssh 0.10.5 → 0.10.6 upgrade, but I downgraded libssh-4 and it still fails the same way. I'll investigate this on the debian-stable upgrade instead on #5733, which has much less churn. Blocking on that.

**Comment by martinpitt** [comment]
[This still fails](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5732-20240103-083139-9b143bee-debian-testing-networking-cockpit-project-cockpit/log.html#37-2), but also rings a bell. I sent https://github.com/cockpit-project/cockpit/pull/19803 to fix it.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
