### PR TITLE
Image refresh for centos-8-stream

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-8-stream
 * [x] image-refresh centos-8-stream
 * [x] add allowed message for new SELinux regression: PR #2156
 * [x] https://github.com/cockpit-project/cockpit/pull/16050
 * [x] https://github.com/cockpit-project/starter-kit/pull/473

### CODE REVIEW

**Comment by martinpitt** [comment]
Same SELinux problem as in RHEL 8.5 refresh in #2156, marking as blocked.

**Comment by martinpitt** [comment]
Pushed a rebase to pick up latest fixes/images, and reset test failure stats.

**Comment by allisonkarlitskaya** [comment]
```
  File "/work/bots/make-checkout-workdir/test/check-application", line 29, in testBasic
    b.wait_in_text(".pf-c-alert__title", "Running on " + hostname
```

surely fallout from the recent hostname changes...

**Comment by martinpitt** [comment]
I sent a [fix for starter-kit](https://github.com/cockpit-project/starter-kit/pull/473) and a [backport for the cockpit rhel-8.4 branch](https://github.com/cockpit-project/cockpit/pull/16050) for the outstanding failures, added to TODO list. The latter is still broken however, due to our premature infra cleanup.

**Review by allisonkarlitskaya — APPROVED** [review]
greeeeeeen

Thanks @martinpitt  :)

**Pull request merged**
