### PR TITLE
machine_core: fix environment handling in .execute(), update rhel images

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
The changes made in 90c0b2efadede35a9cbc583c61a9dfc450eb7e56 introduced
a couple of bugs.

 - They removed the use of `env_script` without removing the code to
   compute it.

 - The environment variables were being prepended as `KEY=VAL` arguments
   before the command to be run.  The introduction of `set -e;` at the
   start of the command turned commands like `DO_BUILD=1 cmd` into
   `DO_BUILD=1 set -e; cmd` which means that `cmd` was running without
   an environment.

Simplify the code for computing the environment: remove the dead bits,
and use `export KEY=VAL;` to make sure all commands in the script get
the values set (since we often use `;` in our .execute() lines now).
Improve the quoting by using `shlex.quote()` instead of just adding
single quotes and hoping it will be OK.

 * [x] image-refresh rhel-9-0
 * [x] image-refresh rhel-7-9
 * [x] image-refresh rhel-8-6

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-3746-20220817-140404/

**Comment by allisonkarlitskaya** [comment]
Looks like this is going to fix the RHEL image refreshes, but not anaconda, which remains broken (no change).

The fact that anaconda is also failing in #3744 strongly suggests that these two problems are not related.  :(

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20220817-142705

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3746-20220817-142727/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-3746-20220817-142727/

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-7-9-20220817-150726

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-3746-20220817-150707/

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20220817-153709

**Review by marusak — APPROVED** [review]

**Comment by allisonkarlitskaya** [comment]
The broken `rhel-7-9` test is due to the dropping of the `script=` kwarg (and in particular, is not caused by anything in this PR, and is currently broken in the `rhel-7.9` branch itself).

I've opened cockpit-project/cockpit#17658 to attempt to deal with that.

**Pull request merged**
