### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20230721-225858

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-testing-20230721-225858.log

**Comment by skobyda** [comment]
Looks like `avc: denied { sqpoll }` now also started to fail for `comm="nsupdate"` (until now, it was only failing for `comm="pmproxy"`)
Fortunately, there is already a report of that: https://bugzilla.redhat.com/show_bug.cgi?id=2223441
So I just added another naughty pattern for #5020

**Review by martinpitt — APPROVED** [review]
Cheers! (Assuming green)

**Comment by martinpitt** [comment]
Any chance to :-1: some package update before it reaches updates?

**Comment by skobyda** [comment]
> Any chance to -1 some package update before it reaches updates?

 libvirt-9.0.0-3.fc38 : https://bodhi.fedoraproject.org/updates/FEDORA-2023-7564d5eb0a
has a regression: https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2224994

**Comment by skobyda** [comment]
All green

**Pull request merged**
