### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-coreos done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-coreos-20231231-224841

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-coreos-20231231-224848.log

**Comment by martinpitt** [comment]
Odd, it's the fixed libssh, but still failed the IPv6 address check..

**Comment by martinpitt** [comment]
Ah! The problem is that the cockpit/ws *container* on this image has libssh 0.10.6-1.fc39. Which is a bit weird, as https://quay.io/repository/cockpit/tasks?tab=tags says that the last refresh was on Nov 20, while that libssh version only happened on Dec 22. But that's obviously bogus, as the real tag says "8 days ago". :man_shrugging: 

The [latest refresh run](https://github.com/cockpit-project/cockpit/actions/runs/7374259478/job/20064434110) already pulled in -2. So let's just try to refresh the image again.

**Pull request closed without merging**
