### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240320-224857

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-9af0bc55-20240320-223737/log.html

**Comment by jelly** [comment]
```
error: failed retrieving file 'empty.db' from disk : Couldn't open file /var/lib/cockpittest/empty/empty.db
error: failed to synchronize all databases (download library error)
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
```
New pacman broke Packagekit hard.

**Comment by mvollmer** [comment]
repo-add doesn't create empty repositories anymore. It used to produce the required empty.db.tar.gz etc files (which were just empty compressed tarballs), but not anymore.

Why do we need that empty repo? Pacman fails with no repos, but we will create the testrepo later one with enableRepo. Isn't that enough?

**Comment by jelly** [comment]
> repo-add doesn't create empty repositories anymore. It used to produce the required empty.db.tar.gz etc files (which were just empty compressed tarballs), but not anymore.

So I suppose we can touch those?

> Why do we need that empty repo? Pacman fails with no repos, but we will create the testrepo later one with enableRepo. Isn't that enough?

```
            # HACK: Setup empty repo for packagekit
```

So this seems to be a hack for packagekit not being able to deal with no repos at all?

**Comment by mvollmer** [comment]
# So this seems to be a hack for packagekit not being able to deal with no repos at all?

Ah, maybe.

**Comment by mvollmer** [comment]
Potential fix: https://github.com/cockpit-project/cockpit/pull/20216

**Comment by mvollmer** [comment]
Next is this: 

```
==> ERROR: Cannot find the debugedit binary required for including source files in debug packages.
```

**Comment by jelly** [comment]
> Next is this:
> 
> ```
> ==> ERROR: Cannot find the debugedit binary required for including source files in debug packages.
> ```

Ah, this is a bug! Need to find the bugzilla but we don't really want to create debug packages anyway so I say we edit the PKGBUILD's:

```
options=(!debug)
```

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240322-111000

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-62892039-20240322-105649/log.html

**Review by mvollmer — APPROVED** [review]
All good now!

**Pull request merged**
