### PR TITLE
images: add python3-pcp for Fedora images

### PR DESCRIPTION
**Pull request by jelly**
The Python rewrite of cockpit-pcp is underway and to help development and testing add the new runtime dependency.

 * [x] image-refresh fedora-40

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-40 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-40-20240705-152112

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-40-4e423c96-20240705-145247/log.html

**Comment by jelly** [comment]
```
# testBeibootWithBridge (__main__.TestClient.testBeibootWithBridge)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
error: Failed dependencies:
	pcp = 6.2.2-3.fc40 is needed by (installed) python3-pcp-6.2.2-3.fc40.x86_64
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-client", line 42, in setUp
    self.m_target.execute("rpm --erase --verbose cockpit-pcp pcp; systemctl daemon-reload")
```

**Comment by jelly** [comment]
Sent https://github.com/cockpit-project/cockpit/pull/20723

**Comment by martinpitt** [comment]
The cockpit fix landed, I rebased this.

**Comment by martinpitt** [comment]
@jelly I'm  afraid you [forgot a spot](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6586-1e8a2d9d-20240709-030018-fedora-40-firefox-other-cockpit-project-cockpit/log.html) :cry:

**Comment by martinpitt** [comment]
cockpit PR landed. Rebased again for clean test results.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
