### PR TITLE
images: Pre-install cockpit/ws container on Fedora image

### PR DESCRIPTION
**Pull request by martinpitt**
https://github.com/cockpit-project/cockpit/pull/21154 introduced cockpit/ws beiboot based RHEL 8 tests to cockpit main. This currently downloads the ws container during image build. Let's make this offline and predictable again by pre-installing the container on the Fedora image which is being used to build the updated container.

 * [x] image-refresh fedora-40
 * [x] https://github.com/cockpit-project/cockpit-podman/pull/1897

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-40 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-40-20241029-143701

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-40-9d278660-20241029-141549/log.html

**Comment by martinpitt** [comment]
[ah yes](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7046-d5846949-20241029-162317-fedora-40-firefox-cockpit-project-cockpit-podman/log.html), need to clean up that extra image for pixel tests..

**Review by jelly — APPROVED** [review]

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/21192 to make use of this.

**Pull request merged**
