### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos

### CODE REVIEW

**Comment by marusak** [comment]
Load of failures like:
```
Error: error creating container storage: the container name "ws" is already in use by "7211a43ae80fae52111a166fdec31673a4f3e1ac0a27ae4489913c32c8444b4f". You have to remove that container to be able to reuse that name.: that name is already in use
Error: `/proc/self/exe run -d --name ws --privileged --pid=host -v /:/host localhost/cockpit/ws:latest /container/atomic-run --local-ssh --no-tls` failed: exit status 125
```

**Comment by martinpitt** [comment]
Hah, this is a fun one -- in the current master image, the `podman container runlabel ` command doesn't respect the `--name NAME`, and it always generates a new container. With this image refresh, the name is now always `ws` as intended, and thus the collision.

**Comment by marusak** [comment]
oh, is that regression in podman?

**Comment by martinpitt** [comment]
@marusak: More like a progression; however, podman itself and crun are the same version, I wonder if it was just the container refresh itself from the last cockpit release? Anyway, fix pushed.

**Pull request merged**
