### PR TITLE
Image refresh for fedora-31

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-31
 * [x] image-refresh fedora-31

### CODE REVIEW

**Comment by marusak** [comment]
@skobyda can you please take a look at [this log](https://logs.cockpit-project.org/logs/pull-889-20200522-082008-4a64ea5b-fedora-31-skobyda-cockpit-certificates/log.html#5-2)? Thanks!

**Comment by marusak** [comment]
Also happens in [starter-kit](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-889-20200522-150323-4a64ea5b-fedora-31-cockpit-project-starter-kit/log.html) although we allow this message by default.

**Comment by marusak** [comment]
Oh, so I was looking into the current master and this message it defined by default, but it used to be in `allow_authorize_journal_messages()` until 3ba7c189d33e71915166fa0370778beffc20370c .

This is the first f-31 image that has the new sudo stuff, so no surprise there.
There are two things that projects could do - either add `allow_authorize_journal_messages()` into every test (or setUp) or just update their test/common to at least 219.
We need it in c-certifikates and s-kit. I'll send PR to bump tests to 219 into both.

**Comment by marusak** [comment]
Sent https://github.com/skobyda/cockpit-certificates/pull/7 and https://github.com/cockpit-project/starter-kit/pull/317

**Comment by martinpitt** [comment]
Both PRs landed, retrying. The lorax tar test has been timing out for a while, that's not new.

**Comment by martinpitt** [comment]
[chrome on rhel8.2](https://logs.cockpit-project.org/logs/pull-889-20200523-055328-4a64ea5b-fedora-31-selenium-chrome-cockpit-project-cockpit-rhel-8.2/log.html#57) has a Machine storage pool failure. Retrying.

**Pull request merged**
