### PR TITLE
Image refresh for fedora-38

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-38
 * [x] image-refresh fedora-38

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-38-20230309-230101.log

**Comment by martinpitt** [comment]
[Eww](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4502-20230309-235104-2f869120-fedora-38-cockpit-project-cockpit-machines/log.html#9-2), what? Searching for "RHEL 4.9" finds "Debian 12"? Doing one retry to compare, checking if that is persistent or an existing flake.

**Comment by martinpitt** [comment]
That's persistent. Regression in osinfo-db?

    osinfo-db (20221130-2.fc38 -> 20230308-1.fc38)

**Review by martinpitt — APPROVED** [review]
Thanks!

**Pull request merged**
