### PR TITLE
Image refresh for fedora-rawhide-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-boot
 * [x] image-refresh fedora-rawhide-boot

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-boot-20230707-084848.log

**Comment by KKoukiou** [comment]
Looks like bash crashes :? 

```
[anaconda root@localhost ~]# coredumpctl gdb 6124
           PID: 6124 (bash)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Fri 2023-07-07 16:01:01 UTC (12min ago)
  Command Line: /bin/bash -c $'\nset -eu\n# new namespaces have lo down by default\nip link set lo up >&2\n\n# start browser in a temporary home dir, so that it does not interfere with your real one\nexport BROWSER_HOME=$(mktemp --directory --tmpdir cockpit.desktop.XXXXXX)\n\n# forward parent stdin and stdout (from bridge) to cockpit-ws\n# it pretty well does not matter which port we use in our own namespace, so use standard http\n# disable /etc/cockpit/\nXDG_CONFIG_DIRS="$BROWSER_HOME" COCKPIT_SUPERUSER="pkexec" /usr/libexec/cockpit-ws -p 80 -a 127.0.0.90 --local-session=- <&0 >&1 &\nWS_PID=$!\n# ... and stop using that stdin/out for everything else\nexec 0</dev/null\nexec 1>&2\n\ntrap "set +e; kill $WS_PID; wait $WS_PID; rm -rf $BROWSER_HOME" EXIT INT QUIT PIPE\n\n# if we have netcat, use it for waiting until ws is up\nif type nc >/dev/null 2>&1; then\n    for retry in `seq 10`; do\n        nc -z 127.0.0.90 80 && break\n        sleep 0.5;\n    done\nelse\n    # otherwise, just wait a bit\n    sleep 3\nfi\n\nHOME="$BROWSER_HOME" /usr/bin/firefox --kiosk http://127.0.0.90/cockpit/@localhost/anaconda-webui/index.html\n'
    Executable: /usr/bin/bash
 Control Group: /system.slice/anaconda.service/init.scope
          Unit: anaconda.service
         Slice: system.slice
       Boot ID: 154afee609aa4458a241a438858bf83d
    Machine ID: d8e3dbf9af7c4214aaf72b26f0b8bd0f
      Hostname: linux
       Storage: /var/lib/systemd/coredump/core.bash.0.154afee609aa4458a241a438858bf83d.6124.1688745661000000.zst (present)
  Size on Disk: 1.9M
       Package: bash/5.2.15-3.fc38
      build-id: 15780967f1c6ffb422b5832185766bee364d3c71
       Message: Process 6124 (bash) of user 0 dumped core.
                
                Module libtinfo.so.6 from rpm ncurses-6.4-5.20230520.fc39.x86_64
                Module bash from rpm bash-5.2.15-3.fc38.x86_64
                Stack trace of thread 6124:
                #0  0x0000564b6456388d yyparse (bash + 0x3a88d)
                #1  0x0000564b64567940 parse_command (bash + 0x3e940)
                #2  0x0000564b645dbb05 parse_and_execute (bash + 0xb2b05)
                #3  0x0000564b645b56f1 run_pending_traps (bash + 0x8c6f1)
                #4  0x0000564b64573129 execute_command_internal (bash + 0x4a129)
                #5  0x0000564b64575472 execute_command_internal (bash + 0x4c472)
                #6  0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #7  0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                #8  0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #9  0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                #10 0x0000564b645dc08b parse_and_execute (bash + 0xb308b)
                #11 0x0000564b645b56f1 run_pending_traps (bash + 0x8c6f1)
                #12 0x0000564b64573129 execute_command_internal (bash + 0x4a129)
                #13 0x0000564b64575472 execute_command_internal (bash + 0x4c472)
                #14 0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #15 0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                #16 0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #17 0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                #18 0x0000564b645dc08b parse_and_execute (bash + 0xb308b)
                #19 0x0000564b645b56f1 run_pending_traps (bash + 0x8c6f1)
                #20 0x0000564b64573129 execute_command_internal (bash + 0x4a129)
                #21 0x0000564b64575472 execute_command_internal (bash + 0x4c472)
                #22 0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #23 0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                #24 0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #25 0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                #26 0x0000564b645dc08b parse_and_execute (bash + 0xb308b)
                #27 0x0000564b645b56f1 run_pending_traps (bash + 0x8c6f1)
                #28 0x0000564b64573129 execute_command_internal (bash + 0x4a129)
                #29 0x0000564b64575472 execute_command_internal (bash + 0x4c472)
                #30 0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #31 0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                #32 0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #33 0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                #34 0x0000564b645dc08b parse_and_execute (bash + 0xb308b)
                #35 0x0000564b645b56f1 run_pending_traps (bash + 0x8c6f1)
                #36 0x0000564b64573129 execute_command_internal (bash + 0x4a129)
                #37 0x0000564b64575472 execute_command_internal (bash + 0x4c472)
                #38 0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #39 0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                #40 0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #41 0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                #42 0x0000564b645dc08b parse_and_execute (bash + 0xb308b)
                #43 0x0000564b645b56f1 run_pending_traps (bash + 0x8c6f1)
                #44 0x0000564b64573129 execute_command_internal (bash + 0x4a129)
                #45 0x0000564b64575472 execute_command_internal (bash + 0x4c472)
                #46 0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #47 0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                #48 0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #49 0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                #50 0x0000564b645dc08b parse_and_execute (bash + 0xb308b)
                #51 0x0000564b645b56f1 run_pending_traps (bash + 0x8c6f1)
                #52 0x0000564b64573129 execute_command_internal (bash + 0x4a129)
                #53 0x0000564b64575472 execute_command_internal (bash + 0x4c472)
                #54 0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #55 0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                #56 0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #57 0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                #58 0x0000564b645dc08b parse_and_execute (bash + 0xb308b)
                #59 0x0000564b645b56f1 run_pending_traps (bash + 0x8c6f1)
                #60 0x0000564b64573129 execute_command_internal (bash + 0x4a129)
                #61 0x0000564b64575472 execute_command_internal (bash + 0x4c472)
                #62 0x0000564b64575e3e execute_command (bash + 0x4ce3e)
                #63 0x0000564b64575429 execute_command_internal (bash + 0x4c429)
                ELF object binary architecture: AMD x86-64

GNU gdb (Fedora Linux) 13.2-2.fc39
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/bash...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.fedoraproject.org/>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Reading symbols from /root/.cache/debuginfod_client/15780967f1c6ffb422b5832185766bee364d3c71/debuginfo...                                                                                                                                    
[New LWP 6124]
[Thread debugging using libthread_db enabled]                                                                                                                                                                                                
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/bin/bash -c 
set -eu
# new namespaces have lo down by default
ip link set lo u'.
Program terminated with signal SIGSEGV, Segmentation fault.
Python Exception <class 'NameError'>: Installation error: gdb._execute_unwinders function is missing
#0  yyparse () at /usr/src/debug/bash-5.2.15-3.fc38.x86_64/y.tab.c:1741
1741      yychar = YYEMPTY; /* Cause a token to be read.  */                                                                                                                                                                                 
(gdb) 

```

**Comment by jkonecny12** [comment]
This looks like a broken Rawhide. Possible issue raised from Python 3.12?

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-boot-20230711-141818.log

**Comment by martinpitt** [comment]
I pushed the image refresh from @jkonecny12 above, let's give it a spin.

**Comment by martinpitt** [comment]
Nope, [still fails](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4976-20230712-054728-0c3d6e1f-fedora-rawhide-boot-rhinstaller-anaconda/log.html)

**Comment by KKoukiou** [comment]
Happening also on anaconda master - but looks like more an easy flake there. Here is more consistent. https://cockpit-logs.us-east-1.linodeobjects.com/pull-4873-20230714-080058-58cc4151-fedora-rawhide-boot/log.html#3

**Comment by KKoukiou** [comment]
tests run here https://github.com/rhinstaller/anaconda/pull/4919

Bash crash was work-arounded - never reported upstream as creating a simple reproducer was not easy.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
