### PR TITLE
Arch clevis tang stratisd support all the things

### PR DESCRIPTION
**Pull request by jelly**
* [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-3998-20221025-152323/

**Comment by jelly** [comment]
Triggered a test run with a fix to enable the tang/clevis test https://cockpit-logs.us-east-1.linodeobjects.com/pull-17844-20221025-155834-cfb5e790-arch-bots-3998/log.html

**Comment by jelly** [comment]
Works!

# 1 TEST PASSED [86s on 3-cockpit-7]
ok 318 test/verify/check-storage-luks TestStorageLuks.testClevisTang # RETRY 1 (test affected tests 3 times)

**Review by mvollmer — APPROVED** [review]
Thanks!

**Pull request merged**
