### PR TITLE
Image refresh for rhel-9-0

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-0
 * [x] image-refresh rhel-9-0
 * [x] glibc 2.34 needs to enter BaseOS to become installable again

### CODE REVIEW

**Comment by martinpitt** [comment]
[broken build](https://logs.cockpit-project.org/logs/pull-2191-20210708-022643-5b717e15-rhel-9-0-cockpit-project-cockpit/log.html), smells like buildroot has a newer glibc than BaseOS. This is a well-known structural problem in RHEL, not sure if we can do anything else but wait.

**Comment by allisonkarlitskaya** [comment]
We solved a similar issue with selinux-policy before: 5cee11198658befdfa50338a483f9967b4d6528d

**Comment by martinpitt** [comment]
BaseOS nightly has that glibc version, retrying.

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-2191-20210709-121717/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20210709-123434

**Comment by martinpitt** [comment]
[This failure](https://logs.cockpit-project.org/logs/pull-2191-20210709-124557-a8fe4fbb-rhel-9-0-cockpit-project-cockpit/log.html#83) is supposed to be known issue #2162, we already have a naughty. Needs a close look.

**Comment by martinpitt** [comment]
I fixed the glob pattern.

**Review by allisonkarlitskaya — APPROVED** [review]

**Pull request merged**
