### PR TITLE
Image refresh for fedora-33

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-33

 * [x] image-refresh fedora-33
 * [x] https://github.com/cockpit-project/cockpit/pull/14655
 * [x] https://github.com/cockpit-project/cockpit/pull/14659
 * [x] https://github.com/cockpit-project/cockpit/pull/14661

### CODE REVIEW

**Comment by marusak** [comment]
[podman](https://logs.cockpit-project.org/logs/pull-1240-20200917-181458-73d5ae60-fedora-33-cockpit-project-cockpit-podman/log.html) and [perf-graphs](https://logs.cockpit-project.org/logs/pull-1240-20200917-181458-73d5ae60-fedora-33-martinpitt-performance-graphs/log.html) fail miserable. It expects `#authorzed-input` on the login page but that was dropped.  F33 was the first to recognize this. I'll send update to all affected projects.

**Comment by marusak** [comment]
Blocks on https://github.com/cockpit-project/cockpit-podman/pull/538

**Comment by mvollmer** [comment]
> It expects `#authorzed-input` on the login page but that was dropped. F33 was the first to recognize this. I'll send update to all affected projects.

Ouch, thanks!

**Comment by mvollmer** [comment]
podman and performance-graphs have been updated.

**Comment by martinpitt** [comment]
The [cockpit test aborted prematurely](https://logs.cockpit-project.org/logs/pull-1240-20200921-190952-73d5ae60-fedora-33-cockpit-project-cockpit/log.html), this looks like an old race on the host, though.

**Comment by martinpitt** [comment]
This keeps happening, needs investigation.

**Comment by martinpitt** [comment]
FTR, the [same error happens on other images](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-1244-20200922-053808-1edc1046-fedora-32-firefox-cockpit-project-cockpit/log). It's just something subtle about the timing here, or that many of our bots now have abandoned stopped domains?

**Comment by mvollmer** [comment]
Blocked on https://github.com/cockpit-project/cockpit/pull/14655

**Comment by mvollmer** [comment]
TestSOS.testBasic seems to time out pretty reliably.

**Comment by mvollmer** [comment]
> TestSOS.testBasic seems to time out pretty reliably.

There still is the occasional timeout even with https://github.com/cockpit-project/cockpit/pull/14655, hmm. 10 minutes might cut it too close for the full set of plugins.  Let's try a couple more times to gather some data.

**Comment by mvollmer** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1818089 has been fixed in fedora-33 and the tests need adapting.

**Comment by mvollmer** [comment]
Proof that #14661 makes this green: https://logs.cockpit-project.org/logs/pull-14661-20200924-081041-e26322dd-fedora-33-bots-1240/log.html

**Review by mvollmer — APPROVED** [review]

**Pull request merged**
