### PR TITLE
images: Don't fail on missing /var/lib/insights/ on centos-9-stream

### LINKED ISSUE #3298: Image refresh for centos-9-stream - fixed in #3299
Image refresh for centos-9-stream
 * [ ] FAIL: image-refresh centos-9-stream

### PR DESCRIPTION
**Pull request by martinpitt**
commit 9d0226d82d broke building centos-*-stream images, which do not
have insights-client. Move that call into the insights conditional code.

Fixes #3298

 * [x] image-refresh centos-8-stream
 * [x] image-refresh centos-9-stream
 * [x] image-refresh rhel-9-0

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-m7qcm.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3299-20220426-044848/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3299-20220426-044848/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-tbzbx.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3299-20220426-044949/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20220426-050404

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-tbzbx.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3299-20220426-050404/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-tbzbx.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3299-20220426-050606/

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20220426-053434

**Comment by cockpituous** [comment]
image-refresh in progress on 7-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-3299-20220426-053434/

**Comment by cockpituous** [comment]
Task threw an exception: https://logs.cockpit-project.org/logs/image-refresh-3299-20220426-053434/

**Comment by cockpituous** [comment]
image-refresh in progress on 7-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-3299-20220426-060000/

**Comment by cockpituous** [comment]
Task threw an exception: https://logs.cockpit-project.org/logs/image-refresh-3299-20220426-060000/

**Comment by cockpituous** [comment]
image-refresh in progress on 12-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-3299-20220426-063131/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-3299-20220426-065555/

**Comment by cockpituous** [comment]
Task threw an exception: https://logs.cockpit-project.org/logs/image-refresh-3299-20220426-063131/

**Review by jelly — APPROVED** [review]

**Pull request merged**
