### PR TITLE
Image refresh for fedora-35

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-35
 * [x] image-refresh fedora-35
 * https://github.com/rhinstaller/anaconda/pull/3875
 * https://github.com/cockpit-project/cockpit-podman/pull/933
 * https://github.com/cockpit-project/cockpit-certificates/pull/83

### CODE REVIEW

**Comment by martinpitt** [comment]
@KKoukiou, @M4rtinK : You mentioned the [python thing](https://logs.cockpit-project.org/logs/pull-2960-20220218-023738-68b53133-fedora-35-rawhide-rhinstaller-anaconda/log.html) yesterday, are you on that?

**Comment by martinpitt** [comment]
Oh, it's part of https://github.com/rhinstaller/anaconda/pull/3875 , blocking on that

**Comment by martinpitt** [comment]
Anaconda is broken on the current image as well, as that's related to the tasks container refresh, not the f35 image.

However, the [stratis pixel test failure](https://logs.cockpit-project.org/logs/pull-2960-20220218-023738-68b53133-fedora-35-cockpit-project-cockpit/log.html#216) is odd. It's highly unlikely that it is related to the image, but let's retry and compare.

**Comment by martinpitt** [comment]
Anaconda got unblocked, but the stratis pixel test failure stays. Needs investigation.

**Comment by mvollmer** [comment]
Blocked on https://github.com/cockpit-project/cockpit/pull/17051

**Comment by martinpitt** [comment]
All blockers resolved. I pushed a clean rebase.

**Comment by martinpitt** [comment]
This now fails on a whole slew of new eslint errors. Could possibly be related to the eslint breakage worked around in https://github.com/cockpit-project/cockpit-machines/pull/597 , but possibly the new eslint version just became a whole lot stricter.

**Comment by martinpitt** [comment]
I checked the [eslint errors in c-podman](https://logs.cockpit-project.org/logs/pull-2960-20220225-105922-fa4d4ff4-fedora-35-cockpit-project-cockpit-podman/log.html); locally I don't get the "missing key" errors any more, just the two  react/jsx-indent errors, and they are both bogus. The parser gets thoroughly confused.

starter-kit builds fine for me locally, even though [on CI last week](https://logs.cockpit-project.org/logs/pull-2960-20220225-105932-fa4d4ff4-fedora-35-cockpit-project-start er-kit/log.html) it ran into several key-errors as well.

The key errors were all due to https://github.com/yannickcr/eslint-plugin-react/issues/3215 , so I'll do a round of retries to get an up to date status.

**Comment by martinpitt** [comment]
Auf ein neues!

**Review by martinpitt — APPROVED** [review]
At last! :partying_face:

**Pull request merged**
