### PR TITLE
arch: disable systemd-time-wait-sync

### PR DESCRIPTION
**Pull request by jelly**
This causes a 30 second delay as enabling systemd-time-wait-sync seems to cause systemd-timesyncd to hit a timeout of 30 seconds. As we run our images offline for tests, we want to disable this anyway.

 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-3913-20220928-102020/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3913-20220928-102020/

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-12.
Log: https://logs.cockpit-project.org/logs/image-refresh-3913-20220928-102929/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3913-20220928-102929/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3913-20220929-115555/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3913-20220929-115555/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-3913-20221004-083131/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3913-20221004-083131/

**Comment by jelly** [comment]
New cloud image is out, let's retry.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-3913-20221018-081919/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3913-20221018-081919/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3913-20221018-082929/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3913-20221018-151717/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3913-20221018-151717/

**Comment by jelly** [comment]
Adding a timeout did not help, so this needs debugging why the machine does not start

**Comment by jelly** [comment]
The machine does not boot due to systemd-time-wait-sync.service, this just hangs on the first boot on our CI

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-3913-20221020-101616/

**Comment by jelly** [comment]
So on boot:
```
[root@archlinux ~]# systemctl list-jobs | grep runn
45  systemd-time-wait-sync.service   start running
[root@archlinux ~]# networkctl status
●        State: routable
  Online state: online
       Address: 172.27.0.15 on eth0
                fec0::5054:ff:fe12:3456 on eth0
                fe80::5054:ff:fe12:3456 on eth0
       Gateway: 172.27.0.2 on eth0
                fe80::2 on eth0
           DNS: 172.27.0.3
```

A simple curl works:
```
curl https://pkgbuild.com
```

System is however not booted:
```
[root@archlinux ~]# systemd-analyze blame
Bootup is not yet finished (org.freedesktop.systemd1.Manager.FinishTimestampMonotonic=0).
Please try again later.
Hint: Use 'systemctl list-jobs' to see active jobs
```

```
[root@archlinux ~]# systemctl list-jobs | grep runn
45  systemd-time-wait-sync.service   start running
[root@archlinux ~]#
```

```
[root@archlinux ~]# SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-time-wait-sync
adjtime state 5 status 40 time Thu 2022-10-20 11:58:04.606071 UTC
```

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-5.
Log: https://logs.cockpit-project.org/logs/image-refresh-3913-20221020-133232/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3913-20221020-133232/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3913-20221020-133535/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3913-20221020-133535/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-3913-20221020-135151/

**Pull request closed without merging**
