### PR TITLE
Image refresh for centos-8-stream

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-8-stream
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by martinpitt** [comment]
[vdo troubles](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-2949-20220217-023742-a005df9a-centos-8-stream-cockpit-project-cockpit/log.html#225-2)

**Comment by marusak** [comment]
So it is not broken per se - but something fishy is surely happening. Sometimes `rpm` is stuck on `rpm -e --no-deps kmod-kvdo` - which we do as cleanup after `self.createPackage("kmod-kvdo", "999", "1")`.

I wonder, why we even create the package, as we have it in the VM:
```
kmod-kvdo-6.2.6.14-83.el8.x86_64
```
and when we run the `rpm -e kmod-kvdo` we remove the version from distro and not the version we created.

So either we don't need to create this package, or create it only when it is not present. I'll send PR to check if we need it first.

**Comment by martinpitt** [comment]
I suppose we could restrict the test case to RHEL and CentOS, which actually have a vdo package. So far the test runs everywhere. Also note that the test covers on-demand installation, so you'll have to remove and build at least one fake package.

**Comment by marusak** [comment]
> Also note that the test covers on-demand installation, so you'll have to remove and build at least one fake package.

Yes, it also does create `vdo` package: https://github.com/cockpit-project/cockpit/pull/17020/files#diff-963506329ee019eba7b52956adab34de2bddb814a265f291eeee24d518719db7L444

**Comment by martinpitt** [comment]
Meh, [two failures](https://logs.cockpit-project.org/logs/pull-2949-20220217-155454-566aeafc-centos-8-stream-cockpit-project-cockpit/log.html#137-2), but they look familiar.

**Comment by martinpitt** [comment]
Yep, [same failures as in another PR](https://logs.cockpit-project.org/logs/pull-17016-20220217-154950-74cea3f0-centos-8-stream/log.html), so unrelated.

**Review by marusak — APPROVED** [review]

**Pull request merged**
