### PR TITLE
images: Display the boot messages on tumbleweed

### PR DESCRIPTION
**Pull request by Nykseli**
Set linux boot arguments to display the boot messages so it's easier to see what's going on when images are failing to build

- [ ] image-refresh: opensuse-tumbleweed

### CODE REVIEW

**Comment by jelly** [comment]
Do you want me to refresh the opensuse image?

**Comment by Nykseli** [comment]
Yes please!

**Comment by Nykseli** [comment]
Thanks!

**Comment by Nykseli** [comment]
Cherry picked the image refresh commit

**Comment by jelly** [comment]
Merged via https://github.com/cockpit-project/bots/pull/6447

**Comment by Nykseli** [comment]
Thanks!

**Pull request closed without merging**
