### PR TITLE
Image refresh for fedora-rawhide-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-boot
 * [x] image-refresh fedora-rawhide-boot

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-boot done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-boot-20240524-223949

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-boot-eddb571f-20240524-223724/log.html

**Comment by martinpitt** [comment]
@M4rtinK @KKoukiou does that ring a bell? do you see that in the kickstart-tests?
```
ERROR    Error validating install location: Could not find an installable distribution at URL '/work/make-checkout-workdir/bots/images/fedora-rawhide-boot'

The location must be the root directory of an install tree.
```

**Comment by KKoukiou** [comment]
> @M4rtinK @KKoukiou does that ring a bell? do you see that in the kickstart-tests?
> 
> ```
> ERROR    Error validating install location: Could not find an installable distribution at URL '/work/make-checkout-workdir/bots/images/fedora-rawhide-boot'
> 
> The location must be the root directory of an install tree.
> ```

It's not persistent.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
