### PR TITLE
Image refresh for rhel-8-4

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-4
 * [x] image-refresh rhel-8-4

### CODE REVIEW

**Comment by skobyda** [comment]
@martinpitt @marusak 
Do you know what does this failure mean? https://logs.cockpit-project.org/logs/pull-1836-20210323-090903-dfd80512-rhel-8-4-osbuild-composer-weldr-lorax-rhel8-branch/log.html

**Comment by marusak** [comment]
It means that 20 is different from 0 :)
(real answer: those tests are not the most stable (I think they even depend on external resources), so please retry. If it persists then ask "atodorov")

**Comment by martinpitt** [comment]
@atodorov: Seems the [new image](https://logs.cockpit-project.org/logs/pull-1836-20210323-125148-dfd80512-rhel-8-4-osbuild-composer-weldr-lorax-rhel8-branchm/log.html) regresses something? Or is "compose_sanity" hitting the network, and it's not dependent on the image?

**Comment by martinpitt** [comment]
There is no recent weldr/lorax/rhel8-branch PR, so I sent https://github.com/weldr/lorax/pull/1130 . This will tell us whether the regression is due to the new image or the RHEL repo.

**Review by martinpitt — APPROVED** [review]
Same error on the current image: https://github.com/weldr/lorax/pull/1130#issuecomment-805526068

**Pull request merged**
