### PR TITLE
Image refresh for rhel-8-6

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-6
 * [x] image-refresh rhel-8-6

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20240424-230426

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-8-6-d52d6a28-20240424-223720/log.html

**Comment by martinpitt** [comment]
@ptoscano Can you please backport the recent test fixes to the stable branches? Thanks!

**Review by martinpitt — APPROVED** [review]
Not a regression, and let's not block this for too long.

**Pull request merged**
