### PR TITLE
Image refresh for fedora-37

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-37
 * [x] image-refresh fedora-37

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-37-20230115-225959.log

**Comment by cockpituous** [comment]
image-refresh fedora-37 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-37-20230115-230342

**Comment by cockpituous** [comment]
Completed. Log: Error accessing /repos/cockpit-project/bots/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value":4275,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}

**Comment by marusak** [comment]
Python bridge [failed](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4275-20230115-230045-15e4e070-fedora-37-pybridge-cockpit-project-cockpit/log.html#57) because `check-metrics TestCurrentMetrics.testCPU` succeeded but it is expected to fail. @jelly I think you commented that this test works if you sleep for a bit in it, right? So we should mark it as flaky?

**Comment by jelly** [comment]
> Python bridge [failed](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4275-20230115-230045-15e4e070-fedora-37-pybridge-cockpit-project-cockpit/log.html#57) because `check-metrics TestCurrentMetrics.testCPU` succeeded but it is expected to fail. @jelly I think you commented that this test works if you sleep for a bit in it, right? So we should mark it as flaky?

No that was a different test, which deletes the manifest. This might actually be related to the AMD CPU sensor fix.

**Review by marusak — APPROVED** [review]

**Pull request merged**
