### PR TITLE
Image refresh for centos-8-stream

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-8-stream
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by martinpitt** [comment]
Looks like [libvirt is going mad](https://logs.cockpit-project.org/logs/pull-593-20200302-143940-37fbbc6c-centos-8-stream-cockpit-project-cockpit/log.html)?

**Comment by marusak** [comment]
```
error: Failed to start domain subVmTest1
error: Machine 'qemu-1-subVmTest1' already exists
```
Lets try this again with https://github.com/cockpit-project/cockpit/pull/13635

**Comment by marusak** [comment]
Rebased as services image changed underneath it.

**Comment by martinpitt** [comment]
[Looking much better](https://logs.cockpit-project.org/logs/pull-593-20200304-173156-5ab42c7f-centos-8-stream-cockpit-project-cockpit/log.html#79-2). It now fails due to the bug fixed in https://github.com/cockpit-project/cockpit/pull/13650

**Pull request merged**
