### PR TITLE
images: Use quay.io to pull cockpit/ws

### LINKED ISSUE #1898: Image refresh for fedora-coreos
Image refresh for fedora-coreos
 * [ ] FAIL: image-refresh fedora-coreos

### PR DESCRIPTION
**Pull request by marusak**
Fixes #1898

 * [x] image-refresh fedora-coreos

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-1901-20210408-122222/

**Comment by cockpituous** [comment]
image-refresh fedora-coreos done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-coreos-20210408-123131

**Comment by marusak** [comment]
hmm
```
rm: cannot remove '/etc/systemd/system/cockpit.service': No such file or directory
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-connection", line 75, in testBasic
    self.ostree_setup_ws()
  File "/work/bots/make-checkout-workdir/test/verify/check-connection", line 49, in ostree_setup_ws
    m.execute("rm /etc/systemd/system/cockpit.service")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 351, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'rm /etc/systemd/system/cockpit.service' returned non-zero exit status 1.
```

**Comment by marusak** [comment]
Locally when I removed this command it all worked just fine, trying it out in https://github.com/cockpit-project/cockpit/pull/15670

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit-container/blob/master/atomic-install#L47
here `container` is `oci` and not `podman`.

**Comment by marusak** [comment]
When https://github.com/cockpit-project/cockpit/pull/15670 lands, it needs to be synced into c-containers and then this image needs to be refreshed once again with the new container.

**Comment by marusak** [comment]
Oh right, `containers/ws/atomic-install ` is used dynamically and from the container. Thus this needs to land in lockstep with https://github.com/cockpit-project/cockpit/pull/15670

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit/pull/15670 as green as it gets

**Review by martinpitt — APPROVED** [review]
Cheers!

**Pull request merged**
