### PR TITLE
Image refresh for services

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for services
 * [x] image-refresh services
 * [x] fix check-subscriptions for multiple pools: https://github.com/cockpit-project/cockpit/pull/15714
 * [x] validate services image refresh against subscription-manager: PR #1938

### CODE REVIEW

**Comment by martinpitt** [comment]
[candlepin failure](https://logs.cockpit-project.org/logs/pull-1935-20210418-023726-2a03eeb1-rhel-7-9-cockpit-project-cockpit-rhel-7.9/log.html) or timeout, retrying to compare -- it seemed fine on cockpit/master run

**Comment by martinpitt** [comment]
The root cause is that there are now two pools:
```
# curl -s --insecure --request GET --user admin:admin https://localhost:8443/candlepin/pools | jq -r '.[] | select(.owner.key == "admin") | select(.contractNumber == "0") | select(.providedProducts[0].productId == "88888") | .id'
8ad8808378e2c8a70178e2c9c1a00320
8ad8808378e2c8a70178e2c9c1db0322
```
the previous image just had one.

They don't differ by much, so let's just pick the first one.

**Comment by martinpitt** [comment]
In addition I noticed that the current (not this refreshed) services image immediately reboots after booting, due to auto-updates. Let's disable these.

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-1935-20210419-061818/

**Comment by cockpituous** [comment]
image-refresh services done: https://github.com/cockpit-project/bots/commits/image-refresh-services-20210419-065353

**Comment by martinpitt** [comment]
[TestGrowShrink failure](https://logs.cockpit-project.org/logs/pull-1935-20210419-072336-0586f6cd-fedora-33-cockpit-project-cockpit/log.html#193-2), but this is really brittle -- retrying once to compare

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
