### PR TITLE
images: Check for files that are shipped by multiple RPMs

### PR DESCRIPTION
**Pull request by martinpitt**
This reproduces https://bugzilla.redhat.com/show_bug.cgi?id=1870521
in a very generic way, and ensures that it does not happen in the
future.

 - [ ] Fix duplicated files in -debuginfo: https://github.com/cockpit-project/cockpit/pull/14650

### CODE REVIEW

**Comment by martinpitt** [comment]
test/image-prepare rhel-8-3 now fails with lots of messages like:
```
ERROR: /usr/share/cockpit/systemd/hwinfo.js.map is shipped by multiple packages: cockpit-appstream-debuginfo-228.10.g251810d15-1.wip.el8.x86_64 cockpit-debuginfo-228.10.g251810d15-1.wip.el8.x86_64
```
Setting this to blocked until we actually fix this in cockpit master.

**Comment by martinpitt** [comment]
This is now ready for review. Still blocked by [the actual fix](https://github.com/cockpit-project/cockpit/pull/14650) of course, but this will be green after that lands.

**Review by marusak — APPROVED** [review]
Nice, thanks!

**Comment by marusak** [comment]
The fix landed, retrying tests

**Pull request merged**
