### PR TITLE
Image refresh for fedora-rawhide-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-boot
 * [x] image-refresh fedora-rawhide-boot
 * [x] https://github.com/cockpit-project/cockpit/pull/20663
 * [x] Pull that into anaconda-webui: https://github.com/rhinstaller/anaconda-webui/pull/322

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-boot done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-boot-20240624-224128

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-boot-4cbfdf2a-20240624-223801/log.html

**Comment by martinpitt** [comment]
ls: cannot access '/home': No such file or directory

What now? We can certainly fix this in our testlib, but how is /home not a thing? @KKoukiou any idea?

**Comment by KKoukiou** [comment]
> ```
> ls: cannot access '/home': No such file or directory
> ```
> 
> What now? We can certainly fix this in our testlib, but how is /home not a thing? @KKoukiou any idea?

/home is expected to be not there: 
https://github.com/weldr/lorax/blob/62c7426c2838f4de4efa9b11d7de800eed36a18f/share/templates.d/99-generic/runtime-cleanup.tmpl#L66

systemd was creating it till now, but because of https://src.fedoraproject.org/rpms/systemd/c/a76669ee222fc4374f14f7e2a6e9a28c5ad87c0e?branch=rawhide not any more. Thanks to @jstodola for checking.

We will need to adjust the cleanup functions for this image.

**Comment by martinpitt** [comment]
@KKoukiou ok! I created https://github.com/cockpit-project/cockpit/pull/20663 . Once that lands, can you please pull it into a-w?

**Comment by martinpitt** [comment]
@KKoukiou I triggered a lib import in a-w, see updated todo list.

**Review by martinpitt — APPROVED** [review]
This ought to work now.

**Pull request merged**
