### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-testing-20230706-230606.log

**Comment by jelly** [comment]
TestApplication.testPods failed retrying..

**Comment by jelly** [comment]
```
  container-selinux (2:2.218.0-1.fc38 -> 2:2.219.0-1.fc38)
  podman (5:4.5.1-1.fc38 -> 5:4.6.0~rc1-1.fc38)
  podman-gvproxy (5:4.5.1-1.fc38 -> 5:4.6.0~rc1-1.fc38)
  ```

**Comment by jelly** [comment]
Test PR to adjust the exception message https://github.com/cockpit-project/cockpit-podman/pull/1343

**Review by jelly — APPROVED** [review]

**Pull request merged**
