### PR TITLE
Image refresh for centos-9-bootc

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-9-bootc
 * [x] image-refresh centos-9-bootc
 * [x] Requires https://github.com/cockpit-project/cockpit-podman/pull/1731

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh centos-9-bootc done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-bootc-20240527-230222

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-9-bootc-96f5ad5d-20240527-223747/log.html

**Comment by martinpitt** [comment]
This is similar to https://github.com/containers/podman/issues/21896 and https://bugzilla.redhat.com/show_bug.cgi?id=2277954 and will affect RHEL 9 as well. I looked at this before, so I'll take the piloting for this one @mvollmer . Needs jira issue and workaround.

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit-podman/pull/1731 to fix this and updated the bugzilla.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
