### PR TITLE
Image refresh for ubuntu-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for ubuntu-stable
 * [x] Retract or fix policykit-1 update: https://launchpad.net/bugs/2089145 
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20241129-225754

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-stable-31564386-20241129-224207/log.html

**Comment by martinpitt** [comment]
This is a regression from https://launchpad.net/bugs/2089145 . This is a proposed update, I stopped it from being released. I block this update until Wednesday, until then there should either be a retraction or a fix. If not, I can send a PR to pin the previous package version.

**Comment by martinpitt** [comment]
The broken package was updated, so rolling the dice again.

**Comment by martinpitt** [comment]
→ #7175

**Pull request closed without merging**
