### PR TITLE
machine: Fix crash when not capturing console

### PR DESCRIPTION
**Pull request by martinpitt**
Regression introduced in commit d600552.

 * [x] image-refresh rhel-9-0

This broke our image refreshes since yesterday evening, e.g. https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-0-20230907-225555.log

### CODE REVIEW

**Comment by martinpitt** [comment]
Eww, this also [breaks tests](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20230908-014746-bc9025bb-fedora-38-updates-testing/log.html). So this is super-duper-urgent. I'll take the bullet and self-land, triggering a quick test here to confirm.

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20230908-035456

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-0-20230908-035454.log

**Comment by martinpitt** [comment]
[tests work again](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5227-20230908-033827-f7c20b47-fedora-38-cockpit-project-cockpit-podman/log.html), and the image refresh succeeded as well. Landing now to unbreak all of our CI.

That taught me to be more careful next time, and check a successful image refresh and a test for such changes...

@skobyda can you please retroactively review, just in case? Thanks!

**Pull request merged**
