### PR TITLE
images: add virtiofsd for fedora-39 and higher

### PR DESCRIPTION
**Pull request by tomasmatus**
virtiofsd is now a separate package

 * [x] image-refresh fedora-39

### CODE REVIEW

**Comment by martinpitt** [comment]
Starting image build

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-39-20230825-083333.log

**Comment by cockpituous** [comment]
image-refresh fedora-39 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-39-20230825-085901

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-39-20230825-085959.log

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
