### PR TITLE
testmap: Test cockpit-machines on fedora-35

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] https://github.com/cockpit-project/cockpit-machines/pull/387

### CODE REVIEW

**Comment by mvollmer** [comment]
Seems like explicitly starting libvirtd.service is the wrong thing to do now: https://bugzilla.redhat.com/show_bug.cgi?id=1998066#c2

**Comment by skobyda** [comment]
* [ ] image-refresh fedora-35

**Comment by skobyda** [comment]
* [ ] image-refresh fedora-35

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-2349-20210908-102525/

**Comment by cockpituous** [comment]
image-refresh fedora-35 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-35-20210908-104444

**Comment by skobyda** [comment]
Fix sent: https://github.com/cockpit-project/cockpit-machines/pull/355

**Comment by martinpitt** [comment]
FTR, this image refresh is too old, I removed the bots branch. I also think it's not directly related to the problem at hand here.

**Review by KKoukiou — APPROVED** [review]

**Comment by martinpitt** [comment]
Succeeded in https://github.com/cockpit-project/cockpit-machines/pull/387

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
