### PR TITLE
Move (most of) tests from F30 to F31

### PR DESCRIPTION
**Pull request by marusak**
* [x] image-refresh fedora-31
 * [x] image-refresh fedora-testing

- [x] Make better use of OS_DEFAULT in Cockpit - https://github.com/cockpit-project/cockpit/pull/13497
- [x] Drop selenium docker - https://github.com/cockpit-project/cockpit/pull/13504
- [x] Drop selenium docker 7.8 - https://github.com/cockpit-project/cockpit/pull/13510
- [x] Drop selenium docker 8.2 - https://github.com/cockpit-project/cockpit/pull/13511
- [x] Update storage message - https://github.com/cockpit-project/cockpit/pull/13512
- [x] Fix windows going to sleep after 30min - https://github.com/cockpit-project/bots/pull/522
- [x] Wait default time for machine to reboot - https://github.com/cockpit-project/cockpit/pull/13517/
- [x] Wait default time for machine to reboot  8.2 - https://github.com/cockpit-project/cockpit/pull/13537 
- [x] Fix testSessionRecordingShell - https://github.com/cockpit-project/cockpit/pull/13539
- [x] testCreateTimer (check_services.TestServices) - https://github.com/cockpit-project/cockpit/pull/13540
- [ ] testConfigureBeforeInstall (check_machines_dbus.TestMachinesDBus)
- [x] cockpit times out while composer is building images - https://github.com/weldr/cockpit-composer/pull/890
 - [x] selenium MachinesBasicTestSuite.testNoVm: https://github.com/cockpit-project/cockpit/pull/13564

Follow ups:
- Move bastion to F31 (we need to replace docker with podman)

### CODE REVIEW

**Comment by marusak** [comment]
`/usr/bin/python3: No module named avocado` hmm

**Comment by marusak** [comment]
ah obviously, `.setup` is run on `image-create` not in prepare stage.

- [ ] image-refresh fedora-31

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-501-20200206-104242/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-501-20200206-104242/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-05.
Log: https://209.132.184.41:8493/logs/image-refresh-501-20200206-113232/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-501-20200206-113232/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-06.
Log: https://209.132.184.41:8493/logs/image-refresh-501-20200206-121212/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-501-20200206-121212/

**Comment by marusak** [comment]
image-upload failed 3 times, hopefully now there is enough space

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-04.
Log: https://209.132.184.41:8493/logs/image-refresh-501-20200206-125959/

**Comment by cockpituous** [comment]
image-refresh fedora-31 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-31-20200206-134545

**Comment by marusak** [comment]
selenium docker tests are going to fail (for obvious reason).

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-501-20200207-065858/

**Comment by cockpituous** [comment]
image-refresh fedora-31 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-31-20200207-073131

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://209.132.184.41:8493/logs/image-refresh-501-20200207-073232/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-testing-20200207-081919

**Comment by marusak** [comment]
If we want to test bastion of F31, we need to move from docker to podman. Dropping this migration for now in this PR as it needs more work and also rebuilding F31 image.

**Comment by marusak** [comment]
Aaah, so 'testSlots' and 'testLuks' are failing with `/dev/sda could not be opened.`. The message used to be `Device is not initialized (/dev/sda)`.  This need to be updated in cockpit. I'll send a PR.

**Comment by marusak** [comment]
`selenium-machines-basic.py (MachinesBasicTestSuite.testForceRestartVm) ` failed on all browsers. Possibly another broken thing? Retrying to compare. [Example](https://209.132.184.41:8493/logs/pull-501-20200207-101212-afdf91c8-fedora-31-selenium-firefox-cockpit-project-cockpit/log.html#28)

**Comment by martinpitt** [comment]
The cockpit 7.8 and 8.2 backports of "drop selenium docker" landed, retrying tests.

**Comment by marusak** [comment]
yeah, '' is broken. It fails on:
```
              wait(lambda: re.search("login:.*Initializing cgroup",               
                                   self.machine.execute("sudo cat {0}".format(args.get('logfile')))), tries=10)
```
in `test/selenium/selenium-machines-basic.py:52`. It seems that just the output has changed. Needs a bit of investigation and then PR into master and both stable branches :(

**Comment by martinpitt** [comment]
@marusak: I sent PR #519 to increase the DHCP lease time. This maaaaaay help with the selenium tests, but I haven't locally run them with the new image.

**Comment by martinpitt** [comment]
I ran this locally. What happens exactly after 30 mins is that Windows either auto-logouts or turns on the automatic screen lock. That's the time when it loses its IP, and ping stops working. So we need a programmatic way to disable/extend the screen timeout.

**Comment by martinpitt** [comment]
After some extensive searching I [found a guide ](https://troubleshooter.xyz/wiki/change-lock-screen-timeout-setting-in-windows-10/#Method_4_Change_Lock_screen_timeout_Settings_using_Command_Prompt) that points to `powercfg.exe`. Indeed I can run this in a non-admin cmd.exe:

    powercfg /S e9a42b02-d5df-448d-aa00-03f14749eb61

and it disables the screen timeout. Now we just need a way to run that command after booting the image.

@henrywang : That may be of interest to you as well.

**Comment by martinpitt** [comment]
I am now trying to rebuild our windows-10 image with that extra command (I wouldn't know how to inject it from outside after booting). Unfortunately the version of the base VMWare image that we have used for our current windows-10 image does not exist any more, so I try with the [current one](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/). If that doesn't work, I'll rather just modify our existing one than doing a bigger rework.

**Comment by martinpitt** [comment]
@marusak: Please feel free to rope in the commit from PR #522 and see how far this gets?

**Comment by henrywang** [comment]
@martinpitt, we can change the power and sleep setting from "setting", and save it. I just don't know how to save change into image.
win10_power_sleep_setting

**Comment by martinpitt** [comment]
@henrywang : PR #522 does exactly that.

**Comment by marusak** [comment]
Ech, some problems:
1. `testSessionRecordingShell` on F31 has unexpected message `/system/overview.js: external channel failed: terminated` [chrome](https://209.132.184.41:8493/logs/pull-501-20200212-115050-235c85ba-fedora-31-cockpit-project-cockpit/log.html#73-2) [firefox](https://209.132.184.41:8493/logs/pull-501-20200212-115050-235c85ba-fedora-31-firefox-cockpit-project-cockpit/log.html#73)
and on F-testing it is `We trust you have received the usual lecture from the local System` [log](https://209.132.184.41:8493/logs/pull-501-20200212-115050-235c85ba-fedora-testing-cockpit-project-cockpit/log.html#73-2)
2. F31 broken/flaky testCreateTimer (check_services.TestServices)  [chrome](https://209.132.184.41:8493/logs/pull-501-20200212-115050-235c85ba-fedora-31-cockpit-project-cockpit/log.html#205-2) [firefox](https://209.132.184.41:8493/logs/pull-501-20200212-115050-235c85ba-fedora-31-firefox-cockpit-project-cockpit/log.html#205-2)

**Comment by marusak** [comment]
> F31 broken/flaky testCreateTimer (check_services.TestServices)

seems to be genuinely broken. We are setting the time to the past, but locally I cannot select time in the past. It needs to be debugged.

**Comment by martinpitt** [comment]
@marusak: Fixed testSessionRecordingShell in https://github.com/cockpit-project/cockpit/pull/13539 , adding as blocker

**Comment by martinpitt** [comment]
`testCreateTimer` regression debug notes:

current f31 image: systemd-243.5-1.fc31.x86_64, new image: systemd-243.6-1.fc31.x86_64

Reproducer:
```sh
# bring Machine into a defined state
timedatectl set-ntp off; timedatectl set-timezone UTC; timedatectl set-time '2020-01-01 12:00:00'
reboot

# create yearly timer with two triggers
cat <<EOF > /etc/systemd/system/yearly_timer.timer
[Unit]
Description=Yearly timer
[Timer]
OnCalendar=*-01-01 16:00:00
OnCalendar=*-01-01 1:22:00
[Install]
WantedBy=timers.target
EOF

cat <<EOF > /etc/systemd/system/yearly_timer.service
[Unit]
Description=Yearly timer
[Service]
ExecStart=/bin/sh -c '/bin/date >> /tmp/date'
EOF

systemctl daemon-reload
systemctl enable --now yearly_timer.timer

systemctl list-timers yearly_timer.timer
# should show NEXT: Wed 2020-01-01 16:00:00 UTC , LEFT: 3h 58min
# but on refreshed image: NEXT: Fri 2021-01-01 01:22:00 UTC, LEFT: 10 months 25 days

timedatectl set-time '2020-01-01 15:30:00'
systemctl list-timers yearly_timer.timer
# should show NEXT: Wed 2020-01-01 16:00:00 UTC, LEFT: 29min

# now go past the later trigger
timedatectl set-time '2020-01-01 16:10:00'
systemctl list-timers yearly_timer.timer
# should show NEXT: Fri 2021-01-01 01:22:00 UTC, LEFT: 1 years 0 months left
```
This works on current fedora-31 image, but not on this refreshed one. The difference seems to be that on the new image, `timedatectl shows the *current* date for the system time, not the fake date, even when I run them with `--no-network`. It somehow manages to undo the set-time on reboot. I need to find out how it does that.

**Comment by martinpitt** [comment]
[fedora-testing](https://209.132.184.41:8493/logs/pull-501-20200213-082020-235c85ba-fedora-testing-cockpit-project-cockpit/log.html) looks a little sad, retrying to compare.

I sent a fix for the timers test, added to TODO list.

**Comment by marusak** [comment]
Ok, getting somewhere, lets write down what failed and retry:
[1 test in weldr](https://209.132.184.41:8493/logs/pull-501-20200213-121414-235c85ba-fedora-31-chrome-weldr-cockpit-composer/log.html)
[testNoConnectionSetting](https://209.132.184.41:8493/logs/pull-501-20200213-121313-235c85ba-fedora-31-firefox-cockpit-project-cockpit/log.html) on F31. This is known - https://github.com/cockpit-project/cockpit/issues/13464#issuecomment-585753338
[testConfigureBeforeInstall](https://209.132.184.41:8493/logs/pull-501-20200213-121313-235c85ba-fedora-testing-cockpit-project-cockpit/log.html) on testing
[firefox 7.8](https://209.132.184.41:8493/logs/pull-501-20200213-121414-235c85ba-fedora-31-selenium-firefox-cockpit-project-cockpit-rhel-7.8/log.html) fails instead of skips. (not retrying)
[chrome 7.8](https://209.132.184.41:8493/logs/pull-501-20200213-121313-235c85ba-fedora-31-selenium-chrome-cockpit-project-cockpit-rhel-7.8/log.html) did not boot

**Comment by martinpitt** [comment]
The [testNoVm selenium failure](https://209.132.184.41:8493/logs/pull-501-20200212-131616-235c85ba-fedora-31-selenium-chrome-cockpit-project-cockpit-rhel-7.8/log.html#23) seems pretty clear -- the [screenshot](https://209.132.184.41:8493/logs/pull-501-20200212-131616-235c85ba-fedora-31-selenium-chrome-cockpit-project-cockpit-rhel-7.8/screenshot-testNoVm-316722.png) shows that libvirt is not running. I'll see to reproducing that locally. We may just need to steal a fix from master for that.

I sent a possible fix for testNoConnectionSettings in https://github.com/cockpit-project/cockpit/pull/13545 , but we may need some discussion around it -- it's a rather tough problem.

**Comment by marusak** [comment]
And `testConfigureBeforeInstall (check_machines_dbus.TestMachinesDBus) ` is broken as well on fedora-testing. Failed 6 times in a row.

```
  File "test/verify/check-machines-dbus", line 282, in testConfigureBeforeInstall
    b.wait_in_text("#vm-VmNotInstalled-firmware", "BIOS")
```
and [screenshot](https://209.132.184.41:8493/logs/pull-501-20200213-121313-235c85ba-fedora-testing-cockpit-project-cockpit/TestMachinesDBus-testConfigureBeforeInstall-fedora-testing-127.0.0.2-2501-FAIL.png) does not show it. @KKoukiou do you have some idea about it?

**Comment by henrywang** [comment]
@marusak, the failed issue is due to cockpit inactivity logout during building image. How many inactivity logout timemout is in cockpit setting by default?
You can find failed case screen capture from [failed report](https://54.89.13.31/logs/pull-501-20200214-110606-235c85ba-fedora-31-chrome-weldr-cockpit-composer/wdio_report/timeline-reporter.html)

**Comment by marusak** [comment]
>  the failed issue is due to cockpit inactivity logout during building image. How many inactivity logout timemout is in cockpit setting by default?

aaa, nice catch! The default is 15 minutes. It can be disabled. I'll send PR for that. Thanks for pointing it out!

**Comment by martinpitt** [comment]
Observations about the [testNoVm selenium failure](https://logs.cockpit-project.org/logs/pull-501-20200217-061212-235c85ba-fedora-31-selenium-chrome-cockpit-project-cockpit-rhel-7.8/log.html#23):

 - libvirtd.service is running initially, but some test that runs before selenium-machines-basic.py stops it; as I keep losing my ssh connection.BasicTestSuite.test50ChangeTabLogs stops the service , it sounds like some test reboots the VM.
 - test/avocado/run-tests starts it (same as test/selenium/run-tests in master), but it seems in master the service somehow survives
 -  Starting on  fedora-31, libvirtd.service is not the thing that we should look at any more, but libvirtd.socket, as the service is socket activated. That should be fixed in cockpit-machines.
 - libvirtd.socket does not yet exist in fedora-30, rhel-8-2, or rhel-7-8. This is the main explanation for this regression.
 - While  testNoVm runs, libvirtd.service actually starts again, but it seems the page  does not pick this up when it already shows the "virt service is not active" curtain.
 - We can quick-fix this for this branch by merely starting the service in selenium-machines-basic.py. I started the service manually before the test started, and it succeeded.

**Comment by marusak** [comment]
> I'd say, we ignore the test on fedora-testing for now, and go ahead with this.

Agree. Opened issue https://github.com/cockpit-project/cockpit/issues/13567

**Pull request merged**
