### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20241101-225204

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-60d7ee27-20241101-224037/log.html

**Comment by martinpitt** [comment]
Something something PCP

> pmlogger.service: Unable to locate executable '/etc/pcp/pmlogger/rc': No such file or directory

and netcat..

**Comment by jelly** [comment]
pcp-6.3.1-4 is out, so let's re-refresh.

**Pull request closed without merging**
