### PR TITLE
images: Move fedora-testing to Fedora 36

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-3420-20220523-102121/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20220523-104545

**Comment by mvollmer** [comment]
libgnutls is broken in FIPS mode.

**Comment by mvollmer** [comment]
Let's wait for gnutls to disappear from updates-testing a bit.

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3420-20220527-142323/

**Comment by mvollmer** [comment]
New version of gnutls is available: https://bodhi.fedoraproject.org/updates/FEDORA-2022-93d7c9e45d

**Comment by mvollmer** [comment]
Ah, not yet, in updates-testing...

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20220527-144545

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-3420-20220530-031616/

**Comment by martinpitt** [comment]
Let's do another round, the new gnutls should be available now.

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20220530-034040

**Review by martinpitt — APPROVED** [review]
Hooray!

**Pull request merged**
