### PR TITLE
images: Remove rhel4edge hack for kickstart improvement

### LINKED ISSUE #6214: Image refresh for rhel4edge
Image refresh for rhel4edge
 * [ ] image-refresh rhel4edge

### PR DESCRIPTION
**Pull request by jscotka**
Image refresh for rhel4edge
 * [ ] FAIL: image-refresh rhel4edge

Fixes #6214

### CODE REVIEW

**Comment by jscotka** [comment]
as part of inspecting https://github.com/cockpit-project/bots/issues/6214 we've found there were some bigger changes inside process what help to simplify process:
 - `fleet.ks` is removed and replaced just by `osbuild.ks`
 - no need to add `rootpw` hack anymore, already inside this file
 -

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel4edge-5f398ccf-20240416-113511/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel4edge-564f991c-20240416-122753/log.html

**Comment by martinpitt** [comment]
Looks like it [doesn't set up the SSH key correctly](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel4edge-564f991c-20240416-122753/log.html)? The 'reach machine with ssh' is trying a login as root with the usual bots SSH key, i.e. *not* with the password (so it *should* be unrelated to the `rootpw --lock` change).

**Comment by jscotka** [comment]
> Looks like it [doesn't set up the SSH key correctly](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel4edge-564f991c-20240416-122753/log.html)? The 'reach machine with ssh' is trying a login as root with the usual bots SSH key, i.e. _not_ with the password (so it _should_ be unrelated to the `rootpw --lock` change).



> g a login as root with the u

Sure it should be not related to `rootpw --lock` because it is also inside the clean kickstart when I've checked.

it is strange, because also setup is done via ssh key for root as there is eg: `rsync --recursive --perms --copy-links -e 'ssh -p 2201 ...` , isn't it?

I'll retest it locally again and then I'll try to reschedule PR image rebuild. If it is not caused somehow externally by something, some timeouting when exhausted resources or something similar.

**Comment by cockpituous** [comment]
image-refresh rhel4edge done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel4edge-20240416-192411

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel4edge-564f991c-20240416-182351/log.html

**Comment by martinpitt** [comment]
Yay, worked now!

**Comment by martinpitt** [comment]
I picked up the image refresh and squashed the fixup.

**Comment by jscotka** [comment]
> Meh, there's still a lot of regressions wrt. superuser handling -- smells like the sudo setup isn't quite right yet?

Hi @martinpitt Seems I've found the root cause.

By default now rhel4edge image creates additional file for wheel group, with passwordless sudo and some tests expects by default to use passwords, as defined inside `become_superuser` function inside `testlib`. We'll see.

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel4edge-f272b79b-20240419-091759/log.html

**Comment by jscotka** [comment]
it did not helped as I've expected, locally it had bigger impact.

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel4edge-9e5bc6b2-20240426-082519/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel4edge-9e5bc6b2-20240426-121251/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel4edge-9e5bc6b2-20240429-090533/log.html

**Comment by martinpitt** [comment]
#6214 worked, and @jscotka said that the fleet.ks change got reverted. Thanks!

**Pull request closed without merging**
