### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

### CODE REVIEW

**Comment by martinpitt** [comment]
[machines failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3813-20220902-233127-e22a93ff-arch-cockpit-project-cockpit-machines/log.html#45-2), retrying for comparison

**Comment by martinpitt** [comment]
Breaks machine migration, needs work

**Comment by mvollmer** [comment]
I can't reproduce the failure locally...

**Comment by mvollmer** [comment]
> I can't reproduce the failure locally...

Argg, I didn't set TEST_OS=arch...

**Comment by mvollmer** [comment]
Looks like the migration process 'forgets' to copy the disk and then assumes it is accessible on the target host, as with shared storage.

With libvirt 8.6.0 (working)

```
# virsh --debug=1 migrate subVmTest1 qemu+ssh://root@machine2/system --copy-storage-all --verbose
migrate: domain(optdata): subVmTest1
migrate: desturi(optdata): qemu+ssh://root@machine2/system
migrate: copy-storage-all(bool): (none)
migrate: verbose(bool): (none)
migrate: found option <domain>: subVmTest1
migrate: found option <domain>: subVmTest1
Migration: [100 %]
```

With libvirt 8.7.0 (not working):

```
# virsh --debug=1 migrate subVmTest1 qemu+ssh://root@machine2/system --copy-storage-all --verbose
migrate: domain(optdata): subVmTest1
migrate: desturi(optdata): qemu+ssh://root@machine2/system
migrate: copy-storage-all(bool): (none)
migrate: verbose(bool): (none)
migrate: found option <domain>: subVmTest1
migrate: found option <domain>: subVmTest1
error: Path '/var/lib/libvirt/images/subVmTest1-2.img' is not accessible: No such file or directory
```

This looks like a bug in libvirt 8.7.0 to me.

**Comment by mvollmer** [comment]
> This looks like a bug in libvirt 8.7.0 to me.

https://gitlab.com/libvirt/libvirt/-/issues/373

I make a naughty for this.

**Review by jelly — APPROVED** [review]

**Pull request merged**
