### PR TITLE
[no-test] images: Install selinux-policy-devel into RHEL/CentOS 8 mock

### PR DESCRIPTION
**Pull request by martinpitt**
We are trying to enable our own SELinux policy for RHEL/CentOS 8 in
https://github.com/cockpit-project/cockpit/pull/16575 .
Install the necessary build dependencies into mock.

 * [x] image-refresh rhel-8-6
 * [x] image-refresh rhel-8-5
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2611-20211108-155050/

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20211108-161111

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-2611-20211108-162525/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-2611-20211108-162222/

**Comment by cockpituous** [comment]
image-refresh rhel-8-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-5-20211108-164747

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-2611-20211108-164848/

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20211108-172626

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-2611-20211108-172626/

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20211108-183737

**Review by marusak — APPROVED** [review]
Thanks! There is also rhel-8-4, any reason why this one was not refreshed?

**Review by allisonkarlitskaya — APPROVED** [review]
👍

**Comment by martinpitt** [comment]
@marusak : Whoops! Honestly I just forgot about it; sub-man does not care the least about this change, though. Is it ok to land this, and after that I make sure that the refresh still works?

**Comment by martinpitt** [comment]
@marusak : I did a rhel-8-4 refresh in #2615, went alright.

**Pull request merged**
