### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos
 * [x] Fix cockpit-ostree for non-accessible nginx container image: https://github.com/cockpit-project/cockpit-ostree/pull/163

### CODE REVIEW

**Comment by marusak** [comment]
```
+ podman pull quay.io/app-sre/nginx
Trying to pull quay.io/app-sre/nginx...
  unauthorized: access to the requested resource is not authorized
Error: unable to pull quay.io/app-sre/nginx: Error initializing source docker://quay.io/app-sre/nginx:latest: Error reading manifest latest in quay.io/app-sre/nginx: unauthorized: access to the requested resource is not authorized
```

I see the same when I run `podman pull quay.io/app-sre/nginx` locally. I am not sure what `app-sre` actually is, but we need to use different namespace or just get it in our own.

**Comment by martinpitt** [comment]
https://quay.io/repository/bitnami/nginx looks promising, shall we try that? I also found https://quay.io/repository/ocsci/nginx , but that doesn't look well maintained.

**Comment by marusak** [comment]
> https://quay.io/repository/bitnami/nginx looks promising, shall we try that?

worth a shot :)

**Comment by martinpitt** [comment]
I'm looking into fixing c-ostree for the nginx container now. This is unrelated to this image refresh, but we should still wait for that.

**Comment by martinpitt** [comment]
c-ostree fix landed, retrying

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
