### PR TITLE
fix centos-10 refresh

### LINKED ISSUE #6273: Image refresh for centos-10
Image refresh for centos-10
 * [ ] FAIL: image-refresh centos-10

### PR DESCRIPTION
**Pull request by jelly**
Resolved in 2.1.2-2.el10.

 * [x] ~Wait until crun 1.14.4 is visible in c10s repos~ use development composes
 * [x] image-refresh centos-10
 * [x] https://github.com/cockpit-project/cockpit/pull/20436

Fixes #6273

### CODE REVIEW

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-f99a6df6-20240425-075532/log.html

**Comment by martinpitt** [comment]
Something else broke :cry:

**Comment by jelly** [comment]
> Something else broke 😢

/me tries to act suprised

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-f99a6df6-20240429-081102/log.html

**Comment by jelly** [comment]
Still broken.

**Comment by martinpitt** [comment]
> ERROR: Could not find required config file: /etc/mock/default.cfg

We create the symlink as centos-stream-10-x86_64.cfg , but this doesn't exist any more. This was fixed in mock-core-configs-40.3-1.fc40.noarch , but on this rebuild, the version went *backwards* to mock-core-configs-40.2-1.fc40.noarch.

The reason for that is pretty mundane, I'll commit a fix here.

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240502-043713

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-204669dc-20240502-041930/log.html

**Comment by martinpitt** [comment]
Now [two of the metrics tests fail](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6280-2146072f-20240502-044233-centos-10-other-cockpit-project-cockpit/log.html) on 

> Error: OCI runtime error: crun: unknown version specified

which is https://issues.redhat.com/browse/RHEL-34649 . That is in state "integration", but apparently not visible in C10S yet. The third metrics test failed on something else.

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-9079d405-20240506-105940/log.html

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240506-111810

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-9079d405-20240506-110442/log.html

**Comment by martinpitt** [comment]
Hmmm.. This build's kexec-tools-2.0.28-9.el10.x86_64 doesn't ship `kdumpctl` any more. OTOH, rawhide [moved to splitting out the package into kdump-utils](https://bugzilla.redhat.com/show_bug.cgi?id=2275385), but that doesn't exist either. `dnf search kdump` doesn't bring up anything, and `dnf install /usr/bin/kdumpctl` fails with "no match". https://gitlab.com/redhat/centos-stream/rpms/kexec-tools/-/commits/c10s?ref_type=heads looks like it's *meant* to split out kdump-utils, but it's not in https://composes.stream.centos.org/stream-10/development/latest-CentOS-Stream/compose/BaseOS/x86_64/os/Packages/.

Filed as https://issues.redhat.com/browse/RHEL-35567 .

But let's turn that cockpit dependency into a `Recommends:`, it's a good thing to do anyway. And then skip the test for now.

**Comment by martinpitt** [comment]
OMG all the green! :tada:

**Comment by martinpitt** [comment]
@jelly can you please cross-check my changes? If you :+1: I'll formally approve/land. Thanks!

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
