### PR TITLE
lib: Move default OS to Fedora 40

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Comment by martinpitt** [comment]
That is the one which will make all pixel tests fail (presumably), right?

**Comment by martinpitt** [comment]
Ah, you triggered the tests exactly when I wrote my comment :sweat_smile:

**Comment by martinpitt** [comment]
Ah no, I'm lying -- that is controlled by project in tests/reference-image, so should be bumped there. This PR should be almost a no-op -- i.e. triggering the tests isn't wrong, but in _theeeeeeeory_ there shouldn't be any regressions

**Comment by jelly** [comment]
> Ah no, I'm lying -- that is controlled by project in tests/reference-image, so should be bumped there. This PR should be almost a no-op -- i.e. triggering the tests isn't wrong, but in _theeeeeeeory_ there shouldn't be any regressions

But that is for pixel tests, not `DEFAULT_OS`. I want to bump `reference-image` in a separate PR per repo

**Comment by martinpitt** [comment]
Not sure about this [kdump error](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6281-8bf8608f-20240425-143619-fedora-40-devel-cockpit-project-cockpit/log.html#43-2), but assuming it's a flake.

**Review by martinpitt — DISMISSED** [review]
:green_circle:  → :+1:

**Comment by jelly** [comment]
```
test/verify/check-kdump:from lib.constants import TEST_OS_DEFAULT
test/verify/check-kdump:        "nfs": {"image": TEST_OS_DEFAULT, "address": "10.111.113.2/24", "memory_mb": 512}
test/verify/check-kdump:        "nfs": {"image": TEST_OS_DEFAULT, "address": "10.111.113.2/24", "memory_mb": 512},
```
kdump is persistant.... so needs investigation.

Abort is an interesting one.
```
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2036, in check_browser_errors
    raise Error(UNEXPECTED_MESSAGE + "browser errors:\n" + log)
testlib.Error: FAIL: Test completed, but found unexpected browser errors:
error: Warning: Each child in a list should have a unique "key" prop.%s%s See https://reactjs.org/link/warning-keys for more information.%s 

Check the render method of `AbrtLogDetails`.  
    at StackItem (http://127.0.0.2:9291/cockpit/@localhost/system/logs.js:38528:11)
    at AbrtLogDetails (http://127.0.0.2:9291/cockpit/@localhost/system/logs.js:45059:7)
    at div
    at Gallery (http://127.0.0.2:9291/cockpit/@localhost/system/logs.js:42246:11)
    at section
    at PageSection (http://127.0.0.2:9291/cockpit/@localhost/system/logs.js:35176:11)
    at main
    at div
    at Page (http://127.0.0.2:9291/cockpit/@localhost/system/logs.js:34927:7)
    at LogEntry (http://127.0.0.2:9291/cockpit/@localhost/system/logs.js:45168:7)
    at LogsPage (http://127.0.0.2:9291/cockpit/@localhost/system/logs.js:45286:31)
```

**Comment by jelly** [comment]
```
Apr 26 10:16:04 fedora-40-127-0-0-2-2201 systemd[1]: Starting kdump.service - Crash recovery kernel arming...
Apr 26 10:16:05 fedora-40-127-0-0-2-2201 kdumpctl[926]: kdump: No kdump initial ramdisk found.
Apr 26 10:16:05 fedora-40-127-0-0-2-2201 kdumpctl[926]: kdump: Rebuilding /boot/initramfs-6.8.7-300.fc40.x86_64kdump.img
Apr 26 10:16:05 fedora-40-127-0-0-2-2201 kdumpctl[926]: kdump: mkdumprd: failed to make kdump initrd
Apr 26 10:16:05 fedora-40-127-0-0-2-2201 kdumpctl[926]: kdump: Starting kdump: [FAILED]
Apr 26 10:16:05 fedora-40-127-0-0-2-2201 systemd[1]: kdump.service: Main process exited, code=exited, status=1/FAILURE
Apr 26 10:16:05 fedora-40-127-0-0-2-2201 systemd[1]: kdump.service: Failed with result 'exit-code'.
Apr 26 10:16:05 fedora-40-127-0-0-2-2201 systemd[1]: Failed to start kdump.service - Crash recovery kernel arming.
```
Can locally reproduce.

**Comment by jelly** [comment]
Ok, turns out the kdump issue is a known flake, same issue just happens different

The machines flake now prints without (uncaught promise) which is a bit weird but still the same issue.

**Comment by martinpitt** [comment]
Looks good, but not sufficient -- still lots of failures, including kdump :cry:

**Comment by jelly** [comment]
X'th time is a charm! Still strange that we now have `(uncaught exception)`

**Comment by mvollmer** [comment]
> Run test "https://api.github.com/repos/jelly/bots" = "https://api.github.com/repos/cockpit-project/bots"

What is that about?

**Review by martinpitt — APPROVED** [review]
Thanks!

**Pull request merged**
