### PR TITLE
images: add Fedora-38 image

### PR DESCRIPTION
**Pull request by jelly**
* [x] image-refresh fedora-38

### CODE REVIEW

**Comment by martinpitt** [comment]
Once you add the built image, please also add fedora-38 to image-trigger. There might also still be some known bugs left in machine/machine_core/machine.py , but I'll send a PR to clean them up.

**Comment by cockpituous** [comment]
image-refresh fedora-38 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-38-20230215-090148

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-38-20230215-090101.log

**Comment by martinpitt** [comment]
Nice, thanks! Let's test this with starter-kit to make sure it can do basic things (boot and such). Then we can work our way upwards to enable it on other projects.

**Review by martinpitt — APPROVED** [review]
Woaks!

**Pull request merged**
