### PR TITLE
Image refresh for fedora-rawhide-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-boot
 * [x] image-refresh fedora-rawhide-boot

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-boot done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-boot-20240210-223906

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-boot-20240210-223939.log

**Comment by martinpitt** [comment]
@KKoukiou This refresh looks much better now. The [testEncryptedUnlockRAIDonLUKS](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5896-20240210-224016-fb821c87-fedora-rawhide-boot-rhinstaller-anaconda-webui/log.html#25-2) failure could be an actual rawhide regression, or it merely needs a timeout bump perhaps?

**Comment by KKoukiou** [comment]
It's not the latest blivet still ->>> blivet-3.9.0-py3.12.egg-info in theboot.iso

What you see in the tests is a blivet regression which should be fixed in https://bodhi.fedoraproject.org/updates/FEDORA-2024-8563591fde blivet-3.9.0-2

**Pull request closed without merging**
