### PR TITLE
images: Add nginx to Fedora images

### PR DESCRIPTION
**Pull request by martinpitt**
With that we can write a full integration test for reverse proxying. We
recently seem to get a lot of user inquiries about that topic.

 * [x] image-refresh fedora-31
 * [x] image-refresh fedora-32

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-895-20200525-145151/

**Comment by cockpituous** [comment]
image-refresh fedora-31 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-31-20200525-155656

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-895-20200525-155858/

**Comment by cockpituous** [comment]
image-refresh fedora-32 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-32-20200525-170000

**Comment by martinpitt** [comment]
This is also affected by https://bugzilla.redhat.com/show_bug.cgi?id=1839805 aka issue #897, so needs another naughty.

**Comment by martinpitt** [comment]
[cockpit-podman](https://logs.cockpit-project.org/logs/pull-895-20200525-183510-b16e8a32-fedora-31-cockpit-project-cockpit-podman/log.html) also has 4 tests; at least one of them is related to sudo handling, but there are others. @mmarusak, could you have a look, please?

**Comment by martinpitt** [comment]
[ostree failures](https://logs.cockpit-project.org/logs/pull-895-20200525-183506-b16e8a32-fedora-coreos-cockpit-project-cockpit-ostree/log.html) are related to the new cockpit auth/sudo behaviour. I'll send a separate PR for that (just curious why the F31 image update triggers that..)

**Comment by marusak** [comment]
> just curious why the F31 image update triggers that

Because it is the first F31 refresh that has cockpit-219?

**Comment by martinpitt** [comment]
@marusak: But that test runs on the fedora-coreos image. Anyway, I'm downloading images now and will look at c-ostree.

**Comment by marusak** [comment]
Sent https://github.com/cockpit-project/cockpit-podman/pull/390 for podman

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit-ostree/pull/91 fixes cockpit-ostree

**Comment by martinpitt** [comment]
Rebased to pick up the naugthies for the sssd regression.

**Comment by martinpitt** [comment]
@henrywang: [testOpenStack](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-895-20200526-073435-8cf774a1-fedora-31-osbuild-cockpit-composer/log.html) fails, this also happens on the [fedora-32](https://logs.cockpit-project.org/logs/pull-895-20200526-073427-8cf774a1-fedora-32-osbuild-cockpit-composer/log.html) image. Is this really related to the image refresh, or some problem with the cloud provider?

**Comment by martinpitt** [comment]
Argh, [fedora-32](https://logs.cockpit-project.org/logs/pull-895-20200526-073857-8cf774a1-fedora-32-cockpit-project-cockpit/log.html#193-2) picked up the sssd/AD regression as well. I copied the naughty pattern.

**Comment by henrywang** [comment]
> @henrywang: [testOpenStack](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-895-20200526-073435-8cf774a1-fedora-31-osbuild-cockpit-composer/log.html) fails, this also happens on the [fedora-32](https://logs.cockpit-project.org/logs/pull-895-20200526-073427-8cf774a1-fedora-32-osbuild-cockpit-composer/log.html) image. Is this really related to the image refresh, or some problem with the cloud provider?

The failed is due to image build timeout (30 minutes). But this [fedora-31](https://logs.cockpit-project.org/logs/pull-895-20200526-123246-0f1159c6-fedora-31-osbuild-cockpit-composer/TestImage-testOpenStack-fedora-31-127.0.0.2-2201-FAIL.png) failed is because of image build failure. Recently the image build(openstack image) failed a lot because timeout and build failure. Retry more times will pass the test.

**Comment by martinpitt** [comment]
The lorax tar test has timed out for a while now, let's not block on that.

**Pull request merged**
