### PR TITLE
services: pin back ansible-role-candlepin scripts

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
The changes introduced in candlepin/ansible-role-candlepin#27 don't work
with our version of ansible, so pin back to the previous version.

 * [x] image-refresh services

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-2.
Log: https://logs.cockpit-project.org/logs/image-refresh-3774-20220825-104545/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3774-20220825-104545/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3774-20220825-104545/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3774-20220825-111313/

**Comment by cockpituous** [comment]
image-refresh services done: https://github.com/cockpit-project/bots/commits/image-refresh-services-20220825-121028

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
