### PR TITLE
Image refresh for fedora-36

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-36
 * [x] image-refresh fedora-36

### CODE REVIEW

**Comment by martinpitt** [comment]
[cockpit failed three tests](https://logs.cockpit-project.org/logs/pull-3198-20220407-102147-0c1be793-fedora-36-cockpit-project-cockpit/log.html#248) on

   libgcrypt selftest: binary  (0): Invalid object

This [podman failure](https://logs.cockpit-project.org/logs/pull-3198-20220407-102145-0c1be793-fedora-36-cockpit-project-cockpit-podman/log.html#9-2) looks like `podman run` now wants to pull/refresh an existing container image?

**Comment by martinpitt** [comment]
@jelly : Would you have time to look at the podman side of this?

**Comment by jelly** [comment]
> @jelly : Would you have time to look at the podman side of this?

Sure!

**Comment by martinpitt** [comment]
Reported libgcrypt regression, [added naughty](https://github.com/cockpit-project/bots/issues/3201).

**Review by jelly — APPROVED** [review]

**Pull request merged**
