### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240301-005934

**Comment by martinpitt** [comment]
[Uuh](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5995-20240301-010053-634bd4d1-arch-storage-cockpit-project-cockpit/log.html#13-2), lots of errors like "mdadm: command not found" and other missing menu entries. But the [log](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-20240229-223720-59f88c20-image-refresh-arch/log.html) shows no removed/added/upgraded packages. WTH?

This needs closer investigation.

**Comment by jelly** [comment]
> [Uuh](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5995-20240301-010053-634bd4d1-arch-storage-cockpit-project-cockpit/log.html#13-2), lots of errors like "mdadm: command not found" and other missing menu entries. But the [log](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-20240229-223720-59f88c20-image-refresh-arch/log.html) shows no removed/added/upgraded packages. WTH?
> 
> This needs closer investigation.

Arch split up udisks2 plugins, I will make a new PR to add these to the image.

**Comment by martinpitt** [comment]
Handled in #6000

**Pull request closed without merging**
