### PR TITLE
Image refresh for fedora-rawhide

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide
 * [x] image-refresh fedora-rawhide

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-20240619-225722

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-78afd8b6-20240619-223727/log.html

**Comment by jelly** [comment]
@KKoukiou do you know what went wrong with the pixel tests?

**Comment by KKoukiou** [comment]
> @KKoukiou do you know what went wrong with the pixel tests?

New cockpit version available.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
