### PR TITLE
images: Introduce rhel-9-5

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh rhel-9-5

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-9-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-5-20240416-120834

**Comment by cockpituous** [comment]
image-refresh rhel-9-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-5-20240416-122503

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-5-ac15136b-20240416-120926/log.html

**Comment by martinpitt** [comment]
To fix [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6228-831ac366-20240416-123429-rhel-9-5-cockpit-project-cockpit-machines/log.html#19), please add a naughty symlink for "rhel-9-5". Also, please don't trigger failing tests on the final PR, as they will make the test appear as 100% failure on the weather report (which is confusing). This is good for a first test run, of course (but there will be a lot of cockpit failures too due to the missing naughties)

**Comment by mvollmer** [comment]
cockpit-machines, cockpit-podman, and cockpit are pretty happy with this image. Let's land it and then enable it for c-machines at least.

**Review by martinpitt — APPROVED** [review]
Kiitos!

**Pull request merged**
