### PR TITLE
Image refresh for fedora-35

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-35
 * [x] image-refresh fedora-35

### CODE REVIEW

**Comment by martinpitt** [comment]
[this failure](https://logs.cockpit-project.org/logs/pull-2465-20211001-023803-09691b5e-fedora-35-cockpit-project-cockpit/log.html#273-2) looks like something that would only happen at the end/start of a month?

**Comment by marusak** [comment]
Podman seems to be affected as well with - https://github.com/cockpit-project/bots/issues/2463

Plus I see a lot of `time="2021-10-01T03:02:45Z" level=warning msg="Failed to decode the keys [\"machine\"] from \"/usr/share/containers/containers.conf\"."` which does not seem great either.

**Comment by marusak** [comment]
cockpit has broken main due to time bomb - https://github.com/cockpit-project/cockpit/pull/16426

**Comment by marusak** [comment]
Warnings `Failed to decode the keys [\"machine\"] from \"/usr/share/containers/containers.conf` are already known - https://github.com/containers/podman/issues/11745

**Comment by marusak** [comment]
[machines](https://logs.cockpit-project.org/logs/pull-2465-20211001-091002-4735484b-fedora-35-cockpit-project-cockpit-machines/log.html#21-2) failed, retrying.

**Comment by marusak** [comment]
Machines failed now 3 times the same way. Needs to be looked at.

**Comment by marusak** [comment]
This is due to some operation in the disk add dialog taking more cpu than before and it is too much for the VM to handle.

**Comment by marusak** [comment]
Reproducible by sitting in the test just before it clicks on `Add` button and executing following commands. The second one kills the VM.
```
# busctl call org.libvirt /org/libvirt/QEMU org.libvirt.Connect StoragePoolLookupByName s pool-disk
"/org/libvirt/QEMU/storagepool/_bd9da8aa_35bf_4bc5_a899_747297145062"
           
# busctl call org.libvirt /org/libvirt/QEMU/storagepool/_bd9da8aa_35bf_4bc5_a899_747297145062 org.libvirt.StoragePool StorageVolCreateXML su "<volume type=\"file\"><name>sda1</name><capacity unit=\"MiB\">1</capacity><target/></volume>" 0
```

It can be also reproduced without dbus, just doing:
```
# cat vol.xml
<volume type="file">
  <name>sda1</name>
  <capacity unit="MiB">1</capacity>
  <target/>
</volume>
# virsh vol-create pool-disk vol.xml
```

**Comment by marusak** [comment]
Giving the VM one more cpu helps (I froze the VM once also with 2cpus, but works much better then with one). I checked logs and nothing interesting happens when the button is pressed:
```
Oct 05 07:45:19 fedora-35-127-0-0-2-2201 kernel:  sda: sda1
Oct 05 07:45:19 fedora-35-127-0-0-2-2201 systemd-homed[623]: block device /sys/devices/pseudo_0/adapter0/host3/target3:0:0/3:0:0:0/block/sda/sda1 has been removed.
Oct 05 07:45:20 fedora-35-127-0-0-2-2201 kernel: kauditd_printk_skb: 18 callbacks suppressed
Oct 05 07:45:20 fedora-35-127-0-0-2-2201 kernel: audit: type=2501 audit(1633419920.380:586): pid=740 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:virtd_t:s0-s0:c0.c1023 msg='virt=kvm resrc=cgroup reason=allow vm="subVmTest1" uuid=370103aa-dad0-45cc-a58d-901c5fc58116 cgroup="/sys/fs/cgroup/machine.slice/machine-qemu\x2d1\x2dsubVmTest1.scope/" class=path path="/dev/sda1" rdev=08:01 acl=rw exe="/usr/sbin/virtqemud" hostname=? addr=? terminal=? res=success'
Oct 05 07:45:20 fedora-35-127-0-0-2-2201 audit[740]: VIRT_RESOURCE pid=740 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:virtd_t:s0-s0:c0.c1023 msg='virt=kvm resrc=cgroup reason=allow vm="subVmTest1" uuid=370103aa-dad0-45cc-a58d-901c5fc58116 cgroup="/sys/fs/cgroup/machine.slice/machine-qemu\x2d1\x2dsubVmTest1.scope/" class=path path="/dev/sda1" rdev=08:01 acl=rw exe="/usr/sbin/virtqemud" hostname=? addr=? terminal=? res=success'
Oct 05 07:45:20 fedora-35-127-0-0-2-2201 kernel: audit: type=2501 audit(1633419920.422:587): pid=740 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:virtd_t:s0-s0:c0.c1023 msg='virt=kvm resrc=disk reason=attach vm="subVmTest1" uuid=370103aa-dad0-45cc-a58d-901c5fc58116 old-disk="?" new-disk="/dev/sda1" exe="/usr/sbin/virtqemud" hostname=? addr=? terminal=? res=success'
Oct 05 07:45:20 fedora-35-127-0-0-2-2201 audit[740]: VIRT_RESOURCE pid=740 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:virtd_t:s0-s0:c0.c1023 msg='virt=kvm resrc=disk reason=attach vm="subVmTest1" uuid=370103aa-dad0-45cc-a58d-901c5fc58116 old-disk="?" new-disk="/dev/sda1" exe="/usr/sbin/virtqemud" hostname=? addr=? terminal=? res=success'
```

Libvirt, qemu or anything machines related did not updated in this refresh. Kernel got updated, so that might be the problem here.

When I try and watch which processes eat the resources, with one cpu it immediately dies, with two nothing really spikes that would seem interesting.

**Comment by marusak** [comment]
So, when I tried updating kernel (which also pulls back in again linux-firmware that somehow got dropped from this refresh) it works again. I'll try to do a new refresh and will see if it works also in CI.

**Comment by marusak** [comment]
Suppressed by https://github.com/cockpit-project/bots/pull/2477

**Pull request closed without merging**
