### PR TITLE
Fix arch image build

### LINKED ISSUE #2788: Image refresh for arch
Image refresh for arch
 * [ ] FAIL: image-refresh arch

### PR DESCRIPTION
**Pull request by martinpitt**
Fixes #2788

 * [x] image-refresh arch
 * https://github.com/cockpit-project/cockpit/pull/17032

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-2987-20220222-103030/

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20220222-104040

**Comment by martinpitt** [comment]
This [breaks the Machine migration tests](https://logs.cockpit-project.org/logs/pull-2987-20220222-114240-4fd3582b-arch-cockpit-project-cockpit-machines/log.html#41-2), apparently they expect NM to use eth1? Also some [cockpit tests](https://logs.cockpit-project.org/logs/pull-2987-20220222-114240-4fd3582b-arch-cockpit-project-cockpit/log.html#55-2) which expect eth1 to point to a peer image. This needs fixing.

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-2987-20220222-112525/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-2987-20220222-112525/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-2987-20220222-123535/

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20220222-124747

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-2987-20220222-124848/

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20220222-125959

**Comment by martinpitt** [comment]
Only two regressions, not bad!

## [TestStoragePackagesNFS.testNfsMissingPackages](https://logs.cockpit-project.org/logs/pull-2987-20220222-125942-c6c8d0f1-arch-cockpit-project-cockpit/log.html#204-2)

The [screenshot](https://logs.cockpit-project.org/logs/pull-2987-20220222-125942-c6c8d0f1-arch-cockpit-project-cockpit/TestStoragePackagesNFS-testNfsMissingPackages-arch-127.0.0.2-2701-FAIL.png) shows the same error message as the log:

> Error: fake-libnfs;1.0-1;any;testrepo: could not find or read package

For me locally, the first run works, and the second one then fails differently:

> warning: fake-nfs-utils is not available from any repository.
> warning: fake-libnfs (/stamp-fake-libnfs-1.0-1): conflicting files

I noticed that arch currently skips all check-packagekit, check-apps, `TestMetricsPackages`, etc. This is also not new, it [failed before](https://logs.cockpit-project.org/logs/pull-15626-20220209-203633-a56677da-arch/log.html#153)  as well. So let's just skip this as well for now. I sent PR https://github.com/cockpit-project/cockpit/pull/17032 for this.

**Review by jelly — APPROVED** [review]

**Pull request merged**
