### PR TITLE
Image refresh for rhel-9-4

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-4
 * [x] image-refresh rhel-9-4

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-9-4 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-4-20231104-225310

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-4-20231104-225353.log

**Comment by martinpitt** [comment]
[testNICDelete failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5504-20231104-225423-0f638ed2-rhel-9-4-cockpit-project-cockpit-machines/log.html#63), retrying for comparison.

**Comment by martinpitt** [comment]
ah, testNICDelete is the second-worst flake right now, so unrelated to the refresh:

image

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
