### PR TITLE
Image refresh for rhel-9-2

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-2
 * [x] image-refresh rhel-9-2

### CODE REVIEW

**Comment by jelly** [comment]
# testVdoMissingPackages (__main__.TestStoragePackagesVDO)

```
warning: Error: vdo is not available from any repository.
warning: Error creating volume: Process reported exit code 3: modprobe: FATAL: Module kvdo not found in directory /lib/modules/5.14.0-168.el9.x86_64
  /usr/sbin/modprobe failed: 1
  vdo: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
```

**Comment by marusak** [comment]
eh this evergreen bug :man_shrugging: I think we might need to auto-naughty it as even the BZ we have they just keep it "for future references".

**Comment by marusak** [comment]
@jelly can I get ack here since I pushed changes here? Thanks!

**Review by mvollmer — APPROVED** [review]
LGTM!

**Pull request merged**
