### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-testing-20221220-225656.log

**Comment by martinpitt** [comment]
This failure looks significant. That's usually a "never fails" test, and killing three VMs in a row needs looking at.

**Comment by KKoukiou** [comment]
I started seeing this exact issue locally today, image-customize stopped working. SSH ing to the VM takes unbearably long and it timeouts. Did not manage to figure this out yet.

**Comment by KKoukiou** [comment]
It was auto-fixed within 2 days with some update on my system. So retrying here an update.

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20221226-144804

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-testing-20221226-144848.log

**Comment by martinpitt** [comment]
Okay, I pushed that new image here, let's try!

**Comment by martinpitt** [comment]
Nope, still the same issue.

**Comment by martinpitt** [comment]
Trivially reproducible with `bots/image-customize --verbose --resize 20G debian-testing` in a clean cockpit tree, with bots/ having this new image. This fails to boot early in initramfs:
```
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... done.
Begin: Will now check root file system ... fsck from util-linux 2.38.1
[/sbin/fsck.ext4 (1) -- /dev/vda1] fsck.ext4 -a -C0 /dev/vda1 
/dev/vda1: clean, 118601/647168 files, 1027851/2588667 blocks
done.
[    1.064055] EXT4-fs (vda1): mounted filesystem with ordered data mode. Quota mode: none.
done.
Begin: Running /scripts/local-bottom ... [    1.086933] EXT4-fs (vda1): unmounting filesystem.
GROWROOT: WARNING: resize failed: failed [flock:127] flock -x 9
/sbin/growpart: line 714: flock: not found
FAILED: Error while obtaining exclusive lock on /dev/vda
[    1.114862] GPT:Primary header thinks Alt. header is not at the end of the disk.
[    1.115544] GPT:20971519 != 41943039
[    1.115927] GPT:Alternate GPT header not at the end of the disk.
[    1.116488] GPT:20971519 != 41943039
[    1.116806] GPT: Use GNU Parted to correct GPT errors.
[    1.117273]  vda: vda1 vda14 vda15
/scripts/local-bottom/growroot: line 97: wait-for-root: not found
done.
Begin: Running /scripts/init-bottom ... mount: mounting /dev on /root/dev failed: No such file or directory
mount: mounting /dev on /root/dev failed: No such file or directory
done.
mount: mounting /run on /root/run failed: No such file or directory
BusyBox v1.35.0 (Debian 1:1.35.0-4) multi-call binary.

Usage: run-init [-d CAP,CAP...] [-n] [-c CONSOLE_DEV] NEW_ROOT NEW_INIT [ARGS]
[...]
```
and it lands in the `(initramfs)` interactive prompt.

@KKoukiou how did you test it, wrt. the "auto-fixed"? This does not break all image-customize commands, just the resizing. The most probable change here is this:

    cloud-initramfs-tools (0.18.debian8 -> 0.18.debian11)

The "flock: not found" is [#1014662](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014662), but that is already present in our current image, and does not seem fatal.

**Comment by martinpitt** [comment]
I reported this to Debian in https://bugs.debian.org/1027050, and created a known issue #4206. Pushed a naughty here.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
