### PR TITLE
images: Explicitly install extra locales on centos-8-stream

### PR DESCRIPTION
**Pull request by Gundersanne**
This problem was also encountered with the fedora-31 image, where only
english locales are installed by default.

---
waiting with refresh until I'm sure no other commits need to come on top of this
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by martinpitt** [comment]
Is glibc-all-langpacks already part of our current rhel7/8 images, or is there something funky on centos-8 specifically that needs these?

**Comment by Gundersanne** [comment]
@martinpitt idk why but they're not installed by default. On rhel-7/8 the tests with german and portuguese locales work fine, so I assume they're installed by default there.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-01.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-259-20191121-152222/

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpituous/bots/commits/image-refresh-centos-8-stream-20191121-195252

**Comment by Gundersanne** [comment]
sorry for the re-review,had to edit a commit message.

The locale tests seem to be fixed with this, tested it locally.

**Pull request merged**
