### PR TITLE
images: Update rhel-8-5 repository URLs for release

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh rhel-8-5

### CODE REVIEW

**Comment by martinpitt** [comment]
@ptoscano FYI

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-2587-20211102-132424/

**Review by ptoscano — APPROVED** [review]
LGTM, matches my internal repos was well.

**Comment by cockpituous** [comment]
image-refresh rhel-8-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-5-20211102-134545

**Review by ptoscano — APPROVED** [review]
Still LGTM, and it still works with all the project that use it.

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
