### PR TITLE
Drop unneeded hack in fedora virt install

### PR DESCRIPTION
**Pull request by marusak**
* [x] image-refresh fedora-30
 * [x] image-refresh fedora-31

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-85-20191003-074747/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-85-20191003-074747/

**Comment by cockpituous** [comment]
image-refresh fedora-30 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-30-20191003-082323

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-jzcxz.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-85-20191003-082424/

**Comment by cockpituous** [comment]
image-refresh fedora-31 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-31-20191003-084242

**Comment by marusak** [comment]
Both refreshes were successful. I don't plan to pick them up, since if this would now work, it would not get through kickstart and failed to build.

**Comment by martinpitt** [comment]
Just thought -- will this work for RHEL as well?

**Pull request merged**
