### PR TITLE
Image refresh for fedora-34

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-34
 * [x] image-refresh fedora-34

### CODE REVIEW

**Review by allisonkarlitskaya — DISMISSED** [review]

**Comment by martinpitt** [comment]
@allisonkarlitskaya : FYI, I already retried the mobile test this morning, it [failed in the same way again](https://logs.cockpit-project.org/logs/pull-2664-20211126-091310-ab164a85-fedora-34-mobile-cockpit-project-cockpit/log.html#216-2). That focus ring now appearing is dubious

**Comment by allisonkarlitskaya** [comment]
This somehow seems so unlikely to have been caused by an OS update... but it must surely be.  I'm going to run `fedora-34/mobile` in an unrelated PR just to triple-check...

**Comment by allisonkarlitskaya** [comment]
In this update:

```
  stratisd (2.4.2-2.fc34 -> 2.4.3-1.fc34)
```

**Comment by martinpitt** [comment]
The [stratis pixel test failure](https://logs.cockpit-project.org/logs/pull-2664-20211126-091310-ab164a85-fedora-34-mobile-cockpit-project-cockpit/log.html#216-2) got fixed in https://github.com/cockpit-project/cockpit/pull/16664 today, so retrying.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
