### PR TITLE
[no-test] Image refresh for centos-9-stream

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-9-stream
 * [ ]  image-refresh  centos-9-stream
 * [x] image-refresh centos-9-stream

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-13.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-085757/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-092008

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-13.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-092020/

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-13.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-094343/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-095704

**Comment by cockpituous** [comment]
image-refresh in progress on 1-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-095757/

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-16.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-101919/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-102357

**Comment by cockpituous** [comment]
image-refresh in progress on 1-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-102424/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-104332

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-16.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-104343/

**Review by jelly — APPROVED** [review]

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-3.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-104949/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-105317

**Comment by cockpituous** [comment]
image-refresh in progress on 1-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-105353/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-110817

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-rwwzt.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-4005-20221101-110808/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-111657

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-112156

**Comment by cockpituous** [comment]
image-refresh in progress on 4-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-112222/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-112222/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-114043

**Comment by cockpituous** [comment]
image-refresh in progress on 3-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-114040/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-114202

**Comment by cockpituous** [comment]
image-refresh in progress on 2-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-114242/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-115005

**Comment by cockpituous** [comment]
image-refresh in progress on 3-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-115050/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-121050

**Comment by cockpituous** [comment]
image-refresh in progress on 3-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-121111/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-121515/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-121822

**Comment by cockpituous** [comment]
image-refresh in progress on 3-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-121818/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-123950

**Comment by cockpituous** [comment]
image-refresh in progress on 3-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-124040/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-124336

**Comment by cockpituous** [comment]
image-refresh in progress on 2-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-124343/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-125336

**Comment by cockpituous** [comment]
image-refresh in progress on 3-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-125353/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-131111/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-131232

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-131212/

**Comment by cockpituous** [comment]
image-refresh centos-9-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-9-stream-20221101-132142

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-6.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-132121/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-131111/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-133131/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-131212/

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-15.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-133232/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-132121/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-133434/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-133232/

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-15.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-134646/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-133434/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-135454/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-134646/

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-15.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-135858/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-135858/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-140909/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-135454/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-141414/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-140909/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-142828/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-141414/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-143333/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-142828/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-4005-20221101-143333/

**Pull request merged**
