### PR TITLE
Image refresh for centos-8-stream

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-8-stream
 * [x] image-refresh centos-8-stream
 * [x] https://github.com/cockpit-project/cockpit/pull/19265

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/centos-8-stream-20230827-225858.log

**Comment by jelly** [comment]
Retrying to see if this is a SELinux flake.

**Comment by martinpitt** [comment]
It also [happens on the current image](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19069-20230831-104720-4f88c3d0-centos-8-stream-pybridge-other/log.html), so it's not a regression -- but one of our top flakes right now. I'll look at it ASAP. It may just take longer, but first I'll see whether I can reproduce it.

**Comment by martinpitt** [comment]
I think the reason is that the string got wider, and the original reference marks only the original area as "ignore me"; that happens via transparency or some other magic value in the ref png. So what happens is that the wider string now flows outside that marked area, and thus becomes diff-y; if we accept that new reference, that will just make the ignored area wider, and thus should work with both the old and new image, and woud also conceptually be correct; does that make sense @mvollmer , or am I misunderstanding how ignoring works?

**Comment by martinpitt** [comment]
Sent fix to https://github.com/cockpit-project/cockpit/pull/19265 , blocking on that.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
