### PR TITLE
images: Update repos for rhel-7.9

### LINKED ISSUE #1305: Image refresh for rhel-7-9
Image refresh for rhel-7-9
 * [ ] FAIL: image-refresh rhel-7-9

### PR DESCRIPTION
**Pull request by marusak**
It has been released to the URL has been updated.

 * [x] image-refresh rhel-7-9

Fixes #1305

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-1332-20201023-073838/

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-7-9-20201023-080606

**Comment by marusak** [comment]
@atodorov lorax is failing on non-existing repos. Can you please update it? Thanks!

**Comment by atodorov** [comment]
> @atodorov lorax is failing on non-existing repos. Can you please update it? Thanks!

This sounds like an issue for RCM. ATM we don't have capacity to work on lorax tests so ignore the failures. Will deal with them once we get back to testing composer-cli or lorax-composer for RHEL 7.

**Comment by marusak** [comment]
Our things are green. Can someone please review, I opened the original PR.

**Review by martinpitt — APPROVED** [review]
Thanks! :man_pilot:

**Pull request merged**
