### PR TITLE
images: Add tracer to rhel-8-4 image

### PR DESCRIPTION
**Pull request by martinpitt**
With that we can enable tests for cockpit's tracer [1] on RHEL 8.

[1] https://github.com/cockpit-project/cockpit/pull/14581

 * [x] image-refresh rhel-8-4
 * [x] Land https://github.com/cockpit-project/cockpit/pull/14581 first, in case this needs any test adjustments
 * [x] pmlogger.service regression is handled as part of PR #1690 
 * [x] Fix cockpit-composer rhel8 branch for react-styles: https://github.com/osbuild/cockpit-composer/pull/1236

See https://github.com/cockpit-project/cockpit/pull/15356 , https://github.com/cockpit-project/cockpit/pull/15372 , https://github.com/candlepin/subscription-manager/pull/2447 and https://github.com/candlepin/subscription-manager/pull/2448 for some discussion what to do about the recently broken rhsm. Filed https://bugzilla.redhat.com/show_bug.cgi?id=1930037 to track this properly.

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-1684-20210216-055454/

**Comment by martinpitt** [comment]
@skobyda FYI

**Comment by cockpituous** [comment]
image-refresh rhel-8-4 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-4-20210216-061313

**Comment by martinpitt** [comment]
The tracer PR landed. I expect some failures on rhel-8-4, let's get a full picture.

**Comment by martinpitt** [comment]
This [broke subscription-manager](https://logs.cockpit-project.org/logs/pull-1684-20210216-175536-6f31a40d-rhel-8-4-cockpit-project-cockpit/log.html#98-2), same as in the current centos-8-stream refresh. This is independent of adding tracer, of course, but needs to be addressed first. Tracer PRs got skipped, so we can enable them after landing this.

**Comment by martinpitt** [comment]
subscription-manager debugging notes:
 - when I start the test, and immediately ssh to the VM and type `subscription-manager status`, this gives rhsm-service a head start, and the test succeeds.
 - when the test runs without me meddling, the journal has no trace of making an effort to start rhsm-service.
 - when I log in manually after that, I *do* see "Not registered", and *then* it starts rhsm.service.
 - Direct D-Bus call seems to work:
```
# busctl call com.redhat.RHSM1 /com/redhat/RHSM1/Entitlement com.redhat.RHSM1.Entitlement GetStatus ss '' ''
s "{\"status\": \"Unknown\", \"status_id\": \"unknown\", \"reasons\": {}, \"reason_ids\": {}, \"valid\": false}"
```

**Comment by martinpitt** [comment]
Rebased to pick up the naughty from #1690.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-1684-20210218-104848/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-1684-20210218-110505/

**Comment by cockpituous** [comment]
image-refresh rhel-8-4 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-4-20210218-110606

**Comment by cockpituous** [comment]
image-refresh rhel-8-4 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-4-20210218-112323

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-1684-20210218-134242/

**Comment by cockpituous** [comment]
image-refresh rhel-8-4 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-4-20210218-140000

**Comment by martinpitt** [comment]
The bug is still being discussed. But I would like to not block rhel-8-4 image refreshes any further, especially as 8.4 is in heavy flux right now and it is critical to spot regressions quickly.

**Review by marusak — APPROVED** [review]
Thanks!
According to the current BZ state, it seems like we should test how it behaves when `enabled=0` as well. But lets not block on then and lets keep discussion for the BZ.

**Pull request merged**
