### PR TITLE
images: debian: require udisk2-btrfs for cockpit-storaged

### PR DESCRIPTION
**Pull request by jelly**
Add udisks2-btrfs as new Cockpit dependency for the btrfs storage page integration.

 * [x] image-refresh debian-testing
 * [x] image-refresh debian-stable
 * [x] image-refresh ubuntu-stable
 * [x] image-refresh ubuntu-2204

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20231206-090652

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-testing-20231206-090606.log

**Comment by jelly** [comment]
I typo'd, let's first do Debian.

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20231206-130408

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/ubuntu-stable-20231206-130404.log

**Comment by cockpituous** [comment]
image-refresh ubuntu-2204 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2204-20231206-131822

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/ubuntu-2204-20231206-131818.log

**Comment by martinpitt** [comment]
[This failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5640-20231206-145314-aafe3d31-ubuntu-stable-expensive-cockpit-project-cockpit/log.html#55) is hopefully a flake, retrying.

**Review by martinpitt — APPROVED** [review]
Thanks! (Bots have the last word, of course)

**Pull request merged**
