### PR TITLE
Image refresh for rhel-7-8

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-7-8
 * [x] image-refresh rhel-7-8

### CODE REVIEW

**Comment by marusak** [comment]
[log](https://209.132.184.41:8493/logs/pull-382-20200102-064848-80d45dd2-weldr-cockpit-composer--rhel-7-8-firefox/log.html)

**Comment by marusak** [comment]
@henrywang `rhel-7-8/firefox@weldr/cockpit-composer` is failing all the time. I really don't have any idea what is happening, but looks like it cannot connect to firefox? Could it be related to image refresh?

```
[0-0] RUNNING in firefox - /specs/api.test.js
[0-0] Error: Failed to create session.
Make sure to connect to valid hostname:port or the port is not in use.
If you use a grid server 
Make sure to add vendor prefix like "goog:", "appium:", "moz:", etc to non W3C capabilities.
See more https://www.w3.org/TR/webdriver/#capabilities
```
[log](https://209.132.184.41:8493/logs/pull-382-20200102-064848-80d45dd2-weldr-cockpit-composer--rhel-7-8-firefox/log.html)

**Comment by marusak** [comment]
Hmm, it seems this image refresh is not related, since the same thing is happening in current master as well on all OSes - https://github.com/weldr/cockpit-composer/pull/862

**Comment by martinpitt** [comment]
Composer tests got fixed, unblocking.

**Comment by martinpitt** [comment]
This now failed as the services image got changed in the meantime. Rebased to current master.

**Pull request merged**
