### PR TITLE
Image refresh for rhel-9-2

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-2
 * [x] image-refresh rhel-9-2

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-9-2 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-2-20240418-112628

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-2-62cc9cad-20240418-111202/log.html

**Comment by martinpitt** [comment]
This was done by request of @ptoscano Blocking as he wanted this as testing ground. Pino, please say how to proceed.

**Comment by ptoscano** [comment]
> This was done by request of @ptoscano Blocking as he wanted this as testing ground. Pino, please say how to proceed.

The tests seem working fine, so I'd ask to get this in, if possible. Thanks!

**Review by martinpitt — APPROVED** [review]
Sure! We keep these images solely for sub-man's benefit anyway.

**Pull request merged**
