### PR TITLE
images: Add fedora-41 image

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh fedora-41

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-41-2497a1cf-20240816-100202/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-41-f3acb888-20240816-101103/log.html

**Comment by mvollmer** [comment]
Transaction failed: Signature verification failed.
    PGP check for package "bash-5.2.32-1.fc41.x86_64" (/var/lib/mock/fedora-rawhide-x86_64/root/var/cache/dnf/fedora-2d95c80a1fa0a67d/packages/bash-5.2.32-1.fc41.x86_64.rpm) from repo "fedora" has failed: Import of the key didn't help, wrong key?

Hmm, is mock still pointing to rawhide?

**Comment by martinpitt** [comment]
image build log says:

    mock-core-configs                 noarch 40.6-2.fc41     fedora     336.5 KiB

https://bodhi.fedoraproject.org/updates/FEDORA-2024-a27ffd7504 is supposed to fix it (mock-core-configs-41.2-1.fc41), so let's wait a day and retry on Monday?

**Comment by mvollmer** [comment]
> https://bodhi.fedoraproject.org/updates/FEDORA-2024-a27ffd7504 is supposed to fix it (mock-core-configs-41.2-1.fc41), so let's wait a day and retry on Monday?

Yep.

**Comment by martinpitt** [comment]
@mvollmer cool, worked now! Please add it to `image-trigger`, `_manual` testmap entries, and commit the image refresh. We already copied naughties before.

**Comment by cockpituous** [comment]
image-refresh fedora-41 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-41-20240818-063313

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-41-f3acb888-20240818-061709/log.html

**Comment by martinpitt** [comment]
@mvollmer most people try starter-kit first, but I see you are heading straight to the top :mountain: :grin: :muscle: That almost surely will need adjustments in cockpit's tests. Please rebase after the first run, I don't want to land this with umpteen failures, as that'll completely ruin our test statistics.

**Review by martinpitt — APPROVED** [review]
Thanks! starter-kit is green and can move to automatic. podman and sub-man also have a good chance of succeeding.

**Pull request merged**
