### PR TITLE
images: Drop obsolete hacks from rhel-7-9 image

### PR DESCRIPTION
**Pull request by martinpitt**
In the future, hacks like disabling kdump.service belong into *.install
files.

 * [x] get https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-45d010c190 into stable
 * [x] image-refresh rhel-7-9
 * [x] image-refresh centos-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-2253-20210728-050404/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-2253-20210728-050404/

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-7-9-20210728-053030

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-2253-20210728-053030/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-7-20210728-060202

**Comment by martinpitt** [comment]
Argh, that can't work yet, https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-45d010c190 did not make it into stable yet.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-2253-20210805-044848/

**Comment by martinpitt** [comment]
Bah, "Package mock.noarch 0:2.11-1.el7 will be installed" [log](https://logs.cockpit-project.org/logs/image-refresh-2253-20210728-050404/backup.txq5a2rl/log). So one day was still not enough to catch up with mirrors.

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2253-20210805-050505/

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-7-9-20210805-053737

**Comment by martinpitt** [comment]
EPEL 7 repos are *still* showing the old broken version, even with epel-testing. I asked on https://bugzilla.redhat.com/show_bug.cgi?id=1976702#c17

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-2253-20210812-064343/

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-7-9-20210812-070808

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-2253-20210812-071212/

**Comment by martinpitt** [comment]
Thanks @marusak ! Seems it's working now, it pulled in mock 2.12 at last. I'll leave this to you then :)

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-7-20210812-074646

**Comment by marusak** [comment]
All passed. @mvollmer wanna review as well?

**Review by mvollmer — APPROVED** [review]

**Pull request merged**
