### PR TITLE
images: Introduce Alpine image

### PR DESCRIPTION
**Pull request by mvollmer**
This will be used for guests in the cockpit-machines tests.  It has qemu-guest-agent, for example.

 * [x] image-refresh alpine

### CODE REVIEW

**Comment by mvollmer** [comment]
Can it really be this simple?

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-alpine-781a5949-20240426-140749/log.html

**Comment by mvollmer** [comment]
Tests are green here: https://github.com/cockpit-project/cockpit-machines/pull/1590

**Review by martinpitt — APPROVED** [review]
Thanks! So we treat this like CirrOS and never auto-update it?

**Pull request merged**
