### PR TITLE
Image refresh for fedora-rawhide-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-boot
 * [x] image-refresh fedora-rawhide-boot

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-boot done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-boot-20240320-224005

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-boot-9af0bc55-20240320-223744/log.html

**Comment by martinpitt** [comment]
Anaconda [failed](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6120-af93d599-20240320-224118-fedora-rawhide-boot-rhinstaller-anaconda-webui/log) with

> ERROR    Error validating install location: Could not find an installable distribution at URL '/work/make-checkout-workdir/bots/images/fedora-rawhide-boot'

@M4rtinK @KKoukiou ring a bell?

**Comment by martinpitt** [comment]
Ah, thanks @KKoukiou !

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
