### PR TITLE
Image refresh for centos-8-stream

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-8-stream
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by marusak** [comment]
[testFips](https://logs.cockpit-project.org/logs/pull-1311-20201015-083126-ad1bd39e-centos-8-stream-cockpit-project-cockpit-rhel-8.3/log.html#47-2) failed, lets compare.

**Comment by marusak** [comment]
`testFips` fails reliably, needs work.

**Comment by Gundersanne** [comment]
@marusak encountered that 2 weeks ago as well, it's just extremely flaky

**Comment by marusak** [comment]
aha, this is problem in rhel-8.3 branch. In master we have fix for it. I sent backport in https://github.com/cockpit-project/cockpit/pull/14794

**Comment by martinpitt** [comment]
Landed the fix, retried.

**Review by marusak — APPROVED** [review]
testFips succeeded.  Other test succeeded before.

**Pull request merged**
