### PR TITLE
images: Add redis to Fedora images

### PR DESCRIPTION
**Pull request by martinpitt**
This is necessary for exporting PCP data to Grafana with the
https://github.com/performancecopilot/grafana-pcp plugin.

It is not enabled/started by default, thus does not change behaviour of
existing tests.

----

As fedora-33 is currently being refreshed in PR #1985 , I build f-testing here instead. That's just f-33 with newer packages, so should be sufficient to prove that redis can be installed on fedora-33.

 * [x] image-refresh fedora-34
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-1991-20210505-075757/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1991-20210505-075757/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-1991-20210505-080707/

**Comment by martinpitt** [comment]
Heh, fedora-34 bootstrap script needs adjustment, 34 is released now. [log](https://logs.cockpit-project.org/logs/image-refresh-1991-20210505-075757/log)

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20210505-082424

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-1991-20210505-083030/

**Comment by cockpituous** [comment]
image-refresh fedora-34 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-34-20210505-085050

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
