### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20230804-225353.log

**Comment by jelly** [comment]
Updates:
```
Changed:
  abseil-cpp (20230125.3-1 -> 20230125.3-2)
  binutils (2.40-6 -> 2.41-3)
  btrfs-progs (6.3.2-1 -> 6.3.3-1)
  ca-certificates-mozilla (3.91-1 -> 3.92-1)
  crun (1.8.5-1 -> 1.8.6-1)
  curl (8.2.0-2 -> 8.2.1-1)
  device-mapper (2.03.21-1 -> 2.03.22-1)
  elfutils (0.189-1 -> 0.189-3)
  gcc-libs (13.1.1-2 -> 13.2.1-3)
  glibc (2.37-3 -> 2.38-2)
  gmp (6.2.1-2 -> 6.3.0-1)
  libarchive (3.7.0-2 -> 3.7.1-1)
  libelf (0.189-1 -> 0.189-3)
  libsysprof-capture (3.48.0-2 -> 3.48.0-4)
  libvirt (1:9.5.0-1 -> 1:9.6.0-1)
  libvirt-python (1:9.5.0-1 -> 1:9.6.0-1)
  licenses (20220125-2 -> 20230729-1)
  linux (6.4.6.arch1-1 -> 6.4.8.arch1-1)
  linux-api-headers (6.3-1 -> 6.4-1)
  lvm2 (2.03.21-1 -> 2.03.22-1)
  mesa (23.1.4-2 -> 1:23.1.5-1)
  mpfr (4.2.0.p12-1 -> 4.2.0.p12-3)
  nss (3.91-1 -> 3.92-1)
  openssl (3.1.1-1 -> 3.1.2-1)
  polkit (122-1 -> 123-1)
  python-chardet (5.1.0-3 -> 5.2.0-1)
  python-yaml (6.0.1-1 -> 6.0.1-2)
  sssd (2.9.0-2 -> 2.9.1-1)
  systemd (253.7-1 -> 254-1)
  systemd-libs (253.7-1 -> 254-1)
  systemd-sysvcompat (253.7-1 -> 254-1)
  thin-provisioning-tools (1.0.4-1 -> 1.0.5-1)
  xz (5.4.3-1 -> 5.4.4-1)
```

systemd 254 seems like a good candidate for:
`TestHistoryMetrics.testEvents` and `TestJournal.testRebootAndTime`.

`TestStorageResize.testResizeNtfs`

**Comment by jelly** [comment]
Systemd issue is https://github.com/systemd/systemd/issues/28746

**Comment by mvollmer** [comment]
> @mvollmer ever seen this?
> 
> ```
> Error resizing logical volume: Process reported exit code 5: File system device usage is not available from libblkid.
> ```
> 
> Only thing I'd say which we might be related in the updates is device mapper or lvm2?
> 
> ```
>   device-mapper (2.03.21-1 -> 2.03.22-1)
>   lvm2 (2.03.21-1 -> 2.03.22-1)
> ```
> 
> And there you go, a little bit more searching around:
> 
> https://github.com/lvmteam/lvm2/blob/847f1dd99cb74dac37c1379627fa5d2d52250fa6/lib/metadata/lv_manip.c#L6108
> 
> So, we'll need to write a reproducer and send it over to the LVM guys.

The issue: https://github.com/lvmteam/lvm2/issues/123
Proposed fix in libblockdev: https://github.com/storaged-project/libblockdev/pull/952

**Comment by tbzatek** [comment]
> Which is kinda odd, as there should be a `ntfs` kernel module but anyway it fails with:

Note that without `ntfs-3g` the `ntfs` kernel module represents the legacy read-only driver that is often disabled in distributions. Sadly the new `ntfs3` driver has a different name.

**Comment by jelly** [comment]
@tomasmatus @mvollmer This refresh is now green, you'll need to decide if a naughty is valid or that we should fix Cockpit's invocation with journalctl's new `--lines` behaviour when `--since` or `--until` is specified. So far the breakage seems to be the logs page and metrics log details. The systemd issue is https://github.com/systemd/systemd/issues/28746#issuecomment-1673873908

**Review by tomasmatus — APPROVED** [review]

**Comment by jelly** [comment]
> > Which is kinda odd, as there should be a `ntfs` kernel module but anyway it fails with:
> 
> Note that without `ntfs-3g` the `ntfs` kernel module represents the legacy read-only driver that is often disabled in distributions. Sadly the new `ntfs3` driver has a different name.

Yes, which is a bit sad due to things like this https://github.com/util-linux/util-linux/issues/1508

**Pull request merged**
