### PR TITLE
Image refresh for rhel-9-4

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-4
 * [x] image-refresh rhel-9-4

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-9-4 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-4-20240125-101956

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-4-20240125-101919.log

**Comment by mvollmer** [comment]
> Hmm, [this test](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5835-20240125-102112-87a72e53-rhel-9-4-storage-cockpit-project-cockpit/log.html#54-2) runs into OOM, this needs work.

It passes locally, but memory usage is very close to the available 1.4 GiB.  Other LUKS tests are the same. Our rhel-9-4 image has no swap (but the kernel will page code in and out.)

I'll make a PR to increase the amount of memory, and show some statistics there.

**Comment by mvollmer** [comment]
> It passes locally, but memory usage is very close to the available 1.4 GiB. Other LUKS tests are the same. Our rhel-9-4 image has no swap (but the kernel will page code in and out.)

Let's try adding swap: https://github.com/cockpit-project/bots/pull/5870

**Pull request closed without merging**
