### PR TITLE
Image refresh for fedora-rawhide-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-boot
 * [x] image-refresh fedora-rawhide-boot
 * #4224

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-boot-20230102-060606.log

**Comment by martinpitt** [comment]
Still a lot of unexpected SELinux messages, but they don't seem to break the actual tests.

**Comment by martinpitt** [comment]
Two weeks old, let's do a fresh one.

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-boot done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-boot-20230118-155128

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-boot-20230118-155151.log

**Comment by martinpitt** [comment]
@M4rtinK , @jkonecny12, do these [SELinux errors](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4225-20230102-060810-4bdb672f-fedora-rawhide-boot-rhinstaller-anaconda/log.html#3) ring a bell?

> avc:  denied  { create } for  pid=4896 comm="bash" name="cockpit.conf" scontext=system_u:system_r:kernel_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=file permissive=1
> avc:  denied  { create } for  pid=4900 comm="mkdir" name="cockpittest" scontext=system_u:system_r:kernel_t:s0 tcontext=unconfined_u:object_r:var_lib_t:s0 tclass=dir permissive=1

These are with SELinux in permissive mode (which is not the default), and it seems they run in `kernel_t` context, which is certainly unusual. `data/liveinst/liveinst` calls `setenforce 0`, is that involved in the test run? If Anaconda is somehow known not to work with SELinux, then the integration tests should just disable the checking of unexpected messages, by calling the tests with env `TEST_AUDIT_NO_SELINUX=1`. But I can't judge whether this would be the right thing to do, or if there's something actually wrong with Rawhide's current SELinux policy.

Thanks in advance!

**Comment by martinpitt** [comment]
Re-testing a current image in #4287

**Comment by martinpitt** [comment]
Closing in favor of #4287. Still the same problem, but at least a current image.

**Pull request closed without merging**
