### PR TITLE
Image refresh for fedora-36

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-36
 * [x] image-refresh fedora-36
 * Land in lockstep with https://github.com/cockpit-project/cockpit/pull/18026

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-36-20221208-084040.log

**Comment by martinpitt** [comment]
New image apparently breaks podman checkpoints/criu, somewhere between these:

```
  container-selinux (2:2.191.0-1.fc36 -> 2:2.193.0-1.fc36)
  crun (1.7-1.fc36 -> 1.7.2-1.fc36)
  kernel-core (6.0.10-200.fc36 -> 6.0.11-200.fc36)
```

**Comment by KKoukiou** [comment]
> New image apparently breaks podman checkpoints/criu, somewhere between these:
> 
> ```
>   container-selinux (2:2.191.0-1.fc36 -> 2:2.193.0-1.fc36)
>   crun (1.7-1.fc36 -> 1.7.2-1.fc36)
>   kernel-core (6.0.10-200.fc36 -> 6.0.11-200.fc36)
> ```

From the journal.

Dec 08 08:51:52 fedora-36-127-0-0-2-2201 podman[2267]: could not load `libcriu.so.2`

**Comment by martinpitt** [comment]
This triggers a very strong déjà vu. @jelly recently looked at that in rawhide or F37, but I [don't see a naughty  for it](https://github.com/cockpit-project/bots/issues)

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20221208-151049

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20221209-153900

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-36-20221209-153939.log

**Comment by martinpitt** [comment]
[annoying unrelated pixel failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4144-20221212-125453-655436bb-fedora-36-cockpit-project-cockpit/log.html#65), retrying

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/18026 . If that goes green, that and this PR need to land in lockstep.

**Pull request merged**
