### PR TITLE
images: install strace and ltrace on rhel

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
strace and ltrace are extremely useful tools, and quite small.  Let's
have them in our images.

 * [x] image-refresh centos-7
 * [x] image-refresh rhel-7-7
 * [x] image-refresh rhel-7-8
 * [x] image-refresh rhel-8-0
 * [x] image-refresh rhel-8-1
 * [x] image-refresh rhel-8-2

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-n9pgb.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-204-20191103-131818/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/bots/commits/image-refresh-centos-7-20191103-133838

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-204-20191103-133838/

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-7-7-20191103-141313

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-01.
Log: https://209.132.184.41:8493/logs/image-refresh-204-20191103-142323/

**Comment by cockpituous** [comment]
image-refresh rhel-7-8 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-7-8-20191103-145656

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-204-20191103-144747/

**Comment by cockpituous** [comment]
image-refresh rhel-8-0 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-0-20191103-151818

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-204-20191103-151818/

**Comment by cockpituous** [comment]
image-refresh rhel-8-1 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-1-20191103-154040

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-05.
Log: https://209.132.184.41:8493/logs/image-refresh-204-20191103-154141/

**Comment by cockpituous** [comment]
image-refresh rhel-8-2 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-2-20191103-160000

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-204-20191103-160101/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-204-20191103-160101/

**Comment by martinpitt** [comment]
I deleted the invalid "rhel" image task, others succeeded.

**Comment by martinpitt** [comment]
@allisonkarlitskaya : Sorry, the [centos-7 refreshed image](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-204-20191104-090101-49eb0a92-cockpit-project-starter-kit-- centos-7/log.html) got lost (long story). But as the rebuild clearly worked, and this isn't blocking you, it's fine to just let this get picked up at the next automatic image refresh.  Can you please drop the centos-7 commit, add a Closes#, and force-push?

**Pull request merged**
