### PR TITLE
Revert "images: Keep cloud-init on alpine"

### PR DESCRIPTION
**Pull request by martinpitt**
This reverts commit 5d9537a09e9c9c8e7d123191d49cb9c41b2161c8.

---

This causes too much fallout due to the longer boot times. Often [like this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1617-4b480c08-20240508-081118-fedora-40-devel/log.html#57-2), but sometimes as bad as [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1620-71bf3b66-20240507-181428-fedora-39/log.html).

 * [x] image-refresh alpine

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-alpine-7349dbd2-20240508-093924/log.html

**Comment by mvollmer** [comment]
> Often [like this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1617-4b480c08-20240508-081118-fedora-40-devel/log.html#57-2)

I am still debugging this. It might not have been caused by cloud-init.

**Comment by mvollmer** [comment]
We can easily have two variants of the alpine image, they are tiny.

**Review by mvollmer — APPROVED** [review]
Not a cloud in the sky!

**Pull request merged**
