### PR TITLE
bots: Install open-iscsi on Debian/Ubuntu images

### PR DESCRIPTION
**Pull request by martinpitt**
So that we can test Cockpit iSCSI functionality on them.

 * [x] image-refresh debian-stable
 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-1804
 * [x] image-refresh ubuntu-2004
 - [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-651-20200318-120707/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/bots/commits/image-refresh-debian-stable-20200318-123737

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-651-20200318-123838/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-651-20200318-123838/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-651-20200318-130303/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1804 done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-1804-20200318-132222

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-651-20200318-132222/

**Comment by martinpitt** [comment]
On [debian-testing](https://logs.cockpit-project.org/logs/image-refresh-651-20200318-123838/log), the installation of the package fails because rtslib-fb-targetctl.service can't find the kernel module; no wonder, it's being upgraded. I'll add a hack for this.

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-651-20200318-132828/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2004 done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-2004-20200318-134545

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-651-20200318-134646/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/bots/commits/image-refresh-debian-testing-20200318-140000

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-651-20200318-140202/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-stable-20200318-141313

**Comment by cockpituous** [comment]
image-refresh ubuntu-2004 done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-2004-20200318-143737

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-651-20200318-143939/

**Pull request merged**
