### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-testing-20230717-225757.log

**Comment by martinpitt** [comment]
>  selinux-policy (38.20-1.fc38 -> 38.21-1.fc38)

[This failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5014-20230717-225836-b98bfddb-fedora-testing-daily-cockpit-project-cockpit/log.html#69) seems relevant and needs to be reported. In the meantime, retrying [this unit test failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5014-20230717-225836-b98bfddb-fedora-testing-daily-cockpit-project-cockpit/log.html#69)

**Comment by martinpitt** [comment]
This broke a lot of tests, and unfortunately https://bodhi.fedoraproject.org/updates/FEDORA-2023-2663818afd was fast-paced into Fedora so it already landed in F38 now. :cry:

**Review by marusak — APPROVED** [review]
:/ @ selinux

Thanks!

**Pull request merged**
