### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by mvollmer** [comment]
The podman failure seems real:
```
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/check-application", line 1029, in testNotRunning
    is_enabled_user("disabled")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/check-application", line 997, in is_enabled_user
    b.wait(lambda: self.execute(False, "systemctl --user is-enabled podman.socket || true").strip() == string)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 373, in wait
    raise Error('timed out waiting for predicate to become true')
```

I'll investigate.

**Comment by mvollmer** [comment]
> The podman failure seems real:

The failure also happens with the current `debian-testing` image, debian-testing-2324c4e562fd18436da8b0ff4d360ac5bb0babd80f778b4eab7d25a7914dae98.qcow2, at least for me locally.
Disabling podman,socket is not reflected in the systemd API:

```
root@debian:~# systemctl --user enable podman.socket
Created symlink /root/.config/systemd/user/sockets.target.wants/podman.socket → /usr/lib/systemd/user/podman.socket.
root@debian:~# systemctl --user is-enabled podman.socket
enabled
root@debian:~# systemctl --user disable podman.socket
Removed /root/.config/systemd/user/sockets.target.wants/podman.socket.
root@debian:~# systemctl --user is-enabled podman.socket
enabled
```

But podman is routinely tested with debian-testing.... hmm.

**Comment by mvollmer** [comment]
> Disabling podman,socket is not reflected in the systemd API:

The same happens for other socket units that can be enabled:

```
admin@debian:~$ systemctl --user enable gpg-agent.socket
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/gpg-agent.socket → /usr/lib/systemd/user/gpg-agent.socket.
admin@debian:~$ systemctl --user disable gpg-agent.socket
Removed /home/admin/.config/systemd/user/sockets.target.wants/gpg-agent.socket.
admin@debian:~$ systemctl --user status gpg-agent.socket
● gpg-agent.socket - GnuPG cryptographic agent and passphrase cache
     Loaded: loaded (/usr/lib/systemd/user/gpg-agent.socket; enabled; vendor preset: enabled)
     Active: active (listening) since Mon 2020-09-21 13:00:40 UTC; 9min ago
   Triggers: ● gpg-agent.service
       Docs: man:gpg-agent(1)
     Listen: /run/user/1002/gnupg/S.gpg-agent (Stream)
     CGroup: /user.slice/user-1002.slice/user@1002.service/gpg-agent.socket

Sep 21 13:00:40 debian systemd[2394]: Listening on GnuPG cryptographic agent and passphrase cache.
```

**Comment by mvollmer** [comment]
> Disabling podman,socket is not reflected in the systemd API:

This happens because it is still enabled with `--global`, d'oh.

**Comment by mvollmer** [comment]
Blocked on https://github.com/cockpit-project/cockpit-podman/pull/541

**Comment by martinpitt** [comment]
> But podman is routinely tested with debian-testing.... hmm.

podman 2.0.6 [migrated to testing](https://tracker.debian.org/news/1177192/libpod-206dfsg1-1-migrated-to-testing/) two days ago, and we don't  pre-install it on the d-testing image. Thus it can "spontaneously" break. We should probably fix that -- d-testing has become a permanently supported OS for c-podman now.

**Review by martinpitt — APPROVED** [review]
Thanks for fixing, @mvollmer!

**Pull request merged**
