### PR TITLE
images: Drop tracer from RHEL 10

### LINKED ISSUE #6738: Image refresh for centos-10
Image refresh for centos-10
 * [ ] FAIL: image-refresh centos-10

### PR DESCRIPTION
**Pull request by martinpitt**
The package was just dropped from RHEL 10 [1], see https://issues.redhat.com/browse/RHELBLD-15667

[1] https://gitlab.com/redhat/centos-stream/rpms/tracer/-/commit/513b244618e63630

Fixes #6738

----

 * [x] image-refresh rhel-10-0
 * [x] image-refresh centos-10

This needs to land in lockstep with https://github.com/cockpit-project/cockpit/pull/20892 . Cockpit /expensive tests run there.

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240816-055737

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-6ff060cd-20240816-054222/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-10-0-6ff060cd-20240816-055842/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-10-0-6ff060cd-20240816-060841/log.html

**Comment by martinpitt** [comment]
grrr.. rpmlint got dropped as well: https://pkgs.devel.redhat.com/cgit/rpms/rpmlint/commit/?h=rhel-10-main&id=9a9efcbfd84418f7145954299049cf5a9b903924

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-10-0-f88f5cd4-20240816-062626/log.html

**Comment by cockpituous** [comment]
image-refresh rhel-10-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-10-0-20240816-065210

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-10-0-ed5ef598-20240816-063642/log.html

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240816-071022

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-ed5ef598-20240816-065427/log.html

**Comment by martinpitt** [comment]
Erk, RHEL 10 breaks crypto-policies: https://cockpit-logs.us-east-1.linodeobjects.com/pull-6739-18fd88a7-20240816-071544-rhel-10-0-other-cockpit-project-cockpit/log.html#81

**Review by mvollmer — APPROVED** [review]
Thanks!

**Pull request merged**
