### PR TITLE
debian.setup: unbreak pbuilder on Ubuntu

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
b51ce28add hardcoded the URL to the Debian archive without taking into consideration that `debian.setup` is also used to build Ubuntu images. Add a conditional.

 * [x] image-refresh ubuntu-stable
 * [x] image-refresh ubuntu-2204
 * [x] image-refresh debian-stable
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20230626-100346

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/ubuntu-stable-20230626-100303.log

**Comment by cockpituous** [comment]
image-refresh ubuntu-2204 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2204-20230626-102419

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20230626-104702

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-stable-20230626-104747.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-testing-20230626-105959.log

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20230626-112528

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-testing-20230626-112525.log

**Review by martinpitt — APPROVED** [review]
Thank you! :see_no_evil:

**Pull request merged**
