### PR TITLE
Image refresh for fedora-40

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-40
 * [x] image-refresh fedora-40

Fixes https://github.com/cockpit-project/cockpit/issues/20694

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-40 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-40-20240704-051722

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-40-cfdacfa8-20240704-043643/log.html

**Comment by martinpitt** [comment]
Yup, this adds kdump-utils and should help with https://github.com/cockpit-project/cockpit/issues/20694

**Comment by martinpitt** [comment]
[common flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6577-fc8b9aa2-20240704-051937-fedora-40-firefox-storage-cockpit-project-cockpit/log.html#6-2), retrying

**Pull request merged**
