### PR TITLE
images: Drop unrequired dbus-broker port on rhel-7-9

### PR DESCRIPTION
**Pull request by jelly**
The dbus broker tests run on local host now.

 * [x] image-refresh rhel-7-9

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-2679-20211201-083333/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2679-20211201-083333/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-2679-20211201-083333/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-2679-20211201-083333/

**Comment by martinpitt** [comment]
The image name is "rhel-7-9"; when you push the updated SHA, can you please fix the commit message to say "... on rhel-7-9"?

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-2679-20211201-083636/

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-7-9-20211201-090303

**Comment by martinpitt** [comment]
@jelly : Thanks! Please do `./tests-trigger 2679 image:rhel-7-9` to validate this.

**Comment by jelly** [comment]
> @jelly : Thanks! Please do `./tests-trigger 2679 image:rhel-7-9` to validate this.

Done, everything passed.

**Review by martinpitt — APPROVED** [review]
Thanks!

**Pull request merged**
