### PR TITLE
Image refresh for services

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for services
 * [x] image-refresh services
 * [x] https://github.com/cockpit-project/cockpit/pull/19794

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh services done: https://github.com/cockpit-project/bots/commits/image-refresh-services-20231229-230616

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/services-20231229-230606.log

**Comment by martinpitt** [comment]
Grafana test needs adjusting.

**Comment by martinpitt** [comment]
There is something funky happening at the login page load, it immediately destroys the current execution context and then there's none left:
```
CDP: executionContextCreated {"context":{"id":4,"origin":"http://127.0.0.2:3002","name":"","auxData":{"isDefault":true,"frameId":"6442450946","type":"default"}}}
CDP: loadEventFired, resolving pageLoadHandler
<- {}
-> wait: ph_is_present("body")
CDP: executionContextDestroyed 4
<- raise {'response': {'message': 'Execution context was destroyed.'}}
CDP: {"source":"javascript","level":"error","text":"NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIWebProgress.DOMWindow]","timestamp":1704006607048,"url":"resource://gre/modules/LoginManagerChild.sys.mjs","lineNumber":121}

-> wait: ph_is_present("body")
<- raise {'request': {'method': 'Runtime.evaluate', 'params': {'expression': 'ph_wait_cond(() => ph_is_present("body"), 15000, null)', 'silent': False, 'awaitPromise': True, 'trace': 'wait: ph_is_present("body")', 'contextId': -1}}, 'response': {'message': 'Cannot find context with specified id', 'data': 'evaluate@chrome://remote/content/cdp/domains/content/Runtime.sys.mjs:279:15\nexecute@chrome://remote/content/cdp/domains/DomainCache.sys.mjs:95:25\nreceiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs:79:45\n'}}
```

**Comment by martinpitt** [comment]
Rebased because of [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19794-20240101-181421-8cec757b-fedora-39-firefox-other-bots-5737/log.html). Will run tests in https://github.com/cockpit-project/cockpit/pull/19794 first.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
