### PR TITLE
Image refresh for rhel-9-3

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-3
 * [x] image-refresh rhel-9-3

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-3-20230423-230101.log

**Comment by martinpitt** [comment]
[TestNetworkingBasic.testNoService](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4689-20230424-045151-627b5ebb-rhel-9-3-cockpit-project-cockpit/log.html#72-2) failed twice, needs work.

**Comment by mvollmer** [comment]
> Indeed after stop/start NM, the veth devices don't appear in the list

Should be fixed by https://github.com/cockpit-project/cockpit/pull/18732

**Comment by mvollmer** [comment]
> > Indeed after stop/start NM, the veth devices don't appear in the list
> 
> Should be fixed by [cockpit-project/cockpit#18732](https://github.com/cockpit-project/cockpit/pull/18732)

The test has passed three times with this image and that PR.  (It's a red mess otherwise, hmm...)

**Comment by martinpitt** [comment]
Cockpit fix landed. Rebased to current main.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
