### PR TITLE
Revert "images: temporarily hack around broken cloud-init-utils"

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
This reverts commit 013f6a34baaf11035045753428db02fc5599d071.

The arch image is now fixed, so we don't need this hack anymore.

 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20230705-073441

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20230705-073434.log

**Review by martinpitt — DISMISSED** [review]
Thanks!

**Review by martinpitt — APPROVED** [review]
Thanks! Assuming green as always.

**Comment by jelly** [comment]
After grabbing some more coffee, this is totally something else and needs a new naughty..

```
  File "/work/bots/make-checkout-workdir/test/check-machines-settings", line 859, in testVsock
    setVsockLive(new_auto=True, previous_auto=False, previous_address="5", reboot_machine=True)
  File "/work/bots/make-checkout-workdir/test/check-machines-settings", line 801, in setVsockLive
    self.performAction("subVmTest1", "forceOff")
  File "/work/bots/make-checkout-workdir/test/machineslib.py", line 56, in performAction
    b.wait_in_text("#vm-{0}-{1}-state".format(vmName, connectionName), "Shut off")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 648, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 587, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 293, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#vm-subVmTest1-system-state","Shut off")): Uncaught (in promise) Error: actual text: Running
```

Nothing qemu related was updated
```
Changed:
  archlinux-keyring (20230504-1 -> 20230704-1)
  bluez-libs (5.66-1 -> 5.68-1)
  boost-libs (1.81.0-6 -> 1.81.0-7)
  ca-certificates-mozilla (3.90-1 -> 3.91-1)
  cockpit (294.1-3 -> 295-1)
  firewalld (1.3.3-1 -> 2.0.0-1)
  gettext (0.21.1-5 -> 0.22-1)
  glib-networking (1:2.76.0-2 -> 1:2.76.1-1)
  grub (2:2.06.r566.g857af0e17-1 -> 2:2.06.r591.g6425c12cd-1)
  hwdata (0.371-1 -> 0.372-1)
  icu (72.1-2 -> 73.2-1)
  iproute2 (6.3.0-2 -> 6.4.0-1)
  kbd (2.6.0-1 -> 2.6.1-1)
  libassuan (2.5.5-2 -> 2.5.6-1)
  libksba (1.6.3-1 -> 1.6.4-1)
  libp11-kit (0.24.1-1 -> 0.25.0-1)
  libpng (1.6.40-1 -> 1.6.40-2)
  libproxy (0.5.2-1 -> 0.5.2-2)
  libuv (1.44.2-1 -> 1.46.0-1)
  libwbclient (4.18.3-1 -> 4.18.3-2)
  libxml2 (2.10.4-4 -> 2.10.4-6)
  linux (6.3.9.arch1-1 -> 6.4.1.arch2-1)
  mkinitcpio-busybox (1.35.0-1 -> 1.36.1-1)
  netavark (1.6.0-1 -> 1.7.0-1)
  nss (3.90-1 -> 3.91-1)
  p11-kit (0.24.1-1 -> 0.25.0-1)
  pacman-mirrorlist (20230410-1 -> 20230628-1)
  pcp (6.0.4-1 -> 6.0.5-1)
  procps-ng (3.3.17-1 -> 4.0.3-1)
  protobuf (21.12-2 -> 23.3-1)
  protobuf-c (1.4.1-1 -> 1.4.1-2)
  python-protobuf (21.12-2 -> 23.3-1)
  smbclient (4.18.3-1 -> 4.18.3-2)
  stratis-cli (3.4.0-3 -> 3.5.1-1)
  stratisd (3.4.1-1 -> 3.5.7-1)
  util-linux (2.39-10 -> 2.39.1-1)
  util-linux-libs (2.39-10 -> 2.39.1-1)
  xfsprogs (6.3.0-1 -> 6.3.0-2)
  zlib (1:1.2.13-2 -> 1:1.2.13-3)
  ```

**Comment by jelly** [comment]
Ok, while re-checking, it's the same just a different failure.. as pressing shutdown again gives me

image

**Comment by jelly** [comment]
Nevermind, it's the same, my regex was just faulty..

**Review by martinpitt — APPROVED** [review]
I had a problem, so I used regular expressions. Now I have two problems!

(It's not really a RE, it's a glob, but still)

**Pull request merged**
