### PR TITLE
Image refresh for fedora-40

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-40
 * [x] image-refresh fedora-40

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-40 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-40-20240725-225810

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-40-81061d81-20240725-223742/log.html

**Comment by martinpitt** [comment]
See https://github.com/cockpit-project/cockpit/issues/20797 -- this is a real regression.

**Comment by martinpitt** [comment]
See https://github.com/cockpit-project/cockpit/issues/20797#issuecomment-2272536346 - due to that and this image being stale by now it's worth trying a fresh build.

**Comment by martinpitt** [comment]
→ #6706

**Comment by martinpitt** [comment]
Didn't help, but at least we have a non-obsolete image.

**Pull request closed without merging**
