### PR TITLE
images: Drop enabling sshd.service on Debian/Ubuntu

### LINKED ISSUE #6147: Image refresh for ubuntu-stable
Image refresh for ubuntu-stable
 * [ ] image-refresh ubuntu-stable

### PR DESCRIPTION
**Pull request by martinpitt**
Updating the openssh-server package while `sshd.service` is enabled upsets the maintainer script and fails. It also causes `ssh.socket` to fail as the port is already used.

This leads to image refresh failures whenever the current cloud image doesn't have the current openssh-server version.

https://github.com/cockpit-project/cockpit/pull/20261 fixed Cockpit's tests to not assume `sshd.service` everywhere, so this is obsolete.

----

 * [x] https://github.com/cockpit-project/cockpit/pull/20261
 * [x] image-refresh debian-stable
 * [x] image-refresh ubuntu-2204
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-stable-e3142532-20240404-093738/log.html

**Comment by martinpitt** [comment]
ubuntu-stable is still b0rked:
```
 libvirt-daemon-system : Depends: libvirt-daemon-config-network (= 10.0.0-1ubuntu1) but it is not going to be installed
                         Depends: libvirt-daemon-config-nwfilter (= 10.0.0-1ubuntu1) but it is not going to be installed
                         Depends: libvirt-daemon-system-systemd (= 10.0.0-1ubuntu1) but it is not going to be installed or
                                  libvirt-daemon-system-sysv (= 10.0.0-1ubuntu1) but it is not going to be installed
                         Recommends: mdevctl but it is not going to be installed
 libvirt-dbus : Depends: libglib2.0-0t64 (>= 2.32.0) but it is not installable
```
I suppose that'll take some more time to sort out the time64 transition. Moreover, there seems to be a bug in the archive itself: there are *older* versions in the -updates pocket than in the release pocket, and -updates shouldn't even *have* any packages before the release. :exploding_head:

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20240404-095425

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-debian-stable-e3142532-20240404-094103/log.html

**Comment by martinpitt** [comment]
I asked on IRC, and was pointed to https://discourse.ubuntu.com/t/xz-liblzma-security-update-post-2/43801 -- the current weird state is part of recovering from the xzocalypse, it was a major "reset archive to known good state and rebuild everything".

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-debian-stable-02e0276d-20240404-125919/log.html

**Comment by cockpituous** [comment]
image-refresh ubuntu-2204 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2204-20240404-132723

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-2204-02e0276d-20240404-131315/log.html

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20240404-134326

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-debian-testing-02e0276d-20240404-132731/log.html

**Review by jelly — APPROVED** [review]
Thanks!

**Pull request merged**
