### PR TITLE
tests-scan: Add --match option for triggered contexts

### PR DESCRIPTION
**Pull request by martinpitt**
This allows developers to select a subset easily, especially with
cockpit's recent scenario split. One can e.g. only trigger all Debian
tests with `-m debian` or only all the /networking scenario with
`-m networking`.

---

 - [x] Rebase after PR #5026

I did that in https://github.com/cockpit-project/cockpit/pull/19104 . Demo:

```
❱❱❱ bots/tests-scan -p 19104 -nv -m other 
INFO:root:Processing #19104 titled 'sosreport: Add fallback error message' on revision ece5d7d240b859a8a795f37ba10456399fbd314d
pull-19104  ubuntu-stable/other       ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  ubuntu-2204/other         ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  rhel4edge/other           ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  rhel-9-3/other            ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  rhel-8-9/other            ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  rhel-8-9-distropkg/other  ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  fedora-coreos/other       ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  fedora-38/pybridge-other  ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  fedora-38/other           ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  fedora-38/firefox-other   ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  fedora-37/other           ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  debian-testing/other      ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  debian-stable/other       ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  centos-8-stream/pybridge-other ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  centos-8-stream/other     ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
pull-19104  arch/other                ece5d7d    5.80896  (cockpit-project/cockpit) [bots@main]   {main}
```

### CODE REVIEW

**Review by marusak — COMMENTED** [review]
Why would one want to use `--match`? Isn't it just dangerous that it makes it too easy to only trigger unspecified subset and pretty much impossible to review what contexts are missing?

**Comment by martinpitt** [comment]
I don't suggest we use it very often. It's useful for iterating in cases like #19102 (that took a number of force pushes) without overloading our CI. For that I just did `bots/tests-scan -p 19102 -m /storage`.

It's also useful for e.g. changes to tools/debian or tools/arch/ to select the debian/ubuntu or arch contexts only.

But indeed one should know what they are doing with this. In the future we need to automate this of course.

**Comment by martinpitt** [comment]
@marusak : Not right now, but that's a good idea. That could also be used to "upgrade" a draft PR where we only triggered a single test, without having to re-run packit and such.

**Comment by martinpitt** [comment]
I split out the ruff fixes to PR #5026 and extended them properly. Blocking on that. This PR is more of an experiment anyway.

**Comment by martinpitt** [comment]
This requires a bigger discussion, shelving for now.

**Pull request closed without merging**
