### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch

*  [ ] merge https://github.com/cockpit-project/cockpit/pull/20589
 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240613-224759

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-9bdccd45-20240613-223709/log.html

**Comment by jelly** [comment]
This should be unblocked by https://github.com/cockpit-project/cockpit/pull/20589

**Comment by martinpitt** [comment]
I don't see a corresponding change here to actually install glib2-devel into the build env?

**Comment by martinpitt** [comment]
Closing in favor of #6504

**Pull request closed without merging**
