### PR TITLE
WIP: 867962fd44bc: [no-test] images: Don't grow virtual size of Alpine image

### PR DESCRIPTION
**Pull request by mvollmer**
A large virtual size interferes with testing migration and cloning.

 * [x] image-refresh alpine
 * [ ] image-refresh fedora-40

### CODE REVIEW

**Comment by mvollmer** [comment]
Somehow fedora-40 is fine with it, but other OSes are not.

**Comment by cockpituous** [comment]
image-refresh alpine done: https://github.com/cockpit-project/bots/commits/image-refresh-alpine-20240429-141951

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-alpine-8ed312e3-20240429-141816/log.html

**Review by martinpitt — APPROVED** [review]
Noice!

**Pull request merged**
