### PR TITLE
images: Drop qemu-virtiofsd on fedora-rawhide

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] ~unbreak nodejs in rawhide: https://bugzilla.redhat.com/show_bug.cgi?id=2190075~ -- added workaround (downgrade to nodejs 18)
 * [x] image-refresh fedora-rawhide

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-20230428-114234

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-20230428-114242.log

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-20230428-123156

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-20230428-123131.log

**Comment by cockpituous** [comment]
image-refresh fedora-38 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-38-20230428-134715

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-38-20230428-134747.log

**Comment by martinpitt** [comment]
Meh, esbuild segfaults:
```
DEBUG: NODE_ENV=production ./build.js
DEBUG: make: *** [Makefile:85: dist/manifest.json] Segmentation fault (core dumped)
DEBUG: error: Bad exit status from /var/tmp/rpm-tmp.F7bcr3 (%build)
```

**Comment by martinpitt** [comment]
Ah, this is the nodejs20 segfault again, see https://bugzilla.redhat.com/show_bug.cgi?id=2190075. Not sure what else to do here, I think we can just wait for a fixed nodejs.

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-20230502-081458

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-20230502-081414.log

**Review by martinpitt — APPROVED** [review]
Thanks! @mvollmer , as I added a commit here, please review and land if/once you are  happy.

**Comment by mvollmer** [comment]
> Thanks! @mvollmer , as I added a commit here, please review and land if/once you are happy.

Works for me! Thanks!

**Pull request merged**
