### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing
 * [x] fix utmp restoration as a workaround: https://github.com/cockpit-project/cockpit/pull/13843

### CODE REVIEW

**Comment by marusak** [comment]
Fixed in https://github.com/cockpit-project/cockpit/pull/13828

**Comment by marusak** [comment]
Today is a very bad day for image refreshes :D 
All machine tests fail with:
```
error: Failed to start domain subVmTest1
error: internal error: child reported (status=125): Unable to get host boot time: No such process
```
[log](https://logs.cockpit-project.org/logs/pull-700-20200401-073611-468782d5-fedora-testing-cockpit-project-cockpit/log.html#79-2)

**Comment by martinpitt** [comment]
@marusak: I've see that a lot on current images as well,  it's not related to the refresh. Retrying.

**Comment by martinpitt** [comment]
I just found https://bugzilla.redhat.com/show_bug.cgi?id=1783715 which is about the "unknown host boot time". But no solution :/

**Comment by martinpitt** [comment]
Fix sent in https://github.com/cockpit-project/cockpit/pull/13843  , marking as blocked.

**Comment by martinpitt** [comment]
This [needs rebasing](https://logs.cockpit-project.org/logs/pull-13843-20200403-075955-ee9d3560-fedora-testing-bots-700/log.html#159-2) to pick up the new services image.

**Pull request merged**
