### PR TITLE
Image refresh for fedora-35

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-35
 * [x] image-refresh fedora-35
 * https://github.com/cockpit-project/cockpit/pull/16848

### CODE REVIEW

**Comment by martinpitt** [comment]
Expected to fail in the selinux restricted user test, needs to land in lockstep with https://github.com/cockpit-project/cockpit/pull/16848 . There's a yet newer selinux-policy version now, here's hope that nothing *else* will be broken now :grin:

**Comment by martinpitt** [comment]
I have a feeling that cockpit 260 changed the login page, and we need an updated testlib in sub-man and podman to fix that. Which sets off a wholly new chain of blockage, as we've seen in cockpit-certificates *sigh*

**Comment by martinpitt** [comment]
... and of course it did: cockpit.service fails to start now:
```
[audit[1]: AVC avc:  denied  { unlink } for  pid=1 comm="systemd" name="key.source" dev="tmpfs" ino=1365 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:cockpit_var_run_t:s0 tclass=lnk_file permissive=0
cockpit-certificate-ensure[17998]: cockpit-certificate-ensure: mkdir: /run/cockpit/tls/server: File exists
systemd[1]: cockpit.service: Control process exited, code=exited, status=1/FAILURE
```

I :-1: 'ed https://bodhi.fedoraproject.org/updates/FEDORA-2022-41fa7610dd , but it's again too late, the update was only in testing for 10 hours.

**Comment by marusak** [comment]
I opened https://bugzilla.redhat.com/show_bug.cgi?id=2042369 - lets give selinux guys until Friday and then we can put in some workaround. But this badly affects users as well...

**Comment by zpytela** [comment]
I am sorry, this was really caused by a rule in selinux-policy, await a new build soon.

**Comment by zpytela** [comment]
The new build should be in testing soon:

https://bodhi.fedoraproject.org/updates/FEDORA-2022-87a0b7e8d0

**Comment by martinpitt** [comment]
New SELinux available and on its way to stable: https://bodhi.fedoraproject.org/updates/FEDORA-2022-87a0b7e8d0 Thanks @zpytela !

This is not the image we want :grin: , let's rebuild it.

**Pull request closed without merging**
