### PR TITLE
Introduce Fedora 32 image

### PR DESCRIPTION
**Pull request by marusak**
I built it locally and ran a few test to make sure the image is correct. But let bots build it themselves first.
 * [x] image-refresh fedora-32

TODO:
- [x] run `fedora-32@cockpit-project/cockpit`
- [x] Check that all copied naugthies applied
- [x] Add it into cockpit/cockpit README.md
- [ ] Enable automatic testing in cockpit
- [ ] Add into cockpit-podman

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-568-20200224-110202/

**Comment by cockpituous** [comment]
image-refresh fedora-32 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-32-20200224-115353

**Comment by marusak** [comment]
A LOT of failures. There need to be some skips in cockpit itself, so I'll send that one now.
Plus it seems like `test-policy` is behaving weirdly, needs to be looked at.

**Comment by marusak** [comment]
Also ton of:
```
audit: type=1400 audit(1582546912.933:276): avc:  denied  { setsched } for  pid=15078 comm="cockpit-ws" scontext=system_u:system_r:cockpit_ws_t:s0 tcontext=system_u:system_r:cockpit_ws_t:s0 tclass=process permissive=0
```
which seems like a new regression.

**Comment by marusak** [comment]
Test passed in https://github.com/cockpit-project/cockpit/pull/13603 thus ready for review

**Pull request merged**
