### PR TITLE
Image refresh for fedora-41

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-41
 * [x] image-refresh fedora-41

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-41 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-41-20241014-225715

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-41-9845515f-20241014-224139/log.html

**Comment by martinpitt** [comment]
This picked up the stratis regression https://github.com/stratis-storage/stratisd/issues/3699 , and the [bodhi update](https://bodhi.fedoraproject.org/updates/FEDORA-2024-f1152e9f57) wasn't stopped in time. So needs a naughtification now.

**Comment by martinpitt** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2024-09cee483a4 is now stuck because of the F41 freeze. So needs a naughty after all.

**Comment by martinpitt** [comment]
The sub-man tests were [green in the previous iteration](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6985-f4460298-20241015-044108-fedora-41-candlepin-subscription-manager-cockpit/log.html), and now fail because of a temporary internal npm mirror lag. We'll either just wait/retry or ignore this for the time being.

**Review by jelly — APPROVED** [review]

**Comment by martinpitt** [comment]
internal npm mirror seems to work again, retrying.

**Pull request merged**
