### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing
 * https://github.com/cockpit-project/cockpit/pull/17048
 * https://github.com/cockpit-project/cockpit/pull/17049

### CODE REVIEW

**Comment by martinpitt** [comment]
@marusak: As you recently looked into ABRT: There is a [failure](https://logs.cockpit-project.org/logs/pull-2993-20220224-025247-50c295d9-fedora-testing-cockpit-project-cockpit/log.html#253-2), it now [asks for an API key](https://logs.cockpit-project.org/logs/pull-2993-20220224-025247-50c295d9-fedora-testing-cockpit-project-cockpit/TestJournal-testAbrtReport-fedora-testing-127.0.0.2-2201-FAIL.png)? Does that ring a bell?

The [dnf-copr failure](https://logs.cockpit-project.org/logs/pull-2993-20220224-025251-50c295d9-fedora-testing-dnf-copr-cockpit-project-cockpit/log.html) is my fault, I'll look into that one.

**Comment by marusak** [comment]
> As you recently looked into ABRT: There is a [failure](https://logs.cockpit-project.org/logs/pull-2993-20220224-025247-50c295d9-fedora-testing-cockpit-project-cockpit/log.html#253-2), it now [asks for an API key](https://logs.cockpit-project.org/logs/pull-2993-20220224-025247-50c295d9-fedora-testing-cockpit-project-cockpit/TestJournal-testAbrtReport-fedora-testing-127.0.0.2-2201-FAIL.png)? Does that ring a bell?

I actually might know - https://github.com/abrt/libreport/commit/7c3c5d1ae1c39f0a3a3e9730bd25643a3f04fd50

We need to adjust tests for this. I'll take a look

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/17048 to fix the dnf-copr scenario, blocking on that.

**Comment by marusak** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/17049 to adjust our tests to the new libvirt version

**Comment by marusak** [comment]
All blockers were merged - did a clean rebase and re-running tests

**Review by marusak — APPROVED** [review]

**Pull request merged**
