### PR TITLE
Image refresh for fedora-36

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-36
 * [x] image-refresh fedora-36

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-36-20230113-230303.log

**Comment by martinpitt** [comment]
[These two RTL pixel failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4267-20230114-071624-a9aff9b9-fedora-36-cockpit-project-cockpit/log.html#86) look very broken, as if it undoes RTL. @KKoukiou does that ring a bell?

**Comment by marusak** [comment]
The pixel test is not related to this refresh, I saw this flake in other places as well

**Comment by martinpitt** [comment]
Indeed, [here is an example](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18198-20230118-080701-a2579535-fedora-36/log.html#188) with the current image. So, retry ahoi

**Comment by martinpitt** [comment]
I can locally reproduce the VM crash when trying to build the rpm inside the image. sub-man-cockpit has a very expensive build, as it calls webpack during rpmbuild. Even `virsh console` completely freezes for several minutes. Eventually:
```
[  200.507474] watchdog: BUG: soft lockup - CPU#0 stuck for 138s! [webpack:1227]
[  200.508575] Modules linked in: nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip_set nf_tables nfnetlink sunrpc vfat fat intel_rapl_msr intel_rapl_common kvm_intel kvm irqbypass rapl virtio_net net_failover joydev failover virtio_balloon i2c_piix4 cirrus ip6_tables ip_tables fuse zram crct10dif_pclmul crc32_pclmul crc32c_intel polyval_clmulni polyval_generic ghash_clmulni_intel serio_raw virtio_scsi ata_generic pata_acpi virtio_blk qemu_fw_cfg
[  200.515134] CPU: 0 PID: 1227 Comm: webpack Not tainted 6.0.15-200.fc36.x86_64 #1
[  200.516274] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.16.0-2.fc37 04/01/2014
[  200.517570] RIP: 0010:clear_page_erms+0x7/0x10
[  200.518400] Code: 48 89 47 18 48 89 47 20 48 89 47 28 48 89 47 30 48 89 47 38 48 8d 7f 40 75 d9 90 c3 cc cc cc cc 0f 1f 00 b9 00 10 00 00 31 c0 <f3> aa c3 cc cc cc cc cc cc 48 85 ff 0f 84 9c 00 00 00 45 31 c9 45
[  200.521019] RSP: 0000:ffffaf598193bc00 EFLAGS: 00010246
[  200.521963] RAX: 0000000000000000 RBX: ffffd1d281cd8000 RCX: 0000000000001000
[  200.523110] RDX: ffffd1d281cd8000 RSI: ffffd1d281cd8040 RDI: ffff9765f3600000
[  200.524200] RBP: 0000000000000040 R08: 0000000000001000 R09: 000000000007efdb
[  200.525293] R10: 0000000000000000 R11: 0000000000000881 R12: 0000000000000000
[  200.526380] R13: 0000000000140dca R14: 0000000000000000 R15: 0000000000000001
[  200.527456] FS:  00007f2bd1adcc00(0000) GS:ffff9765fdc00000(0000) knlGS:0000000000000000
[  200.528661] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  200.529555] CR2: 000011b95d648000 CR3: 0000000025dea005 CR4: 0000000000370ef0
[  200.530588] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  200.531732] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  200.532817] Call Trace:
[  200.533410]  <TASK>
[  200.533945]  post_alloc_hook+0xfe/0x160
[  200.534663]  get_page_from_freelist+0x81f/0x16c0
[  200.535453]  ? __refill_stock+0x1a/0x90
[  200.536157]  ? refill_stock+0x31/0x50
[  200.536848]  ? prepare_alloc_pages.constprop.0+0x190/0x1a0
[  200.537739]  __alloc_pages+0xe4/0x230
[  200.538437]  __folio_alloc+0x17/0x50
[  200.539087]  ? policy_node+0x51/0x70
[  200.539757]  vma_alloc_folio+0x88/0x320
[  200.540425]  __handle_mm_fault+0x8e7/0xe10
[  200.541118]  handle_mm_fault+0xae/0x290
[  200.541780]  do_user_addr_fault+0x1cd/0x690
[  200.542484]  ? kvm_read_and_reset_apf_flags+0x3f/0x60
[  200.543305]  exc_page_fault+0x70/0x170
[  200.543960]  asm_exc_page_fault+0x22/0x30
[  200.544615] RIP: 0033:0x7f2bce7581a4
[  200.545160] Code: 00 0f 1f 44 00 00 c5 fe 6f 4e 20 f7 c1 00 0e 00 00 75 68 49 89 c9 48 8d 4c 16 ff 48 83 ce 3f 4a 8d 7c 0e 01 48 29 f1 48 ff c6 <f3> a4 c4 c1 7e 7f 00 c4 c1 7e 7f 48 20 c5 f8 77 c3 66 66 2e 0f 1f
[  200.547356] RSP: 002b:00007ffe36a90078 EFLAGS: 00010212
[  200.548053] RAX: 000011b95d641128 RBX: 00007f2bd0a3b970 RCX: 0000000000027ec0
[  200.548992] RDX: 000000000002ed98 RSI: 000009780c308000 RDI: 000011b95d648000
[  200.549941] RBP: 00007ffe36a900c8 R08: 000011b95d641128 R09: 0000084151340000
[  200.550824] R10: 00007f2bd03f12b8 R11: 000000000002ed98 R12: 000011b95d640000
[  200.551843] R13: 00005579aff9b880 R14: 0000158ac1915c18 R15: 000011b95d641119
[  200.552821]  </TASK>
```
after that, the webpack build even resumes and finishes, and it starts dnf install, like in the [log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4267-20230118-085526-347f9903-fedora-36-candlepin-subscription-manager/log.html).  After that, it freezes again:

```
[  352.689815] watchdog: BUG: soft lockup - CPU#0 stuck for 61s! [dnf:1561]
[  352.690901] Modules linked in: tls nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip_set nf_tables nfnetlink sunrpc vfat fat intel_rapl_msr intel_rapl_common kvm_intel kvm irqbypass rapl virtio_net net_failover joydev failover virtio_balloon i2c_piix4 cirrus ip6_tables ip_tables fuse zram crct10dif_pclmul crc32_pclmul crc32c_intel polyval_clmulni polyval_generic ghash_clmulni_intel serio_raw virtio_scsi ata_generic pata_acpi virtio_blk qemu_fw_cfg
[  352.697949] CPU: 0 PID: 1561 Comm: dnf Tainted: G             L     6.0.15-200.fc36.x86_64 #1
[  352.699247] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.16.0-2.fc37 04/01/2014
[  352.700766] RIP: 0010:clear_page_erms+0x7/0x10
[  352.701741] Code: 48 89 47 18 48 89 47 20 48 89 47 28 48 89 47 30 48 89 47 38 48 8d 7f 40 75 d9 90 c3 cc cc cc cc 0f 1f 00 b9 00 10 00 00 31 c0 <f3> aa c3 cc cc cc cc cc cc 48 85 ff 0f 84 9c 00 00 00 45 31 c9 45
[  352.704620] RSP: 0000:ffffaf5981bcbc00 EFLAGS: 00010246
[  352.705630] RAX: 0000000000000000 RBX: ffffd1d281ef8000 RCX: 0000000000001000
[  352.706809] RDX: ffffd1d281ef8000 RSI: ffffd1d281ef8040 RDI: ffff9765fbe00000
[  352.707880] RBP: 0000000000000040 R08: 0000000000001000 R09: 000000000007efdb
[  352.708920] R10: 0000000000000000 R11: 0000000000000881 R12: 0000000000000000
[  352.709957] R13: 0000000000140dca R14: 0000000000000000 R15: 0000000000000001
[  352.711001] FS:  00007f4af0792740(0000) GS:ffff9765fdc00000(0000) knlGS:0000000000000000
[  352.712094] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  352.712996] CR2: 00007f4ad97a7000 CR3: 0000000005858003 CR4: 0000000000370ef0
[  352.714165] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  352.715437] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  352.716692] Call Trace:
[  352.717313]  <TASK>
[  352.717902]  post_alloc_hook+0xfe/0x160
[  352.718709]  get_page_from_freelist+0x81f/0x16c0
[  352.719597]  ? __refill_stock+0x1a/0x90
[  352.720393]  ? prepare_alloc_pages.constprop.0+0xf6/0x1a0
[  352.721372]  __alloc_pages+0xe4/0x230
[  352.722139]  __folio_alloc+0x17/0x50
[  352.722875]  ? policy_node+0x51/0x70
[  352.723591]  vma_alloc_folio+0x88/0x320
[  352.724306]  __handle_mm_fault+0x8e7/0xe10
[  352.725037]  handle_mm_fault+0xae/0x290
[  352.725697]  do_user_addr_fault+0x1cd/0x690
[  352.726394]  ? kvm_read_and_reset_apf_flags+0x3f/0x60
[  352.727169]  exc_page_fault+0x70/0x170
[  352.727848]  asm_exc_page_fault+0x22/0x30
[  352.728540] RIP: 0033:0x7f4af015820a
[  352.729193] Code: 00 01 00 00 00 74 99 83 f9 c0 0f 87 7b fe ff ff c5 fe 6f 4e 20 48 29 fe 48 83 c7 3f 49 8d 0c 10 48 83 e7 c0 48 01 fe 48 29 f9 <f3> a4 c4 c1 7e 7f 00 c4 c1 7e 7f 48 20 c5 f8 77 c3 0f 1f 44 00 00
[  352.731779] RSP: 002b:00007ffcd83f4598 EFLAGS: 00010202
[  352.732620] RAX: 00007f4ad97a45bc RBX: 000055973822d7c0 RCX: 000000000000103c
[  352.733735] RDX: 0000000000003a80 RSI: 00007f4ad979faf4 RDI: 00007f4ad97a7000
[  352.734916] RBP: 0000559733276a80 R08: 00007f4ad97a45bc R09: 0000000000000000
[  352.736066] R10: 0000000000000fff R11: fffffffffffff000 R12: 0000000000000ea0
[  352.737212] R13: 00000000ffff96e2 R14: 0000000000000035 R15: 0000000000000001
[  352.738317]  </TASK>
```
... and then does an orderly shutdown. A merge `./vm-run fedora-36` and running `dnf install -y cockpit-ws python3-devel openssl-devel intltool gcc` inside actually reproduces this, it kills ssh without leaving a trace on the console or in the journal.

Seems this kernel is rather broken. There are two newer kernels since that, let's re-do this and see if they perform any better.

**Pull request closed without merging**
