### PR TITLE
images: Install tcsh and tlog on RHEL/CentOS

### PR DESCRIPTION
**Pull request by martinpitt**
With these we can enable some Cockpit test cases.

 * [x] image-refresh rhel-9-0
 * [x] image-refresh rhel-8-6
 * [x] image-refresh centos-8-stream
 * [x] image-refresh rhel-8-5
 * [x] PR #2732
 * [x] https://github.com/cockpit-project/cockpit/pull/16741

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-2729-20211216-095757/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20211216-101313

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-2729-20211216-101313/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-2729-20211216-101313/

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20211216-103333

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-2729-20211216-103434/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-2729-20211216-103434/

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20211216-105454

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-2729-20211216-105454/

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20211216-112626

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-2729-20211216-113838/

**Comment by cockpituous** [comment]
image-refresh rhel-8-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-5-20211216-115959

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2729-20211216-115959/

**Comment by cockpituous** [comment]
image-refresh rhel-8-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-5-20211216-122222

**Comment by martinpitt** [comment]
The sudo kerberos fix made it into c8s and rhel8.6, thus [TestIPA.testClientCertAuthentication](https://logs.cockpit-project.org/logs/pull-2729-20211216-195029-fd3dfae8-centos-8-stream-cockpit-project-cockpit/log.html#261-2) now "fails" there. Needs a lockstep update.

**Comment by martinpitt** [comment]
PR #2732 will address the centos-8-stream@cockpit-project/cockpit/rhel-8.5 failure (should be landed first), and https://github.com/cockpit-project/cockpit/pull/16741 will address the c8s/rhel-8-6 failures of cockpit (needs to land in lockstep).

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
