### PR TITLE
Add python3-tracer to fedora

### PR DESCRIPTION
**Pull request by skobyda**
* [x] image-refresh fedora-33
 * [x] image-refresh fedora-32

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-1584-20210125-143131/

**Comment by cockpituous** [comment]
image-refresh fedora-33 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-33-20210125-142121

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-1584-20210125-142222/

**Comment by cockpituous** [comment]
image-refresh fedora-32 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-32-20210125-144848

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-1584-20210125-144949/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1584-20210125-144949/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-1584-20210125-153232/

**Comment by cockpituous** [comment]
image-refresh fedora-33 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-33-20210125-155454

**Comment by marusak** [comment]
Bummer, as I expected, the dbus-broker hit us here as well. A fix being introduced in https://github.com/cockpit-project/cockpit/pull/15218, setting to blocked for the time being.

**Comment by martinpitt** [comment]
packagekit fix landed, re-running.

**Review by marusak — APPROVED** [review]

**Pull request merged**
