### PR TITLE
images: Install tcsh on Debian images

### PR DESCRIPTION
**Pull request by martinpitt**
We need to test (and fix) logging in with tcsh, see
https://github.com/cockpit-project/cockpit/issues/14060

 * [x] image-refresh debian-stable
 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-stable
 * [x] image-refresh ubuntu-2004

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-1038-20200702-051414/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/bots/commits/image-refresh-debian-stable-20200702-052727

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-1038-20200702-052828/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/bots/commits/image-refresh-debian-testing-20200702-054343

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-1038-20200702-054343/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-stable-20200702-055959

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-1038-20200702-055959/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1038-20200702-055959/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-1038-20200702-063838/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2004 done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-2004-20200702-065757

**Comment by martinpitt** [comment]
[two failures](https://logs.cockpit-project.org/logs/pull-1038-20200702-072611-79b0b2ee-ubuntu-stable-cockpit-project-cockpit/log.html), retrying

**Pull request merged**
