### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-coreos-20231109-224747.log

**Comment by martinpitt** [comment]
This refresh switches FCOS to F39 and thus Python 3.11 → 3.12. Not sure yet what causes the incompatibility though.

**Comment by jelly** [comment]
Cockpit tests fail with the `cockpit-ws` container.
```
'/usr/lib/os-release' -> '/host/usr/lib/os-release'
/usr/libexec/cockpit-ws: /lib64/libc.so.6: version `GLIBC_2.38' not found (required by /usr/libexec/cockpit-ws)
```

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit/pull/19599 landed, triggering a new build.

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-coreos-20231113-124545.log

**Comment by martinpitt** [comment]
Same [TestSuperuserDashboard.test](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5527-20231113-125024-382777b3-fedora-coreos-expensive-cockpit-project-cockpit/log.html#63) flake that I'm also battling in https://github.com/cockpit-project/cockpit/pull/19602 . I'll take a look.

[This claim of a known issue](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5527-20231113-125030-382777b3-fedora-coreos-other-cockpit-project-cockpit/log.html#119) may also be relevant.

**Comment by martinpitt** [comment]
Ah, of course! naughty symlink needed to move to f39.

**Review by jelly — APPROVED** [review]

**Comment by jelly** [comment]
> Ah, of course! naughty symlink needed to move to f39.

Nice catch, now we both worked on it. So I approved it and I guess you also want to? :)

**Pull request merged**
