### PR TITLE
Fix fedora-37 image

### PR DESCRIPTION
**Pull request by martinpitt**
See https://github.com/cockpit-project/cockpit-machines/pull/802

 * [x] image-refresh fedora-37
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-3798-20220831-065050/

**Review by allisonkarlitskaya — APPROVED** [review]
:+1:

Thanks for the fixes!

**Comment by cockpituous** [comment]
image-refresh fedora-37 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-37-20220831-071152

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-3798-20220831-072121/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20220831-074649

**Comment by martinpitt** [comment]
Bah, this refresh causes [yet another SELinux regression](https://cockpit-logs.us-east-1.linodeobjects.com/pull-802-20220831-081753-1ef6e20d-fedora-37-bots-3798/log.html) :cry: . I'll sort this after #3801 then, and report it in the meantime.

**Review by allisonkarlitskaya — APPROVED** [review]

**Pull request merged**
