### PR TITLE
Image refresh for rhel-9-0

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-0
 * [x] image-refresh rhel-9-0

### CODE REVIEW

**Comment by mvollmer** [comment]
This looks like we need most of the fedora 35 fixes also for rhel 9 now.

**Comment by mvollmer** [comment]
There is something wrong with the permissions of `~admin/.ssh`.

**Comment by mvollmer** [comment]
> There is something wrong with the permissions of `~admin/.ssh`.

It is owned by root.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-2334-20210825-083737/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20210825-085252

**Comment by mvollmer** [comment]
In this run https://logs.cockpit-project.org/logs/pull-2334-20210825-090119-99db6d52-rhel-9-0-cockpit-project-cockpit/log.html

UDisks2 crashed during shutdown with this failed assertion:
```
udisksd[16809]: malloc_consolidate(): unaligned fastbin chunk detected
```
When this happened, systemd-coredump.socket had already been stopped, so we also got this message in the journal
```
Failed to connect to coredump service: Connection refused
```
which was found by check_journal_messages. *shrug*

**Comment by mvollmer** [comment]
> UDisks2 crashed during shutdown with this failed assertion:

I can't provoke this crash locally, hmm.

**Comment by martinpitt** [comment]
Closing in favor of #2350, which changes the image.

**Comment by mvollmer** [comment]
Oh, there were fixes here that we need to also put into #2350 then.

**Pull request closed without merging**
