### PR TITLE
Image refresh for rhel-8-2

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-2
 * [x] image-refresh rhel-8-2
 * [ ] adjust cockpit rhel-8-2-distropkg tests: https://github.com/cockpit-project/cockpit/pull/13463

### CODE REVIEW

**Comment by marusak** [comment]
The same coredump: https://209.132.184.41:8493/logs/pull-469-20200129-080909-424640f1-rhel-8-2-cockpit-project-cockpit/log.html#192-2

**Comment by martinpitt** [comment]
And now a lot of other rhel-8-2-distropkg tests fail, as they were still assuming cockpit 210. Nice to be able to clean up the special cases now! :-)

**Comment by martinpitt** [comment]
I investigated and reported the sssd crash (it's relatively harmless) and added a naughty pattern for it. cockpit/rhel-8-2-distropkg will still fail, I'm investigating that next.

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/13463 to adjust the cockpit tests

**Comment by martinpitt** [comment]
I pinged @atodorov about the [lorax alibaba failure](https://209.132.184.41:8493/logs/pull-469-20200129-142727-0d17dd9f-rhel-8-2-alibaba-weldr-lorax-rhel8-branch/log.html), apparently that test doesn't exist. So it seems safe to ignore that failure.

**Comment by martinpitt** [comment]
[rhel-8-2@weldr/lorax/rhel8-branch](https://209.132.184.41:8493/logs/pull-469-20200129-225555-0d17dd9f-rhel-8-2-weldr-lorax-rhel8-branch/log.html) keeps failing, retrying a few times.

**Comment by martinpitt** [comment]
@atodorov : rhel-8-2@weldr/lorax/rhel8-branch keeps failing in `test_ext4_filesystem()`, without an useful error message. Do you know what's wrong there?

**Comment by martinpitt** [comment]
@atodorov : I looked into the [logs tarball](https://209.132.184.41:8493/logs/pull-469-20200130-085151-0d17dd9f-rhel-8-2-weldr-lorax-rhel8-branch/tests/cli/test_compose_ext4-filesystem.sh/2ac8c677-3d17-4a3e-951c-5e3e5278e0c4-logs.tar), and the only error that I can find is in packaging.log:
```
04:05:20,063 INF packaging: Error downloading 'treeinfo': HTTPSConnectionPool(host='download.eng.bos.redhat.com', port=443): Max retries exceeded with url: /beakerrepos/client/RedHatEnterpriseLinux8//treeinfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),))
04:05:20,064 ERR packaging: Repo info download for https://download.eng.bos.redhat.com/beakerrepos/client/RedHatEnterpriseLinux8/ failed after 6 retries
```
but that doesn't seem to break the installation -- it does install packages after that.

**Comment by atodorov** [comment]
@martinpitt - the error you show is network/infrastructure issue, nothing I can do about it. This is apparently new b/c everything seemed to be working yesterday.

**Pull request merged**
