### PR TITLE
naughty: Add pattern for apparmor blocking VM installation when UEFI is set

### PR DESCRIPTION
**Pull request by KKoukiou**
Known issue: #2991
Downstream report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006324

### CODE REVIEW

**Comment by KKoukiou** [comment]
Tests are running here https://github.com/cockpit-project/cockpit-machines/pull/583

**Review by martinpitt — DISMISSED** [review]
Thanks! A bit sad to introduce a regression (from user's POV) that way, but let's hope it gets fixed soon.

**Comment by KKoukiou** [comment]
@martinpitt oh indeed, good catch. As you imagined, ubuntu-2004 fails with:

```error: unrecognized arguments: --reinstall``` I guess I need to block this PR on newer virt-install on ubuntu.

**Comment by martinpitt** [comment]
Thanks @KKoukiou : It's not *that* serious -- at least Debian does not have AppArmor installed by default (Ubuntu does), and I have some reasonably good connections to be able to pull some strings to fix that. AppArmor is also significantly easier to fix than SELinux, I am happy to give it a shot even.

However, `--reinstall` not supported in 20.04 LTS is more serious. In two months 22.04 LTS gets released, and then I'll stop backports to 20.04 LTS. As this is a really cool simplification, I'm also happy to stop backporting now already (it doesn't make much of a difference really).

**Comment by KKoukiou** [comment]
> It's also worth filing that bug on https://bugs.launchpad.net/ubuntu/+source/apparmor -- if you have time to do that, I'd appreciate; otherwise I'll do it soon.

https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1962035

**Review by martinpitt — APPROVED** [review]

**Comment by martinpitt** [comment]
@KKoukiou : I sent a fix to https://gitlab.com/libvirt/libvirt/-/merge_requests/140 in case you want to try this (it's easy enough to patch in a running system)

**Comment by KKoukiou** [comment]
> @KKoukiou : I sent a fix to https://gitlab.com/libvirt/libvirt/-/merge_requests/140 in case you want to try this (it's easy enough to patch in a running system)

Sure, I can test this gladly.

**Comment by martinpitt** [comment]
Rebased to run against current images in https://github.com/cockpit-project/cockpit-machines/pull/583

**Comment by martinpitt** [comment]
See https://github.com/cockpit-project/cockpit-machines/pull/583#issuecomment-1060235455 , the previous pattern does not match. Updated to match on the AppArmor message instead.

**Comment by martinpitt** [comment]
Let's land it now -- we are now needing this for debian-testing in PR #3108 anyway, even without the `--reinstall` rewrite in https://github.com/cockpit-project/cockpit-machines/pull/583

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
