### PR TITLE
testmap: add rhel-9-5 to cockpit-composer and drop rhel-8

### PR DESCRIPTION
**Pull request by croissanne**
- [x] https://github.com/osbuild/cockpit-composer/pull/2029

### CODE REVIEW

**Comment by croissanne** [comment]
> Thanks! I triggered the new contexts.

It'll need https://github.com/osbuild/cockpit-composer/pull/2029 to work.

**Comment by martinpitt** [comment]
@croissanne ah, I see -- setting to "blocked" then. Indeed the [f-40 run](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6716-ec4d8995-20240809-082512-fedora-40-firefox-osbuild-cockpit-composer/log.html) has a failure (but test is still running), let's sort that out in the composer PR first.

**Comment by croissanne** [comment]
@martinpitt osbuild/cockpit-composer#2029 is merged now, so should be good.

**Comment by martinpitt** [comment]
@croissanne Can you please rebase (to clear the test results, and avoid counting as flakes) and re-trigger the new tests?

**Review by martinpitt — APPROVED** [review]
Rebased and triggered. If this goes green, please land. Thanks!

**Pull request merged**
