### PR TITLE
Image refresh for fedora-38

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-38
 * [x] image-refresh fedora-38

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-38-20230817-230404.log

**Comment by jelly** [comment]
We previously already applied the pixel test changes when this test failed but now that it appears again but different we should not do the same. Maybe we can ignore the size changes? Or make the selector more specific?

https://cockpit-logs.us-east-1.linodeobjects.com/pull-5126-20230818-153419-9bd85a38-fedora-38-networking-cockpit-project-cockpit/pixeldiff.html#TestNetworkingBasic-testBasic-network-interface-mobile

**Comment by martinpitt** [comment]
Once again a [dialog width change](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5126-20230822-111727-9bd85a38-fedora-38-networking-cockpit-project-cockpit/pixeldiff.html#TestNetworkingBasic-testBasic-network-interface-mobile) due to shuffling IPv6 addresses. Let's see if this is stable.

**Comment by martinpitt** [comment]
It got fixed in https://github.com/cockpit-project/cockpit/pull/19219

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
