### PR TITLE
Image refresh for rhel-9-2

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-2
 * [x] image-refresh rhel-9-2
 * #4224
 * https://github.com/cockpit-project/cockpit/pull/18108

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-2-20230102-062525.log

**Comment by martinpitt** [comment]
The [SELinux](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4226-20230102-062659-89275c99-rhel-9-2-cockpit-project-cockpit/log.html#137-2) failure here is the same as in RHEL 8.8 in #4178 -- it seems insights-client modifies the local SELinux policy, which is awkward.

**Comment by martinpitt** [comment]
The two storage resize failures are a regression, I reported it at https://bugzilla.redhat.com/show_bug.cgi?id=2157591 and tracked in https://bugzilla.redhat.com/show_bug.cgi?id=2157591 . Will add naughties.

**Comment by martinpitt** [comment]
And finally, the new [SELinux messsage](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4226-20230102-062659-89275c99-rhel-9-2-cockpit-project-cockpit/log.html#307) in check-system-shutdown-restart. Curiously, I get *exactly* the same PID and inode number locally, this seems very reliable :grin:  This is https://bugzilla.redhat.com/show_bug.cgi?id=2156068 aka https://github.com/cockpit-project/bots/issues/4229

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
