### PR TITLE
Image refresh for fedora-40

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-40
 * [x] image-refresh fedora-40

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-40 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-40-20240410-225240

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-40-a36e735a-20240410-223741/log.html

**Comment by martinpitt** [comment]
[FIPS regressions](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6199-f70600f2-20240410-225407-fedora-40-other-cockpit-project-cockpit/log.html) need reporting/naughty treatment.

**Comment by martinpitt** [comment]
Reported as https://bugzilla.redhat.com/show_bug.cgi?id=2274527 . Will create the naughty later, gotta run now.

**Review by jelly — APPROVED** [review]

**Review by mvollmer — APPROVED** [review]
thansk! The gnutls thing has happened before...

**Comment by martinpitt** [comment]
@mvollmer yeah, *three times* alone in F40..

**Pull request merged**
