### PR TITLE
images: Build centos-7 image from official qcow image

### PR DESCRIPTION
**Pull request by martinpitt**
Starting from the cloud image is faster, more robust, and more realistic
(using an official product) than our own virt-install bootstrap.

CentOS 7 offers xz-compressed qcow images (254 MB xz vs. 819 MB
uncompressed, so well worth it). Download these and teach
cloudimage.bootstrap to handle these as well.

 * [x] image-refresh centos-7
 * [x] fix cockpit rhel-7.9 branch for current bots: https://github.com/cockpit-project/cockpit/pull/15675

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-1913-20210411-090000/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-7-20210411-092727

**Comment by martinpitt** [comment]
@marusak: [oh-uh!](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-1913-20210411-110529-25cb426f-centos-7-cockpit-project-cockpit-rhel-7.9/log.html#42-2) Looks like the rhel-7.9 branch needs some backport for the dropped `atomic_image`?

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/15675 to fix the rhel-7.9 branch, blocking on that.

**Comment by marusak** [comment]
cockpit-project/cockpit#15675 landed, retrying

**Comment by martinpitt** [comment]
Bah, still [too many failures](https://logs.cockpit-project.org/logs/pull-1913-20210412-072330-25cb426f-centos-7-cockpit-project-cockpit-rhel-7.9/log.html). I don't care enough about this.

**Pull request closed without merging**
