### PR TITLE
images: Depend on /usr/bin/kdumpctl instead of kexec-tools

### PR DESCRIPTION
**Pull request by martinpitt**
In recent Fedora and RHEL 10, `kdumpctl` moved from the kexec-tools to the kdump-utils package [1]. We already adjusted cockpit's dependency accordingly [2]. Follow suit in our image build scripts.

kdump-utils is already installed on our Fedora packages, so that's no effective change right now. But this will fix future centos-10 builds.

[1] https://issues.redhat.com/browse/RHEL-35567
[2] https://github.com/cockpit-project/cockpit/commit/4d7fcbfeb

---

Note that I won't refresh c10 here, it's being fixed in #6378.

 * [x] image-refresh rhel-9-5
 * [x] image-refresh fedora-39

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-9-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-5-20240521-102223

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-5-1ccc9f2e-20240521-100703/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-1ccc9f2e-20240521-102232/log.html

**Comment by martinpitt** [comment]
Ah, rawhide is also busted, see #6393. I'll refresh f-39 instead.

**Comment by cockpituous** [comment]
image-refresh fedora-39 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-39-20240521-115942

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-39-1ccc9f2e-20240521-112402/log.html

**Review by jelly — APPROVED** [review]

**Pull request merged**
