### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos
 * [ ] https://github.com/cockpit-project/cockpit-ostree/pull/366

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-coreos-20230526-224848.log

**Comment by martinpitt** [comment]
Hmm, that updated cockpit to 292, but it does not seem to have the PF5 shell yet? Apparently we landed that after the release, and I goofed up the version check.

**Comment by martinpitt** [comment]
Yup!
```
❱❱❱ git describe 14174cf6f6c1a44f17ffcd5b55cafac745c30f50
292-12-g14174cf6f
```

I sent https://github.com/cockpit-project/cockpit-ostree/pull/366 to fix that, and triggered a run against this image here.

**Review by KKoukiou — APPROVED** [review]
Tests passed in ostree repo

**Pull request merged**
