### PR TITLE
images: Reduce libvirt dependencies on Fedora images

### PR DESCRIPTION
**Pull request by martinpitt**
cockpit-machines recently reduced its dependency footprint [1], in
particular to get rid of the very heavy libvirt-daemon-kvm and qemu-kvm
dependencies.

Adjust the Fedora image packages accordingly. This makes sure that the
c-machines dependencies are sufficient, and also reduces the image size
a bit.

[1] https://github.com/cockpit-project/cockpit-machines/pull/622

 * [x] image-refresh fedora-35
 * [x] image-refresh fedora-36
 * https://github.com/cockpit-project/cockpit-machines/pull/666
 * https://github.com/cockpit-project/cockpit-podman/pull/956

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3227-20220411-075252/

**Comment by cockpituous** [comment]
image-refresh fedora-35 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-35-20220411-081212

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3227-20220411-081212/

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20220411-082929

**Comment by martinpitt** [comment]
[fedora-35 machines failure](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-3227-20220411-084741-f407af41-fedora-35-cockpit-project-cockpit-machines/log.html#1-2), apparently `virtstoraged.socket` does not run automatically. That is a packaging bug.

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3227-20220411-161111/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-3227-20220411-162828/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-3227-20220411-164141/

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20220411-170505

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3227-20220411-172222/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-3227-20220411-205555/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3227-20220411-205555/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-3227-20220411-205555/

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20220411-212424

**Review by skobyda — APPROVED** [review]

**Pull request merged**
