### PR TITLE
Fix debian-testing image refresh, and a race condition

### LINKED ISSUE #755: Image refresh for debian-testing
Image refresh for debian-testing
 * [ ] image-refresh debian-testing

### PR DESCRIPTION
**Pull request by martinpitt**
Fixes #755 

 * [x] image-refresh debian-testing
 * [x] image-refresh debian-stable
 * [x] image-refresh ubuntu-2004
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-757-20200416-074141/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/bots/commits/image-refresh-debian-testing-20200416-081818

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-757-20200416-082424/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/bots/commits/image-refresh-debian-stable-20200416-084242

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-757-20200416-084242/

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit/pull/13910 drops the purging of chronyd. Curiously it turns out it doesn't break [the test](https://logs.cockpit-project.org/logs/pull-757-20200416-082215-4b9d087c-debian-testing-cockpit-project-cockpit/log.html):
```
dpkg: warning: ignoring request to remove chrony, only the config
 files of which are on the system; use --purge to remove them too
```
But it was good to clean up the special case anyway.

**Comment by cockpituous** [comment]
image-refresh ubuntu-2004 done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-2004-20200416-090101

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-757-20200416-090202/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-stable-20200416-092121

**Pull request merged**
