### PR TITLE
images: install split udisks2 btrfs, lvm2 plugins

### PR DESCRIPTION
**Pull request by jelly**
Following Fedora and Debian Arch now also split up udisk2 plugins into separate packages.

 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-20240301-081534-dca1597f-image-refresh-arch/log.html

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240301-160130

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-20240301-104500-dca1597f-image-refresh-arch/log.html

**Comment by jelly** [comment]
libblockdev-mdadm does not depend on `mdadm`. Reported to the packager and should be fixed. Let's re-refresh.

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240304-084422

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-20240304-082940-dca1597f-image-refresh-arch/log.html

**Review by martinpitt — APPROVED** [review]
:star2:

**Pull request merged**
