### PR TITLE
images: Disable cron and kdump on services image

### PR DESCRIPTION
**Pull request by martinpitt**
They both start at boot, and kdump.service rebuilds the initrd (which
takes 45s). This may help with some timeouts that we see in
check-realms.

 * [x] image-refresh services

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-827-20200504-072727/

**Comment by martinpitt** [comment]
This is a stab into the dark. It may not actually help much with the check-realms flakes investigated in https://github.com/cockpit-project/cockpit/pull/14009 , but it's a nice optimization either way.

**Comment by cockpituous** [comment]
image-refresh services done: https://github.com/cockpituous/bots/commits/image-refresh-services-20200504-081010

**Comment by martinpitt** [comment]
This doesn't help much with the test instability, but it still reduces what the test has to do, so I think we should land this anyway. But I'll keep digging.

**Pull request merged**
