### PR TITLE
images: Hack around systemd-dev alternate build dependency in Debian/Ubuntu

### LINKED ISSUE #5323: Image refresh for debian-stable
Image refresh for debian-stable
 * [ ] Fix pbuilder build dep installation in #5349
 * [ ] FAIL: image-refresh debian-stable

### LINKED ISSUE #5325: Image refresh for ubuntu-stable
Image refresh for ubuntu-stable
 * [ ] Fix pbuilder build dep installation in #5349
 * [ ] FAIL: image-refresh ubuntu-stable

### LINKED ISSUE #5349: Image refresh for ubuntu-2204
Image refresh for ubuntu-2204
 * [ ] FAIL: image-refresh ubuntu-2204

### PR DESCRIPTION
**Pull request by martinpitt**
https://github.com/cockpit-project/cockpit/pull/19407 introduced an
alternate "systemd-dev | old version of systemd" build dependency. But
our static `pbuilder-satisfydepends-classic` parsing cannot resolve
that, and will try to install systemd-dev on debian-stable and our
current ubuntu-* images, which don't have it yet. Replace it with the
full "systemd" package on the old images. This is hackish, but will go
away over time.

Fixes #5323
Fixes #5325
Fixes #5349

 * [x] image-refresh debian-stable
 * [x] image-refresh ubuntu-2204
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20231006-064728

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-stable-20231006-064747.log

**Comment by cockpituous** [comment]
image-refresh ubuntu-2204 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2204-20231006-070743

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/ubuntu-2204-20231006-070707.log

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20231006-072812

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/ubuntu-stable-20231006-072828.log

**Review by allisonkarlitskaya — APPROVED** [review]

**Pull request merged**
