### PR TITLE
images: Change rhel-8-3 from nightly to released

### PR DESCRIPTION
**Pull request by mvollmer**
There isn't any useable rhel-8-3 in nightly anymore: "latest-RHEL-8.3"
has disappeared, and "latest-RHEL-8.3.0" is from October 2020 with
status DOOMED.

 * [x] image-refresh rhel-8-3

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-1749-20210305-084444/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1749-20210305-084444/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-1749-20210305-084747/

**Comment by cockpituous** [comment]
image-refresh rhel-8-3 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-3-20210305-090707

**Review by martinpitt — APPROVED** [review]
Danke lieber Herr Pilot! :man_pilot:

**Pull request merged**
