### PR TITLE
README.md: Fix paragraph formatting

### PR DESCRIPTION
**Pull request by martinpitt**
This is just a vehicle to test the new tasks container from https://github.com/cockpit-project/cockpituous/pull/330

 * [x] image-refresh cirros

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-952-20200605-093232/

**Comment by cockpituous** [comment]
image-refresh cirros done: https://github.com/cockpituous/bots/commits/image-refresh-cirros-20200605-093232

**Comment by martinpitt** [comment]
One more round, as I refreshed the container again.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-952-20200605-095858/

**Comment by cockpituous** [comment]
image-refresh cirros done: https://github.com/cockpituous/bots/commits/image-refresh-cirros-20200605-095858

**Comment by martinpitt** [comment]
Tests and image rebuilds are fine (the firefox failures are unrelated, and being worked on), so this has done its purpose.

**Pull request closed without merging**
