### PR TITLE
images: Disable SSH PerSourcePenalties on arch

### PR DESCRIPTION
**Pull request by mvollmer**
The PerSourcePenalties option is new with OpenSSH 3.9. It's default value will cause sshd to drop connections after a number of quick failed login attempts. Our TestMultiMachineAdd.testBasic test runs into that currently. More tests might be affected in random ways in the future.

 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240730-072745

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-98f23afa-20240730-071533/log.html

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240730-073115

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-98f23afa-20240730-072000/log.html

**Review by martinpitt — APPROVED** [review]
Cheers! Bye-bye to a 70% flake

**Pull request merged**
