### PR TITLE
images: add C.UTF-8 locale to arch image

### PR DESCRIPTION
**Pull request by jelly**
Since glibc 2.53 C.UTF-8 is finally supported by glibc upstream, other
distributions such as Fedora/Debian patched in C.UTF-8. C.UTF-8 is
required for our tests to get rid of `setlocale: C.UTF-8 not found`
errors in cockpit-machines.

@martinpitt do we want to refresh again, as the Arch Image was also refreshed today already. I tested this locally and it fixes:
```
test/check-machines-consoles:    @skipImage('TODO: setlocale: No such file or directory', "arch")
```

 * [x] image-refresh arch

### CODE REVIEW

**Comment by martinpitt** [comment]
Normally I prefer such changes to be in test/vm.install. But I suppose at least the unexpected message would affect all our projects. So yes, let's rebuild the image with this and test everything. Cheers!

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3166-20220331-053434/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3166-20220331-053434/

**Comment by martinpitt** [comment]
Hmm, so even the 3x retry with curl didn't help.. Need to wait a bit until Linode comes back.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3166-20220331-073434/

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20220331-074747

**Comment by martinpitt** [comment]
@jelly : Oh, it already picked up cockpit 266, and we changed base-2 to base-10. Indeed we need to adjust cockpit-machines tests to deal with that (using `self.machine.system_before(266)`)

**Comment by jelly** [comment]
> @jelly : Oh, it already picked up cockpit 266, and we changed base-2 to base-10. Indeed we need to adjust cockpit-machines tests to deal with that (using `self.machine.system_before(266)`)

PR triggered here https://logs.cockpit-project.org/logs/pull-648-20220331-164708-d4406a4a-arch-bots-3166/log.html

**Comment by jelly** [comment]
Triggered https://logs.cockpit-project.org/logs/pull-649-20220331-164921-fbc9618c-arch-bots-3166/log.html which enables the previously failing C.UTF-8 test.

**Review by martinpitt — APPROVED** [review]
Cheers!

**Pull request merged**
