### PR TITLE
images: Move fedora-testing  to Fedora 32

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-1030-20200630-195353/

**Comment by martinpitt** [comment]
I went through cockpit's test special cases, and it seems master should already work with this.

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-testing-20200630-202121

**Comment by martinpitt** [comment]
There's something [wrong with ABRT](https://logs.cockpit-project.org/logs/pull-1030-20200701-055444-0331ee8a-fedora-testing-cockpit-project-cockpit/log.html)

**Comment by martinpitt** [comment]
Ah, so it's:

    .cockpit-logline .cockpit-log-message:contains('(sleep) crashed in') is ambiguous

I can't actually reproduce that locally, even after several runs. But indeed it makes sense -- this page shows the whole log, so we should just take the first child. The [journal](https://logs.cockpit-project.org/logs/pull-1030-20200701-055444-0331ee8a-fedora-testing-cockpit-project-cockpit/TestJournal-testAbrtSegv-fedora-testing-127.0.0.2-2201-FAIL.log.gz) shows two entries:
```
Jul 01 02:04:33 localhost.localdomain abrt-notification[21554]: Process 21474 (sleep) crashed in pause()
Jul 01 02:56:17 localhost.localdomain abrt-notification[349843]: Process 349679 (sleep) crashed in clock_nanosleep@@GLIBC_2.17()
```
We probably got that when we dropped the matching for the nanosleep function.

So I'll retry, but let's fix this.

**Comment by martinpitt** [comment]
Now it's just the known testConfigureBeforeInstall() failure. The ABRT flakes are (hopefully) fixed by https://github.com/cockpit-project/cockpit/pull/14298 , but this is ready to land now.

**Pull request merged**
