### PR TITLE
Image refresh for fedora-32

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-32
 * [x] image-refresh fedora-32

### CODE REVIEW

**Comment by marusak** [comment]
[libvirtd](https://logs.cockpit-project.org/logs/pull-786-20200424-045145-ffed10f6-fedora-32-cockpit-project-cockpit/log.html#94-2) is dumping core and [podman](https://logs.cockpit-project.org/logs/pull-786-20200424-045145-ffed10f6-fedora-32-cockpit-project-cockpit-podman/log.html) also is not happiest.

**Comment by martinpitt** [comment]
[This failure](https://logs.cockpit-project.org/logs/pull-786-20200427-102838-5e81431c-fedora-32-cockpit-project-cockpit/log.html#90-2) may also be related?

    Failed to generate stack trace: (null)

**Comment by marusak** [comment]
> This failure may also be related?

hmm, possibly. I'll check it out if I can reproduce it.

**Comment by marusak** [comment]
Cannot reproduce. Also message `Failed to generate stack trace: (null)` does not really provide any useful information, so we may just ignore it in general. (It says that something coredumped, but we really don't know what and we might already have naughty for it)

Retrying tests and I'll send PR to ignore this message in the future.

**Pull request merged**
