### PR TITLE
images: Add "stratis" packageset to Fedoras and RHELs

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh fedora-37
 * [x] image-refresh rhel-9-3
 * [x] https://github.com/cockpit-project/cockpit/pull/18635

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-37 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-37-20230412-115746

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-37-20230412-115757.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-2-20230412-120808.log

**Comment by martinpitt** [comment]
@mvollmer : Sorry, I accidentally killed your f37 rebuild here. I thought it was a duplicate, the kind that our automatic refreshes produce so often.

**Comment by martinpitt** [comment]
But the actual image is still present: https://cockpit-images.us-east-1.linodeobjects.com/fedora-37-893da5db8db7553cbcd03cd316ea45a4a434f29d65dce901423ac6dabb9f655e.qcow2

I.e. you can still update the symlink manually to that SHA, we just lost that auto-generated commit.

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-37-20230413-122222.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-2-20230413-122929.log

**Comment by mvollmer** [comment]
There is something wrong with rhel-9-2:

```
DEBUG: No matches found for the following disable plugin patterns: local, spacewalk
DEBUG: Last metadata expiration check: 0:00:27 ago on Thu Apr 13 08:29:24 2023.
DEBUG: Package make-1:4.3-7.el9.x86_64 is already installed.
DEBUG: Package sed-4.8-9.el9.x86_64 is already installed.
DEBUG: Error: 
DEBUG:  Problem 1: package glib-networking-2.68.3-3.el9.x86_64 requires gsettings-desktop-schemas, but none of the providers can be installed
DEBUG:   - conflicting requests
DEBUG:   - nothing provides font(sourcecodepro) needed by gsettings-desktop-schemas-40.0-6.el9.x86_64
DEBUG:  Problem 2: package libsoup-2.72.0-8.el9.x86_64 requires glib-networking(x86-64) >= 2.58.0, but none of the providers can be installed
DEBUG:   - package libappstream-glib-0.7.18-4.el9.x86_64 requires libsoup(x86-64) >= 2.51.92, but none of the providers can be installed
DEBUG:   - package libappstream-glib-0.7.18-4.el9.x86_64 requires libsoup-2.4.so.1()(64bit), but none of the providers can be installed
DEBUG:   - package glib-networking-2.68.3-3.el9.x86_64 requires gsettings-desktop-schemas, but none of the providers can be installed
DEBUG:   - conflicting requests
DEBUG:   - nothing provides font(sourcecodepro) needed by gsettings-desktop-schemas-40.0-6.el9.x86_64
DEBUG:  Problem 3: package libappstream-glib-0.7.18-4.el9.x86_64 requires libsoup(x86-64) >= 2.51.92, but none of the providers can be installed
DEBUG:   - package libappstream-glib-0.7.18-4.el9.x86_64 requires libsoup-2.4.so.1()(64bit), but none of the providers can be installed
DEBUG:   - package libsoup-2.72.0-8.el9.x86_64 requires glib-networking(x86-64) >= 2.58.0, but none of the providers can be installed
DEBUG:   - package rpmlint-1.11-19.el9.noarch requires /usr/bin/appstream-util, but none of the providers can be installed
DEBUG:   - package glib-networking-2.68.3-3.el9.x86_64 requires gsettings-desktop-schemas, but none of the providers can be installed
DEBUG:   - conflicting requests
DEBUG:   - nothing provides font(sourcecodepro) needed by gsettings-desktop-schemas-40.0-6.el9.x86_64
DEBUG: (try to add '--skip-broken' to skip uninstallable packages)
DEBUG: Child return code was: 1
```

**Comment by cockpituous** [comment]
image-refresh rhel-9-3 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-3-20230413-132802

**Comment by martinpitt** [comment]
Indeed that seems to be some broken RHEL 9.2 compose. It's reproducible on the current rhel-9-2 image with:
```
su - builder
mock --clean
mock -i glib-networking glib2-devel libappstream-glib
```
It could be because RHEL 9.2 is being released, and nightly somehow doesn't fit the build root any more?

I filed https://issues.redhat.com/browse/RHELBLD-12664 for this.

**Comment by martinpitt** [comment]
FTR: The RHEL 9.2 broken build root was fixed, and PR #4646 proves it :+1: 

I want to fix the `mock` package on the RHEL images, and there is another blocked RHEL update in #4645, so let's untangle and land this ASAP. I took the liberty to push the image refreshes here, and I'll land if they don't regress.

**Comment by martinpitt** [comment]
[pixel failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4639-20230414-044729-f102a7ac-fedora-37-cockpit-project-cockpit/log.html#70), which looks like the reversal of https://github.com/cockpit-project/cockpit/pull/18618 . Re-trying once to compare, if it's stable, I'll revert it.

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/18635 to address that pesky pixel failure.

**Comment by martinpitt** [comment]
Unblocked. The test ran in https://github.com/cockpit-project/cockpit/pull/18635 against this new image.

**Pull request merged**
