### PR TITLE
testmap: Move cockpit-machines from fedora-36 to fedora-38

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by jelly** [comment]
```
error: internal error: process exited while connecting to monitor: audio: Unknown audio driver `spice'
```

@skobyda do you have more information about this error? I compared the packages between F37 / F38 and don't see anything special.

It does seem qemu was updated from 7.0.0 to 7.2.0 and spice-server-0.15.1-2.fc38.x86_64 (minor bump from -1)

**Comment by KKoukiou** [comment]
> Unknown audio driver `spice'

Looks like qemu-audio-spice package is missing.

**Comment by jelly** [comment]
> 



> > Unknown audio driver `spice'
> 
> Looks like qemu-audio-spice package is missing.

our fedora test VM has no `qemu-audio-spice` package installed it seems more that this is somehow now also enabled when setting `spice`.

**Comment by jelly** [comment]
```
virt-install --connect qemu:///system --name subVmTest1 --os-variant cirros0.4.0 --boot hd,network --vcpus 1 --memory 128 --import -
-disk /var/lib/libvirt/images/subVmTest1-2.img --graphics spice,listen=127.0.0.1 --console file,target.type=serial,source.path=/var/log/libvirt/console-subVmTest1.log --pri
nt-step 1 > /tmp/xml-system
```

```xml
<domain type="qemu">
  <name>subVmTest1</name>
  <uuid>90f8a57b-88e9-4244-b327-6570a84a3b8f</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://cirros-cloud.net/cirros/0.4.0"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory>131072</memory>
  <currentMemory>131072</currentMemory>
  <vcpu>1</vcpu>
  <os>
    <type arch="x86_64" machine="pc-i440fx-7.2">hvm</type>
    <boot dev="hd"/>
    <boot dev="network"/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <vmport state="off"/>
  </features>
  <clock offset="utc">
    <timer name="rtc" tickpolicy="catchup"/>
    <timer name="pit" tickpolicy="delay"/>
    <timer name="hpet" present="no"/>
  </clock>
  <pm>
    <suspend-to-mem enabled="no"/>
    <suspend-to-disk enabled="no"/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2"/>
      <source file="/var/lib/libvirt/images/subVmTest1-2.img"/>
      <target dev="vda" bus="virtio"/>
    </disk>
    <controller type="usb" model="ich9-ehci1"/>
    <controller type="usb" model="ich9-uhci1">
      <master startport="0"/>
    </controller>
    <controller type="usb" model="ich9-uhci2">
      <master startport="2"/>
    </controller>
    <controller type="usb" model="ich9-uhci3">
      <master startport="4"/>
    </controller>
    <interface type="network">
      <source network="default"/>
      <mac address="52:54:00:e7:dd:ef"/>
      <model type="virtio"/>
    </interface>
    <console type="file">
      <source path="/var/log/libvirt/console-subVmTest1.log"/>
      <target type="serial"/>
    </console>
    <channel type="unix">
      <source mode="bind"/>
      <target type="virtio" name="org.qemu.guest_agent.0"/>
    </channel>
    <channel type="spicevmc">
      <target type="virtio" name="com.redhat.spice.0"/>
    </channel>
    <input type="tablet" bus="usb"/>
    <graphics type="spice" port="-1" tlsPort="-1" autoport="yes" listen="127.0.0.1">
      <image compression="off"/>
    </graphics>
    <sound model="ich6"/>
    <video>
      <model type="vga"/>
    </video>
    <redirdev bus="usb" type="spicevmc"/>
    <redirdev bus="usb" type="spicevmc"/>
    <memballoon model="virtio"/>
    <rng model="virtio">
      <backend model="random">/dev/urandom</backend>
    </rng>
  </devices>
</domain>

```

**Comment by skobyda** [comment]
As discussed in IRC, the bug is probably here: https://gitlab.com/libvirt/libvirt/-/blob/master/src/qemu/qemu_domain.c#L3887
Where libvirt assings the audio the same backend as the graphics (this fails the test where we test for spice graphics)

**Comment by jelly** [comment]
Added naughty, let's retry!

**Comment by martinpitt** [comment]
> audit: type=1400 audit(1676482850.464:5845): avc:  denied  { name_bind } for  pid=23694 comm="rpcbind" src=61068 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0

That's good old issue #118 , naughty needs copying.

**Comment by mvollmer** [comment]
Alright, let's have a naughty for https://bugzilla.redhat.com/show_bug.cgi?id=2170110 for the time being and give them a chance to fix it.  But if that fails, we need to put a workaround into c-machines before fedora-38 ships, I am afraid.

**Review by mvollmer — APPROVED** [review]

**Comment by martinpitt** [comment]
Ack, I added it to my todo list, thanks!

**Pull request merged**
