### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch
 * [x] https://github.com/cockpit-project/cockpit/pull/19799
 * [x] Backport fix for https://gitlab.com/libssh/libssh-mirror/-/issues/227 into Arch: https://gitlab.archlinux.org/archlinux/packaging/packages/libssh/-/issues/1 - naughtied

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20231221-224848.log

**Comment by martinpitt** [comment]
Oh uh, that smells like libssh 0.10.5 → 0.10.6 broke something thoroughly. We see a related failure in rawhide now, where unit tests fail.

**Comment by martinpitt** [comment]
It's the openssh 0.9.6 update, which is fixed in https://github.com/allisonkarlitskaya/ferny/pull/25 and pulled into cockpit in https://github.com/cockpit-project/cockpit/pull/19799 . Blocking on that.

Plus, arch doesn't have the libssh regression fix. I don't have an account on https://gitlab.archlinux.org/archlinux/packaging/ , I asked for one.

**Comment by martinpitt** [comment]
Pushing a rebase to ensure that nothing else than the libssh IPv6 regression fails now.

**Comment by martinpitt** [comment]
Yup, [as expected](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5697-20240103-081241-cc9cac26-arch-other-cockpit-project-cockpit/log.html#93-2) - let's handle this via a naughty.

**Review by allisonkarlitskaya — APPROVED** [review]
Commits are in the wrong order, but close enough.

Maybe squash on merge?

**Comment by martinpitt** [comment]
Hmm, that's how we usually push them.

**Pull request merged**
