### PR TITLE
images: Fix debian-testing

### LINKED ISSUE #6460: Image refresh for debian-testing
Image refresh for debian-testing
 * [x] Do this again once [cockpit goes back to testing](https://tracker.debian.org/pkg/cockpit)
 * [x] Install pcp from unstable unless it goes back to testing quickly; but needs the same in pbuilder, which is more difficult
 * [ ] FAIL: image-refresh debian-testing

### PR DESCRIPTION
**Pull request by martinpitt**
pcp has fallen out of unstable, and due to slow maintenance it will take some time to get back. We also need to do that in the pbuilder.

Fixes #6460

 * [x] image-refresh debian-testing
 * [x] https://github.com/cockpit-project/cockpit/pull/20579
 * [x] Revert the expected PAM message here, the above PR includes it
 * [x] https://github.com/cockpit-project/cockpit-files/pull/560
 * [x] https://github.com/cockpit-project/cockpit-podman/pull/1759
 * [x] https://github.com/cockpit-project/cockpit-machines/pull/1685
 * [x] https://github.com/cockpit-project/cockpit/pull/20613
 * [x] Rebase once more to get clean test stats

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20240611-134925

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-debian-testing-6e185ba2-20240611-133456/log.html

**Comment by martinpitt** [comment]
This image completely breaks the accounts page, see [expensive](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6491-59092a9a-20240611-143914-debian-testing-expensive-cockpit-project-cockpit/log.html) and [other](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6491-59092a9a-20240611-143917-debian-testing-other-cockpit-project-cockpit/log.html) tests.

The page immediately throws an uncaught `not-found` error. This isn't very friendly as the page also never finishes loading. The [most recent version of login](https://tracker.debian.org/news/1534499/accepted-shadow-1413dfsg1-5-source-into-unstable/) dropped `lastlog` and our code doesn't handle this.

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20240611-162904

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-debian-testing-c43af7ca-20240611-161410/log.html

**Comment by martinpitt** [comment]
The main issue is now that `lastlog2` only outputs the users which ever logged in; so we are never running the `isLocked` detection for all the other users in `getLogins()`. This needs some more code shifting.

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20240617-131115

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-debian-testing-89dacba6-20240617-125740/log.html

**Comment by martinpitt** [comment]
[This failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6491-275efd40-20240617-131425-debian-testing-cockpit-project-cockpit-files/log.html) just needs a lib refresh. I triggered https://github.com/cockpit-project/cockpit-files/pull/560

**Review by jelly — APPROVED** [review]

**Comment by jelly** [comment]
That was quite the fight :boxing_glove:

**Pull request merged**
