### PR TITLE
testmap: Run sub-man on Fedora 40

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by martinpitt** [comment]
[This failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5985-20240227-113626-a2d71d11-fedora-40-osbuild-cockpit-composer/log.html) is a common flake. Retrying.

@ptoscano @jkozol FYI -- I take it you don't mind enabling F40 now?

**Comment by ptoscano** [comment]
The sub-man parts LGTM, thanks! :+1:

**Comment by martinpitt** [comment]
OK, repeated [composer failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5985-20240227-122441-a2d71d11-fedora-40-osbuild-cockpit-composer/log.html), sorry @jkozol -- that needs fixing on your end first.

I reduce this PR to just enable sub-man.

**Review by ptoscano — APPROVED** [review]
Thanks :+1: 

In general, you can safely add new Fedora versions to the sub-man repositories without many issues: we run the sub-man test suite for sub-man in the `main` branch also on Fedora rawhide, so we are able to fix issues in advance (most of them being compatibility with a newer Python version).

**Review by jelly — APPROVED** [review]

**Pull request merged**
