### PR TITLE
testmap: Test rhel-9 by default

### PR DESCRIPTION
**Pull request by marusak**

### CODE REVIEW

**Review by KKoukiou — APPROVED** [review]

**Comment by martinpitt** [comment]
Hmm, I haven't seen this [TestAccounts failure](https://logs.cockpit-project.org/logs/pull-1877-20210401-073603-7aef75c1-rhel-9-0-cockpit-project-cockpit/log.html#322-2) at all so far. It could be vaguely related to https://github.com/cockpit-project/cockpit/pull/15613  , which was not tested (with CI) on RHEL 9.0. Of course I *developed* the fix on RHEL 9.0, as we got the bug report there.. But I figure this needs to be looked at.

**Comment by marusak** [comment]
I actually saw this issue on some different OS today as well in https://github.com/cockpit-project/cockpit/pull/15626 so not strictly related to rhel-9

**Comment by marusak** [comment]
This is broken due to today being 1.4 :) Fixed in https://github.com/cockpit-project/cockpit/pull/15636

**Comment by martinpitt** [comment]
Cockpit got fixed, retrying

**Comment by martinpitt** [comment]
@mvollmer: [This failure here](https://logs.cockpit-project.org/logs/pull-1877-20210401-184359-7aef75c1-rhel-9-0-cockpit-project-cockpit/log.html#245-2) smells very much like https://github.com/cockpit-project/bots/issues/1739 , but it does not time out, but fails on `assert (size > 300000)`; This is a rather bad assertion, as it does not tell us the actual value. But supposedly it's the same bug, just hitting at a slightly different place?

**Comment by marusak** [comment]
Ok, now the assert is better:
```
AssertionError: 268624 not greater than 300000
```

**Comment by marusak** [comment]
First observation - when we `Mount` it then the resize works as expected.

**Comment by marusak** [comment]
Looking into this in https://github.com/cockpit-project/cockpit/pull/15657

**Comment by martinpitt** [comment]
Ugh, a [lot of test failures](https://logs.cockpit-project.org/logs/pull-1877-20210406-163013-a6c14423-rhel-9-0-cockpit-project-cockpit/log.html#65) .. Maybe let's drop -machines first?

Retrying once, anyway, to compare.

**Review by martinpitt — APPROVED** [review]
Thanks! (Assuming this goes green)

**Comment by marusak** [comment]
Ok, this is annoying. `TestMachinesSnapshots.testSnapshots` is dumping `qemu-kvm`.
This is nothing new (weather page knows about it) yet it seems strongly persistent.
As we are moving machines away this will solve itself. We will likely hit it again when we will try to enable rhel 9 on machines tests though.

**Comment by martinpitt** [comment]
> We will likely hit it again when we will try to enable rhel 9 on machines tests though.

c-machines already has rhel-9 enabled.

**Pull request merged**
