### PR TITLE
images: Install libappstream-glib into RHEL mocks

### PR DESCRIPTION
**Pull request by martinpitt**
We need this to build starter-kit/cockpit-podman/etc. rpms on the test
VM instead of on the host, see [1]. Our rhel-9-0 image already has this,
but not 8.6.

[1] https://github.com/cockpit-project/cockpit-podman/pull/901

 - [x] Fix image refresh in PR #2870
 - [x] image-refresh rhel-8-6
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-2876-20220131-135555/

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20220131-141717

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-2876-20220131-141818/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-2876-20220131-141919/

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20220131-144747

**Comment by martinpitt** [comment]
Against this image, the test in https://github.com/cockpit-project/cockpit-podman/pull/901 now succeeded.

**Review by marusak — APPROVED** [review]
Thanks!

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-2876-20220131-171919/

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20220131-174141

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20220131-231010

**Pull request merged**
