### PR TITLE
Image refresh for centos-10

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-10
 * [x] image-refresh centos-10

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20241024-072307

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-4df8e53a-20241024-070708/log.html

**Comment by martinpitt** [comment]
OK, most of the problems are gone, but [TestSshDialog.testPassword](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7027-d1c8f783-20241024-072428-centos-10-other-cockpit-project-cockpit/log.html#62-2) still fails -- apparently that uses a pty?

**Comment by martinpitt** [comment]
Ah, this still picked up the revision -2 of openssh-clients. I don't get that -- we already enable the development compose https://composes.stream.centos.org/stream-10/development/latest-CentOS-Stream/compose/BaseOS/x86_64/os/Packages/ and that very definitively has -3. I can run

```
dnf update https://composes.stream.centos.org/stream-10/development/latest-CentOS-Stream/compose/BaseOS/x86_64/os/Packages/openssh-9.9p1-3.el10.x86_64.rpm https://composes.stream.centos.org/stream-10/development/latest-CentOS-Stream/compose/BaseOS/x86_64/os/Packages/openssh-clients-9.9p1-3.el10.x86_64.rpm  https://composes.stream.centos.org/stream-10/development/latest-CentOS-Stream/compose/BaseOS/x86_64/os/Packages/openssh-server-9.9p1-3.el10.x86_64.rpm
```

and all tests work again. So we need to figure out how to fix this *censored* repo.

**Comment by martinpitt** [comment]
Fixed in #7030

**Pull request closed without merging**
