### PR TITLE
images: add glib2-devel as makedependency

### LINKED ISSUE #6499: Image refresh for arch
Image refresh for arch
 * [ ] image-refresh arch

### PR DESCRIPTION
**Pull request by jelly**
* [x] image-refresh arch

glib2 has been split up into glib2-devel since 2.80.3-2.

https://lists.archlinux.org/archives/list/arch-dev-public@lists.archlinux.org/thread/FLUDH7DXL5CJNZPX4NAWKQO2QJF3PZCD/

Closes #6499

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240615-200054

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-0571f695-20240615-195103/log.html

**Comment by martinpitt** [comment]
This could have been pushed to #6499, but I just marked this PR as closing that. Thanks!

**Comment by jelly** [comment]
> This could have been pushed to #6499, but I just marked this PR as closing that. Thanks!

Woops, it just crossed my mind we still had this broken refresh so it was easy to just push a new branch.

**Comment by martinpitt** [comment]
```
gdbus-codegen --interface-prefix com.redhat.Cockpit.DBusTests --c-namespace Test --c-generate-object-manager  --header --output src/ws/mock-dbus-tests.h src/ws/com.redhat.Cockpit.DBusTests.xml
make: gdbus-codegen: No such file or directory
```

Give me just ... one more? :notes:

**Comment by martinpitt** [comment]
Oh, I think you need to add it to the build chroot, not into the host (it's not a test dependency)

**Comment by jelly** [comment]
Re-refreshing by installing it to the build chroot :face_exhaling:

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240617-102713

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-c42bc4c0-20240617-101529/log.html

**Review by martinpitt — APPROVED** [review]
Dankjewel!

**Pull request merged**
