### PR TITLE
Image refresh for rhel-8-10

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-10
 * [x] image-refresh rhel-8-10
 * [ ] https://issues.redhat.com/browse/RHEL-55757

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-8-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-10-20240908-230627

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-8-10-8bf46d64-20240908-223855/log.html

**Comment by jelly** [comment]
The podman issue is https://issues.redhat.com/browse/RHEL-55757

**Comment by martinpitt** [comment]
OMG :see_no_evil: how does such an update even make it past gating.. Let's wait for a week or so, and then look at more drastic measures such as downgrading?

**Comment by martinpitt** [comment]
Latest runc update has fixed this. A new round..

**Pull request closed without merging**
