### PR TITLE
Image refresh for fedora-rawhide

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide
 * [x] image-refresh fedora-rawhide
 * [x] ~Get fix for https://bugzilla.redhat.com/show_bug.cgi?id=2250930 landed in rawhide and re-refresh~, or globally ignore SELinux failure

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-20231126-225852

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-20231126-225858.log

**Comment by martinpitt** [comment]
> audit: type=1400 audit(1701062979.018:351): avc:  denied  { map_read map_write } for  pid=1592 comm="cockpit-tls" scontext=system_u:system_r:cockpit_ws_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=bpf permissive=0

This is the same error that I saw in https://pagure.io/fedora-ci/general/issue/447 , the more specific bug is https://bugzilla.redhat.com/show_bug.cgi?id=2250930 . This affects rawhide only for now. We can block this for a few days, but if it's not fixed quickly, we'll have to globally allow it in cockpit test/common, and bump starter-kit and navigator.

**Comment by martinpitt** [comment]
Timeout, I added an ignore.

**Review by jelly — APPROVED** [review]

**Pull request merged**
