### PR TITLE
Revert "images: Drop conditional insights-client code from rhel-7-9.setup"

### LINKED ISSUE #3253: Image refresh for centos-7 - fixed in #3256
Image refresh for centos-7
 * [ ] FAIL: image-refresh centos-7

### PR DESCRIPTION
**Pull request by martinpitt**
This was bogus -- the centos-7 image also uses this setup script, and
does not have insights-client.

This reverts commit 9b9c17a99e0c27fd313378f1ad9d96708072b167.

Fixes #3253 

 * [x] image-refresh centos-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-3256-20220420-043131/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-7-20220420-050808

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-3256-20220420-050808/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-7-20220420-054545

**Review by marusak — APPROVED** [review]
ug, centos-7 uses `rhel-7-9.setup` script?

**Pull request merged**
