### PR TITLE
Image refresh for fedora-41

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-41
 * [x] image-refresh fedora-41

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-41 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-41-20240826-094224

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-41-3874bb95-20240826-092733/log.html

**Comment by martinpitt** [comment]
[this login failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6790-95e155a2-20240826-094346-fedora-41-other-cockpit-project-cockpit/log.html) is naughty issue #6789 . @allisonkarlitskaya handles that in PR #6791, so closing as duplicate.

**Comment by allisonkarlitskaya** [comment]
Let's kill #6791 and keep this one: it already finished building the image.

**Review by martinpitt — APPROVED** [review]
Thanks! Green bot, happy pitti!

**Pull request merged**
