### PR TITLE
Image refresh for ubuntu-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for ubuntu-stable
 * [x] image-refresh ubuntu-stable
 * [ ] fix timesyncd tests: https://github.com/cockpit-project/cockpit/pull/13017

### CODE REVIEW

**Comment by martinpitt** [comment]
Ubuntu 19.10 got released, so we need some adjustments to the new release.

All password checks now fail with

    BAD PASSWORD: The password is shorter than 8 characters

We already spotted this for Fedora 31 and fixed in #57, so we need something similar for Debian/Ubuntu now.

**Comment by martinpitt** [comment]
There's also something wrong with [timesyncd](https://209.132.184.41:8493/logs/pull-151-20191020-073636-5ac0f489-cockpit-project-cockpit--ubuntu-stable/backup.e1N7Av/backup.nO9QLh/log.html#250-2)

**Comment by martinpitt** [comment]
I pushed a fix for the libpwquality issue. The timesyncd one still applies, that needs some actual debugging effort.

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/13017 to fix the timesyncd tests.

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit/pull/13017 landed, retrying the test.

**Comment by martinpitt** [comment]
Just the usual [libVirt failure](https://209.132.184.41:8493/logs/pull-151-20191020-152626-4bcd7dba-cockpit-project-cockpit--ubuntu-stable/backup.AET6dF/log.html), retrying.

**Pull request merged**
