### PR TITLE
images: Use cloud image for centos-7

### PR DESCRIPTION
**Pull request by marusak**
* [x] image-refresh centos-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-3547-20220623-075252/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-7-20220623-083044

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-f5ds2.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3547-20220623-083030/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-7-20220623-085735

**Comment by marusak** [comment]
Cannot manage docker storage - https://cockpit-logs.us-east-1.linodeobjects.com/pull-3547-20220623-090141-ffa50c57-centos-7-cockpit-project-cockpit-rhel-7.9/log.html#43-2

**Comment by martinpitt** [comment]
Argh, because no LVM on cloud images..

**Comment by marusak** [comment]
Ok, lets not use then cloud images

**Pull request closed without merging**
