### PR TITLE
Image refresh for centos-10

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-10
 * [x] image-refresh centos-10
 * [ ] ~https://github.com/allisonkarlitskaya/ferny/pull/31 (nacked, asked for vendor-patching)~
 * [ ] pull that into cockpit: https://github.com/cockpit-project/cockpit/pull/21133
 * [x] alternatively: land https://gitlab.com/redhat/centos-stream/rpms/openssh/-/merge_requests/99 in c10s

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20241017-225703

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-e014a6d3-20241017-224104/log.html

**Comment by martinpitt** [comment]
I don't see anything in the changed package list which sticks out, but this seriously breaks multi-host stuff.

**Comment by martinpitt** [comment]
Indeed the new ssh version breaks our error message parsing. With the old version:
```
# ssh -p 987 localhost
ssh: connect to host localhost port 987: Connection refused
```

with the new version there's some additional text:

```
# ssh -p 987 localhost
ssh: connect to host localhost port 987: Connection refused

You can find some explanations for typical errors at this link:
	    https://red.ht/support_rhel_ssh
```

This is a RHEL specific patch: https://gitlab.com/redhat/centos-stream/rpms/openssh/-/commit/84ad70de575a2a241a3739c1f5aa1ae1d3cbb59e

I quickly ran the ferny tests in a  c10s container, and they work fine. I submitted https://github.com/allisonkarlitskaya/ferny/pull/30  to get that under CI.

So apparently that's somewhere in remote.py or beiboot.py?

**Comment by martinpitt** [comment]
I sent a ferny fix to https://github.com/allisonkarlitskaya/ferny/pull/31 . I applied it to a locally built c10 image, and confirmed that all test failures here now pass again. To get more confidence, I sent https://github.com/cockpit-project/cockpit/pull/21133 to test this new image against that PR.

**Pull request closed without merging**
