### PR TITLE
images: Drop PAM config hack

### PR DESCRIPTION
**Pull request by martinpitt**
This got fixed in cockpit's tests properly now:

 - [x] Fix tests in cockpit: https://github.com/cockpit-project/cockpit/pull/15164
 - [x] Backport to rhel-8.3 branch: https://github.com/cockpit-project/cockpit/pull/15169

### CODE REVIEW

**Comment by martinpitt** [comment]
Triggering the three affected tests, these should fail now. I want them for comparison, and I can trigger the tests against this image in the cockpit PRs.

**Review by marusak — DISMISSED** [review]
The commit message contains still TODO, I guess you wanted to put there reference?
But otherwise looks good, thanks!
(If you decide to repush, then no need to run tests if diff is empty)

**Comment by martinpitt** [comment]
@marusak: Thanks! I edited it here, but forgot to push it. I'll fix it on merge&squash.

**Comment by martinpitt** [comment]
Ah, no squashing, it's two commits. @marusak: So I adjusted the commit message, see above that it's zero diff. PTAL?

**Review by marusak — APPROVED** [review]
Thanks :)

**Pull request merged**
