### PR TITLE
lib: Enable cockpit-navigator testing

### PR DESCRIPTION
**Pull request by KKoukiou**
Needs PR to enable CI on the cockpit-navigator repo.

### CODE REVIEW

**Comment by martinpitt** [comment]
What is it blocked on? Do you really want to enable all these OSes right away, or perhaps start with `_manual`?

**Comment by KKoukiou** [comment]
> What is it blocked on? Do you really want to enable all these OSes right away, or perhaps start with `_manual`?

I though I need to add the .cockpit-ci/ directory to the repo, but looks like not. Let me try first once all the OSes and see how the tests do.

**Comment by martinpitt** [comment]
@KKoukiou the entry point is https://github.com/cockpit-project/bots/blob/main/test/run . `.cockpit-ci/run` is an alternate entry point indeed, but test/run is more common, especially if you have a test/ directory already anyway

**Review by martinpitt — APPROVED** [review]
Thanks! I'd add `TEST_OS_DEFAULT` (aka fedora-38) and at least ubuntu-stable as well, though. You can do that as a follow-up, or here right away.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
