### PR TITLE
Image refresh for rhel-8-2

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-2
 * [x] image-refresh rhel-8-2

### CODE REVIEW

**Comment by marusak** [comment]
`+ module -d ipa_custodia` not this again. I thought we fixed it in every possible scenario.

**Comment by martinpitt** [comment]
@marusak: We need to backport it to the rhel-8.2 branch, right?

**Comment by martinpitt** [comment]
I sent PR #14022 to fix the two test regressions.

**Comment by marusak** [comment]
> We need to backport it to the rhel-8.2 branch, right?

ah, of course. I totally missed that I looked into test from branch. Thanks for the backport!

**Comment by martinpitt** [comment]
@marusak: podman [keeps failing](https://logs.cockpit-project.org/logs/pull-826-20200505-074939-888d1d78-rhel-8-2-cockpit-project-cockpit-podman/log.html), is that a known crash or something new? I. e. retry or bz+naughty?

**Comment by marusak** [comment]
Possible fix in https://github.com/cockpit-project/cockpit-podman/pull/378

**Pull request merged**
