### PR TITLE
Image refresh for fedora-37

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-37
 * [x] image-refresh fedora-37

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-37-20230208-230202.log

**Comment by jelly** [comment]
```
Changed:
  container-selinux (2:2.198.0-1.fc37 -> 2:2.199.0-1.fc37)
  containers-common (4:1-76.fc37 -> 4:1-78.fc37)
  containers-common-extra (4:1-76.fc37 -> 4:1-78.fc37)
  distribution-gpg-keys (1.81-1.fc37 -> 1.82-1.fc37)
  hwdata (0.366-1.fc37 -> 0.367-1.fc37)
  kernel-core (6.1.8-200.fc37 -> 6.1.9-200.fc37)
  libpwquality (1.4.5-1.fc37 -> 1.4.5-3.fc37)
  mock-core-configs (37.9-1.fc37 -> 38.1-1.fc37)
  selinux-policy (37.18-1.fc37 -> 37.19-1.fc37)
  selinux-policy-devel (37.18-1.fc37 -> 37.19-1.fc37)
  selinux-policy-targeted (37.18-1.fc37 -> 37.19-1.fc37)
  stratis-cli (3.4.1-1.fc37 -> 3.5.0-1.fc37)
  stratisd (3.4.4-1.fc37 -> 3.5.0-1.fc37)
```

**Comment by jelly** [comment]
So this pixel diff:

```
compare TestBonding-testBasic-networking-bond-settings-dialog-mobile-pixels.png test/reference/TestBonding-testBasic-networking-bond-settings-dialog-mobile-pixels.png -compose src foo.png
```

image


https://stackoverflow.com/questions/5132749/diff-an-image-using-imagemagick

**Comment by jelly** [comment]
So rawhide also fails in their own PR's which is problematic, @M4rtinK is this a flake or a known issue?

https://github.com/rhinstaller/anaconda/pull/4548
https://cockpit-logs.us-east-1.linodeobjects.com/pull-4548-20230209-143727-e6319936-fedora-rawhide-boot/pixeldiff.html#TestLanguage-testLanguageSwitching-language-step-basic

**Comment by jelly** [comment]
anaconda tests already fail in their PR's, merging.

**Comment by M4rtinK** [comment]
> So rawhide also fails in their own PR's which is problematic, @M4rtinK is this a flake or a known issue?
> 
> [rhinstaller/anaconda#4548](https://github.com/rhinstaller/anaconda/pull/4548) https://cockpit-logs.us-east-1.linodeobjects.com/pull-4548-20230209-143727-e6319936-fedora-rawhide-boot/pixeldiff.html#TestLanguage-testLanguageSwitching-language-step-basic

Yeah, if its just this once case, then that's indeed a known issue we need to address on our side - basically, some new translations invalidating pixel test reference images & should be fine once we update the reference image.

**Pull request merged**
