### PR TITLE
task: distributed_queue: add 'localhost' mode

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
If the --amqp parameter of `run-queue`, `inspect-queue`, `tests-scan`, etc. is given as exactly the string `"localhost"` then don't try to load certificates -- instead try to connect to localhost on port 6572 using plain text credentials (guest:guest).  That's the default configuration for the docker image.

This means that you can do this for simplified local testing:

```
$ podman run --net=host --rm docker.io/rabbitmq
$ ./run-queue --amqp localhost
```

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
If you need this and prefer it over `run-local.sh -i`, then no objection.

**Comment by allisonkarlitskaya** [comment]
I don't *need* this, but it makes my life easier for random local/heavily-interactive testing outside of the framework of `run-local.sh`.  I could still be convinced that I'm "doing it wrong"...

**Comment by martinpitt** [comment]
Yeah, you *really* want `-i` for that, that's what it's for :grin:

**Comment by allisonkarlitskaya** [comment]
> Yeah, you _really_ want `-i` for that, that's what it's for 😁

So for example, when I first do that, it complains about missing `openssl`.  I install it, then it complains about:

`mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "https://localhost.localdomain:9000/probe-bsign-ise2c9rty4fwdhus6uzqf19xoizcz0/?location=": http: server gave HTTP response to HTTPS client.`

**Pull request merged**
