### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos
 * https://github.com/cockpit-project/cockpit-ostree/pull/309

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-coreos-20221227-224545.log

**Comment by martinpitt** [comment]
Weird, [lots of subtle pixel failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4208-20221227-224713-2f7fd148-fedora-coreos-cockpit-project-cockpit-ostree/log.html). This shouldn't be related to the image refresh surely? They still worked 3 days ago in https://github.com/cockpit-project/cockpit-ostree/pull/307.

I'll retry this here to compare, and sent https://github.com/cockpit-project/cockpit-ostree/pull/308 to test it against the current image.

**Comment by martinpitt** [comment]
Interesting, this is stable. I'll send a c-ostree PR to update pixels.

**Comment by martinpitt** [comment]
Updated pixels in https://github.com/cockpit-project/cockpit-ostree/pull/309 , running the c-ostree test there.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
