### PR TITLE
Image refresh for fedora-37

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-37
 * [x] image-refresh fedora-37

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-37-20221201-091717.log

**Comment by martinpitt** [comment]
@M4rtinK , @KKoukiou : So the pixel test fails here due to the change from "1.73" → "1.74 GB" of required storage space. It seems to me that the pixel test should just ignore the whole message? Or perhaps changing Anaconda to show this number with less precision?

**Comment by skobyda** [comment]
> It seems to me that the pixel test should just ignore the whole message?

Yesterday I sent a PR which does exactly that: https://github.com/rhinstaller/anaconda/pull/4458

**Comment by jkonecny12** [comment]
Merged on the Anaconda side. Thanks for everything!

**Comment by M4rtinK** [comment]
Thanks! It's nice how easy this is - I'm sure we will use this for more stuff & check the dynamic value via regular non-pixel unit tests if necessary. :)

**Comment by martinpitt** [comment]
Nice, thanks @skobyda ! Retrying anaconda test, this should then be ready to land.

**Review by skobyda — APPROVED** [review]
All green

**Pull request merged**
