### PR TITLE
images: Build rhel-8-4 from official qcow image

### PR DESCRIPTION
**Pull request by martinpitt**
Starting from the cloud image is faster, more robust, and more realistic
(using an official product) than our own virt-install bootstrap.

Teach cloudimage.bootstrap to get along with redirects, as
download.devel.redhat.com is a geolocation mirror.

 * [x] image-refresh rhel-8-4
 * [x] wait until nightly qcows come back: https://projects.engineering.redhat.com/browse/RHELCMP-3635 - worked around by using specific mirror for now
 * [x] fix cockpit-composer vm.install: https://github.com/osbuild/cockpit-composer/pull/1205
 * [x] fix [crypttab failures](https://logs.cockpit-project.org/logs/pull-1518-20210105-155953-aa71a887-rhel-8-4-cockpit-project-cockpit/log.html): reported as https://github.com/cockpit-project/cockpit/issues/15100 , added workaround
 * [x] fix [check-metrics TestMetrics.testCurrentMetrics](https://logs.cockpit-project.org/logs/pull-1518-20210106-131421-751e1597-rhel-8-4-cockpit-project-cockpit/log.html#128-2): https://github.com/cockpit-project/cockpit/pull/15104

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-1518-20210105-063636/

**Comment by cockpituous** [comment]
image-refresh rhel-8-4 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-4-20210105-065050

**Comment by martinpitt** [comment]
The [previous refresh](https://logs.cockpit-project.org/logs/image-refresh-1489-20201224-022222/log) took 1219s . Image size was 2.47 GB. This refresh took just 891 s and image size is roughly the same (2.46 GB).

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-1518-20210105-074949/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1518-20210105-074949/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-1518-20210105-075757/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1518-20210105-075757/

**Comment by martinpitt** [comment]
While the first image refresh still worked, the image now literally disappeared from the current compose. Blocking until they come back.

**Comment by martinpitt** [comment]
I am temporarily putting back the initial (still slightly broken) image refresh so that I can test my cockpit-composer fix.

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-1518-20210105-152121/

**Comment by cockpituous** [comment]
image-refresh rhel-8-4 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-4-20210105-154444

**Comment by martinpitt** [comment]
Apparently we [lost /etc/crypttab on the image](https://logs.cockpit-project.org/logs/pull-1518-20210105-155953-aa71a887-rhel-8-4-cockpit-project-cockpit/log.html), and we need to adjust our tests or even the code to get along without it. Or bring back cryptsetup onto the image, I need to check this locally.

**Comment by martinpitt** [comment]
I reported the crypttab failure as https://github.com/cockpit-project/cockpit/issues/15100 , this is real -- this kinda shows the point of testing this on more variety of image types. This should be green now, ready for review.

**Comment by martinpitt** [comment]
There is [one remaining test case failure](https://logs.cockpit-project.org/logs/pull-1518-20210106-131421-751e1597-rhel-8-4-cockpit-project-cockpit/log.html#128-2) as this new image does not have swap. I sent a fix for that to  https://github.com/cockpit-project/cockpit/pull/15104

**Comment by marusak** [comment]
All landed, unblocked

**Review by marusak — APPROVED** [review]
Nice one, thanks!

**Pull request merged**
