### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-coreos done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-coreos-20240429-224448

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-coreos-83da136b-20240429-223712/log.html

**Comment by martinpitt** [comment]
Note that this moves f-coreos from F39 to F40. Fortunately most things work ok, but there's a pasta regression:  :cry: 
```
Error: pasta failed with exit code 1:
External interface not usable
```

**Comment by jelly** [comment]
I tried to reproduce this and it is way more interesting, networking for the admin user is totally broken:

I can't pull an image as `admin` user I can as root. I can't curl as admin, I can as root:
```
[admin@fedora-40-127-0-0-2-2201 ~]$ curl https://getfedora.org
```
This just hangs

**Comment by jelly** [comment]
So to make this a bit more clear:

As user:
```
admin@fedora-coreos-127-0-0-2-2202:~$ podman run -ti localhost/test-alpine sh
/ #
```

Then exit container and as root

```
[root@fedora-coreos-127-0-0-2-2202 ~]# podman run -ti localhost/test-alpine sh
/ #
```

Then try to start a container as user:

```
admin@fedora-coreos-127-0-0-2-2202:~$ podman run -ti localhost/test-alpine sh
Error: pasta failed with exit code 1:
External interface not usable
```

```

**Comment by jelly** [comment]
@martinpitt a solution is to run the tests not offline in podman as workaround.

**Comment by martinpitt** [comment]
@jelly Thanks for figuring out! That seems like an acceptable workaround as long as it comes with a bz reference.

**Comment by jelly** [comment]
Created https://github.com/cockpit-project/cockpit-podman/pull/1701 for testing purposes.

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit-podman/pull/1701 landed, unblocked. I pushed a rebase.

**Pull request merged**
