### PR TITLE
Image refresh for debian-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-stable
 * [x] image-refresh debian-stable
 * [x] image-refresh ubuntu-2004
 * [x] image-refresh rhel-7-9
 * [x] image-refresh fedora-34

### CODE REVIEW

**Comment by allisonkarlitskaya** [comment]
This is now failing:

```
            # make sure root never gets locked out
            for n in range(1, 10):
                expect_failed_login("root", "bad", n)
            expect_successful_login("root", "foobar")
```

**Comment by allisonkarlitskaya** [comment]
That's odd: 

```
Removed:

Added:

Changed:
```

**Comment by allisonkarlitskaya** [comment]
I'm suspicious that this is due to the change in how we supply the password to cloud-init, rather than any change in the OS itself.

**Comment by allisonkarlitskaya** [comment]
Indeed, root has no password on this image.  That would explain the failing tests, and probably it's exactly the same story in #2318.

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-2317-20210818-093535/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20210818-094949

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-2317-20210818-094949/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2004 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2004-20210818-100707

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2317-20210818-101919/

**Comment by allisonkarlitskaya** [comment]
Doing some extra builds (one rhel, one Fedora) to make sure these set of changes didn't break those ones :)

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-7-9-20210818-104545

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-4dm75.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-2317-20210818-104545/

**Comment by cockpituous** [comment]
image-refresh fedora-34 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-34-20210818-110000

**Comment by allisonkarlitskaya** [comment]
Uh, obviously ignore the fedora and rhel statuses: the images for those aren't even in this branch.

**Comment by allisonkarlitskaya** [comment]
I manually inspected the built rhel and fedora images and they're working fine.

**Review by allisonkarlitskaya — APPROVED** [review]
Someone else should look at this as well.

**Review by mvollmer — APPROVED** [review]

**Comment by mvollmer** [comment]
Nice, thanks!

**Pull request merged**
