### PR TITLE
pin mock's selinux-policy version to that on the VM

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
We've seen a couple of failures like #2057 lately, caused by mock ending up with a different (newer) version of selinux-policy than the "host" VM.

Here's a workaround to make sure it will have the same one.

 * [x] image-refresh fedora-34
 * [x] image-refresh fedora-33
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-2059-20210528-150505/

**Comment by cockpituous** [comment]
image-refresh fedora-34 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-34-20210528-152121

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2059-20210528-152121/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-2059-20210528-152121/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-p4wtg.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-2059-20210528-152121/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20210528-153939

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-2059-20210528-153939/

**Comment by allisonkarlitskaya** [comment]
Pushed the fedora-34 update, since it's the only one that really needs it.

**Comment by cockpituous** [comment]
image-refresh fedora-33 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-33-20210528-155757

**Comment by allisonkarlitskaya** [comment]
from the f34 fail:

```
Upgraded:
  abrt (2.14.5-3.fc34 -> 2.14.6-1.fc34)
  abrt-addon-ccpp (2.14.5-3.fc34 -> 2.14.6-1.fc34)
  abrt-dbus (2.14.5-3.fc34 -> 2.14.6-1.fc34)
  abrt-libs (2.14.5-3.fc34 -> 2.14.6-1.fc34)
  abrt-retrace-client (2.14.5-3.fc34 -> 2.14.6-1.fc34)
```

**Comment by allisonkarlitskaya** [comment]
eh.  I actually don't feel like debugging this one lol.

Anyone else? :)

**Comment by marusak** [comment]
`reportd` crashes. It need to be reported. Mind you, we are using for this special workflow.
I am happy to create the report, but tomorrow evening or on Monday.

```
May 28 15:58:28 fedora systemd-coredump[27716]: Process 27698 (reportd) of user 0 dumped core.
                                                
                                                Stack trace of thread 27705:
                                                #0  0x00007f9458db32a2 raise (libc.so.6 + 0x3d2a2)
                                                #1  0x00007f9458d9c8a4 abort (libc.so.6 + 0x268a4)
                                                #2  0x00007f9458df5a97 __libc_message (libc.so.6 + 0x7fa97)
                                                #3  0x00007f9458dfd70c malloc_printerr (libc.so.6 + 0x8770c)
                                                #4  0x00007f9458dfeadc _int_free (libc.so.6 + 0x88adc)
                                                #5  0x00007f9458e027c8 cfree (libc.so.6 + 0x8c7c8)
                                                #6  0x00007f9458ff724d g_free (libglib-2.0.so.0 + 0x5a24d)
                                                #7  0x00007f9458f7d175 free_run_event_state (libreport.so.1 + 0x1d175)
                                                #8  0x000055a0f81fb0bd reportd_task_start (reportd + 0xe0bd)
                                                #9  0x00007f94591e0def g_task_thread_pool_thread (libgio-2.0.so.0 + 0xaedef)
                                                #10 0x00007f9459023b24 g_thread_pool_thread_proxy.lto_priv.0 (libglib-2.0.so.0 + 0x86b24)
                                                #11 0x00007f9459020c32 g_thread_proxy (libglib-2.0.so.0 + 0x83c32)
                                                #12 0x00007f9458cb3299 start_thread (libpthread.so.0 + 0x9299)
                                                #13 0x00007f9458e76353 __clone (libc.so.6 + 0x100353)
                                                
                                                Stack trace of thread 27698:
                                                #0  0x00007f9458e6b5bf __poll (libc.so.6 + 0xf55bf)
                                                #1  0x00007f945904647c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa947c)
                                                #2  0x00007f9458ff1a93 g_main_loop_run (libglib-2.0.so.0 + 0x54a93)
                                                #3  0x000055a0f81f597e main (reportd + 0x897e)
                                                #4  0x00007f9458d9db75 __libc_start_main (libc.so.6 + 0x27b75)
                                                #5  0x000055a0f81f5b7e _start (reportd + 0x8b7e)
                                                
                                                Stack trace of thread 27699:
                                                #0  0x00007f9458e6b5bf __poll (libc.so.6 + 0xf55bf)
                                                #1  0x00007f945904647c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa947c)
                                                #2  0x00007f9458fefc03 g_main_context_iteration (libglib-2.0.so.0 + 0x52c03)
                                                #3  0x00007f9458fefc51 glib_worker_main (libglib-2.0.so.0 + 0x52c51)
                                                #4  0x00007f9459020c32 g_thread_proxy (libglib-2.0.so.0 + 0x83c32)
                                                #5  0x00007f9458cb3299 start_thread (libpthread.so.0 + 0x9299)
                                                #6  0x00007f9458e76353 __clone (libc.so.6 + 0x100353)
                                                
                                                Stack trace of thread 27700:
                                                #0  0x00007f9458e6b5bf __poll (libc.so.6 + 0xf55bf)
                                                #1  0x00007f945904647c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa947c)
                                                #2  0x00007f9458ff1a93 g_main_loop_run (libglib-2.0.so.0 + 0x54a93)
                                                #3  0x00007f9459242d5a gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x110d5a)
                                                #4  0x00007f9459020c32 g_thread_proxy (libglib-2.0.so.0 + 0x83c32)
                                                #5  0x00007f9458cb3299 start_thread (libpthread.so.0 + 0x9299)
                                                #6  0x00007f9458e76353 __clone (libc.so.6 + 0x100353)
```

**Comment by marusak** [comment]
We have naughty https://github.com/cockpit-project/bots/pull/2064 which seems very close - but not the same. And it hasn't happened in 28 days so might be, that there has been a slight change and it it failing somewhat differently.

**Comment by mvollmer** [comment]
Upps, I went too fast with the reopening and reverting. The pattern needs to be different.

**Comment by mvollmer** [comment]
> The pattern needs to be different.

Alright, we need two patterns...

**Comment by mvollmer** [comment]
The way a focused text input is rendered has somehow changed: https://logs.cockpit-project.org/logs/pull-2059-20210602-113605-077d49ed-fedora-34-cockpit-project-cockpit-machines/pixeldiff.html#TestMachinesCreate-testCreateBasicValidation-auto

This wasn't caused by the image refresh here and has been seen elsewhere as well. Let's ignore this here.

**Review by mvollmer — APPROVED** [review]

**Pull request merged**
