### PR TITLE
images: Drop man-db from Fedora and RHEL images

### PR DESCRIPTION
**Pull request by martinpitt**
It installs a pair of man-db-{,restart-}cache-update.service which are really evil/strange and hard to disable. The man-db cache update uses a lot of CPU, and starts shortly after boot, and thus interferes with every test.

----

I noticed that [here](https://github.com/cockpit-project/cockpit/pull/19389#issuecomment-1735396314). `top` snapshot from a few seconds into the boot:

    810 root      39  19  230164   4764   2784 S  20.7   0.5   0:00.86 mandb      

 * [x] image-refresh centos-8-stream
 * [x] image-refresh rhel-9-4
 * [x] image-refresh fedora-39

### CODE REVIEW

**Review by allisonkarlitskaya — APPROVED** [review]
Fine by me if the rebuilds succeed.

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20230926-124529

**Comment by cockpituous** [comment]
image-refresh rhel-9-4 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-4-20230926-130707

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-4-20230926-130707.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-39-20230926-132626.log

**Review by allisonkarlitskaya — APPROVED** [review]
check, check, checkity check check, you are lis certified!

**Pull request merged**
