### PR TITLE
images: Build fedora-34 image from actual 34, not Rawhide

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh fedora-34

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-1718-20210225-055858/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1718-20210225-055858/

**Comment by martinpitt** [comment]
"Waiting for machine poweroff timed out", bah -- I'll see if I can reproduce this locally. Building f-33 from cloud image (PR #1719) worked well for me.

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-1718-20210225-063636/

**Comment by cockpituous** [comment]
image-refresh fedora-34 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-34-20210225-065151

**Review by KKoukiou — APPROVED** [review]

**Comment by martinpitt** [comment]
I'm doing a test run in I'm https://github.com/cockpit-project/cockpit/pull/15350 to make sure that this doesn't totally regress. I also test the old and this new image in https://github.com/cockpit-project/starter-kit/pull/428

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/starter-kit/pull/428 is green, and the image also [generally works](https://logs.cockpit-project.org/logs/pull-15350-20210225-065606-ae568063-fedora-34-bots-1718/log.html) for cockpit, so landing.

**Pull request merged**
