### PR TITLE
Image refresh for rhel-8-4

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-4
 * [x] image-refresh rhel-8-4

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 7-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-3317-20220502-093636/

**Comment by jelly** [comment]
Image was not successfully uploaded everywhere, let's just re-refresh.

**Comment by cockpituous** [comment]
Task threw an exception: https://logs.cockpit-project.org/logs/image-refresh-3317-20220502-093636/

**Comment by martinpitt** [comment]
@jelly : The previous refresh was fine. As long as e2e is down, uploads to cockpit-11 can't succeed. But even before they failed, but as long as they get uploaded to linode, all is fine.

**Comment by jelly** [comment]
> @jelly : The previous refresh was fine. As long as e2e is down, uploads to cockpit-11 can't succeed. But even before they failed, but as long as they get uploaded to linode, all is fine.

So, I listed the images on linode EU and there is only one rhel-8-4 image. I can't access us US linode s3 instance but it's probably not there either so I will close this PR so it can be re-refreshed.

**Pull request closed without merging**
