### PR TITLE
images: Clean up old kernels on RHEL images

### PR DESCRIPTION
**Pull request by martinpitt**
This reduces image size, and also halves the time for `fips-mode-setup`,
as that regenerates the initrd for all installed kernels.

-----

See e.g. [this log](https://logs.cockpit-project.org/logs/pull-16944-20220420-152532-e0814f83-centos-8-stream/log.html#249), `TestSystemInfo.testInconsistentCryptoPolicy` takes almost 10 minutes, and often more (and thus times out). rebuilding the initrd takes *loooong*, let's not do it twice. Also see our [Grafana board](https://grafana-frontdoor.apps.ocp.ci.centos.org/d/ci/cockpit-ci?orgId=1&viewPanel=34&from=now-2d&to=now)

 * [x] image-refresh centos-8-stream
 * [x] image-refresh rhel-8-6
 * [x] image-refresh rhel-9-0

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-5qfsz.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3265-20220421-053737/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3265-20220421-053737/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-5qfsz.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3265-20220421-055454/

**Comment by martinpitt** [comment]
The cleanup works as expected:
```
kernels before cleanup:
+ echo 'kernels before cleanup:'
+ rpm -qa kernel
+ sort -u
kernel-4.18.0-358.el8.x86_64
kernel-4.18.0-373.el8.x86_64
+ dnf repoquery --installonly --latest-limit=-1 -q
+ xargs --no-run-if-empty rpm -e --verbose
Preparing packages...
kernel-4.18.0-358.el8.x86_64
kernel-modules-4.18.0-358.el8.x86_64
kernel-core-4.18.0-358.el8.x86_64
kernels after cleanup:
+ echo 'kernels after cleanup:'
+ rpm -qa kernel
+ sort -u
kernel-4.18.0-373.el8.x86_64
```

However, cleaning up the old kernel broke loading new modules:
```
# podman pull quay.io/libpod/busybox
Error: kernel does not support overlay fs: 'overlay' is not supported over xfs at "/var/lib/containers/storage/overlay": backing file system is unsupported for this graph driver
```
So this cleanup needs to move to the end.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3265-20220421-061414/

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20220421-064444

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-3265-20220421-070505/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3265-20220421-070505/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-3265-20220421-071414/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20220421-073636

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-3265-20220421-073636/

**Comment by martinpitt** [comment]
Yay, the two [crypto policies tests](https://logs.cockpit-project.org/logs/pull-3265-20220421-064749-38029d71-centos-8-stream-cockpit-project-cockpit/log.html) on c8s "only" took 5 mins now instead of 10.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3265-20220421-073838/

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20220421-082727

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-3265-20220421-082727/

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20220421-091414

**Comment by martinpitt** [comment]
Tests succeeded, but due to the networking flakes the result wasn't sent to GitHub.

**Review by jelly — APPROVED** [review]

**Review by jelly — APPROVED** [review]

**Pull request merged**
