### PR TITLE
chronyd package sets for the rest

### PR DESCRIPTION
**Pull request by cockpituous**
* [x] image-refresh debian-stable
 * [x] image-refresh ubuntu-stable
 * [x] image-refresh ubuntu-2204

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-stable-20230120-131919.log

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/ubuntu-stable-20230120-134040.log

**Comment by cockpituous** [comment]
image-refresh ubuntu-2204 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2204-20230120-135954

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/ubuntu-2204-20230120-135959.log

**Review by martinpitt — APPROVED** [review]
Roger, Roger!

**Pull request merged**
