### PR TITLE
Image refresh for ubuntu-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for ubuntu-stable
 * [x] image-refresh ubuntu-stable
 * [x] add naughty for [cockpit-podman regression](https://logs.cockpit-project.org/logs/pull-1952-20210423-041454-7fc98305-ubuntu-stable-cockpit-project-cockpit-podman/log.html#5-2): issue #1956
 * [ ] adjust cockpit-machines tests to 21.04: https://github.com/cockpit-project/cockpit-machines/pull/130 (land together with this PR)
 * [x] cockpit [vfat format failure](https://logs.cockpit-project.org/logs/pull-1952-20210423-041454-7fc98305-ubuntu-stable-cockpit-project-cockpit/log.html#164-2): known issue #1957
 * [x] cockpit [storage flakes](https://logs.cockpit-project.org/logs/pull-1952-20210423-041454-7fc98305-ubuntu-stable-cockpit-project-cockpit/log.html#196-2): https://github.com/cockpit-project/cockpit/pull/15761
 * [x] cockpit [testResizeLuks](https://logs.cockpit-project.org/logs/pull-15752-20210428-052504-63de6efc-ubuntu-stable-bots-1952/log.html#196-2)

### CODE REVIEW

**Comment by martinpitt** [comment]
This is an interesting one -- Ubuntu 21.04 "hirsute" got released yesterday, so this refresh upgrades our previous 20.10 "groovy" image. There is apparently some fallout.

**Comment by martinpitt** [comment]
Looking at c-podman [failure](https://logs.cockpit-project.org/logs/pull-1952-20210423-041454-7fc98305-ubuntu-stable-cockpit-project-cockpit-podman/log.html#5-2). Ubuntu 21.04 still uses hybrid cgroups and has the same criu version as 21.10, so neither of the two current "ubuntu-stable" special cases in the tests should change.

`testDownloadImage` is something different, and it is reproducible easily on the CLI:
```
podman run -it --rm -p 5000:5000 --name registry docker.io/registry:2
curl http://localhost:5000/v2/
```

The curl command hangs forever, and so does netcat and anything else (like the `podman push` in the test). There is no log output from podman.

It's not firewalld -- that is running, but `systemctl stop firewalld` does not help, and either way this is localhost. I filed https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/1925765 about it, and a known issue https://github.com/cockpit-project/bots/issues/1956.

**Comment by martinpitt** [comment]
For c-machines I sent https://github.com/cockpit-project/cockpit-machines/pull/130 . That fixes all of the structural failures, but there's still some flakes left (mostly the ever-annoying libvirt/qemu crashes)

**Comment by martinpitt** [comment]
For cockpit, I investigated [TestStorageFormat.testFormatTypes](https://logs.cockpit-project.org/logs/pull-1952-20210423-041454-7fc98305-ubuntu-stable-cockpit-project-cockpit/log.html#164-2): This is a regression in udisks or the underlying stack, reported as https://launchpad.net/bugs/1925822 and added known issue https://github.com/cockpit-project/bots/issues/1957

**Comment by martinpitt** [comment]
Looking at [testMountOptions](https://logs.cockpit-project.org/logs/pull-1952-20210426-153344-bc0602a2-ubuntu-stable-cockpit-project-cockpit/log.html#181-2), the [screenshot](https://logs.cockpit-project.org/logs/pull-1952-20210426-153344-bc0602a2-ubuntu-stable-cockpit-project-cockpit/TestStorageMounting-testMountOptions-ubuntu-stable-127.0.0.2-2801-FAIL.png) shows "Type: No filesystem", so the `self.dialog_set_val("type", "ext4")` call either silently failed, or got reset somehow. 

I got this to fail locally at last. The initial setting correctly detected the "type" field type as "select" and chose the intended code path in `dialog_set_val()`:

```
dialog [data-field=\"type\"]","data-field-type")
<- {'type': 'string', 'value': 'select'}
-> wait: ph_is_present("#dialog [data-field=\"type\"] select:not([disabled]):not([aria-disabled=true])")
<- {'type': 'undefined'}
-> wait: ph_is_visible("#dialog [data-field=\"type\"] select:not([disabled]):not([aria-disabled=true])")
<- {'type': 'undefined'}
-> ph_set_val("#dialog [data-field=\"type\"] select","ext4")
<- {'type': 'undefined'}
```

I added an additional `self.browser.wait_val(sel + " select", val)` right after the `set_val()` to confirm that the `set_val` succeeds, and it does not: `wait: ph_has_val("#dialog [data-field=\"type\"] select","ext4")` times out, and the  dialog shows "No filesystem".

Then I suspected that the set_val happens too early, and the dialog is still initializing. I added

    b.wait_in_text("#dialog [data-field='type']", "Recommended default")

after the `self.dialog_wait_open()`, and that also fails: Type still shows "No filesystem". Indeed the select *only* has that value.

This points to the condition in `add_fsys()` failing. I'll add some debugging around this.

**Comment by martinpitt** [comment]
I filed https://github.com/cockpit-project/cockpit/pull/15752 which ought to fix these flakes.

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit/pull/15761 landed, which should improve the Storage tests a lot. Pushed a rebase, as we got several common image refreshes in between.

**Comment by martinpitt** [comment]
Finally, green! :four_leaf_clover:

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
