### PR TITLE
Image refresh for centos-8-stream

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-8-stream
 * [x] image-refresh centos-8-stream
 * [x] Add expected message: https://github.com/cockpit-project/cockpit/pull/13353

### CODE REVIEW

**Comment by martinpitt** [comment]
[this failure](https://209.132.184.41:8493/logs/pull-372-20191228-122929-1834c60a-cockpit-project-cockpit--centos-8-stream/log.html#67-2) looks a bit fishy, retrying once

**Comment by martinpitt** [comment]
Yep, that error is persistent.

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/13353 to fix the expected message. Once that lands, the test can be retried and should get green.

**Comment by marusak** [comment]
I had to rebase since some images changed in the meantime (like Fedora 30)

**Comment by martinpitt** [comment]
[Machines testCreate failure](https://209.132.184.41:8493/logs/pull-372-20200104-142323-cd1c5307-cockpit-project-cockpit--centos-8-stream/log.html#74-2), retrying

**Comment by martinpitt** [comment]
Same failure again, and it failed several times before that -- @KKoukiou , can you please have a look?

**Comment by KKoukiou** [comment]
> Same failure again, and it failed several times before that -- @KKoukiou , can you please have a look?

I ran locally twice - I can't reproduce. Maybe the CI was just too unlucky, re-triggering.

**Comment by martinpitt** [comment]
Nope, it's [persistent](https://209.132.184.41:8493/logs/pull-372-20200113-104848-cd1c5307-cockpit-project-cockpit--centos-8-stream/log.html)

**Comment by martinpitt** [comment]
Needs rebasing now, as it can't find the old f-30 image.

**Comment by martinpitt** [comment]
Still a [testCreate failure](https://209.132.184.41:8493/logs/pull-372-20200203-081414-612758d7-centos-8-stream-cockpit-project-cockpit/log.html#80-2), retrying

**Comment by martinpitt** [comment]
[testSnapshots](https://209.132.184.41:8493/logs/pull-372-20200203-094141-612758d7-centos-8-stream-cockpit-project-cockpit/log.html#230-2) failed again

**Comment by martinpitt** [comment]
testSnapshots keeps failing, same problem that we keep having on other OSes these days ("Create Snapshot" is not in the expected volume/table row), but here it's annoyingly persistent.  @mvollmer, can you please have a look?

**Pull request merged**
