### PR TITLE
Image refresh for rhel-7-9

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-7-9
 * [x] image-refresh rhel-7-9
 * [x] https://github.com/weldr/lorax/pull/1057

### CODE REVIEW

**Comment by martinpitt** [comment]
@bcl, @atodorov : `pip install` failure on the two lorax tests, does that ring a bell?

**Comment by atodorov** [comment]
> @bcl, @atodorov : `pip install` failure on the two lorax tests, does that ring a bell?

No, it doesn't.

Looking at the logs I see a traceback ending with 
```
STDERR: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
```

Not really sure what to do about that.

**Comment by bcl** [comment]
It looks like a unicode problem in pip when it is trying to cleanup after the install. I'm not sure where the installed pip comes from, but since py2.7 is dead it's probably not a good idea to upgrade it. I'd try dropping the `pip install --upgrade pip setuptool` and see if that works.

```
STDOUT: Collecting pip
STDOUT:   Downloading https://files.pythonhosted.org/packages/36/74/38c2410d688ac7b48afa07d413674afc1f903c1c1f854de51dc8eb2367a5/pip-20.2-py2.py3-none-any.whl (1.5MB)
STDOUT: Collecting setuptools
STDOUT:   Downloading https://files.pythonhosted.org/packages/e1/b7/182161210a13158cd3ccc41ee19aadef54496b74f2817cc147006ec932b4/setuptools-44.1.1-py2.py3-none-any.whl (583kB)
STDOUT: Installing collected packages: pip, setuptools
STDOUT:   Found existing installation: pip 9.0.1
STDOUT:     Uninstalling pip-9.0.1:
STDOUT:       Successfully uninstalled pip-9.0.1
STDOUT:   Found existing installation: setuptools 28.8.0
STDOUT:     Uninstalling setuptools-28.8.0:
STDOUT:       Successfully uninstalled setuptools-28.8.0
STDOUT: Successfully installed pip-20.2 setuptools-44.1.1
```

It goes from pip 9.0.1 to pip 20.2 which is quite a jump.

**Comment by marusak** [comment]
Sent https://github.com/weldr/lorax/pull/1057 to debug this

**Pull request merged**
