### PR TITLE
images: Move RHEL-10 images to valkey

### LINKED ISSUE #6700: Image refresh for rhel-10-0
Image refresh for rhel-10-0
 * [ ] FAIL: image-refresh rhel-10-0

### PR DESCRIPTION
**Pull request by martinpitt**
redis got removed from RHEL 10 [1] in favor of valkey. Make that the new default, and keep redis for RHEL 8/9.

Fixes #6700

[1] https://issues.redhat.com/browse/RHELBLD-15568

----

 * [x] image-refresh rhel-10-0
 * [x] image-refresh rhel-9-5

### CODE REVIEW

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-10-0-92ce931b-20240805-083450/log.html

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-5-92ce931b-20240805-090046/log.html

**Comment by cockpituous** [comment]
image-refresh rhel-10-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-10-0-20240805-093723

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-10-0-92ce931b-20240805-092211/log.html

**Review by tomasmatus — APPROVED** [review]

**Pull request merged**
