### PR TITLE
build-deps.sh: set -D 'cockpit_enable_python 1'

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
We want to make sure our images contain the required build dependencies for building the package with Python support enabled.

 * [x] image-refresh fedora-37
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-37 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-37-20230428-124059

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20230428-131435

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/centos-8-stream-20230428-131414.log

**Comment by mvollmer** [comment]
The log says:

```
++ /var/lib/testvm/build-deps.sh 'fedora 37'
warning: Macro expanded in comment on line 28: %{version}.

curl: (22) The requested URL returned error: 404
+ su builder -c '/usr/bin/mock --no-bootstrap-chroot --verbose -i "/usr/bin/python3" "autoconf" "automake" "docbook-style-xsl" "gcc" "gdb" "gettext >= 0.21" "glib-networking" "glib2-devel >= 2.50.0" "gnutls-devel >= 3.4.3" "krb5-devel >= 1.11" "krb5-server" "libssh-devel >= 0.8.5" "libxslt-devel" "make" "openssh-clients" "openssl-devel" "pam-devel" "pcp-libs-devel" "pkgconfig(gio-unix-2.0)" "pkgconfig(json-glib-1.0)" "pkgconfig(polkit-agent-1) >= 0.105" "sed" "selinux-policy" "selinux-policy-devel" "systemd-devel >= 235" "xmlto" "zlib-devel" "desktop-file-utils" "gdk-pixbuf2-devel" "gettext-devel >= 0.19.8" "glade-devel" "glib2-doc" "gobject-introspection-devel" "gsettings-desktop-schemas" "gtk-doc" "gtk3-devel >= 3.22.17" "gtk3-devel-docs >= 3.22.17" "libarchive-devel >= 3.0.4" "libgnomekbd-devel" "libtimezonemap-devel >= 0.4.1-2" "libtool" "libxklavier-devel >= 5.4" "libxml2" "make" "pango-devel" "python3-devel" "rpm-devel >= 4.15.0" "systemd" libappstream-glib rpmlint gettext desktop-file-utils nodejs nodejs-devel'
```

@allisonkarlitskaya, is that the expected output?

**Comment by mvollmer** [comment]
Let's run the cockpit tests with the fedora-37 image created here, to prove that building cockpit still works.

**Comment by allisonkarlitskaya** [comment]
> Let's run the cockpit tests with the fedora-37 image created here, to prove that building cockpit still works.

I'm currently rebuilding the fedora 37 image.  The first attempt failed and I needed to adjust the spec.

**Comment by allisonkarlitskaya** [comment]
ps: the 404 is because of Anaconda.  We try to fetch https://raw.githubusercontent.com/rhinstaller/anaconda/fedora-37/anaconda.spec.in but it apparently (no longer?) exists.

We should fix that in a separate PR.

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-37-20230428-133333.log

**Comment by allisonkarlitskaya** [comment]
The fedora-37 refresh actually went exactly as expected, but then after it finished, this happened on the host:

```
qemu-img: /cache/images/fedora-37.rebuild: error while converting qcow2: Could not create '/cache/images/fedora-37.rebuild': Permission denied
```

Let's retry that and hope we get a different host...

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-37-20230428-140202.log

**Comment by allisonkarlitskaya** [comment]
> Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-37-20230428-140202.log

Another one that has nothing to do with the changes here — and the image build was actually successful.  I'll pick it up here, rebase, and force-push, then run the tests.

**Comment by cockpituous** [comment]
image-refresh fedora-37 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-37-20230428-150616

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-37-20230428-150606.log

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20230428-162528

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/centos-8-stream-20230428-162525.log

**Comment by cockpituous** [comment]
image-refresh fedora-37 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-37-20230428-185304

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-37-20230428-185353.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/centos-8-stream-20230428-205656.log

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20230428-221222

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/centos-8-stream-20230428-221212.log

**Comment by allisonkarlitskaya** [comment]
```
stratisd (3.5.2-1.fc37 -> 3.5.3-1.fc37)
```

Looks like 3.5.4 is already on bodhi.  Maybe we get better luck with that.

**Comment by martinpitt** [comment]
@allisonkarlitskaya Stratis 3.5.4 is still in -testing, trying that version in PR #4647 where the same failure happened.

**Comment by martinpitt** [comment]
So the [stratisd 3.5.4 update](https://bodhi.fedoraproject.org/updates/FEDORA-2023-f437723ac7) does fix that bug, but it will take another 4 days to get into stable. I suggest to add a naughty but without a bugzilla to unblock this.

But I don't understand that [sub-man](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4707-20230429-012552-7df270b1-fedora-37-candlepin-subscription-manager/log.html) failure. That could have been a temporary glitch on the internal RH npm mirror? Retrying

**Review by martinpitt — APPROVED** [review]
sub-man retry was fine. I added a stratis naughty, and triggered c8s tests as well. New build-deps.sh installed packages look reasonable. Assuming that tests go green, let's get this in, and validate that they are sufficient to run your packaging update PR before we refresh the other images.

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit/pull/18723 already ran tests against this refreshed image, and they do work in general (there's a new unexpected message, but we'll deal with that there)

**Comment by martinpitt** [comment]
[annoying pixel test flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4707-20230501-174205-a9e1855c-fedora-37-cockpit-project-cockpit/log.html) which is PF5 fallout, retrying

**Pull request merged**
