### PR TITLE
testmap: test c-machines on fedora-39

### PR DESCRIPTION
**Pull request by tomasmatus**
* [x] image-refresh fedora-39
 * [x] image-refresh fedora-37

### CODE REVIEW

**Comment by martinpitt** [comment]
FTR, no need to trigger starter-kit and podman, these are already covered. So it seems machines needs code changes, thus you need to send a c-machines PR first. Once that's green, this one will be unblocked.

**Comment by tomasmatus** [comment]
yes, I now know how to trigger a single context instead of every fedora-39 context :) sorry

**Comment by martinpitt** [comment]
@tomasmatus : I started f37/f39 rebuilds; but note that it's a bit inconvenient to change the image and testmap in the same run. It's still possible, by running a cockpit-machines PR against `@bots#5146`, but it's usually easier to land an image refresh ASAP. You can still take the package addition and image refresh commits into a new PR after the builds finish, of course.

**Comment by tomasmatus** [comment]
@martinpitt ah right, I forgot that image builds run agains `bots:main`. I wont change it for now since you already triggered the refresh

**Comment by martinpitt** [comment]
> image builds run agains bots:main.

They don't, they run against the proposed branch. I just meant that you have this "need new image with package" → send machines PR with packaging fix → update testmap dependency chain.

**Comment by cockpituous** [comment]
image-refresh fedora-39 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-39-20230824-100741

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-39-20230824-100707.log

**Comment by cockpituous** [comment]
image-refresh fedora-37 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-37-20230824-103704

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-37-20230824-103737.log

**Comment by martinpitt** [comment]
There are still several regressions to be worked out -- possibly also just copying naughties? In order for not blocking two image refreshes any longer than necessary, I recommend to split this -- land the refreshes now, and queue the testmap change for later.

**Comment by skobyda** [comment]
https://github.com/cockpit-project/cockpit-machines/pull/1192 landed which unblocked, the last regression

**Review by skobyda — APPROVED** [review]

**Pull request merged**
