### PR TITLE
Image refresh for fedora-32

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-32
 * [x] image-refresh fedora-32

### CODE REVIEW

**Comment by marusak** [comment]
`Failed to enable unit: Unit file osbuild-composer.socket does not exist.`
ehm, what?

**Comment by marusak** [comment]
@larskarlitski

**Comment by ondrejbudai** [comment]
This is my fault, sorry. `osbuild-composer 15` (in f32 stable) requires `osbuild >= 17`. `osbuild 17` was obsoleted (= it never made it to stable) by `osbuild 18` in f32. However, `osbuild 18` is still in testing, therefore everything is currently broken.

The solution is to get `osbuild 18` to stable asap, see Bodhi: https://bodhi.fedoraproject.org/updates/FEDORA-2020-c872c5222e

**Comment by marusak** [comment]
Thanks @ondrejbudai ! Let's then wait for a day or so and then re-test.

**Comment by martinpitt** [comment]
Unblocking -- the failure [happens on the current image](https://github.com/osbuild/cockpit-composer/pull/1013) as well, presumably because dnf always installs the latest packages anyway in vm.install.

**Pull request merged**
