### PR TITLE
images: add python3-pcp to Debian images

### PR DESCRIPTION
**Pull request by jelly**
* [x] image-refresh ubuntu-stable
 * [x] image-refresh ubuntu-2204
 * [x] image-refresh ubuntu-2404

---

Needed for https://github.com/cockpit-project/cockpit/pull/20049

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20240911-130907

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-stable-b3cc5e28-20240911-125428/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-2204-b3cc5e28-20240911-130914/log.html

**Comment by cockpituous** [comment]
image-refresh ubuntu-2404 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2404-20240911-133250

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-2404-b3cc5e28-20240911-131712/log.html

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-2204-b3cc5e28-20240911-144557/log.html

**Review by mvollmer — APPROVED** [review]
Nice!

**Pull request merged**
