### PR TITLE
Image refresh for fedora-32

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-32
 * [x] image-refresh fedora-32
 * [x] Avoid podman 2.0.3 in tests: https://github.com/cockpit-project/cockpit-podman/pull/478

### CODE REVIEW

**Comment by martinpitt** [comment]
This [breaks podman all over the place](https://logs.cockpit-project.org/logs/pull-1109-20200731-031016-0aaacac0-fedora-32-cockpit-project-cockpit-podman/log.html#7) because of https://github.com/containers/podman/issues/7078 ; unfortunately we missed to -1 it in bodhi. I pinged the upstream issue for making a new release.

**Comment by marusak** [comment]
Yeah, `podman-2.0.3` is in this refresh. That won't work out. It is fixed in master so hopefully soon?

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit-podman/pull/478 to avoid the podman 2.0.3 breakage.

**Comment by martinpitt** [comment]
Still [some podman flakes](https://logs.cockpit-project.org/logs/pull-1109-20200803-101841-0aaacac0-fedora-32-cockpit-project-cockpit-podman/log.html), retrying for comparison. As  we install podman from updates-testing now, it should behave exactly the same as in https://github.com/cockpit-project/cockpit-podman/pull/478

**Pull request merged**
