### PR TITLE
Image refresh for fedora-35

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-35
 * [x] image-refresh fedora-35

### CODE REVIEW

**Comment by jelly** [comment]
```
Trying to pull quay.io/bitnami/nginx:latest...
Error: initializing source docker://quay.io/bitnami/nginx:latest: reading manifest latest in quay.io/bitnami/nginx: unauthorized: access to the requested resource is not authorized
```

Something wrong on our infra? Re-trying!

**Comment by martinpitt** [comment]
[temporary quay.io trouble](https://logs.cockpit-project.org/logs/pull-3261-20220421-074834-46887286-fedora-coreos-cockpit-project-cockpit-ostree/log.html). @jelly is looking into fixing this on the fcos image, but that doesn't need to block this image refresh.

**Comment by martinpitt** [comment]
@jelly : Ah no -- https://quay.io/repository/bitnami/nginx simply disappeared, so we need some other test webserver for cockpit-ostree. https://quay.io/repository/jitesoft/nginx looks reasonably maintained, but I'm sure there's some others.

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit-ostree/pull/247 landed, which should fix the ostree failure. @jelly, please rebase this and the fcos refresh to get a clean test run. Thanks!

**Review by jelly — APPROVED** [review]

**Pull request merged**
