### PR TITLE
Image refresh for fedora-40

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-40
 * [x] image-refresh fedora-40
 * [ ] https://github.com/cockpit-project/cockpit/issues/21301

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-40 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-40-20241123-230137

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-40-bbd1993b-20241123-224040/log.html

**Comment by martinpitt** [comment]
Phew, this is a big one. There's the python crashes from #21301, [files needs a pixel update](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7126-31b95e35-20241123-230312-fedora-40-cockpit-project-cockpit-files/log.html) due to the new cockpit version enabling "open in terminal", sub-man causes an oops in the same manner as in #7123, and composer failed on an internal npm mirror failure (retried that one).

**Comment by martinpitt** [comment]
Closing in favor of #7140

**Pull request closed without merging**
