### PR TITLE
services: candlepin now uses java 11

### LINKED ISSUE #1322: Image refresh for services
Image refresh for services
 * [ ] FAIL: image-refresh services

### PR DESCRIPTION
**Pull request by marusak**
Fixes #1322

 * [x] image-refresh services

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-hh7hv.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-1340-20201026-120909/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-1340-20201026-120909/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1340-20201026-120909/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-hh7hv.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-1340-20201026-135656/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-1340-20201026-135656/

**Comment by marusak** [comment]
Still fails with ` Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.`

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-1340-20201026-144141/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1340-20201026-144141/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-1340-20201026-195858/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1340-20201026-195858/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-1340-20201026-203636/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1340-20201026-203636/

**Comment by marusak** [comment]
hey @wolfdale, I saw that you bumped java in [candlepin](https://github.com/candlepin/ansible-role-candlepin/pull/14). Now it fails to build for us. Do you have some idea what am I missing? Thanks!

Here is [log](https://logs.cockpit-project.org/logs/image-refresh-1340-20201026-203636/log), last lines are the ones where stuff is happening.

**Comment by wolfdale** [comment]
Hey @marusak, Yes we bumped Candlepin to use Java 11 from v3.2.0 & onwards. 
Looking at the error logs here, It seems like Java 11 dependency is missing as ``services.setup`` script is checking out older version of ansible-role-candlepin on this [line.](https://github.com/cockpit-project/bots/blob/6ba20a2127555e963308d0743343eecc2dce2bc2/images/scripts/services.setup#L144) Could this be a possible issue ?

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-1340-20201027-102121/

**Comment by marusak** [comment]
> Looking at the error logs here, It seems like Java 11 dependency is missing as services.setup script is checking out older version of ansible-role-candlepin on this line. Could this be a possible issue ?

oh good point, totally missed that. Thank you!

**Comment by cockpituous** [comment]
image-refresh services done: https://github.com/cockpituous/bots/commits/image-refresh-services-20201027-110404

**Comment by marusak** [comment]
All failures are unrelated to service image.

**Review by Gundersanne — APPROVED** [review]

**Pull request merged**
