### PR TITLE
Image refresh for rhel-8-6

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-6
 * [x] image-refresh rhel-8-6
 * ~https://github.com/cockpit-project/cockpit/pull/16825~

### CODE REVIEW

**Comment by martinpitt** [comment]
[several regressions](https://logs.cockpit-project.org/logs/pull-2794-20220111-055828-471f5392-rhel-8-6-cockpit-project-cockpit/log.html)

**Comment by skobyda** [comment]
It seems that this change https://fedoraproject.org/wiki/Changes/EnableSysctlPingGroupRange now also got into rhel-8-6 now and it breaks pinger tets. This degraded ping utility and there is still an unresolved bugzilla for that: https://bugzilla.redhat.com/show_bug.cgi?id=1840190
It causes ping operation to fail ping: socket: Operation not permitted for non-root users. It seems they disabled it for a reson to make ping work for podman.

One way to work around it is to use sysctl -w net.ipv4.ping_group_range="0 1000".

**Comment by martinpitt** [comment]
@skobyda: Let's just track the ping regression as a naughty. I'll look at the SELinux ldap related errors now, and work on a Cockpit PR.

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/16825 to take care of the unexpected message in check-system-s4u and TestIPA. The TestAD failures are unrelated, and they happen before cockpit even gets into play. These smell like a regression in the new sssd version, the only [plausible changed package](https://logs.cockpit-project.org/logs/image-refresh-2794-20220111-022323/log). I'll investigate some more, but this smells like bugzilla+naughty.

**Comment by martinpitt** [comment]
About the [Active Directory](https://logs.cockpit-project.org/logs/pull-2794-20220111-055828-471f5392-rhel-8-6-cockpit-project-cockpit/log.html#258-2) failures.

Start with the old image, break right at the start of the test. Then update sssd:
```
echo 'nameserver 172.27.0.3' > /etc//resolv.conf
dnf update -y sssd-nfs-idmap libsss_autofs libsss_sudo python3-sss-murmur
sed -i '/nameserver 172.27/d' /etc/resolv.conf
```

then continue the test.

/var/log/sssd/sssd_cockpit.lan.log has an interesting log:
```
2022-01-12 10:22:33): [be[cockpit.lan]] [be_ptask_done] (0x0040): Task [Subdomains Refresh]: failed with [1432158212]: SSSD is offline
   *  ... skipping repetitive backtrace ...
(2022-01-12 10:22:33): [be[cockpit.lan]] [ad_subdomains_refresh_connect_done] (0x0020): [RID#1] Unable to connect to LDAP [11]: Resource temporarily unavailable
   *  ... skipping repetitive backtrace ...
(2022-01-12 10:22:33): [be[cockpit.lan]] [sbus_issue_request_done] (0x0040): sssd.dataprovider.getAccountInfo: Error [1432158212]: SSSD is offline
********************** PREVIOUS MESSAGE WAS TRIGGERED BY THE FOLLOWING BACKTRACE:
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [ad_subdomains_refresh_connect_done] (0x0080): [RID#1] No AD server is available, cannot get the subdomain list while offline
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [dp_req_done] (0x0400): [RID#1] DP Request [Subdomains #1]: Request handler finished [0]: Success
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [_dp_req_recv] (0x0400): [RID#1] DP Request [Subdomains #1]: Receiving request data.
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [dp_req_destructor] (0x0400): [RID#1] DP Request [Subdomains #1]: Request removed.
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [dp_req_destructor] (0x0400): [RID#1] Number of active DP request: 0
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [dp_req_reply_std] (0x1000): [RID#1] DP Request [Subdomains #1]: Returning [Provider is Offline]: 1,1432158212,Offline
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [sbus_issue_request_done] (0x0400): sssd.dataprovider.getDomains: Success
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [sbus_issue_request_done] (0x0400): sssd.dataprovider.getDomains: Success
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [sdap_id_release_conn_data] (0x4000): Releasing unused connection with fd [-1]
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [sbus_dispatch] (0x4000): Dispatching.
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [sbus_dispatch] (0x4000): Dispatching.
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [sbus_dispatch] (0x4000): Dispatching.
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [sbus_dispatch] (0x4000): Dispatching.
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [sbus_method_handler] (0x2000): Received D-Bus method sssd.dataprovider.getAccountInfo on /sssd
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [sbus_senders_lookup] (0x2000): Looking for identity of sender [sssd.nss]
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [dp_get_account_info_send] (0x0200): Got request for [0x1][BE_REQ_USER][name=administrator@cockpit.lan]
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [dp_attach_req] (0x0400): [RID#2] DP Request [Account #2]: REQ_TRACE: New request. [sssd.nss CID #1] Flags [0x0001].
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [dp_attach_req] (0x0400): [RID#2] [CID #1] Backend is offline! Using cached data if available
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [dp_attach_req] (0x0400): [RID#2] Number of active DP request: 1
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [sss_domain_get_state] (0x1000): [RID#2] Domain cockpit.lan is Active
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [_dp_req_recv] (0x0400): DP Request [Account #2]: Receiving request data.
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [dp_req_destructor] (0x0400): DP Request [Account #2]: Request removed.
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [dp_req_destructor] (0x0400): Number of active DP request: 0
   *  (2022-01-12 10:22:33): [be[cockpit.lan]] [sbus_issue_request_done] (0x0040): sssd.dataprovider.getAccountInfo: Error [1432158212]: SSSD is offline
```

and I am not getting that on the old image.

This agrees:
```
# sssctl domain-status cockpit.lan
Online status: Offline

Active servers:
AD Global Catalog: not connected
AD Domain Controller: f0.cockpit.lan

Discovered AD Global Catalog servers:
None so far.
Discovered AD Domain Controller servers:
- f0.cockpit.lan
```

In `journalctl` I see that sssd keeps starting and stopping.

**Comment by martinpitt** [comment]
I filed https://bugzilla.redhat.com/show_bug.cgi?id=2039892 . Needs a known issue and a set of naughty patterns now.

**Comment by marusak** [comment]
> I filed https://bugzilla.redhat.com/show_bug.cgi?id=2039892 . Needs a known issue and a set of naughty patterns now.

@skobyda want to finish this up or should I take over?

**Comment by martinpitt** [comment]
I pushed a metric ton of naughties now.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
