### PR TITLE
Fix centos-10 image refresh

### LINKED ISSUE #6654: Image refresh for centos-10
Image refresh for centos-10
 * [ ] FAIL: image-refresh centos-10

### PR DESCRIPTION
**Pull request by martinpitt**
The download.f.o redirection is way too unreliable. Image builds on our CI keep running into 404s. Move to `metalink=` like a standard Fedora system has.

Fixes #6654

---

We've been plagued for months with [image build failures like this](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-8d00cc7a-20240808-041856/log.html).

 * [x] image-refresh centos-10
 * [x] image-refresh rhel-10-0
 * [x] https://github.com/cockpit-project/cockpit/pull/20854

### CODE REVIEW

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-746d5823-20240808-051710/log.html

**Comment by cockpituous** [comment]
image-refresh rhel-10-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-10-0-20240808-054249

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-10-0-746d5823-20240808-052719/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-746d5823-20240808-054556/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-746d5823-20240808-060622/log.html

**Comment by martinpitt** [comment]
I can locally reproduce the boot failure. It's that dreaded thing again:

> [**    ] Job NetworkManager-wait-online.service/start running (17s / no limit)

Our setup script still assumes eth0/eth1, but RHEL 10 recently switched predictable network interface names on by default. So the current image has `ens14` and `ens15`.

Fixed.

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240808-082051

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-e6641593-20240808-080329/log.html

**Comment by cockpituous** [comment]
image-refresh rhel-10-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-10-0-20240808-083617

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-10-0-e6641593-20240808-082100/log.html

**Comment by martinpitt** [comment]
Meh, and now after 3 weeks of broken images we of course get a whole host of regressions in CentOS 10. That's a lot of piloting work..

**Comment by mvollmer** [comment]
- Centos 10 and RHEL 10 moved to valkey, have to update cockpit tests. 
- Error: [Errno 13] Permission denied: '/etc/firewalld/zones/public.xml' -> naughty
- ...

**Comment by mvollmer** [comment]
> * Error: [Errno 13] Permission denied: '/etc/firewalld/zones/public.xml' -> naughty

We were actually missing the newest packages. The `s/production/development/` replacement stopped working.

**Comment by martinpitt** [comment]
Interesting! The [version updates in the build log](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-e6641593-20240808-080329/log.html) seemed quite plausible and current. But this is nicer indeed. Thanks!

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240808-110818

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-8eed4511-20240808-105201/log.html

**Comment by mvollmer** [comment]
> Interesting! The [version updates in the build log](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-e6641593-20240808-080329/log.html) seemed quite plausible and current. But this is nicer indeed. Thanks!

I have of course no idea who these different repositories relate... I was looking for firewalld 2.2.1 which fixes that annoying "permission denied" bug.

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240808-122544

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-196156ed-20240808-120829/log.html

**Comment by cockpituous** [comment]
image-refresh rhel-10-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-10-0-20240808-124153

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-10-0-196156ed-20240808-122553/log.html

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit/pull/20854 landed, so let's rebase and it should go green now.

**Comment by martinpitt** [comment]
@mvollmer I'm happy with your changes. It's my PR, so you need to approve.

**Review by mvollmer — APPROVED** [review]
Let's go!

**Pull request merged**
