### PR TITLE
Image refresh for ubuntu-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for ubuntu-stable
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by marusak** [comment]
[some failures](https://logs.cockpit-project.org/logs/pull-1327-20201023-094215-2e809c52-ubuntu-stable-cockpit-project-cockpit/log.html) lets compare.

**Comment by marusak** [comment]
testIPA failed again

**Comment by marusak** [comment]
```
CalledProcessError(Command ['/bin/systemctl', 'restart', 'chrony.service'] returned non-zero exit status 5: 'Failed to restart chrony.service: Unit chrony.service not found.\n')
The ipa-client-install command failed. See /var/log/ipaclient-install.log for more info
```

```
$ cat /var/log/ipaclient-install.log
T12:47:39Z WARNING Option --force-ntpd has been deprecated and will be removed in a future release.
2020-10-27T12:47:39Z DEBUG ipa-client-install was invoked with arguments [] and options: {'unattended': True, 'principal': 'admin', 'prompt_password': True, 'on_master': False, 'ca_cert_files': None, 'force': False, 'configure_firefox': False, 'firefox_dir': None, 'keytab': None, 'mkhomedir': True, 'force_join': True, 'ntp_servers': None, 'ntp_pool': None, 'no_ntp': False, 'force_ntpd': True, 'nisdomain': None, 'no_nisdomain': False, 'ssh_trust_dns': False, 'no_ssh': False, 'no_sshd': False, 'no_sudo': False, 'no_dns_sshfp': False, 'kinit_attempts': None, 'request_cert': False, 'ip_addresses': None, 'all_ip_addresses': False, 'fixed_primary': False, 'permit': False, 'enable_dns_updates': True, 'no_krb5_offline_passwords': False, 'preserve_sssd': False, 'automount_location': None, 'domain_name': 'cockpit.lan', 'servers': None, 'realm_name': 'COCKPIT.LAN', 'host_name': None, 'verbose': False, 'quiet': False, 'log_file': None, 'uninstall': False}
2020-10-27T12:47:39Z DEBUG IPA version 4.8.6
2020-10-27T12:47:39Z DEBUG Loading Index file from '/var/lib/ipa-client/sysrestore/sysrestore.index'
2020-10-27T12:47:39Z DEBUG Starting external process
2020-10-27T12:47:39Z DEBUG args=['/usr/sbin/selinuxenabled']
2020-10-27T12:47:39Z DEBUG Process finished, return code=1
2020-10-27T12:47:39Z DEBUG stdout=
2020-10-27T12:47:39Z DEBUG stderr=
2020-10-27T12:47:39Z DEBUG Deleting invalid keytab: '/etc/krb5.keytab'.
2020-10-27T12:47:39Z DEBUG [IPA Discovery]
2020-10-27T12:47:39Z DEBUG Starting IPA discovery with domain=cockpit.lan, servers=None, hostname=x0.cockpit.lan
2020-10-27T12:47:39Z DEBUG Search for LDAP SRV record in cockpit.lan
2020-10-27T12:47:39Z DEBUG Search DNS for SRV record of _ldap._tcp.cockpit.lan
2020-10-27T12:47:39Z DEBUG DNS record found: 0 100 389 f0.cockpit.lan.
2020-10-27T12:47:39Z DEBUG [Kerberos realm search]
2020-10-27T12:47:39Z DEBUG Kerberos realm forced
2020-10-27T12:47:39Z DEBUG Search DNS for SRV record of _kerberos._udp.cockpit.lan
2020-10-27T12:47:39Z DEBUG DNS record found: 0 100 88 f0.cockpit.lan.
2020-10-27T12:47:39Z DEBUG [LDAP server check]
2020-10-27T12:47:39Z DEBUG Verifying that f0.cockpit.lan (realm COCKPIT.LAN) is an IPA server
2020-10-27T12:47:39Z DEBUG Init LDAP connection to: ldap://f0.cockpit.lan:389
2020-10-27T12:47:39Z DEBUG Search LDAP server for IPA base DN
2020-10-27T12:47:39Z DEBUG Check if naming context 'dc=cockpit,dc=lan' is for IPA
2020-10-27T12:47:39Z DEBUG Naming context 'dc=cockpit,dc=lan' is a valid IPA context
2020-10-27T12:47:39Z DEBUG Search for (objectClass=krbRealmContainer) in dc=cockpit,dc=lan (sub)
2020-10-27T12:47:39Z DEBUG Found: cn=COCKPIT.LAN,cn=kerberos,dc=cockpit,dc=lan
2020-10-27T12:47:39Z DEBUG Discovery result: Success; server=f0.cockpit.lan, domain=cockpit.lan, kdc=f0.cockpit.lan, basedn=dc=cockpit,dc=lan
2020-10-27T12:47:39Z DEBUG Validated servers: f0.cockpit.lan
2020-10-27T12:47:39Z DEBUG will use discovered domain: cockpit.lan
2020-10-27T12:47:39Z DEBUG Start searching for LDAP SRV record in "cockpit.lan" (Validating DNS Discovery) and its sub-domains
2020-10-27T12:47:39Z DEBUG Search DNS for SRV record of _ldap._tcp.cockpit.lan
2020-10-27T12:47:39Z DEBUG DNS record found: 0 100 389 f0.cockpit.lan.
2020-10-27T12:47:39Z DEBUG DNS validated, enabling discovery
2020-10-27T12:47:39Z DEBUG will use discovered server: f0.cockpit.lan
2020-10-27T12:47:39Z INFO Discovery was successful!
2020-10-27T12:47:39Z DEBUG will use discovered realm: COCKPIT.LAN
2020-10-27T12:47:39Z DEBUG will use discovered basedn: dc=cockpit,dc=lan
2020-10-27T12:47:39Z INFO Client hostname: x0.cockpit.lan
2020-10-27T12:47:39Z DEBUG Hostname source: Machine's FQDN
2020-10-27T12:47:39Z INFO Realm: COCKPIT.LAN
2020-10-27T12:47:39Z DEBUG Realm source: Discovered from LDAP DNS records in f0.cockpit.lan
2020-10-27T12:47:39Z INFO DNS Domain: cockpit.lan
2020-10-27T12:47:39Z DEBUG DNS Domain source: Discovered LDAP SRV records from cockpit.lan
2020-10-27T12:47:39Z INFO IPA Server: f0.cockpit.lan
2020-10-27T12:47:39Z DEBUG IPA Server source: Discovered from LDAP DNS records in f0.cockpit.lan
2020-10-27T12:47:39Z INFO BaseDN: dc=cockpit,dc=lan
2020-10-27T12:47:39Z DEBUG BaseDN source: From IPA server ldap://f0.cockpit.lan:389
2020-10-27T12:47:39Z DEBUG Loading Index file from '/var/lib/ipa-client/sysrestore/sysrestore.index'
2020-10-27T12:47:39Z DEBUG Loading StateFile from '/var/lib/ipa-client/sysrestore/sysrestore.state'
2020-10-27T12:47:39Z DEBUG Starting external process
2020-10-27T12:47:39Z DEBUG args=['/usr/sbin/ipa-rmkeytab', '-k', '/etc/krb5.keytab', '-r', 'COCKPIT.LAN']
2020-10-27T12:47:39Z DEBUG Process finished, return code=3
2020-10-27T12:47:39Z DEBUG stdout=
2020-10-27T12:47:39Z DEBUG stderr=Failed to open keytab '/etc/krb5.keytab': No such file or directory

2020-10-27T12:47:39Z DEBUG Starting external process
2020-10-27T12:47:39Z DEBUG args=['/usr/sbin/service', 'ntp', 'status', '']
2020-10-27T12:47:39Z DEBUG Process finished, return code=4
2020-10-27T12:47:39Z DEBUG stdout=
2020-10-27T12:47:39Z DEBUG stderr=Unit ntp.service could not be found.

2020-10-27T12:47:39Z DEBUG Loading StateFile from '/var/lib/ipa-client/sysrestore/sysrestore.state'
2020-10-27T12:47:39Z DEBUG Saving StateFile to '/var/lib/ipa-client/sysrestore/sysrestore.state'
2020-10-27T12:47:39Z DEBUG Loading StateFile from '/var/lib/ipa-client/sysrestore/sysrestore.state'
2020-10-27T12:47:39Z DEBUG Saving StateFile to '/var/lib/ipa-client/sysrestore/sysrestore.state'
2020-10-27T12:47:39Z DEBUG Search DNS for SRV record of _ntp._udp.cockpit.lan
2020-10-27T12:47:39Z DEBUG DNS record not found: NXDOMAIN
2020-10-27T12:47:39Z INFO Synchronizing time
2020-10-27T12:47:39Z WARNING No SRV records of NTP servers found and no NTP server or pool address was provided.
2020-10-27T12:47:39Z DEBUG Starting external process
2020-10-27T12:47:39Z DEBUG args=['/bin/systemctl', 'enable', 'chrony.service']
2020-10-27T12:47:39Z DEBUG Process finished, return code=1
2020-10-27T12:47:39Z DEBUG stdout=
2020-10-27T12:47:39Z DEBUG stderr=Failed to enable unit: Unit file chrony.service does not exist.

2020-10-27T12:47:39Z DEBUG Starting external process
2020-10-27T12:47:39Z DEBUG args=['/bin/systemctl', 'restart', 'chrony.service']
2020-10-27T12:47:39Z DEBUG Process finished, return code=5
2020-10-27T12:47:39Z DEBUG stdout=
2020-10-27T12:47:39Z DEBUG stderr=Failed to restart chrony.service: Unit chrony.service not found.

2020-10-27T12:47:39Z DEBUG   File "/usr/lib/python3/dist-packages/ipapython/admintool.py", line 179, in execute
    return_value = self.run()
  File "/usr/lib/python3/dist-packages/ipapython/install/cli.py", line 340, in run
    return cfgr.run()
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 360, in run
    return self.execute()
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 386, in execute
    for rval in self._executor():
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3/dist-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 655, in _configure
    next(executor)
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 518, in _handle_exception
    self.__parent._handle_exception(exc_info)
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 515, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3/dist-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3/dist-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3/dist-packages/ipapython/install/common.py", line 65, in _install
    for unused in self._installer(self.parent):
  File "/usr/lib/python3/dist-packages/ipaclient/install/client.py", line 3818, in main
    install(self)
  File "/usr/lib/python3/dist-packages/ipaclient/install/client.py", line 2531, in install
    _install(options)
  File "/usr/lib/python3/dist-packages/ipaclient/install/client.py", line 2576, in _install
    sync_time(options.ntp_servers, options.ntp_pool, fstore, statestore)
  File "/usr/lib/python3/dist-packages/ipaclient/install/client.py", line 2500, in sync_time
    return timeconf.sync_chrony()
  File "/usr/lib/python3/dist-packages/ipaclient/install/timeconf.py", line 83, in sync_chrony
    services.knownservices.chronyd.restart()
  File "/usr/lib/python3/dist-packages/ipaplatform/base/services.py", line 341, in restart
    self._restart_base(instance_name, "restart",
  File "/usr/lib/python3/dist-packages/ipaplatform/base/services.py", line 326, in _restart_base
    ipautil.run([paths.SYSTEMCTL, operation,
  File "/usr/lib/python3/dist-packages/ipapython/ipautil.py", line 597, in run
    raise CalledProcessError(

2020-10-27T12:47:39Z DEBUG The ipa-client-install command failed, exception: CalledProcessError: CalledProcessError(Command ['/bin/systemctl', 'restart', 'chrony.service'] returned non-zero exit status 5: 'Failed to restart chrony.service: Unit chrony.service not found.\n')
2020-10-27T12:47:39Z ERROR CalledProcessError(Command ['/bin/systemctl', 'restart', 'chrony.service'] returned non-zero exit status 5: 'Failed to restart chrony.service: Unit chrony.service not found.\n')
```

**Comment by martinpitt** [comment]
@marusak: Hmm, that sounds like https://launchpad.net/bugs/1890786 and we have a hack for it:
```
        # HACK: ipa-client-install fails on restarting absent chronyd.service: https://launchpad.net/bugs/1890786
        if self.machine.image in ["ubuntu-2004", "ubuntu-stable"]:
            self.write_file("/run/systemd/system/chronyd.service", """
[Service]
Type=oneshot
ExecStart=/bin/true
""")
            self.machine.execute("ln -s /bin/true /usr/bin/chronyc")
```

The Launchpad bug got fixed, and it now expects the service to be "chrony.service", not chrony*d*. So this needs adjustment, and presumably chrony is still not installed?

**Comment by marusak** [comment]
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1760235.html

**Comment by marusak** [comment]
Sent https://github.com/cockpit-project/cockpit/pull/14817 to fix it

**Review by marusak — APPROVED** [review]

**Pull request merged**
