### PR TITLE
Image refresh for fedora-34

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-34
 * [x] image-refresh fedora-34

### CODE REVIEW

**Comment by martinpitt** [comment]
First run [failed](https://logs.cockpit-project.org/logs/pull-2784-20220110-024544-7afed88e-fedora-coreos-cockpit-project-cockpit/log.html#152) on a new SELinux issue. [retry failed as well](https://logs.cockpit-project.org/logs/pull-2784-20220110-063907-7afed88e-fedora-coreos-cockpit-project-cockpit/log.html#241), so this is real.

**Comment by martinpitt** [comment]
Ah, this isn't new -- happens on current image as well, like [here](https://logs.cockpit-project.org/logs/pull-16798-20220110-064948-be591291-fedora-coreos/log.html#232) in https://github.com/cockpit-project/cockpit/pull/16798

**Comment by martinpitt** [comment]
I added the naughty here, even though it's not strictly due to this image refresh. But with that it's self-validating.

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
