### PR TITLE
fedora.setup: stop relying on updates-archive

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
We can ensure we get the same versions of selinux-policy and friends
inside and outside of the container by simply downloading them with dnf
and installing them from the local .rpm files.

That lets us skip using the updates-archive repository which isn't yet
available for Fedora 35.

This is what we're already doing on rhel.

Some test builds:

 * [x] image-refresh fedora-34
 * [x] image-refresh fedora-33
 * [x] image-refresh fedora-testing

Fix for setTroubleShoot:

 * [x] https://github.com/cockpit-project/cockpit/pull/16236
 * [x] https://github.com/cockpit-project/cockpit/pull/16237
 * [x] https://github.com/cockpit-project/cockpit/pull/16238

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-2313-20210816-133838/

**Comment by cockpituous** [comment]
image-refresh fedora-34 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-34-20210816-135858

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-2313-20210816-135959/

**Comment by cockpituous** [comment]
image-refresh fedora-33 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-33-20210816-141818

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-2313-20210816-140606/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20210816-142727

**Comment by allisonkarlitskaya** [comment]
So all of the images got far enough that I'd be comfortable saying that the selinux-policy trickery is working just fine.  There are some other issues, though.

That gives us two possible approaches:
 1. land the selinux-policy patch without the image refreshes
 2. try to fix up the other issues and land all three image refreshes while we're at it.

**Comment by marusak** [comment]
> There are some other issues, though.

What issues?

> try to fix up the other issues and land all three image refreshes while we're at it.

I would prefer this one.

**Comment by allisonkarlitskaya** [comment]
> What issues?

See very many broken tests.

**Comment by marusak** [comment]
Seems that only `TestSelinux.testTroubleshootAlerts` is broken. It is also broken in rhel-9 in different PR, this needs to be adjusted to a new version anyway.
Please ignore `TestCustom.testUserAccount ` in composer tests, this one is busted.

**Review by mvollmer — APPROVED** [review]

**Comment by allisonkarlitskaya** [comment]
Let's wait for the cockpit fix to land, and rerun the tests.

**Pull request merged**
