### PR TITLE
images: Fix candlepin container host name

### PR DESCRIPTION
**Pull request by martinpitt**
Don't use a private hostname like "91aaf0c7ea04" for the candlepin
container, but use the host's "services.cockpit.lan". This avoids
breaking TLS host name validation and thus the
subscription-manager/Insights tests in cockpit's rhel-7.9 branch.

 * [x] image-refresh services

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-1816-20210318-065353/

**Comment by cockpituous** [comment]
image-refresh services done: https://github.com/cockpit-project/bots/commits/image-refresh-services-20210318-072727

**Comment by martinpitt** [comment]
cockpit rhel-7.9 branch is known broken, also with the previous image. This is being fixed in https://github.com/cockpit-project/cockpit/pull/15549 . Ready for review.

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
