### PR TITLE
Image refresh for fedora-38

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-38
 * [x] image-refresh fedora-38

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-38-20230918-230808.log

**Review by jelly — APPROVED** [review]

**Comment by jelly** [comment]
Cockpit issues seem tracer related?

image

**Comment by jelly** [comment]
I've managed to get our tests green by running:

```
./bots/vm-run -m fedora-38
dnf remove dnf5
```

I am not sure why we suddenly have added `dnf5` but it breaks.

**Comment by jelly** [comment]
@martinpitt this is a [tracer bug](https://github.com/FrostyX/tracer/issues/204). We can avoid installing dnf5 by disabling weakdepends for the `dnf install` of `mock`. Shall we go that way or a naughty? I would prefer not installing `dnf5` yet as it's Fedora-38, so should not really be used yet except for testing I suppose.

**Comment by martinpitt** [comment]
@jelly Fine for me to drop dnf5, as it'll be fixed eventually. Thanks!

**Comment by jelly** [comment]
> @jelly Fine for me to drop dnf5, as it'll be fixed eventually. Thanks!

tracer was moved to stable, so I opt to just refresh the image and I suppose help out with finding the dnf5 related bugs :)

**Comment by jelly** [comment]
Closing to let the bots refresh.

**Pull request closed without merging**
