### PR TITLE
Image refresh for fedora-33

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-33
 * [x] image-refresh fedora-33

### CODE REVIEW

**Comment by skobyda** [comment]
Looking at `https://logs.cockpit-project.org/logs/pull-1834-20210323-090932-0f28e52f-fedora-33-cockpit-project-cockpit/log.html#242-2`, it seems like a common failure. Retrigerring.

**Comment by martinpitt** [comment]
`TestStorageResize.testGrowShrinkEncryptedHelp` is broken; regression, needswork.

**Comment by skobyda** [comment]
So I tried to debug it a bit and found the problem is that the after resizing the volume (clicking on the "Grow" button which triggers lvol_grow at pkg/storaged/lvol-tabs.jsx), the volume gets unmounted automatically. This unmount happens on fedora-testing and fedora-33 but doesn't happen on fedora-34 for example.
I got lost futher and could not find the problem any deeper. Perhaps @mvollmer know what could be the bug there? Is it normal that sometimes volume gets unmounted after resizing it? If so, then perhaps test needs to be changed to account for that. If not then I guess the problem is with resizing function.

**Comment by marusak** [comment]
@skobyda you triggered only two contexts here. There were 13 more to be triggered. Please use `image:fedora-33` pattern on such PRs. Thanks!

**Review by martinpitt — APPROVED** [review]
All green, nice! Thanks @skobyda !

**Pull request merged**
