### PR TITLE
Image refresh for centos-8-stream

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-8-stream
 * [x] image-refresh centos-8-stream
 * [x] https://github.com/cockpit-project/starter-kit/pull/648

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/centos-8-stream-20230509-225959.log

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20230509-230756

**Comment by cockpituous** [comment]
Completed. Log: Error accessing /repos/cockpit-project/bots/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value":4744,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}

**Comment by martinpitt** [comment]
starter-kit is currently broken, see #4746

**Pull request merged**
