### PR TITLE
Image refresh for rhel-9-4

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-4
 * [x] image-refresh rhel-9-4

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-9-4 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-4-20240617-225603

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-4-8166af54-20240617-223735/log.html

**Comment by martinpitt** [comment]
[This failure repeats](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6517-6a284fe4-20240618-061512-rhel-9-4-storage-cockpit-project-cockpit/log.html#7-2). @mvollmer -- I have pilot overflow, do you have time to take a look?

**Comment by martinpitt** [comment]
Wait, there's no removed/added and only a trivial (mock-core-config) change. Let's re-re-retry.

**Comment by martinpitt** [comment]
OK, 5th time is the charm. What an annoying flake..

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
