### PR TITLE
Image refresh for fedora-34

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-34
 * [x] image-refresh fedora-34
 * [ ] Blocked on https://github.com/cockpit-project/bots/issues/2434

### CODE REVIEW

**Comment by martinpitt** [comment]
[fedora-coreos failure](https://logs.cockpit-project.org/logs/pull-2400-20210910-023054-f9a640d4-fedora-coreos-cockpit-project-cockpit/log.html#12-2) looks like our coreos image needs to be refreshed first?
```
error: Could not depsolve transaction; 1 problem detected:
 Problem: package cockpit-ws-252.51.g46751fa44-1.wip.fc34.x86_64 requires (selinux-policy >= 34.18-1.fc34 if selinux-policy-targeted), but none of the providers can be installed
  - conflicting requests
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-connection", line 73, in testBasic
    self.ostree_setup_ws()
  File "/work/bots/make-checkout-workdir/test/verify/check-connection", line 49, in ostree_setup_ws
    m.execute("rpm-ostree install --cache-only /var/tmp/build-results/cockpit-ws-*.rpm")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 359, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'rpm-ostree install --cache-only /var/tmp/build-results/cockpit-ws-*.rpm' returned non-zero exit status 1.
Wrote screenshot to TestConnection-testBasic-fedora-coreos-127.0.0.2-2401-FAIL.png
```

**Comment by KKoukiou** [comment]
> [fedora-coreos failure](https://logs.cockpit-project.org/logs/pull-2400-20210910-023054-f9a640d4-fedora-coreos-cockpit-project-cockpit/log.html#12-2) looks like our coreos image needs to be refreshed first?
> 
> ```
> error: Could not depsolve transaction; 1 problem detected:
>  Problem: package cockpit-ws-252.51.g46751fa44-1.wip.fc34.x86_64 requires (selinux-policy >= 34.18-1.fc34 if selinux-policy-targeted), but none of the providers can be installed
>   - conflicting requests
> Traceback (most recent call last):
>   File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
>     method()
>   File "/work/bots/make-checkout-workdir/test/verify/check-connection", line 73, in testBasic
>     self.ostree_setup_ws()
>   File "/work/bots/make-checkout-workdir/test/verify/check-connection", line 49, in ostree_setup_ws
>     m.execute("rpm-ostree install --cache-only /var/tmp/build-results/cockpit-ws-*.rpm")
>   File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 359, in execute
>     raise subprocess.CalledProcessError(proc.returncode, command, output=output)
> subprocess.CalledProcessError: Command 'rpm-ostree install --cache-only /var/tmp/build-results/cockpit-ws-*.rpm' returned non-zero exit status 1.
> Wrote screenshot to TestConnection-testBasic-fedora-coreos-127.0.0.2-2401-FAIL.png
> ```

Indeed selinux-policy got updated to the required version yesterday https://bodhi.fedoraproject.org/updates/FEDORA-2021-ad4033a9b0 - when also the fedora-coreos image update happened.

**Comment by martinpitt** [comment]
https://builds.coreos.fedoraproject.org/streams/testing.json finally got a new build yesterday, so it's worth trying this again. I requested a refresh in #2434

**Comment by martinpitt** [comment]
fcos refresh landed, so let's retry this.

**Pull request closed without merging**
