### PR TITLE
Image refresh for fedora-31

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-31
 * [x] image-refresh fedora-31

### CODE REVIEW

**Comment by martinpitt** [comment]
The [lorax tests](https://logs.cockpit-project.org/logs/pull-771-20200420-152526-c523f840-fedora-31-live-iso-weldr-lorax/log.html) have a weird failure:
```
Errors during downloading metadata for repository 'fedora-modular':
  - Curl error (6): Couldn't resolve host name for http://download.example/pub/fedora/linux/releases/31/Modular/x86_64/os/repodata/repomd.xml [Could not resolve host: download.example]
Error: Failed to download metadata for repo 'fedora-modular': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

where does the `.example` domain come from?

**Comment by marusak** [comment]
Just dowloading this image and checking for example:
```
# grep -r example /etc/yum.repos.d/
/etc/yum.repos.d/fedora-modular.repo:#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Modular/$basearch/os/
/etc/yum.repos.d/fedora-modular.repo:#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Modular/$basearch/debug/tree/
/etc/yum.repos.d/fedora-modular.repo:#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Modular/source/tree/
/etc/yum.repos.d/fedora-updates-modular.repo:#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Modular/$basearch/
/etc/yum.repos.d/fedora-updates-modular.repo:#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Modular/$basearch/debug/
/etc/yum.repos.d/fedora-updates-modular.repo:#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Modular/SRPMS/
/etc/yum.repos.d/fedora-updates-testing-modular.repo:#baseurl=http://download.example/pub/fedora/linux/updates/testing/$releasever/Modular/$basearch/
/etc/yum.repos.d/fedora-updates-testing-modular.repo:#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Modular/$basearch/debug/
/etc/yum.repos.d/fedora-updates-testing-modular.repo:#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Modular/SRPMS/
/etc/yum.repos.d/fedora-updates-testing.repo:#baseurl=http://download.example/pub/fedora/linux/updates/testing/$releasever/Everything/$basearch/
/etc/yum.repos.d/fedora-updates-testing.repo:#baseurl=http://download.example/pub/fedora/linux/updates/testing/$releasever/Everything/$basearch/debug/
/etc/yum.repos.d/fedora-updates-testing.repo:#baseurl=http://download.example/pub/fedora/linux/updates/testing/$releasever/Everything/SRPMS/
/etc/yum.repos.d/fedora-updates.repo:#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Everything/$basearch/
/etc/yum.repos.d/fedora-updates.repo:#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Everything/$basearch/debug/
/etc/yum.repos.d/fedora-updates.repo:#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Everything/SRPMS/
/etc/yum.repos.d/fedora.repo:#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Everything/$basearch/os/
/etc/yum.repos.d/fedora.repo:#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Everything/$basearch/debug/tree/
/etc/yum.repos.d/fedora.repo:#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Everything/source/tree/
```
seems that all baseurls have now example in their address. This is definitely weird and issue against fedora would be in place.
Why it fails on lorax though - I guess they parse it out/or enable baseurls in their tests. @atodorov is that the case?

**Comment by marusak** [comment]
From `vm.install` from lorax:
```
# disable mirrors & re-enable direct download                                   
sed -i "s/metalink.*//" /etc/yum.repos.d/*.repo                                 
sed -i "s/#\(baseurl=.*\)/\1/" /etc/yum.repos.d/*.repo 
sed -i "s/download.fedoraproject/dl.fedoraproject/" /etc/yum.repos.d/*.repo
```
@atodorov what is the reason for this?

**Comment by marusak** [comment]
Sent fix in https://github.com/weldr/lorax/pull/1001

**Comment by martinpitt** [comment]
I landed the lorax hack PR, retrying tests.

**Comment by atodorov** [comment]
> From `vm.install` from lorax:
> 
> ```
> # disable mirrors & re-enable direct download                                   
> sed -i "s/metalink.*//" /etc/yum.repos.d/*.repo                                 
> sed -i "s/#\(baseurl=.*\)/\1/" /etc/yum.repos.d/*.repo 
> sed -i "s/download.fedoraproject/dl.fedoraproject/" /etc/yum.repos.d/*.repo
> ```
> 
> @atodorov what is the reason for this?

From the commit log which introduced these changes:

>    bcl: The mirrors are not very good at staying in sync, and if
>    composer hits one mirror and anaconda hits a different mirror,
>    you will see depsolve fail. The safest thing is to not use mirrors
>    in Fedora.

**Comment by martinpitt** [comment]
lol, what? Of course mirrors should be used -- how else would you get any non-ridiculous bandwidth from a place that's not close or in the US? A single master archive also doesn't scale to/withstand requests from the whole world..

**Comment by marusak** [comment]
meh, podman is also failing with `Error: could not get runtime: database libpod temporary files directory (tmpdir) "/tmp/run-1000/libpod/tmp" does not match our libpod temporary files directory (tmpdir) "/run/user/1000/libpod/tmp": database configuration mismatch`

**Comment by marusak** [comment]
Meh. It also needs rebase since some other images changed. It is week old, podman seems to be weird... Let's try our luck once more :)

**Pull request closed without merging**
