### PR TITLE
Image refresh for fedora-41

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-41
 * [x] image-refresh fedora-41
 * [x] https://github.com/cockpit-project/cockpit/issues/21301
 * [x] https://github.com/cockpit-project/cockpit/pull/21321 and land https://bodhi.fedoraproject.org/updates/FEDORA-2024-cbf666ab6a ; or https://github.com/candlepin/subscription-manager-cockpit/pull/84
 * [x] https://github.com/cockpit-project/cockpit-machines/pull/1914
 * [x] https://github.com/cockpit-project/cockpit-machines/pull/1925

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-41 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-41-20241123-092150

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-41-ea843220-20241123-090320/log.html

**Comment by martinpitt** [comment]
The [metrics failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7123-7bb78741-20241123-092305-fedora-41-other-cockpit-project-cockpit/log.html) are the same python crashes as in #21301.

sub-man crashes, but it's not obvious why/how -- there's no crash in the [js log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7123-7bb78741-20241123-092312-fedora-41-candlepin-subscription-manager-cockpit/log.html).

**Comment by martinpitt** [comment]
I cannot reproduce [these failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7123-7bb78741-20241123-092312-fedora-41-candlepin-subscription-manager-cockpit/log.html)  locally at all, neither with the old nor the new services image. Retrying.

**Comment by martinpitt** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2024-cbf666ab6a landed, trying a refresh.

**Comment by cockpituous** [comment]
image-refresh fedora-41 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-41-20241126-124533

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-41-912f69f0-20241126-122738/log.html

**Comment by martinpitt** [comment]
Meh, [more NFS fallout](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7123-4771f8ba-20241126-125336-fedora-41-other-cockpit-project-cockpit/log.html#86). But the [storage ones](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7123-4771f8ba-20241126-125339-fedora-41-storage-cockpit-project-cockpit/log.html#66) should already be covered by #7137, why aren't they?

[machines failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7123-4771f8ba-20241126-125318-fedora-41-cockpit-project-cockpit-machines/log.html#61-2) are half NFS and half https://github.com/cockpit-project/cockpit-machines/pull/1914 (hopefully), retrying to confirm.

**Review by martinpitt — APPROVED** [review]

**Comment by martinpitt** [comment]
Phew...

**Pull request merged**
