### PR TITLE
Fix fedora-30 image refresh

### PR DESCRIPTION
**Pull request by martinpitt**
Continuation of https://github.com/cockpit-project/cockpit/pull/12799

 * [x] image-refresh fedora-30

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-05.
Log: https://209.132.184.41:8493/logs/image-refresh-29-20190926-092525/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-05.
Log: https://209.132.184.41:8493/logs/image-refresh-29-20190926-092525/

**Comment by cockpituous** [comment]
image-refresh fedora-30 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-30-20190926-100202

**Comment by martinpitt** [comment]
This is good enough now -- we know that cockpit's edge test is currently FUBAR, and the three others are bogus statuses.

**Pull request merged**
