### PR TITLE
debian: Add the python3-gssapi package

### PR DESCRIPTION
**Pull request by Gundersanne**
* [x] image-refresh debian-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-1050-20200708-194242/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/bots/commits/image-refresh-debian-stable-20200708-195757

**Comment by martinpitt** [comment]
@Gundersanne : Do the other Debian/Ubuntu images already have it, or will you rebuild them as well?

**Comment by Gundersanne** [comment]
@martinpitt on ubuntu the cache gets built but the ssh fails.

**Comment by martinpitt** [comment]
@Gundersanne: These pull/12345/head contexts don't work, they just run the local unittests. Instead, trigger this on the cockpit PR: `bots/tests-trigger debian-stable@bots#1050`

**Comment by martinpitt** [comment]
@Gundersanne: Also, please run `./tests-trigger image:debian-stable` here to make sure that this doesn't regress for cockpit master.

**Pull request merged**
