### PR TITLE
testmap: promote rhel-8-6 for cockpit-machines from _manual

### PR DESCRIPTION
**Pull request by KKoukiou**
* [x] https://github.com/cockpit-project/cockpit-machines/pull/392

### CODE REVIEW

**Comment by KKoukiou** [comment]
Obviously ignore the podman tests, triggered by mistake.

**Comment by martinpitt** [comment]
@KKoukiou : c-machines also needs some rhel-8-6 special case treatment in the tests.

**Comment by KKoukiou** [comment]
Succeeded in https://github.com/cockpit-project/cockpit-machines/pull/392

**Review by marusak — DISMISSED** [review]
Thanks!

**Comment by marusak** [comment]
There is rarely reason for adding no-test for bots PRs. We only trigger `bots` by default which is required context anyway.

**Review by martinpitt — APPROVED** [review]
Thanks! Triggering test to be 100% sure.

**Pull request merged**
