### PR TITLE
Image refresh for rhel-8-2 - fixed by #336

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-2
 * [x] image-refresh rhel-8-2
 * [x] Fix cockpit's OnCalendar= parsing: https://github.com/cockpit-project/cockpit/pull/13229
 * [x] Fix selinux post and dnf-automatic.timer tests: https://github.com/cockpit-project/cockpit/pull/13235

### CODE REVIEW

**Comment by martinpitt** [comment]
automatic updates [got broken](https://209.132.184.41:8493/logs/pull-292-20191201-100808-947c72cc-cockpit-project-cockpit--rhel-8-2/log.html), and the timedatex SELinux failure looks different now.

**Comment by martinpitt** [comment]
I adjusted the naughty patterns for the timedatex SELinux bug. The automatic updates tests are an actual issue in cockpit, I'll send a PR there.

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/13229 to fix OnCalendar= parsing.

**Comment by martinpitt** [comment]
The recently landed [testClientCertAuthentication](https://209.132.184.41:8493/logs/pull-292-20191203-141818-e4332817-cockpit-project-cockpit--rhel-8-2/log.html#184-2) fails as well now:
```
audit: type=1400 audit(1575384296.233:7): avc:  denied  { read } for  pid=1981 comm="cockpit-session" name="2c27e4101c40bf8660a958237ceb296832ab6996e4a77387416018a7418fa814" dev="tmpfs" ino=35840 scontext=system_u:system_r:cockpit_session_t:s0 tcontext=system_u:object_r:cockpit_var_run_t:s0 tclass=file permissive=0
cockpit-ws[1975]: cockpit-session: Failed to open certificate file /run/cockpit/tls/2c27e4101c40bf8660a958237ceb296832ab6996e4a77387416018a7418fa814: Permission denied
```

**Comment by martinpitt** [comment]
@henrywang , @larskarlitski : Composer tests keep failing on this new RHEL 8.2 image. Is this known? Due to some incompatibility with new lorax-composer, or changes in osbuild? But I thought both would always be installed on the fly, it doesn't use preinstalled packages.

**Comment by larskarlitski** [comment]
> @henrywang , @larskarlitski : Composer tests keep failing on this new RHEL 8.2 image. Is this known? Due to some incompatibility with new lorax-composer, or changes in osbuild? But I thought both would always be installed on the fly, it doesn't use preinstalled packages.

Hm, nothing has changed on the cockpit-composer side yet. We're working on making the tests pass with osbuild-composer on https://github.com/weldr/cockpit-composer/pull/839. This PR should still use lorax-composer.

**Comment by larskarlitski** [comment]
Could it be that the password strength rules have become stronger? https://209.132.184.41:8493/logs/pull-292-20191204-081717-e4332817-weldr-cockpit-composer--rhel-8-2-firefox/wdio_report/error/ERROR_firefox_2019-12-04T08-37-02.408Z.png

**Comment by martinpitt** [comment]
@larskarlitski : Hah, well spotted! That would indeed be something that a newer base image influences, outside of cockpit-composer.

**Pull request closed without merging**
