### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-testing-20230629-040404.log

**Comment by allisonkarlitskaya** [comment]
Got it locally and clicked on the error:

image

**Comment by allisonkarlitskaya** [comment]
hihi qemu 1.8.0

```
  qemu-block-extra (1:7.2+dfsg-7 -> 1:8.0.2+dfsg-2)
  qemu-system-common (1:7.2+dfsg-7 -> 1:8.0.2+dfsg-2)
  qemu-system-data (1:7.2+dfsg-7 -> 1:8.0.2+dfsg-2)
  qemu-system-gui (1:7.2+dfsg-7 -> 1:8.0.2+dfsg-2)
  qemu-system-x86 (1:7.2+dfsg-7 -> 1:8.0.2+dfsg-2)
  qemu-utils (1:7.2+dfsg-7 -> 1:8.0.2+dfsg-2)
```

**Comment by allisonkarlitskaya** [comment]
`qemu-system-common` shipped `/usr/share/qemu/vhost-user/50-qemu-virtiofsd.json` in 7, but in 8 this file is gone.  libvirt apparently goes looking for it.

**Comment by allisonkarlitskaya** [comment]
Upstream here: https://github.com/qemu/qemu/commit/8ab5e8a503b55eb27672777cfedea902bb22a246

The binary is also missing from `/usr/lib/qemu/virtiofsd`

**Comment by martinpitt** [comment]
We also dropped the package on Fedora 39: commit 58e612252d03498ff. It was taken out of qemu and rewritten as a separate project (in Rust): https://gitlab.com/virtio-fs/virtiofsd

**Comment by martinpitt** [comment]
https://tracker.debian.org/pkg/rust-virtiofsd has that, but it didn't migrate to testing yet.

**Comment by allisonkarlitskaya** [comment]
Okay, let's naughty this one, then.

**Comment by allisonkarlitskaya** [comment]
> Okay, let's naughty this one, then.

#4950

**Review by allisonkarlitskaya — APPROVED** [review]

**Pull request merged**
