### PR TITLE
Image refresh for ubuntu-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for ubuntu-stable
 * [ ] Refresh after https://launchpad.net/bugs/2063200 got a regression fix
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20240525-225125

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-stable-138d68fe-20240525-223714/log.html

**Comment by martinpitt** [comment]
Ugh, seems [this recent fix](https://bugs.launchpad.net/ubuntu/+source/shadow/+bug/2063200) broke something. Not sure if that's a bug on our or Ubuntu side, something for tomorrow.

**Comment by mvollmer** [comment]
And `w -sh` segfaults...

**Comment by mvollmer** [comment]
> And `w -sh` segfaults...

This is a known bug, apparently.

**Comment by martinpitt** [comment]
The regression got fixed in devel and soon in -proposed, so let's just block on that for a few days?

**Comment by mvollmer** [comment]
> The regression got fixed in devel and soon in -proposed, so let's just block on that for a few days?

Yes.

**Pull request closed without merging**
