### PR TITLE
Image refresh for rhel-8-9

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-9
 * [x] image-refresh rhel-8-9

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-8-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-9-20240420-225644

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-8-9-9343007d-20240420-223737/log.html

**Comment by jelly** [comment]
Re-tried twice but it still fails. @ptoscano  do you have an idea? Not much changed in the RHEL 8 image refresh.

**Comment by martinpitt** [comment]
@jelly @ptoscano that's just the same long-standing issue as in https://github.com/candlepin/subscription-manager-cockpit/pull/64 / https://github.com/candlepin/subscription-manager-cockpit/pull/66 but that fix wasn't backported to the -1.28 branch yet. This affects the current image as well, so no need to block this refresh.

**Review by martinpitt — APPROVED** [review]

**Comment by jelly** [comment]
> @jelly @ptoscano that's just the same long-standing issue as in [candlepin/subscription-manager-cockpit#64](https://github.com/candlepin/subscription-manager-cockpit/pull/64) / [candlepin/subscription-manager-cockpit#66](https://github.com/candlepin/subscription-manager-cockpit/pull/66) but that fix wasn't backported to the -1.28 branch yet. This affects the current image as well, so no need to block this refresh.

Ah, this was not on my radar.

**Pull request merged**
