### PR TITLE
Image refresh for fedora-rawhide

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide
 * [x] image-refresh fedora-rawhide

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-20230720-225959.log

**Comment by martinpitt** [comment]
@KKoukiou @jkonecny12 : Wow, installation size requirement blew up from 1.4 to 6.3 GB disk space? That sounds wrong..

**Comment by martinpitt** [comment]
Test run worked in #5043, perhaps this got fixed now in anaconda/rawhide? Retrying

**Review by martinpitt — APPROVED** [review]
Yay

**Pull request merged**
