### PR TITLE
Image refresh for fedora-36

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-36
 * [x] image-refresh fedora-36

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-36-20230202-230000.log

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20230202-234113

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-36-20230202-234141.log

**Comment by martinpitt** [comment]
composer keeps failing to boot. I think this problem has been plagueing us for a while, but it seems to have gotten worse.

**Review by jelly — APPROVED** [review]

**Comment by jelly** [comment]
Retried and it's back to working state.. ugh.

**Pull request merged**
