### PR TITLE
images: Move rhel-9 away from beta

### PR DESCRIPTION
**Pull request by marusak**
* [x] image-refresh rhel-9-0

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-2445-20210923-062525/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-2445-20210923-064646/

**Comment by cockpituous** [comment]
Command '('git', 'push', 'https://github.com/cockpit-project/bots', '+HEADNone/heads/image-refresh-rhel-9-0-20210923-070505')' returned non-zero exit status 128.: https://logs.cockpit-project.org/logs/image-refresh-2445-20210923-064646/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-2445-20210923-071111/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2445-20210923-072525/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20210923-074040

**Comment by marusak** [comment]
- [podman](https://logs.cockpit-project.org/logs/pull-2445-20210923-075240-646e4167-rhel-9-0-cockpit-project-cockpit-podman/log.html) is unhappy - `Failed to start podman.socket: Transaction for podman.socket/start is destructive (shutdown.target has 'start' job queued, but 'stop' is included in transaction).`
- [machines](https://logs.cockpit-project.org/logs/pull-2445-20210923-075240-646e4167-rhel-9-0-cockpit-project-cockpit-machines/log.html#13-2) are unhappy
- [/ME](https://github.com/marusak/) is unhappy because of ^

**Comment by marusak** [comment]
Added naughty and green

**Review by martinpitt — APPROVED** [review]
Thanks!

**Pull request merged**
