### PR TITLE
TESTS: image refresh with job-runner

### PR DESCRIPTION
**Pull request by cockpituous**
:warning:  **DO NOT ADD A BOTS LABEL HERE** This isn't supposed to be picked up by production bots.

I ran this with
```sh
./job-runner --config ~/job-runner.toml json '{"repo": "cockpit-project/bots", "sha": "a18582b6783d1465d1984926e8013640280c2007", "pull": null, "slug": "image-refresh-cirros-test-20240307-110434", "context": "image-refresh/cirros", "command": ["./image-refresh", "--verbose", "--issue=6033", "cirros"], "secrets": ["github-token", "image-upload"]}'
```

 * [x] image-refresh cirros

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh cirros done: https://github.com/cockpit-project/bots/commits/image-refresh-cirros-20240307-100526

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-cirros-test-20240307-110434/log.html

**Comment by martinpitt** [comment]
:rocket: status, log, issue → PR, everything works :+1:

**Comment by cockpituous** [comment]
image-refresh cirros done: https://github.com/cockpit-project/bots/commits/image-refresh-cirros-20240307-102836

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-cirros-test-20240307-110434/log.html

**Comment by martinpitt** [comment]
OK, gotta try this again on a fresh issue.

**Pull request closed without merging**
