### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

### CODE REVIEW

**Comment by martinpitt** [comment]
[machines testNICDelete failure](https://logs.cockpit-project.org/logs/pull-2733-20211218-024630-7d743b35-arch-cockpit-project-cockpit-machines/log.html#57-2), retrying for comparison

**Comment by martinpitt** [comment]
Regression is persistent, needs investigation.

**Comment by jelly** [comment]
Debugging the issue, setting the [libvirt log level](https://libvirt.org/kbase/debuglogs.html) as in the documentation, I get the following in journal:

```
Dec 20 14:43:04 archlinux libvirtd[1186]: QEMU_MONITOR_SEND_MSG: mon=0x7fc26c06f180 msg={"execute":"device_del","arguments":{"id":"net0"},"id":"libvirt-13"}
                                           fd=-1
Dec 20 14:43:04 archlinux libvirtd[1186]: OBJECT_REF: obj=0x7fc26c06f180
Dec 20 14:43:04 archlinux libvirtd[1186]: QEMU_MONITOR_IO_WRITE: mon=0x7fc26c06f180 buf={"execute":"device_del","arguments":{"id":"net0"},"id":"libvirt-13"}
                                           len=70 ret=70 errno=0
Dec 20 14:43:04 archlinux libvirtd[1186]: OBJECT_REF: obj=0x7fc26c06f180
Dec 20 14:43:04 archlinux libvirtd[1186]: OBJECT_UNREF: obj=0x7fc26c06f180
Dec 20 14:43:04 archlinux libvirtd[1186]: OBJECT_UNREF: obj=0x7fc26c06f180
Dec 20 14:43:04 archlinux libvirtd[1186]: OBJECT_REF: obj=0x7fc26c06f180
Dec 20 14:43:04 archlinux libvirtd[1186]: QEMU_MONITOR_RECV_REPLY: mon=0x7fc26c06f180 reply={"id": "libvirt-13", "error": {"class": "DeviceNotFound", "desc": "Device 'net0' not found"}}
```

ip a output is:
```
5: vnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master virbr0 state UNKNOWN group default qlen 1000
    link/ether c6:24:59:59:0c:49 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc54:ff:fe21:538e/64 scope link
       valid_lft forever preferred_lft forever
```

So it seems the either libvirt informs cockpit-machines the wrong nic or cockpit-machines does this?

**Comment by jelly** [comment]
After further debugging it seems that the upgrade to `qemu 6.1.0-5 -> 6.2.0-1`  is the cause of  the issue where mac addresses are no longer able to get deleted.

**Comment by martinpitt** [comment]
With QEMU 6.1 (on Fedora 35), I get this on the running VM:
```
# virsh domiflist subVmTest1 ; cat /sys/class/net/vnet0/address
 Interface   Type      Source    Model    MAC
-------------------------------------------------------------
 vnet0       network   default   virtio   52:54:00:39:11:a3

fe:54:00:39:11:a3
```

while on QEMU 6.2 on RHEL 8.6 I get this:
```
# virsh domiflist subVmTest1 ; cat /sys/class/net/vnet0/address
 Interface   Type      Source    Model    MAC
-------------------------------------------------------------
 vnet0       network   default   virtio   52:54:00:8e:08:69

fe:54:00:8e:08:69
```

So these actually coincide rather well -- I suppose the 52 → fe prefix is somehow intended/magic to tell apart the guest MACs from the host's view of them? Your host MAC on arch looks singnificantly different indeed, but this may just be a red herring.

When I click on "Delete" button with qemu 6.1, this works pretty much right away, the NIC is gone (and vnet0 on the host), and there are some log messages:
```
kernel: virbr0: port 1(vnet0) entered disabled state
VIRT_RESOURCE pid=4740 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:virtd_t:s0-s0:c0.c1023 msg='virt=kvm resrc=net reason=detach vm="subVmTest1" uuid=9005aa07-dc76-46ce-8f02-adbfa74fb074 old-net="52:54:00:39:11:a3" new-net="?" exe="/usr/sbin/virtqemud" hostname=? addr=? terminal=? res=success'
NetworkManager[620]: <info>  [1641192286.5432] device (vnet0): state change: activated -> unmanaged (reason 'unmanaged', sys-iface-state: 'removed')
```

but when I do this with qemu 6.2, I get a spinner for some 5 seconds, then the dialog goes away, and *nothing at all* happens any more -- no log messages, no change in NICs, not even a JS error.

The delete action results in a call to

    virt-xml -c qemu:///system subVmTest1 --remove-device --update --network mac=<MAC>

On F35 with QEMU 6.1 this says:
```
Device hotunplug successful.
Domain 'subVmTest1' defined successfully.
```

With QEMU 6.2 it indeed fails:
```
Device hotunplug successful.
ERROR    No matching objects found for --remove-device mac=52:54:00:8e:08:69
```

even though `dumpxml` clearly contains a matching MAC:
```xml
    <interface type='network'>
      <mac address='52:54:00:8e:08:69'/>
      <source network='default' portid='0c38eb91-5f97-48ee-b7e6-b7275471dc59' bridge='virbr0'/>
      <target dev='vnet0'/>
      <model type='virtio'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </interface>
```

**Comment by martinpitt** [comment]
I filed https://bugzilla.redhat.com/show_bug.cgi?id=2036562 about this, and created known issue #2775. I'll push a naughty here.

**Review by jelly — APPROVED** [review]

**Pull request merged**
