### PR TITLE
images: Do not install glibc-all-langpacks to CentOS-7

### LINKED ISSUE #285: Image refresh for centos-7
Image refresh for centos-7
 * [ ] FAIL: image-refresh centos-7

### PR DESCRIPTION
**Pull request by marusak**
* [x] image-refresh centos-7

Fixes #285

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-293-20191201-125353/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-dnw3x.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-293-20191201-125353/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/bots/commits/image-refresh-centos-7-20191201-131313

**Comment by martinpitt** [comment]
Meh, image got built on centosci, and disappeared too quickly. Rebuilding.

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-293-20191201-202424/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/bots/commits/image-refresh-centos-7-20191201-205252

**Pull request merged**
