### PR TITLE
images: Add RHEL 8 python3-devel build dependency

### PR DESCRIPTION
**Pull request by martinpitt**
On RHEL 8, cockpit needs to BuildRequires python3-devel instead of /usr/bin/python3, as the latter can give non-supported versions from modules [1]. Due to our offline CI package builds, we need to add it to our images' mocks before we can add it to the spec.

[1] https://issues.redhat.com/browse/RHEL-2215

 * [x] image-refresh rhel-8-9
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-8-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-9-20230908-120705

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-9-20230908-120707.log

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20230908-122842

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/centos-8-stream-20230908-122828.log

**Review by jelly — APPROVED** [review]

**Pull request merged**
