### PR TITLE
images: Fix CirrOS image rebuild

### PR DESCRIPTION
**Pull request by martinpitt**
There are now some redirections in place; tell curl to follow them.

Also move to the current stable version.

 * [x] image-refresh cirros

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-860-20200513-062121/

**Comment by cockpituous** [comment]
image-refresh cirros done: https://github.com/cockpituous/bots/commits/image-refresh-cirros-20200513-062121

**Comment by martinpitt** [comment]
cockpit is the only project that uses the cirros image (for the Machines page), so I triggered only that.

**Comment by martinpitt** [comment]
This [breaks tests](https://logs.cockpit-project.org/logs/pull-860-20200513-103137-19a32aaa-fedora-32-cockpit-project-cockpit/log.html), apparently the new CirroS 0.5.0 doesn't show the "Initializing cgroupfs..." message any more. I think we should be consistent and expect the same "login:" message everywhere. CirrOS boots really fast, so that doesn't make much difference. But for now I'll just move back to 0.4.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-860-20200513-130404/

**Comment by cockpituous** [comment]
image-refresh cirros done: https://github.com/cockpituous/bots/commits/image-refresh-cirros-20200513-130505

**Pull request merged**
