### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-coreos-20221219-224848.log

**Comment by cockpituous** [comment]
image-refresh fedora-coreos done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-coreos-20221220-113210

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-coreos-20221220-113232.log

**Comment by jelly** [comment]
I wonder why  https://github.com/cockpit-project/cockpit-podman/pull/1157 does not apply to coreos?

**Review by martinpitt — APPROVED** [review]
Thanks @jelly !

**Comment by jelly** [comment]
> @jelly: One does not install rpms on coreos. Look at Makefile, for coreos it more or less just copies `dist/` to /usr/local/share/cockpit.

Oic! Danke!

**Pull request merged**
