### PR TITLE
Image refresh for centos-8-stream

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-8-stream
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by marusak** [comment]
needs vdo report. I wonder, if https://bugs.centos.org is the right place for reporting centos stream bugs. (I think I saw somewhere some discussion about where to report centos stream bugs).

**Comment by martinpitt** [comment]
@marusak: No, it's not any more. Report it in bugzilla against RHEL and select "Version: CentOS Stream".

**Comment by marusak** [comment]
> Report it in bugzilla against RHEL and select "Version: CentOS Stream".

Awesome, thanks! Will do that.

**Comment by martinpitt** [comment]
I cloned the original https://bugzilla.redhat.com/show_bug.cgi?id=1894978 for CentOS 8 stream here: https://bugzilla.redhat.com/show_bug.cgi?id=1907968

**Comment by martinpitt** [comment]
Argh argh, what is it today with us not being able to push to cockpituous' repo? Filing a new PR.

**Pull request closed without merging**
