### PR TITLE
Image refresh for fedora-32

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-32
 * [x] image-refresh fedora-32

### CODE REVIEW

**Comment by marusak** [comment]
Bunch of AVCs

**Comment by martinpitt** [comment]
On the plus side, the clevis/tang issue is fixed: https://github.com/latchset/tang/issues/44

**Comment by marusak** [comment]
List of AVCs:
```
audit: type=1400 audit(1583299690.008:322): avc:  denied  { read } for  pid=22496 comm="runlevel" name="utmp" dev="tmpfs" ino=15019 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:initrc_var_run_t:s0 tclass=file permissive=0
                                                                                
audit: type=1400 audit(1583300065.711:269): avc:  denied  { fsetid } for  pid=7234 comm="xz" capability=4  scontext=system_u:system_r:pcp_pmlogger_t:s0 tcontext=system_u:system_r:pcp_pmlogger_t:s0 tclass=capability permissive=0
                                                                                
audit: type=1400 audit(1583301709.843:138): avc:  denied  { fsetid } for  pid=1107 comm="cp" capability=4  scontext=system_u:system_r:pcp_pmlogger_t:s0 tcontext=system_u:system_r:pcp_pmlogger_t:s0 tclass=capability permissive=0
                                                                                
audit: type=1400 audit(1583300599.325:1189): avc:  denied  { dac_override } for  pid=36778 comm="touch" capability=1  scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:system_r:pcp_pmie_t:s0 tclass=capability permissive=0

audit: type=1400 audit(1583300599.340:1190): avc:  denied  { dac_override } for  pid=36755 comm="pmie_check" capability=1  scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:system_r:pcp_pmie_t:s0 tclass=capability permissive=0

audit: type=1400 audit(1583300599.370:1191): avc:  denied  { dac_override } for  pid=36785 comm="mv" capability=1  scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:system_r:pcp_pmie_t:s0 tclass=capability permissive=0
```

Plus the same failure as was in [fedora-testing]( https://logs.cockpit-project.org/logs/pull-604-20200304-050159-700b962a-fedora-32-cockpit-project-cockpit/TestSelinux-testTroubleshootAlerts-fedora-32-127.0.0.2-2501-FAIL.log) with missing `pydbus`

I'll report them now and create naughty for them.

**Comment by marusak** [comment]
@ pydbus - How it got in? [the build](https://bodhi.fedoraproject.org/updates/FEDORA-2020-09dbfd7a6e) is still in testing. But there is new [build](https://bodhi.fedoraproject.org/updates/FEDORA-2020-5812c2d582) already.

**Comment by martinpitt** [comment]
updates-testing indeed is enabled by default on our current f-32 image. I just booted it and checked if setroubleshoot 3.3.22-6 is already available, but the mirror still has -5. So we'll need to wait a bit before we can rebuild. We can of course investigate the AVCs already.

**Comment by marusak** [comment]
I pushed here naughties, but we need another image refresh anyway. Lets do it in this PR though.

**Comment by marusak** [comment]
`3.3.22-6.fc32` is already visible, so I'll retrigger this build.

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-mcld1.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-604-20200306-055959/

**Comment by cockpituous** [comment]
image-refresh fedora-32 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-32-20200306-061919

**Comment by cockpituous** [comment]
verify/fedora-32
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testUnprivileged (__main__.TestAccounts)
Creating mailbox file: File exists
# Warning: cockpit.service changed on disk, the version systemd has loaded is outdated.
# This output shows the current version of the unit's original fragment and drop-in files.
# If fragments or drop-ins were added or removed, they are not properly reflected in this output.
# Run 'systemctl daemon-reload' to reload units.
Failed to cat /etc/systemd/system/cockpit.service.d/notls.conf: No such file or directory
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket

DevTools listening on ws://127.0.0.1:9928/devtools/browser/2e763d0b-2b3c-4430-9147-c2da94b0c687
[0306/062844.137932:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 12690: Permission denied (13)
[0306/062844.152692:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0306/062844.154142:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0306/062844.156831:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
[0306/062844.335465:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 12728: Permission denied (13)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1583476125529.6719,"url":"http://127.0.0.2:9091/cockpit/$bf89e7d26db725e150cae8e078d649249164cb57ee63e38588ee055d62d8e148/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: Error: Could not obtain the password to be scored

CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1583476126903.086,"url":"http://127.0.0.2:9091/users#/anton"}
> warning: Error: Could not obtain the password to be scored

> warning: You must wait longer to change your password
audit: type=1400 audit(1583476130.664:1159): avc:  denied  { read } for  pid=24773 comm="runlevel" name="utmp" dev="tmpfs" ino=15026 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:initrc_var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1583476130.678:1160): avc:  denied  { read } for  pid=24773 comm="runlevel" name="utmp" dev="tmpfs" ino=15026 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:initrc_var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1583476130.757:1161): avc:  denied  { dac_override } for  pid=24808 comm="touch" capability=1  scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:system_r:pcp_pmie_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1583476130.769:1162): avc:  denied  { dac_override } for  pid=24785 comm="pmie_check" capability=1  scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:system_r:pcp_pmie_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1583476130.783:1163): avc:  denied  { dac_override } for  pid=24815 comm="mv" capability=1  scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:system_r:pcp_pmie_t:s0 tclass=capability permissive=0
Wrote JS log to TestAccounts-testUnprivileged-fedora-32-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestAccounts-testUnprivileged-fedora-32-127.0.0.2-2201-FAIL.log
Wrote screenshot to TestAccounts-testUnprivileged-fedora-32-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestAccounts-testUnprivileged-fedora-32-127.0.0.2-2201-FAIL.html
Wrote JS log to TestAccounts-testUnprivileged-fedora-32-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestAccounts-testUnprivileged-fedora-32-127.0.0.2-2201-FAIL.log
> warning: grep: /sys/class/dmi/id/product_serial: Permission denied
grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
grep: /sys/class/dmi/id/chassis_serial: Permission denied
grep: /sys/class/dmi/id/product_uuid: Permission denied

Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 883, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1077, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1583476130.664:1159): avc:  denied  { read } for  pid=24773 comm="runlevel" name="utmp" dev="tmpfs" ino=15026 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:initrc_var_run_t:s0 tclass=file permissive=0

# Result testUnprivileged (__main__.TestAccounts) failed
# 1 TEST FAILED [12s on centosci-tasks-4hjcm]
not ok 4 test/verify/check-accounts TestAccounts.testUnprivileged
```
First occurrence: 2020-03-06T06:28:56.247980 | revision 190071495551061913006d8b8bbaf3bcebd032d0
Times recorded: 1
Latest occurrences:

- 2020-03-06T06:28:56.247980 | revision 190071495551061913006d8b8bbaf3bcebd032d0

**Comment by martinpitt** [comment]
[This failure](https://logs.cockpit-project.org/logs/pull-604-20200306-064752-fcdba241-fedora-32-cockpit-project-cockpit/log.html#75) should be fixed by https://github.com/cockpit-project/cockpit/pull/13665

**Comment by martinpitt** [comment]
[one more naughty to do?](https://logs.cockpit-project.org/logs/pull-604-20200306-141941-fcdba241-fedora-32-cockpit-project-cockpit/log.html#244-2)

**Comment by marusak** [comment]
```
/build/cockpit-project/bots/make-checkout-workdir/pkg/networkmanager/firewall.jsx
  523:61  error  Empty components are self-closing  react/self-closing-comp

/build/cockpit-project/bots/make-checkout-workdir/pkg/systemd/hwinfo.jsx
  195:17  error  Empty components are self-closing  react/self-closing-comp
```

Wondering if this slipped in or new version of eslint. I'll send fix anyway.

**Comment by marusak** [comment]
Sent https://github.com/cockpit-project/cockpit/pull/13674

**Comment by martinpitt** [comment]
Looks promising, just the usual [networking checkpoint flake](https://logs.cockpit-project.org/logs/pull-604-20200308-105507-b2a52623-fedora-32-cockpit-project-cockpit/log.html#163-2).

**Pull request merged**
