### PR TITLE
images: add nodejs-devel in RHEL/Fedora mock

### PR DESCRIPTION
**Pull request by ptoscano**
Pull it so it is possible to build nodejs bits in mock, following the
latest guidelines for Fedora:
- https://bugzilla.redhat.com/show_bug.cgi?id=1969450#c8
- https://github.com/cockpit-project/cockpit-certificates/pull/66

 * [x] image-refresh fedora-36
 * [x] image-refresh rhel-9-1
 * [x] image-refresh fedora-35

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3346-20220509-124646/

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20220509-130707

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3346-20220509-130707/

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20220509-132424

**Comment by cockpituous** [comment]
image-refresh rhel-9-1 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-1-20220509-134444

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-3346-20220509-140202/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3346-20220509-143535/

**Comment by cockpituous** [comment]
image-refresh rhel-9-1 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-1-20220509-145454

**Comment by cockpituous** [comment]
image-refresh fedora-35 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-35-20220509-152424

**Comment by martinpitt** [comment]
Somehow the bot went bonkers here, and refreshes the images over and over again. I un-labeled bot for now. I'd say, pick up the three refreshed images, let's test and land them, then refresh the others separately.

**Comment by cockpituous** [comment]
image-refresh fedora-35 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-35-20220509-155050

**Review by martinpitt — APPROVED** [review]
Thanks! Let's land this, and refresh the others in separate PRs. In particular, we need fedora-rawhide and centos-8-stream for https://github.com/cockpit-project/starter-kit/pull/573

**Pull request merged**
