### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by martinpitt** [comment]
I retried it a couple of times, and [testLibvirt](https://209.132.184.41:8493/logs/pull-457-20200127-135252-fe7caef3-fedora-testing-cockpit-project-cockpit/log.html#84-2) keeps failing. @KKoukiou , can you please have a look? This will soon affect  f-30/f31 too.

**Comment by KKoukiou** [comment]
> I retried it a couple of times, and [testLibvirt](https://209.132.184.41:8493/logs/pull-457-20200127-135252-fe7caef3-fedora-testing-cockpit-project-cockpit/log.html#84-2) keeps failing. @KKoukiou , can you please have a look? This will soon affect f-30/f31 too.

https://github.com/cockpit-project/cockpit/pull/13475

**Comment by martinpitt** [comment]
Now it fails for a completely different reason:
```
/build/cockpit-project/bots/make-checkout-workdir/pkg/machines/helpers.js
  308:27  error  Expected indentation of 12 space characters but found 0  react/jsx-indent
```
That sounds like some new eslint version that crept in. I'll look at that separately.

**Comment by martinpitt** [comment]
Rebased to current master to get the current f-30 image

**Comment by martinpitt** [comment]
[testLibvirt](https://209.132.184.41:8493/logs/pull-457-20200203-080303-819b77f7-fedora-testing-cockpit-project-cockpit/log.html#89-2) still fails, but retrying

**Pull request merged**
