### PR TITLE
Image refresh for fedora-rawhide

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide
 * [x] image-refresh fedora-rawhide

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-20241006-231925

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-ff91a585-20241006-223946/log.html

**Comment by mvollmer** [comment]
There is currently some version skew between udisks2 in fedora-rawhide-boot and the module packages udisks2-lvm2 and udisks2-btrfs that vm.install downloads. @KKoukiou is working on sorting this out.

```
> warn: Can't enable storaged btrfs module Error initializing module 'btrfs': /usr/lib64/udisks2/modules/libudisks2_btrfs.so: undefined symbol: udisks_mdraid_set_consistency_policy
> warn: Can't enable storaged lvm2 module Error initializing module 'lvm2': /usr/lib64/udisks2/modules/libudisks2_lvm2.so
```

**Comment by mvollmer** [comment]
> @KKoukiou is working on sorting this out.

Done!

**Pull request merged**
