### PR TITLE
Image refresh for centos-8-stream

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-8-stream
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by skobyda** [comment]
Sent fix for packagekit failures: https://github.com/cockpit-project/cockpit/pull/15622

**Comment by skobyda** [comment]
It seems there is a bug which breaks tracer for centos-8. More in comment here https://github.com/cockpit-project/cockpit/pull/15622#issuecomment-810660934

**Comment by marusak** [comment]
Added naughty pattern.

**Comment by marusak** [comment]
It will also need 8.4 backport but lets do that separetely after this lands.

**Comment by martinpitt** [comment]
Tests look disastrous, but the machines ones are hopefully unrelated (and will be dropped soon anyway), and check-packagekit is tested in https://github.com/cockpit-project/cockpit/pull/15622 . Thanks!

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
