### PR TITLE
WIP: 4-cockpit-9: [no-test] rebuild some more rpm-based images with python build-deps

### PR DESCRIPTION
**Pull request by cockpituous**
* [ ] FAIL: image-refresh fedora-38
 * [ ] FAIL: image-refresh centos-9-stream
 - [ ] image-refresh rhel-8-9
 - [ ] image-refresh rhel-9-3

### CODE REVIEW

**Comment by cockpituous** [comment]
Completed. Log: Failed to retrieve updated pull data after force pushing

**Comment by cockpituous** [comment]
image-refresh rhel-9-3 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-3-20230502-204006

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-3-20230502-204040.log

**Comment by martinpitt** [comment]
@allisonkarlitskaya : Also, I think there's not much hurry about it. We only need this once we enable the pybridge for real, and https://github.com/cockpit-project/cockpit/labels/pybridge-blocker still feels like at least two weeks away from that. During that time, the refreshes should mostly happen naturally. (Except the Debians, where we didn't update the packaging yet)

**Pull request closed without merging**
