### PR TITLE
Image refresh for fedora-rawhide-anaconda-payload

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-anaconda-payload
 * [x] image-refresh fedora-rawhide-anaconda-payload

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-anaconda-payload done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-anaconda-payload-20240718-224754

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-anaconda-payload-4044e914-20240718-223850/log.html

**Comment by martinpitt** [comment]
@KKoukiou @M4rtinK [these pixel failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6636-7a87e241-20240718-224905-fedora-rawhide-boot-rhinstaller-anaconda-webui/pixeldiff.html#TestStorageCockpitIntegration-testEncryptedUnlock-storage-editor) -- I *really* recommend to ignore or mock the value for the pixel test, and assert its value textually instead. Leaving this one to you.

**Comment by KKoukiou** [comment]
> @KKoukiou @M4rtinK [these pixel failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6636-7a87e241-20240718-224905-fedora-rawhide-boot-rhinstaller-anaconda-webui/pixeldiff.html#TestStorageCockpitIntegration-testEncryptedUnlock-storage-editor) -- I _really_ recommend to ignore or mock the value for the pixel test, and assert its value textually instead. Leaving this one to you.

Actually this failing element is whitelisted through it's class since a long time. Debugging  the issue now.

**Review by martinpitt — APPROVED** [review]
Wohoo, thanks @KKoukiou !

**Pull request merged**
