### PR TITLE
images: Move fedora-testing to Fedora 31, some image cleanup

### PR DESCRIPTION
**Pull request by martinpitt**
This was already intended in #501 and #567, but the symlinks were not
actually updated, so that the current image is still based on F30.

 * [x] image-refresh fedora-testing
 * [x] image-refresh fedora-31
 * [x] image-refresh fedora-30
 * [ ] adjust f-testing cockpit tests: https://github.com/cockpit-project/cockpit/pull/13618

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-q4wtw.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-569-20200224-150202/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-569-20200224-150202/

**Comment by martinpitt** [comment]
No match for argument: atomic

Let's postpone this PR until PR #562 lands, as that one also modifies the setup script.

**Comment by martinpitt** [comment]
Now that #562 landed, I rebased this and fixed the .setup.

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-569-20200225-142525/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-569-20200225-142525/

**Comment by martinpitt** [comment]
```
+ useradd -c Builder -G mock builder
+ '[' fedora '!=' fedora-testing ']'
+ echo 'config_opts['\''yum.conf'\''] += '\''[updates-testing]\nenabled=1'\'''
++ cut -d - -f 1
+ opsys=fedora
++ cut -d - -f 2
+ version=testing
+ '[' testing -eq testing ']'
+ version=31
++ /var/lib/testvm/build-deps.sh 'fedora 31'
packages
[...]
KeyError: 'yum.conf'
```

**Comment by martinpitt** [comment]
Seems 'yum.conf' does not exist any more at last, we need to switch that to "dnf.conf". This will affect all images, so I'm taking the opportunity to clean up a bit.

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-546lp.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-569-20200225-183434/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-testing-20200225-185858

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-569-20200225-185858/

**Comment by cockpituous** [comment]
image-refresh fedora-31 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-31-20200225-194646

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-569-20200225-194646/

**Comment by cockpituous** [comment]
image-refresh fedora-30 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-30-20200225-202929

**Comment by martinpitt** [comment]
Ah, we still [need docker](https://logs.cockpit-project.org/logs/pull-569-20200225-203406-8154d64b-fedora-31-container-bastion-cockpit-project-cockpit/log.html) as an installed package dependency.

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-569-20200225-213434/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-testing-20200225-223333

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-569-20200225-223434/

**Comment by cockpituous** [comment]
image-refresh fedora-31 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-31-20200225-232424

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-569-20200225-232525/

**Comment by cockpituous** [comment]
image-refresh fedora-30 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-30-20200226-001212

**Comment by martinpitt** [comment]
f31 based fedora-testing [still needs some test adjustments](https://logs.cockpit-project.org/logs/pull-569-20200226-081853-ceab3806-fedora-testing-cockpit-project-cockpit/log.html), I'll send a cockpit PR for these.

**Pull request merged**
