### PR TITLE
Image refresh for fedora-rawhide-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-boot

 * [x] Land and release https://github.com/cockpit-project/cockpit/pull/17622
 * [x] Get https://bodhi.fedoraproject.org/updates/FEDORA-2022-0bd441d073 into rawhide and let it land on the mirrors
 * [ ] wait for ISO to update
 * [ ] image-refresh fedora-rawhide-boot

### CODE REVIEW

**Comment by martinpitt** [comment]
[image failed to boot](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3696-20220802-224843-c045ab6a-fedora-rawhide-boot-rhinstaller-anaconda/log.html). Trying once more, then investigating.

**Comment by martinpitt** [comment]
This easily reproduces locally. `virsh console` is useless, as nothing actually talks to ttyS0. But `virt-viewer` works, shows Anaconda starting up, and then the whole VM crashes immediately. @M4rtinK , @jkonecny12, can you please have a closer look? How to debug such issues? I.e. how do you stop anaconda from running automatically, and step through it manually?

**Comment by M4rtinK** [comment]
> This easily reproduces locally. `virsh console` is useless, as nothing actually talks to ttyS0. But `virt-viewer` works, shows Anaconda starting up, and then the whole VM crashes immediately. @M4rtinK , @jkonecny12, can you please have a closer look? 

I'll take a look.

>How to debug such issues? I.e. how do you stop anaconda from running automatically, and step through it manually?

Can we inject boot options to this environment ? In that case I suggest:
`inst.nokill` - this should prevent Anaconda from shutting down the environment if the Anaconda process terminates for some reason
`inst.sshd` - this makes it possible to log-in as root without password (!) to the installation environment

**Comment by martinpitt** [comment]
Right now, the most plausible cause is https://github.com/cockpit-project/cockpit/pull/17617#issuecomment-1205175023 - i.e. the new image does not have the webkit2gtk3 package.

**Comment by martinpitt** [comment]
Whoops -- it wasn't really the intention to close this just yet. Let's still keep it open to have the ongoing discussion, and only refresh this once the fix is in rawhide.

**Comment by martinpitt** [comment]
I did a point release last night. https://bodhi.fedoraproject.org/updates/FEDORA-2022-0bd441d073 is in testing now, still need to fight with the gating test a bit. But this should land today, so tomorrow we can try a new build.

**Comment by martinpitt** [comment]
I checked in a rawhide toolbox, and I don't see 274.1 yet. More waiting..

**Comment by martinpitt** [comment]
Another day, another "274.1 is still not available" issue. What on earth takes so long to get this on the mirrors?

**Comment by VladimirSlavik** [comment]
One word: branching.

**Comment by martinpitt** [comment]
@VladimirSlavik : I'm afraid I need a second word, or possibly even a third :grin: AFAIK this is just publishing/mirror delay. Fedora branches are not affected, this is only on rawhide for now.

**Comment by VladimirSlavik** [comment]
Oh, I would love to have more words as well...

**Comment by martinpitt** [comment]
274.1still not available on the mirrors..

**Comment by allisonkarlitskaya** [comment]
> 274.1still not available on the mirrors..

It's there!! :tada:

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-3696-20220815-132020/

**Comment by allisonkarlitskaya** [comment]
Let's have another go

```
boot.iso          16-Aug-2022 16:15           683743232
```

**Comment by allisonkarlitskaya** [comment]
i have no idea why the bots aren't picking this up.  I'm doing another go of it in #3743 and it seems to be working there.  *shrug*

**Pull request closed without merging**
