### PR TITLE
Image refresh for rhel-9-3

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-3
 * [x] image-refresh rhel-9-3

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-9-3 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-3-20231115-054208

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-3-20231115-054242.log

**Comment by martinpitt** [comment]
[testUserPasswords](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5548-20231115-054346-c070e88c-rhel-9-3-other-cockpit-project-cockpit-rhel-9.3/log.html#177-2) failure on "Password is longer than 256 characters". As there are *zero* changed packages on this image, retrying for comparison.

**Comment by martinpitt** [comment]
ooh, wait, that's the rhel-9.3 branch! We fixed that on cockpit main in https://github.com/cockpit-project/cockpit/pull/19591. But we don't really need this branch any more, I sent PR #5550 .

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
