### PR TITLE
Image refresh for rhel-8-10

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-10
 * [x] image-refresh rhel-8-10
 * [x] https://github.com/cockpit-project/cockpit/pull/20030
 * [x] backport it to rhel-8: https://github.com/cockpit-project/cockpit/pull/20033

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-8-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-10-20240213-225931

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-10-20240213-225959.log

**Comment by martinpitt** [comment]
Hmm, [this looks relevant](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5912-20240214-080542-98275447-rhel-8-10-other-cockpit-project-cockpit-rhel-8/log.html#102), and we probably need to deal with it:
```
logger.warning('WARN: BASIC authentication method is being deprecated. Please consider using CERT authentication method.')
```

**Comment by mvollmer** [comment]
Cockpit runs `insights-client --check-results`, which tries to write to stdout, but for some reason stdout is closed. It then spews the backtrace about EPIPE to stderr, which ends up in the journal.

I am not exactly sure what has changed. Maybe selinux closes stdout? Or maybe insights-client didn't write to stdout earlier.

The best fix would be to remove the call to `insights-client --check-result`, as it is hopefully no longer necessary.

**Comment by mvollmer** [comment]
> If that doesn't work, we can redirect stdout of insights-client to /dev/null.

insights-client --check-results is still neccessary, unfortunately: https://github.com/cockpit-project/cockpit/pull/20030

**Review by jelly — APPROVED** [review]

**Pull request merged**
