### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by martinpitt** [comment]
Oops, that needs some work in the cockpit debian files: https://fedorapeople.org/groups/cockpit/logs/pull-240-20191122-075050-314737b3-cockpit-project-cockpit--debian-testing/log.html

**Comment by martinpitt** [comment]
This is actually a lintian regression. I filed https://bugs.debian.org/945276 about it, let's give it a few days.

**Comment by martinpitt** [comment]
The lintian bug got fixed, should go into testing in 5 days.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-240-20191202-070303/

**Comment by martinpitt** [comment]
Retrying, fixed lintian is in testing.

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-240-20191202-070303/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-240-20191202-070808/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/bots/commits/image-refresh-debian-testing-20191202-073232

**Comment by martinpitt** [comment]
I think [this](https://209.132.184.41:8493/logs/pull-240-20191202-073737-86cf22bd-cockpit-project-cockpit--debian-testing/log.html#152-2) is a flake, retrying.

**Pull request merged**
