### PR TITLE
images: Install post-release updates on stable RHEL images

### PR DESCRIPTION
**Pull request by martinpitt**
RHEL 8 only gets updates via the /updates composes, and RHEL 9 up to 9.4 is also stable by now. This evolved totally wrong, despite the comment..

---

 * [x] image-refresh rhel-8-10
 * [x] image-refresh rhel-9-4

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-8-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-10-20240603-045516

**Comment by martinpitt** [comment]
Oh yes, this [picked up a whole lot of updates now](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-8-10-97751f17-20240603-043406/log.html). These are the whole point of refreshing post-release images regularly.

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-4-97751f17-20240603-045616/log.html

**Comment by cockpituous** [comment]
image-refresh rhel-9-4 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-4-20240603-053951

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-4-97751f17-20240603-052103/log.html

**Comment by martinpitt** [comment]
[9.4 now also got a lot of updates](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-4-97751f17-20240603-052103/log.html). Let's hope they didn't break anything :sweat_smile:

**Review by jelly — APPROVED** [review]

**Pull request merged**
