### PR TITLE
Image refresh for fedora-31

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-31
 * [x] image-refresh fedora-31

### CODE REVIEW

**Comment by martinpitt** [comment]
I rebased this to current master to get the disk IO fixes and latest service image.

**Comment by martinpitt** [comment]
This breaks `MachinesStoragePoolTestSuite.testAddAllPhysicalDiskDevice` selenium tests on all browsers.

**Comment by marusak** [comment]
Sent https://github.com/cockpit-project/cockpit/pull/14081 where I drop selenium tests that we don't care about anymore.

**Comment by martinpitt** [comment]
The selenium fix landed in the 8.2 branch. This is stale, let's build a new one.

**Pull request closed without merging**
