### PR TITLE
naughty: drop the motd-wheel workaround

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
The upstream pam patch just landed in Fedora 32.

Fixes #1412

 * [x] image-refresh fedora-32

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-1472-20201216-073232/

**Comment by cockpituous** [comment]
image-refresh fedora-32 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-32-20201216-075454

**Comment by allisonkarlitskaya** [comment]
The cockpit-podman fail is almost certainly related to the upstream podman v2.2.1 release:

```
$ ./image-diff fedora-32-998c9b1228891f7d7c51f006fc6c83c53d333060bdece9f14a4c0ffcbf05983f.qcow2 fedora-32-9a4530a00b40f734b97cce0dcbfa399b1e2153d9a6103c2e76c540d4c52b23c3.qcow2
...
  podman (2:2.1.1-7.fc32 -> 2:2.2.1-1.fc32)
  podman-plugins (2:2.1.1-7.fc32 -> 2:2.2.1-1.fc32)
```

https://github.com/containers/podman/releases/tag/v2.2.1

Lots of changes there, and landed just landed in this image for the first time.  I'd guess that our other images will start breaking as well, once this version sees wider distribution.

**Comment by marusak** [comment]
> The cockpit-podman fail is almost certainly related to the upstream podman v2.2.1 release (8 days ago):

Yeah, I saw this in gating and then also in c-podman repo. I started to look into it yesterday but had not enough time: https://github.com/cockpit-project/cockpit-podman/issues/619 . I was expecting when we get image refresh and it will get broken also in F32 and F33 images. It seems from what I saw that user service times out after minute or so thus taking down event listener we have set up. Weirdly it works fine on my machine.

**Comment by marusak** [comment]
I sent https://github.com/containers/podman/issues/8751 but if there is not workaround we can use in the meantime, this is gonna be hopeless as the whole podman is pretty much unusable (once again).

**Comment by allisonkarlitskaya** [comment]
I'm inclined to treat this situation as a naughty.

**Comment by marusak** [comment]
> I'm inclined to treat this situation as a naughty.

I am getting very close to having fix in https://github.com/cockpit-project/cockpit-podman/pull/624

**Review by marusak — APPROVED** [review]

**Pull request merged**
