### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by martinpitt** [comment]
Several failures due to new SELinux violation:

> audit: type=1400 audit(1623381106.279:360): avc:  denied  { getattr } for  pid=1784 comm="mdadm" path="/dev/dma_heap" dev="devtmpfs" ino=127 scontext=system_u:system_r:mdadm_t:s0-s0:c0.c1023 tcontext=system_u:object_r:dma_device_dir_t:s0 tclass=dir permissive=0

**Comment by martinpitt** [comment]
Introduced in https://bodhi.fedoraproject.org/updates/FEDORA-2021-d8e34dbd6e which got pushed through updates-testing in less than a day (argh!)

Reported as https://bugzilla.redhat.com/show_bug.cgi?id=1970744

**Comment by martinpitt** [comment]
Pattern updated. As that version is already in updates now, I let it apply to fedora-34 and rhel-9-0 as well.

**Comment by martinpitt** [comment]
I meddled with this, so don't want to self-approve.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
