### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by marusak** [comment]
ups, every firewall tests fails with `subprocess.CalledProcessError: Command 'virsh net-list | grep -qw default || virsh net-start default' returned non-zero exit status 1.`. This must be due to https://github.com/cockpit-project/cockpit/pull/13720

**Comment by martinpitt** [comment]
Indeed, and starting it fails with `error: Failed to start network default`. I've also seen this in another fedora-31 or -32 run today. I couldn't reproduce it yet, but I'll look into that ASAP.

**Comment by martinpitt** [comment]
[still failing kdump](https://logs.cockpit-project.org/logs/pull-638-20200315-174718-d9b38edb-fedora-testing-cockpit-project-cockpit/log.html). This is known issue #629, I just forgot to add it for f-testing as well.

**Comment by martinpitt** [comment]
I :-1:  'ed  https://bodhi.fedoraproject.org/updates/FEDORA-2020-b36b25de24and added the naughty here. I also updated the downstream bug https://bugzilla.redhat.com/show_bug.cgi?id=1812393 and reassigned it to dracut.

**Pull request merged**
