### PR TITLE
Fix fedora-coreos updates

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh fedora-coreos

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-05.
Log: https://209.132.184.41:8493/logs/image-refresh-286-20191128-151111/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-286-20191128-151111/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-286-20191128-152121/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-286-20191128-152121/

**Comment by martinpitt** [comment]
```
Updating metadata for 'updates'...done
error: cannot update repo 'updates': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Downloading successful, but checksum doesn't match. Calculated: 
```

That looked like a  transient network glitch first, but it now happened twice in a row..

**Comment by martinpitt** [comment]
My local image build just finished (again) successfully, so let's try this again

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-04.
Log: https://209.132.184.41:8493/logs/image-refresh-286-20191128-155353/

**Comment by cockpituous** [comment]
image-refresh fedora-coreos done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-coreos-20191128-160303

**Pull request merged**
