### PR TITLE
images: add python3-pcp for RHEL images

### PR DESCRIPTION
**Pull request by jelly**
The Python rewrite of cockpit-pcp is underway and to help development and testing add the new runtime dependency.

 * [x] image-refresh rhel-9-5
 * [x] https://github.com/candlepin/subscription-manager-cockpit/pull/80

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-10-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-10-0-20240822-150951

**Comment by cockpituous** [comment]
image-refresh rhel-10-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-10-0-20240822-151111

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-10-0-85478484-20240822-145430/log.html

**Comment by cockpituous** [comment]
image-refresh rhel-9-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-5-20240822-152713

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-5-85478484-20240822-150957/log.html

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-85478484-20240822-153056/log.html

**Comment by martinpitt** [comment]
Just to make sure, you *only* want this as a runtime dependency, not a build-time one (`BuildRequires:`), right? I.e. `pytest` should be able to skip the pcp unit tests. (This is fine for me)

Tests are an absolute disaster.. :cry: this is definitively a "yell very loudly on Monday" thing.

**Comment by jelly** [comment]
> Just to make sure, you _only_ want this as a runtime dependency, not a build-time one (`BuildRequires:`), right? I.e. `pytest` should be able to skip the pcp unit tests. (This is fine for me)

Yes

> Tests are an absolute disaster.. 😢 this is definitively a "yell very loudly on Monday" thing.

Ugh, kinda feared that. Should I split it up?

**Comment by martinpitt** [comment]
@ptoscano Can you please have a look at the three sub-man regressions on RHEL 10? [sub-man](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6775-3e1c8c3a-20240822-173057-rhel-10-0-candlepin-subscription-manager/log.html), [sub-man-cockpit](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6775-3e1c8c3a-20240822-173100-rhel-10-0-candlepin-subscription-manager-cockpit/log.html#4), and [on rhel-9-5](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6775-3e1c8c3a-20240822-173055-rhel-9-5-subscription-manager-1.29-candlepin-subscription-manager-cockpit/log.html) ? Same test, and same failed assertion, but slightly different failure mode -- one screenshot has a popup alert ("Failure in name resolution"), the other doesn't.

@jelly I take a look at the c10s failures first, they also break TF runs. As this is such a mess, I suggest to only take one image refresh here, and handle the other images in separate PRs.

**Comment by martinpitt** [comment]
Most of the centos-10 regressions are explained by the new kernel breaking journal logging. I reported this as https://issues.redhat.com/browse/RHEL-56025 . This has a reasonably straightforward workaround, however, it's not the full story as the [TF failures show](https://artifacts.dev.testing-farm.io/ce4faf33-38b4-41cf-b524-806bd95b2d04/). However, let's do another refresh with that fix, and see where we land.

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240826-032738

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-4bce68a3-20240826-030943/log.html

**Comment by cockpituous** [comment]
image-refresh rhel-10-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-10-0-20240826-034313

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-10-0-4bce68a3-20240826-032747/log.html

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240826-075906

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-4779053a-20240826-074228/log.html

**Comment by cockpituous** [comment]
image-refresh rhel-10-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-10-0-20240826-081522

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-10-0-4779053a-20240826-075913/log.html

**Comment by martinpitt** [comment]
OK, there's no sense in trying to hack around this. This is broken beyond our reach. https://issues.redhat.com/browse/RHEL-54549 is likely a duplicate and points to some more root causes. So this is just broken for now. I'll still keep the cleanup commit, and let's consider RHEL 10 as "broken" and rebuilds as blocked. Let's instead try to refresh rhel 9.5 so that @jelly has something to play with for pcp?

**Comment by cockpituous** [comment]
image-refresh rhel-9-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-5-20240826-084927

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-5-ca684ffd-20240826-083232/log.html

**Comment by martinpitt** [comment]
So it's just that sub-man regression now. @ptoscano can you please have a look?

**Comment by ptoscano** [comment]
> So it's just that sub-man regression now. @ptoscano can you please have a look?

It's due to recent changes in insights-client that appeared few days ago in RHEL composes; see https://github.com/candlepin/subscription-manager-cockpit/pull/80 for a longer explanation and hopefully a fix (reviewer welcome, my JS is non-existent).

**Pull request merged**
