### PR TITLE
images: update spec file location for cockpit

### PR DESCRIPTION
**Pull request by jelly**
Cockpit no longer ships cockpit.spec.in which is replaced by a normal
spec file and no longer replaces BUILD_ALL as removing unrequired build
packages is now done by image-prepare. This was done in 6fe66f0 and
ec81f06 in cockpit.

 * [x] image-refresh fedora-35

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3520-20220617-074040/

**Comment by cockpituous** [comment]
image-refresh fedora-35 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-35-20220617-080635

**Comment by jelly** [comment]
The cockpit-machines issue seems related to iscsi, locally it fails in a different way, the test passes but the cleanup fails:

```
killing ssh master process 392787
Traceback (most recent call last):
  File "/home/jelle/projects/cockpit-bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'targetcli /backstores/ramdisk delete test && targetcli /iscsi delete iqn.2019-09.cockpit.lan && (iscsiadm -m node -o delete || true)' returned non-zero exit status 1.
```

**Comment by jelly** [comment]
```
> warning: Error mounting system-managed device /dev/dm-0: Filesystem type (null) not configured in kernel.
```

Seems not a flake but a real issue.

**Review by marusak — APPROVED** [review]
Nice, thank you!

**Pull request merged**
