### PR TITLE
images: Install tcsh on Fedora images

### PR DESCRIPTION
**Pull request by martinpitt**
We need to test (and fix) logging in with tcsh, see
https://github.com/cockpit-project/cockpit/issues/14060

 * [x] image-refresh fedora-31
 * [x] image-refresh fedora-32
 * [ ] https://github.com/cockpit-project/cockpit-podman/pull/415 (ready to land, together with this PR)

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-1037-20200702-050909/

**Comment by cockpituous** [comment]
image-refresh fedora-31 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-31-20200702-053838

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-1037-20200702-053838/

**Comment by cockpituous** [comment]
image-refresh fedora-32 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-32-20200702-060606

**Comment by martinpitt** [comment]
Fedora 32 got podman 2.0 now, which [breaks cockpit-podman](https://logs.cockpit-project.org/logs/pull-1037-20200702-071104-e352e510-fedora-32-cockpit-project-cockpit-podman/log.html). This needs an upstream bug report and a naughty. :sob:

**Comment by marusak** [comment]
podman investigation:
1. Format of podman inspect has changed:
```
$ sudo podman inspect --format '{{.NetworkSettings.Ports}}' busybox-with-tty
# With podman-2.0:
map[5000/tcp:[{ 6000}] 5001/udp:[{ 6001}] 8001/tcp:[{ 8001}]]
# With podman 1.8:
[{6000 5000 tcp } {6001 5001 udp }]
```

**Comment by marusak** [comment]
Still draft, any reason for that?

**Comment by martinpitt** [comment]
@marusak: Not inherently, but there is [still one podman test](https://logs.cockpit-project.org/logs/pull-1037-20200702-075727-e352e510-fedora-32-cockpit-project-cockpit-podman/log.html#8-2) which seems to be broken by the new podman?

**Comment by martinpitt** [comment]
@marusak : Ah wait, no -- it succeeded in https://github.com/cockpit-project/cockpit-podman/pull/415 , so unrelated flake, I take it. So, that plus 415 are ready to go in.

**Pull request merged**
