### PR TITLE
Introduce rhel-8-6 image

### PR DESCRIPTION
**Pull request by KKoukiou**
* [x] image-refresh rhel-8-6

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2432-20210921-123939/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-2432-20210921-123939/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-2432-20210921-125959/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-2432-20210921-125959/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-2432-20210921-163333/

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20210921-165252

**Comment by KKoukiou** [comment]
I just run the tests OOI - they are still all in manual trigger mode - do you want to take a look at the new image scrpits @martinpitt ?

**Comment by martinpitt** [comment]
Looks good, thanks! Can you please add a bunch of rhel-8-6 runs to project's `_manual` test maps? Then we can enable stuff one by one. Tests are not going to work yet as they don't recognize special cases for `rhel-8-6` yet.

**Comment by KKoukiou** [comment]
> Looks good, thanks! Can you please add a bunch of rhel-8-6 runs to project's `_manual` test maps? Then we can enable stuff one by one. Tests are not going to work yet as they don't recognize special cases for `rhel-8-6` yet.

I added already to cockpit-machines and cockpit itself. I can sure add to all that run on rhel images sure. That's what you mean?

**Review by martinpitt — COMMENTED** [review]
Ah right, missed that. Thanks! I'll do a quick local smoke test with the new image, and then land that.

**Review by martinpitt — APPROVED** [review]
`TEST_OS=rhel-8-6 make check` in starter-kit passes, so this qualifies the image as "not totally broken". Cheers!

**Pull request merged**
