### PR TITLE
Pre-install basic cockpit packages and podman images on Fedora images

### PR DESCRIPTION
**Pull request by martinpitt**
This will make cockpit-podman image preparation offline, faster, and more reliable.

 * [x] image-refresh fedora-32
 * [x] image-refresh fedora-33
 * [x] Fix bug #14133: https://github.com/cockpit-project/cockpit/pull/14943
 * [x] Bump test/common dependency in cockpit-composer after releasing cockpit 233: https://github.com/osbuild/cockpit-composer/pull/1176
 * [x] Bump test/common dependency in cockpit-certificates after releasing cockpit 233: https://github.com/skobyda/cockpit-certificates/pull/27
 * [x] (not a blocker, but cleanup): Drop hack and bump test/common dependency in starter-kit: https://github.com/cockpit-project/starter-kit/pull/396
 * [x] Blocked on fedora-33 refresh: PR #1403

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-1407-20201122-071515/

**Comment by cockpituous** [comment]
image-refresh fedora-32 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-32-20201122-073737

**Comment by martinpitt** [comment]
Image build log looks as expected: It installs the correct set of packages and pulls the quay.io container images. I'll give the new image a spin to test for runtime regressions. However, I expect this to be blocked for a few days until #1403 gets resolved.

**Comment by martinpitt** [comment]
Argh, bug 14133 bites again..

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-1407-20201126-053333/

**Comment by cockpituous** [comment]
image-refresh fedora-33 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-33-20201126-055353

**Comment by martinpitt** [comment]
[weird log writing failure](https://logs.cockpit-project.org/logs/pull-1407-20201126-142831-f9d58d67-fedora-32-selenium-firefox-cockpit-project-cockpit-rhel-7.9/log.html#16) in fedora-32/selenium-firefox@cockpit-project/cockpit/rhel-7.9, retrying

**Comment by martinpitt** [comment]
The rhel-7.9 firefox failure is nothing new, it already happened in the last f32 refresh in #1389. So this does need to be investigated, but I'd appreciate if we could not block these image refreshes on that?

**Review by mvollmer — APPROVED** [review]

**Pull request merged**
