### PR TITLE
images: Install a snap on the Ubuntus

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh ubuntu-stable
 * [x] image-refresh ubuntu-2004
 * [x] image-refresh ubuntu-2204

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-3140-20220324-150000/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20220324-152727

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3140-20220324-152727/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3140-20220324-152727/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3140-20220324-153939/

**Comment by martinpitt** [comment]
@marusak : This happened after your commit 41f34a369c9bcb96, and yet it auto-triggered tests (against the main branch) :cry:

**Comment by martinpitt** [comment]
The ubuntu-2004 refresh failure:
```
+ podman pull quay.io/libpod/busybox
/var/lib/testvm/podman-images.setup: line 6: podman: command not found
```

is fallout from PR #3111 -- this only refreshed one image. This needs to be conditionalized to not happen on ubuntu-2004.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3140-20220325-072626/

**Comment by mvollmer** [comment]
> This needs to be conditionalized to not happen on ubuntu-2004.

See #3143

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3140-20220325-072626/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-3140-20220325-135252/

**Comment by martinpitt** [comment]
#3142 landed. Please rebase, fix the conflict, and rebuild the ubuntu images.

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3140-20220325-135252/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3140-20220325-141919/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20220325-152929

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3140-20220328-060505/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2004 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2004-20220328-062424

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-3140-20220328-062424/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3140-20220328-062424/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2204 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2204-20220328-064343

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
