### PR TITLE
images: Mock config for centos-8-stream is called centos-stream-8 now

### LINKED ISSUE #1747: Image refresh for centos-8-stream
Image refresh for centos-8-stream
 * [ ] FAIL: image-refresh centos-8-stream

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh centos-8-stream

Fixes #1747

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-1750-20210305-095151/

**Comment by martinpitt** [comment]
Oh, because centos stream 9 is now also a thing, of course.. Thanks!

**Comment by mvollmer** [comment]
> Oh, because centos stream 9 is now also a thing, of course.. Thanks!

Or is that centos 9 stream?

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20210305-101616

**Review by martinpitt — APPROVED** [review]
Cheers!

**Comment by martinpitt** [comment]
I added "Fixes#" to the description so that the failed bot refresh will be auto-closed.

**Pull request merged**
