### PR TITLE
images: Get freeipa-server container image from its native home on quay

### PR DESCRIPTION
**Pull request by mvollmer**
We don't need to mirror it.

 * [x] image-refresh services

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-1429-20201202-112727/

**Comment by cockpituous** [comment]
image-refresh services done: https://github.com/cockpituous/bots/commits/image-refresh-services-20201202-121010

**Review by martinpitt — COMMENTED** [review]
Very nice, thanks! You still need to push the rebuilt image and the Closes#, and make sure that tests are happy.

**Comment by mvollmer** [comment]
The fedora-32/firefox@osbuild/cockpit-composer failures look strange, and not related.  I can reproduce this locally, so I have a closer look.

**Comment by martinpitt** [comment]
fedora-32/firefox@osbuild/cockpit-composer> Uh, wow -- is that a broken bot somehow?

**Review by martinpitt — APPROVED** [review]
Cheers! I'm glad to eventually lose these mirrors again, when upstream projects move to someplace else.

**Comment by mvollmer** [comment]
> fedora-32/firefox@osbuild/cockpit-composer> Uh, wow -- is that a broken bot somehow?

This also happens in their own CI runs: https://github.com/osbuild/cockpit-composer/pull/1182

I can get most tests to pass with the little patch I posted, but there are still some failures left.  I think we can ignore fedora-32/firefox@osbuild/cockpit-composer here.

**Comment by mvollmer** [comment]
>  I think we can ignore fedora-32/firefox@osbuild/cockpit-composer here.

(since we have enough proof that the "services" image is ok.)

**Pull request merged**
