### PR TITLE
Image refresh for rhel-8-5

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-5
 * [x] image-refresh rhel-8-5
 * [ ] libvirt/qemu complete failure: https://bugzilla.redhat.com/show_bug.cgi?id=1961562 ; need to postpone image refresh until this gets fixed

### CODE REVIEW

**Comment by KKoukiou** [comment]
Missing kvdo kernel module.

**Comment by martinpitt** [comment]
[cockpit-machines failures](https://logs.cockpit-project.org/logs/pull-2020-20210517-150150-d470d5b6-rhel-8-5-cockpit-project-cockpit-machines/log.html) are some general regression in 8.5, we see the same thing in the most recent downstream package update. I'll look at that part.

**Comment by mvollmer** [comment]
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1961562 is ON_QA since today.

**Comment by martinpitt** [comment]
The downstream bug was verified. Closing this PR, let's let the bots build a new one.

**Pull request closed without merging**
