### PR TITLE
machine_core: Use rsync for uploading, with scp fallback

### LINKED ISSUE #3639: Image refresh for rhel-8-5 - fixed in #3640
Image refresh for rhel-8-5
 * [ ] FAIL: image-refresh rhel-8-5

### PR DESCRIPTION
**Pull request by martinpitt**
Uploading directories is now between a rock and a hard place:

 * The scp protocol has been deprecated for a long time, and current
   (Fedora 36+) OpenSSH versions now provide an "scp" which emulates the 
   old CLI using sftp.

 * sftp `put -r` (uploading directories) in RHEL up to 8.6 is broken, it
   always fails with "Unable to canonicalize path".

 * rsync works much better, and is one of the recommended successors of
   scp. But some cloud images (such as Debian) don't ship rsync.

So for the time being, move to rsync in upload() by default, but provide
a fallback to scp. This will fix image refreshes for rhel-8.{4,5,6}, and 
start the path of migrating to rsync. Over time, we can add some
cloud-init tricks to always install rsync, and only use that.

----

Fixes #3639

See image-refresh in #3639 ([log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1449-20220720-130855-73f81506-rhel-8-6/log.html)) and the same error in [c-composer](https://github.com/osbuild/cockpit-composer/pull/1449).

 * [x] image-refresh rhel-8-5
 * [x] image-refresh debian-stable
 * [x] image-refresh fedora-coreos
 * https://github.com/cockpit-project/cockpit-podman/pull/1053
 * https://github.com/candlepin/subscription-manager/pull/3089

Of course we eventually want to replace the scp in download() and download_dir() as well. But given how complicated this is, I'd rather avoid making this even bigger/more dependent than it already is.

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-3640-20220721-073333/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3640-20220721-073333/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-3640-20220721-074141/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-3640-20220721-074646/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3640-20220721-074747/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-3640-20220721-074747/

**Comment by cockpituous** [comment]
image-refresh rhel-8-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-5-20220721-081514

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-6.
Log: https://logs.cockpit-project.org/logs/image-refresh-3640-20220721-081515/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-3640-20220721-081515/

**Comment by cockpituous** [comment]
image-refresh rhel-8-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-5-20220721-084314

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-3640-20220721-084343/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20220721-090332

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-3640-20220721-090303/

**Comment by cockpituous** [comment]
image-refresh fedora-coreos done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-coreos-20220721-091443

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-3640-20220721-091414/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by martinpitt** [comment]
possible approach: create the target directory in advance, and

    echo 'put -r images/scripts/lib/*' | sftp -P 2201 c:/var/lib/testvm/

**Comment by martinpitt** [comment]
The [sub-man-1.28.21 failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3640-20220725-045106-a60ac424-rhel-8-5-candlepin-subscription-manager-subscription-manager-1.28.21/log.html) is unrelated, that broke with moving cockpit/tasks to Fedora 36. I sent https://github.com/candlepin/subscription-manager/pull/3089 for it.

**Review by marusak — APPROVED** [review]
Phew, thanks for digging into it!

**Pull request merged**
