### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20241024-225230

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-02cf2c63-20241024-224039/log.html

**Comment by martinpitt** [comment]
[sssd regression](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7028-5f7cf6f0-20241024-225343-arch-other-cockpit-project-cockpit/log.html), this looks real. One retry for comparison.

**Comment by jelly** [comment]
Should be fixed in -2 https://gitlab.archlinux.org/archlinux/packaging/packages/sssd/-/commit/78b09c53e4e4f86e058f766c2029504f787ca623

**Comment by jelly** [comment]
Let's re-refresh.

**Pull request closed without merging**
