### PR TITLE
Image refresh for debian-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-stable
 * [x] image-refresh debian-stable

### CODE REVIEW

**Comment by martinpitt** [comment]
[storage failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3849-20220910-224701-d4f2b351-debian-stable-cockpit-project-cockpit/log.html#214-2) looks like a flake, retrying to compare.

**Comment by martinpitt** [comment]
No, this is a real regression.

**Comment by mvollmer** [comment]
I was only able to get this to fail once locally.  My best guess is that during the teardown phase of deletion (unmounting, removing entry from fstab), systemd has for some reason mount the partition back, and then deleting it failed.  This condition somehow persistet for the next retries.

Systemd mounting things unexpectedly is happening in other places, as well, and we try to combat it by reloading the daemon after changing fstab, which is something that should be done anyway, I guess.

So I don't think this is a regression, we just got very unlucky.

I'll retry once more here, and also make a PR to reload systemd after all tear-down actions.

**Review by mvollmer — APPROVED** [review]

**Comment by martinpitt** [comment]
Ah, third time is the charm then!

**Pull request merged**
