### PR TITLE
Image refresh for centos-7

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-7
 * [x] work around `mock --shell` breakage: https://bugzilla.redhat.com/show_bug.cgi?id=1976702
 * [x] image-refresh centos-7

### CODE REVIEW

**Comment by martinpitt** [comment]
Uh, [what??](https://logs.cockpit-project.org/logs/pull-2145-20210626-023918-c30bd3d7-centos-7-cockpit-project-cockpit-rhel-7.9/log.html) -- can we please stop breaking old stable releases? sigh

    /usr/bin/systemd-nspawn: unrecognized option '--chdir=/builddir'

**Comment by martinpitt** [comment]
This is a regression from [mock (2.10-1.el7 -> 2.11-1.el7)
](https://koji.fedoraproject.org/koji/buildinfo?buildID=1763874):
```
$ mock --shell true
[...]
/usr/bin/systemd-nspawn: unrecognized option '--chdir=/builddir'
```

from [this upstream commit](https://github.com/rpm-software-management/mock/commit/707da91681b73398ce11c931c09b1c99004be3be) -- In CentOS 7, systemd-nspawn does not have a `--chdir` option yet.

I reported this downstream to https://bugzilla.redhat.com/show_bug.cgi?id=1976702

`--isolation=simple` works around this, but it's awkward having to do that on every OS. We could introduce an "override options" variable, but this image refresh is not important -- let's give it a week or so for the mock maintainer to fix the regression.

**Comment by KKoukiou** [comment]
systemd did not get updated in this image according to the logs, so I am unsure what caused this regression.

**Comment by martinpitt** [comment]
@KKoukiou : See my comment above your's and the bz link. It's a regression in mock.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-2145-20210706-123232/

**Comment by martinpitt** [comment]
I added a workaround, rebuilding the image.

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-7-20210706-130707

**Comment by martinpitt** [comment]
Seems the new image [breaks NFS](https://logs.cockpit-project.org/logs/pull-2145-20210706-132035-7c337cee-centos-7-cockpit-project-cockpit-rhel-7.9/log.html#131-2) somehow? That's unexpected, the only changes on that image are mock and the distribution GPG keys.

**Comment by martinpitt** [comment]
There is no significant difference in `testNfsBusy()` between main and rhel-7.9, and yet it failed three times in a row on the "busy" dialog never closing. But I can reproduce this locally, so not just a flake.

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
