### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-3309-20220502-114444/

**Comment by jelly** [comment]
Image not uploaded successfully retrying.

**Comment by cockpituous** [comment]
Task threw an exception: https://logs.cockpit-project.org/logs/image-refresh-3309-20220502-114444/

**Comment by jelly** [comment]
Re-committed the initial image, now the tests succeed.

**Review by jelly — APPROVED** [review]

**Review by martinpitt — APPROVED** [review]
Nice! (FTR, you could have self-approved, as it's just the bots commit)

**Pull request merged**
