### PR TITLE
images: Keep kernel-headers installed

### PR DESCRIPTION
**Pull request by martinpitt**
On latest fedora-rawhide, qemu-kvm-core depends on kernel-headers, and thus gets removed alongside. This breaks cockpit-machines testing.

This was just a little optimization for image size, not important.

---

See the [recent image refresh log](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-20240123-225555.log) and search for "kernel-headers" to see what's going on.

 * [x] image-refresh fedora-rawhide

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-20240125-122814

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-20240125-122828.log

**Comment by martinpitt** [comment]
OK, the ["Added:" list in the log](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-20240125-122828.log) looks as intended.

**Review by jelly — APPROVED** [review]
Thanks!

**Pull request merged**
