### PR TITLE
Image refresh for fedora-33

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-33
 * [x] image-refresh fedora-33

### CODE REVIEW

**Comment by martinpitt** [comment]
@larskarlitski, @henrywang : The composer testOSTree test is broken. This is apparently a change/regression in current Fedora 33, as recent c-composer PRs against the current image work. I already retried it, same result. Can you please have a look?

**Comment by henrywang** [comment]
@martinpitt, thanks. Working on that.

**Comment by henrywang** [comment]
@allisonkarlitskaya, all tests passed. We can land this PR now.

**Review by allisonkarlitskaya — APPROVED** [review]
<xiaofwan> allison: we can land 1403 now.

**Pull request merged**
