### PR TITLE
Arch workaround growpart bug 

### PR DESCRIPTION
**Pull request by jelly**
* [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20230626-082214

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20230626-082222.log

**Comment by jelly** [comment]
```
error: failed retrieving file 'perl-json-4.10-1-any.pkg.tar.zst' from geo.mirror.pkgbuild.com : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'perl-json-4.10-1-any.pkg.tar.zst' from mirror.rackspace.com : Resolving timed out after 10001 milliseconds
error: failed retrieving file 'perl-json-4.10-1-any.pkg.tar.zst' from mirror.leaseweb.net : Resolving timed out after 10000 milliseconds
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
```

**Comment by jelly** [comment]
We did not drop these dependencies from main:

```
tools/arch/PKGBUILD:makedepends=(krb5 libssh accountsservice perl-json perl-locale-po json-glib glib-networking
tools/arch/PKGBUILD:  depends=(krb5 libssh accountsservice perl-json perl-locale-po json-glib glib-networking python)
```

**Comment by jelly** [comment]
The machines failure sounds like the detection of the python bridge went wrong

https://cockpit-logs.us-east-1.linodeobjects.com/pull-4930-20230626-085311-fa717020-arch-cockpit-project-cockpit-machines/log.html#45-2

**Comment by jelly** [comment]
Blocked by https://github.com/cockpit-project/cockpit/pull/19016

**Comment by jelly** [comment]
Changed:

```
Changed:
  bind (9.18.15-1 -> 9.18.16-1)
  btrfs-progs (6.3.1-1 -> 6.3.2-1)
  cockpit (293-1 -> 294.1-3)
  duktape (2.7.0-5 -> 2.7.0-6)
  firewalld (1.3.2-1 -> 1.3.3-1)
  glib-networking (1:2.76.0-1 -> 1:2.76.0-2)
  grub (2:2.06.r499.ge67a551a4-1 -> 2:2.06.r566.g857af0e17-1)
  iana-etc (20230405-1 -> 20230524-1)
  kbd (2.5.1-2 -> 2.6.0-1)
  libcups (1:2.4.5-1 -> 1:2.4.6-1)
  libmd (1.0.4-1 -> 1.1.0-1)
  libpng (1.6.39-1 -> 1.6.40-1)
  libproxy (0.4.18-3 -> 0.5.2-1)
  libssh2 (1.10.0-3 -> 1.11.0-1)
  libtraceevent (1:1.7.2-1 -> 1:1.7.3-1)
  libtracefs (1.6.4-2 -> 1.7.0-1)
  libx11 (1.8.5-2 -> 1.8.6-1)
  linux (6.3.7.arch1-1 -> 6.3.9.arch1-1)
  mesa (23.1.2-1 -> 23.1.3-1)
  parallel (20230522-1 -> 20230622-1)
  pcsclite (1.9.9-3 -> 2.0.0-1)
  systemd (253.5-1 -> 253.5-2)
  systemd-libs (253.5-1 -> 253.5-2)
  systemd-sysvcompat (253.5-1 -> 253.5-2)
  tracer (0.7.8-3 -> 0.7.11-1)
  util-linux (2.39-8 -> 2.39-10)
  util-linux-libs (2.39-8 -> 2.39-10)
  vim (9.0.1572-1 -> 9.0.1628-1)
  vim-runtime (9.0.1572-1 -> 9.0.1628-1)
  wolfssl (5.6.2-1 -> 5.6.3-1)
  xorgproto (2023.1-1 -> 2023.2-1)
```

Build issue:

```
python3 -m pip install --no-index --force-reinstall --root='/build/cockpit/pkg/cockpit/' --prefix='/usr' \
        "$(python3 '.'/src/build_backend.py --wheel '.' tmp/wheel)"
Processing ./tmp/wheel/cockpit-294.1.dev70+g13ddbf090-py3-none-any.whl
Installing collected packages: cockpit
  Attempting uninstall: cockpit
    Found existing installation: cockpit 294.1
    Uninstalling cockpit-294.1:
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/bin/cockpit-bridge'
Consider using the `--user` option or check the permissions.

```

**Comment by jelly** [comment]
Machines failures are leftover:

```
> error: Failed to get libvirt version from the dbus API:Cannot recv data: Connection reset by peer
Exception ignored in: <coroutine object DBusChannel.setup_path_watch.<locals>.handler at 0x7ff95c13b060>
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/cockpit/channels/dbus.py", line 419, in handler
async with self.watch_processing_lock:
File "/usr/lib/python3.11/asyncio/locks.py", line 21, in __aexit__
self.release()
File "/usr/lib/python3.11/asyncio/locks.py", line 138, in release
self._wake_up_first()
File "/usr/lib/python3.11/asyncio/locks.py", line 155, in _wake_up_first
fut.set_result(True)
File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
self._check_closed()
File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Wrote JS log to TestMachinesLifecycle-testBasicAdminUser-arch-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesLifecycle-testBasicAdminUser-arch-127.0.0.2-2301-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/machineslib.py", line 405, in tearDown
    super().tearDown()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1630, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1861, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Exception ignored in: <coroutine object DBusChannel.setup_path_watch.<locals>.handler at 0x7ff95c13b060
```

```
  bind (9.18.15-1 -> 9.18.16-1)
  btrfs-progs (6.3.1-1 -> 6.3.2-1)
  cockpit (293-1 -> 294.1-3)
  duktape (2.7.0-5 -> 2.7.0-6)
  firewalld (1.3.2-1 -> 1.3.3-1)
  glib-networking (1:2.76.0-1 -> 1:2.76.0-2)
  grub (2:2.06.r499.ge67a551a4-1 -> 2:2.06.r566.g857af0e17-1)
  iana-etc (20230405-1 -> 20230524-1)
  kbd (2.5.1-2 -> 2.6.0-1)
  libcups (1:2.4.5-1 -> 1:2.4.6-1)
  libmd (1.0.4-1 -> 1.1.0-1)
  libpng (1.6.39-1 -> 1.6.40-1)
  libproxy (0.4.18-3 -> 0.5.2-1)
  libssh2 (1.10.0-3 -> 1.11.0-1)
  libtraceevent (1:1.7.2-1 -> 1:1.7.3-1)
  libtracefs (1.6.4-2 -> 1.7.0-1)
  libx11 (1.8.5-2 -> 1.8.6-1)
  linux (6.3.7.arch1-1 -> 6.3.9.arch1-1)
  mercurial (6.4.4-1 -> 6.4.5-1)
  mesa (23.1.2-1 -> 23.1.3-1)
  parallel (20230522-1 -> 20230622-1)
  pcsclite (1.9.9-3 -> 2.0.0-1)
  systemd (253.5-1 -> 253.5-2)
  systemd-libs (253.5-1 -> 253.5-2)
  systemd-sysvcompat (253.5-1 -> 253.5-2)
  tracer (0.7.8-3 -> 0.7.11-1)
  util-linux (2.39-8 -> 2.39-10)
  util-linux-libs (2.39-8 -> 2.39-10)
  vim (9.0.1572-1 -> 9.0.1628-1)
  vim-runtime (9.0.1572-1 -> 9.0.1628-1)
  vulkan-icd-loader (1.3.251-1 -> 1.3.255-1)
  wolfssl (5.6.2-1 -> 5.6.3-1)
  xorgproto (2023.1-1 -> 2023.2-1)
```

**Comment by martinpitt** [comment]
@jelly : That is https://github.com/cockpit-project/cockpit/issues/18355 and our testlib [already allows it](https://github.com/cockpit-project/cockpit/blob/main/test/common/testlib.py#L1792). I suppose that pattern needs a little adjustment for machines?

**Comment by jelly** [comment]
> @jelly : That is [cockpit-project/cockpit#18355](https://github.com/cockpit-project/cockpit/issues/18355) and our testlib [already allows it](https://github.com/cockpit-project/cockpit/blob/main/test/common/testlib.py#L1792). I suppose that pattern needs a little adjustment for machines?

Ah interesting, good catch!

**Comment by jelly** [comment]
**UGH**, our machines `test/common is 355c0aa59e3991243e10a61183e62ea129d3261a while the fix was in 43c3606ed4.

I don't think we can willy nilly update but let's try. Otherwise we patch machines.

**Review by martinpitt — APPROVED** [review]
Great work @jelly , thanks!

**Pull request merged**
