### PR TITLE
images: remove some dependencies from Fedora

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
At 228MB installed size, glibc-all-langpacks is the single largest thing
in our images.  Remove it.

qemu-char-spice has a large number of heavy dependencies, including mesa
drivers (>100MB) and llvm-libs (109MB).

ansible has a large number of standard and community-contributed scripts
in the default install (327MB), none of which we use.  Replace it with
ansible-core (11MB).

 * [x] image-refresh fedora-36

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3404-20220518-161515/

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20220518-163737

**Comment by allisonkarlitskaya** [comment]
2.36GB → 2.19GB.  Not a huge game changer, but progress.

**Comment by mvollmer** [comment]
> The failure is presumably caused not by the change here, but by an unrelated change in the image.

Looks like #2787 has made its way into fedora-36.

**Review by martinpitt — APPROVED** [review]
Cheers! I validated that even on this Fedora 36 image I can use cockpit in all supported languages. Some strings which come from the OS won't be translated of course, but that doesn't affect `check-pages` -- the point of this test is to make sure that our own translations work and don't cause a crash.

Also, the "select all languages" test only runs on RHEL, so it's not affected by Fedora image changes.

**Pull request merged**
