### PR TITLE
Image refresh for fedora-37

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-37
 * [x] image-refresh fedora-37
 * Land together with https://github.com/cockpit-project/cockpit/pull/18618

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-37-20230407-225858.log

**Comment by cockpituous** [comment]
image-refresh fedora-37 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-37-20230407-232015

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-37-20230407-232020.log

**Comment by martinpitt** [comment]
Already retried, same failures.

**Comment by martinpitt** [comment]
[pixel test failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4620-20230408-054457-3c56b05e-fedora-37-cockpit-project-cockpit/log.html) due to different length of IPv6 address. This may be random, or due to some new library versions on the refreshed image. Re-running once to compare.

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/18618 which needs to land in lockstep with this one.

**Pull request merged**
