### PR TITLE
Image refresh for opensuse-tumbleweed

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for opensuse-tumbleweed
 * [x] image-refresh opensuse-tumbleweed

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh opensuse-tumbleweed done: https://github.com/cockpit-project/bots/commits/image-refresh-opensuse-tumbleweed-20241009-225424

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-opensuse-tumbleweed-9ff7de57-20241009-224046/log.html

**Comment by martinpitt** [comment]
Tests fail with

> Failed to restart nfs-server.service: Unit nfs-server.service not found.

and indeed the image build log says that nfs-kernel-server got removed. It needs to be installed as an explicit test dependency.

**Comment by mvollmer** [comment]
Continued in #6973.

**Pull request closed without merging**
