### PR TITLE
images: Add stratis-cli and stratisd to the Fedoras

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh fedora-33
 * [x] image-refresh fedora-34
 * [x] Fix [realmd test on failed units](https://logs.cockpit-project.org/logs/pull-2274-20210803-145127-82795814-fedora-33-cockpit-project-cockpit/log.html#254-2): https://github.com/cockpit-project/cockpit/pull/16197

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-2274-20210803-112222/

**Comment by cockpituous** [comment]
image-refresh fedora-33 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-33-20210803-113939

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-2274-20210803-112727/

**Comment by cockpituous** [comment]
image-refresh fedora-34 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-34-20210803-114444

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2274-20210803-133939/

**Comment by cockpituous** [comment]
image-refresh fedora-33 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-33-20210803-135757

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-2274-20210803-135858/

**Comment by cockpituous** [comment]
image-refresh fedora-34 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-34-20210803-141515

**Comment by martinpitt** [comment]
[This failure](https://logs.cockpit-project.org/logs/pull-2274-20210803-145127-82795814-fedora-33-cockpit-project-cockpit/log.html#254-2) is an actual issue -- the terminal picks up the `stratisd.service` failure. This arguably does not belong into  TestKerberos.testNegotiate, so we should fix that test to be more lenient for the terminal output, or disable displaying failed units. We already did that in commit 7a6b68a8afcac0806977fba11656ed55657d5b6f

The [TestFIPS reboot failure](https://logs.cockpit-project.org/logs/pull-2274-20210803-145127-82795814-fedora-33-cockpit-project-cockpit/log.html#136-2) smells like a regression in Fedora 33.

**Comment by martinpitt** [comment]
@mvollmer: Ignore the cockpit-composer failures -- that test fails more often than not, and we've been ignoring it recently. Jakob is on it.

**Comment by martinpitt** [comment]
I filed https://github.com/cockpit-project/cockpit/pull/16197 to fix check-realms, blocking on this. The FIPS regression is https://bugzilla.redhat.com/show_bug.cgi?id=1989771 , I copied the naughty from fedora-34. Pushed a rebase. I'll trigger the f-33 tests once https://github.com/cockpit-project/cockpit/pull/16197 landed, but the f-34 tests can already run.

**Review by martinpitt — APPROVED** [review]
:+1: assuming green (ignore the fedora-33/composer tests)

**Pull request merged**
