### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch
 * [x] https://github.com/cockpit-project/cockpit/pull/19462

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20231006-042121.log

**Comment by martinpitt** [comment]
[retrying for comparison](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5345-20231006-042242-757ff49c-arch-networking-cockpit-project-cockpit/log.html#20)

**Comment by martinpitt** [comment]
Failed again, it's broken.

**Comment by martinpitt** [comment]
This was likely fixed by https://github.com/cockpit-project/cockpit/pull/19428 , retrying.

**Comment by martinpitt** [comment]
No -- while that should have been necessary (this image also updated to firewalld 2.0.1), it's apparently not sufficient.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
