### PR TITLE
Image refresh for rhel-9-2

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-2
 * [x] image-refresh rhel-9-2

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-2-20230219-230303.log

**Comment by mvollmer** [comment]
TestStorageNBDE.testRootReboot fails because the connection to the 10.111.112.0 network doesn't come back after the reboot. `eth1` is now named `ens15`.

**Comment by mvollmer** [comment]
Fix for TestStorageNBDE.testRootReboot in https://github.com/cockpit-project/cockpit/pull/18382, hopefully.

**Comment by martinpitt** [comment]
The cockpit fix landed. I rebased, as this branch was a bit stale and we got lots of other image refreshes in between.

**Review by mvollmer — APPROVED** [review]

**Pull request merged**
