### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

Needs:
* [x] https://github.com/cockpit-project/cockpit/pull/20699
* [x] https://github.com/cockpit-project/cockpit-machines/pull/1707

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240702-224809

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-ec5a356f-20240702-223743/log.html

**Comment by jelly** [comment]
Machines:
```
[root@archlinux ~]# ssh-keygen -t dsa -N '' -C '' -f /tmp/dsakey
unknown key type dsa
```

This release deprecates DSA by default:
```
OpenSSH plans to remove support for the DSA signature algorithm in
early 2025. This release disables DSA by default at compile time.
```

**Comment by jelly** [comment]
Cockpit issue comes from:
```
keys=$(ssh-keyscan -t dsa,ecdsa,ed25519,rsa -p "$port" "$host" || true)
```
Now that arch has no `dsa` it reports:

```
[root@archlinux ~]# ssh-keyscan -t dsa,ecdsa,ed25519,rsa
Unknown key type "dsa"
```

**Review by jelly — APPROVED** [review]

**Pull request merged**
