### PR TITLE
Clean up Fedora images

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh fedora-33
 * [x] image-refresh fedora-34
 - [x] Drop fedora-32: PR #1795

fedora-33 shrinks by 300 MB (1.77 → 1.45 GB), thanks mostly to losing chromium. fedora-34 still shrinks by 130 MB (1.53 → 1.40 GB).

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-1796-20210315-110303/

**Comment by cockpituous** [comment]
image-refresh fedora-33 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-33-20210315-112323

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-1796-20210315-112424/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1796-20210315-112424/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-1796-20210315-113333/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1796-20210315-113333/

**Comment by martinpitt** [comment]
Hmm, I don't understand this [build failure](https://logs.cockpit-project.org/logs/image-refresh-1796-20210315-113333/log) -- it works just fine locally. It seems to me that the mirror that download.fedoraproject.org picks on the e2e machines is broken.

Indeed after a few tries on the e2e machine (the first few worked), I got a redirect to https://mirror.genesisadaptive.com/fedora/ which is entirely kaputt. The working ones were for https://mirror.lax.genesisadaptive.com/fedora/linux/development/34/Cloud/x86_64/images/ which does work.

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-1796-20210315-122626/

**Comment by cockpituous** [comment]
image-refresh fedora-34 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-34-20210315-124242

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
