### PR TITLE
images: Drop cloud-init from Fedora images

### PR DESCRIPTION
**Pull request by martinpitt**
We don't need it after the initial boot. Remove it, just like we do
on the Debian/Ubuntu/RHEL images. This reduces boot time from 5.6 to
3.8 seconds.

 * [x] image-refresh fedora-33
 * [x] image-refresh fedora-34

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-ttzrz.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-1911-20210410-160000/

**Comment by cockpituous** [comment]
image-refresh fedora-33 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-33-20210410-161818

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-1911-20210410-161818/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-1911-20210410-161919/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1911-20210410-161919/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-1911-20210410-162020/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1911-20210410-162020/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-1911-20210410-174444/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1911-20210410-174444/

**Comment by martinpitt** [comment]
Hmm, somehow our e2e machines seem to have trouble with downloading the Fedora 34 cloud image? 33 worked, and 34 works for me locally as well.

**Comment by martinpitt** [comment]
A-ha! `curl -o ...` on ci-srv-04 indeed gives me a 0-byte file. With `--verbose` it shows a redirect. I suppose we need to use `-L` here as well, like in some other places.

**Comment by martinpitt** [comment]
Nevermind, we already use `-L`

     curl --verbose -L -o tmp/Fedora-Cloud-Base-34-20210410.n.0.x86_64.qcow2 https://download.fedoraproject.org/pub/fedora/linux//development/34/Cloud/x86_64/images//Fedora-Cloud-Base-34-20210410.n.0.x86_64.qcow2

This works just fine on ci-srv-04.. Trying again.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-1911-20210410-175252/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1911-20210410-175252/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-ttzrz.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-1911-20210410-175959/

**Comment by cockpituous** [comment]
image-refresh fedora-34 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-34-20210410-181313

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
