### PR TITLE
Image refresh for rhel-9-3

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-3
 * [x] image-refresh rhel-9-3

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-9-3 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-3-20240108-225350

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-3-20240108-225353.log

**Comment by martinpitt** [comment]
Ah, this needs the [recent Grafana updates](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5770-20240108-225510-5cd824ce-rhel-9-3-other-cockpit-project-cockpit-rhel-9.3/log.html). But, we didn't get further major bug reports for 9.3, so we can once again retire the branch. I sent PR #5771

**Review by martinpitt — APPROVED** [review]
Actually, no reason to block this. The rhel-9.3 branch is broken on the current rhel-9-3 image as well, it was the services image.

**Pull request merged**
