### PR TITLE
Image refresh for fedora-rawhide-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-boot
 * [x] image-refresh fedora-rawhide-boot

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-boot done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-boot-20231208-224014

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-boot-20231208-224040.log

**Comment by martinpitt** [comment]
Hmm, how is [that "file system busy"](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5652-20231208-224124-6b2481de-fedora-rawhide-boot-rhinstaller-anaconda-webui/TestInstallationProgress-testBasic-fedora-rawhide-boot-127.0.0.2-2201-FAIL.png) failure a regression of an image-refresh? This isn't using the storage page yet, right? @KKoukiou @M4rtinK

**Comment by martinpitt** [comment]
Same failure after retry, needs work.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
