### PR TITLE
Image refresh for rhel-8-6

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-6
 * [x] image-refresh rhel-8-6
 * https://github.com/cockpit-project/cockpit-machines/pull/473

### CODE REVIEW

**Comment by martinpitt** [comment]
New [SELinux violation](https://logs.cockpit-project.org/logs/pull-2681-20211202-023200-2cf30941-rhel-8-6-cockpit-project-cockpit/log.html#46) about `rhsm-service" name="memfd:libffi"` which needs to be reported and added to the allowed messages on this image (too big for naughty)

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-2681-20211207-141212/

**Comment by mvollmer** [comment]
Oh, pilot error, I don't need to remake the image when allowing journal messages...

**Review by martinpitt — APPROVED** [review]
Thanks! Looks promising so far.

**Comment by mvollmer** [comment]
Same cockpit-machines failures as in #2690 (and https://github.com/cockpit-project/cockpit-machines/pull/473?)

**Comment by mvollmer** [comment]
`TestUpdatesSubscriptions.testNoUpdates` seems to fail because while RHSM1 does send a EntitlementChanged signal, the subsequent GetStatus call still returns `valid: false`. I'll compare with older images to be sure.

**Comment by martinpitt** [comment]
This is now only waiting on https://github.com/cockpit-project/cockpit-machines/pull/473 (where the run against the refreshed image is green), so adding blocked and pointer in description.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
