### PR TITLE
Image refresh for fedora-rawhide-anaconda-payload

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-anaconda-payload
 * [x] image-refresh fedora-rawhide-anaconda-payload

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-anaconda-payload done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-anaconda-payload-20240412-224552

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-anaconda-payload-ac1f4e05-20240412-223718/log.html

**Comment by martinpitt** [comment]
@KKoukiou This [pixel change about the disk space](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6207-a978ee31-20240413-074419-fedora-rawhide-boot-rhinstaller-anaconda-webui/pixeldiff.html#TestStorageCockpitIntegration-testEncryptedUnlock-storage-editor), do you want to update the ref or should we just ignore the precise value in the pixel test? My gut feeling is the latter.

**Comment by KKoukiou** [comment]
> @KKoukiou This [pixel change about the disk space](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6207-a978ee31-20240413-074419-fedora-rawhide-boot-rhinstaller-anaconda-webui/pixeldiff.html#TestStorageCockpitIntegration-testEncryptedUnlock-storage-editor), do you want to update the ref or should we just ignore the precise value in the pixel test? My gut feeling is the latter.

Thanks, adjusted the pixel test. I will land when green https://github.com/rhinstaller/anaconda-webui/pull/252

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
