### PR TITLE
RHEL: make insights-client non-verbose

### LINKED ISSUE #2563: [no-test] Image refresh for rhel-9-0
Image refresh for rhel-9-0
 * [ ] image-refresh rhel-9-0

### PR DESCRIPTION
**Pull request by martinpitt**
Copied from @ptoscano 's PR #2594, as he is not a member he can't refresh images.

Apparently, newer versions of the insights-client in RHEL 9 log the HTTP traffic, which includes binary data (the egg file). Since we are not really interested in it, and that the log file is available locally anyway, simply make the `--status` run as non-verbose.

Also, print the RPM version of the `insights-client` package, to help debugging problems.

Fixes #2563

 * [x] image-refresh rhel-9-0
 * [x] image-refresh rhel-8-6

 * [ ] blocked on https://github.com/cockpit-project/cockpit-machines/pull/445

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-2595-20211104-082424/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20211104-084141

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2595-20211104-084242/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20211104-085656

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-2595-20211104-090808/

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20211104-093333

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-2595-20211104-093333/

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20211104-095555

**Comment by martinpitt** [comment]
There are two bogus contexts here: rhel-9-0@candlepin/subscription-manager/subscription-manager-1.28 and rhel-9-0-distropkg@cockpit-project/cockpit. That's a bug in our testmap lib, I sent a fix in #2596.

[TestTeam.testBasic on rhel-8-6](https://logs.cockpit-project.org/logs/pull-2595-20211104-093731-8cb2b0e5-rhel-8-6-cockpit-project-cockpit/log.html#88-2) smells like a flake, retrying once to compare.

However, this [podman rhel-9.0 failure](https://logs.cockpit-project.org/logs/pull-2595-20211104-093749-8cb2b0e5-rhel-9-0-cockpit-project-cockpit-podman/log.html) smells like an actual regression. Marking needswork for that.

**Comment by martinpitt** [comment]
and of course [cockpit-machines on this new rhel-9-0 image](https://logs.cockpit-project.org/logs/pull-2595-20211104-093746-8cb2b0e5-rhel-9-0-cockpit-project-cockpit-machines/log.html#2-2) is an unmitigated disaster..

**Comment by KKoukiou** [comment]
Cockpit machines fixes in a PR on the cockpit-machines repo https://github.com/cockpit-project/cockpit-machines/pull/445
Cockpit podman needed a copy of a set of naughties - also cloned the existing downstream report.

**Review by martinpitt — COMMENTED** [review]
Ah, nice to see that at least it's a known issue -- sad to see that it's spreading like mad :cry: 

If everything goes green, please land the two PRs together. Thank you!

(I can't formally approve, but :+1: )

**Review by jelly — APPROVED** [review]

**Comment by martinpitt** [comment]
[testTeam on rhel-8-6](https://logs.cockpit-project.org/logs/pull-2595-20211104-164526-85917575-rhel-8-6-cockpit-project-cockpit/log.html#88-2) failed again.. This is becoming systematic.

**Pull request merged**
