### PR TITLE
arch: Use zero-disk.setup, pull podman images

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3122-20220322-052727/

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20220322-054040

**Comment by martinpitt** [comment]
Failed to stat /var/cache/pacman/pkg/: No such file or directory

Whoops, we need to protect that one, it seems.. Having the unpacked chroot in /var/lib/ isn't enough. Would be nice to disable the cache usage, as it's redundant and unnecessary.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-3122-20220322-064747/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3122-20220322-064747/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3122-20220322-071010/

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20220322-072323

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3122-20220322-072323/

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20220322-073636

**Review by jelly — APPROVED** [review]

**Pull request merged**
