### PR TITLE
images: add `rhel-9-1`, and use it for subscription-manager-cockpit

### PR DESCRIPTION
**Pull request by ptoscano**
Based on rhel-9-0 with references switched to 9.1 material.

Also switch subscription-manager-cockpit from `rhel-9-0` to `rhel-9-1`.

 * [x] image-refresh rhel-9-1

### CODE REVIEW

**Comment by martinpitt** [comment]
Thanks! Triggering build.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-3252-20220420-025454/

**Comment by cockpituous** [comment]
image-refresh rhel-9-1 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-1-20220420-033030

**Comment by martinpitt** [comment]
@ptoscano: Can you please give the image a quick sanity check (boot and run it against the sub-man tests, for example), and if it's ok, commit it here? I'm fine with landing it then, even if it doesn't have any testmap entries yet.

**Comment by ptoscano** [comment]
@martinpitt unless I did any mistake in testing, this new `rhel-9-1` image should work fine with subscription-manager-cockpit/main. Can you please trigger this combination?

**Comment by ptoscano** [comment]
> but the insights tests fail the same way as on rhel-9-0. Please add a `rhel-9-1 -> rhel-9` symlink in naughty/

Ahh the classic issue with `insights-client` :unamused: 

> and add `rhel-9-1` to sub-man-cockpit in testmap.

Done.

**Review by martinpitt — APPROVED** [review]
Works! :+1: Grazie!

**Pull request merged**
