### PR TITLE
Image refresh for fedora-eln

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-eln
 * [x] image-refresh fedora-eln

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-eln done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-eln-20240213-225048

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-eln-20240213-225050.log

**Comment by martinpitt** [comment]
@KKoukiou Do you know what that is?
```
Repository 'fedora-40-x86_64' does not exist in project '@rhinstaller/Anaconda'.
Available repositories: 'fedora-eln-x86_64', 'fedora-rawhide-x86_64'
```

Also, I faintly remember that you dropped ELN testing. Did it get back? Do you want it back?

**Comment by KKoukiou** [comment]
> @KKoukiou Do you know what that is?
> 
> ```
> Repository 'fedora-40-x86_64' does not exist in project '@rhinstaller/Anaconda'.
> Available repositories: 'fedora-eln-x86_64', 'fedora-rawhide-x86_64'
> ```
> 
> Also, I faintly remember that you dropped ELN testing. Did it get back? Do you want it back?

Hi @martinpitt , I did it because it was unstable - and we had no capacity to look into that. Ideally, after the Fedora-40 branching, I would like to give this one more try. 

As long as there are no RHEL10 ISOS we can use for testing, we will need to use the ELN ones, to start testing against RHEL10 like scenario.

**Comment by KKoukiou** [comment]
@martinpitt if the updates bother you, I can remove the images, and re-introduce these once I find time.

**Comment by martinpitt** [comment]
Thanks @KKoukiou We can let it sit here for a while, sure.

**Comment by martinpitt** [comment]
Since there's no current interest in these images, I disabled their refresh in #6002

**Pull request closed without merging**
