### PR TITLE
images: Improve hack for pmlogger.service startup failure

### LINKED ISSUE #679: Image refresh for ubuntu-stable
Image refresh for ubuntu-stable
 * [ ] FAIL: image-refresh ubuntu-stable

### PR DESCRIPTION
**Pull request by martinpitt**
Sometimes it takes pmlogger.service so long to start up that it misses
even the second attempt and times out again. Just disable it completely
during the image build by runtime-masking it.

Fixes #679

 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-727-20200405-210404/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-727-20200405-211313/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-stable-20200405-213232

**Comment by martinpitt** [comment]
@marusak: This all happens in /run, thus this only affects the image build. The resulting VM and tests are unchanged -- i. e. pmlogger will still take ages to start and such, but the tests have to deal with that. I don't want to permanently disable it, just avoid the long wait on image-create.

**Pull request merged**
