### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos

### CODE REVIEW

**Comment by jelly** [comment]
Highlighted changes:

```
  ostree (2022.1-1.fc35 -> 2022.2-1.fc35)
  ostree-libs (2022.1-1.fc35 -> 2022.2-1.fc35)
  rpm-ostree (2022.5-1.fc35 -> 2022.6-2.fc35)
  rpm-ostree-libs (2022.5-1.fc35 -> 2022.6-2.fc35)
```

**Comment by jelly** [comment]
> Highlighted changes:
> 
> ```
>   ostree (2022.1-1.fc35 -> 2022.2-1.fc35)
>   ostree-libs (2022.1-1.fc35 -> 2022.2-1.fc35)
>   rpm-ostree (2022.5-1.fc35 -> 2022.6-2.fc35)
>   rpm-ostree-libs (2022.5-1.fc35 -> 2022.6-2.fc35)
> ```

Reproducing with the new image:

```
$ scp pkg/systemd/kernelopt.sh c:
$ ssh c
$ ./kernelopt.sh set mitigations=auto
[root@fedora-coreos-127-0-0-2-2201 ~]# ./kernelopt.sh set mitigations=auto
ignoring ``: invalid filter directive
Checking out tree 0a69c8e... done
Resolving dependencies... done
Checking out packages... done
Running pre scripts... done
Running post scripts... done
Running posttrans scripts... done
Writing rpmdb... done
Writing OSTree commit... done
Staging deployment... done
Freed: 25.7?MB (pkgcache branches: 5)
Kernel arguments updated.
Run "systemctl reboot" to start a reboot
$ grep mitigations /proc/cmdline
BOOT_IMAGE=(hd0,gpt3)/ostree/fedora-coreos-bb6786d8909bac38e885f5fabc06553a67dd0e1718e8d4fba59178bb8a909d93/vmlinuz-5.17.4-200.fc35.x86_64 mitigations=auto,nosmt console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ostree=/ostree/boot.1/fedora-coreos/bb6786d8909bac38e885f5fabc06553a67dd0e1718e8d4fba59178bb8a909d93/0 root=UUID=52b769ca-5215-4402-88cc-7c9e4780bcb9 rw rootflags=prjquota boot=UUID=6b2c1360-2874-48e1-942c-7012a0b19916 mitigations=auto
```

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-3316-20220505-080303/

**Comment by cockpituous** [comment]
image-refresh fedora-coreos done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-coreos-20220505-081515

**Comment by allisonkarlitskaya** [comment]
Nope.  Still busted :(

**Comment by allisonkarlitskaya** [comment]
Even though this got fixed a long time ago and landed in the distro, the images seem only to get rebuilt once every two weeks: https://getfedora.org/coreos?stream=stable

We keep pulling the `20220424` image, which is why this keeps failing.  I guess the `0508` image will be out early next week, at which point this should be working again...

**Comment by jelly** [comment]
> Clarification: our image uses the [testing stream](https://getfedora.org/coreos?stream=testing), not the stable one. But even today, the latest image is still 0424.

Aha, I did read they were busy rebasing it on fedora-36 https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/Q2QXOQOVZ57USSQEJ3VRXC2JOWMEHKIE/

**Comment by allisonkarlitskaya** [comment]
Yay!  `36.20220505.2.0` is released.  Let's try one more time...

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-3316-20220511-113333/

**Comment by cockpituous** [comment]
image-refresh fedora-coreos done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-coreos-20220511-114242

**Review by allisonkarlitskaya — APPROVED** [review]
Yay!!

**Pull request merged**
