### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch
 * [x] https://github.com/cockpit-project/cockpit-podman/pull/838
 * [x] https://github.com/cockpit-project/cockpit-machines/pull/461

### CODE REVIEW

**Comment by martinpitt** [comment]
Projects finally got fixed; Rebased to re-run tests from a clean slate.

**Comment by martinpitt** [comment]
This [arch failure](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-2666-20211129-141447-377b5b2d-arch-cockpit-project-cockpit-machines/log.html#34-2) is now completely separate from the previous problems, and needs to be investigated separately -- most probably package updates?

**Comment by jelly** [comment]
> This [arch failure](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-2666-20211129-141447-377b5b2d-arch-cockpit-project-cockpit-machines/log.html#34-2) is now completely separate from the previous problems, and needs to be investigated separately -- most probably package updates?

I've tested it locally, updating the system without cockpit makes it still pass `pacman -Syu --ignore cockpit`. I then found a test failure related to:
```
cockpit-session: pam: Activate the web console with: systemctl enable --now cockpit.socket
```

After updating test/common to 258 the tests pass.

**Review by martinpitt — APPROVED** [review]
Nice!

**Pull request merged**
