### PR TITLE
images: Add rhel-8-10

### PR DESCRIPTION
**Pull request by martinpitt**
Add it as manual test context, until we enable it in the projects.

While at it, clean up the obsolete manual contexts of candlepin/subscription-manager-cockpit and cockpit-certificates, these don't get tested on RHEL 8.

---

I've done the first RHEL 8.10 upload, and various gating tests failed. I hope our own image will make it easier to investigate.

 * [x] image-refresh rhel-8-10

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-8-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-10-20230927-092114

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-10-20230927-092121.log

**Comment by cockpituous** [comment]
image-refresh rhel-8-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-10-20230927-105203

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-10-20230927-105252.log

**Comment by martinpitt** [comment]
I smoke-tested this new image with `make check` in starter-kit and a cursory boot and inspection. After this lands, I'll enable our projects.

**Review by jelly — APPROVED** [review]

**Pull request merged**
