### PR TITLE
Image refresh for opensuse-tumbleweed

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for opensuse-tumbleweed
 * [x] image-refresh opensuse-tumbleweed

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh opensuse-tumbleweed done: https://github.com/cockpit-project/bots/commits/image-refresh-opensuse-tumbleweed-20240712-225400

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-opensuse-tumbleweed-405e0303-20240712-223906/log.html

**Comment by martinpitt** [comment]
[This test flakes](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6612-f8f545a2-20240712-225514-opensuse-tumbleweed-cockpit-project-cockpit-machines/log.html#12-2) 70% of the time, see the [weather report](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit-machines&days=7&test=%2Ftest%2Fcheck-machines-create+TestMachinesCreate.testCreateDownloadAnOS). This *only* happens on tumbleweed. @Nykseli @Lunarequest @SludgeGirl do you know what's going on there?

**Comment by martinpitt** [comment]
Let's unblock this image refresh, that test failure isn't new. I'll take a look at it now.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
