### PR TITLE
Image refresh for rhel-7-8

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-7-8
 * [x] image-refresh rhel-7-8

### CODE REVIEW

**Comment by martinpitt** [comment]
"No package beakerlib available." -- did this fall out of rhel 7.8 now?

**Comment by martinpitt** [comment]
Ah no, beakerlib gets installed from a third-party source -- see e. g. https://logs.cockpit-project.org/logs/pull-967-20200220-131017-21483a0c-rhel-7-8-vmware/log . So that third-party source simply disappeared, and the lorax test needs to get updated -- @atodorov , FYI.

So we can ignore that one for now, but we still need to get the composer tests to green.

**Comment by martinpitt** [comment]
Nice, a retry worked,  so it seems there was just a temporary outage of the external beaker repos.

**Comment by martinpitt** [comment]
@henrywang , can you please have a look at the composer rhel-8 errors?

**Comment by henrywang** [comment]
@martinpitt, all green now!

**Pull request merged**
