### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240814-225211

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-cd70f1e3-20240814-223919/log.html

**Comment by martinpitt** [comment]
Looks like the systemd package fell out of the build chroot, so the image is broken.

**Comment by martinpitt** [comment]
Comparing with the [previous build log](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-02e1524d-20240806-223825/log.html) that installed "systemd", and now it's just "systemd-libs".

**Comment by martinpitt** [comment]
Fixing in #6740

**Comment by martinpitt** [comment]
Superseded by #6740

**Pull request closed without merging**
