### PR TITLE
Introduce rhel-9-3 image

### PR DESCRIPTION
**Pull request by KKoukiou**
* [x] image-refresh rhel-9-3

Run cockpit and cockpit-machines tests on rhel-9-3 now as we stopped updating the rhel-9-2 branch with the new releases.

For the rest of the projects this should be also true, but let's take a closer look separately.

### CODE REVIEW

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-3-20230325-090202.log

**Comment by cockpituous** [comment]
image-refresh rhel-9-3 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-3-20230325-092003

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-3-20230325-092020.log

**Comment by KKoukiou** [comment]
cockpit machines failed exactly the same way like osci gating downstream. That's good start. Should have added these tests here last week already.

**Comment by KKoukiou** [comment]
Cockpit machines tests are running with the new test skips on https://github.com/cockpit-project/cockpit-machines/pull/990

**Review by martinpitt — APPROVED** [review]
Thanks! Please move cockpit and c-machines out of _manual into the automatic testmap.

**Pull request merged**
