### PR TITLE
Fedora 39 update for fsinfo

### PR DESCRIPTION
**Pull request by cockpituous**
* [x] image-refresh fedora-39
 * [x] image-refresh fedora-38

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-39 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-39-20240205-081909

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-39-20240205-081919.log

**Comment by cockpituous** [comment]
image-refresh fedora-38 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-38-20240205-103932

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-38-20240205-103939.log

**Review by allisonkarlitskaya — APPROVED** [review]
Only images changes — can't possibly affect unit tests.

**Pull request merged**
