### PR TITLE
images: Drop unrequired dbus-broker port in Fedora

### PR DESCRIPTION
**Pull request by jelly**
The dbus broker tests run on local host now.

 * [x] image-refresh fedora-34

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-2680-20211201-083333/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-2680-20211201-083333/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-2680-20211201-083636/

**Comment by cockpituous** [comment]
image-refresh fedora-34 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-34-20211201-085959

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-2680-20211201-090000/

**Comment by cockpituous** [comment]
image-refresh fedora-34 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-34-20211201-092020

**Comment by martinpitt** [comment]
@jelly : I suggest to run a single cockpit test on this now, to validate that it works. Then rebuild fedora-35, push them both, and trigger all image tests.

**Comment by martinpitt** [comment]
@jelly -- this changes the firewalld screenshot, as the additional "8765" now went away. To do this without too much pain, I suggest the following:
 * Send a quick cockpit PR to change the test to close port 8765 on Fedora, test-run it agains this refreshed image and the old one, and update the pixel test.
 * Refresh all images here, this does work in general
 * Re-drop the "drop port 8765" hack again

**Comment by martinpitt** [comment]
This should be unblocked now. As we updated a lot of images (including centos-7) in the meantime, please rebase this to current main, and re-run the tests. Should be good now. (Then also please rebuild F35)

**Review by martinpitt — APPROVED** [review]
To avoid blocking this any further, let's push our luck and land as-is (assuming green, of course). AFAICS F35 does not have anything fundamentally new (such as pixel tests). Danke!

**Pull request merged**
