### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by marusak** [comment]
It seems that `We trust you have received the usual lecture` statement is not present anymore. We don't expect it on Ubuntu, seems that Debian got rid of it as well?

**Comment by martinpitt** [comment]
Yes indeed -- [version 1.9.10-1](https://tracker.debian.org/news/1311597/accepted-sudo-1910-1-source-into-experimental/) changelog says:

> * adopt configure changes from Ubuntu
>   --without-lecture --with-tty-tickets --enable-admin-flag (Closes: [#1006273](https://bugs.debian.org/1006273))

So this was intentional.

**Comment by marusak** [comment]
I've sent https://github.com/cockpit-project/cockpit/pull/17217 and running tests there as well

**Comment by marusak** [comment]
I'll rebase to get clean run

**Review by marusak — APPROVED** [review]

**Pull request merged**
