### PR TITLE
image-create: Build candlepin in Fedora 35

### LINKED ISSUE #3546: Image refresh for services
Image refresh for services
 * [ ] FAIL: image-refresh services

### PR DESCRIPTION
**Pull request by martinpitt**
fedora:latest switched over to Fedora 36, which caused candlepin's ruby
build to fail. Continue to build in Fedora 35, until candlepin catches
up.

FTR, candlepin wants ruby 2.4, which is ancient -- even RHEL 8 and 
Debian oldstable have 2.5, so there are no supported distro binaries
around. So we have to live with that compilation madness until candlepin
arrives in this decade.

Fixes #3546

 * [x] image-refresh services

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3618-20220715-082323/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3618-20220715-082323/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-3618-20220715-093434/

**Comment by cockpituous** [comment]
image-refresh services done: https://github.com/cockpit-project/bots/commits/image-refresh-services-20220715-103804

**Comment by martinpitt** [comment]
@jelly : Ready for review now.

**Comment by jelly** [comment]
> @jelly : Ready for review now.

Looks good, I am still a bit concerned about the compilation step. Let's hope it doesn't flake too often.

**Review by jelly — APPROVED** [review]

**Pull request merged**
