### PR TITLE
Image refresh for opensuse-tumbleweed

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for opensuse-tumbleweed
 * [x] image-refresh opensuse-tumbleweed

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh opensuse-tumbleweed done: https://github.com/cockpit-project/bots/commits/image-refresh-opensuse-tumbleweed-20240808-225123

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-opensuse-tumbleweed-5e52dd54-20240808-223831/log.html

**Comment by martinpitt** [comment]
Ugh -- that update [breaks cockpit-machines hard](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6714-55885884-20240808-225238-opensuse-tumbleweed-cockpit-project-cockpit-machines/log.html), and in more than one way. I'll do a retry to have two logs for comparison, but this can't all be explained away with just flakes.

**Comment by martinpitt** [comment]
Yes, same catastrophe -- @SludgeGirl, @Lunarequest @Nykseli something thoroughly broke libvirt in tumbleweed?

**Comment by Nykseli** [comment]
Another week, another virt issue!

The "good news" is that now some of tests are failing locally on my machine so I can dig into it more easily

**Comment by martinpitt** [comment]
That image is stale by now (2 weeks), closing and letting the bots open a new one. Perhaps someone magically fixed this already :sweat_smile:

**Pull request closed without merging**
