### PR TITLE
images: Get Openshift from quay.io

### PR DESCRIPTION
**Pull request by mvollmer**
* [ ] FAIL: image-refresh openshift

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-ztr72.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-1783-20210311-174848/

**Comment by mvollmer** [comment]
Oho, I think my changes are all wrong and we still pull a lot from dockerhub, but we didn't seem to have run into any rate limits this time...

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpit-project/bots/commits/image-refresh-openshift-20210311-180505

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-1783-20210311-181919/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1783-20210311-181919/

**Comment by martinpitt** [comment]
Oh cool, so the origin-base quay.io container images *are* a working substitute? Nice!

**Comment by martinpitt** [comment]
> we didn't seem to have run into any rate limits this time...

It's really a matter of day time/luck..

**Comment by mvollmer** [comment]
> Oh cool, so the origin-base quay.io container images _are_ a working substitute?

Looks like it.  Tbh, I don't really know what's going on in openshift.setup...

**Comment by mvollmer** [comment]
> > we didn't seem to have run into any rate limits this time...
> 
> It's really a matter of day time/luck..

Yeah, the second attempt with more quay.io prefixes failed on `docker.io/library/registry`, which is Docker's own stuff. It might not be on Quay, but we should be able to mirror it.

Then there is busybox and maybe other images that are used for testing, I guess.  We can use anything we find on quay, I guess, preferably something that doesn't need changes to the tests themselves.

I am thinking right now that we push the image created by my partial changes as is (when tests are green), conceptually broken as they are (maybe with a comment to the effect), and then I try a bit more to make openshift.setup cleaner and not use docker.io at all.

**Comment by mvollmer** [comment]
> > Oh cool, so the origin-base quay.io container images _are_ a working substitute?
> 
> Looks like it. Tbh, I don't really know what's going on in openshift.setup...

No, it doesn't work:

```
+ docker run --rm --entrypoint tar quay.io/openshift/origin-base:v3.11.0 -C /usr/bin -c openshift oc kubectl
tar: openshift: Cannot stat: No such file or directory
tar: oc: Cannot stat: No such file or directory
tar: kubectl: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

`docker run` didn't propagate the error, of course.

In my first attempt, I forgot to update this line, and we were still using the image from docker.io.

**Comment by mvollmer** [comment]
There is `quay.io/openshift/origin`, but it is empty.

**Comment by mvollmer** [comment]
What about just dropping the openshift image completely? It's only used by check-openshift on the rhel-7.9 branch.

**Comment by mvollmer** [comment]
> I am thinking right now that we push the image created by my partial changes as is

On scond thought, let's not. We are fine with a old version for a while.

**Comment by mvollmer** [comment]
Okay, I'll just mirror the whole bunch.

**Comment by mvollmer** [comment]
As @martinpitt points out, the openshift containers on docker.io seem to no longer be updated. We would have to find out what the current way of installing openshift is, which doesn't seem to be worth it. So let's keep using our existing openshift image without any further updates until we drop support for rhel-7-9.

**Pull request closed without merging**
