### PR TITLE
Image refresh for rhel-9-4

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-4
 * [x] image-refresh rhel-9-4

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-9-4 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-4-20231126-230136

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-4-20231126-230101.log

**Comment by martinpitt** [comment]
@jelly can you please have a look at the kdump regression here?

**Comment by jelly** [comment]
> @jelly can you please have a look at the kdump regression here?

```
BOOT_IMAGE=(hd0,gpt3)/vmlinuz-5.14.0-386.el9.x86_64 root=UUID=b84b3494-0f62-45a6-a7f0-989186913e76 console=tty0 console=ttyS0,115200n8 no_timer_check net.ifnames=0 crashkernel=
```

This seems the root cause.

**Comment by jelly** [comment]
Reported https://issues.redhat.com/browse/RHEL-17401 I'd say we mark this as blocked and see if this is resolved quickly? As I don't expect RHEL 9 to change dramatically over the coming days.

**Comment by jelly** [comment]
I just re-created the image locally and crashkernel is set, so let's retry in CI.

**Comment by cockpituous** [comment]
image-refresh rhel-9-4 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-4-20231128-083106

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-4-20231128-083131.log

**Comment by jelly** [comment]
Closing for a new refresh

**Pull request closed without merging**
