### PR TITLE
images: Introduce rhel-8-4

### PR DESCRIPTION
**Pull request by marusak**
* [x] image-refresh rhel-8-4

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-1342-20201027-164141/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-1342-20201027-164141/

**Comment by marusak** [comment]
meh, I opened it with refresh for 8-3 by mistake and now it does that... I'll wait until it finishes and then re-trigger it.

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1342-20201027-164141/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-1342-20201027-165454/

**Comment by cockpituous** [comment]
image-refresh rhel-8-4 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-4-20201027-171616

**Comment by marusak** [comment]
Sent https://github.com/cockpit-project/cockpit/pull/14837 where most tests fixes will happen.

**Comment by KKoukiou** [comment]
https://github.com/cockpit-project/cockpit/pull/14837 got completelly green, this is fine to merge.

**Review by KKoukiou — APPROVED** [review]
cockpit-project/cockpit#14837 got completelly green, this is fine to merge.

**Pull request merged**
