### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos

### CODE REVIEW

**Comment by marusak** [comment]
[testRestart](https://logs.cockpit-project.org/logs/pull-1536-20210109-090115-6c065ddf-fedora-coreos-cockpit-project-cockpit/log.html#231-2) failed twice in a row the same way. Needs to be looked at.

**Comment by martinpitt** [comment]
I locally ran that test several times, and I could reproduce the failure once. So it's a flake, and nothing new: it's the top fcos flake on https://images-frontdoor.apps.ocp.ci.centos.org/failure-stats.html . So retrying this one once more to not block the refresh, but I'm looking at it to fix it properly.

**Comment by martinpitt** [comment]
When that happens, machine2 (m2/b2) has a proper multicast-network IP (10.111.113.2), but machine1 doesn't:
```
3: ens15: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:01:00:00:01 brd ff:ff:ff:ff:ff:ff
    altname enp0s15
    inet6 fe80::5054:1ff:fe00:1/64 scope link 
       valid_lft forever preferred_lft forever
```

Cockpit says "Cockpit could not contact the given host", and ssh says the same:
```
# ssh root@10.111.113.1
ssh: connect to host 10.111.113.1 port 22: No route to host
```
This smells like some NM confusion about two configurations for the same interface. On the working one, we have
```
# nmcli d
ens15         ethernet  connected               static-52:54:01    
# nmcli c
static-52:54:01     6b88da53-3215-403f-9593-302bd684bcbc  ethernet  ens15       
mcast1              4bf68e6e-d2d4-345b-aa95-2259ef3bc196  ethernet  --          
```

while on the failing one it's the other way around:
```
ens15         ethernet  connected               mcast1             

mcast1              4bf68e6e-d2d4-345b-aa95-2259ef3bc196  ethernet  ens15       
static-52:54:01     d71a13fe-1efc-4423-89d1-e9677f2a51a3  ethernet  --          
```

We create the `static-{mac}` connection in machine/machine_core/machine.py `set_address()`, need to check how we can de-prioritize the `mcast1` dummy connection so that new ones always take precedence.

**Comment by martinpitt** [comment]
Succeeded, but I also have a fix now. I'll send mine as a follow-up.

**Review by martinpitt — APPROVED** [review]

**Comment by martinpitt** [comment]
Fixed that flake in #1548

**Pull request merged**
