### PR TITLE
Let's test job-runner

### PR DESCRIPTION
**Pull request by cockpituous**
* [ ] FAIL: image-refresh fedora-39
 * [x] image-refresh cirros
 * [ ] FAIL: image-refresh debian-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh cirros done: https://github.com/cockpit-project/bots/commits/image-refresh-cirros-20240307-160709

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-cirros-6aa2b40c-20240307-160631/log.html

**Comment by martinpitt** [comment]
Theory: cirros works because it doesn't have a `.setup` script. The structural difference between "old" and "job-runner" is that the job containers have no init which reaps zombies, and the waiting for qemu times out because it's a zombie and never goes away. Testing..

**Comment by martinpitt** [comment]
I [added a cirros.setup](https://github.com/cockpit-project/bots/commit/2fcaeb74350d3d78ba3059bdb7311e2c1cba2aff)  in my fork, and that reproduces it very well:
```
./job-runner run --sha 2fcaeb74350d3d78ba3059bdb7311e2c1cba2aff martinpitt/bots -- ./image-create --verbose cirros
```

In the container I see
```
user           1  0.1  0.2  51988 32392 ?        Ss   03:10   0:00 python3 ./image-create --verbose cirros
user          25  0.0  0.1 1363768 24572 ?       Sl   03:10   0:00 /usr/sbin/virtqemud --timeout=120
user          69  0.0  0.0      0     0 ?        Zs   03:10   0:00 [qemu-system-x86] <defunct>
user          71  0.0  0.0      0     0 ?        Z    03:10   0:00 [qemu-system-x86] <defunct>
user          74  0.0  0.0   4788  3968 pts/0    Ss   03:11   0:00 bash
user          79  0.0  0.0      0     0 ?        Zs   03:11   0:00 [qemu-system-x86] <defunct>
user          81  0.0  0.0      0     0 ?        Z    03:11   0:00 [qemu-system-x86] <defunct>
```

I sent a fix to #6041. Locally, 
```
./job-runner run cockpit-project/bots -- ./image-create --verbose arch
```
succeeds now (I figured that's the fastest non-trivial image)

**Pull request closed without merging**
