### PR TITLE
images: Move FreeIPA to centos-9-stream tag

### LINKED ISSUE #6482: Image refresh for services
Image refresh for services
 * [ ] FAIL: image-refresh services

### PR DESCRIPTION
**Pull request by martinpitt**
CentOS 8 stream is no more, and likewise the freeipa-server image dropped the tag. Also, bz#2015102 got fixed years ago, drop the obsolete comment.

Fixes #6482

---

 * [x] image-refresh services
 * [x] https://github.com/cockpit-project/cockpit/pull/20626
 * [x] backport: https://github.com/cockpit-project/cockpit/pull/20630

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh services done: https://github.com/cockpit-project/bots/commits/image-refresh-services-20240609-102904

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-services-8985699e-20240609-100633/log.html

**Comment by martinpitt** [comment]
The [Grafana tests](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6483-4c1d8d4b-20240609-110949-fedora-40-other-cockpit-project-cockpit/log.html#28-2) are fixed by https://github.com/cockpit-project/cockpit/pull/20626.

That leaves the [old sub-man tests](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6483-4c1d8d4b-20240609-110914-rhel-8-8-candlepin-subscription-manager-subscription-manager-1.28/log.html) (current branches all pass). @ptoscano , I really don't have time to debug this. Does it really make sense to keep  the old branches and images alive? How often did you update sub-man on RHEL 8.6 or 8.8?

**Comment by martinpitt** [comment]
Rebased, so that I can actually run a test against this.

**Comment by martinpitt** [comment]
Oh look, sub-man was a flake! Rebasing to get clean test results.

**Review by jelly — APPROVED** [review]

**Pull request merged**
