### PR TITLE
naughty: Add pattern for podman failing to start containers

### PR DESCRIPTION
**Pull request by marusak**
See known issue #1475

### CODE REVIEW

**Comment by marusak** [comment]
Triggering in https://github.com/cockpit-project/cockpit-podman/pull/624

**Review by martinpitt — CHANGES_REQUESTED** [review]
ITYM #1476, not #1475?

(Also, what a disaster!)

**Comment by marusak** [comment]
> ITYM #1476, not #1475?

Of course. Thanks for spotting, fixed

**Comment by marusak** [comment]
The patter worked, see https://logs.cockpit-project.org/logs/pull-624-20201217-142051-5943f721-fedora-32-rawhide-bots-1477/log.html

**Review by martinpitt — APPROVED** [review]
Cheers!

**Pull request merged**
