### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20230519-225757.log

**Comment by jelly** [comment]
```
# testClientCertAuthentication (__main__.TestLogin.testClientCertAuthentication)
Job for sssd.service failed because the control process exited with error code.
See "systemctl status sssd.service" and "journalctl -xeu sssd.service" for details.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-static-login", line 788, in testClientCertAuthentication
    m.execute("systemctl restart sssd")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by martinpitt** [comment]
sssd fails with "Unsupported provider 'files' is used in SSSD config.". That's what the test explicitly sets.

This image changed sssd 2.8.2-2 -> 2.9.0-1. The [arch version update](https://gitlab.archlinux.org/archlinux/packaging/packages/sssd/-/commit/512874bf03420588fca0128badc625dd7aad7545) has nothing specific about the files provider, it's just a clean version bump.

We have version 2.9.2 in F38/rawhide as well, but it's very new, and our fedora-38 CI VM does not have this yet (still 2.8.2). When I update that VM to 2.9.0 (`dnf update -y sssd`), the test still passes, so that "files" provider is still supported upstream. The [fedora update](https://src.fedoraproject.org/rpms/sssd/c/a969dbbcdc8a019e5750fccb17e1b4b87fcef84b?branch=f38) now explicitly adds `--with-files-provider`, which the Arch package is missing.

**Comment by martinpitt** [comment]
I filed a downstream bug: https://bugs.archlinux.org/task/78569 and a known issue #4790. Added naughty.

**Review by jelly — APPROVED** [review]

**Comment by martinpitt** [comment]
Bah, "error: failed to synchronize all databases (unable to lock database)" -- this has been going on for some time, retrying.

**Pull request merged**
