### PR TITLE
Image refresh for fedora-rawhide

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide
 * [x] image-refresh fedora-rawhide

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-20240905-081411

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-73bd8927-20240905-075833/log.html

**Comment by jelly** [comment]
TestExistingSystemUbuntu.testReclaimSpaceShrink fails with a retry as well @KKoukiou any ideas?

**Comment by KKoukiou** [comment]
> [TestExistingSystemUbuntu.testReclaimSpaceShrink](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6823-bdfdb6cd-20240905-084701-fedora-rawhide-boot-other-rhinstaller-anaconda-webui/log.html#9-2) fails with a retry as well @KKoukiou any ideas?

Yes I will fix that.

**Comment by KKoukiou** [comment]
Fixed @ https://github.com/rhinstaller/anaconda-webui/pull/430

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
