### PR TITLE
Image refresh for fedora-39

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-39
 * [x] image-refresh fedora-39
 * [x] https://github.com/cockpit-project/cockpit/pull/19524

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-39-20231024-230101.log

**Comment by martinpitt** [comment]
Uh, new Fedora breaks kdump:

> kdump.service - Crash recovery kernel arming was skipped because of an unmet condition check (ConditionKernelCommandLine=crashkernel).

**Comment by martinpitt** [comment]
The only plausible change is this one:

    kexec-tools (2.0.27-1.fc39 -> 2.0.27-2.fc39)

The change description on https://bodhi.fedoraproject.org/updates/FEDORA-2023-93fab3be92 sounds like this is intended. I'll see if it works when merely enabling it.

**Comment by martinpitt** [comment]
This is ready to land in lockstep with https://github.com/cockpit-project/cockpit/pull/19524

**Review by jelly — APPROVED** [review]

**Pull request merged**
