### PR TITLE
Image refresh for rhel-9-0

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-0

 * [x] image-refresh rhel-9-0

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-2779-20220105-160909/

**Review by jelly — APPROVED** [review]
cockpit-composer is a known issue.

**Comment by jelly** [comment]
The failing tests should now work in https://github.com/cockpit-project/cockpit-podman/pull/870 as crun was updated to 1.4

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20220105-172323

**Pull request merged**
