### PR TITLE
images: fix centos-10

### LINKED ISSUE #6376: Image refresh for centos-10
Image refresh for centos-10
 * [ ] FAIL: image-refresh centos-10

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
Fixes #6376 

 * [x] image-refresh centos-10

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240514-041151

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-fdf4c864-20240514-035722/log.html

**Comment by jelly** [comment]
SELinux failure galore:

```
audit: type=1400 audit(1715689617.214:4): avc:  denied  { map_read map_write } for  pid=488 comm="nfs-server-gene" scontext=system_u:system_r:nfsd_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=bpf permissive=0
```

**Comment by allisonkarlitskaya** [comment]
Lovely :(

Thanks for the cherry-pick.

**Comment by martinpitt** [comment]
I have some more fixes queued. I also want a fresh build to pick up kdumpctl.

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-9dcd959e-20240522-051044/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-9dcd959e-20240522-052626/log.html

**Comment by martinpitt** [comment]
That [failure](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-9dcd959e-20240522-052626/log.html) reproduces. After installing packages, /etc/resolv.conf is a broken symlink. `systemctl start systemd-resolved` fixes it.

I noticed that during my initial experiments and thought it was a glitch, but it's systematic. Our initial image doesn't have systemd-resolved installed. But installing `wireguard-tools` pulls in `systemd-resolved` as a dependency, and its rpm script changes /etc/resolv.conf.

So: installing wireguard-tools breaks DNS, because installing systemd-resolved changes the symlink but doesn't start the service. I filed that as https://issues.redhat.com/browse/RHEL-37686 and will add a workaround.

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240522-073543

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-7c27fdc5-20240522-072129/log.html

**Comment by martinpitt** [comment]
SELinux issues are https://issues.redhat.com/browse/RHEL-37631 , added ignore.

**Review by allisonkarlitskaya — COMMENTED** [review]
:heavy_check_mark: :+1: (if I could).

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
