### PR TITLE
images: Drop kernel-modules-extra hack on centos-10

### PR DESCRIPTION
**Pull request by martinpitt**
Our current image has libvirt 10.4.0 which uses nftables by default, i.e. fixes networking. Drop the hack again.

-----

See https://github.com/cockpit-project/cockpit-machines/pull/1690#issuecomment-2182030380 for details

 * [x] image-refresh centos-10

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240621-054831

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-a68851c1-20240621-053228/log.html

**Comment by martinpitt** [comment]
[This failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6535-36172477-20240621-055011-centos-10-other-cockpit-project-cockpit/log.html#55-2) is interesting -- in RHEL, sosreport is bundled into cockpit-system, so if it is shown at all in the Applications list, it should appear as already installed. Same for networking and selinux.

This is fallout from

  appstream-data (1:10-20240326.1.el10 -> 40-5.el10)

/usr/share/swcatalog/xml/fedora.xml.gz now contains cockpit-sosreport, cockpit-networkmanager, and cockpit-selinux. I reported this to https://issues.redhat.com/browse/RHEL-44339 and will create a naughty.

**Comment by jelly** [comment]
FYI: related to nftables/libvirt https://fedoraproject.org/wiki/Changes/LibvirtVirtualNetworkNFTables

**Comment by martinpitt** [comment]
Whoa, lots of versions went *backwards*. This is https://issues.redhat.com/browse/CS-2309

**Pull request merged**
