### PR TITLE
images: Add nodejs to RHEL 9 and CentOS 8 image mocks

### PR DESCRIPTION
**Pull request by martinpitt**
Centralize the additional packages in mock into build-deps.sh, so that
the RHEL images get nodejs as well.

 * [x] image-refresh rhel-8-6
 * [x] image-refresh rhel-9-0
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 6-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-2903-20220207-083535/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-2903-20220207-083535/

**Comment by cockpituous** [comment]
image-refresh in progress on 6-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-2903-20220207-084444/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20220207-085757

**Comment by cockpituous** [comment]
image-refresh in progress on 6-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-2903-20220207-085858/

**Comment by martinpitt** [comment]
Hmm @ [rhel-8-6 failure](https://logs.cockpit-project.org/logs/image-refresh-2903-20220207-083535/) .. In the current image I can do `mock --install --verbose nodejs` just fine.

**Comment by cockpituous** [comment]
Task threw an exception: https://logs.cockpit-project.org/logs/image-refresh-2903-20220207-085858/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-2903-20220207-100707/

**Comment by cockpituous** [comment]
Task threw an exception: https://logs.cockpit-project.org/logs/image-refresh-2903-20220207-100707/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-2903-20220207-102626/

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20220207-104545

**Comment by cockpituous** [comment]
image-refresh in progress on 15-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-2903-20220207-104545/

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20220207-110303

**Comment by martinpitt** [comment]
The recent sssd selinux regression now [affects RHEL 9.0 as well](https://logs.cockpit-project.org/logs/pull-2903-20220207-110403-060a14db-rhel-9-0-cockpit-project-cockpit-machines/log.html#38). I'll copy the naughty.

**Review by marusak — APPROVED** [review]
Danke!

**Pull request merged**
