### PR TITLE
images: Install RH internal SSL certificate for package mirror

### LINKED ISSUE #6966: Image refresh for rhel-9-6
Image refresh for rhel-9-6
 * [ ] Fix download server certificate: https://issues.redhat.com/browse/INFRAPLTS-6504
 * [ ] FAIL: image-refresh rhel-9-6

### PR DESCRIPTION
**Pull request by martinpitt**
The fix for https://issues.redhat.com/browse/INFRAPLTS-6497 now caused download.devel.redhat.com to redirect http to https. This may or may not be intended, but either way it doesn't hurt to get along with it.

Install Red Hat's internal infrastructure TLS certificate so that curl/mock continue to work.

https://issues.redhat.com/browse/INFRAPLTS-6504
Fixes #6966

 * [x] image-refresh rhel-9-6

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-6-b17da746-20241009-140954/log.html

**Comment by martinpitt** [comment]
Uh, I should probably have done this for rhel-9-2 first, instead of simultaneously getting hit by all the package updates, but :crossed_fingers:

**Comment by martinpitt** [comment]
... and of course it *also* picked up the bad clevis, similar to #6961.

**Review by mvollmer — APPROVED** [review]
Thanks! Let's encrypt everything!

**Pull request merged**
