### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by martinpitt** [comment]
seems the mock build env is broken:
```
DEBUG: configure: error: in `/builddir/build/BUILD/cockpit-217.57.g91fb038a1':
DEBUG: configure: error: no acceptable C compiler found in $PATH
DEBUG: See `config.log' for more details
```

**Comment by martinpitt** [comment]
Indeed the mock on that image is missing pretty much all required build dependencies:
```
+ useradd -c Builder -G mock builder
+ '[' fedora '!=' fedora-testing ']'
+ echo 'config_opts['\''dnf.conf'\''] += '\''[updates-testing]\nenabled=1'\'''
++ cut -d - -f 1
+ opsys=fedora
++ cut -d - -f 2
+ version=testing
+ '[' testing -eq testing ']'
+ version=31
+ echo 'config_opts['\''use_bootstrap'\''] = False'
++ /var/lib/testvm/build-deps.sh 'fedora 31'
error: line 1: Unknown tag: 500: Internal Server Error
error: query of specfile /dev/stdin failed, can't parse
+ su builder -c '/usr/bin/mock --no-bootstrap-chroot --verbose -i intltool'
```
This ought to fail the image build, not silently succeed like that.

**Comment by martinpitt** [comment]
I added a commit that robustifies image build. I suspect GitHub was down at the time it tried to build this image, so let's rebuild it.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-787-20200427-130505/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-testing-20200427-135252

**Comment by martinpitt** [comment]
[libvirt crash](https://logs.cockpit-project.org/logs/pull-787-20200427-144405-f4d5bf8f-fedora-testing-cockpit-project-cockpit/log.html#94-2), that smells like https://github.com/cockpit-project/bots/issues/798

**Comment by martinpitt** [comment]
I shamelessly stole @marusak 's naughty and copied it here.

**Pull request merged**
