### PR TITLE
images: Pull images for Docker from quay.io instead of docker.io

### PR DESCRIPTION
**Pull request by mvollmer**
- [x] Improved naughty for fsadm, best to have the real error in the dialog, next best is to dump unexpected journal messages always so that we can match against them, maybe just do both
- [x] TestEmbedded, https://github.com/cockpit-project/cockpit/pull/15017
- [x] https://github.com/cockpit-project/cockpit/pull/15021
- [x] https://github.com/cockpit-project/cockpit/pull/15033

 * [x] image-refresh rhel-7-9
 * [x] image-refresh centos-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-1443-20201204-110606/

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-7-9-20201204-113030

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-1443-20201204-113232/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/bots/commits/image-refresh-centos-7-20201204-115858

**Comment by mvollmer** [comment]
Upps, I fat-fingured a couple of irrelevant test runs onto this PR (they were intended for #1429)

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-1443-20201204-134848/

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-7-9-20201204-141515

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-1443-20201204-141616/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/bots/commits/image-refresh-centos-7-20201204-144141

**Comment by martinpitt** [comment]
Moving to draft, the images still need to be pushed and tests run.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-1443-20201207-090303/

**Comment by mvollmer** [comment]
(rhel-7-9 has to be made again, it didn't pick up 55f4777...)

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-7-9-20201207-092525

**Comment by mvollmer** [comment]
rhel-7-9@cockpit-project/cockpit/rhel-7.9  seems to have genuine failures, as expected from stable OS releases, like `/usr/sbin/fsadm: line 818: $3: unbound variable`.

**Comment by mvollmer** [comment]
The insights-client in rhel-7-9 now unconditionally uploads performance metrics to Satellite or cloud.redhat.com about itself. Some failure modes are ignored, but not all.

In our specific case, insights-client does not honor the `insecure = 1` setting for our Candlepin instance, and fails with a certificate validation error. This aborts everything.

If we can make the certificate validation pass, the actual upload might not be accepted by our Candlepin instance, but I think that should not lead to a aborted insights-client run.

**Comment by mvollmer** [comment]
Status: I figured out the reasons for the rhel-7-9 regressions, but the fixes need improvement, see the description.

**Comment by mvollmer** [comment]
Notes for myself: Appending /etc/candlepin/certs/candlepin-ca.crt to /etc/pkit/tls/certs/ca-bundle.crt does the trick for curl and hopefully also for HTTPClient.

**Comment by mvollmer** [comment]
> Notes for myself: Appending /etc/candlepin/certs/candlepin-ca.crt to /etc/pkit/tls/certs/ca-bundle.crt does the trick for curl and hopefully also for HTTPClient.

insights-client wants it in /etc/rhsm/ca/redhat-uep.pem.

**Review by martinpitt — APPROVED** [review]
Looks great, thanks for sorting this out!

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
