### PR TITLE
Image refresh for fedora-34

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-34
 * [x] image-refresh fedora-34

### CODE REVIEW

**Comment by martinpitt** [comment]
podman is kaputt

**Comment by allisonkarlitskaya** [comment]
I think the correct solution here is to wait:

https://bodhi.fedoraproject.org/updates/FEDORA-2021-51708c90bc

**Comment by martinpitt** [comment]
Agreed, changing to blocked. It already has enough karma.

**Comment by marusak** [comment]
It has been in stable for two days. Closing so tomorrow we will get a new update

**Pull request closed without merging**
