### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by marusak** [comment]
[one](https://logs.cockpit-project.org/logs/pull-602-20200304-002641-9d0e38c0-fedora-testing-cockpit-project-cockpit/log.html) failure, retrying for comparison

**Comment by marusak** [comment]
`Install setroubleshoot-server to troubleshoot SElinux events.`

**Comment by marusak** [comment]
`setroubleshoot-server-3.3.22-5.fc31.x86_64` is installed so there is different issue.

**Comment by martinpitt** [comment]
The journal shows the cause:
```
Mar 04 02:39:16 localhost.localdomain setroubleshootd[7077]: Traceback (most recent call last):
Mar 04 02:39:16 localhost.localdomain setroubleshootd[7077]:   File "/usr/sbin/setroubleshootd", line 35, in <module>
Mar 04 02:39:16 localhost.localdomain setroubleshootd[7077]:     from setroubleshoot.util import log_debug
Mar 04 02:39:16 localhost.localdomain setroubleshootd[7077]:   File "/usr/lib/python3.7/site-packages/setroubleshoot/util.py", line 71, in <module>
Mar 04 02:39:16 localhost.localdomain setroubleshootd[7077]:     from pydbus import SystemBus
Mar 04 02:39:16 localhost.localdomain setroubleshootd[7077]: ModuleNotFoundError: No module named 'pydbus'
```
So, missing dependency apparently.

**Comment by martinpitt** [comment]
I :-1 'ed https://bodhi.fedoraproject.org/updates/FEDORA-2020-b5030bee51 to block this from going into fedora 31. I'm glad that our tests found an actual regression before it hits the masses!

**Pull request closed without merging**
