### PR TITLE
Image refresh for centos-8-stream

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-8-stream
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by marusak** [comment]
[4 failures](https://logs.cockpit-project.org/logs/pull-762-20200427-100418-450e30a0-centos-8-stream-cockpit-project-cockpit/log.html), retying to compare.

**Comment by marusak** [comment]
`test/verify/check-storage-luks TestStorage.testClevisTang` needs to be looked at.

**Comment by marusak** [comment]
Sent fix in https://github.com/cockpit-project/cockpit/pull/13979

**Comment by martinpitt** [comment]
[testDetachDisk](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-762-20200428-050201-450e30a0-centos-8-stream-cockpit-project-cockpit/log.html) again..

**Comment by marusak** [comment]
> testDetachDisk again..

thats like 5th time, lets assume it is broken and needs to be adjusted.

**Comment by marusak** [comment]
well, I cannot reproduce it locally and it passed now. So this is just very flaky test.

**Pull request merged**
