### PR TITLE
Image refresh for rhel-8-1

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-1
 * [x] image-refresh rhel-8-1

### CODE REVIEW

**Comment by marusak** [comment]
`Installing: intltool` and fails to pull deps. We dropped this and it needs to be backported into stable branches.

**Comment by martinpitt** [comment]
Argh, right -- let's please put back intltool into the rhel-8-1 image's mock then.

**Comment by martinpitt** [comment]
I  pushed a fix to put back intltool.

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-157-20191024-071515/

**Comment by martinpitt** [comment]
Bah:
```
Error validating install location: Could not find an installable distribution at 'http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/': The URL could not be accessed, maybe you mistyped?
```

Fixed.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-157-20191024-080303/

**Comment by cockpituous** [comment]
image-refresh rhel-8-1 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-1-20191024-082222

**Comment by martinpitt** [comment]
The lorax tar failure is "known", I pinged the maintainers this morning. But we should retry the [cockpit rhel-8-appstream failure](https://209.132.184.41:8493/logs/pull-157-20191024-084242-54f16194-cockpit-project-cockpit-rhel-8-appstream-rhel-8-1/log.html#201)

**Pull request merged**
