### PR TITLE
image-refresh: Do not trigger tests when refreshing in pull request

### PR DESCRIPTION
**Pull request by marusak**
* [x] image-refresh rhel-8-5

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3135-20220324-081313/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3135-20220324-081313/

**Comment by cockpituous** [comment]
image-refresh rhel-8-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-5-20220324-083535

**Comment by cockpituous** [comment]
image-refresh rhel-8-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-5-20220324-091414

**Comment by marusak** [comment]
So this works \o/ It created refresh but not triggered any tests. There is no reasonable way how to test this, but it should :tm: work as `task.pull()` has the same logic and then it would never convert issue into pull request if `pull` would be present.

**Review by martinpitt — APPROVED** [review]
Looks very plausible, thank you!

**Pull request merged**
