### PR TITLE
images: Fix fedora-35, 36, and testing

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh fedora-36
 * [x] image-refresh fedora-35
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-3464-20220601-085757/

**Comment by mvollmer** [comment]
fedora-35 has not been updated since the broken commit 97af4bf. Also, the (pixel) tests would have caught it moving to Fedora 36.

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20220601-091919

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-3464-20220601-091919/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3464-20220601-091919/

**Comment by mvollmer** [comment]
Let's update fedora-36 for real here, and only test that fedora-35 and fedora-testing images can be created and are based on the expected cloud image.

**Comment by cockpituous** [comment]
image-refresh fedora-35 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-35-20220601-094040

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3464-20220601-094141/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20220601-100303

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-d262w.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3464-20220601-100303/

**Review by martinpitt — APPROVED** [review]
Danke!

**Pull request merged**
