### PR TITLE
images: Reduce libpwquality checks on RHEL ≥ 8.2 images

### PR DESCRIPTION
**Pull request by martinpitt**
Same as commit cce925994 for Fedora. This fixes composer's tests on
latest 8.2.

 * [x] image-refresh rhel-8-2

### CODE REVIEW

**Comment by martinpitt** [comment]
This should fix #292

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-336-20191216-161515/

**Comment by cockpituous** [comment]
image-refresh rhel-8-2 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-2-20191216-164141

**Comment by marusak** [comment]
`image-download: image link does not exist: /build/cockpit-project/bots/make-checkout-workdir/bots/images/selenium` seems that `rhel-8.2` branch in c-composer does not have patch to use `services` package?

**Comment by marusak** [comment]
Yeah, https://github.com/weldr/cockpit-composer/commit/641663ffd02fb757262d344bb68f552ff3d3df7e this commit needs to be backported into rhel-8.2 branch, I'll send PR

**Comment by marusak** [comment]
https://github.com/weldr/cockpit-composer/pull/851

**Comment by martinpitt** [comment]
Most of the tests fail due to https://bugzilla.redhat.com/show_bug.cgi?id=1782435. This is too big for a naughty, and needs a hack in cockpit's testlib.

**Comment by martinpitt** [comment]
The virt-what failure apparently [breaks the "virtual-guest" profile](https://209.132.184.41:8493/logs/pull-336-20191216-202323-a1a1c13a-cockpit-project-cockpit--rhel-8-2/log.html#261-2). That's not very surprising, as it's actually tuned (and subscription-manager) that require the virt-what package in the first place. The two timer related tests are https://bugzilla.redhat.com/show_bug.cgi?id=1779098 and apparently need some naughty tweaking.

**Pull request merged**
