### PR TITLE
Image refresh for rhel-9-4

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-4
 * [x] image-refresh rhel-9-4
 * [ ] https://github.com/candlepin/subscription-manager-cockpit/pull/64

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-9-4 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-4-20240401-225350

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-4-7a3c02e3-20240401-223733/log.html

**Comment by martinpitt** [comment]
sub-man testSubAndInAndFail test is notoriously flaky, but it failed retries three times in a row. This  needs a closer look.

**Comment by mvollmer** [comment]
> sub-man testSubAndInAndFail test is notoriously flaky, but it failed retries three times in a row. This needs a closer look.

It fails also with our current image.  https://github.com/candlepin/subscription-manager-cockpit hasn't seen an update in 7 months, hmm.

I'll investigate more.

**Comment by mvollmer** [comment]
> I'll investigate more.

Seems to be a too short timeout.

**Comment by martinpitt** [comment]
Note that I sent https://github.com/candlepin/subscription-manager-cockpit/pull/63 just last week, and it passed.

**Comment by mvollmer** [comment]
> Note that I sent [candlepin/subscription-manager-cockpit#63](https://github.com/candlepin/subscription-manager-cockpit/pull/63) just last week, and it passed.

Yes, with warnings about getting very close to the timeout... :-)

**Comment by martinpitt** [comment]
Oh right -- I faintly remember patching `run-tests` to show them even for successful tests :grin: https://github.com/cockpit-project/cockpit/commit/ebaea5592d000a41557cf73d75e16a7ae70fa844

**Comment by mvollmer** [comment]
I was suspecting that we miss some notification, but it just takes long for insights-client to fail.

 - I see if I can implement a cleaner way for it to fail by having mock-insights return an error. This doesn't make the test faster, but is more realistic.
 - There is a avalanche of "[Errno -2] Name or service not known" alerts popping up. I'll investigate that as well.

**Comment by mvollmer** [comment]
> * There is a avalanche of "[Errno -2] Name or service not known" alerts popping up. I'll investigate that as well.

No, I gave up on that. Nicht meine Baustelle.

**Comment by mvollmer** [comment]
> * I see if I can implement a cleaner way for it to fail by having mock-insights return an error. This doesn't make the test faster, but is more realistic.

https://github.com/candlepin/subscription-manager-cockpit/pull/64

**Comment by martinpitt** [comment]
The re-re-re-retry failed as well. Blocking for a while. However, let's time out in a week or so, we shouldn't block the refresh forever.

**Review by martinpitt — APPROVED** [review]

**Comment by martinpitt** [comment]
Landing -- more RHEL images are coming in, and this isn't a regression.

**Pull request merged**
