### PR TITLE
various cleanups on RHEL images

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh rhel-9-0
 * [x] image-refresh rhel-8-6
 * [x] image-refresh rhel-8-5
 * [x] image-refresh rhel-8-4
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-2625-20211112-042727/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20211112-044141

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-2625-20211112-044646/

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20211112-050505

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2625-20211112-054646/

**Comment by cockpituous** [comment]
image-refresh rhel-8-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-5-20211112-060606

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2625-20211112-060707/

**Comment by cockpituous** [comment]
image-refresh rhel-8-4 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-4-20211112-062828

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-2625-20211112-062828/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2625-20211112-062828/

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20211112-070404

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-2625-20211112-071919/

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20211112-075151

**Comment by martinpitt** [comment]
@ptoscano: Do these [two unexpected messages](https://logs.cockpit-project.org/logs/pull-2625-20211112-080950-86b2f5be-rhel-8-6-candlepin-subscription-manager/log.html#1) ring a bell? I'm happy to report them as a bug and we can add a filter for the message, just want to check that it's not something which is interesting to you?

**Comment by ptoscano** [comment]
> @ptoscano: Do these [two unexpected messages](https://logs.cockpit-project.org/logs/pull-2625-20211112-080950-86b2f5be-rhel-8-6-candlepin-subscription-manager/log.html#1) ring a bell? I'm happy to report them as a bug and we can add a filter for the message, just want to check that it's not something which is interesting to you?

Hmm it does not sound nice. It means that either
1. sub-man's mock-insights test server does not fully emulate the real server as insights-client expects
2. what images/scripts/rhel.setup does with the *.egg files of insights-client is not correct
3. something else I'm missing

I had to disable the Insights tests for sub-man with `rhel-9-0`, however the issue was different. Considering I was told that insights-client works fine otherwise, I started to think that (1) could be the problem, and thus I wonder if the same applies now with a new version of insights-client.

Would it be possible to exclude the `rhel-8-6` image from this refresh PR, for now? It seems also cockpit broke, so maybe it's better to refresh it separately.

**Comment by martinpitt** [comment]
Reported [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2022655), added known issue #2626, added naughty.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
