### PR TITLE
Image refresh for rhel-8-5

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-5
 * [x] image-refresh rhel-8-5
 * [x] change mock-insights to TLS: https://github.com/cockpit-project/cockpit/pull/15698

### CODE REVIEW

**Comment by marusak** [comment]
`insights-client --register` is failing also locally. Needs work. I'll take a look at it in a bit.

**Comment by marusak** [comment]
so I see there two issues:
1. `insecure_connection` is not a thing apparently. And indeed it is not documented anywhere.
2. Our [mock-server](https://github.com/cockpit-project/cockpit/blob/master/test/verify/files/mock-insights) does not know about `/r/insights/platform/module-update-router/v1/channel\\?module=(.*)` but even when I add it it still fails to connect.

Even previous rhel-8-5 image would not recogznize this option yet it would not fail. There is almost no difference in packages:
```
Removed:

Added:

Changed:
  annobin (9.50-1.el8 -> 9.65-1.el8)
  crypto-policies (20200713-1.git51d1222.el8 -> 20210209-1.gitbfb6bed.el8_3)
  crypto-policies-scripts (20200713-1.git51d1222.el8 -> 20210209-1.gitbfb6bed.el8_3)
  device-mapper-multipath (0.8.4-10.el8 -> 0.8.4-11.el8)
  device-mapper-multipath-libs (0.8.4-10.el8 -> 0.8.4-11.el8)
  file (5.33-16.el8 -> 5.33-16.el8_3.1)
  file-libs (5.33-16.el8 -> 5.33-16.el8_3.1)
  kpartx (0.8.4-10.el8 -> 0.8.4-11.el8)
  python3-magic (5.33-16.el8 -> 5.33-16.el8_3.1)
  shim-x64 (15-16.el8 -> 15.4-2.el8_1)
```

Output:

```sudo insights-client --register 
WARNING: Unknown options: insecure_connection
Error: Could not submit event: Could not find the TLS certificate file, invalid path: /etc/pki/consumer/cert.pem
Fatal error
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
    ssl_context=context)
  File "/usr/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 367, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 776, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1036, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:897)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: /r/insights/platform/module-update-router/v1/channel?module=insights-core (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:897)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/insights/newest.egg/insights/client/phase/v1.py", line 32, in _f
    func(client, config)
  File "/var/lib/insights/newest.egg/insights/client/phase/v1.py", line 124, in update
    client.update()
  File "/var/lib/insights/newest.egg/insights/client/__init__.py", line 259, in update
    egg_paths = self.fetch()
  File "/var/lib/insights/newest.egg/insights/client/__init__.py", line 132, in fetch
    egg_release = self.get_egg_url()
  File "/var/lib/insights/newest.egg/insights/client/__init__.py", line 73, in _init_connection
    return func(self, *args, **kwargs)
  File "/var/lib/insights/newest.egg/insights/client/__init__.py", line 110, in get_egg_url
    response = self.session.get(url, timeout=self.config.http_timeout)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: /r/insights/platform/module-update-router/v1/channel?module=insights-core (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:897)'),))
Error: Could not submit event: Could not find the TLS certificate file, invalid path: /etc/pki/consumer/cert.pem
Fatal error
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
    ssl_context=context)
  File "/usr/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 367, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 776, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1036, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:897)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: /r/insights/platform/module-update-router/v1/channel?module=insights-core (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:897)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/insights/last_stable.egg/insights/client/phase/v1.py", line 32, in _f
    func(client, config)
  File "/var/lib/insights/last_stable.egg/insights/client/phase/v1.py", line 124, in update
    client.update()
  File "/var/lib/insights/last_stable.egg/insights/client/__init__.py", line 259, in update
    egg_paths = self.fetch()
  File "/var/lib/insights/last_stable.egg/insights/client/__init__.py", line 132, in fetch
    egg_release = self.get_egg_url()
  File "/var/lib/insights/last_stable.egg/insights/client/__init__.py", line 73, in _init_connection
    return func(self, *args, **kwargs)
  File "/var/lib/insights/last_stable.egg/insights/client/__init__.py", line 110, in get_egg_url
    response = self.session.get(url, timeout=self.config.http_timeout)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: /r/insights/platform/module-update-router/v1/channel?module=insights-core (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:897)'),))
Error: Could not submit event: Could not find the TLS certificate file, invalid path: /etc/pki/consumer/cert.pem

```

So I think our mock server needs to properly do https?

**Comment by martinpitt** [comment]
@marusak : I'm quite sure it's the addition of crypto-policies which disable some old TLS version, certificate properties, or somethinng similar.

**Comment by marusak** [comment]
Comparing `crypto-policies` only `/usr/share/crypto-policies/policies/modules/OSPP.pmod` changed.
It adds:
```
mac = -HMAC-SHA1  # see above, both SSH and TLS ended up not using it 
sign = -ECDSA-SHA2-512
```

and modified from:
```
ssh_group = -FFDHE-4096 -FFDHE-8192 
```
to
```
ssh_group = -FFDHE-2048 -FFDHE-4096 -FFDHE-8192
```

**Comment by martinpitt** [comment]
This has nothing to do with crypto-policies. What changed is the insights-client itself:
```
# insights-client --version
WARNING: Unknown options: insecure_connection
Client: 3.1.1
Core: 3.0.217-1
```
Current image has "Core: 3.0.216-1". Looking at the mock insights server http log, insights-client now tries to talk https to the mock server, which it doesn't support. The "WARNING: Unknown options: insecure_connection" is the clue here, apparently it forgot how to speak plain http.

Unfortunately, setting `base_url=http://...` does not work either, it insists on https. So we need to make our mock server https somehow.

**Comment by martinpitt** [comment]
I tried to https-ify our mock server, but this is no end of trouble: 
 - I first tried to use src/bridge/mock-server.{crt,key}, but RHEL 8.5's OpenSSL somehow does not like that:
```
openssl s_server -cert /var/tmp/mock-server.crt -key /var/tmp/mock-server.key
openssl s_client -connect localhost:8888 -CAfile /var/tmp/mock-server.crt -verify_return_error
→ "unable to get local issuer certificate"
```
(but works with curl). Using src/tls/ca's alice and ca.pem works with openssl s_client and Python, when adding "alice" to /etc/hosts:
```
python3 -c 'import urllib.request; print(urllib.request.urlopen("https://alice:8888/r/insights").read())'
b'lub-dup'
```

but `insights-client --register` still fails later on:
```
Error: Could not submit event: HTTPSConnectionPool(host='cert.cloud.redhat.com', port=443): Max retries exceeded with url: /api/module-update-router/v1/event (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd1a6163048>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

Not sure why it now tries to talk to cert.cloud.redhat.com, it really can't. There is some serious hardcoding going on in the new insights-client apparently.

**Comment by martinpitt** [comment]
This is my current status:

[0001-test-Enable-TLS-for-mock-insights-server.patch.txt](https://github.com/cockpit-project/bots/files/6317206/0001-test-Enable-TLS-for-mock-insights-server.patch.txt)

In addition I hot-patched /usr/lib/python3.6/site-packages/insights_client/metrics.py to just return in the `post()` function, to short-circuit the metrics stuff. It may also help a bit to set `authmethod=BASIC` in /etc/insights-client/insights-client.conf

But this is still not enough, I once again  get TLS cert errors for localhost:8888, even though both python and curl work fine now.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
