### PR TITLE
images: Reduce Fedora image size

### PR DESCRIPTION
**Pull request by martinpitt**
* Only install qemu-system-x86-core instead of the full "qemu". We
   don't need the support for emulating other architectures, qemu-gui,
   etc. Unfortunately libvirt packages still pull in a ton of
   unnecessary graphic/desktop stuff, but we can't easily help that.

 * Never create and use a separate bootstrap chroot. We only use the
   regular one for exactly one build, and we don't want to carry around
   an extra 400 MB for the -bootstrap chroot.

 * Remove the mock cache, and in lieu of a `dnf_builddep_command`
   option, hack mock to disable `dnf builddep`. This saves another
   500MB.

 * Remove old kernels after upgrading.

 * Remove some development packaes like gcc, kernel-headers, etc.

 * [x] image-refresh fedora-31
 * [x] image-refresh fedora-32

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-658-20200319-135151/

**Comment by martinpitt** [comment]
This reduces the fedora-32 image from 2.6 GB to 1.6 GB, which is about as much as we can do (argh at overzealous package dependencies -- debian-stable is 1.2 GB). But that's already something, 40% less!

**Comment by cockpituous** [comment]
image-refresh fedora-31 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-31-20200319-145555

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-658-20200319-145656/

**Comment by martinpitt** [comment]
fedora-31 went from 3.0 to 2.0 GB.

**Comment by cockpituous** [comment]
image-refresh fedora-32 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-32-20200319-154848

**Comment by martinpitt** [comment]
[This is obviously broken](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-658-20200319-171319-94b6d033-fedora-32-cockpit-project-cockpit/log.html), I wonder how my previous test survived that (I also just used image-prepare fedora-32). I successfully tested a fix in fedora.install, but to really do this cleanly, I should rebuild the images.

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-658-20200319-173030/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-658-20200319-173434/

**Comment by cockpituous** [comment]
image-refresh fedora-32 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-32-20200319-180707

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-658-20200319-183939/

**Comment by cockpituous** [comment]
image-refresh fedora-31 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-31-20200319-192020

**Comment by martinpitt** [comment]
Meh, seems this [breaks lorax](https://logs.cockpit-project.org/logs/pull-658-20200319-192209-6cae9d88-fedora-31-aws-weldr-lorax/log.html)?

**Comment by martinpitt** [comment]
For lorax the problem is that the [build](https://logs.cockpit-project.org/logs/pull-980-20200319-210342-d6ce9c90-fedora-31/log) *does* install build deps from the internet, and actually quite a lot of them. So that needs to keep working.

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-658-20200323-074747/

**Comment by cockpituous** [comment]
image-refresh fedora-31 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-31-20200323-082424

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-658-20200323-082424/

**Pull request merged**
