### PR TITLE
images: add wireguard-tools to Arch

### PR DESCRIPTION
**Pull request by subhoghoshX**
* [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20230719-203030.log

**Comment by martinpitt** [comment]
Oops, I'm afraid this is fallout from commit 230139a566fd8f4ae somehow.

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20230719-205536

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20230719-205555.log

**Review by jelly — APPROVED** [review]

**Pull request merged**
