### PR TITLE
Image refresh for fedora-rawhide-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-boot
 * [x] image-refresh fedora-rawhide-boot

### CODE REVIEW

**Comment by martinpitt** [comment]
[failed to boot](https://logs.cockpit-project.org/logs/pull-3277-20220423-032741-a5434ecf-fedora-rawhide-boot-rhinstaller-anaconda/log), retrying to rule out infra trouble.

**Comment by martinpitt** [comment]
Nope, this is kaputt. @jelly: Suggestion - just close this and let the bots create a fresh one, and hope that it works again :grin: If not, escalate to @jkonecny12 for debugging this.

**Comment by VladimirSlavik** [comment]
Just making sure - If I was going to do the debugging, I would grab the iso from url at end of log and proceed from there, right?

**Comment by martinpitt** [comment]
@VladimirSlavik : You can grab https://github.com/cockpit-project/bots/pull/3277.patch and `git am` it, or `git fetch origin refs/pull/3277/head && git checkout FETCH_HEAD`. You can of course download the image manually, but that wouldn't work with all the local test machinery.

**Pull request closed without merging**
