### PR TITLE
images: Include selenium containers on services image

### PR DESCRIPTION
**Pull request by martinpitt**
This will replace our selenium image, once cockpit's and
cockpit-composer's tests switch over. Thus already trigger cockpit
selenium tests on refreshes, as
https://github.com/cockpit-project/cockpit/pull/13191 will land soon
after this.

 * [x] image-refresh services

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-281-20191126-125959/

**Comment by martinpitt** [comment]
See PR #164 for some background. This will allow us to move forward with current firefox/chrome for cockpit testing, while not immediately breaking cockpit-composer.

**Comment by cockpituous** [comment]
image-refresh services done: https://github.com/cockpituous/bots/commits/image-refresh-services-20191126-135353

**Comment by martinpitt** [comment]
"debian-stable@cockpit-project/cockpitrhel-8-2@cockpit-project/cockpit"? That's clearly bogus, let's fix that typo while I'm at it. I added a commit.

**Pull request merged**
