### PR TITLE
Image refresh fedora 32 20201103 015555

### PR DESCRIPTION
**Pull request by KKoukiou**
This is just building on top of https://github.com/cockpit-project/bots/pull/1357 because I can't push to cockpituous.
Till I get permissions for that - let's tests it here.

### CODE REVIEW

**Comment by martinpitt** [comment]
Thanks @KKoukiou! Please trigger a few more images to make sure that this also works on e. g. centos-8-stream or debian-stable.

> I can't push to cockpituous.

It's not about you -- sometimes cockpituous PRs are not pushable by project owners (I can't push to *that* branch either). Most of the time it works, and nobody found out why sometimes it doesn't..

**Review by marusak — APPROVED** [review]
Just `TestSource.testBasic` failing in c-composer, but that is known issue being fixed in https://github.com/osbuild/cockpit-composer/pull/1155

**Comment by KKoukiou** [comment]
Triggered also tests for centos and debian, just to make sure I did not break these.

**Comment by KKoukiou** [comment]
both debian and centos-8 failing tests are unrelated, all network tests have passed.

**Pull request merged**
