### PR TITLE
images: install strace and ltrace on fedora

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
strace and ltrace are extremely useful tools, and quite small.  Let's
have them in our images.

Skipping image-refresh fedora-30 because of unrelated failures blocking us.

 * [x] image-refresh fedora-29
 * [x] image-refresh fedora-31
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-202-20191103-131818/

**Comment by cockpituous** [comment]
image-refresh fedora-23-stock done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-23-stock-20191103-133838

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-202-20191103-133939/

**Comment by cockpituous** [comment]
image-refresh fedora-29 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-29-20191103-144343

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-t5p60.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-202-20191103-144343/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-202-20191103-144343/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-t5p60.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-202-20191103-150000/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-202-20191103-150000/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-01.
Log: https://209.132.184.41:8493/logs/image-refresh-202-20191103-152727/

**Comment by cockpituous** [comment]
image-refresh fedora-atomic done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-atomic-20191103-160707

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-01.
Log: https://209.132.184.41:8493/logs/image-refresh-202-20191103-160707/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-202-20191103-160707/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-01.
Log: https://209.132.184.41:8493/logs/image-refresh-202-20191103-164343/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-202-20191103-164343/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-7rmdk.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-202-20191103-163535/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-202-20191103-163535/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-7rmdk.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-202-20191103-163636/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-testing-20191103-165959

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://209.132.184.41:8493/logs/image-refresh-202-20191103-165959/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-202-20191103-165959/

**Comment by martinpitt** [comment]
I removed the builds that aren't affected by fedora.setup.

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-t5p60.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-202-20191103-195454/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-202-20191103-195454/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-t5p60.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-202-20191103-201111/

**Comment by martinpitt** [comment]
fedora-30 fails due to the same problem as in #158 and #196, let's skip that for now.

**Comment by cockpituous** [comment]
Task failed: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-202-20191103-201111/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-fqpbg.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-202-20191103-203030/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-202-20191103-203030/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-202-20191103-204040/

**Comment by cockpituous** [comment]
image-refresh fedora-31 done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-31-20191103-210909

**Comment by martinpitt** [comment]
I salvaged the [missing fedora-29 rebuild](https://209.132.184.41:8493/logs/pull-202-20191104-085252-b11a9534-cockpit-project-cockpit-podman--fedora-29/log.html), retrying tests.

**Pull request merged**
