### PR TITLE
Image refresh for fedora-40

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-40
 * [x] image-refresh fedora-40
 * [x] Requires https://github.com/cockpit-project/cockpit-podman/pull/1608
 * [x] Requires https://github.com/cockpit-project/cockpit/pull/20153

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-40 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-40-20240308-225943

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-40-1c40dcef-20240308-223715/log.html

**Comment by martinpitt** [comment]
podman has lots of [failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6050-20240308-230105-686c9e16-fedora-40-cockpit-project-cockpit-podman/log.html) like
```
Error: pasta failed with exit code 1:
No routable interface for IPv4: IPv4 is disabled
External interface not usable
```

That's already reported as https://github.com/containers/podman/issues/21896 , we need to expand the current workaround.

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit-podman/pull/1608 for this pasta workaround. 

The [metrics tests](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6050-20240309-073607-686c9e16-fedora-40-other-cockpit-project-cockpit/log.html) failed on the exact same issue, so I'll apply the hack there as well.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
