### PR TITLE
images: Add rhel-8-7

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh rhel-8-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-3377-20220516-113030/

**Comment by cockpituous** [comment]
image-refresh rhel-8-7 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-7-20220516-120101

**Comment by martinpitt** [comment]
#3375 adds the test contexts, for enabling them on our projects. For now I test-booted the image, made sure it looks sane, and ran starter-kits test against it. So the image works in principle.

**Review by marusak — APPROVED** [review]
But looks good ofc, thanks!

**Comment by martinpitt** [comment]
@marusak : I only did a local run. But I'll enable c-podman etc. next (running locally, unfortunately some regressions).

**Pull request merged**
