### PR TITLE
Image refresh for rhel-8-10

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-10
 * [x] image-refresh rhel-8-10
 * [x] https://github.com/cockpit-project/cockpit/pull/20393

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-8-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-10-20240428-225728

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-8-10-8a22acf8-20240428-223717/log.html

**Comment by martinpitt** [comment]
Ah, I'll backport the "uncentos7" commit to the rhel-8 branch.

**Review by martinpitt — APPROVED** [review]
The encrypted stratis failure is not a regression, see https://github.com/cockpit-project/cockpit/pull/20373

**Pull request merged**
