### PR TITLE
Image refresh for fedora-33

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-33
 * [x] image-refresh fedora-33

### CODE REVIEW

**Comment by martinpitt** [comment]
[testOSTreeCommit](https://logs.cockpit-project.org/logs/pull-2603-20211107-073441-3bbe8b00-fedora-33-osbuild-cockpit-composer/log.html) failure -- this is not just a flake, I already retried once. @jkozol , @henrywang , can you please have a look here what went wrong? Also, with F35 being released, F33 is on its way to EOL -- does it still even make sense to test/release c-composer to F33?

Thanks!

**Comment by martinpitt** [comment]
@jkozol , @henrywang: In other words -- these two c-composer tests are the only reasons why our CI even has a F33 image still, we need to lose it at some point as F33 becomes unsupported.

**Comment by henrywang** [comment]
@martinpitt Thanks. After talk with @jkozol, I'll send a PR to remove fedora 33.

**Comment by jkozol** [comment]
@martinpitt Thanks for pointing this out. I will also drop f33 from cockpit-composer's cockpuous-release.

**Comment by martinpitt** [comment]
@KKoukiou : Dear pilot, #2609 dropped that test -- so please just remove the f-33 image entirely now, and close this PR.

**Comment by martinpitt** [comment]
#2610 dropped the image, thanks!

**Pull request closed without merging**
