### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos
 * [x] Fix kernelopt.sh option handling: https://github.com/cockpit-project/cockpit/pull/13561

### CODE REVIEW

**Comment by martinpitt** [comment]
[testCPUSecurityMitigations failure](https://logs.cockpit-project.org/logs/pull-531-20200217-083636-c976f33c-fedora-coreos-cockpit-project-cockpit/log.html#266-2), retrying once for comparison.

**Comment by marusak** [comment]
@martinpitt I was waiting for this run, as it failed on the same before - [log](https://logs.cockpit-project.org/logs/pull-531-20200217-075757-c976f33c-fedora-coreos-cockpit-project-cockpit/log.html#266-1)

**Comment by martinpitt** [comment]
@marusak : Ack, thanks. I'll take a look.

**Comment by martinpitt** [comment]
This exposed an actual bug, I sent a fix here: https://github.com/cockpit-project/cockpit/pull/135615

**Comment by marusak** [comment]
Rebased as fedora-30 changed in the meantime

**Pull request merged**
