### PR TITLE
Image refresh for rhel-8-6

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-6
 * [x] image-refresh rhel-8-6
 * [x] sort out qemu 6.1 → 6.2 NIC delete regression in #2733

### CODE REVIEW

**Comment by skobyda** [comment]
At first glance the c-machines failure looks like the same as here https://github.com/cockpit-project/bots/pull/2733

**Comment by martinpitt** [comment]
Right, this image also updated QEMU from 6.1 to 6.2. Moving "needswork" to "blocked", let's figure this out in #2733 and add naughties for all affected OSes there.

**Comment by martinpitt** [comment]
@jkozol : Do you know what [this failure](https://logs.cockpit-project.org/logs/pull-2753-20211225-062901-5d0c8638-rhel-8-6-osbuild-cockpit-composer/log.html#5-2) is about? "ssh server image" → "edit ssh server image description" label change looks totally unintended -- this is not an action, so it shouldn't have the "edit.." wrapping.

**Comment by martinpitt** [comment]
Rebased to pick up naughty for the virt-xml regression. This still leaves the composer failure though, so needswork.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
