### PR TITLE
DBG - insights-client selinux labels

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh rhel-8-6

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3053-20220309-124040/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3053-20220309-124040/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-3053-20220309-125252/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3053-20220309-130404/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3053-20220309-130404/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3053-20220309-125252/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-3053-20220309-133535/

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20220309-135555

**Comment by mvollmer** [comment]
It might make sense to get rid of that insights-client dance.  It might actually not do anything anymore, and at least for me it has produced a metric ton of garbage in the logs...

But this here was just to figure out if we do something wrong re labels during image build.  We don't.

**Comment by martinpitt** [comment]
@mvollmer : IIRC the original point of that exercise was that it would download its actual code (the python egg). During tests it both can't and should not do that, as the VMs are offline.

**Pull request closed without merging**
