### PR TITLE
Image refresh for rhel-9-2

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-2
 * [x] image-refresh rhel-9-2

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-9-2 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-2-20240618-225607

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-2-b43cff29-20240618-223723/log.html

**Comment by martinpitt** [comment]
Hmm, our rhel4edge image went out of sync:

> Problem: package cockpit-ws-318.dev21+g531286241-1.el9.x86_64 from @commandline requires (selinux-policy >= 38.1.11-2.el9_2.6 if selinux-policy-targeted), but none of the providers can be installed

The rhel4edge image is on the chopping block anyway, but I'll try a quick refresh for that first.

**Comment by martinpitt** [comment]
Done in #6524, let's try again.

**Comment by jelly** [comment]
Needs a rebase for the new rhel4edge image.

**Comment by martinpitt** [comment]
@jelly worth a try, it's just a shot into the dark, though -- I haven't looked *at all* what's going wrong here.

**Comment by martinpitt** [comment]
Let's just let the bots build a new one, there's no hurry.

**Pull request closed without merging**
