### PR TITLE
Image refresh for fedora-36

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-36
 * [x] image-refresh fedora-36

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20230225-230623

**Comment by cockpituous** [comment]
Completed. Log: Error accessing /repos/cockpit-project/bots/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value":4456,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-36-20230225-230505.log

**Comment by mvollmer** [comment]
Running dnf in the new fedora-36 image needs more than 1 GiB when processing repository meta data.  This is reasonable.

**Comment by martinpitt** [comment]
Ach -- @mvollmer , can you please rebase this? There is no fedora-36@cockpit any more. I initially thought the bots would just have missed it, but we dropped it from our testmap earlier on.

**Review by martinpitt — APPROVED** [review]
Nevermind, I pushed a rebase. Assuming that this goes green, LGTM!

**Pull request merged**
