### PR TITLE
images: fix some SELinux contexts on RHEL & derived images

### PR DESCRIPTION
**Pull request by ptoscano**
This customization scripts creates/changes files, so make sure that
their SELinux contexts are actually the correct ones.

 * [x] image-refresh rhel-9-1

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3271-20220422-064545/

**Comment by cockpituous** [comment]
image-refresh rhel-9-1 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-1-20220422-070505

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3271-20220422-073030/

**Comment by martinpitt** [comment]
Thanks, without the `-F` it [looks much more reasonable now](https://logs.cockpit-project.org/logs/image-refresh-3271-20220422-073030/log):
```
+ restorecon -vR /etc/ /var/lib/insights/
Relabeled /etc/insights-client/.insights-core.etag from unconfined_u:object_r:insights_client_etc_t:s0 to unconfined_u:object_r:insights_client_etc_rw_t:s0
Relabeled /etc/insights-client/.insights-core-gpg-sig.etag from unconfined_u:object_r:insights_client_etc_t:s0 to unconfined_u:object_r:insights_client_etc_rw_t:s0
Relabeled /etc/insights-client/.cache.json.asc from unconfined_u:object_r:insights_client_etc_t:s0 to unconfined_u:object_r:insights_client_etc_rw_t:s0
Relabeled /etc/insights-client/.cache.json from unconfined_u:object_r:insights_client_etc_t:s0 to unconfined_u:object_r:insights_client_etc_rw_t:s0
```

**Comment by cockpituous** [comment]
image-refresh rhel-9-1 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-1-20220422-075656

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3271-20220422-075656/

**Comment by cockpituous** [comment]
image-refresh rhel-9-1 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-1-20220422-082121

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
