### PR TITLE
Debian image build script cleanups, install freeipa-client onto ubuntu-2004

### PR DESCRIPTION
**Pull request by martinpitt**
This will allow us to run the cockpit FreeIPA tests on ubuntu-2004.

Rebuilding debian-testing as well, to prove that the generic cleanup doesn't break anything.

 * [x] image-refresh ubuntu-2004
 * [x] image-refresh debian-testing
 * [x] Don't require docker.service in cockpit-podman tests: https://github.com/cockpit-project/cockpit-podman/pull/547
 * [x] Fix runc vs. crun confusion on debian: https://github.com/cockpit-project/cockpit-podman/pull/549

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-1262-20200927-075353/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2004 done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-2004-20200927-080808

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-1262-20200927-080909/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/bots/commits/image-refresh-debian-testing-20200927-082626

**Comment by martinpitt** [comment]
c-podman fix landed, retrying test. (it already succeeded on that PR)

**Review by marusak — APPROVED** [review]
Thanks!  Changes make sense and tests are happy.

**Comment by martinpitt** [comment]
I don't understand this [c-podman failure](https://logs.cockpit-project.org/logs/pull-1262-20200928-053822-2ed01ba4-debian-testing-cockpit-project-cockpit-podman/log.html) -- that's exactly what we fixed in https://github.com/cockpit-project/cockpit-podman/pull/547

**Comment by martinpitt** [comment]
Oh, I guess it's the `Error: default OCI runtime "runc" not found: invalid argument` -- the `docker.service: No such file or directory
` is just noise (and we  can remove it entirely once we land this image).

**Comment by martinpitt** [comment]
Sent a fix for debian-testing to https://github.com/cockpit-project/cockpit-podman/pull/549 . This happened because we dropped docker.io from the image, which pulled in runc.

**Pull request merged**
