### PR TITLE
image-download: fix handling of COCKPIT_IMAGE_UPLOAD_STORE

### LINKED ISSUE #6037: image-download: incorrect handling of COCKPIT_IMAGE_UPLOAD_STORES
```python
   stores += image_upload_store
```

that should be `.append()`

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
...and much more.

Oh.  Fixes #6037.

 - [x] Land after https://github.com/cockpit-project/cockpit-machines/pull/1502

### CODE REVIEW

**Comment by martinpitt** [comment]
This uses "too modern" type annotations which don't work on RHEL 8, and image-download is being used there. I get it to work with this diff:

```diff
diff --git a/image-download b/image-download
index 149c9346..46b9e1ec 100755
--- a/image-download
+++ b/image-download
@@ -68,7 +68,7 @@ def curl_cmd(args: Sequence[str]) -> Sequence[str]:
     return ['curl', '--connect-timeout', '10', '--fail', *args]
 
 
-def check_curl_args(args: Sequence[str]) -> tuple[str, float] | None:
+def check_curl_args(args: Sequence[str]) -> 'tuple[str, float] | None':
     head_args = ['--silent', '--head']  # only used for this check
 
     try:
@@ -80,7 +80,7 @@ def check_curl_args(args: Sequence[str]) -> tuple[str, float] | None:
         return None
 
 
-def find(name: str, stores: Sequence[str], latest: float, quiet: bool) -> tuple[list[str], str] | None:
+def find(name: str, stores: Sequence[str], latest: float, quiet: bool) -> 'tuple[list[str], str] | None':
     found = []
 
     for store in stores:
@@ -111,7 +111,7 @@ def find(name: str, stores: Sequence[str], latest: float, quiet: bool) -> tuple[
         return None
 
     # Find the most recent version of this file
-    def header_date(args: tuple[Sequence[str], tuple[str, float], str]) -> str | float:
+    def header_date(args: 'tuple[Sequence[str], tuple[str, float], str]') -> 'str | float':
         _, (output, duration), message = args
         try:
             reply_line, headers_alone = output.split('\n', 1)
diff --git a/lib/s3.py b/lib/s3.py
index 1768b7a8..2f5940a1 100644
--- a/lib/s3.py
+++ b/lib/s3.py
@@ -43,7 +43,7 @@ SHA256_NIL = hashlib.sha256(b'').hexdigest()
 logger = logging.getLogger('s3')
 
 
-def get_key(url: urllib.parse.ParseResult) -> tuple[str, str]:
+def get_key(url: urllib.parse.ParseResult) -> 'tuple[str, str]':
     s3_key_dir = xdg_config_home('cockpit-dev/s3-keys', envvar='COCKPIT_S3_KEY_DIR')
 
     if url.hostname is None:
@@ -75,7 +75,7 @@ def is_key_present(url: urllib.parse.ParseResult) -> bool:
 
 def sign_request(
     url: urllib.parse.ParseResult, method: str, headers: Mapping[str, str], checksum: str
-) -> dict[str, str]:
+) -> 'dict[str, str]':
     """Signs an AWS request using the AWS4-HMAC-SHA256 algorithm
 
     Returns a dictionary of extra headers which need to be sent along with the request.
diff --git a/lib/testmap.py b/lib/testmap.py
index 232dba97..94e523c7 100644
--- a/lib/testmap.py
+++ b/lib/testmap.py
@@ -278,7 +278,7 @@ def get_test_image(image: str) -> str:
     return image.replace("-distropkg", "")
 
 
-def split_context(context: str) -> tuple[str, int | None, str, str]:
+def split_context(context: str) -> 'tuple[str, int | None, str, str]':
     bots_pr = None
     repo_branch = ""
 
```

For the simple cases you can also use `Tuple`/`Dict` from `typing`, but I suppose just quoting them is simpler all around.

**Review by martinpitt — CHANGES_REQUESTED** [review]
Cheers! This looks good of course, but needs some "ancient Python" treatment. I'll trigger a cockpit-machines test to demonstrate.

**Comment by martinpitt** [comment]
> I'll trigger a cockpit-machines test to demonstrate.

Ah no, that won't work -- this only happens on Testing Farm. Perhaps we should add a little c8s workflow run.. (not necessarily in this PR)

**Comment by allisonkarlitskaya** [comment]
This is blocked until we get all testing farm runs moved over to using the tasks container as we did in https://github.com/cockpit-project/starter-kit/pull/812.

**Comment by martinpitt** [comment]
Note: this is only really blocked on cockpit-machines. The others should be fine. Adding https://github.com/cockpit-project/cockpit-machines/pull/1502 to todo list

**Review by martinpitt — APPROVED** [review]
Aside from the blocker, the code changes look great!

**Pull request merged**
