### PR TITLE
Fix openshift image refresh

### LINKED ISSUE #585: Image refresh for openshift
Image refresh for openshift
 * [ ] FAIL: image-refresh openshift

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh openshift

Fixes #585

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-546lp.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-605-20200304-085252/

**Comment by martinpitt** [comment]
I just realized that we can't run container/kubernetes test any more, as we can't build the package on fedora-31. That's why we disabled the test ages ago.

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/bots/commits/image-refresh-openshift-20200304-091010

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-605-20200304-091313/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/bots/commits/image-refresh-openshift-20200304-093838

**Pull request merged**
