### PR TITLE
images: Don't install systemd-timesyncd on Lunar Lobster

### PR DESCRIPTION
**Pull request by mvollmer**
The freeipa-client package has started conflicting with it:

    https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008195

 * [x] image-refresh ubuntu-stable
 * [x] https://github.com/cockpit-project/cockpit/pull/18736

### CODE REVIEW

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/ubuntu-stable-20230428-120909.log

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20230428-123321

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/ubuntu-stable-20230428-123333.log

**Comment by mvollmer** [comment]
We very likely need to adjust the chronyd/timesyncd test matrix in check-system-info, and maybe make a "timesyncd" packageset...

**Comment by martinpitt** [comment]
@mvollmer FYI the testSocket failure is known issue #4468

**Comment by mvollmer** [comment]
> We very likely need to adjust the chronyd/timesyncd test matrix in check-system-info, and maybe make a "timesyncd" packageset...

Alternatively, we could leave "freeipa-client" out of the images, and make a packageset for it. But I guess freeipa-client has a ton of dependencies... hmm.

**Comment by martinpitt** [comment]
@mvollmer As much as I hate running most tests with a non-default configuration, I agree that timesync as a package set works better than freeipa. That package conflict is just wildly annoying, and a bad hack around FreeIPA not getting along with timesyncd..

**Comment by martinpitt** [comment]
@mvollmer When you push again to add the image, remember to add the naughty for #4468 (see above)

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20230502-084826

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/ubuntu-stable-20230502-084848.log

**Comment by mvollmer** [comment]
> @mvollmer As much as I hate running most tests with a non-default configuration, I agree that timesync as a package set works better than freeipa. That package conflict is just wildly annoying, and a bad hack around FreeIPA not getting along with timesyncd..

I'll make a issue for us. Maybe we find the energy to get back to this.

**Comment by mvollmer** [comment]
> I'll make a issue for us. Maybe we find the energy to get back to this.

https://issues.redhat.com/browse/COCKPIT-992

**Pull request merged**
