### PR TITLE
Paint go-faster stripes onto Ubuntu images

### PR DESCRIPTION
**Pull request by martinpitt**
Reduce the boot time by 10s, image size by a third, and ensure that our images don't take too long to boot. The latter could affect all images, but I promise to investigate fallout. (In fact, you'll have a hard time from *stopping* me from doing that, I just get magically attracted to debugging such things :grin: )

[recent](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17598-20220727-083702-6ffb7f57-ubuntu-stable/log.html) [ubuntu](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17598-20220727-083702-6ffb7f57-ubuntu-2204/log.html) [runs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17595-20220727-080953-dc73f10c-ubuntu-2204/log.html) regularly take > 60 minutes, which breaks our SLO. The [first run here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3668-20220727-123919-839dd2ff-ubuntu-stable-cockpit-project-cockpit/log.html#90-2) only took 36 mins, even with 5 failure retries.

cockpit-machines also dropped from 15 mins to [11 mins](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3668-20220727-123916-839dd2ff-ubuntu-stable-cockpit-project-cockpit-machines/log.html).

 * [x] image-refresh debian-stable
 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-stable
 * [x] image-refresh ubuntu-2204

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-1.
Log: https://logs.cockpit-project.org/logs/image-refresh-3668-20220727-121717/

**Comment by martinpitt** [comment]
[recent](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17598-20220727-083702-6ffb7f57-ubuntu-stable/log.html) [ubuntu](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17598-20220727-083702-6ffb7f57-ubuntu-2204/log.html) [runs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17595-20220727-080953-dc73f10c-ubuntu-2204/log.html) regularly take > 60 minutes.

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20220727-123251

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20220727-125712

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3668-20220727-130000/

**Comment by martinpitt** [comment]
Ah, the `team` kernel support is also not in the virtual kernel image, but only the full one:
```
Jul 27 12:47:52 ubuntu NetworkManager[659]: <warn>  [1658926072.8887] platform-linux: do-add-link[tteam/team]: failure 95 (Operation not supported - Unknown device type)
Jul 27 12:47:52 ubuntu NetworkManager[659]: <error> [1658926072.8887] manager: (tteam) couldn't create the device: Failed to create team master interface 'tteam' for 'tteam': Operation not supported
```

[log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3668-20220727-123919-839dd2ff-ubuntu-stable-cockpit-project-cockpit/log.html#90-2)

I was first inclined to disable the tests on Ubuntu, but then again, as long as we offer this functionality we should test it. (I understand team is somewhat deprecated). So let's just extract the team modules the same way as I extract scsi_debug.

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20220727-132456

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3668-20220727-132727/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20220727-134030

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-4.
Log: https://logs.cockpit-project.org/logs/image-refresh-3668-20220727-134040/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-3668-20220727-134040/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3668-20220727-134040/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-3668-20220727-141313/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2204 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2204-20220727-143913

**Review by marusak — APPROVED** [review]
nice! Let's hope for green :crossed_fingers:

**Pull request merged**
