### PR TITLE
testmap: add Fedora-36 to subscription-manager

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Comment by jelly** [comment]
```
+ python3 ./setup.py install --prefix /usr --root /
running install
/usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running build
running build_py
running build_ext
running build_trans
running build_template
running install_lib
creating /usr/local/lib64/python3.10
creating /usr/local/lib64/python3.10/site-packages
creating /usr/local/lib64/python3.10/site-packages/cloud_what
copying build/lib.linux-x86_64-3.10/cloud_what/__init__.py -> /usr/local/lib64/python3.10/site-packages/cloud_what
copying build/lib.linux-x86_64-3.10/cloud_what/_base_provider.py -> /usr/local/lib64/python3.10/site-packages/cloud_what
copying build/lib.linux-x86_64-3.10/cloud_what/fact_collector.py -> /usr/local/lib64/python3.10/site-packages/cloud_what
````
The issue is that it's installed into /local. setting `--root` to /tmp makes it install to `/tmp/usr/local/lib64/python3.10/site-packages/subscription_manager-1.29.26-py3.10.egg-info`. So the problem is that `local` is coming from somewhere.



BTW, we could use --exec-prefix to get rid of the manual mv?

**Comment by jelly** [comment]
Conclusion https://github.com/pypa/distutils/commit/c8fcf4d2e3aaf543f065971dcf78451be35adcc4

**Comment by ptoscano** [comment]
Thanks @jelly for the report!

https://github.com/candlepin/subscription-manager/pull/2989 fixes the cockpit CI for sub-man on fedora-36.

**Comment by hroncok** [comment]
> Conclusion, broken by [pypa/distutils@c8fcf4d](https://github.com/pypa/distutils/commit/c8fcf4d2e3aaf543f065971dcf78451be35adcc4)

I strongly believe this is a wrong conclusion. This is far more likely caused by https://src.fedoraproject.org/rpms/python3.10/pull-request/63 -- see also https://bugzilla.redhat.com/show_bug.cgi?id=2026979

**Comment by ptoscano** [comment]
subscription-manager/main was fixed, can you please check this again?

Thanks in advance!

**Comment by ptoscano** [comment]
From a subscription-manager POV, :+1: - thanks!

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
