### PR TITLE
image-create: Allow slow fedora-rawhide boots

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh fedora-rawhide
 * [x] image-refresh fedora-36

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3789-20220829-114949/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3789-20220829-114949/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3789-20220829-115252/

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-20220829-121852

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3789-20220829-122626/

**Comment by mvollmer** [comment]
One rfresh of fedora-rawhide to prove that it can succeed, one refresh of fedora-36 to prove that it still works. We don't need to install either of them.

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20220829-125344

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3789-20220829-125353/

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20220829-131556

**Review by allisonkarlitskaya — APPROVED** [review]
Thanks for sorting this out!

**Pull request merged**
