### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by martinpitt** [comment]
[NTFS regression](https://logs.cockpit-project.org/logs/pull-2380-20210903-022942-5c7da963-fedora-testing-cockpit-project-cockpit/log.html#207-2) -- this needs to be tracked down (see updated packages in image build log), blocked in bodhi (so that the regression does not enter stable Fedora), and bugzilla'ed with a reproducer. @skobyda , do you feel comfortable about this, or want help?

**Comment by skobyda** [comment]
Reported bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2001713

**Comment by martinpitt** [comment]
I :-1: 'ed the corresponding bodhi update: https://bodhi.fedoraproject.org/updates/FEDORA-2021-38d1b07839

This needs to happen in a timely manner, otherwise these go into released updates, and catching the regression was in vain.

**Comment by martinpitt** [comment]
@skobyda: See https://bugzilla.redhat.com/show_bug.cgi?id=2001713#c5 -- so we'll need to add ntfs-3g as an explicit package in fedora.setup. Want to do that, or want me to?

**Comment by skobyda** [comment]
* [ ] image-refresh fedora-35

**Comment by skobyda** [comment]
* [ ] image-refresh fedora-testing

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-2380-20210907-145959/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20210907-152020

**Comment by martinpitt** [comment]
I pushed the newly built image here.

**Comment by martinpitt** [comment]
Nope! Didn't work, still the same error. So it seems we need to reopen the bug and re- :-1: the bodhi update.

**Comment by martinpitt** [comment]
I tested this again here: https://bugzilla.redhat.com/show_bug.cgi?id=2001713#c8

So the root cause is https://bugzilla.redhat.com/show_bug.cgi?id=2001755

This now made it to stable even, as the update got fast-paced/forced through bodhi despite these regression reports :cry: So the only thing we can do now is to naughty it (also for F34/35)

**Comment by skobyda** [comment]
Added a naught: https://github.com/cockpit-project/bots/pull/2393

**Comment by martinpitt** [comment]
Thanks @skobyda! Please add that commit into this PR instead.

**Comment by martinpitt** [comment]
Thanks @skobyda ! Triggering tests.

**Pull request merged**
