### PR TITLE
images: Bootstrap rhel-8-3 from latest-RHEL-8.3.1

### PR DESCRIPTION
**Pull request by mvollmer**
The latest-RHEL-8.3 locations seems to be broken right now for use
with virt-install, as it is missing the bootloader images.  The
latest-RHEL-8.3.1 location seems to work.

 * [x] image-refresh rhel-8-3

### CODE REVIEW

**Comment by mvollmer** [comment]
One would think that latest-RHEL-8.3 would be identical to
latest-RHEL-8.3.1 right now, but that would apparently make too much
sense for the Enterprise.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-1425-20201201-104141/

**Comment by martinpitt** [comment]
Even if that builds, it'll be incomplete and create some kind of frankendistro -- mixing 8.3.1 and 8.3.0. It still needs to [bump the installed repos to 8.3.1](https://github.com/cockpit-project/bots/pull/1339/files#diff-df41639d84c8102e8dc6e9cca7c2770030adbb54f5f1a4b3badb3235b3655d33) like in PR #1339

**Comment by cockpituous** [comment]
image-refresh rhel-8-3 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-3-20201201-110303

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-1425-20201201-111919/

**Comment by cockpituous** [comment]
image-refresh rhel-8-3 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-3-20201201-114040

**Comment by mvollmer** [comment]
> Even if that builds, it'll be incomplete and create some kind of frankendistro -- mixing 8.3.1 and 8.3.0. It still needs to [bump the installed repos to 8.3.1](https://github.com/cockpit-project/bots/pull/1339/files#diff-df41639d84c8102e8dc6e9cca7c2770030adbb54f5f1a4b3badb3235b3655d33) like in PR #1339

Yes, done.

I don't use `updates` since we didn't use it before.

**Comment by mvollmer** [comment]
cockpit-podman/rhel8 still pulls from dockerhub.io.  https://github.com/cockpit-project/cockpit-podman/pull/613 tries to move that to quay.io

**Comment by mvollmer** [comment]
@jkozol, @henrywang, the `rhel-8` branch of osbuild/cockpit-composer doesn't build any more.  It fails with many errors like this:

```
ERROR in ./components/Modal/CreateBlueprint.js
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

/home/mvo/work/cockpit-composer/components/Modal/CreateBlueprint.js
  110:3  error  dismissErrors should be placed after handleErrorNameInvalid  react/sort-comp
```
Can you advise?

**Comment by marusak** [comment]
My guess is that https://github.com/osbuild/cockpit-composer/commit/7fc34e19ddff889f68d33f19481ecd15ed36dbb1 needs to be backported :)

**Comment by marusak** [comment]
Sent https://github.com/osbuild/cockpit-composer/pull/1181

**Comment by mvollmer** [comment]
> Sent [osbuild/cockpit-composer#1181](https://github.com/osbuild/cockpit-composer/pull/1181)

Thanks!

**Comment by mvollmer** [comment]
check-kdump fails with cockpit/rhel-8

**Comment by henrywang** [comment]
> Sent [osbuild/cockpit-composer#1181](https://github.com/osbuild/cockpit-composer/pull/1181)

Merged. Thanks.

**Comment by mvollmer** [comment]
> One would think that latest-RHEL-8.3 would be identical to
> latest-RHEL-8.3.1 right now, but that would apparently make too much
> sense for the Enterprise.

The latest-RHEL-8.3 symlink has been corrected, but the mirrors haven't caught up yet. I am inclined to just keep using latest-RHEL-8.3.1 anyway here and immediately open a PR that moves us back.

**Review by martinpitt — APPROVED** [review]
Thanks, great work! Ergh @ the explicit 8.3.1 symlink, as this is prone to getting stale. But as you said, let's move it back to latest ASAP.

**Pull request merged**
