### PR TITLE
Image refresh for rhel-8-2

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-2
 * [x] image-refresh rhel-8-2

### CODE REVIEW

**Comment by marusak** [comment]
@atodorov https://209.132.184.41:8493/logs/pull-499-20200206-105353-b6c8cd4c-rhel-8-2-weldr-lorax-rhel8-branch/log.html failed 4 times in a row with the same error. Any idea about this?

**Comment by atodorov** [comment]
@marusak I see subscription-manager failed. 

@jikortus, @jrusz ^^^ do you know what subscription credentials are we using for lorax-composer testing? Maybe they have expired or are failing because we're now using a newer image which is newer than what is available on CDN.

**Comment by jikortus** [comment]
@atodorov I'm not really sure what credentials we are using. I'll ask @jrusz tomorrow (he's not available today) as he's the author of the CDN registration code and he should definitely know that.

**Comment by jrusz** [comment]
Should be ok now. What happened is rhel8 switched form being beta to being high touch beta and the subscription we use didn't have the correct SKU.

**Pull request merged**
