### PR TITLE
Image refresh for debian-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-stable
 * [x] image-refresh debian-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20240215-102400

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-stable-20240215-102424.log

**Comment by martinpitt** [comment]
Uh, [metrics trouble](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5910-20240215-102513-e1b13488-debian-stable-other-cockpit-project-cockpit/log.html). Re-running to compare, but this looks real.

**Comment by martinpitt** [comment]
Yes, it's broken.

**Comment by jelly** [comment]
The test fails waiting on PCP to be "ready" [here in the test](https://github.com/cockpit-project/cockpit/blob/main/test/verify/check-metrics#L860). However can't reproduce this..

**Review by martinpitt — APPROVED** [review]
Thanks @jelly for fixing!

**Pull request merged**
