### PR TITLE
Image refresh for rhel-9-2

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-2
 * [x] image-refresh rhel-9-2
 * [x] #6585

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-9-2 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-2-20240627-225718

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-2-36bc0a62-20240627-223721/log.html

**Comment by martinpitt** [comment]
> Problem: package cockpit-ws-319.dev29+gd5688ab59-1.el9.x86_64 from @commandline requires (selinux-policy >= 38.1.11-2.el9_2.6 if selinux-policy-targeted), but none of the providers can be installed

So the refresh didn't help and this doesn't automagically fix itself :cry:

**Comment by martinpitt** [comment]
rhel4edge is history, rebased.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
