### PR TITLE
Image refresh for fedora-40

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-40
 * [x] image-refresh fedora-40
 * [ ] needs osbuild-composer 118: https://bodhi.fedoraproject.org/updates/FEDORA-2024-ba75e9ed45

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-40-ec3e0776-20240825-223855/log.html

**Comment by martinpitt** [comment]
@croissanne : This F40 update causes `composer-cli blueprints depsolve httpd-server` to hang and time out. Can you please have a look? [log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6785-07cbbceb-20240826-014035-fedora-40-osbuild-cockpit-composer/log.html). Same failures with [firefox](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6785-07cbbceb-20240826-014042-fedora-40-firefox-osbuild-cockpit-composer/log.html#3-2), and I already  retried this once, so it's robust.

Possibly dnf (4.21.0-1.fc40 -> 4.21.1-1.fc40) or createrepo_c (1.1.3-1.fc40 -> 1.1.4-1.fc40) ?

**Comment by croissanne** [comment]
@martinpitt this is fixed by the latest version of composer 118, which just now got pushed to stable. Could we redo the refresh in a bit?

**Comment by martinpitt** [comment]
@croissanne Sure, we can wait a bit, but what for exactly? When you say "composer 118" you don't mean https://bodhi.fedoraproject.org/updates/?packages=composer or https://bodhi.fedoraproject.org/updates/?packages=cockpit-composer. Thanks!

**Comment by croissanne** [comment]
> @croissanne Sure, we can wait a bit, but what for exactly? When you say "composer 118" you don't mean https://bodhi.fedoraproject.org/updates/?packages=composer or https://bodhi.fedoraproject.org/updates/?packages=cockpit-composer. Thanks!

It's https://packages.fedoraproject.org/pkgs/osbuild-composer/osbuild-composer/, 
image

I'm also trying to do https://github.com/osbuild/cockpit-composer/pull/2050 to see if we can unblock it earlier for a bit and then revert that soon. I'm not quite sure how long it takes from being marked stable -> actually in repositories.

**Comment by martinpitt** [comment]
@croissanne thanks! added as blocker to description. That's fine, we can wait for two days or so.

**Comment by martinpitt** [comment]
118 is visible now in dnf, so let's do a new refresh.

**Pull request closed without merging**
