### PR TITLE
images: Include "clevis" package set in Debian and Ubuntu images

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh debian-testing
 * [x] image-refresh debian-stable
 * [x] image-refresh ubuntu-stable
 * [x] image-refresh ubuntu-2204

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3997-20221025-132727/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20221025-135338

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3997-20221025-135353/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20221025-140809

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-rz6p7.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3997-20221025-140808/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20221025-142619

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-rz6p7.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3997-20221025-142626/

**Review by jelly — APPROVED** [review]

**Pull request merged**
