### PR TITLE
Image refresh for rhel-8-8

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-8
 * [x] image-refresh rhel-8-8
 * https://github.com/cockpit-project/cockpit/pull/18108
 * #4224

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-8-20221216-225656.log

**Comment by martinpitt** [comment]
[several failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4178-20221216-225731-5172de32-rhel-8-8-cockpit-project-cockpit/log.html), looks like VDO and setroubleshoot may be broken. Let's do one retry for comparing.

**Comment by jelly** [comment]
> [several failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4178-20221216-225731-5172de32-rhel-8-8-cockpit-project-cockpit/log.html), looks like VDO and setroubleshoot may be broken. Let's do one retry for comparing.

I have seen [setroubleshoot flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18038-20221216-160547-77ff0d6c-centos-8-stream/log.html#95), this seems to be the different:

```
> error: TextArea: TextArea requires either an id or aria-label to be specified
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-selinux", line 251, in testTroubleshootAlerts
    ansible_m.execute("ansible -m include_role -a name=selinux localhost")
```

**Comment by martinpitt** [comment]
I'm taking a look, to help out with post-holiday piloting.

The VDO lockup is totally straightforward:
```
vgcreate vdo_vgroup /dev/sda
lvcreate --type vdo --size 6g --virtualsize 10g --name vdo1 --yes vdo_vgroup
```

immediately hangs, and eventually crashes the kernel:
```
[   84.293360] uds: modprobe: loaded version 8.0.6.2
[   84.314278] kvdo: modprobe: loaded version 6.2.8.4
[  172.464685] kvdo0:lvcreate: underlying device, REQ_FLUSH: supported, REQ_FUA: not supported
[  172.465525] kvdo0:lvcreate: Using write policy async automatically.
[  172.466142] kvdo0:lvcreate: loading device 'vdo_vgroup-vpool0-vpool'
[  172.466813] kvdo0:lvcreate: zones: 1 logical, 1 physical, 1 hash; base threads: 5
[  200.033002] watchdog: BUG: soft lockup - CPU#0 stuck for 23s! [kvdo0:journalQ:4326]
[  200.033710] Modules linked in: kvdo(O) uds(O) dm_bufio sd_mod t10_pi xt_CHECKSUM ipt_MASQUERADE xt_conntrack ipt_REJECT nft_compat nf_nat_tftp nft_objref nf_conntrack_tftp nft_counter bridge stp llc nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct nf_tables_set nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip_set nf_tables nfnetlink vfat fat intel_rapl_msr intel_rapl_common intel_pmc_core_pltdrv intel_pmc_core kvm_intel kvm cirrus drm_shmem_helper drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops drm irqbypass rapl joydev pcspkr virtio_balloon i2c_piix4 xfs libcrc32c dm_multipath sr_mod cdrom sg ata_generic crct10dif_pclmul ata_piix crc32_pclmul crc32c_intel libata virtio_net ghash_clmulni_intel serio_raw net_failover failover virtio_blk virtio_scsi sunrpc dm_mirror dm_region_hash dm_log dm_mod be2iscsi bnx2i cnic uio cxgb4i cxgb4 tls libcxgbi libcxgb qla4xxx iscsi_boot_sysfs iscsi_tcp
[  200.033776]  libiscsi_tcp libiscsi fuse scsi_transport_iscsi
[  200.042544] CPU: 0 PID: 4326 Comm: kvdo0:journalQ Kdump: loaded Tainted: G           O     --------- -  - 4.18.0-445.el8.x86_64 #1
[  200.043625] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.16.0-2.fc37 04/01/2014
[  200.044421] RIP: 0010:native_queued_spin_lock_slowpath+0x5f/0x1c0
[  200.045051] Code: 71 3e 0f ba 2f 08 0f 92 c0 0f b6 c0 c1 e0 08 89 c2 8b 07 30 e4 09 d0 a9 00 01 ff ff 75 4b 85 c0 74 0e 8b 07 84 c0 74 08 f3 90 <8b> 07 84 c0 75 f8 b8 01 00 00 00 66 89 07 e9 ee 95 aa 00 8b 37 81
[  200.046903] RSP: 0018:ffffbb660129fe68 EFLAGS: 00000202 ORIG_RAX: ffffffffffffff13
[  200.047719] RAX: 0000000000000101 RBX: 0000000000003ea0 RCX: 0000000000000000
[  200.048479] RDX: 0000000000000000 RSI: 0000000000000000 RDI: ffffffffc0e10038
[  200.049190] RBP: ffff995e030ff900 R08: ffff995e47c2b978 R09: 000000000000029f
[  200.049863] R10: 00000000000000cb R11: 000000000000028c R12: ffff995e030ff800
[  200.050555] R13: ffffbb6601227888 R14: ffffffffc0dc48f0 R15: ffff995e030ff800
[  200.051248] FS:  0000000000000000(0000) GS:ffff995e47c00000(0000) knlGS:0000000000000000
[  200.052067] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  200.052613] CR2: 00007f580af80006 CR3: 0000000028e10004 CR4: 0000000000370ef0
[  200.053242] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  200.054145] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  200.055003] Call Trace:
[  200.055347]  _raw_spin_lock+0x1e/0x30
[  200.055808]  initializeWorkQueueStackHandle+0x30/0x70 [kvdo]
[  200.056468]  workQueueRunner+0x4c/0x610 [kvdo]
[  200.056999]  ? __schedule+0x2d9/0x870
[  200.057441]  ? dumpSimpleWorkQueue+0x120/0x120 [kvdo]
[  200.057998]  kthread+0x134/0x150
[  200.058398]  ? set_kthread_struct+0x50/0x50
[  200.058872]  ret_from_fork+0x1f/0x40
[  228.033002] watchdog: BUG: soft lockup - CPU#0 stuck for 22s! [kvdo0:journalQ:4326]
```

This is most probably a regression in kernel (4.18.0-441.el8 -> 4.18.0-445.el8). `dnf update kernel` has a new 4.18.0-447.el8, but that still has the same problem. So refreshing the image again won't help for this issue. Someone else already reported this at https://bugzilla.redhat.com/show_bug.cgi?id=2156147 , I added some information. I'll add a naughty.

**Comment by martinpitt** [comment]
The [selinux test](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4178-20221219-053317-5172de32-rhel-8-8-cockpit-project-cockpit/log.html#133-2)  fails differently for me locally. It gets past the point where it times out on running ansible (which was probably just a flake due to a busy CI machine), and runs into an unexpected SELinux option:

```
Traceback (most recent call last):
  File "/var/home/martin/upstream/cockpit/main/test/verify/check-selinux", line 279, in testTroubleshootAlerts
    b.wait_text("ul[aria-label='System modifications']", "No system modifications")
  File "/var/home/martin/upstream/cockpit/main/test/common/testlib.py", line 655, in wait_text
    self.wait_js_cond("ph_text_is(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/var/home/martin/upstream/cockpit/main/test/common/testlib.py", line 582, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/var/home/martin/upstream/cockpit/main/test/common/testlib.py", line 288, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_text_is("ul[aria-label='System modifications']","No system modifications")): Uncaught (in promise) Error: actual text: permissive -a insights_client_t
```

**Comment by martinpitt** [comment]
So indeed it seems that insights-client modifies the local SELinux policy, which is awkward -- this essentially means "anything goes" in insights-client, and also that there is an unclean SELinux policy out of the box. The same happens on RHEL 9.2 in #4226.  But alas, we don't control that, so let's adjust our tests.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
