### PR TITLE
Image refresh for fedora-32

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-32
 * [x] image-refresh fedora-32

### CODE REVIEW

**Comment by martinpitt** [comment]
@skobyda: Same -certificates problems as in the fedora-33 refresh in #1628.

**Comment by martinpitt** [comment]
https://github.com/skobyda/cockpit-certificates/pull/30 landed, retrying.

**Comment by martinpitt** [comment]
Bah, too old, [needs rebasing](https://logs.cockpit-project.org/logs/pull-1627-20210209-172201-d96cf34f-fedora-32-selenium-firefox-cockpit-project-cockpit-rhel-7.9/log.html). Pushed.

**Comment by martinpitt** [comment]
Same [c-certificates failure](https://logs.cockpit-project.org/logs/pull-1627-20210209-173645-23f94e1e-fedora-32-skobyda-cockpit-certificates/log.html) as on fedora-33 refresh. I don't think it's related to locales. @skobyda , any idea?

**Comment by marusak** [comment]
certs are being fixed in https://github.com/skobyda/cockpit-certificates/pull/32

**Comment by martinpitt** [comment]
@atodorov : FYI, [osbuild-composer@lorax](https://logs.cockpit-project.org/logs/pull-1627-20210210-054431-23f94e1e-fedora-32-osbuild-composer-weldr-lorax/log.html) fails on some beakerlib regression:

    /usr/share/beakerlib/profiling.sh: line 63: BEAKERLIB_PROFILING: unbound variable

This gets pulled in from the internet, it's not part of the fedora-32 image.

**Review by martinpitt — APPROVED** [review]

**Comment by atodorov** [comment]
> This gets pulled in from the internet, it's not part of the fedora-32 image.

We use beakerlib for most of the tests. The issue if probably because we use stricter bash flags to warn against undefined variables, etc.

From what I can see this happens after the tests are executed and we try parsing the results. I need to dig more into it.

**Comment by atodorov** [comment]
@martinpitt it looks like this is an upstream issue, see https://github.com/beakerlib/beakerlib/pull/91

**Comment by martinpitt** [comment]
Thanks @atodorov !

**Pull request merged**
