### PR TITLE
Fix centos-8-stream image refresh

### PR DESCRIPTION
**Pull request by skobyda**
During image-refresh #4526 , our bootstrap script was trying to download CentOS-Stream-GenericCloud-8-20230308.3.x86_64.qcow2.SHA256SUM Fix the regex so it only uses the actual qcow2 image.

Image refresh for centos-8-stream
 * [X] ~https://bugzilla.redhat.com/show_bug.cgi?id=2174645 fix is in C8S~ -- takes absurdly long, let's workaround
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/centos-8-stream-20230316-234646.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/centos-8-stream-20230316-235555.log

**Comment by skobyda** [comment]
While this fixes the incorrect regex, and bootstrap manages to download correct image, there is another issue.

Centos-8-stream now also has the `[FAILED] Failed to start Flush Journal to Persistent Storage.` issue.

I tried to run
`qemu-system-x86_64 -enable-kvm -nographic -m 2048 -device virtio-rng-pci -drive file=tmp/CentOS-Stream-GenericCloud-8-20230308.3.x86_64.qcow2,if=virtio -snapshot -cdrom machine/cloud-init.iso`

And gotten the same issue. So adding a blocked until new centos-8-stream is out.
Screenshot from 2023-03-17 01-13-29

**Comment by martinpitt** [comment]
Right, thanks. https://bugzilla.redhat.com/show_bug.cgi?id=2174645 is ON_QA now, so should hopefully be imported into C8S soon. Adding this to the description.

**Comment by martinpitt** [comment]
This is obnoxious.. I asked on rhel-devel@ where I can file a ticket for getting the image refreshed.

**Comment by martinpitt** [comment]
Yay, prodding helped -- there's now a 20230404 image. Retrying!

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/centos-8-stream-20230405-073131.log

**Comment by martinpitt** [comment]
What, that too? Argh..

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/centos-8-stream-20230411-040505.log

**Comment by martinpitt** [comment]
That bug hasn't gotten fixed at all:

    [  *** ] A start job is running for Flush Jo…ersistent Storage (16s / 1min 30s)

and after that, it's still our old friend 

    [*     ] A start job is running for Network … Wait Online (2min 15s / no limit)

And indeed the image still has systemd-239-73.el8.x86_64 , as https://bugzilla.redhat.com/show_bug.cgi?id=2174645#c25 has shown. :exploding_head:

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20230413-101227

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/centos-8-stream-20230413-101212.log

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20230413-101324

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/centos-8-stream-20230413-101313.log

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
