### PR TITLE
fedora.setup: fix dnf download compatibility issues

### LINKED ISSUE #4932: Image refresh for fedora-rawhide
Image refresh for fedora-rawhide
 * [ ] FAIL: image-refresh fedora-rawhide

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
dnf5 renamed `dnf download --downloadir` to `--distdir`.  Avoid the issue by just using `cd` in a subshell.

Fixes #4932

 * [x] image-refresh fedora-rawhide
 * [x] image-refresh fedora-38

### CODE REVIEW

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-38-20230627-075858.log

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-20230627-082747

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-20230627-082727.log

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-20230627-085821

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-20230627-085858.log

**Comment by cockpituous** [comment]
image-refresh fedora-38 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-38-20230627-092646

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-38-20230627-092626.log

**Comment by martinpitt** [comment]
F-38 collision with #4933, please drop the image here again. It was proven that it builds, that's enough.

**Review by martinpitt — APPROVED** [review]
Thank you!

**Pull request merged**
