### PR TITLE
Refresh ubuntu-stable

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh ubuntu-stable
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-5.
Log: https://logs.cockpit-project.org/logs/image-refresh-3842-20220907-155656/

**Comment by mvollmer** [comment]
This tries to fix the same problem as #3795

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20220907-160906

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3842-20220907-161212/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20220907-163546

**Review by martinpitt — COMMENTED** [review]
Okay.. That feels more like a workaround than a legitimate thing, but if it's that easy it doesn't hurt a lot. Thanks for figuring this out!

However, you didn't actually run the test against the refreshed images.. You need to push them here and re-run.

**Comment by mvollmer** [comment]
> However, you didn't actually run the test against the refreshed images.. You need to push them here and re-run.

Ouch.

**Review by martinpitt — APPROVED** [review]
Assuming green, thanks! Good point for not actually including d-testing, it collides with #3835

**Comment by mvollmer** [comment]
Let's try to actually update ubuntu-stable here.

**Review by martinpitt — DISMISSED** [review]
Thank you!

**Comment by martinpitt** [comment]
Oh wait, I just saw green, but this didn't run tests yet.

**Comment by martinpitt** [comment]
Meh, [still one regression](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3842-20220908-090737-3f4856df-ubuntu-stable-cockpit-project-cockpit/log.html#165). This smells like a pitti thing

**Comment by mvollmer** [comment]
Alright, turns out Ubuntu didn't actually rename `ssh.service` to `sshd.service`, we were just missing the alis symlink that is normally created by `systemctl enable ssh`.  For some reason, `ssh.service` is not enabled anymore in the new ubuntu-stable image. Let's enable it explicitly.

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-3842-20220909-110404/

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-2.
Log: https://logs.cockpit-project.org/logs/image-refresh-3842-20220909-112222/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-3842-20220909-112222/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20220909-114424

**Comment by martinpitt** [comment]
Triggering ubuntu-stable tests here to get some feedback.

**Review by martinpitt — APPROVED** [review]
Tests get fixed in https://github.com/cockpit-project/cockpit/pull/17720 where the tests run against this image. Pre-approving, assuming green. Thanks for solving this puzzle! :man_pilot:

**Pull request merged**
