### PR TITLE
Image refresh for rhel-7-7

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-7-7
 * [x] image-refresh rhel-7-7
 * [x] Fix naughty handling: https://github.com/cockpit-project/cockpit/pull/13424

### CODE REVIEW

**Comment by marusak** [comment]
`testlib.Error: type=1400 audit(1579255100.113:5): avc:  denied  { sendto } for  pid=767 comm="chronyd" path="/host/run/chrony/chronyc.3234.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
` we have it in 'rhel-atomic' (issue #71), but needs to be added into rhel-7 as well. I'll send fix here.

**Comment by martinpitt** [comment]
The naughty also needs to be added to [rhel-atomic](https://209.132.184.41:8493/logs/pull-422-20200117-133636-629966a0-cockpit-project-cockpit-rhel-7.8-rhel-atomic/log.html#93-2).

**Comment by martinpitt** [comment]
Oh wait, it already *was* on rhel-atomic. Piping the test log through `./tests-policy rhel-atomic` works fine. Didn't we already have this problem a few weeks ago? I think that was an unsolved mystery. Trying again to see if it was just temporarily not able to talk to the flake predictor.

**Comment by marusak** [comment]
> Didn't we already have this problem a few weeks ago? I think that was an unsolved mystery. Trying again to see if it was just temporarily not able to talk to the flake predictor.

We did and the problem was that we were not checking naughty on the last retry. Which was fixed, buuut this is happening in a stable branch, so commit from #13345 needs to be backported into stable branches. (and then we need to remove this commit I added here which was absolute thinko)

**Comment by martinpitt** [comment]
@marusak : Oh, *slap*, of course! Sent https://github.com/cockpit-project/cockpit/pull/13424

**Comment by martinpitt** [comment]
@marusak: I dropped your commit again and rebased to master.

**Comment by martinpitt** [comment]
Still [rhel-atomic failure](https://209.132.184.41:8493/logs/pull-422-20200121-083535-346a704d-cockpit-project-cockpit-rhel-7.8-rhel-atomic/log.html#135-2), retrying.

**Pull request merged**
