### PR TITLE
images: add rawhide image for testing

### PR DESCRIPTION
**Pull request by jelly**
I had a script in my ~ to obtain the latest rawhide image and run it
with with cloud-init so I can easily ssh into it for testing. It feels
like it makes sense to allow anyone to easily spin up a rawhide image
with `./image-create fedora-rawhide`.

 * [x] image-refresh fedora-rawhide

### CODE REVIEW

**Review by martinpitt — CHANGES_REQUESTED** [review]
Err, wait, doesn't this at least need a fedora-rawhide.setup → fedora.setup symlink?

**Comment by jelly** [comment]
> Err, wait, doesn't this at least need a fedora-rawhide.setup → fedora.setup symlink?

Oh, we can. My intention was to have it available for manual testing not an "active" image which get's refreshed. We could do that and just add it to starterkit.

**Comment by martinpitt** [comment]
I see -- so your *intention* was that this image-create was more or less a pristine rawhide image, without any cockpit setup? Isn't that more or less the same as

    tmt run --until provision provision --how virtual --image fedora-rawhide

or just [booting the current cloud image in qemu](https://piware.de/gitweb/?p=bin.git;a=blob;f=cloud-rawhide)?

Like this it just feels a little odd: It's *almost* a pristine image, but uses our infra (so using it in bugzilla reproducers always has that "it's your bug!" smell), but we can't run any test against it as it's missing our common setup.

**Comment by jelly** [comment]
> I see -- so your _intention_ was that this image-create was more or less a pristine rawhide image, without any cockpit setup? Isn't that more or less the same as
> 
> ```
> tmt run --until provision provision --how virtual --image fedora-rawhide
> ```

I still have to debug that on my system as it does not run out of the box on my Arch Linux host with a fedora toolbox.
 
> or just [booting the current cloud image in qemu](https://piware.de/gitweb/?p=bin.git;a=blob;f=cloud-rawhide)?

Yup, that's basically the script I have somewhere too :)

> Like this it just feels a little odd: It's _almost_ a pristine image, but uses our infra (so using it in bugzilla reproducers always has that "it's your bug!" smell), but we can't run any test against it as it's missing our common setup.

Ok, let's make it build cockpit then :)

**Review by martinpitt — DISMISSED** [review]
LGTM, assuming you tested this. Thanks!

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3324-20220505-092929/

**Comment by allisonkarlitskaya** [comment]
> image-refresh in progress on 3-ci-srv-02. Log: https://logs.cockpit-project.org/logs/image-refresh-3324-20220505-092929/

This ought to be fun.  I wonder how it works to "refresh" something that doesn't exist yet :)

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-20220505-095656

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3324-20220505-095757/

**Comment by allisonkarlitskaya** [comment]
Okay.  So we can't update `lib/` without proposing this from `origin`, and meanwhile the bots aren't gonna run the requested test because it's not in the testmap.

I'll try the test locally and push an origin branch if it works.

**Comment by allisonkarlitskaya** [comment]
```
ok 1 /var/home/lis/src/starter-kit/main/test/check-application TestApplication.testBasic [ND@0]

# TESTS PASSED [41s on toolbox, 1 serial tests: 0: 40s]
```

**Comment by allisonkarlitskaya** [comment]
I'm not sure why the bot decided to run twice...

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-20220505-101818

**Review by allisonkarlitskaya — APPROVED** [review]
Let's merge this much, and deal with the rest from #3333.

**Pull request merged**
