### PR TITLE
testmap: Enable rhel-9-4 for cockpit-podman

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by martinpitt** [comment]
@cockpit-project/committers : Do you get this GitHub notification? Please tell me here or on Matrix.

**Comment by jelly** [comment]
> @cockpit-project/committers : Do you get this GitHub notification? Please tell me here or on Matrix.

Yes

https://github.com/orgs/cockpit-project/teams/committers : Do you get this GitHub notification? Please tell me here or on Matrix.

**Review by jelly — APPROVED** [review]

**Comment by martinpitt** [comment]
@jelly: Presumably you got the notification for this PR as you are generally subscribed to the bots project, no? So in a sense this was a bad test, I should have tried that on a podman PR.

**Comment by martinpitt** [comment]
Ah, but:

> You are receiving this because you are on a team that was mentioned.

Nice!

**Pull request merged**
