### PR TITLE
Image refresh for rhel-8-6

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-6
 * [x] image-refresh rhel-8-6

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-6-20230423-231919.log

**Comment by martinpitt** [comment]
@ptoscano : Does this failure ring a bell? There are *zero* changed/added/removed packages on that image.

**Comment by ptoscano** [comment]
```
Apr 24 01:02:22 rhel-8-6-127-0-0-2-2201 insights-client[23324]: No GPG-verified eggs can be found
Apr 24 01:02:22 rhel-8-6-127-0-0-2-2201 systemd[1]: insights-client-results.service: Main process exited, code=exited, status=1/FAILURE
Apr 24 01:02:22 rhel-8-6-127-0-0-2-2201 systemd[1]: insights-client-results.service: Failed with result 'exit-code'.
Apr 24 01:02:22 rhel-8-6-127-0-0-2-2201 systemd[1]: Failed to start Check for insights from Red Hat Cloud Services.
Apr 24 01:02:22 rhel-8-6-127-0-0-2-2201 systemd[1]: Starting Insights Client...
```
and
```
Apr 24 01:02:23 rhel-8-6-127-0-0-2-2201 cockpit-ws[23367]: Error importing insights.client for pre_update as /var/lib/insights/newest.egg: No module named 'insights'
```
IMHO show that something is not right with the egg inside the image. I cannot tell why only by looking at logs, this needs to be investigated.

**Comment by martinpitt** [comment]
Image build log says
```
Core: 3.0.246-1
+ insights-client --status
Unable to fetch egg url. Defaulting to /release
Please ensure that the system is registered with RHSM for CERT auth, or that correct credentials are set in /etc/insights-client/insights-client.conf for BASIC auth.
System is NOT registered locally via .registered file.
Insights API could not be reached to confirm registration status.
```

Let's just try a fresh build then as a first step.

**Comment by martinpitt** [comment]
> Let's just try a fresh build then as a first step.

→ #4690

**Pull request closed without merging**
