### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by jelly** [comment]
Seems the stratisd 3.0.3 upgrade broke testEncrypted locally I get:

```
Danger alert:TypeError: client.stratis_pools[path_a].Name is undefined
```

**Comment by mvollmer** [comment]
Stratisd sends a wrong properties changed signal.  It wants to set the properties for  the Manager at `/org/storage/stratis3` but uses the wrong interface `org.storage.stratis3.pool.r0`.

From that point on, Cockpit treats `/org/storage/stratis3` as a pool, but that object doesn't have any of the expected properties, like `Name`.

Furthermore, in the specific test run, the wrong properties changed signal is the first time `org.storage.pool.r0` is mentioned (because there aren't any pools when Cockpit starts), and Cockpit will introspect `/org/storage/stratis3` to learn about the `org.storage.stratis3.pool.r0` interface. The introspect data returned for `/org/storage/stratis3` is correct and doesn't contain anything about `org.storage.stratis3.pool.r0`. Thus, Cockpit thinks from that point on that a pool doesn't have any properties or methods.  Cockpit-bridge could maybe be noisy about this unexpected situation (introspection data and properties changed signals not agreeing with each other).

I file a bug with stratisd, and we can have a naugthty pattern for this.

Here is the signal from `busctl monitor`:

```
‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=11  Timestamp="Thu 2022-02-10 13:32:50.831372 UTC"
  Sender=:1.0  Path=/org/storage/stratis3  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.0
  MESSAGE "sa{sv}as" {
          STRING "org.storage.stratis3.pool.r0";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "LockedPools";
                          VARIANT "a{sa{sv}}" {
                                  ARRAY "{sa{sv}}" {
                                          DICT_ENTRY "sa{sv}" {
                                                  STRING "e11eb60baf4348f48bba1e507faf3363";
                                                  ARRAY "{sv}" {
                                                          DICT_ENTRY "sv" {
                                                                  STRING "clevis_info";
                                                                  VARIANT "(bv)" {
                                                                          STRUCT "bv" {
                                                                                  BOOLEAN true;
                                                                                  VARIANT "(b(ss))" {
                                                                                          STRUCT "b(ss)" {
                                                                                                  BOOLEAN false;
                                                                                                  STRUCT "ss" {
                                                                                                          STRING "";
                                                                                                          STRING "";
                                                                                                  };
                                                                                          };
                                                                                  };
                                                                          };
                                                                  };
                                                          };
                                                          DICT_ENTRY "sv" {
                                                                  STRING "devs";
                                                                  VARIANT "aa{ss}" {
                                                                          ARRAY "a{ss}" {
                                                                                  ARRAY "{ss}" {
                                                                                          DICT_ENTRY "ss" {
                                                                                                  STRING "devnode";
                                                                                                  STRING "/dev/sda";
                                                                                          };
                                                                                          DICT_ENTRY "ss" {
                                                                                                  STRING "uuid";
                                                                                                  STRING "93d4e9c0526044a38a7491e0452add49";
                                                                                          };
                                                                                  };
                                                                          };
                                                                  };
                                                          };
                                                          DICT_ENTRY "sv" {
                                                                  STRING "key_description";
                                                                  VARIANT "(bv)" {
                                                                          STRUCT "bv" {
                                                                                  BOOLEAN true;
                                                                                  VARIANT "(bs)" {
                                                                                          STRUCT "bs" {
                                                                                                  BOOLEAN true;
                                                                                                  STRING "pool0";
                                                                                          };
                                                                                  };
                                                                          };
                                                                  };
                                                          };
                                                  };
                                          };
                                  };
                          };
                  };
          };
          ARRAY "s" {
          };
  };
```

**Comment by mvollmer** [comment]
> [stratis-storage/stratisd#2923](https://github.com/stratis-storage/stratisd/issues/2923)

This got fixed already, but needs to be released. So I guess we wait a few days to see where we are then.

While testing the fix, I got this selinux message:

```
audit: type=1400 audit(1644567117.086:148): avc:  denied  { associate } for  pid=535 comm="systemd-udevd" name="stratis" scontext=system_u:object_r:stratisd_data_t:s0 tcontext=system_u:object_r:device_t:s0 tclass=filesystem permissive=0
```

and (aha!) it's already known: https://github.com/cockpit-project/bots/issues/2877

**Comment by martinpitt** [comment]
The fix got released in 3.0.4, and 3.0.3 got unpushed. So let's try this again.

**Pull request closed without merging**
