### PR TITLE
Image refresh for fedora-39

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-39
 * [x] image-refresh fedora-39

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-39 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-39-20240710-231256

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-39-d10c50e4-20240710-223718/log.html

**Comment by martinpitt** [comment]
[dnf install hanging](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6602-46cadd7f-20240711-035003-fedora-39-candlepin-subscription-manager/log.html) for that long for just three packages is highly suspicious.  I already saw such an error in the cockpit-composer test, but a retry worked.

**Comment by martinpitt** [comment]
The Fedora mirrors were abysmally slow yesterday. Let's try again.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
