### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-testing-20231018-083939.log

**Comment by martinpitt** [comment]
Olala, `w` crashes a lot now. This needs reporting and ignoring globally, too big for a naughty.

**Comment by martinpitt** [comment]
This is already reported at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1053706 and fixed upstream. I added a commit to ignore the crash messages. Let's give it another run -- I still expect some tests to fail which actually cover the "last login" information, but these should be few enough to handle via a naughty.

**Comment by martinpitt** [comment]
I do understand the [testGroups](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5402-20231019-111458-ddca05d5-debian-testing-other-cockpit-project-cockpit/log.html#168-2) failure, that needs another naughty pattern. But testUserPasswords? That works for me..

```
❱❱❱ ./test-failure-policy -o debian-testing < /tmp/out 
Known issue #5419
```

**Comment by martinpitt** [comment]
@jelly I *hope* it goes green now. I need to EOD now, if it still fails, please ignore.

**Review by jelly — APPROVED** [review]
w segfaulting, now that's something I haven't seen before

**Pull request merged**
