### PR TITLE
Image refresh for rhel-7-9

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-7-9
 * [x] image-refresh rhel-7-9

### CODE REVIEW

**Comment by marusak** [comment]
```
Apr 15 06:53:26 localhost.localdomain com.redhat.SubscriptionManager[640]: return ep.load()
Apr 15 06:53:26 localhost.localdomain com.redhat.SubscriptionManager[640]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
Apr 15 06:53:26 localhost.localdomain com.redhat.SubscriptionManager[640]: entry = __import__(self.module_name, globals(),globals(), ['__name__'])
Apr 15 06:53:26 localhost.localdomain com.redhat.SubscriptionManager[640]: File "/usr/lib64/python2.7/site-packages/subscription_manager/scripts/rhsm_d.py", line 55, in <module>
Apr 15 06:53:26 localhost.localdomain com.redhat.SubscriptionManager[640]: import psutil
Apr 15 06:53:26 localhost.localdomain com.redhat.SubscriptionManager[640]: ImportError: No module named psutil
```
[rhbz#1821830](https://bugzilla.redhat.com/show_bug.cgi?id=1821830)talks about `AttributeError: 'Restlib' object has no attribute '_get_cert_key_list'` so this needs a new BZ a naughty.

**Comment by marusak** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1823523 there we go

**Comment by marusak** [comment]
Ok, so this can be naughtified. Another common pattern I see there is that it is waiting for 'Not registered' on the overview page, but it sees 'Bug fixes are available'. Not sure what is the expected behaviour really.

**Comment by martinpitt** [comment]
@marusak: If cockpit can't talk to rhsmd, it assumes there is no registration support (like on Fedora), so that's expected. I. e. it's just a follow-up of rhsmd crashing.

**Comment by marusak** [comment]
Meh, could not push into this branch (permission denied), so I opened #774

**Pull request closed without merging**
