### PR TITLE
Image refresh for fedora-rawhide-anaconda-payload

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-anaconda-payload
 * [x] image-refresh fedora-rawhide-anaconda-payload

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-anaconda-payload done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-anaconda-payload-20240313-224612

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-anaconda-payload-3a06d23f-20240313-223725/log.html

**Comment by martinpitt** [comment]
@KKoukiou @M4rtinK : This [pixel test failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6085-f5e7479c-20240313-224845-fedora-rawhide-boot-rhinstaller-anaconda-webui/pixeldiff.html#TestStorageCockpitIntegration-testEncryptedUnlock-storage-editor) should be robustified in webui -- better ignore that part or replace it with a mock value?

**Comment by martinpitt** [comment]
I retried, and it's stable.

**Comment by KKoukiou** [comment]
> I retried, and it's stable.

Payload size can be indeed changed with this 'image'  - aka payload - update.

**Review by martinpitt — APPROVED** [review]
webui pixel update landed, so this goes along with it.

**Pull request merged**
