### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by marusak** [comment]
In `dnf-copr` all packagekit tests failed with `Packagekit is not installed`. Needs to be looked at.

**Comment by marusak** [comment]
Wait, why is this working locally?
```
./test/verify/check-packagekit TestAutoUpdates.testBasic
```

possibly some nond test breaks it?

**Comment by marusak** [comment]
Perfect, `./test/common/run-tests --test-dir test/verify TestHistoryMetrics.testNoData TestAutoUpdates.testBasic` reproduces this just fine.

**Comment by marusak** [comment]
Aha, I thought that metrics tests broke it, but by accident I pick the only metrcis tests that does not touch packagekit :)
It happens with any test:
```
./test/common/run-tests --test-dir test/verify TestJournal.testBinary TestAutoUpdates.testBasic
```
so the issue must be with general cleanup after nond test and not with any specific test.

**Comment by marusak** [comment]
Just refreshing the page is enough to make it work so it is not broken completly, just the first call to pk api fails with "not-found". A bit of trial and error and I got it down to one line.

This line in `test/verify/packagelib.py` is the problem:
```
self.machine.execute("systemctl kill --signal=SIGKILL packagekit; rm -rf /var/cache/PackageKit")
```

If I comment it out, it seems to work just fine.

Splitting it into two halves shows, that only `systemctl kill --signal=SIGKILL packagekit` is the problematic part.

**Comment by marusak** [comment]
> Splitting it into two halves shows, that only `systemctl kill --signal=SIGKILL packagekit` is the problematic part.

Seems to be fine to drop it on the new f-testing, but then it breaks for example F-32.
I'll compare what has changed in the new image and see, if these is something more to it.

**Comment by marusak** [comment]
```
Removed:

Added:

Changed:
  SDL2 (2.0.12-4.fc33 -> 2.0.14-1.fc33)
  bind-libs (32:9.11.26-2.fc33 -> 32:9.11.27-1.fc33)
  bind-libs-lite (32:9.11.26-2.fc33 -> 32:9.11.27-1.fc33)
  bind-license (32:9.11.26-2.fc33 -> 32:9.11.27-1.fc33)
  bind-utils (32:9.11.26-2.fc33 -> 32:9.11.27-1.fc33)
  btrfs-progs (5.9-1.fc33 -> 5.10-1.fc33)
  cockpit (235-1.fc33 -> 236-1.fc33)
  cockpit-bridge (235-1.fc33 -> 236-1.fc33)
  cockpit-system (235-1.fc33 -> 236-1.fc33)
  cockpit-ws (235-1.fc33 -> 236-1.fc33)
  conmon (2:2.0.24-1.fc33 -> 2:2.0.25-1.fc33)
  crun (0.16-3.fc33 -> 0.17-1.fc33)
  dbus-broker (24-1.fc33 -> 26-1.fc33)
  dnsmasq (2.82-3.fc33 -> 2.83-1.fc33)
  fuse-overlayfs (1.3.0-1.fc33 -> 1.4.0-1.fc33)
  gdisk (1.0.5-2.fc33 -> 1.0.6-1.fc33)
  kernel (5.10.8-200.fc33 -> 5.10.9-201.fc33)
  kernel-core (5.10.8-200.fc33 -> 5.10.9-201.fc33)
  kernel-modules (5.10.8-200.fc33 -> 5.10.9-201.fc33)
  kernel-tools (5.9.9-200.fc33 -> 5.10.9-200.fc33)
  kernel-tools-libs (5.9.9-200.fc33 -> 5.10.9-200.fc33)
  kexec-tools (2.0.20-21.fc33 -> 2.0.21-4.fc33)
  libibumad (32.0-1.fc33 -> 33.0-1.fc33)
  libibverbs (32.0-1.fc33 -> 33.0-1.fc33)
  librdmacm (32.0-1.fc33 -> 33.0-1.fc33)
  nftables (1:0.9.3-6.fc33 -> 1:0.9.3-7.fc33)
  pango (1.48.0-1.fc33 -> 1.48.1-1.fc33)
  python-unversioned-command (3.9.1-1.fc33 -> 3.9.1-2.fc33)
  python3 (3.9.1-1.fc33 -> 3.9.1-2.fc33)
  python3-libs (3.9.1-1.fc33 -> 3.9.1-2.fc33)
  python3-nftables (1:0.9.3-6.fc33 -> 1:0.9.3-7.fc33)
  python3-perf (5.9.9-200.fc33 -> 5.10.9-200.fc33)
  python3-pyyaml (5.3.1-4.fc33 -> 5.4.1-1.fc33)
  rdma-core (32.0-1.fc33 -> 33.0-1.fc33)
  tlog (10-1.fc33 -> 11-1.fc33)
  xen-libs (4.14.1-1.fc33 -> 4.14.1-2.fc33)
  xen-licenses (4.14.1-1.fc33 -> 4.14.1-2.fc33)
```

Almost no change, I wonder if it happens on the current f-testing.

**Comment by marusak** [comment]
Bah, does not happen on the current master: https://github.com/cockpit-project/cockpit/pull/15216

**Comment by marusak** [comment]
`dnf downgrade dbus-broker` does the trick. It seems, that when we kill the process, dbus-broker somehow behaves differently then it used to.

**Comment by marusak** [comment]
Ok, I can reproduce and it seems that just restarting service does the trick.
```
# busctl get-property org.freedesktop.PackageKit /org/freedesktop/PackageKit  org.freedesktop.PackageKit BackendDescription
s "Dnf"                                                                         
                                                                                
# systemctl kill --signal=SIGKILL packagekit                                    
                                                                                
# busctl get-property org.freedesktop.PackageKit /org/freedesktop/PackageKit  org.freedesktop.PackageKit BackendDescription
s "Dnf"                                                                         
                                                                                
# rpm -q dbus-broker                                                            
dbus-broker-24-1.fc33.x86_64                                                    
                                                                                
                                                                                
--------------------------------------                                          
# busctl get-property org.freedesktop.PackageKit /org/freedesktop/PackageKit  org.freedesktop.PackageKit BackendDescription
s "Dnf"                                                                         
                                                                                
# systemctl kill --signal=SIGKILL packagekit                                    
                                                                                
# busctl get-property org.freedesktop.PackageKit /org/freedesktop/PackageKit  org.freedesktop.PackageKit BackendDescription
Failed to get property BackendDescription on interface org.freedesktop.PackageKit: Could not activate remote peer.
                                                                                
# busctl get-property org.freedesktop.PackageKit /org/freedesktop/PackageKit  org.freedesktop.PackageKit BackendDescription
s "Dnf"                                                                         
                                                                                
# rpm -q dbus-broker                                                            
dbus-broker-26-1.fc33.x86_64                                                    
                                                                                
-----------------------------------                                             
# busctl get-property org.freedesktop.PackageKit /org/freedesktop/PackageKit  org.freedesktop.PackageKit BackendDescription
s "Dnf"                                                                         
                                                                                
# systemctl kill --signal=SIGKILL packagekit                                    
                                                                                
# systemctl restart packagekit                                                  
                                                                                
# busctl get-property org.freedesktop.PackageKit /org/freedesktop/PackageKit  org.freedesktop.PackageKit BackendDescription
s "Dnf"                                                                         
                                                                                
# rpm -q dbus-broker                                                            
dbus-broker-26-1.fc33.x86_64   
```

**Comment by marusak** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/15218 which hopefully works everywhere.

**Comment by martinpitt** [comment]
The packagekit fix landed, re-running.

**Review by marusak — APPROVED** [review]

**Pull request merged**
