### PR TITLE
Image refresh for fedora-39

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-39
 * [x] image-refresh fedora-39

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-39 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-39-20240912-230015

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-39-872e2886-20240912-224015/log.html

**Comment by jelly** [comment]
@croissanne does composer still want to test on Fedora-39?

**Review by jelly — APPROVED** [review]

**Comment by croissanne** [comment]
@jelly we're basically following your lead. When you're ready to remove it just let me know and I'll do it :)

**Pull request merged**
