### PR TITLE
scripts: add Fedora 40 image

### PR DESCRIPTION
**Pull request by jelly**
* [x] image-refresh fedora-40

### CODE REVIEW

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-40-20240220-174040.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-40-20240220-174141.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-40-20240220-181010.log

**Comment by jelly** [comment]
```
+ rm -f /var/tmp/SETUP
killing ssh master process 580
+ ! test -f /run/nologin && cat /proc/sys/kernel/random/boot_id
Uploading to https://cockpit-images.eu-central-1.linodeobjects.com/fedora-40-46ed164cb0cab6cb864e681e1d5d15f9946b283ddad9a83d5f4250fef77533c2.qcow2
Uploading to https://cockpit-images.us-east-1.linodeobjects.com/fedora-40-46ed164cb0cab6cb864e681e1d5d15f9946b283ddad9a83d5f4250fef77533c2.qcow2
Traceback (most recent call last):
  File "/usr/lib64/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib64/python3.12/http/client.py", line 1327, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.12/http/client.py", line 1373, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.12/http/client.py", line 1322, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.12/http/client.py", line 1081, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.12/http/client.py", line 1025, in send
    self.connect()
  File "/usr/lib64/python3.12/http/client.py", line 1461, in connect
    super().connect()
  File "/usr/lib64/python3.12/http/client.py", line 991, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/usr/lib64/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host
```

@allisonkarlitskaya @martinpitt this happened twice now in a row, so this must be some infra failure.

**Comment by martinpitt** [comment]
Indeed, our minio S3 server on cockpit-11 was broken. Fallout from my screwup last week, sorry. Fixed and retried.

**Comment by martinpitt** [comment]
When you push the image, please don't forget to add it to image-trigger as well. Naughties are already in place.

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-40-20240221-063838.log

**Review by martinpitt — CHANGES_REQUESTED** [review]
Thanks! Please add to image-trigger, too.

**Comment by jelly** [comment]
> Thanks! Please add to image-trigger, too.

Oh duh!

**Review by martinpitt — APPROVED** [review]
Cheers! Welcome, 40! :star2:

**Pull request merged**
