### PR TITLE
Image refresh for fedora-rawhide-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-boot
 * [x] image-refresh fedora-rawhide-boot

### CODE REVIEW

**Comment by martinpitt** [comment]
@VladimirSlavik, @jkonecny12: So #3277 was not just a random failure, rawhide really does not boot any more. Could this possibly be related to [dropping legacy BIOS support](https://fedoraproject.org/wiki/Changes/DeprecateLegacyBIOS)? I.e. the image now needs to be booted with EFI?

**Comment by VladimirSlavik** [comment]
@M4rtinK you have infra duty, do you think you will have time to look at this?

**Comment by M4rtinK** [comment]
> @VladimirSlavik, @jkonecny12: So #3277 was not just a random failure, rawhide really does not boot any more. Could this possibly be related to [dropping legacy BIOS support](https://fedoraproject.org/wiki/Changes/DeprecateLegacyBIOS)? I.e. the image now needs to be booted with EFI?

Looks like the change in it's current form was rejected:

`As discussed in [today's meeting](https://meetbot.fedoraproject.org/fedora-meeting/2022-04-26/fesco.2022-04-26-17.00.log.html#l-131), I'm processing this change as rejected. FESCo will ask BIOS sig to submit a new change with plans/responsibilities.`

From: https://pagure.io/fesco/issue/2780#comment-794311

So its not it, at least not directly - they would certainly not push the switch before the change has been approved by FESCO but I can imagine possibly some boot related fixed/improvement being pushed as a result of the big discussion and boot tooling investigation triggered by the change proposal.

I'll fetch the image locally and try if it boots on my machine in BIOS & EFI modes. :)

**Comment by jelly** [comment]
Loaded the iso into gnome-boxes (bios boot) and it boots fine but there seems to be some issue with a systemd unit

image

Our boot timeout is 1 minute? So I assume that's why the test fails.

**Comment by VladimirSlavik** [comment]
That might be it, I think - I saw this too but did not think it would be significant. It's somewhat annoying.

Tagging @poncovka who's the infra duty this week...

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3301-20220505-080404/

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-boot done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-boot-20220505-080707

**Review by allisonkarlitskaya — APPROVED** [review]
Oops.  Obviously this shouldn't be two commits, but it's also harmless, so let's go with it.

**Comment by VladimirSlavik** [comment]
Thank you!

**Pull request merged**
