### PR TITLE
image-customize: Use 2 GiB RAM by default

### PR DESCRIPTION
**Pull request by mvollmer**
Running dnf might need this now.

### CODE REVIEW

**Comment by mvollmer** [comment]
This is needed for https://github.com/cockpit-project/bots/pull/4456. subman and cockpit-composer canÄt run their "dnf" customizations otherwise: https://cockpit-logs.us-east-1.linodeobjects.com/pull-4456-20230301-120317-9937de87-fedora-36-candlepin-subscription-manager/log.html

**Comment by mvollmer** [comment]
subman already has "--memory-mb 2048" in one of its image-customize invocations, but not in the other, and I think this is a general problem that should be fixed in image-customize.

**Comment by mvollmer** [comment]
Hmm, let's put this right into the image refresh PR...

**Comment by martinpitt** [comment]
Ooh, thanks for tracking this down! 1 GiB of memory!?!? Ugh. FTR, +1 for the change.

**Pull request closed without merging**
