### PR TITLE
images: Adjust fedora-coreos network config to current release

### LINKED ISSUE #708: Image refresh for fedora-coreos
Image refresh for fedora-coreos
 * [ ] FAIL: image-refresh fedora-coreos

### PR DESCRIPTION
**Pull request by martinpitt**
Latest CoreOS does not like it when new network interfaces appear after
the initial boot. Move the configuration of eth1 from the .setup script
to the initial bootstrap by putting the NM device config into the
Ignition config.

Also the latest Ignition compiler now uses GNU CLI syntax,  adjust the
comment how to build it.

Fixes #708

 * [x] image-refresh fedora-coreos
 * [x] Skip dhclient-modifying tests on fedora-coreos: https://github.com/cockpit-project/cockpit/pull/13851
 * [x] Adjust error messages on ostree: https://github.com/cockpit-project/cockpit-ostree/pull/74

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-726-20200405-203333/

**Comment by cockpituous** [comment]
image-refresh fedora-coreos done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-coreos-20200405-203939

**Comment by martinpitt** [comment]
The two [check-networking-* failures](https://logs.cockpit-project.org/logs/pull-726-20200405-215115-7ce7f578-fedora-coreos-cockpit-project-cockpit/log.html) are due to dropping dhclient. NM uses its internal implementation now, so we can't slow it down. I'll send a PR to disable that bit.

**Comment by martinpitt** [comment]
The [ostree failure](https://logs.cockpit-project.org/logs/pull-726-20200405-215112-7ce7f578-fedora-coreos-cockpit-project-cockpit-ostree/log.html#3) is just a changed error message, I [sent a fix](https://github.com/cockpit-project/cockpit-ostree/pull/74).

**Pull request merged**
