### PR TITLE
Image refresh for rhel-8-2

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-2
 * [x] image-refresh rhel-8-2

### CODE REVIEW

**Comment by marusak** [comment]
c-podman fails with:
```
Trying to pull registry.access.redhat.com/busybox...
  name unknown: Repo not found
Trying to pull registry.redhat.io/busybox...
  unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
Error: error pulling image "busybox": unable to pull busybox: 2 errors occurred:
	* Error initializing source docker://registry.access.redhat.com/busybox:latest: Error reading manifest latest in registry.access.redhat.com/busybox: name unknown: Repo not found
	* Error initializing source docker://registry.redhat.io/busybox:latest: unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
```

**Comment by martinpitt** [comment]
@marusak: I. e. its' not even attempting to try docker.io/*? Perhaps we should try an explit `pull docker.io/busybox`,  but of course without a registry it should still work.

**Comment by martinpitt** [comment]
This got broken recently in RHEL 8.2: https://bugzilla.redhat.com/show_bug.cgi?id=1810056

We can work around it by specifying the registry though, I'll send a PR.

**Comment by marusak** [comment]
@martinpitt nice, thanks for the investigation!
I think we can just do the workaround. I am happy to send PR.

**Comment by martinpitt** [comment]
Fix sent to https://github.com/cockpit-project/cockpit-podman/pull/335

**Pull request merged**
