### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-coreos done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-coreos-20231121-224932

**Comment by cockpituous** [comment]
Completed. Log: Error accessing /repos/cockpit-project/bots/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value":5577,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/pulls/pulls#create-a-pull-request"}

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-coreos-20231121-224949.log

**Comment by martinpitt** [comment]
[This test](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5577-20231122-043846-ae3728ad-fedora-coreos-expensive-cockpit-project-cockpit/log.html#63-2) failed twice in a row now, but it's one of our top flakes, so retrying a second time.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
