### PR TITLE
Image refresh for debian-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-stable
 * [x] image-refresh debian-stable
 * [x] https://github.com/allisonkarlitskaya/ferny/pull/25
 * [x] Pull the above ferny fix into cockpit: https://github.com/cockpit-project/cockpit/pull/19799

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20231229-225857

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-stable-20231229-225858.log

**Comment by martinpitt** [comment]
Interestingly it is *not* the libssh 0.10.5 → 0.10.6 upgrade, which has caused us so much trouble. Upgrading libssh-4.deb to 0.10.6 on the image still passes the test. Upgrading openssh from 1:9.2p1-2+deb12u1 to u2 on the *target* (secondary) machine also works. Upgrading that openssh version on the *source* (primary) machine breaks. That explains why it only affects the shell, not the login page, as the latter uses cockpit-ssh and the former uses ferny.

With `COCKPIT_DEBUG=cockpit.remote`, the log for the working case is:

```
Request for channel {'payload': 'echo', 'host': '10.111.113.2', 'init-superuser': None, 'command': 'open', 'channel': '1:4', 'flow-control': True} is remote.
key=('10.111.113.2', None, None)
('10.111.113.2', None, None) is not among the existing remotes {}.  Opening a new connection.
Starting ssh session user=None, host=10.111.113.2, private=False
SshPeer got a <class 'cockpit._vendor.ferny.ssh_errors.SshUnknownHostKeyError'> No ED25519 host key is known for 10.111.113.2 and you have requested strict checking.
Host key verification failed.; private False, seen hostkeys []; raising unknown-host with extra args {}
Request for channel {'session': 'private', 'payload': 'echo', 'host': '10.111.113.2', 'init-superuser': None, 'command': 'open', 'channel': '1:5', 'flow-control': True} is remote.
key=('10.111.113.2', None, '1:5')
('10.111.113.2', None, '1:5') is not among the existing remotes {}.  Opening a new connection.
Starting ssh session user=None, host=10.111.113.2, private=True
SshPeer got a <class 'cockpit._vendor.ferny.ssh_errors.SshUnknownHostKeyError'> No ED25519 host key is known for 10.111.113.2 and you have requested strict checking.
Host key verification failed.; private True, seen hostkeys [('HOSTNAME', '10.111.113.2', 'ssh-ed25519', 'AAAAC3NzaC1lZDI1NTE5AAAAILVH0rmPcgO2AS6Ptjyjt/lllCZVfkbWwKuAr3HhfQmP', 'SHA256:9g/7ckrPe5HjMJzQ5f5dorvZw9opIFnYLQFWT4V22U8')]; raising unknown-hostkey with extra args {'host-key': '10.111.113.2 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILVH0rmPcgO2AS6Ptjyjt/lllCZVfkbWwKuAr3HhfQmP', 'host-fingerprint': 'SHA256:9g/7ckrPe5HjMJzQ5f5dorvZw9opIFnYLQFWT4V22U8'}
```

with the new openssh in the failing case it doesn't report any host keys, the last line is:
```
Host key verification failed.; private True, seen hostkeys []; raising unknown-hostkey with extra args {}
```

**Comment by martinpitt** [comment]
https://github.com/allisonkarlitskaya/ferny/pull/25 is at least necessary if not sufficient. Locally fixes at least TestSuperuserDashboard and TestHostSwitching.testBasic. I'll test the rest in a cockpit PR, I'll update the description.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
