### PR TITLE
images: Drop verbose output of insights-client on rhel-7-9

### LINKED ISSUE #3199: Image refresh for rhel-7-9 - fixed in #3251
Image refresh for rhel-7-9
 * [x] bring back nightly extras repo: https://issues.redhat.com/browse/RHELDST-11075
 * [ ] FAIL: image-refresh rhel-7-9

### PR DESCRIPTION
**Pull request by martinpitt**
Apply the same change as commit 208af0f997a368 for RHEL 8/9.
    
This avoids dumping a giant binary blob onto stdout.
    
Fixes #3199

 * [x] image-refresh rhel-7-9

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-3251-20220419-091818/

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-7-9-20220419-095858

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-3251-20220419-095858/

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-7-9-20220419-104444

**Comment by martinpitt** [comment]
The test passed. Not sure what went wrong with the statuses update.

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
