### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-3000-20220225-024242/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20220225-030202

**Comment by martinpitt** [comment]
RuntimeError: TypeError: Cannot set properties of undefined (setting 'vendor_urls')

PackageKit change? This points out an unchecked variable in our code, needs fixing in cockpit.

**Comment by mvollmer** [comment]
> This points out an unchecked variable in our code, needs fixing in cockpit.

I'll look at that.

**Comment by mvollmer** [comment]
> > This points out an unchecked variable in our code, needs fixing in cockpit.
> 
> I'll look at that.

Looks broken to me.

The UpdateDetail signal/callback/whatever is invoked with the wrong packageId.  In the TestUpdates.testUpdateError test case, we call `GetUpdateDetail` for "vapor;1-2;all;local" (the available update) but get back information via UpdateDetail for "vapor;1-1;all;manual:local" (the currently installed package).

Previously, UpdateDetail would be invoked with "vapor;1-2;all;local".

This new image does not contain a newer PackageKit, however:

```
Changed:
  apt (2.3.15 -> 2.4.0)
  debianutils (4.11.2 -> 5.7-0.1)
  golang-github-containernetworking-plugins (0.9.1+ds1-1 -> 1.0.1+ds1-1)
  golang-github-containers-dnsname (1.3.1+ds1-1+b1 -> 1.3.1+ds1-2)
  nftables (1.0.1-1 -> 1.0.2-1)
  python3.9 (3.9.10-1 -> 3.9.10-2)
```

Maybe the changes to apt or dpkg have confused the PackageKit backend for Debian.

**Comment by mvollmer** [comment]
> Looks broken to me.

Making Cockpit robust against this (by ignoring details for unexpected package ids) makes it so that testUpdateError is actually able to install the update, although it is expected to fail.  The summary says that no packages have been installed.

So maybe there is a bug with resolving a package id to the exact "VerIterator", and it always picks the installed one instead of the correct one. *shrug* I see if I can get a cli reproducer.

**Comment by mvollmer** [comment]
Reproducer:

Set up the "vapor" packages as in TestPackagekit.testUpdatesError (but leave the files in the repo).

```
# pkcon  get-updates
Normal      	vapor-1-2.all (local)                                       	dummy vapor
# pkcon resolve vapor
Installed   	vapor-1-1.all (manual:local)                                	dummy vapor
Available   	vapor-1-2.all (local)                                       	dummy vapor
# pkcon get-update-detail vapor
Details about the update:
 Package: vapor-1-1.all
 Updates: vapor;1-1;all;manual:local
 Update text: 
 Changes: Changelog for this version is not yet available
 Issued: 
 Updated: 
# pkcon update vapor
There are no updates available at this time.
```

With the previous debian-testing image, we get this:

```
# pkcon get-updates
Normal      	vapor-1-2.all (local)                                       	dummy vapor
root@debian:~# pkcon resolve vapor
Installed   	vapor-1-1.all (installed:local)                             	dummy vapor
Available   	vapor-1-2.all (local)                                       	dummy vapor
root@debian:~# pkcon get-update-detail vapor
Details about the update:
 Package: vapor-1-2.all
 Updates: vapor;1-1;all;installed:local
 Update text: 
 Changes: Changelog for this version is not yet available
 Issued: 
 Updated: 
root@debian:~# pkcon update vapor
```

vapor 1.1 was "installed:local" and is now "manual:local", get-update-detail used to say "Package: vapor-1.2.all", and now says "Package: vapor-1-1.all", and "pkcon update" actually installs 1.2.

**Comment by mvollmer** [comment]
Filed a bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006440

**Comment by mvollmer** [comment]
> Filed a bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006440

Oh no, I totally messed up the package versions... we did update packagekit from 1.2.4 to 1.2.5...

**Comment by mvollmer** [comment]
Ah, it's already being worked on: 

https://github.com/PackageKit/PackageKit/issues/534

**Comment by mvollmer** [comment]
> Ah, it's already being worked on:
> 
> [PackageKit/PackageKit#534](https://github.com/PackageKit/PackageKit/issues/534)

Fixed in 1.2.5-2, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006440#15.  Let's wait a bit for that.

**Comment by martinpitt** [comment]
It just [migrated to testing](https://tracker.debian.org/news/1307292/packagekit-125-2-migrated-to-testing/), so we can retry tomorrow when it got published and the mirrors caught up.

**Comment by martinpitt** [comment]
Then let's re-do this

**Pull request closed without merging**
