### PR TITLE
naughty: systemd regression spilled from fedora-34 to fedora-33 and image-refresh fedora-33

### PR DESCRIPTION
**Pull request by skobyda**
Copy the existing fedora-33 naughty to fedora-34

Known issue #1739

### CODE REVIEW

**Comment by skobyda** [comment]
Moved the fedora-33 image refresh from #1834 to here to see if moving naughty files fixes failures

**Comment by martinpitt** [comment]
@skobyda : It's much easier to commit the naughty updates etc. straight into the image-refresh-* branch and thus the existing PR. Then you don't need to duplicate PRs and split the information. It's not even possible to handle more than one naughty update or image build script fix at a time with this "separate PR" approach.

**Comment by marusak** [comment]
Tests are not green, I suggest rather then retrying to just push that one commit into  #1828 and closing this.

**Comment by marusak** [comment]
> naughty: systemd regression spilled from fedora-34 to fedora-33

Maybe also please rename the commit message as well. There is no process in which changes from F34 trickle down down to F33 (unless F34 would be current rawhide and F33 would be the next branched out release, but that is not the case). It is just that F33 now has new systemd that landed in F34 sooner.

**Comment by mvollmer** [comment]
I am not yet comfortable calling this a "systemd regression".  In my understanding right now, the udev rules were always set up to produce this kind of behavior (suspended device mapper devices are treated by systemd as unplugged), but we got lucky that the udev rules never ran while a dm device was suspended until now.

**Comment by skobyda** [comment]
> I am not yet comfortable calling this a "systemd regression". In my understanding right now, the udev rules were always set up to produce this kind of behavior (suspended device mapper devices are treated by systemd as unplugged), but we got lucky that the udev rules never ran while a dm device was suspended until now.

Im just copying the name from existing fedora-34 naughties.
But sure, reading at https://bugzilla.redhat.com/show_bug.cgi?id=1934567 I'm seeing it's either cryptsetup failt? we could rename it to something else (on both fedora-34 and fedora-33), like `udev-rules-unmount-fs` ? WDYT @mvollmer

**Comment by skobyda** [comment]
So I added the commit to #1834 . Closing this PR

**Pull request closed without merging**
