### PR TITLE
Image refresh for opensuse-tumbleweed

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for opensuse-tumbleweed
 * [x] image-refresh opensuse-tumbleweed

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh opensuse-tumbleweed done: https://github.com/cockpit-project/bots/commits/image-refresh-opensuse-tumbleweed-20240616-225225

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-opensuse-tumbleweed-cf4f9a79-20240616-223836/log.html

**Comment by martinpitt** [comment]
@Nykseli @Lunarequest the new rebuild breaks iSCSI somehow. In the above image build log you can see a list of package changes (near the bottom). 

I'm not sure if it's due to the

> One time configuration for iscsi.service was skipped because of an unmet condition check (ConditionPathExists=!/etc/iscsi/initiatorname.iscsi).

or if that was there before. This needs some investigation.

**Comment by Nykseli** [comment]
Looks like new version of `python-rtslib-fb-common` broke `targetcli` which is causing the issue.
There's a bugzilla about is so hopefully it will be resolved soon. https://bugzilla.suse.com/show_bug.cgi?id=1226333

P.s. @SludgeGirl also works on these images so tagging her gets you even more visibility :-)

**Comment by Nykseli** [comment]
I'm just happy to see tests catching issues! :grin:

**Comment by martinpitt** [comment]
There's no movement on the downstream bug. This has been open for too long -- let's just naughty these four failures.

**Comment by Nykseli** [comment]
Looks like issue with python library was fixed [1] but no one has updated the bugzilla. 

And now we have another issue with admin group not being created when the admin user is created [2]. Which breaks one of the tests. It has been fixed but the fix is not yet on the latest tumbleweed snapshot. It will _hopefully_ land on friday

[1]: https://build.opensuse.org/request/show/1181351
[2]: https://bugzilla.suse.com/show_bug.cgi?id=1226850

**Comment by Nykseli** [comment]
Looks like the latest tumbleweed snapshot has all the required fixes. On my machine™, the tests are passing again!

**Comment by martinpitt** [comment]
Yay, thanks @Nykseli ! Let's close this one then and let the bots rebuild a fresh one.

**Comment by martinpitt** [comment]
→ #6552

**Pull request closed without merging**
