### PR TITLE
Image refresh for fedora-rawhide-anaconda-payload

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
* [x] image-refresh fedora-rawhide-anaconda-payload

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-anaconda-payload done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-anaconda-payload-20231002-064829

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-anaconda-payload-20231002-064848.log

**Review by allisonkarlitskaya — COMMENTED** [review]
That looks better, but I can't self-review.

**Comment by allisonkarlitskaya** [comment]
Another apparent issue: `tests-trigger - fedora-rawhide-anaconda-payload` triggers nothing.

**Comment by allisonkarlitskaya** [comment]
> Another apparent issue: `tests-trigger - image:fedora-rawhide-anaconda-payload` triggers nothing.

That much, [seems to be intentional](https://github.com/cockpit-project/bots/pull/5057).

> Right now it is not gated

**Review by jelly — APPROVED** [review]

**Comment by KKoukiou** [comment]
@jelly @allisonkarlitskaya the fact that this was not gated is definitely not intended. [Here](https://github.com/cockpit-project/bots/pull/5057) I describe the previous problematic situation, and why we moved here - which is to have this gated :P 


Additionally I am afraid that this merge was the reason for anaconda webui CI being right now broken. Will debug this and update.

**Comment by allisonkarlitskaya** [comment]
> @jelly @allisonkarlitskaya the fact that this was not gated is definitely not intended. [Here](https://github.com/cockpit-project/bots/pull/5057) I describe the previous problematic situation, and why we moved here - which is to have this gated :P
> 
> Additionally I am afraid that this merge was the reason for anaconda webui CI being right now broken. Will debug this and update.

Ya, it did seem a bit off to me.  Happy to hear that it was not intended, and sorry if I broke something by landing this without testing.

**Pull request merged**
