### PR TITLE
images: Add fedora-coreos image

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh fedora-coreos

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-04.
Log: https://209.132.184.41:8493/logs/image-refresh-218-20191107-141818/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-218-20191107-141818/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-10.
Log: https://209.132.184.41:8493/logs/image-refresh-218-20191107-141818/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-218-20191107-141818/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-05.
Log: https://209.132.184.41:8493/logs/image-refresh-218-20191107-144141/

**Comment by cockpituous** [comment]
image-refresh fedora-coreos done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-coreos-20191107-145252

**Comment by martinpitt** [comment]
There isn't much that we can test with the new image yet; once that lands, I'll send a cockpit PR to adjust the tests for it. This PR also adds the new context as a manual test.

**Comment by martinpitt** [comment]
Ah, we stopped testing fedora-atomic on Cockpit recently, as fedora-29 is gone. Triggering ostree instead.

**Pull request merged**
