### PR TITLE
Fix rhel-9-0: Missing package and naughties

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh rhel-9-0

Tested in https://github.com/cockpit-project/cockpit/pull/15614

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-1860-20210329-124242/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20210329-125454

**Comment by martinpitt** [comment]
This definitively helped. I analyzed the [remaining 10 failures](https://logs.cockpit-project.org/logs/pull-15614-20210329-125805-5748ce09-rhel-9-0-bots-1860/log.html) (down from 28), and updated https://github.com/cockpit-project/cockpit/pull/15614 to fix ~ 7 of them. The rest look more complicated and are probably actual regressions that need to be reported/naughtied, but that can happen step by step.

**Comment by martinpitt** [comment]
cockpit-machines worked fine in https://github.com/cockpit-project/cockpit-machines/pull/27

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
