### PR TITLE
Image refresh for rhel-9-0

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-0
 * [x] image-refresh rhel-9-0

### CODE REVIEW

**Comment by martinpitt** [comment]
Yay, consistent compose again. There are [two test failures](https://logs.cockpit-project.org/logs/pull-1989-20210505-023530-feabb5ee-rhel-9-0-cockpit-project-cockpit/log.html#24-2), one of which (nc segfaulting) looks rather dubious. Retrying once to compare.

**Comment by martinpitt** [comment]
Yup, this is kaputt.

**Comment by KKoukiou** [comment]
@martinpitt do you want to review my naugties?

**Review by KKoukiou — APPROVED** [review]

**Review by martinpitt — APPROVED** [review]
Very naughty! :grin:

**Pull request merged**
