### PR TITLE
Image refresh for fedora-rawhide-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-boot
 * [x] image-refresh fedora-rawhide-boot

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-boot done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-boot-20231114-223935

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-boot-20231114-223939.log

**Comment by jelly** [comment]
@KKoukiou does this require a retry to fix the flakes?

**Comment by KKoukiou** [comment]
@jelly yes, this image not loading is a known flake, did not find the time to resolve this. Please retry.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
