### PR TITLE
images: Introduce rhel-8-3

### PR DESCRIPTION
**Pull request by marusak**
* [x] image-refresh rhel-8-3

image-create locally went fine and tested one test to see if the image boots and it seemed fine.

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-776-20200420-102121/

**Comment by cockpituous** [comment]
image-refresh rhel-8-3 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-3-20200420-104242

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-776-20200421-053737/

**Comment by marusak** [comment]
We need a new refresh as kmod-kvdo was in old version and was not working with the given kernel, but new version is available.

**Comment by cockpituous** [comment]
image-refresh rhel-8-3 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-3-20200421-055959

**Pull request merged**
