### PR TITLE
images: Build rhel-8-3 from official qcow image

### LINKED ISSUE #1522: Image refresh for rhel-8-3
Image refresh for rhel-8-3
 * [ ] FAIL: image-refresh rhel-8-3

### PR DESCRIPTION
**Pull request by martinpitt**
Starting from the cloud image is faster, more robust, and more realistic
(using an official product) than our own virt-install bootstrap.

Teach cloudimage.bootstrap to get along with redirects, as
download.devel.redhat.com is a geolocation mirror.

Fixes #1522

 * [x] image-refresh rhel-8-3
 - [x] builds on top of PR #1518
 - [x] needs subscription-manager fix: https://github.com/candlepin/subscription-manager/pull/2380 (broken in general, unrelated to the new image)
 - [x] needs cockpit-composer backported fix: https://github.com/osbuild/cockpit-composer/pull/1208
 - [x] needs lorax/rhel8 image preparation fix: https://github.com/weldr/lorax/pull/1105
 - [x] .. and its backport to rhel8: https://github.com/weldr/lorax/pull/1106
 - [x] fix some cockpit test regressions
 - [x] fix composer flake: https://github.com/osbuild/cockpit-composer/pull/1215

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-1527-20210107-074040/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1527-20210107-074040/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-1527-20210107-074444/

**Comment by cockpituous** [comment]
image-refresh rhel-8-3 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-3-20210107-075858

**Comment by martinpitt** [comment]
Fixing `TestUpdatesSubscriptions` was simple (sub-man is disabled by default on the cloud image), but `TestLogin.testExpired` is more subtle: This really *is* a bug in RHEL 8.3, which we already found long ago in gating -- that's why we [disabled the test downstream](https://src.fedoraproject.org/rpms/cockpit/blob/917966bcedaf571eb6fc5c796c057636b85cdc73/f/tests/run-test.sh#_75) for Fedora 31 and RHEL.

This seems to work fine on RHEL 8.4 (as we already use the cloud image there). I want to see if that's something obvious in the PAM config, otherwise I'll just file a naughty for it.

**Comment by martinpitt** [comment]
That should do it. I'll clean this up a bit in a follow-up, to move the *.install adjustments into the cockpit tests themselves. But I don't want to block this any further.

**Comment by martinpitt** [comment]
@jkozol, @henrywang : [this flake](https://logs.cockpit-project.org/logs/pull-1527-20210114-181122-84bf7018-rhel-8-3-firefox-osbuild-cockpit-composer-rhel-8/log.html#22-2) seems to happen over and over. Do you know what's happening there?

**Comment by martinpitt** [comment]
At this point I'll call the composer/firefox failure unrelated. This has been failing for a long time. Most recent example known to me is in https://github.com/osbuild/cockpit-composer/pull/1208

**Comment by henrywang** [comment]
@martinpitt, I have a new [PR](https://github.com/osbuild/cockpit-composer/pull/1215) to fix this issue on branch `rhel-8`

**Comment by martinpitt** [comment]
Many thanks @henrywang !

**Review by marusak — APPROVED** [review]
Nice, thanks!

**Pull request merged**
