### PR TITLE
images: Add rsync to openshift image

### PR DESCRIPTION
**Pull request by martinpitt**
Since commit d4489db8c, all our images need rsync installed. openshift
was the last one which missed that, which broke tests of cockpit's
rhel-7.9 branch.

----

Fixes [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3669-20220729-063527-5104c6c6-rhel-7-9-cockpit-project-cockpit-rhel-7.9/log.html#163). It doesn't only affect the image refresh, it's broken on current main.

 * [x] image-refresh openshift

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-3671-20220729-135050/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3671-20220729-135050/

**Comment by martinpitt** [comment]
> API rate limit exceeded for 66.187.232.129.

Argh argh argh dockercalypse! I have the image refresh locally, so in the worst case I'll upload that directly. However, I'll give it one more try over the weekend, when hopefully dockerhub gets pounded less from the RH network.

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-14.
Log: https://logs.cockpit-project.org/logs/image-refresh-3671-20220729-190101/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3671-20220729-190101/

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-12.
Log: https://logs.cockpit-project.org/logs/image-refresh-3671-20220730-064040/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3671-20220730-064040/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-6p2t6.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-3671-20220730-071212/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpit-project/bots/commits/image-refresh-openshift-20220730-073510

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
