### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by marusak** [comment]
Failed 2 times on the same issue. It sets up udp port 194 and expects that we recognize that it is `irc`. But we don't. Seems like it dropped out from `/etc/services`?

**Comment by marusak** [comment]
Hmm, indeed, in the new `/etc/services` there are many services missing. No idea why.
Current debian-stable: [old_etc_services.txt](https://github.com/cockpit-project/bots/files/4044769/old_etc_services.txt)
Debian-stable from this PR: [new_etc_services.txt](https://github.com/cockpit-project/bots/files/4044770/new_etc_services.txt)

**Comment by martinpitt** [comment]
The removal of irc [was intended](https://tracker.debian.org/news/1089559/accepted-netbase-60-source-into-unstable/), so I suppose we should change the test to use a port that is still being used in this millenium?

**Comment by marusak** [comment]
Sent https://github.com/cockpit-project/cockpit/pull/13381 which fixes this.

**Comment by martinpitt** [comment]
Fix landed in cockpit master, re-running.

**Pull request merged**
