### PR TITLE
images: Add cockpit pybridge build dependencies to Debian/Ubuntu pbuilder

### PR DESCRIPTION
**Pull request by martinpitt**
This will allow us to start building and testing the debs with the pybridge in the official way. This extra package list can be removed after https://github.com/cockpit-project/cockpit/pull/18757 lands, then these will be picked up by the usual parsing of build dependencies from cockpit main.

 * [x] image-refresh debian-testing
 * [x] test that first and rebuild the other 3 images if/once this works sufficiently well in the above cockpit PR
 * [x] image-refresh debian-stable
 * [x] image-refresh ubuntu-2204
 * [x] image-refresh ubuntu-stable
 * [x] Do a first test run against these other 3 images to confirm the package builds and mostly works: See linked logs in https://github.com/cockpit-project/cockpit/pull/18757

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20230505-202646

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-testing-20230505-202626.log

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20230505-205315

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-stable-20230505-205353.log

**Comment by cockpituous** [comment]
image-refresh ubuntu-2204 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2204-20230505-210836

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/ubuntu-2204-20230505-210808.log

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20230505-212412

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/ubuntu-stable-20230505-212424.log

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20230506-055150

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-stable-20230506-055151.log

**Comment by cockpituous** [comment]
image-refresh ubuntu-2204 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2204-20230506-061115

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/ubuntu-2204-20230506-061111.log

**Review by mvollmer — APPROVED** [review]

**Pull request merged**
