### PR TITLE
images: Add NetworkManager-openvpn to fedora images

### PR DESCRIPTION
**Pull request by subhoghoshX**
NetworkManager-openvpn is necessary in for integration tests of openvpn configurations

 * [x] image-refresh fedora-39
 * [x] image-refresh fedora-38

### CODE REVIEW

**Comment by martinpitt** [comment]
Here, have a bots label! Triggered the refreshes.

**Comment by cockpituous** [comment]
image-refresh fedora-39 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-39-20230922-170819

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-39-20230922-170808.log

**Comment by cockpituous** [comment]
image-refresh fedora-38 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-38-20230922-173654

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-38-20230922-173636.log

**Comment by martinpitt** [comment]
Ah good, you already pushed the images. Now the next step is to trigger all tests that use these images:
```
./tests-trigger 5292 image:fedora-3{8,9}
```

**Comment by subhoghoshX** [comment]
> Ah good, you already pushed the images. Now the next step is to trigger all tests that use these images:
> 
> ```
> ./tests-trigger 5292 image:fedora-3{8,9}
> ```

I get the 404 errors again 🥲

**Comment by martinpitt** [comment]
@subhoghoshX Ah right, different project. I sent you an invite for the "committers" team, then this will work for all cockpit projects.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
