### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing
 * [x] https://github.com/cockpit-project/cockpit-machines/pull/1764

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20240812-225222

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-debian-testing-314032a6-20240812-223906/log.html

**Comment by martinpitt** [comment]
New AppArmor denial:

> audit: type=1400 audit(1723503632.836:152): apparmor="DENIED" operation="open" class="file" profile="libvirt-aabe06c9-c0ff-4128-a956-6bc1fe37fabe" name="/proc/sys/vm/max_map_count" pid=6865 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0

Probably from  libvirt-daemon (10.5.0-1 -> 10.6.0-1) , needs confirmation.

And we have to do something about that [bridge crash](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6730-54fd8f07-20240812-225338-debian-testing-cockpit-project-cockpit-files/log.html#16) -- it's not a regression from the image refresh, it also [affects c-files PRs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-701-64610cc9-20240812-061748-debian-testing/log.html#16-1) and is [at the top of the weather report](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit-files&days=7)

**Comment by martinpitt** [comment]
It cleared up, but this [TestMultiMachineVNC](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6730-dee48a5f-20240813-053938-debian-testing-cockpit-project-cockpit-machines/log.html#60-2) failure is persistent.

**Review by mvollmer — APPROVED** [review]
Thanks!

**Pull request merged**
