### PR TITLE
Image refresh for fedora-40

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-40
 * [x] image-refresh fedora-40
 * [x] https://github.com/cockpit-project/cockpit/pull/20850

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-40 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-40-20240807-033852

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-40-6f633484-20240807-031708/log.html

**Comment by martinpitt** [comment]
Noooo! This NFS kdump failure is still here, despite not turning up in the nightly runs. We *just never ever* get a free ride, don't we :cry:

**Comment by martinpitt** [comment]
Meh, I ran this four times locally, with chromium and firefox, and I cannot reproduce. kdump is still broken, the other tests get skipped on #6114 (and they fail the same way locally). 

Locally, the kdump machine's console shows this after test-crashing the kernel:
```
[   28.036683] sysrq: Trigger a crash
[   28.036919] Kernel panic - not syncing: sysrq triggered crash
[   28.037245] CPU: 0 PID: 4345 Comm: sh Kdump: loaded Not tainted 6.9.12-200.fc40.x86_64 #1
[    0.000000] Linux version 6.9.12-200.fc40.x86_64 (mockbuild@c8d7f86626ae4d1ab5450ec2dba703ce) (gcc (GCC) 14.1.1 20240701 (Red Hat 14.1.1-7), GNU ld version 2.41-37.fc40) #1 SMP PREEMPT_DYNAMIC Sat Jul 27 15:56:15 UTC 2024
```
... and it immediately reboots into kdump mode:

```
[    1.321330] dracut-cmdline[269]: Using kernel command line parameters:  rd.neednet kdump_remote_ip=10.111.113.2   elfcorehdr=0x27000000 BOOT_IMAGE=(hd0,gpt3)/vmlinuz-6.9.12-200.fc40.x86_64 ro rootflags=subvol=root no_timer_check net.ifnames=0 console=tty1 console=ttyS0,115200n8 rootflags=subvol=root irqpoll nr_cpus=1 reset_devices cgroup_disable=memory mce=off numa=off udev.children-max=2 panic=10 acpi_no_memhotplug transparent_hugepage=never nokaslr hest_disable novmcoredd cma=0 hugetlb_cma=0 pcie_ports=compat disable_cpu_apicid=0
[...]
[    2.489121] systemd[1]: Mounting kdumproot.mount - /kdumproot...
         Mounting kdumproot.mount - /kdumproot...
```
Unfortunately that's everything -- there's no console message about *actually* doing the dump to the NFS machine. After that, it reboots again into the normal system.

On [failing CI test](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6706-f3e62d04-20240807-034031-fedora-40-expensive-cockpit-project-cockpit/log.html), there  *two* kernel panics, the second one immediately after the supposed kdump boot (after the first one happened):

```
[    2.096753] Run /init as init process
/init: line 17: modprobe: command not found
/init: line 18: modprobe: command not found
/init: line 19: modprobe: command not found
mount: /squash/root: failed to setup loop device for /squash-root.img.
mount: /newroot: unknown filesystem type 'overlay'.
       dmesg(1) may have more information after failed mount system call.
mount: /newroot/squash: mount point does not exist.
       dmesg(1) may have more information after failed mount system call.
/init: line 34: exec: switch_root: not found
[    2.152787] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
``

After that it reboots *again*, and this is again into the normal mode, not kdump. So the kdump never happens. There's no trace of `kdump_remote_ip` or `kdumproot`. 

This seems to be a flake -- the retry now passed on chromium.

@licliu do you happen to have any idea what's going on here? This looks like a broken dracut initrd build which is unable to boot into kdump mode. Any hints how to debug this? Thanks!

**Comment by martinpitt** [comment]
@licliu sorry, I botched the notification from the previous comment. If you could have a look at my question above, I'd appreciate. Thanks!

**Comment by licliu** [comment]
@martinpitt, from the log it seems the kdump initrd is broken, at least modprobe is missing.
```
/init: line 17: modprobe: command not found
/init: line 18: modprobe: command not found
/init: line 19: modprobe: command not found
```
I'd like to know how does initrd is generated. Is there a image I can download to reproduce this issue? I want to get some debug log by running `debug=1 kdumpctl rebuild`.

**Comment by martinpitt** [comment]
@licliu The kdump page can generate an Ansible role which uses [linux-system-role's kdump role](https://galaxy.ansible.com/ui/standalone/roles/linux-system-roles/kdump/). This test generates this role:

```yaml
- name: install linux-system-roles
  package:
    name: linux-system-roles
    state: present
  delegate_to: 127.0.0.1
  become: true
- name: run kdump system role
  include_role:
    name: linux-system-roles.kdump
  vars:
    kdump_path: /var/crash
    kdump_core_collector: makedumpfile -l --message-level 7 -d 31
    kdump_target:
      type: nfs
      location: 10.111.113.2:/srv/kdump
```

The role is run with

    ansible -vv -m include_role -a name=kdump localhost

and then immediately rebooted. It could very well be that the bug is in l-s-r, that it doesn't properly wait for kdump.service to rebuild the initrd or so? But that should be synchronous -- the [journal](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6706-f3e62d04-20240808-042120-fedora-40-firefox-expensive-cockpit-project-cockpit/TestKdumpNFSAnsible-testBasic-fedora-40-127.0.0.2-2202-FAIL-1.log.gz) of that machine shows output which seems successful:

```
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: kernel-modules-extra ***
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]:   kernel-modules-extra: configuration source "/run/depmod.d" does not exist
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]:   kernel-modules-extra: configuration source "/etc/depmod.d" is ignored (directory or doesn't exist)
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]:   kernel-modules-extra: configuration source "/lib/depmod.d" does not exist
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: kernel-network-modules ***
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: pcmcia ***
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]: Skipping udev rule: 60-pcmcia.rules
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: qemu ***
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: qemu-net ***
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: tpm2-tss ***
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: fstab-sys ***
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: nfs ***
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: rootfs-block ***
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: terminfo ***
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: udev-rules ***
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: virtiofs ***
Aug 08 04:33:54 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: dracut-systemd ***
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: usrmount ***
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: base ***
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: fs-lib ***
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: kdumpbase ***
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 NetworkManager[796]: <info>  [1723091635.6297] audit: op="connection-add" uuid="35bdd208-9551-4911-99c5-aebaad9ae955" name="static-52-54-01" pid=2887 uid=0 result="success"
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 NetworkManager[796]: <info>  [1723091635.6539] audit: op="connection-update" uuid="35bdd208-9551-4911-99c5-aebaad9ae955" name="static-52-54-01" args="connection.timestamp,ipv4.may-fail" pid=2893 uid=0 result="success"
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: Warning: There is another connection with the name 'static-52-54-01'. Reference the connection by its uuid '35bdd208-9551-4911-99c5-aebaad9ae955'
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 NetworkManager[796]: <info>  [1723091635.6779] audit: op="connection-update" uuid="35bdd208-9551-4911-99c5-aebaad9ae955" name="static-52-54-01" args="ipv6.method" pid=2900 uid=0 result="success"
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: Warning: There is another connection with the name 'static-52-54-01'. Reference the connection by its uuid '35bdd208-9551-4911-99c5-aebaad9ae955'
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 NetworkManager[796]: <info>  [1723091635.7017] audit: op="connection-update" uuid="35bdd208-9551-4911-99c5-aebaad9ae955" name="static-52-54-01" args="connection.wait-device-timeout" pid=2909 uid=0 result="success"
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: Warning: There is another connection with the name 'static-52-54-01'. Reference the connection by its uuid '35bdd208-9551-4911-99c5-aebaad9ae955'
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 NetworkManager[796]: <info>  [1723091635.7476] audit: op="connection-update" uuid="35bdd208-9551-4911-99c5-aebaad9ae955" name="static-52-54-01" args="802-3-ethernet.mac-address" pid=2926 uid=0 result="success"
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: Warning: There is another connection with the name 'static-52-54-01'. Reference the connection by its uuid '35bdd208-9551-4911-99c5-aebaad9ae955'
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 NetworkManager[796]: <info>  [1723091635.7702] audit: op="connection-update" uuid="35bdd208-9551-4911-99c5-aebaad9ae955" name="static-52-54-01" args="connection.interface-name" pid=2934 uid=0 result="success"
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: Warning: There is another connection with the name 'static-52-54-01'. Reference the connection by its uuid '35bdd208-9551-4911-99c5-aebaad9ae955'
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 NetworkManager[796]: <info>  [1723091635.8182] audit: op="connection-delete" uuid="35bdd208-9551-4911-99c5-aebaad9ae955" name="static-52-54-01" pid=2952 uid=0 result="success"
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: Connection 'static-52-54-01' (35bdd208-9551-4911-99c5-aebaad9ae955) successfully deleted.
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: memstrack ***
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: shutdown ***
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including module: squash ***
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: *** Including modules done ***
Aug 08 04:33:55 fedora-40-127-0-0-2-2201 dracut[1163]: *** Installing kernel module dependencies ***
Aug 08 04:33:56 fedora-40-127-0-0-2-2201 dracut[1163]: *** Installing kernel module dependencies done ***
Aug 08 04:33:56 fedora-40-127-0-0-2-2201 dracut[1163]: *** Resolving executable dependencies ***
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: *** Resolving executable dependencies done ***
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: *** Hardlinking files ***
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: Mode:                     real
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: Method:                   sha256
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: Files:                    605
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: Linked:                   1 files
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: Compared:                 0 xattrs
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: Compared:                 15 files
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: Saved:                    60.58 KiB
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: Duration:                 0.006805 seconds
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: *** Hardlinking files done ***
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: *** Generating early-microcode cpio image ***
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: *** Store current command line parameters ***
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: Stored kernel commandline:
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: rd.neednet
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: kdump_remote_ip=10.111.113.2
Aug 08 04:33:57 fedora-40-127-0-0-2-2201 dracut[1163]: *** Install squash loader ***
Aug 08 04:33:58 fedora-40-127-0-0-2-2201 systemd[1]: NetworkManager-dispatcher.service: Deactivated successfully.
Aug 08 04:33:58 fedora-40-127-0-0-2-2201 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 08 04:33:58 fedora-40-127-0-0-2-2201 dracut[1163]: *** Stripping files ***
Aug 08 04:33:58 fedora-40-127-0-0-2-2201 dracut[1163]: *** Stripping files done ***
Aug 08 04:33:58 fedora-40-127-0-0-2-2201 dracut[1163]: *** Squashing the files inside the initramfs ***
Aug 08 04:34:12 fedora-40-127-0-0-2-2201 dracut[1163]: *** Squashing the files inside the initramfs done ***
Aug 08 04:34:12 fedora-40-127-0-0-2-2201 dracut[1163]: *** Creating image file '/boot/initramfs-6.9.12-200.fc40.x86_64kdump.img' ***
Aug 08 04:34:12 fedora-40-127-0-0-2-2201 dracut[1163]: *** Creating initramfs image file '/boot/initramfs-6.9.12-200.fc40.x86_64kdump.img' done ***
Aug 08 04:34:13 fedora-40-127-0-0-2-2201 kdumpctl[923]: kdump: kexec: loaded kdump kernel
Aug 08 04:34:13 fedora-40-127-0-0-2-2201 kdumpctl[923]: kdump: Starting kdump: [OK]
Aug 08 04:34:13 fedora-40-127-0-0-2-2201 systemd[1]: Finished kdump.service - Crash recovery kernel arming.
```

The time coincides with the Ansible output:
```
localhost | CHANGED => {
    "backup_file": "/etc/kdump.conf.1450.2024-08-08@04:33:27~",
```

> Is there a image I can download to reproduce this issue? 

I'm unfortunately unable to reproduce it locally with the test. On CI it seems to fail 75% and pass 25% of the time, so it's some timing issue.

I sent https://github.com/cockpit-project/cockpit/pull/20850 to increase logging, and I'll experiment with some sleeps and adding `debug=1 kdumpctl rebuild`.

**Comment by martinpitt** [comment]
@licliu I made some experiments in https://github.com/cockpit-project/cockpit/pull/20850 with some interesting results:

  * First I tried to merely sleep(30) before rebooting, just in case the initrd rebuilding happened async in the background and got interrupted by the reboot. No change.
  * Then I [added an explicit initrd rebuild](https://github.com/cockpit-project/cockpit/commit/3409fca02e59995f1f0b7c4904f11d89ed2ef9bc) after running the Ansible role, with `debug=1 kdumpctl rebuild`. The [test log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20850-3409fca0-20240808-125859-fedora-40-expensive-bots%236706/log.html#6) now has two metric tons of dracut-install output, and after that it *still* fails with exactly the same "modprobe: not found / exec: switch_root: not found" error. I was a bit afraid that the rebuild would change the result, but it doesn't -- so that hopefully should help a bit.

Could that be a problem, or is that expected?
```
dracut-install: get_real_file(/usr/bin/modprobe) not found
dracut-install: find_binary(modprobe) == /usr/sbin/modprobe
dracut-install: dracut_install '/usr/sbin/modprobe'
dracut-install: dracut_install('/usr/sbin/modprobe', '/usr/sbin/modprobe', 0, 1, 1)
dracut-install: dest dir '/var/tmp/dracut.OGHtj4/initramfs/usr/sbin' does not exist
```

**Comment by martinpitt** [comment]
@licliu also, the [image build log](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-40-6f633484-20240807-031708/log.html) has the full package update list at the bottom, but the relevant ones are probably these:
```
dracut (101-1.fc40 -> 102-2.fc40)
kdump-utils (1.0.42-10.fc40 -> 1.0.44-1.fc40)
kernel-core (6.9.9-200.fc40 -> 6.9.12-200.fc40)
systemd (255.8-1.fc40 -> 255.10-1.fc40)
```

**Comment by licliu** [comment]
@martinpitt I noticed there is an initramfs unpacking error:
```
[    1.150400] Initramfs unpacking failed: write error
```
It should be something wrong when unpacking initramfs in the kdump kernel.

**Comment by licliu** [comment]
From the log I can see there is ~82M available memory in second kernel and the initrd is ~42M. The memory might just be insufficient, so it occasionally succeeds when there is a bit more available memory(for the 25% passed cases).

**Comment by martinpitt** [comment]
> From the log I can see there is ~82M available memory in second kernel

Interesting, where do you see that? I'd like to learn how to spot that for the future. I only saw:

> Memory: 929016K/1048036K available (20480K kernel code, 4290K rwdata, 15108K rodata, 4700K init, 5356K bss, 118760K reserved, 0K cma-reserved)

I increased the kdump machine's RAM from 1024 MiB to 1280 MiB, and that [worked better](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20850-dad395a4-20240808-174742-fedora-40-expensive-bots%236706/log.html), but still failed. I tried to increase it further to 1500 MiB, and that [RUNNING](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20850-d0f79b82-20240808-181440-fedora-40-expensive-bots%236706/log.html). Using that much RAM brings our CI to the brim of OOM by itself, and ballooning by several hundred MB sounds like a bug.

But I'll get that landed for now to unblock this. Thanks for your help!

**Comment by licliu** [comment]
> > From the log I can see there is ~82M available memory in second kernel
> 
> Interesting, where do you see that? I'd like to learn how to spot that for the future. I only saw:
> 

Nothing special, just by searching "Memory: " around the second kernel boot log.
```
[    0.018960] Memory: 84248K/196340K available (20480K kernel code, 4290K rwdata, 15108K rodata, 4700K init, 5356K bss, 111836K reserved, 0K cma-reserved)
```

> I increased the kdump machine's RAM from 1024 MiB to 1280 MiB.

I'm afraid that increasing the vm's RAM will not work.  Kdump kernel uses the reserved memory, which is specified by crashkernel= in kernel cmdline. 

We have a default value "crashkernel=1G-4G:192M,4G-64G:256M,64G-:512M" based on experience. But as kernel size grows, default value starts to become insufficient. We are also seeing more OOM issues in RHEL.

I suggest to run `grubby --update-kernel=ALL --args="crashkernel=256M"` or do same work by l-s-r.bootloader after linux-system-roles.kdump and before system reboot since l-s-r.kdump doesn't support custom crashkernel values.

**Comment by martinpitt** [comment]
@licliu hmm, it did survive a 5x amplified test run with increased memory. Perhaps the automatic `crashkernel` adjusts to that?

> I suggest to run grubby --update-kernel=ALL --args="crashkernel=256M"

No, we will very much not do that in tests/production. The whole *point* of using linux-system-roles and Ansible for a user is to *not* do manual hacking afterwards. However, it is a good hint for debugging thanks! If this fails again and that helps, we'll file a bug against l-s-r.

**Comment by licliu** [comment]
@martinpitt Thanks for the explanation! 

Yes, we don't do this in test/production, I just want you to run it for debugging purposes.

If we observe a significant increase in out-of-memory issues with new OS releases, we will adjust the default values ​​for crashkernel, which is what we are working on. We are investigating a more flexible way to estimate a suitable crashkernel value based on runtime after the OS is installed, but it is still under investigation.

**Comment by martinpitt** [comment]
@licliu Thanks!

**Comment by licliu** [comment]
And for your test, by the default "crashkernel=1G-4G:192M,4G-64G:256M,64G-:512M", system memory > 4G we will reserve 256M for crashkernel, I think this can explain why increase RAM works.

**Comment by martinpitt** [comment]
Hmm, I only bumped it from 1024 to 1500 MiB. There's no way we can spend 4 GiB (our CI runners just aren't that big). Also, it would be an unrealistic demand IMHO -- RAM is expensive in clouds (which is where a lot of customer workload is).  So I suppose it was not due to that default `crashkernel`. But I thought it looked like the *unpacking* of the initramfs somehow ran out of memory? (I can't really imagine that either -- 1 GiB is a *lot* of space, initrds shouldn't be that bloated). Mystery..

**Comment by licliu** [comment]
OK, that's interesting, for 1500M RAM, kdump can only use 192M by default, as I commented before, from the log there is ~82M available memory. For unpacking initrd, it should be enough in most cases, but maybe some other services ate some memory. The memory may be in a state of just enough or not enough, since the runtime enviorment may vary from run to run, the final results may not be stable.

**Comment by mvollmer** [comment]
@licliu, I am running into the same symptoms on Fedora 41 now. I think you really need to bump your crashkernel defaults.

This is all super obscure and impossible to figure out when it happens to a normal person. Is there really any point in optimizing crashkernel values? Can't we just use 512 MiB everywhere?

**Comment by martinpitt** [comment]
@mvollmer I don't claim I understood everything, but it seemed to me that last time the reason was not a too small "crashkernel" (we didn't bump RAM enough to slide into the next bigger range), but that somehow unpacking the initrd ran out of RAM. It can't possibly take a full GiB to do that, so I take it this is somehow confined in another way (or unpacking takes way more RAM than appropriate). So it's still mysterious to me, but my gut feeling is that bumping `crashkernel` won't change it (also, our tests change the value themselves at least in some cases). Remember, this is failing on *boot*, not on oops time.

**Pull request merged**
