### PR TITLE
images: Move fedora-testing to Fedora 35

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh fedora-testing
 * https://github.com/cockpit-project/cockpit/pull/16864

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-2841-20220121-132626/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-2841-20220121-134949/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20220121-141212

**Comment by martinpitt** [comment]
[This failure](https://logs.cockpit-project.org/logs/pull-2841-20220121-151158-203fd812-fedora-testing-dnf-copr-cockpit-project-cockpit/log.html#113-2) rings a bell -- it was renamed, and we need to adjust cockpit's tests accordingly.

**Comment by martinpitt** [comment]
Let's rebase after the depending PR lands, for accurate test stats.

**Comment by martinpitt** [comment]
Rebased, dependency landed, should be good now.

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
