### PR TITLE
images: Move ubuntu-stable to oracular

### PR DESCRIPTION
**Pull request by martinpitt**
With the recent introduction of ubuntu-2404, let's move ubuntu-stable off 24.04 to the current development series "oracular", which will become 24.10. It is already past feature freeze, so now is a good time to find and fix bugs.

Drop the workarounds which applied to 24.04.

 * [x] https://github.com/cockpit-project/cockpit-machines/pull/1487
 * [x] https://github.com/cockpit-project/cockpit/pull/20946
 * [x] https://github.com/cockpit-project/cockpit/pull/20947
 * [x] do a cockpit-machines testlib update to pick up :arrow_up: https://github.com/cockpit-project/cockpit-machines/pull/1787
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by martinpitt** [comment]
I locally ran cockpit-podman against a locally built image, and all green. So trigger that here. Otherwise this depends on https://github.com/cockpit-project/cockpit/pull/20946

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20240827-113551

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-stable-8712e93f-20240827-111950/log.html

**Comment by martinpitt** [comment]
[c-machines has two failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6799-95450f4a-20240827-113706-ubuntu-stable-cockpit-project-cockpit-machines/log.html). The first is a missing naughty, the VNC one is because c-machines requires enabling multihost, and that's blocked on https://github.com/cockpit-project/cockpit/pull/20946 and then a testlib update.

**Comment by martinpitt** [comment]
Ah no, "ubuntu-stable" precisely *falls out* of `self.multihost_enabled`, so this will require a more complicated lockstep update :thinking:

**Comment by martinpitt** [comment]
Very weird -- the pristine image boots fine on my laptop, but after `test/image-prepare -q ubuntu-stable`, `bots/vm-run ubuntu-stable` fails during boot:

```
[    2.383318] xor: automatically using best checksumming function   avx       
done.
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... Scanning for Btrfs filesystems
done.
Begin: Will now check root file system ... fsck from util-linux 2.40.2
[/usr/sbin/fsck.ext4 (1) -- /dev/vda1] fsck.ext4 -a -C0 /dev/vda1 
cloudimg-rootfs: recovering journal
cloudimg-rootfs: Clearing orphaned inode 298343 (uid=0, gid=999, mode=0100640, size=8388608)
cloudimg-rootfs: Clearing orphaned inode 262156 (uid=0, gid=999, mode=042755, size=4096)
cloudimg-rootfs: clean, 141906/1376256 files, 1009273/2752251 blocks
done.
[    2.500433] EXT4-fs (vda1): orphan cleanup on readonly fs
[    2.501379] EXT4-fs error (device vda1): ext4_orphan_get:1417: comm mount: bad orphan inode 298343
[    2.502858] ext4_test_bit(bit=3430, block=524294) = 0
[    2.503780] EXT4-fs error (device vda1): ext4_orphan_get:1417: comm mount: bad orphan inode 262156
[    2.505208] ext4_test_bit(bit=11, block=524292) = 0
[    2.506148] EXT4-fs (vda1): recovery complete
[    2.507498] EXT4-fs error (device vda1): ext4_mark_recovery_complete:6207: comm mount: Orphan file not empty on read-only fs.
[    2.509313] EXT4-fs (vda1): mount failed
mount: mounting /dev/vda1 on /root failed: Structure needs cleaning
done.
Begin: Running /scripts/local-bottom ... done.
Begin: Running /scripts/init-bottom ... mount: mounting /dev on /root/dev failed: No such file or directory
mount: mounting /dev on /root/dev failed: No such file or directory
done.
mount: mounting /run on /root/run failed: No such file or directory
BusyBox v1.36.1 (Ubuntu 1:1.36.1-9ubuntu1) multi-call binary.

Usage: run-init [-d CAP,CAP...] [-n] [-c CONSOLE_DEV] NEW_ROOT NEW_INIT [ARGS]
```

This apparently doesn't affect CI, but we need to investigate that first -- tests must be able to run on developer laptops.

**Comment by martinpitt** [comment]
The problem seems to be an unclean shutdown after image-prepare:
```
[  OK  ] Reached target poweroff.target - System Power Off.
[  127.009009] systemd-shutdown[1]: Failed to enumerate /proc/: Invalid argument
[  127.010245] systemd-shutdown[1]: Failed to enumerate /proc/: Invalid argument
[  127.033370] shutdown[1]: Failed to enumerate /proc/: Invalid argument
[  127.034522] shutdown[1]: Failed to enumerate /proc/: Invalid argument
[  127.047819] (sd-remou[10090]: Failed to remount '/run/shutdown/mounts/deeb11fc416f08f0' read-only: Device or resource busy
[  127.049921] (sd-umoun[10091]: Failed to unmount /run/shutdown/mounts/deeb11fc416f08f0: Device or resource busy
[  127.052401] (sd-umoun[10091]: Unmounting '/run/shutdown/mounts/deeb11fc416f08f0' blocked by: systemd-journal(303)
[  127.058362] shutdown[1]: Unable to finalize remaining file systems, ignoring.
[  127.062242] reboot: Power down
```

I just saw that we have -proposed versions on this image -- we can't do this just yet, only after release. This comes with kernel 6.11.0 which gives us no end of trouble in centos 10 as well.

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20240827-182336

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-stable-40843cf8-20240827-180726/log.html

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20240827-185839

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-stable-f59ce374-20240827-184412/log.html

**Review by jelly — APPROVED** [review]

**Pull request merged**
