### PR TITLE
Image refresh for rhel-10-0

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-10-0
 * [x] image-refresh rhel-10-0
 * [x] https://github.com/cockpit-project/cockpit/pull/20945
 * [x] https://github.com/candlepin/subscription-manager-cockpit/pull/80

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-10-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-10-0-20240826-225515

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-10-0-503d1d72-20240826-223933/log.html

**Comment by martinpitt** [comment]
Ah, so this didn't pick up the broken rc4 kernel, and "just" breaks the notoriously brittle `TestStorageNBDE.testRootReboot`. That needs checking.

@ptoscano : This fails `TestSubscriptions.testSubAndInAndFail` in the same way as the 9.5 update in PR #6775.

**Comment by martinpitt** [comment]
The cockpit NBDE test failure was very shallow, sent a PR, blocking on that.

**Comment by ptoscano** [comment]
> This fails `TestSubscriptions.testSubAndInAndFail` in the same way as the 9.5 update in PR #6775.

It's due to recent changes in insights-client that appeared few days ago in RHEL composes; see https://github.com/candlepin/subscription-manager-cockpit/pull/80 for a longer explanation and hopefully a fix (reviewer welcome, my JS is non-existent).

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
