### PR TITLE
images: install util-linux in cockpit/base image

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
The Fedora 36 container contains a stripped-down `util-linux-core`,
which doesn't have `getopt`, which we use when building the bastion
container in Cockpit.

Add the full `util-linux`.

 * [x] image-refresh fedora-36

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3368-20220511-123636/

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20220511-125656

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3368-20220511-125656/

**Comment by allisonkarlitskaya** [comment]
Looks good: https://logs.cockpit-project.org/logs/pull-3368-20220511-130647-a704f889-fedora-36-container-bastion-cockpit-project-cockpit/log.html

Let's make sure we didn't pick up some randomly-breaking stuff as a side-effect of the image refresh, and let's also make sure the changes to the container building didn't hurt fedora-35.

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20220511-131919

**Comment by martinpitt** [comment]
See https://github.com/cockpit-project/cockpit/pull/17336 as an alternative to this.

**Pull request closed without merging**
