### PR TITLE
Image refresh for fedora-rawhide-anaconda-payload

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-anaconda-payload
 * [x] image-refresh fedora-rawhide-anaconda-payload

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-anaconda-payload done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-anaconda-payload-20240824-224640

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-anaconda-payload-a43a23cd-20240824-223719/log.html

**Comment by martinpitt** [comment]
@KKoukiou does that startup failure ring a bell? Is that related to your manual fedora-rawhide-boot refresh in #6774?

**Comment by KKoukiou** [comment]
> @KKoukiou does that startup failure ring a bell? Is that related to your manual fedora-rawhide-boot refresh in #6774?

Nothing obvious - it showes that Web UI did not start.
I will need to download the new payload and check. Retrying to see if it's persistent.

**Comment by martinpitt** [comment]
@KKoukiou indeed, now it [fails on three pixel tests](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6779-b516c511-20240826-111522-fedora-rawhide-boot-other-rhinstaller-anaconda-webui/log.html) due to a change of the available space from 1.93 to 1.94 GB. Perhaps best to ignore or mock this number for the pixel test?

**Comment by KKoukiou** [comment]
> @KKoukiou indeed, now it [fails on three pixel tests](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6779-b516c511-20240826-111522-fedora-rawhide-boot-other-rhinstaller-anaconda-webui/log.html) due to a change of the available space from 1.93 to 1.94 GB. Perhaps best to ignore or mock this number for the pixel test?

https://github.com/rhinstaller/anaconda-webui/pull/417

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
