### PR TITLE
Image refresh for debian/ubuntu, install libnss-myhostname

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-stable
 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-2004
 * [x] image-refresh ubuntu-stable
 * Land in lockstep with https://github.com/cockpit-project/cockpit-podman/pull/877

### CODE REVIEW

**Comment by martinpitt** [comment]
Sounds like fallout from updating the base cockpit version.

**Comment by jelly** [comment]
> Sounds like fallout from updating the base cockpit version.

In the updated packages list cockpit does not appear?

**Comment by martinpitt** [comment]
Failed again with same errors, so needswork

**Comment by martinpitt** [comment]
The most plausible root cause what changed here is [sudo 1.9.5p2 → 1.9.8p2](https://tracker.debian.org/media/packages/s/sudo/changelog-1.9.8p2-1). All the other [changed packages](https://logs.cockpit-project.org/logs/image-refresh-2741-20211224-021818/log) seem mostly noise in this context.

E.g. `TestShutdownRestart.testBasic` changes the hostname in the `provision` properties, and that seems to upset sudo:

```
$ sudo true
sudo: unable to resolve host machine1: Name or service not known
sudo: error initializing audit plugin sudoers_audit
```

The `sudoers_audit` plugin seems to be a new thing from sudo 1.9.8. Once I make the host name resolvable (Debian/Ubuntu does not use libnss-myhosthame by default), it works again.

This actually fixes all 6 failures, so let's just install that -- Fedora etc. uses that as well, and these days it's really the right thing to do.

**Comment by cockpituous** [comment]
image-refresh in progress on 18-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-2741-20220103-122828/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20220103-124343

**Comment by cockpituous** [comment]
image-refresh in progress on 18-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-2741-20220103-124343/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20220103-130505

**Comment by cockpituous** [comment]
image-refresh in progress on 18-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-2741-20220103-130505/

**Comment by cockpituous** [comment]
Task threw an exception: https://logs.cockpit-project.org/logs/image-refresh-2741-20220103-130505/

**Comment by cockpituous** [comment]
image-refresh in progress on 18-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-2741-20220103-132424/

**Comment by cockpituous** [comment]
Task threw an exception: https://logs.cockpit-project.org/logs/image-refresh-2741-20220103-132424/

**Comment by martinpitt** [comment]
Meh [GitHub SSL errors](https://logs.cockpit-project.org/logs/image-refresh-2741-20220103-130505/log), retrying

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-9wwqh.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-2741-20220103-135454/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2004 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2004-20220103-141515

**Comment by cockpituous** [comment]
image-refresh in progress on 10-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-2741-20220103-141717/

**Comment by cockpituous** [comment]
Task threw an exception: https://logs.cockpit-project.org/logs/image-refresh-2741-20220103-141717/

**Comment by cockpituous** [comment]
image-refresh in progress on 11-cockpit-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-2741-20220103-144747/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20220103-151212

**Comment by martinpitt** [comment]
[podman failure on d-testing](https://logs.cockpit-project.org/logs/pull-2741-20220103-153720-3d99c7b4-debian-testing-cockpit-project-cockpit-podman/log.html), retrying to compare.

The test expects "restart policy" to be absent, but it is [present](https://logs.cockpit-project.org/logs/pull-2741-20220103-153720-3d99c7b4-debian-testing-cockpit-project-cockpit-podman/TestApplication-testRunImageSystem-debian-testing-127.0.0.2-2201-FAIL.png) So this could just be a new feature that debian-testing learned, but in the [package diff](https://logs.cockpit-project.org/logs/image-refresh-2741-20220103-124343/log) I don't see much relevant stuff for containers -- no runc/crun, podman, or kernel. the [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001780) is still pending. However, this might need some further examination.

**Comment by martinpitt** [comment]
I filed https://github.com/cockpit-project/cockpit-podman/pull/877 to enable restart policy testing on debian-testing now, that and this PR need to land in lockstep.

**Review by marusak — APPROVED** [review]
Thank you!

**Pull request merged**
