### PR TITLE
Image refresh for centos-10

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-10
  * [x] Needs fix for https://issues.redhat.com/browse/RHEL-56025 / https://issues.redhat.com/browse/RHEL-54549: Fixed in [this build](https://kojihub.stream.centos.org/koji/buildinfo?buildID=67881), needs to make it to the [compose](https://composes.stream.centos.org/stream-10/development/latest-CentOS-Stream/compose/BaseOS/x86_64/os/Packages/)
 * [x] image-refresh centos-10

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240826-225800

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-503d1d72-20240826-223926/log.html

**Comment by martinpitt** [comment]
Current kernel is hopelessly broken, blocking.

**Comment by martinpitt** [comment]
Yay, the fixed kernel is in the compose. Closing, let the bots generate a new one. Preferably after #6775 landed.

**Pull request closed without merging**
