### PR TITLE
images: Disable FreeIPA on debian-testing

### LINKED ISSUE #3539: Image refresh for debian-testing
Image refresh for debian-testing
 * [ ] FAIL: image-refresh debian-testing

### PR DESCRIPTION
**Pull request by marusak**
It seems it was dropped again. Partially reverts b91491f

Fixes #3539

 * [x] image-refresh debian-testing
 * [x] https://github.com/cockpit-project/cockpit/pull/17480

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-3544-20220622-052222/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20220622-054716

**Comment by marusak** [comment]
Not triggering tests, blocking on https://github.com/cockpit-project/cockpit/pull/17480 but in that PR I will trigger context against this new image

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit/pull/17480 landed, so triggering tests now.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
