### PR TITLE
Image refresh for rhel-9-5

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-5
 * [x] image-refresh rhel-9-5

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-9-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-5-20240605-225331

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-rhel-9-5-f55c7469-20240605-223726/log.html

**Comment by martinpitt** [comment]
This apparently [broke core dumping](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6473-0cb66a3d-20240606-043544-rhel-9-5-networking-cockpit-project-cockpit/log.html#3-2) somehow?

**Review by jelly — APPROVED** [review]
Approved assuming it goes green

**Pull request merged**
