### PR TITLE
images: Split off rhel.setup for RHEL/CentOS 7

### PR DESCRIPTION
**Pull request by martinpitt**
We will soon add RHEL 9, and it becomes too cumbersome to maintain all
the special cases for 7, 8, and 9 in one file. RHEL 7 will hardly change
any more, so that can settle down now and we can more easily change
rhel.setup without constantly breaking 7.

 * [x] image-refresh centos-7
 * [x] image-refresh rhel-7-9

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-1856-20210328-145454/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-7-20210328-150404

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-1856-20210328-150505/

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-7-9-20210328-152929

**Comment by martinpitt** [comment]
Ugh, this is totally broken :cry: back to draft

**Comment by martinpitt** [comment]
Ah, typoed the centos-7 setup script link, d'oh!

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-1856-20210328-184444/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-7-20210328-191414

**Review by marusak — APPROVED** [review]
Thanks!
Was about to ask if we should not clean up rhel.setup but then I checked out https://github.com/cockpit-project/bots/pull/1859/ and saw the commit.

**Pull request merged**
