### PR TITLE
Image-refresh fedora-34

### PR DESCRIPTION
**Pull request by cockpituous**
* [x] image-refresh fedora-34

### CODE REVIEW

**Comment by marusak** [comment]
[kdump](https://logs.cockpit-project.org/logs/pull-1865-20210330-155406-003abf9c-fedora-34-cockpit-project-cockpit/log.html#43-2) is acting up. I'll retry but seems broken.

**Comment by marusak** [comment]
Yeah, kdump is broken, needs work

**Comment by marusak** [comment]
I can reproduce this locally just fine, looking.

**Comment by marusak** [comment]
Machines tests are failing with:
`ls: cannot access 'cockpit-machines-242.1.tar.gz': No such file or directory`

**Comment by martinpitt** [comment]
@marusak: This is now some lurking bug in download-dist if HEAD is tagged -- then the tarball looks different. I'll look into that first thing in the morning tomorrow.

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit-machines/pull/34 as a quickfix for all the c-machines failures in current refreshes. Not a piece of proud engineering, but at least a hack.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
