### PR TITLE
Image refresh for fedora-eln-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-eln-boot
 * [x] image-refresh fedora-eln-boot

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-eln-boot done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-eln-boot-20231229-223946

**Comment by cockpituous** [comment]
image-refresh fedora-eln-boot done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-eln-boot-20231229-224038

**Comment by cockpituous** [comment]
Completed. Log: Error accessing /repos/cockpit-project/bots/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value":5735,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/pulls/pulls#create-a-pull-request"}

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-eln-boot-20231229-223939.log

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
