### PR TITLE
Image refresh for fedora-32

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-32
 * [x] image-refresh fedora-32
 * [x] adjust starter-kit tests to changed language selector dialog: https://github.com/cockpit-project/starter-kit/pull/411
 * [x] adjust cockpit-podman tests: https://github.com/cockpit-project/cockpit-podman/pull/641

### CODE REVIEW

**Comment by martinpitt** [comment]
@marusak: Could it be that f32 podman now supports checkpoint/restore?

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/starter-kit/pull/411 to adjust the starter-kit tests, same reason as in https://github.com/cockpit-project/bots/pull/1500

**Comment by marusak** [comment]
> @marusak: Could it be that f32 podman now supports checkpoint/restore?

I think so. A few weeks ago podman team was mentioning they will fix it up so if it works it is expected.

**Comment by marusak** [comment]
I sent https://github.com/cockpit-project/cockpit-podman/pull/641 for podman

**Comment by martinpitt** [comment]
kdump tests ran in https://github.com/cockpit-project/cockpit/pull/15087 , so all three blocked PRs are now ready to go.

**Review by martinpitt — APPROVED** [review]

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
