### PR TITLE
Image refresh for fedora-rawhide

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide
 * [ ] FAIL: image-refresh fedora-rawhide

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-20240229-022421

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-20240228-223727-c28e0864-image-refresh-fedora-rawhide/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-20240228-223727-c28e0864-image-refresh-fedora-rawhide/log.html

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-rawhide-20240228-223727-c28e0864-image-refresh-fedora-rawhide/log.html

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
