### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing
 * [x] https://github.com/cockpit-project/cockpit/pull/21174
 * [x] https://github.com/cockpit-project/cockpit/pull/21176

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20241025-225411

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-debian-testing-cd6f1d25-20241025-224030/log.html

**Comment by martinpitt** [comment]
The problem with [TestLogin.testBasic](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7033-8efd3fbe-20241026-063411-debian-testing-other-cockpit-project-cockpit/log.html#63-2) is that `who` is completely broken, and always empty now. Simple reproducer, just ssh in and type `who`. It's not ssh specific, same happens with a VT login.

The culprit is systemd (256.7-1 -> 256.7-2). It's actually known already: https://bugs.debian.org/1085643 . Apparently coreutils' `who` command still uses the old utmp, and systemd disables this now as it's not 2038 safe. We only call `who` during tests, and could move that to `loginctl`. I'll see how well that works, otherwise I'll do a naughty.

**Comment by martinpitt** [comment]
[TestPages.testHistory](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7033-8efd3fbe-20241026-063409-debian-testing-expensive-cockpit-project-cockpit/log.html#31-2) is similar -- there is no more /var/log/lastlog database, we need to consult `lastlog2` now.

**Review by martinpitt — APPROVED** [review]
Yay!

**Pull request merged**
