### PR TITLE
images: Restart `systemd-networkd` after upgrade

### LINKED ISSUE #1151: Image refresh for ubuntu-stable
Image refresh for ubuntu-stable
 * [ ] FAIL: image-refresh ubuntu-stable

### PR DESCRIPTION
**Pull request by marusak**
When systemd is updated this service may be in failed state and all
subsequent network-related operations fail.

Fixes #1151

 * [x] image-refresh debian-stable
 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-2004
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-1161-20200818-200101/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/bots/commits/image-refresh-debian-stable-20200818-201313

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-1161-20200818-201414/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/bots/commits/image-refresh-debian-testing-20200818-202727

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-1161-20200818-202727/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2004 done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-2004-20200818-204545

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-1161-20200818-204545/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-stable-20200818-210101

**Comment by marusak** [comment]
Pushed all images. Likely I'll have to drop ubuntu-2004 due to https://github.com/cockpit-project/bots/pull/1137 but at least I want to see if it worked in general.

**Comment by marusak** [comment]
ah [ubuntu-stable](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-1161-20200819-060625-53532b6a-ubuntu-stable-cockpit-project-cockpit/log.html) is affected as well :/ But the refresh worked and the VM is functional in general.

**Review by Gundersanne — APPROVED** [review]
Is there a bug report about this somewhere?

**Comment by marusak** [comment]
> Is there a bug report about this somewhere?

No. I should report it but every time when I think of the process how to report to debian/ubuntu I do anything to avoid it :)

Reproducer:
```
$ apt-get install systemd
...
Setting up systemd (246-2ubuntu1) ...
Installing new version of config file /etc/systemd/logind.conf ...
Installing new version of config file /etc/systemd/networkd.conf ...
Installing new version of config file /etc/systemd/resolved.conf ...
Installing new version of config file /etc/systemd/system.conf ...
Installing new version of config file /etc/systemd/user.conf ...
Job for systemd-networkd.service failed.
See "systemctl status systemd-networkd.service" and "journalctl -xe" for details.
Removing obsolete conffile /etc/dhcp/dhclient-enter-hooks.d/resolved ...

$ systemctl status systemd-networkd.service
* systemd-networkd.service - Network Service
     Loaded: loaded (/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2020-08-18 19:17:11 UTC; 16s ago
TriggeredBy: * systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
   Main PID: 5637 (code=exited, status=1/FAILURE)

Aug 18 19:17:11 ubuntu systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
Aug 18 19:17:11 ubuntu systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
Aug 18 19:17:11 ubuntu systemd[1]: Failed to start Network Service.
Aug 18 19:17:11 ubuntu systemd[1]: systemd-networkd.service: Scheduled restart job, restart counter is at 5.
Aug 18 19:17:11 ubuntu systemd[1]: Stopped Network Service.
Aug 18 19:17:11 ubuntu systemd[1]: systemd-networkd.service: Start request repeated too quickly.
Aug 18 19:17:11 ubuntu systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
Aug 18 19:17:11 ubuntu systemd[1]: Failed to start Network Service.
```
before that the service is fine and restarting it is also fine. Just right after systemd upgrade it ends up in failed state.

**Pull request merged**
