### PR TITLE
images: Enable FreeIPA on debian-testing

### PR DESCRIPTION
**Pull request by martinpitt**
After a long while, freeipa is back \o/

 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3132-20220324-055050/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20220324-061010

**Comment by martinpitt** [comment]
Note that we still need to actually unskip the FreeIPA tests, which I am doing in https://github.com/cockpit-project/cockpit/pull/17174 . This is mostly just a regular image refresh which checks against regressions.

[one failure here](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-3132-20220324-061357-dcff8edb-debian-testing-cockpit-project-cockpit/log.html#133-2), could be because of slow CentOS or an actual regression. I retry once to compare.

**Review by marusak — APPROVED** [review]
The tests are failing in https://github.com/cockpit-project/cockpit/pull/17174 but that does not need to skip this refresh, thanks!

**Pull request merged**
