### PR TITLE
Image refresh for rhel-7-9

### PR DESCRIPTION
**Pull request by marusak**
I could not push into #752, so this is duplicate.

### CODE REVIEW

**Comment by marusak** [comment]
Ech, one more: [https://logs.cockpit-project.org/logs/pull-774-20200420-074613-e66231a7-rhel-7-9-cockpit-project-cockpit-rhel-7.9/log.html#141-2]
```
Traceback (most recent call last):
  File "test/verify/check-storage-luks", line 159, in testClevisTang
    m.execute("systemctl reset-failed tangd-update; systemctl restart tangd-update")
  File "/build/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 345, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'systemctl reset-failed tangd-update; systemctl restart tangd-update' returned non-zero exit status 5.
```

I'll retry, but it failed in previous run as well.

**Comment by marusak** [comment]
I guess just adding 7.9 into:
```
if m.image not in ["rhel-8-2", "rhel-8-2-distropkg"]:
```
should do the trick?

**Comment by martinpitt** [comment]
@marusak: No, it's a real regression -- this [works fine in 7.8](https://logs.cockpit-project.org/logs/pull-636-20200329-154729-a1694181-rhel-7-8-cockpit-project-cockpit-rhel-7.8/log.html). So I suppose another bugzilla+naughty :/

**Comment by martinpitt** [comment]
@marusak: actually, if the test works *without* the hack, it would be even better, of course.

**Comment by marusak** [comment]
Sent https://github.com/cockpit-project/cockpit/pull/13930 so :crossed_fingers:

**Comment by martinpitt** [comment]
The tang fix landed, thanks! Unblocking/retrying.

**Pull request merged**
