### PR TITLE
Image refresh for rhel-9-2

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-2
 * [x] image-refresh rhel-9-2
 * [x] https://github.com/cockpit-project/cockpit/pull/17834

### CODE REVIEW

**Comment by jelly** [comment]
Possibly related or unrelated.
```
+ echo foobarfoo
+ realm join -vU admin cockpit.lan
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Successfully discovered: cockpit.lan
 * Required files: /usr/sbin/ipa-client-install, /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated and will be removed in a future release.
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
```

**Comment by jelly** [comment]
Ok, it seems the test wants to ssh into itself using the admin user, this works with a normal ssh command but we do it via `cockpit-ssh` and this gives:

```
Oct 21 06:57:15 x0.cockpit.lan cockpit-ssh[12289]: cockpit-ssh admin@x0.cockpit.lan: -1 couldn't connect: Socket error: Connection reset by peer 'x0.cockpit.lan' '22'
Oct 21 06:57:18 x0.cockpit.lan cockpit-ssh[12308]: cockpit-ssh admin@x0.cockpit.lan: -1 couldn't connect: Socket error: Connection reset by peer 'x0.cockpit.lan' '22'
Oct 21 06:57:35 x0.cockpit.lan cockpit-ssh[12328]: cockpit-ssh admin@x0.cockpit.lan: -1 couldn't connect: Socket error: Connection reset by peer 'x0.cockpit.lan' '22'
```

This works fine in CLI it seems:

```
[root@x0 ~]# /usr/libexec/cockpit-ssh admin@x0.cockpit.lan
74

{"command":"authorize","challenge":"*","cookie":"session123491666349936"}^C
```

**Comment by jelly** [comment]
```
[root@x0 ~]# G_MESSAGES_DEBUG=all /usr/libexec/cockpit-s
cockpit-session  cockpit-ssh
[root@x0 ~]# G_MESSAGES_DEBUG=all /usr/libexec/cockpit-ssh  x0.cockpit.lan
74

{"command":"authorize","challenge":"*","cookie":"session122241666355026"}1
3
cockpit-protocol-Message: 08:23:51.331: received invalid message without channel prefix
cockpit-ssh-Message: 08:23:51.332: cockpit-ssh did not receive valid message
(cockpit-ssh:12224): cockpit-ssh-DEBUG: 08:23:51.333: cockpit-ssh x0.cockpit.lan: host argument 'x0.cockpit.lan', host 'x0.cockpit.lan', username 'root', port '0'
[2022/10/21 08:23:51.333540, 3] ssh_config_parse_file:  Reading configuration data from /etc/libssh/libssh_client.config
[2022/10/21 08:23:51.333764, 3] local_parse_file:  Reading additional configuration data from /etc/crypto-policies/back-ends/libssh.config
[2022/10/21 08:23:51.337200, 3] local_parse_file:  Reading additional configuration data from /etc/ssh/ssh_config
[2022/10/21 08:23:51.338009, 3] local_parse_file:  Reading additional configuration data from /etc/ssh/ssh_config.d/04-ipa.conf
[2022/10/21 08:23:51.338382, 4] ssh_config_parse_line:  line 9: Processing Match keyword 'exec'
[2022/10/21 08:23:51.339707, 3] ssh_exec_shell:  Running command 'true'
[2022/10/21 08:23:51.345917, 4] ssh_exec_shell:  Command 'true' returned 0
[2022/10/21 08:23:51.346311, 4] ssh_match_exec:  Matched 'exec' command 'true' (rv=0)
[2022/10/21 08:23:51.346893, 3] local_parse_file:  Reading additional configuration data from /etc/ssh/ssh_config.d/50-redhat.conf
[2022/10/21 08:23:51.347285, 4] ssh_config_parse_line:  line 3: Processing Match keyword 'final'
[2022/10/21 08:23:51.347337, 2] ssh_config_parse_line:  line 3: Unsupported Match keyword 'final', skipping
[2022/10/21 08:23:51.347835, 4] ssh_config_parse_line:  line 3: Processing Match keyword 'all'
[2022/10/21 08:23:51.348146, 3] local_parse_file:  Reading additional configuration data from /etc/crypto-policies/back-ends/openssh.config
[2022/10/21 08:23:51.348535, 2] ssh_config_parse_line:  Unknown option: GSSAPIKexAlgorithms, line: 3
[2022/10/21 08:23:51.348949, 2] ssh_config_parse_line:  Unknown option: CASignatureAlgorithms, line: 6
[2022/10/21 08:23:51.349217, 2] ssh_config_parse_line:  Unknown option: RSAMinSize, line: 7
[2022/10/21 08:23:51.349724, 2] ssh_config_parse_line:  Unapplicable option: ForwardX11Trusted, line: 12
[2022/10/21 08:23:51.350086, 1] ssh_session_has_known_hosts_entry:  Cannot access file /root/.ssh/known_hosts
[2022/10/21 08:23:51.353719, 1] ssh_key_cmp:  key types don't match!
[2022/10/21 08:23:51.354328, 1] ssh_key_cmp:  key types don't match!
[2022/10/21 08:23:51.354867, 1] ssh_key_cmp:  key types don't match!
(cockpit-ssh:12224): cockpit-ssh-DEBUG: 08:23:51.355: cockpit-ssh x0.cockpit.lan: using known hosts file (null); host known: 1; connect to unknown hosts: 0
[2022/10/21 08:23:51.355948, 2] ssh_connect:  libssh 0.10.4 (c) 2003-2022 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please r
efer to COPYING file for information about your rights, using threading threads_pthread
[2022/10/21 08:23:51.356520, 2] ssh_socket_connect_proxycommand:  Executing proxycommand 'exec exec /usr/bin/sss_ssh_knownhostsproxy -p 22 x0.cockpit.lan'
[2022/10/21 08:23:51.357591, 2] ssh_socket_connect_proxycommand:  ProxyCommand connection pipe: [4,5]
[2022/10/21 08:23:51.358012, 1] socket_callback_connected:  Socket connection callback: 1 (0)
[2022/10/21 08:23:51.358596, 3] ssh_socket_unbuffered_write:  Enabling POLLOUT for socket
[2022/10/21 08:23:51.358871, 2] ssh_connect:  Socket connecting, now waiting for the callbacks to work
[2022/10/21 08:23:51.359259, 3] ssh_connect:  Actual timeout : 10000
[2022/10/21 08:23:51.360132, 4] ssh_socket_pollcallback:  Poll callback on socket 5 (POLLOUT ), out buffer 0
[2022/10/21 08:23:51.365127, 4] ssh_socket_pollcallback:  Poll callback on socket 5 (POLLIN POLLERR), out buffer 0
[2022/10/21 08:23:51.365323, 1] ssh_socket_exception_callback:  Socket exception callback: 2 (104)
[2022/10/21 08:23:51.365403, 1] ssh_socket_exception_callback:  Socket error: Connection reset by peer
[2022/10/21 08:23:51.365836, 4] ssh_socket_close:  Proxy command returned 127
[2022/10/21 08:23:51.366031, 3] ssh_connect:  current state : 9
cockpit-ssh-Message: 08:23:51.366: cockpit-ssh x0.cockpit.lan: -1 couldn't connect: Socket error: Connection reset by peer 'x0.cockpit.lan' '22'
82
```

**Comment by martinpitt** [comment]
Ah, so this is the same [cockpit-ssh/libssh issue](https://bugzilla.redhat.com/show_bug.cgi?id=2136824) as in the fedora-37 refresh in PR #3974

**Comment by mvollmer** [comment]
Let's remove the naughty for libssh here and hope the workaround fixes it.

**Comment by jelly** [comment]
> Let's remove the naughty for libssh here and hope the workaround fixes it.

Done!

**Review by mvollmer — APPROVED** [review]

**Pull request merged**
