### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240718-224952

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-4044e914-20240718-223840/log.html

**Comment by martinpitt** [comment]
Several 

> Error: COMMAND_FAILED: 'python-nftables' failed: internal:0:0-0: Error: Could not process rule: No such file or directory

And [machines fails](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6632-27163e13-20240718-225113-arch-cockpit-project-cockpit-machines/log.html#19-2) with

> GLib-GIO-ERROR **: 22:57:56.963: Settings schema 'org.gnome.system.proxy' is not installed

These both look like proper bugs in arch.

**Comment by jelly** [comment]
nftables has been fixed so it is worth re-refreshing. https://gitlab.archlinux.org/archlinux/packaging/packages/nftables/-/commit/f3ca10b4fceb652cad099c97d97f25a704aea89e

**Comment by martinpitt** [comment]
Thanks @jelly So yes, let's punt to the next round.

**Pull request closed without merging**
