### PR TITLE
Image refresh for centos-8-stream

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-8-stream
 * [x] image-refresh centos-8-stream

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20240423-225955

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-8-stream-3e1264fb-20240423-223716/log.html

**Comment by jelly** [comment]
@mvollmer I am not trusting our bots that this stratis issue is introduced with the image refresh:

So maybe this is just a flake?

Updated packages:
```
  c-ares (1.13.0-10.el8 -> 1.13.0-11.el8)
  cockpit (310.3-1.el8 -> 310.4-1.el8)
  cockpit-bridge (310.3-1.el8 -> 310.4-1.el8)
  cockpit-system (310.3-1.el8 -> 310.4-1.el8)
  cockpit-ws (310.3-1.el8 -> 310.4-1.el8)
  krb5-libs (1.18.2-26.el8 -> 1.18.2-27.el8)
  krb5-pkinit (1.18.2-26.el8 -> 1.18.2-27.el8)
  krb5-workstation (1.18.2-26.el8 -> 1.18.2-27.el8)
  libkadm5 (1.18.2-26.el8 -> 1.18.2-27.el8)
  libnghttp2 (1.33.0-5.el8 -> 1.33.0-6.el8.1)
  libtirpc (1.1.4-10.el8 -> 1.1.4-11.el8)
  libvirt-client (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-config-network (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-interface (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-network (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-nodedev (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-nwfilter (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-qemu (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-secret (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-storage (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-storage-core (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-storage-disk (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-storage-gluster (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-storage-iscsi (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-storage-iscsi-direct (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-storage-logical (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-storage-mpath (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-storage-rbd (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-driver-storage-scsi (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-daemon-kvm (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  libvirt-libs (8.0.0-23.module_el8+785+dceced31 -> 8.0.0-23.1.module_el8+1010+06b1482b)
  mock-core-configs (40.2-1.el8 -> 40.3-1.el8)
  nss (3.90.0-6.el8 -> 3.90.0-7.el8)
  nss-softokn (3.90.0-6.el8 -> 3.90.0-7.el8)
  nss-softokn-freebl (3.90.0-6.el8 -> 3.90.0-7.el8)
  nss-sysinit (3.90.0-6.el8 -> 3.90.0-7.el8)
  nss-tools (3.90.0-6.el8 -> 3.90.0-7.el8)
  nss-util (3.90.0-6.el8 -> 3.90.0-7.el8)
  pcp (5.3.7-19.el8 -> 5.3.7-20.el8)
  pcp-conf (5.3.7-19.el8 -> 5.3.7-20.el8)
  pcp-libs (5.3.7-19.el8 -> 5.3.7-20.el8)
  pcp-selinux (5.3.7-19.el8 -> 5.3.7-20.el8)
  sos (4.6.1-1.el8 -> 4.7.0-1.el8)
```

**Comment by martinpitt** [comment]
@jelly backporting https://github.com/cockpit-project/cockpit/commit/58f7d6a9c949c63186312c544c5c48e8599c7be2 to rhel-8 branch might also help. I haven't checked the naughty

**Comment by jelly** [comment]
> @jelly backporting [cockpit-project/cockpit@58f7d6a](https://github.com/cockpit-project/cockpit/commit/58f7d6a9c949c63186312c544c5c48e8599c7be2) to rhel-8 branch might also help. I haven't checked the naughty

Sounds like a good plan, shall I just attempt that?

**Comment by jelly** [comment]
Opened https://github.com/cockpit-project/cockpit/pull/20373 and the bots are unhappy.

**Review by martinpitt — APPROVED** [review]
Not a regression, this happens on the current image as well, also see https://github.com/cockpit-project/cockpit/pull/20393. We don't need to track this in *three* places, so let's wave this through. I'm dropping testing of c8s anyway.

**Pull request merged**
