### PR TITLE
Image refresh for rhel-8-5

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-5
 * [x] image-refresh rhel-8-5
 * [x] https://github.com/cockpit-project/cockpit/pull/16049

### CODE REVIEW

**Comment by martinpitt** [comment]
Yay, an exciting new SELinux regression:

    audit: type=1400 audit(1625053959.034:4): avc:  denied  { getattr } for  pid=2160 comm="systemctl" name="/" dev="vda3" ino=128 scontext=system_u:system_r:cockpit_ws_t:s0 tcontext=system_u:object_r:fs_t:s0 tclass=filesystem permissive=0

It felt familar, but it's different from https://bugzilla.redhat.com/show_bug.cgi?id=1967125.

**Comment by martinpitt** [comment]
I reported https://bugzilla.redhat.com/show_bug.cgi?id=1979182 and added it as an allowed message.

**Comment by martinpitt** [comment]
Weird [TestConnection.testBasic](https://logs.cockpit-project.org/logs/pull-2156-20210705-072732-dad850fb-rhel-8-5-cockpit-project-cockpit/log.html#12-2) failure, retrying once to compare.

**Comment by martinpitt** [comment]
That test case is still broken, image regression. Back to needswork.

**Comment by martinpitt** [comment]
That's the problem:

    systemd-coredump[17931]: Resource limits disable core dumping for process 17663 (systemd-hostnam)

So the test's "kill hostnamed and expect a core dump file" is failing.

Simple reproducer with just pure bots (`./vm-run rhel-8-5`):

    systemctl start systemd-hostnamed; pkill -e -SEGV systemd-hostnam

It's not `ulimit -c`, that's `unlimited` on both images. Digging deeper..

**Comment by martinpitt** [comment]
Sent a cockpit PR to fix the test, blocking.

**Comment by allisonkarlitskaya** [comment]
> Sent a cockpit PR to fix the test, blocking.

Merged.  Retrying the test.

**Review by allisonkarlitskaya — APPROVED** [review]

**Pull request merged**
