### PR TITLE
images: Explicitly install systemd into arch build root

### LINKED ISSUE #6736: Image refresh for arch
Image refresh for arch
 * [ ] image-refresh arch

### PR DESCRIPTION
**Pull request by martinpitt**
It's not there any more by default (only systemd-libs), but cockpit build-depends on it.

Fixes #6736

 * [x] https://archlinux.org/packages/extra-testing/any/cloud-init/ 24.2-1 needs to hit Extras
 * [x] https://america.mirror.pkgbuild.com/images/latest/ needs a fresh build to pick up that cloud-init fix (20240815 is still broken - should happen on Sept 1)
 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-cdf70093-20240816-060838/log.html

**Comment by martinpitt** [comment]
WTH happened here? It downloaded a very recent cloud image (20240815.255016) and then wants to download 285 (:exclamation:) package updates?

Total Installed Size:  1390.65 MiB
Net Upgrade Size:      1325.37 MiB

No wonder it exceeds the available disk space.

Let's try this again next week.

**Comment by jelly** [comment]
cloud-init broke with the new btrfs utils which version now emits config options. The package is being updated which hopefully fixes the issue.

```
2024-08-19 17:17:15,250 - subp.py[DEBUG]: Running command ['btrfs', '--version'] with allowed return codes [0] (shell=False, capture=True
)
2024-08-19 17:17:15,253 - handlers.py[DEBUG]: finish: init-network/config-resizefs: FAIL: running config-resizefs with frequency always
2024-08-19 17:17:15,253 - util.py[WARNING]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.12/sit
e-packages/cloudinit/config/cc_resizefs.py'>) failed
2024-08-19 17:17:15,253 - util.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.12/site-
packages/cloudinit/config/cc_resizefs.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/cloudinit/config/modules.py", line 270, in _run_modules
    ran, _r = cc.run(
              ^^^^^^^
  File "/usr/lib/python3.12/site-packages/cloudinit/cloud.py", line 71, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cloudinit/helpers.py", line 156, in run
    results = functor(**args)
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cloudinit/config/cc_resizefs.py", line 327, in handle
    resize_cmd = resizer(resize_what, devpth)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cloudinit/config/cc_resizefs.py", line 81, in _resize_btrfs
    system_btrfs_ver = util.Version.from_str(
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cloudinit/util.py", line 3145, in from_str
    return cls(*(list(map(int, version.split(".")))))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '1\n-EXPERIMENTAL -INJECT -STATIC +LZO +ZSTD +UDEV +FSVERITY +ZONED CRYPTO=libgcrypt'
2024-08-19 17:17:15,254 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.12/site-p
ackages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2024-08-19 17:17:15,254 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2024-08-19 17:17:15,254 - helpers.py[DEBUG]: config-mounts already ran (freq=once-per-instance)
2024-08-19 17:17:15,254 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts previously ran
```

**Comment by martinpitt** [comment]
Ah, thanks @jelly . So I interpret this as "it doesn't make sense to retry just yet".

Any idea why there's such a ginormous amount of updates?

**Comment by jelly** [comment]
> Ah, thanks @jelly . So I interpret this as "it doesn't make sense to retry just yet".

Yes

> Any idea why there's such a ginormous amount of updates?

That I don't know, as image-diff does not work it's not easy to debug.

**Comment by jelly** [comment]
A fix is in https://archlinux.org/packages/extra-testing/any/cloud-init/ we need to wait till it hits [extra].

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-7a22d0e4-20240824-150400/log.html

**Comment by martinpitt** [comment]
```
Total Download Size:    332.70 MiB
Total Installed Size:  1517.04 MiB
Net Upgrade Size:      1325.11 MiB

:: Proceed with installation? [Y/n] error: Partition / too full: 90432 blocks needed, 59048 blocks free
error: failed to commit transaction (not enough free disk space)
```

Meh -- https://archlinux.org/packages/extra/any/cloud-init/ is the fixed version, in Extras. But the refresh still both has the "too small disk" *and* "gargantuan update from fresh daily cloud image" problems.

**Comment by jelly** [comment]
> ```
> Total Download Size:    332.70 MiB
> Total Installed Size:  1517.04 MiB
> Net Upgrade Size:      1325.11 MiB
> 
> :: Proceed with installation? [Y/n] error: Partition / too full: 90432 blocks needed, 59048 blocks free
> error: failed to commit transaction (not enough free disk space)
> ```
> 
> Meh -- https://archlinux.org/packages/extra/any/cloud-init/ is the fixed version, in Extras. But the refresh still both has the "too small disk" _and_ "gargantuan update from fresh daily cloud image" problems.

Sounds like we need to wait on a new release image? That should be every two weeks so soon (enough).

**Comment by martinpitt** [comment]
@jelly that can't be the whole story, though. The [last refresh](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-02e1524d-20240806-223825/log.html) had a similarly-sized update (Net Upgrade Size: 1323.45 MiB, 293 packages), and fit well into the 6.6 GB of free space on the hard disk. So my suspicion is that cloud-init resizing is still broken.

**Comment by martinpitt** [comment]
Oh nevermind, I see what you mean -- the fixed cloud-init must be part of the built VM image, it doesn't make sense to update *to* the fixed version from an existing image.

**Comment by martinpitt** [comment]
There finally is a new cloud image from Sep 01, let's try again.

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20240901-232609

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-72aed1e1-20240901-231559/log.html

**Comment by martinpitt** [comment]
Progress! There is a [single qemu crash](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6740-fb3e9e5d-20240901-232854-arch-cockpit-project-cockpit-machines/log.html#9) in machines tests, and it is "just" an unexpected message. Retrying once to get two logs for comparison.

**Comment by jelly** [comment]
Woohoo!

**Review by jelly — APPROVED** [review]

**Pull request merged**
