### PR TITLE
images: Rename debian.bootstrap

### PR DESCRIPTION
**Pull request by martinpitt**
There is nothing Debian specific about it, and we now use it for CentOS
as well.

 * [x] image-refresh debian-stable

### CODE REVIEW

**Comment by martinpitt** [comment]
Rebuilding debian-stable just to prove that I didn't mess up anything.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-aws-tasks.
Log: https://logs.cockpit-project.org/logs/image-refresh-1260-20200925-110606/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/bots/commits/image-refresh-debian-stable-20200925-111919

**Comment by martinpitt** [comment]
.. and of course I made a typo in the commit message. Let's fix it on squash&merge (I don't plan to land this debian-stable rebuild, building it worked fine).

**Comment by martinpitt** [comment]
But then again, why not. I fixed the typo and included the image.

**Review by mvollmer — APPROVED** [review]
Thanks!

**Pull request merged**
