### PR TITLE
Image refresh for rhel-9-0

### PR DESCRIPTION
**Pull request by cockpituous**
Blocked:
 - [ ] https://bugzilla.redhat.com/show_bug.cgi?id=1966125

Image refresh for rhel-9-0
 * [x] image-refresh rhel-9-0

### CODE REVIEW

**Comment by marusak** [comment]
The new image seems to be usable.

**Comment by martinpitt** [comment]
The new image breaks stuff left and right, but there is at least a chance that [cockpit-machines](https://logs.cockpit-project.org/logs/pull-2011-20210524-082032-cb99d08e-rhel-9-0-cockpit-project-cockpit-machines/log.html) failures are better now, since it moved from static XML to virt-install. Retrying that one.

**Comment by mvollmer** [comment]
Let's make another new image.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-2011-20210602-073131/

**Comment by mvollmer** [comment]
During image-prepare:
```
+ firewall-cmd --add-service=cockpit --permanent
ERROR:dbus.proxies:Introspect error on :1.5:/org/fedoraproject/FirewallD1: dbus.exceptions.DBusException: org.freedesktop.PolicyKit1.Error.Failed: Action org.fedoraproject.FirewallD1.info is not registered
Error: Action org.fedoraproject.FirewallD1.info is not registered
```

**Comment by mvollmer** [comment]
The polkit actions for firewalld are installed, but only as *.choice:

```
# ls /usr/share/polkit-1/actions/org.fedoraproject.FirewallD1.* 
/usr/share/polkit-1/actions/org.fedoraproject.FirewallD1.desktop.policy.choice
/usr/share/polkit-1/actions/org.fedoraproject.FirewallD1.server.policy.choice
```

The symlink to make the choice is missing.

**Comment by mvollmer** [comment]
> The symlink to make the choice is missing.

https://bugzilla.redhat.com/show_bug.cgi?id=1966125, let's wait for that fix to land.

**Comment by martinpitt** [comment]
That bz fix landed, let's start afresh.

**Pull request closed without merging**
