### PR TITLE
Image refresh for fedora-31

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-31
 * [x] image-refresh fedora-31

### CODE REVIEW

**Comment by marusak** [comment]
alibaba for weldr fails with:
```
:: [ 17:16:24 ] :: [   INFO   ] :: [1;31mERROR: SDK.ServerError
ErrorCode: OperationDenied.NoStock
Recommend: 
RequestId: 806EECD4-BB02-49C5-8032-51DD745A6D42
Message: The resource is out of stock in the specified zone. Please try other types, or choose other regions and zones.
```
@atodorov is there something we can do about this?

**Comment by atodorov** [comment]
@marusak can you restart this job a few times and see if it keeps failing ? 

This happens when we try the RunInstances command using the us-east-1 region. I am not able to find any particular information what this error message means but it looks like the availability zone in this region may be out of capacity.

**Comment by martinpitt** [comment]
[retried](https://logs.cockpit-project.org/logs/pull-701-20200401-143516-92ed6896-fedora-31-alibaba-weldr-lorax/log.html), still says "out of stock". @atodorov : Do you know if the cleanup of unused resources is working correctly? I. e. is the CI just hogging old instances perhaps?

**Comment by martinpitt** [comment]
Let's not block the image refresh on the alibaba "out of stock" issue, that's obviously unrelated.

**Comment by atodorov** [comment]
> Do you know if the cleanup of unused resources is working correctly? 

I don't really know. The latest changes were in https://github.com/weldr/lorax/pull/842

> I. e. is the CI just hogging old instances perhaps?

In the case of Alibaba all instances are started with a timestamp limit when the vendor should recycle them. That's a feature of Alibaba cloud itself. If anything that should be the most robust cleanup compared to all other vendors.

**Pull request merged**
