### PR TITLE
images: Fix RHEL 8 compose URLs

### PR DESCRIPTION
**Pull request by martinpitt**
The /rhel-8/ paths are a backwards compatiblity shim that is out of date
on some mirrors, so use the canonical path underneath /nightly/ instead.

 * [x] image-refresh rhel-8-3
 * [x] image-refresh rhel-8-4
 * [ ] Fix candlepin failure on missing `python` (unrelated to this refresh): https://github.com/candlepin/subscription-manager/pull/2380
 * [ ] Fix [composer rhel-8 branch](https://logs.cockpit-project.org/logs/pull-1519-20210105-115652-c8de93f2-rhel-8-3-firefox-osbuild-cockpit-composer-rhel-8/log.html)
 * [ ] Confirm with EXD team that these are really the better paths now: https://projects.engineering.redhat.com/browse/RHELCMP-3679

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-1519-20210105-083737/

**Comment by martinpitt** [comment]
I did that a while ago in https://github.com/rhinstaller/kickstart-tests/commit/5951452f51c2 after spending an hour of confusion why an image build worked somewhere in Europe (eng.brq) but not in the US (eng.bos) -- or possibly vice versa. Either way, it's better to use the official non-deprecated URLs.

**Comment by cockpituous** [comment]
image-refresh rhel-8-3 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-3-20210105-085656

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-1519-20210105-085656/

**Comment by martinpitt** [comment]
Hmm,  our latest rhel-8-3 refresh (commit eea42e8e7af04208f1e76d441f851d0d41c71f4d) was from one month ago, and the latest automatic one from Oct 8. I think the presence of #1425 prevents further automatic updates.

**Comment by martinpitt** [comment]
[This candlepin](https://logs.cockpit-project.org/logs/pull-1519-20210105-085631-5d140862-rhel-8-3-candlepin-subscription-manager/log.html) failure is unrelated to this refresh as it happens with the *current* image. But still that needs to be addressed.

**Comment by cockpituous** [comment]
image-refresh rhel-8-4 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-4-20210105-091717

**Comment by martinpitt** [comment]
@henrywang : Could you please have a quick look at the [TestSource.testBasic failure](https://logs.cockpit-project.org/logs/pull-1519-20210105-103332-c8de93f2-rhel-8-3-firefox-osbuild-cockpit-composer-rhel-8/log.html#22-2)? Is that a known flake?

**Comment by martinpitt** [comment]
I just got word from EXD that the current URLs are really the canonical ones. What we saw a month ago was a broken mirroring, and the old compat links just happened to "work".

**Pull request closed without merging**
