### PR TITLE
Image refresh for fedora-37

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-37
 * [x] image-refresh fedora-37

### CODE REVIEW

**Comment by martinpitt** [comment]
This now needs to be installed explicitly on the image:
```
Removed:
  gettext (0.21-19.0.20220203.fc37)
```

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-4077-20221122-154848/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-4077-20221122-154848/

**Comment by martinpitt** [comment]
Ah, and of course /development → /release

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-4077-20221122-155454/

**Comment by cockpituous** [comment]
image-refresh fedora-37 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-37-20221122-161703

**Review by jelly — APPROVED** [review]
Danke!

**Comment by martinpitt** [comment]
Yay, that was the last outstanding image refresh.

**Pull request merged**
