### PR TITLE
Revert "images: Work around disabled subscription-manager on rhel-8-4"

### PR DESCRIPTION
**Pull request by martinpitt**
This reverts commit 56736a97ef576bdffc2867ffd8a8c6a39c0538ea.

The file having enabled=0 in a default qcow image was intended after
all. This situation needs to be handled properly by cockpit and
subscription-manager.

 * [x] image-refresh rhel-8-4
 * [x] Fix build failure of cockpit-podman (unrelated): https://github.com/cockpit-project/cockpit-podman/pull/680
 * [x] Fix handling enabled=0 in cockpit: https://github.com/cockpit-project/cockpit/pull/15401
 * [x] Add naughty for subscription-manager-cockpit: [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1930037), known issue #1711
 * [x] Fix cockpit [journal test  regressions](https://logs.cockpit-project.org/logs/pull-1710-20210223-100303-2bb8434e-rhel-8-4-cockpit-project-cockpit/log.html#284-1): https://github.com/cockpit-project/cockpit/pull/15406

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-1710-20210223-084646/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1710-20210223-084646/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-1710-20210223-083737/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1710-20210223-083737/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-1710-20210223-084040/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1710-20210223-084040/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-1710-20210223-084343/

**Comment by cockpituous** [comment]
image-refresh rhel-8-4 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-4-20210223-085959

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
