### PR TITLE
Image refresh for rhel-8-5

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-5
 * [x] image-refresh rhel-8-5
 * [x] https://github.com/cockpit-project/cockpit/pull/15743

### CODE REVIEW

**Comment by marusak** [comment]
distropkg needs update for language modal.

**Comment by marusak** [comment]
Sent https://github.com/cockpit-project/cockpit/pull/15743

**Comment by marusak** [comment]
Repushing to cleanup failed tests

**Comment by marusak** [comment]
Unexpected message. Likely flake, but lets address it.
```
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
org.fedoraproject.Setroubleshootd: couldn't introspect /org/fedoraproject/Setroubleshootd: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

**Comment by marusak** [comment]
We already have pattern for it, just slightly different:
```
elf.allow_journal_messages(".*couldn't introspect /org/fedoraproject/Setroubleshootd: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Remote peer disconnected.*")

```

I'll send PR for it.

**Comment by marusak** [comment]
Sent https://github.com/cockpit-project/cockpit/pull/15747

**Comment by martinpitt** [comment]
Retrying after landing the above cockpit PR. Thanks!

**Review by marusak — APPROVED** [review]

**Pull request merged**
