### PR TITLE
Image refresh for ubuntu-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for ubuntu-stable
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by martinpitt** [comment]
Uh, what? ubuntu-stable has SELinux enabled now??

**Comment by allisonkarlitskaya** [comment]
1) I've rebuilt the image locally and I can't get the fail

2) I don't think this is related to selinux in any way.  The failure code is 32, which is documented in `mount(8)` to mean 

```
       32     mount failure
```

**Comment by martinpitt** [comment]
@allisonkarlitskaya : I mean that now `if selinuxenabled` obviously is true, and that's unexpected. So it is somehow related. Would be interesting to investigate that locally?

**Comment by marusak** [comment]
https://logs.cockpit-project.org/logs/pull-14876-20201112-093728-21a2742b-rhel-8-3/log.html#305-2 happens the same issue also on other OSes like 8.3

**Comment by allisonkarlitskaya** [comment]
> @allisonkarlitskaya : I mean that now `if selinuxenabled` obviously is true, and that's unexpected. So it is somehow related. Would be interesting to investigate that locally?

I think maybe you read the code incorrectly

```
if selinuxenabled 2>/dev/null; then chcon --reference /proc/cmdline /run/cmdline; fi && mount --bind /run/cmdline /proc/cmdline
```

ie:
```
if selinuxenabled 2>/dev/null; then chcon --reference /proc/cmdline /run/cmdline; fi
```

followed by

```
mount --bind /run/cmdline /proc/cmdline
```

(note: `if`/`then`/`fi` branch returns `0` in case the condition is false, or the return value of the `then` branch, otherwise, and that seems to be what was intended here).

So, the error 32 is definitely coming either from `chcon` (which is extremely unlikely) or from `mount`, irrespective of selinux (which is extremely likely).

**Comment by allisonkarlitskaya** [comment]
Put another way:

```
[lis@x1 ~]$ if false; then true; fi && mount /x /y
mount: /y: mount point does not exist.
[lis@x1 ~]$ echo $?
32
```

**Comment by martinpitt** [comment]
@allisonkarlitskaya : Of course you are right, I missed the `;fi`. Brown paperbag totally! :blush:

**Comment by martinpitt** [comment]
So, this does seem to be some valid race condition, but not specific to this refresh. Retrying test.

**Review by allisonkarlitskaya — APPROVED** [review]

**Pull request merged**
