### PR TITLE
images: Get newest insights egg 3.0.156 into rhel-8-2

### PR DESCRIPTION
**Pull request by cockpituous**
This has support for `--check-results`.

 * [x] image-refresh rhel-8-2

### CODE REVIEW

**Comment by mvollmer** [comment]
The expected egg has been installed!

```
+ insights-client --version
Client: 3.0.13-1
Core: 3.0.156-1
```

**Comment by martinpitt** [comment]
@mvollmer: Note that you still need to commit the new image here.

**Comment by mvollmer** [comment]
> @mvollmer: Note that you still need to commit the new image here.

Really?  This started out as a issue and the bots have turned it into a PR with their image refresh commit, no?

**Comment by martinpitt** [comment]
@mvollmer: Oh, sorry, of course! I thought that this would change the build scripts, but of course we already did that.

**Pull request merged**
