### PR TITLE
Image refresh for centos-10

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-10
 * [ ] image-refresh centos-10

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20240829-105647

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-e000e112-20240829-103948/log.html

**Comment by martinpitt** [comment]
NOOOOOOooooo....! This *did* get kernel 6.11.0-0.rc5.21.el10, and yet this effing **still** breaks logging. Back to square one in https://issues.redhat.com/browse/RHEL-56025

**Comment by jelly** [comment]
> NOOOOOOooooo....! This _did_ get kernel 6.11.0-0.rc5.21.el10, and yet this effing **still** breaks logging. Back to square one in https://issues.redhat.com/browse/RHEL-56025

Hmm that jira issue mentions: 

> upstream kernel reverted the pidfd patch, that should be in -rc5

**Comment by martinpitt** [comment]
@jelly Yes, and [in this comment](https://issues.redhat.com/browse/RHEL-56025?focusedId=25442300&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25442300) I tested 6.11.0-0.rc5.22.el10 and it passed. That's the reason for my "NOoooo.." -- either that is a different kernel build, or something else broke now (systemd?)

**Comment by jelly** [comment]
> @jelly Yes, and [in this comment](https://issues.redhat.com/browse/RHEL-56025?focusedId=25442300&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25442300) I tested 6.11.0-0.rc5.22.el10 and it passed. That's the reason for my "NOoooo.." -- either that is a different kernel build, or something else broke now (systemd?)

Interestingly https://github.com/torvalds/linux/commit/3b5bbe798b2451820e74243b738268f51901e7d0 is still in rc5

**Comment by jelly** [comment]
https://gitlab.com/redhat/centos-stream/rpms/kernel/-/commit/64f7da175968ef6cdddde66688e760b9c6b94e8c should have the revert.

Also rc6 was just tagged, so we can also sit this one out.

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-2f9c8ab6-20240905-075938/log.html

**Pull request closed without merging**
