### PR TITLE
Image refresh for rhel-7-9

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-7-9
 * [x] image-refresh rhel-7-9
 * Requires #3671 , rebase after that

### CODE REVIEW

**Comment by martinpitt** [comment]
[missing rsync](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3669-20220729-063527-5104c6c6-rhel-7-9-cockpit-project-cockpit-rhel-7.9/log.html#163), fallout from commit d4489db8cee. Need to install that into the image.

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-6.
Log: https://logs.cockpit-project.org/logs/image-refresh-3669-20220729-071616/

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-7-9-20220729-073819

**Comment by martinpitt** [comment]
Ah, that was bogus -- we need rsync on the `openshift` image, not on the rhel-7-9 image; or an scp fallback. So we can revert that commit/image refresh. We haven't refreshed the openshift image in literally years, not sure if that even still works. I'll have a quick look.

**Comment by martinpitt** [comment]
Surprisingly, refreshing the openshift image *almost* worked. I sent #3671 with a little fix, blocking on that.

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-15.
Log: https://logs.cockpit-project.org/logs/image-refresh-3669-20220729-135050/

**Comment by martinpitt** [comment]
Fixed openshift landed, rebased.

**Pull request merged**
