### PR TITLE
images: Disable expensive OS maintenance jobs on Debian images

### PR DESCRIPTION
**Pull request by martinpitt**
These days, apt's daily index updating is done by
apt-daily-upgrade.timer, disable that as well.

Also disable man-db and fstrim, these take a lot of I/O bandwidth which
significantly slow down tests.

 * [x] image-refresh debian-stable
 * [x] image-refresh ubuntu-stable
 * [x] image-refresh ubuntu-2004

### CODE REVIEW

**Comment by martinpitt** [comment]
Leaving out debian-testing for now, that's being refreshed in #1072.

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-1077-20200717-115050/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/bots/commits/image-refresh-debian-stable-20200717-120707

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-1077-20200717-120707/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-stable-20200717-122626

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-1077-20200717-122626/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1077-20200717-122626/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-1077-20200717-135555/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2004 done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-2004-20200717-141212

**Comment by martinpitt** [comment]
@marusak: yes, that was on purpose, as that isn't enabled/disabled by itself -- it gets activated through the .timer.

**Pull request merged**
