### PR TITLE
images: Add rsync to Debian images

### PR DESCRIPTION
**Pull request by martinpitt**
This will allow us to replace the deprecated `scp` in our bots API. All
other images already have rsync installed.

----

 * [x] image-refresh debian-stable
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-3664-20220726-072727/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20220726-075209

**Comment by cockpituous** [comment]
image-refresh in progress on 4-fedora.
Log: https://logs.cockpit-project.org/logs/image-refresh-3664-20220726-075252/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20220726-081819

**Comment by martinpitt** [comment]
Urgh, debian-testing has a regression with its NFS-server.

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-5.
Log: https://logs.cockpit-project.org/logs/image-refresh-3664-20220726-100606/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20220726-102302

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
