### PR TITLE
images: Fix invalid reloading of logind on old Debian/Ubuntu images

### LINKED ISSUE #7120: Image refresh for debian-stable
Image refresh for debian-stable
 * [ ] FAIL: image-refresh debian-stable

### LINKED ISSUE #7128: Image refresh for ubuntu-2204
Image refresh for ubuntu-2204
 * [ ] FAIL: image-refresh ubuntu-2204

### PR DESCRIPTION
**Pull request by martinpitt**
The hack in commit 0e29a8a44fe does not apply to Debian 12 and Ubuntu 22.04. systemd-logind.service cannot be reloaded there.

Fixes #7120
Fixes #7128

 * [x] image-refresh debian-stable
 * [x] image-refresh ubuntu-2204

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20241124-095922

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-debian-stable-59096181-20241124-094703/log.html

**Comment by cockpituous** [comment]
image-refresh ubuntu-2204 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2204-20241124-101239

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-2204-59096181-20241124-095928/log.html

**Review by jelly — APPROVED** [review]

**Pull request merged**
