### PR TITLE
images: drop reflector removal from Arch Linux image

### PR DESCRIPTION
**Pull request by jelly**
The new 20220104 image no longer ship with reflector. See the refresh log here https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20230105-113939.log

 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20230105-125916

**Comment by martinpitt** [comment]
Nice, thanks! There's still two test failures, apparently stratis is broken:

    stratisd version 3.3.0 does not meet stratis version requirements; the version must be at least 3.4.0 and no more than 4.0.0. stratis can execute only the subset of its commands that do not require stratisd. 

This probably requires an Arch bug report and a naughty.

And this `firewall-cmd --zone=public --change-interface eth0 --permanent` failure, which  looks very shallow ("FirewallD is not running"). That seems fixable in our tests?

**Comment by jelly** [comment]
> 



> Nice, thanks! There's still two test failures, apparently stratis is broken:
> 
> ```
> stratisd version 3.3.0 does not meet stratis version requirements; the version must be at least 3.4.0 and no more than 4.0.0. stratis can execute only the subset of its commands that do not require stratisd. 
> ```

Interesting, guess who updated stratis-cli!
 
> This probably requires an Arch bug report and a naughty.

Will investigate.

> And this `firewall-cmd --zone=public --change-interface eth0 --permanent` failure, which looks very shallow ("FirewallD is not running"). That seems fixable in our tests?

Interesting, locally I got a different error.

**Comment by jelly** [comment]
I updated stratisd in the Arch repository so we can refresh again and the stratisd tests should work.

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20230105-210940

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20230105-210909.log

**Comment by cockpituous** [comment]
image-refresh arch done: https://github.com/cockpit-project/bots/commits/image-refresh-arch-20230105-215958

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20230105-215959.log

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
