### PR TITLE
images: install strace and ltrace on debian

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
strace and ltrace are extremely useful tools, and quite small.  Let's
have them in our images.

 * [x] image-refresh debian-stable
 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-1804
 * [ ] FAIL: image-refresh ubuntu-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-203-20191103-131818/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-203-20191103-131818/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-203-20191103-131919/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/bots/commits/image-refresh-debian-stable-20191103-135656

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-203-20191103-135757/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/bots/commits/image-refresh-debian-testing-20191103-143333

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-203-20191103-143333/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1804 done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-1804-20191103-150101

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-fqpbg.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-203-20191103-150202/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-203-20191103-150202/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-203-20191103-195454/

**Comment by martinpitt** [comment]
ubuntu-stable [failed](https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-203-20191103-150202/log) with a pcp startup error. Let's see if that was just a temporary glitch. I deleted the invalid "debian" image task.

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-203-20191103-195454/

**Comment by martinpitt** [comment]
pcp failure is persistent, this needs investigation.

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-203-20191106-185050/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-01.
Log: https://209.132.184.41:8493/logs/image-refresh-203-20191106-185050/

**Comment by allisonkarlitskaya** [comment]
We seem to have lost a couple of images.  Kicking them off again, and I'll try to get them onto the branch quicker this time.

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/bots/commits/image-refresh-debian-stable-20191106-191616

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-203-20191106-191616/

**Comment by allisonkarlitskaya** [comment]
ubuntu-stable build was successful locally.  I guess i'll try one more time...

**Comment by cockpituous** [comment]
image-refresh ubuntu-1804 done: https://github.com/cockpituous/bots/commits/image-refresh-ubuntu-1804-20191106-194747

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-203-20191107-063434/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-203-20191107-063434/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-64f2w.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-203-20191107-093636/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-203-20191107-093636/

**Comment by Gundersanne** [comment]
re: ubuntu-stable

This is a bug which hasn't been fixed yet, figuring out a workaround https://bugs.launchpad.net/ubuntu/+source/pcp/+bug/1850281

**Pull request merged**
