### PR TITLE
machine: Allow ebtables crash on Ubuntu 20.04 as well

### PR DESCRIPTION
**Pull request by martinpitt**
Seen in https://logs.cockpit-project.org/logs/pull-16393-20210924-055006-c0468b60-ubuntu-2004/log.html#234

### CODE REVIEW

**Review by marusak — DISMISSED** [review]
Danke :)

**Comment by martinpitt** [comment]
Heh, and the run here [failed](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-2451-20210924-070856-4b1b8cde-ubuntu-2004-cockpit-project-cockpit/log.html#49) with yet another unrelated crash. This is known issue #2248, but here systemd-coredump can't figure out a proper stack trace.

While I'm at it, I fixed that as well.

**Comment by martinpitt** [comment]
Fun fact: It's not possible to have a line like `#0 ...` (part of the stack trace) in a git commit message. I massaged the commit message now to drop the `#` and still be legible.

**Comment by marusak** [comment]
> It's not possible to have a line like #0 ... (part of the stack trace) in a git commit message.

What happens when you do it? Is it dangerous as [googling `google`](https://www.youtube.com/watch?v=OqxLmLUT-qc)?

**Review by marusak — APPROVED** [review]
Danke!

**Comment by martinpitt** [comment]
> What happens when you do it?

Linus will personally come to your home and LART you!

Nah, it's just that lines starting with `#` are treated as comments and be removed from the commit message. I had a good four rounds of "WTF?" on my copy&paste skills before I realized :grin:

**Pull request merged**
