### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by marusak** [comment]
Failed twice on [testTally](https://logs.cockpit-project.org/logs/pull-1569-20210122-073755-683ff398-debian-testing-cockpit-project-cockpit/log.html#76-2). Screenshot shows `Module is unknown`. Needs work.

**Comment by marusak** [comment]
It probably uses faillock now:
```
        if m.image.startswith('debian') or m.image.startswith('ubuntu'):        
            module = 'pam_tally2'                                               
            logfile = lambda user: '/var/log/tallylog'                          
        elif m.image.startswith('rhel') or m.image.startswith('fedora') or m.image.startswith('cent'):
            module = 'faillock'                                                 
            logfile = lambda user: '/var/run/faillock/' + user                  
        else:                                                                   
            raise ValueError('unexpected image name', m.image)  
```

**Comment by marusak** [comment]
ok, it surely is not using faillock, but there has been an update in pam (1.3.1-5 -> 1.4.0-2)

**Comment by marusak** [comment]
Hmm, is there `faillock` command available on debian testing? :thinking: 
https://packages.debian.org/search?searchon=contents&keywords=faillock&mode=filename&suite=testing&arch=any

**Comment by marusak** [comment]
Ok, I am admitting I have no idea how this should work :)
Maybe @allisonkarlitskaya can help as author of https://github.com/cockpit-project/cockpit/pull/13962 which introduced this test.

**Comment by allisonkarlitskaya** [comment]
This is a debian packaging bug.  The `libpam-modules-bin` package dropped the tally helper programs (`pam_tally` and `pam_tally2`) and didn't add the `faillock` helper, which it should have done with the port from tally2 to faillock.

To be honest, I'm surprised to see this port done in this manner.  This is going to break people's systems on updates, if they have tally in their pam config and it suddenly disappears...

The changelog mentions
  * Drop pam_tally and pam_tally2 modules, which have been deprecated
    upstream in favor of pam_faillock.  Closes: #569746, LP: #772121.

The referenced bugs seem unrelated to the change...

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=569746
https://bugs.launchpad.net/ubuntu/+source/pam/+bug/772121

I'll talk to Steve

**Comment by allisonkarlitskaya** [comment]
→ #1594

**Pull request closed without merging**
