### PR TITLE
images: Fix depmod call for updated kernels

### LINKED ISSUE #3699: Image refresh for ubuntu-2204
Image refresh for ubuntu-2204
 * [ ] image-refresh ubuntu-2204

### PR DESCRIPTION
**Pull request by martinpitt**
Sometimes the dist-upgrade installs a new kernel ABI version. The extra
modules already get extracted for that updated kernel, but the depmod
call still applied to the currently running one. Supply the new version
number to depmod, so that it applies to that version instead.

Fixes #3699

---

 * [x] image-refresh ubuntu-2204

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3700-20220804-062525/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on rhos-01-16.
Log: https://logs.cockpit-project.org/logs/image-refresh-3700-20220804-062828/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2204 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2204-20220804-064139

**Comment by martinpitt** [comment]
> + depmod 5.15.0-43-generic

That looks better!

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
