### PR TITLE
images: Use "Generic" variant for fedora-40

### PR DESCRIPTION
**Pull request by mvollmer**
Just like we did for fedora-rawhide.

 * [x] image-refresh fedora-40

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-40 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-40-20240403-082637

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-40-9e4d6359-20240403-080812/log.html

**Review by jelly — APPROVED** [review]

**Comment by jelly** [comment]
So this fixes https://github.com/cockpit-project/bots/issues/6143

But I see a new? stratis failure.

**Comment by mvollmer** [comment]
> But I see a new? stratis failure.

Yeah, let's see... there are many reasons why rebooting might fail.

**Comment by martinpitt** [comment]
@mvollmer maybe the same as in https://github.com/cockpit-project/cockpit/issues/20245 ?

**Comment by mvollmer** [comment]
> @mvollmer maybe the same as in [cockpit-project/cockpit#20245](https://github.com/cockpit-project/cockpit/issues/20245) ?

Interesting! Thanks for the pointer.

**Comment by mvollmer** [comment]
> > But I see a new? stratis failure.
> 
> Yeah, let's see... there are many reasons why rebooting might fail.

https://github.com/stratis-storage/stratisd/issues/3586

I make a naughty pattern for that.

**Comment by mvollmer** [comment]
> @mvollmer maybe the same as in [cockpit-project/cockpit#20245](https://github.com/cockpit-project/cockpit/issues/20245) ?

Yes, that also got stratisd 3.6.6, which has the bug.

**Comment by martinpitt** [comment]
This [machines failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6166-a97c224f-20240403-154431-fedora-40-cockpit-project-cockpit-machines/log.html#70) is similar to issue #5979, but it crashes in a different place: `udevInterfaceGetXMLDesc`. That needs to be reported still.

**Review by martinpitt — APPROVED** [review]
Cheers! I'll deal with the machines flake separately, that's not new.

**Pull request merged**
