### PR TITLE
images: add pod infra container

### PR DESCRIPTION
**Pull request by jelly**
Include the pod infra container in the test image required for testing cockpit-podman's new create pod feature.

 * [x] image-refresh ubuntu-2204

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-3856-20220913-073636/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2204 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2204-20220913-075416

**Comment by jelly** [comment]
Let's see if https://cockpit-logs.us-east-1.linodeobjects.com/pull-961-20220913-080836-bfe5b802-ubuntu-2204-bots-3856/log.html is happy about the extra podman image.

**Comment by martinpitt** [comment]
The tests still seems to be a [bit wonky](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3856-20220913-080810-ab42b298-ubuntu-2204-cockpit-project-cockpit-podman/log.html) and mis-count the expected number of images to delete. I think that needs fixing in c-podman first?

**Comment by jelly** [comment]
> 

Ye

> The tests still seems to be a [bit wonky](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3856-20220913-080810-ab42b298-ubuntu-2204-cockpit-project-cockpit-podman/log.html) and mis-count the expected number of images to delete. I think that needs fixing in c-podman first?

Yes, this is kinda unfortunate...

**Review by martinpitt — APPROVED** [review]
Yay!

**Pull request merged**
