### PR TITLE
Image refresh for fedora-39

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-39
 * [x] image-refresh fedora-39

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-39 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-39-20231126-230917

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-39-20231126-230909.log

**Comment by martinpitt** [comment]
There is nore more variant of #5444 with `unlink` and `usr_t` (instead of `kdumpctl_tmp_t`). [log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5594-20231126-231032-9a279a40-fedora-39-expensive-cockpit-project-cockpit/log.html#1), [log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5594-20231126-231035-9a279a40-fedora-39-devel-cockpit-project-cockpit/log.html#43). As https://bugzilla.redhat.com/show_bug.cgi?id=2246046 (downstream of #5444) is already fixed, we need to make a new one.

**Comment by martinpitt** [comment]
Meh -- this doesn't reproduce locally, and above all, *doesn't make sense*'. The only plausible files for that are /usr/share/terminfo/v/vt102 and /usr/share/terminfo/v/vt10* , but why on earth should starting kdump.service remove these? This happens even before rebuilding the initrd.

This happens in the second boot, i.e. after the kdump enablement. The "minimal nfs validation" step doesn't really change anything, afterwards it enables compression (kdump.service restart and initrd build #1, which is fine), afterwards it tests ssh (kdump.service restart and initrd build #2, which causes these failures). I'll send a cockpit debug PR which enables some more debugging.

**Comment by martinpitt** [comment]
... and so did the [second run](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19654-20231127-070531-0e3905b8-fedora-39-expensive-bots-5594/log.html). The retry here was successful as well, so :man_shrugging:

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
