### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/arch-20230926-225151.log

**Comment by jelly** [comment]
The udisks2 package now lacks the lvm2 plugin.

**Comment by jelly** [comment]
Should be fixed by https://gitlab.archlinux.org/archlinux/packaging/packages/udisks2/-/commit/74bed488e3a7fe148483567586ccc77a6403265a

**Comment by jelly** [comment]
I want to re-refresh so let's close this one.

**Pull request closed without merging**
