### PR TITLE
images: Drop GPG key installation on rhel-7-9

### LINKED ISSUE #2150: Image refresh for rhel-7-9 - fixed in #2185
Image refresh for rhel-7-9
 * [x] fix [`mock --shell` breakage](https://bugzilla.redhat.com/show_bug.cgi?id=1976702): PR #2145
 * [ ] FAIL: image-refresh rhel-7-9

### PR DESCRIPTION
**Pull request by martinpitt**
cockpit-composer has not needed this any more for a long time.
pool.sks-keyservers.net went away, so this does not work any more.

Fixes #2150

 * [x] image-refresh rhel-7-9
 * [x] Adjust insights tests to new insights client: https://github.com/cockpit-project/cockpit/pull/16065

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-2185-20210707-055454/

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-7-9-20210707-061919

**Comment by martinpitt** [comment]
[subscriptions are broken](https://logs.cockpit-project.org/logs/pull-2185-20210707-064224-1e58d6d4-rhel-7-9-cockpit-project-cockpit-rhel-7.9/log.html#151-2) *sigh*

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/16065 to fix the tests for the new insights client here:

    insights-client (0:3.1.1-1.el7_9 -> 0:3.1.5-1.el7_9)

**Comment by martinpitt** [comment]
Rebased, as services image was updated in the meantime, and [timed out](https://logs.cockpit-project.org/logs/pull-16065-20210708-053746-8c32e15a-rhel-7-9-bots-2185/log.html). Will re-trigger tests once https://github.com/cockpit-project/cockpit/pull/16065 lands.

**Review by allisonkarlitskaya — APPROVED** [review]
Up to the bots, now.

**Pull request merged**
