### PR TITLE
Image refresh for rhel-8-4

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-4
 * [x] image-refresh rhel-8-4

### CODE REVIEW

**Comment by marusak** [comment]
```
warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-255.el8.x86_64
```

not this again :/ Needs naughty, see previous ones in https://github.com/cockpit-project/bots/issues/538 or https://github.com/cockpit-project/bots/issues/1236

**Comment by allisonkarlitskaya** [comment]
```
$ bots/image-diff  rhel-8-4-afaf02bc44953ea6ba9ac257221929a81d5ff15a64d882f1be315f27faec0fff.qcow2 rhel-8-4-61ab42d1631be62f21674306d59d143b75039c01009d9d5f589d5c6ba4b6a4c4.qcow2

...
Changed:
...
  kernel (4.18.0-250.el8 -> 4.18.0-255.el8)
...

$ bots/vm-run -q -e 'find /lib/modules' -e 'poweroff -f' rhel-8-4-61ab42d1631be62f21674306d59d143b75039c01009d9d5f589d5c6ba4b6a4c4.qcow2
...
/lib/modules/4.18.0-255.el8.x86_64/modules.symbols.bin
/lib/modules/4.18.0-242.el8.x86_64
/lib/modules/4.18.0-242.el8.x86_64/extra
/lib/modules/4.18.0-242.el8.x86_64/extra/kmod-kvdo
/lib/modules/4.18.0-242.el8.x86_64/extra/kmod-kvdo/uds
/lib/modules/4.18.0-242.el8.x86_64/extra/kmod-kvdo/uds/uds.ko
/lib/modules/4.18.0-242.el8.x86_64/extra/kmod-kvdo/vdo
/lib/modules/4.18.0-242.el8.x86_64/extra/kmod-kvdo/vdo/kvdo.ko
```

ie: kernel got updated and kvdo module not.

**Comment by allisonkarlitskaya** [comment]
Filed https://bugzilla.redhat.com/show_bug.cgi?id=1904034 about that

**Comment by marusak** [comment]
> $ bots/image-diff 

nice!

**Comment by allisonkarlitskaya** [comment]
I can't push the naughty for some reason.  I'll just open a separate PR.

**Comment by allisonkarlitskaya** [comment]
Dealing with this in  #1434 now.

**Pull request closed without merging**
