### PR TITLE
Image refresh for rhel-8-3

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-3
 * [x] image-refresh rhel-8-3

### CODE REVIEW

**Comment by martinpitt** [comment]
@marusak: [This podman failure](https://logs.cockpit-project.org/logs/pull-1106-20200729-063250-b3663eeb-rhel-8-3-cockpit-project-cockpit-podman-rhel8/log.html#7-2) rings a bell -- do we need to backport something to the rhel-8 branch? Presumably it's because RHEL 8.3 got a new podman now?

**Comment by marusak** [comment]
>  This podman failure rings a bell -- do we need to backport something to the rhel-8 branch? Presumably it's because RHEL 8.3 got a new podman now?

Indeed, sent https://github.com/cockpit-project/cockpit-podman/pull/463

**Comment by martinpitt** [comment]
@atodorov , @larskarlitski : Seems lorax fails on current RHEL 8.3, and [tar](https://logs.cockpit-project.org/logs/pull-1106-20200729-063304-b3663eeb-rhel-8-3-tar-weldr-lorax-rhel8-branch/log.html) does not talk to any external service, right? This sounds like a red flag :fire:

**Comment by marusak** [comment]
`TestLogin.testSELinuxRestrictedUser` is failing on distropkg, this needs some backport? @martinpitt 
[master](https://logs.cockpit-project.org/logs/pull-1106-20200729-063301-b3663eeb-rhel-8-3-distropkg-cockpit-project-cockpit/log.html) and [rhel-8.3 branch](https://logs.cockpit-project.org/logs/pull-1106-20200729-063301-b3663eeb-rhel-8-3-distropkg-cockpit-project-cockpit-rhel-8.3/log.html#79-2)

**Comment by martinpitt** [comment]
@marusak: Done in https://github.com/cockpit-project/cockpit/pull/14426 -- I suggest to ignore that rhel-8.3 branch failure for this PR, and after the above PR lands, I'll do a backport of the recent test and bug fixes to rhel-8.3.

**Comment by martinpitt** [comment]
@bcl: Could you please have a look at the lorax failure here? This smells like a regression in RHEL 8.3 itself, as the latest PR to the rhel-8 branch succeeded. Thanks!

**Comment by bcl** [comment]
Looks like it's a depsolve issue when trying to build images:

```
 Problem 1: module perl-App-cpanminus:1.7044:8010020190322100642:3a33b840-0.x86_64 requires module(perl:5.30), but none of the providers can be installed
  - module perl:5.26:820181219174508:9edba152-0.x86_64 conflicts with module(perl:5.30) provided by perl:5.30:8030020200609055348:568f3a16-0.x86_64
  - module perl:5.30:8030020200609055348:568f3a16-0.x86_64 conflicts with module(perl:5.26) provided by perl:5.26:820181219174508:9edba152-0.x86_64
  - conflicting requests
 Problem 2: module perl:5.26:820181219174508:9edba152-0.x86_64 conflicts with module(perl:5.30) provided by perl:5.30:8030020200609055348:568f3a16-0.x86_64
  - module perl:5.30:8030020200609055348:568f3a16-0.x86_64 conflicts with module(perl:5.26) provided by perl:5.26:820181219174508:9edba152-0.x86_64
  - module perl-App-cpanminus:1.7044:820181214184336:3a33b840-0.x86_64 requires module(perl:5.30), but none of the providers can be installed
  - module freeradius:3.0:8030020200609121000:1e4bbb35-0.x86_64 requires module(perl:5.26), but none of the providers can be installed
  - conflicting requests
```

**Comment by martinpitt** [comment]
Thanks @bcl. Indeed that was mentioned as a recent regression on rhel-devel@, so that's a regression in the archive, not on the image.

**Pull request merged**
