### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-coreos-20230309-225555.log

**Comment by martinpitt** [comment]
start_trivial_httpd() times out, because the nginx container crashes:
```
Starting...
nginx.c: loadable library and perl binaries are mismatched (got first handshake key 0xeb00080, needed 0xeb80080)
```

This reproduces straight away with `podman run -it --rm quay.io/jitesoft/nginx` -- their latest container image from 9 days ago is just plain broken. Let's rather just use the `:stable` tag, and re-tag it as latest so that we don't have to change the tests.

**Comment by cockpituous** [comment]
image-refresh fedora-coreos done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-coreos-20230310-103537

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-coreos-20230310-103535.log

**Review by skobyda — APPROVED** [review]
LGTM, thanks

**Pull request merged**
