### PR TITLE
images: Build centos-7 from official qcow image

### PR DESCRIPTION
**Pull request by martinpitt**
Starting from the cloud image is faster, more robust, and more realistic
(using an official product) than our own virt-install bootstrap.

CentOS 7 offers xz-compressed qcow images (254 MB xz vs. 819 MB
uncompressed, so well worth it). Download these and teach
cloudimage.bootstrap to handle these as well.

 * [x] image-refresh centos-7
 * [x] image-refresh services

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-1512-20210104-085252/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1512-20210104-085252/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-1512-20210104-085959/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/bots/commits/image-refresh-openshift-20210104-092020

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-mpt7w.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-1512-20210104-092222/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-1512-20210104-092222/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-1512-20210104-101010/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1512-20210104-101010/

**Comment by martinpitt** [comment]
Huh, an hour ago or so this worked locally for me, and it also did on the bots. Now it fails on a certificate error everywhere.

**Comment by martinpitt** [comment]
Ah, the certificate just timed out:

            Not After : Apr  4 06:38:29 2021 GMT

If only LetsEncrypt would have a mechanism for auto-renewal... :exploding_head:

**Comment by martinpitt** [comment]
Filed https://pagure.io/centos-infra/issue/178 about the expired certificate.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-1512-20210104-102828/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/bots/commits/image-refresh-centos-7-20210104-104949

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-1512-20210104-103535/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1512-20210104-103535/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-1512-20210104-111616/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/bots/commits/image-refresh-centos-7-20210104-113636

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-8.
Log: https://logs.cockpit-project.org/logs/image-refresh-1512-20210104-113636/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-1512-20210104-113636/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-mk4ct.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-1512-20210104-122626/

**Comment by cockpituous** [comment]
image-refresh services done: https://github.com/cockpituous/bots/commits/image-refresh-services-20210104-130101

**Comment by martinpitt** [comment]
For $DEITY's sake, our [rhel-7.9](https://logs.cockpit-project.org/logs/pull-1512-20210104-145255-dbc6924e-centos-7-cockpit-project-cockpit-rhel-7.9/log.html) branch has so much cruft with huge and finnicky testbed assumptions. This is similar to PR #1511, I just don't want to wade through that old ovirt/atomic storage setup cruft. I'll try my luck with rhel-8* images first.

**Pull request closed without merging**
