### PR TITLE
images: download podman test containers on RHEL

### PR DESCRIPTION
**Pull request by jelly**
For podman tests to run offline we need the test containers to be
available.

 * [x] image-refresh rhel-9-0

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-3137-20220324-120000/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-3137-20220324-120000/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3137-20220324-122222/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20220324-124545

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://logs.cockpit-project.org/logs/image-refresh-3137-20220324-124646/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20220324-130606

**Review by marusak — APPROVED** [review]
Thank you!

**Comment by martinpitt** [comment]
This affects rhel-8-6 image too, right? But we can trigger that separately. I triggered #3141

**Pull request merged**
