### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by marusak** [comment]
[testTally](https://logs.cockpit-project.org/logs/pull-1072-20200716-041543-11a8760c-debian-testing-cockpit-project-cockpit/log.html#88) failed twice in a row. Once more.

**Comment by martinpitt** [comment]
testTally by itself works fine, but all red tests failed on a libvirt crash. so need to track down where it happens, and why it then affects unrelated tests.

**Comment by martinpitt** [comment]
I locally ran all machines tests and testTally, and I'm still unable to reproduce this. Need to retry on a CI machine.

**Comment by martinpitt** [comment]
I reproduced two libvirtd crashes on a CI box. Indeed debian-testing is the only OS with libvirt 6.4.0; Fedora 32 still has 6.1.0, 6.5 is in Rawhide. It seems systemd-coredump doesn't actually create core dumps on Debian-testing because of resource limits. Fedora has "unlimited", but *not* through /etc/security/limits.conf. I don't know how it does that, I can't find anything in /etc.

**Comment by martinpitt** [comment]
When trying to install debug symbols, it upgrades to libc 2.31. I am not able to get a crash with that, either because that fixed something, or because of sheer bad/good luck. Let's try and build a fresh one, this one is getting rather stale anyway.

**Comment by martinpitt** [comment]
Bah, and a few minutes after saying that it of course *did* crash again. But for some reason, systemd-coredump doesn't collect a core dump on Debian testing, even though I set the core ulimit to "unlimited":
```
Process 8435 (libvirtd) of user 1002 dumped core.

Stack trace of thread 8435:
#0  0x00007f6ddcdb0cb1 __GI_raise (libc.so.6 + 0x3bcb1)
#1  0x00007f6ddcd9a537 __GI_abort (libc.so.6 + 0x25537)
#2  0x00007f6ddd10cd62 n/a (libdbus-1.so.3 + 0xed62)
#3  0x00007f6ddd12ea80 _dbus_warn_check_failed (libdbus-1.so.3 + 0x30a80)
#4  0x00007f6ddd112667 dbus_connection_ref (libdbus-1.so.3 + 0x14667)
#5  0x00007f6ddd2110ee virDBusWatchCallback (libvirt.so.0 + 0xc00ee)
#6  0x00007f6ddd218b16 virEventGLibHandleDispatch (libvirt.so.0 + 0xc7b16)
#7  0x00007f6ddcfc84de g_main_context_dispatch (libglib-2.0.so.0 + 0x504de)
#8  0x00007f6ddcfc8890 n/a (libglib-2.0.so.0 + 0x50890)
#9  0x00007f6ddcfc891f g_main_context_iteration (libglib-2.0.so.0 + 0x5091f)
#10 0x00007f6ddd2197c0 virEventGLibRunOnce (libvirt.so.0 + 0xc87c0)
#11 0x00007f6ddd35a8bd virNetDaemonRun (libvirt.so.0 + 0x2098bd)
#12 0x000055a6b8bf4e44 main (libvirtd + 0x23e44)
#13 0x00007f6ddcd9bcca __libc_start_main (libc.so.6 + 0x26cca)
#14 0x000055a6b8bf57ba _start (libvirtd + 0x247ba)

Stack trace of thread 8436:
#0  0x00007f6ddcf637b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f6ddd272367 virCondWait (libvirt.so.0 + 0x121367)
#2  0x00007f6ddd272f43 virThreadPoolWorker (libvirt.so.0 + 0x121f43)
#3  0x00007f6ddd2724b5 virThreadHelper (libvirt.so.0 + 0x1214b5)
#4  0x00007f6ddcf5cea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f6ddce72dcf __clone (libc.so.6 + 0xfddcf)
```

So this is a D-Bus assertion. The journal suggests it's related to shutting down the user libvirtd and libvirt-dbus when the session goes down:

```
Jul 24 12:04:50 debian libvirtd[8435]: libvirt version: 6.4.0, package: 2 (Guido Günther <agx@sigxcpu.org> Fri, 10 Jul 2020 16:44:12 +0200)
Jul 24 12:04:50 debian libvirtd[8435]: hostname: debian
Jul 24 12:04:50 debian libvirtd[8435]: Failed to open file '/sys/kernel/security/apparmor/profiles': Permission denied
Jul 24 12:04:50 debian libvirtd[8435]: Failed to read AppArmor profiles list '/sys/kernel/security/apparmor/profiles': Permission denied
Jul 24 12:04:50 debian libvirtd[8435]: Failed to open file '/sys/kernel/security/apparmor/profiles': Permission denied
Jul 24 12:04:50 debian libvirtd[8435]: Failed to read AppArmor profiles list '/sys/kernel/security/apparmor/profiles': Permission denied
Jul 24 12:06:58 debian libvirtd[8435]: Operation not supported: CPU tuning is not available in session mode
Jul 24 12:08:51 debian libvirtd[8435]: Failed to open file '/sys/class/scsi_host/host3/unique_id': No such file or directory
[...]
Jul 24 12:15:48 debian systemd[1]: Stopping User Manager for UID 1003...
Jul 24 12:15:48 debian systemd[34184]: Stopped target Main User Target.
Jul 24 12:15:48 debian systemd[34184]: Stopping D-Bus User Message Bus...
Jul 24 12:15:48 debian libvirt-dbus[34257]: Error releasing name org.libvirt: The connection is closed

Jul 24 12:15:49 debian systemd-coredump[35061]: Process 8435 (libvirtd) of user 1002 dumped core.
                                                Stack trace of thread 8435:
```

**Comment by martinpitt** [comment]
I was able to get a stack trace at last. Reported upstream to https://gitlab.com/libvirt/libvirt/-/issues/59

**Comment by martinpitt** [comment]
Filed and added a naughty, rebased.

**Pull request merged**
