### PR TITLE
images: Pre-install basic cockpit packages on Debian/Ubuntu

### PR DESCRIPTION
**Pull request by martinpitt**
We have already done this on Fedora/RHEL/CentOS for a long time. This
helps projects like cockpit-{podman,machines} to do test preparation
offline, and moves test breakage due to changes in newer cockpit
versions from "spontaneously happens" to "happens on image refreshes".

 * [x] image-refresh debian-stable
 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-2004
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-2675-20211130-080404/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-stable-20211130-082121

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-2675-20211130-082222/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20211130-084242

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-2675-20211130-084242/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2004 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2004-20211130-085858

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-2675-20211130-085858/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2004 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2004-20211130-091717

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-7.
Log: https://logs.cockpit-project.org/logs/image-refresh-2675-20211130-091717/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20211130-094949

**Review by allisonkarlitskaya — APPROVED** [review]
Looks good.  Thanks for the refreshes and test runs.

**Pull request merged**
