### PR TITLE
Image refresh for arch

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for arch
 * [x] image-refresh arch

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-arch-1906428f-20240329-223718/log.html

**Comment by martinpitt** [comment]
This got xz-utils 5.6.1-1 which fixes the recent trojan. See https://security.archlinux.org/AVG-2851

**Comment by martinpitt** [comment]
[This failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6151-dc331a66-20240330-110503-arch-storage-cockpit-project-cockpit/log.html#49-2) is real -- the test expects "bad option", but the new packages say "unknown parameter".

**Comment by mvollmer** [comment]
> This got xz-utils 5.6.1-1 which fixes the recent trojan. See https://security.archlinux.org/AVG-2851

Fix is in 5.6.1-2.

**Comment by mvollmer** [comment]
> > This got xz-utils 5.6.1-1 which fixes the recent trojan. See https://security.archlinux.org/AVG-2851
> 
> Fix is in 5.6.1-2.

Which is in the image. All good!

**Comment by mvollmer** [comment]
> [This failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6151-dc331a66-20240330-110503-arch-storage-cockpit-project-cockpit/log.html#49-2) is real -- the test expects "bad option", but the new packages say "unknown parameter".

Fixed in https://github.com/cockpit-project/cockpit/pull/20249, hopefully.

**Review by martinpitt — APPROVED** [review]
Nice! Let's land that quickly, to purge the dangerous xz from existence.

**Pull request merged**
