### PR TITLE
Gradually introduce typing

### PR DESCRIPTION
**Pull request by jelly**
Instead of a big bang, do the same thing as @allisonkarlitskaya `--strict` PR in cockpit. As the codebase is rather small I feel like it makes sense to directly go for `--stict`.

 * [x] image-refresh cirros

### CODE REVIEW

**Comment by martinpitt** [comment]
The changes LGTM. It's just not [clear from the unit test log](https://github.com/cockpit-project/bots/actions/runs/6074731184/job/16479413588?pr=5206) whether ruff actually ran or was skipped. However, it uses the standard cockpit unit test container, which does have rust.

**Comment by jelly** [comment]
> The changes LGTM. It's just not [clear from the unit test log](https://github.com/cockpit-project/bots/actions/runs/6074731184/job/16479413588?pr=5206) whether ruff actually ran or was skipped. However, it uses the standard cockpit unit test container, which does have rust.

Good question.. I know flake8 runs as that as bite me a ton as it has no language server so I don't run it anymore in neovim.

**Review by martinpitt — APPROVED** [review]
Indeed let's land this -- there's more work to be done either way.

I wonder, is it easier to run mypy in non-strict mode on everything first, or go from none to strict in one go?

**Comment by martinpitt** [comment]
I triggered an example image refresh to test the changed machinery. No need to actually land that.

**Comment by cockpituous** [comment]
image-refresh cirros done: https://github.com/cockpit-project/bots/commits/image-refresh-cirros-20230907-045046

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/cirros-20230907-045050.log

**Pull request merged**
