### PR TITLE
images: Use rhel-7.8's spec file for rhel/centos-7 images

### LINKED ISSUE #41: Image refresh for rhel-7-7
Image refresh for rhel-7-7
 * [ ] image-refresh rhel-7-7

### LINKED ISSUE #42: Image refresh for continuous-atomic
Image refresh for continuous-atomic
 * [ ] image-refresh continuous-atomic

### PR DESCRIPTION
**Pull request by martinpitt**
master's cockpit.spec grew some stricter version constraints than what's
available on RHEL 7. Due to yum silently ignoring unavailable versions,
the mock was missing systemd-devel.

Use the rhel-7.8 branch for building the RHEL 7 based images instead,
which also gets rid of the previous golang hardcoding.

Fixes #41

 * [x] image-refresh rhel-7-7
 * [x] image-refresh centos-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-58-20190930-142929/

**Comment by cockpituous** [comment]
image-refresh continuous-atomic done: https://github.com/cockpituous/bots/commits/image-refresh-continuous-atomic-20190930-144242

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-04.
Log: https://209.132.184.41:8493/logs/image-refresh-58-20190930-144444/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-58-20190930-144444/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-06.
Log: https://209.132.184.41:8493/logs/image-refresh-58-20190930-145454/

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-7-7-20190930-152222

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-58-20190930-162929/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/bots/commits/image-refresh-centos-7-20190930-170202

**Comment by martinpitt** [comment]
[testCreate](https://209.132.184.41:8493/logs/pull-58-20190930-191414-2fa72db0-cockpit-project-cockpit-rhel-7.7-rhel-7-7/log.html) failure, but this is a nasty flake right now, retrying.

**Comment by martinpitt** [comment]
Hmm, [testCreate](https://209.132.184.41:8493/logs/pull-58-20191001-072323-2fa72db0-cockpit-project-cockpit-rhel-7.7-rhel-7-7/log.html#230-2) is impossible to get green. @KKoukiou , is this a known issue in the 7.7 branch? are we missing some backport here?

**Comment by martinpitt** [comment]
This is a bit urgent as it blocks three image rebuilds. 7.7 is released, so I can't imagine it's the new image that broke this, but to make sure I'll run this test against the current one. I filed https://github.com/cockpit-project/cockpit/pull/12899 to compare.

**Comment by martinpitt** [comment]
Confirmed, [testCreate](https://209.132.184.41:8493/logs/pull-12899-20191001-094040-914144c9-cockpit-project-cockpit--rhel-7-7/log.html) fails on the current image as well. So this is not a regression.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-01.
Log: https://209.132.184.41:8493/logs/image-refresh-58-20191001-124848/

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-7-7-20191001-131212

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-06.
Log: https://209.132.184.41:8493/logs/image-refresh-58-20191001-131313/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/bots/commits/image-refresh-centos-7-20191001-135656

**Pull request merged**
