### PR TITLE
Image refresh for ubuntu-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for ubuntu-stable
 * [ ] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by martinpitt** [comment]
There's something [seriously wrong](https://logs.cockpit-project.org/logs/pull-1266-20200929-044544-af3be7a4-ubuntu-stable-cockpit-project-cockpit/log.html#250-2) here. I already retried once, that wasn't just an one-off "WTH?"

**Comment by mvollmer** [comment]
The many parted issues are due to a change in the 5.8 kernel, where the BLKPG_DEL_PARTITION ioctl syscall now returns ENOMEM instead of ENXIO for non-existing partitions. This trips up parted, partprobe, etc.

See https://gitlab.gnome.org/GNOME/gparted/-/issues/111, https://github.com/torvalds/linux/commit/88ce2a530cc9865a894454b2e40eba5957a60e1a

**Comment by martinpitt** [comment]
There's a new kernel in the pipeline: https://bugs.launchpad.net/kernel-sru-workflow/+bug/1896668 . Might be worth trying that (from -proposed) to see if that fixes it already; if so, we can just stall this until that lands.

**Comment by martinpitt** [comment]
From #ubuntu-devel:
```
sil2100 | pitti: yes please! Since I know the current linux in release was not supposed to be released
sil2100 | pitti: it migrated by accident, only the -proposed one is the right one (hopefully migrating soon)
sil2100 | We were waiting with beta images until that lands 
```

**Comment by mvollmer** [comment]
The kernel tracking bug went to "Fixed Released", I don't know what that means but let's try a new image.

**Comment by martinpitt** [comment]
@mvollmer: I checked this morning and it wasn't published yet. Let's try tomorrow morning to be sure that it propagated to the mirrors.

**Comment by martinpitt** [comment]
OK, it's time to try a new build.

**Pull request closed without merging**
