### PR TITLE
images: Update fedora-testing to Fedora 37

### PR DESCRIPTION
**Pull request by jelly**
* [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by martinpitt** [comment]
Please remember to also change the naughty/fedora-testing symlink. This needs another push when the image is built anyway. Thanks for doing this!

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-testing-20230118-180656

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-testing-20230118-180606.log

**Review by martinpitt — APPROVED** [review]
Cheers!

**Pull request merged**
