### PR TITLE
images: Add Stratis to the RHELs

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh centos-8-stream
 * [x] image-refresh rhel-8-5
 * [x] image-refresh rhel-9-0

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-06.
Log: https://logs.cockpit-project.org/logs/image-refresh-2350-20210830-070101/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-sjt9l.
Log: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/image-refresh-2350-20210830-070101/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-2350-20210830-070101/

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20210830-072828

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://logs.cockpit-project.org/logs/image-refresh-2350-20210830-072828/

**Comment by cockpituous** [comment]
image-refresh rhel-8-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-5-20210830-075050

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-2350-20210830-075151/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20210830-080707

**Comment by mvollmer** [comment]
rhel-9-0 has this again during shutdown: `udisksd[17244]: malloc_consolidate(): unaligned fastbin chunk detected`

**Comment by mvollmer** [comment]
SELinux breaks pmproxy on centos-8-stream, and probably rhel-8-5.

**Comment by mvollmer** [comment]
> SELinux breaks pmproxy on centos-8-stream, and probably rhel-8-5.

https://bugzilla.redhat.com/show_bug.cgi?id=2000106

**Comment by mvollmer** [comment]
> > SELinux breaks pmproxy on centos-8-stream, and probably rhel-8-5.
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=2000106

Already fixed in pcp-5.3.1-5.el8

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-11.
Log: https://logs.cockpit-project.org/logs/image-refresh-2350-20210901-131515/

**Comment by cockpituous** [comment]
image-refresh rhel-8-5 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-5-20210901-133434

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-2350-20210901-134343/

**Comment by mvollmer** [comment]
> > > SELinux breaks pmproxy on centos-8-stream, and probably rhel-8-5.
> > 
> > 
> > https://bugzilla.redhat.com/show_bug.cgi?id=2000106
> 
> Already fixed in pcp-5.3.1-5.el8

Which is in the most recent rhel-8-5 image here. Let's see.

**Comment by cockpituous** [comment]
image-refresh centos-8-stream done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-8-stream-20210901-141414

**Comment by martinpitt** [comment]
@mvollmer: Want to squash the two rhel-8-5 image refreshes? Did you not trigger rhel-9-0 image tests on purpose, or merely forgot? Can you please remove the origin branches that you picked up here? Thanks! Crossing fingers that it works now :crossed_fingers:

**Comment by martinpitt** [comment]
This needs at least some work on [podman](https://logs.cockpit-project.org/logs/pull-2350-20210902-042338-90b537dd-rhel-9-0-cockpit-project-cockpit-podman/log.html#3-2). I thought container snapshot/restore was supposed to get *introduced* into RHEL 9 instead of being broken..

**Comment by mvollmer** [comment]
> This needs at least some work on [podman](https://logs.cockpit-project.org/logs/pull-2350-20210902-042338-90b537dd-rhel-9-0-cockpit-project-cockpit-podman/log.html#3-2).

I file a bug and turn this into a naughty.

**Comment by mvollmer** [comment]
> > This needs at least some work on [podman](https://logs.cockpit-project.org/logs/pull-2350-20210902-042338-90b537dd-rhel-9-0-cockpit-project-cockpit-podman/log.html#3-2).
> 
> I file a bug and turn this into a naughty.

We already had https://bugzilla.redhat.com/show_bug.cgi?id=1944964 since March, and the officially fixed crun-1.0 is now the repos. Let's rebuild rhel-9-0.  Earlier, we probably had picked up a accidentally fixed package...

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-2350-20210906-084444/

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20210906-085757

**Comment by mvollmer** [comment]
> We already had https://bugzilla.redhat.com/show_bug.cgi?id=1944964 since March, and the officially fixed crun-1.0 is now the repos.

Works!

**Comment by mvollmer** [comment]
> rhel-9-0 has this again during shutdown: `udisksd[17244]: malloc_consolidate(): unaligned fastbin chunk detected`

I am trying a bit to reproduce this. Must have something to do with running both storage and tracer tests non-destructively in the same machine... but this will be a naughty, I guess.

**Comment by mvollmer** [comment]
> > rhel-9-0 has this again during shutdown: `udisksd[17244]: malloc_consolidate(): unaligned fastbin chunk detected`
> 
> I am trying a bit to reproduce this. Must have something to do with running both storage and tracer tests non-destructively in the same machine... but this will be a naughty, I guess.

Some notes in the bug report: https://bugzilla.redhat.com/show_bug.cgi?id=2001549

**Comment by mvollmer** [comment]
I can reproduce the TestMachinesDisks.testAddDiskAdditionalOptions failure, it's not a flake.  Let's see...

**Comment by mvollmer** [comment]
> I can reproduce the TestMachinesDisks.testAddDiskAdditionalOptions failure, it's not a flake. Let's see...

This test triggers a avalanche of virt-install processes (some 30 of them or so). This happens on our old rhel-9-0 image, as well as on fedora-34, as well as on the new rhel-9-0 image here (and probably happens everywhere). What seems to be new with this rhel-9-0 image is that the CI vm runs out of memory and stalls the cockpit-bridge process long enough to trigger the connection health check.

We don't expect this avalanche of virt-install processes from adding disks, so let's see where it comes from.

**Comment by mvollmer** [comment]
> What seems to be new with this rhel-9-0 image is that the CI vm runs out of memory and stalls the cockpit-bridge process long enough to trigger the connection health check.

fedora-34 also runs out of memory, but it manages to complete the test before the virt-install avalanche has slowed the system down too much.

**Comment by mvollmer** [comment]
> We don't expect this avalanche of virt-install processes from adding disks, so let's see where it comes from.

It is triggered by https://github.com/cockpit-project/cockpit-machines/blob/main/src/components/create-vm-dialog/createVmDialog.jsx#L1117

The method runs 18 times during the test and spawns 3 concurrent virt-install processes. This happens fast enough and (virt-install is slow enough) so that we get 40 or more concurrent virt-install processes.

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit-machines/pull/359 landed, retrying.

**Review by martinpitt — APPROVED** [review]
What an ordeal, thanks for bearing with all this mess!

**Comment by mvollmer** [comment]
Yay!

**Pull request merged**
