### PR TITLE
images: RHEL 8.8 and 9.2 are still nightly

### LINKED ISSUE #4667: Image refresh for rhel-8-8
Image refresh for rhel-8-8
 * [ ] FAIL: image-refresh rhel-8-8

### PR DESCRIPTION
**Pull request by martinpitt**
Fixes #4667

----

I missed that in #4647 as I wasn't refreshing all images at the same time.

 * [x] image-refresh rhel-8-8
 * [x] image-refresh rhel-9-2

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-8-8 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-8-20230418-031834

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-8-20230418-031818.log

**Comment by cockpituous** [comment]
image-refresh rhel-9-2 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-2-20230418-034004

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-2-20230418-034040.log

**Review by jelly — APPROVED** [review]

**Pull request merged**
