### PR TITLE
Image refresh for fedora-38

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-38
 * [x] image-refresh fedora-38

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-38 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-38-20240311-230319

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-38-e1594166-20240311-223822/log.html

**Comment by martinpitt** [comment]
@jkozol This [testCreateAndDeleteBlueprint failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6069-20240312-072139-db031bdd-fedora-38-osbuild-cockpit-composer/log.html#3-2) became a lot more insistent. It used to be a "75% flake" until now, see https://github.com/cockpit-project/cockpit/issues/20138#issuecomment-1982817505 . But I retried it 3 times, and it has always failed.

**Comment by martinpitt** [comment]
This is actually not a regression -- it fails on the current images as well, e.g. in  https://github.com/osbuild/cockpit-composer/pull/1991 So let's land this.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
