### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing
 * [x] Fix `TestLogin.testTally` on debian-testing: https://github.com/cockpit-project/cockpit/pull/15323
 * [x] Blocked on https://github.com/cockpit-project/cockpit-podman/pull/675

### CODE REVIEW

**Comment by martinpitt** [comment]
[TestLogin.testTally regression](https://logs.cockpit-project.org/logs/pull-1667-20210212-021523-c12d117a-debian-testing-cockpit-project-cockpit/log.html#204-2) looks real ("permission denied" on login). This was recently changed by @allisonkarlitskaya to work  around some bugs, but now [pam 1.4.0-3 hit testing](https://tracker.debian.org/news/1226655/accepted-pam-140-3-source-into-unstable/) with some fixes.

**Comment by martinpitt** [comment]
The two changes in the new PAM package in debian-testing are:

 - backported fix for [faillock: create tallydir before creating tallyfile ](https://github.com/linux-pam/linux-pam/commit/d54870f993e97fe75e2cd0470a3701d5af22877c)
 - Install the missing faillock program:

```diff
--- pam-1.4.0/debian/libpam-modules-bin.install…2020-12-29 04:20:38.000000000 +0100
+++ pam-1.4.0/debian/libpam-modules-bin.install…2021-02-01 23:28:30.000000000 +0100
@@ -2,3 +2,5 @@
 sbin/unix_update…………………sbin
 sbin/mkhomedir_helper……sbin
 sbin/pam_timestamp_check…………………usr/sbin
+sbin/faillock usr/sbin
+modules/pam_faillock/faillock.8 usr/share/man/man8
```

The latter fixes our [current naughty](https://github.com/cockpit-project/bots/issues/1585), so the test gets a little further.

**Comment by martinpitt** [comment]
This somehow smells like some off-by-one: The test does this:
```py
        # try three bogus login attempts
        for n in [1, 2, 3]:
            expect_failed_login("admin", "bad", n)
        expect_fail_count(3)

        # make sure we can still login
        expect_successful_login("admin", "foobar")
```
The loop causes this:
```
Feb 12 10:31:25 debian cockpit-session[3993]: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=::ffff:172.27.0.2  user=admin
Feb 12 10:31:28 debian cockpit-session[3997]: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=::ffff:172.27.0.2  user=admin
Feb 12 10:31:30 debian cockpit-session[4001]: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=::ffff:172.27.0.2  user=admin
Feb 12 10:31:30 debian cockpit-session[4001]: pam_faillock(cockpit:auth): Consecutive login failures for user admin account temporarily locked
```
and thus the "expect_successful" gets a permission denied. When I run `faillock --reset`, I can log in again.

This is indeed because the "debian-testing" special case in the test sets up pam_faillock with the default `deny=`, while on every other OS we specify `deny=4`. With that, the test succeeds. I'll send a PR.

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/15323 to fix the test for debian-testing, blocking on that. Nice to see that known issue fixed!

**Review by allisonkarlitskaya — DISMISSED** [review]
Please don't land without removing the naughty.

**Comment by martinpitt** [comment]
Test fix landed, restarting.

**Comment by martinpitt** [comment]
> Please don't land without removing the naughty.

Ugh.. we normally leave that to our bots, but *shrug*, pushed.

**Review by allisonkarlitskaya — APPROVED** [review]
+1 if the tests pass

**Comment by martinpitt** [comment]
Eh, why does [podman now fail](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-1667-20210212-132454-2567e3ae-debian-testing-cockpit-project-cockpit-podman/log.html#4-2) all of a sudden? I just dropped the naughty (unrelated), and it passed before. Back to "needswork" *sigh*

**Comment by martinpitt** [comment]
Ah:

    Get:5 http://deb.debian.org/debian bullseye/main amd64 podman amd64 3.0.0~rc2+dfsg1-2+b1 [9503 kB]

In commit 1d94c0e7a88d I pre-installed podman to the image, but apparently that somehow did not work? So we have some regression, or at least behaviour change, with podman 3.0.

**Comment by martinpitt** [comment]
Retrying take 3. Thanks @KKoukiou for fixing the podman tests!

**Pull request merged**
