### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing
 * [ ] ~copr nightly regression: https://bugzilla.redhat.com/show_bug.cgi?id=1944517~
 * [x] Fix scenario setup to not install recommends on upgrade: https://github.com/cockpit-project/cockpit/pull/15630

### CODE REVIEW

**Comment by martinpitt** [comment]
One or two storage regressions and a new SELinux violation.

**Comment by skobyda** [comment]
The SELinux violation is not new, it exists as naughty/fedora-33/118-selinux-rpcbind-name_bind, so that will be fixed when https://github.com/cockpit-project/bots/pull/1849 will be merged
Also storage regressions will be fixed when https://github.com/cockpit-project/bots/pull/1851 is merged. Adding blocked tag

**Comment by martinpitt** [comment]
f-33 naughties got fixed, retrying. Our f-testing image is f-33 based, so it shouldn't be affected by the (still open) f-34 refresh. Retrying.

**Comment by martinpitt** [comment]
Pushed a rebase.

**Comment by marusak** [comment]
`dnf-copr` context is failing to install packages:
```
error: Failed dependencies:
	cockpit-bridge >= 186 is needed by (installed) cockpit-networkmanager-240-1.fc33.noarch
	cockpit-bridge >= 186 is needed by (installed) cockpit-packagekit-240-1.fc33.noarch
	cockpit-shell >= 186 is needed by (installed) cockpit-networkmanager-240-1.fc33.noarch
	cockpit-shell >= 186 is needed by (installed) cockpit-storaged-240-1.fc33.noarch
```

This is fishy.

**Comment by martinpitt** [comment]
@marusak : Indeed that smells like a dnf regression. The log shows that cockpit-bridge-240-1.fc33.x86_64 is installed. Needs bugzilla.

**Comment by martinpitt** [comment]
I filed https://bugzilla.redhat.com/show_bug.cgi?id=1944517

**Comment by martinpitt** [comment]
This reproduces fine locally with `TEST_SCENARIO=dnf-copr TEST_OS=fedora-33 test/run`. So it's not updates-testing and not this image refresh, but really the copr.

The bit that's new and breaks our scenario is this:
```
# dnf -y copr enable rpmsoftwaremanagement/dnf-nightly && dnf -y update
Upgraded:
  cockpit-240-1.fc33.x86_64                                                     
  cockpit-bridge-240-1.fc33.x86_64                                              
  cockpit-system-240-1.fc33.noarch                                              
  cockpit-ws-240-1.fc33.x86_64                    
  [... lots ...]
Installed:
  cockpit-networkmanager-240-1.fc33.noarch cockpit-packagekit-240-1.fc33.noarch
  cockpit-storaged-240-1.fc33.noarch       kernel-core-5.11.10-200.fc33.x86_64 
```

I.e. the upgrade now installs previously existing Recommends:. We can certainly prevent that somehow, but that does not feel right. I'll ask on the downstream bug.

**Comment by martinpitt** [comment]
Depending on what upstream dnf says about the behaviour change, this is either a fix or a workaround:

```diff
--- test/run
+++ test/run
@@ -28,7 +28,7 @@ case $TEST_SCENARIO in
         test/containers/run-tests --container ${TEST_SCENARIO#*-}
         ;;
     dnf-copr*)
-        bots/image-customize -v --run-command 'dnf -y copr enable rpmsoftwaremanagement/dnf-nightly && dnf -y update' $TEST_OS
+        bots/image-customize -v --run-command 'dnf -y copr enable rpmsoftwaremanagement/dnf-nightly && dnf -y --setopt=install_weak_deps=False update' $TEST_OS
         test/image-prepare --verbose --overlay $TEST_OS
         test/common/run-tests --jobs ${TEST_JOBS:-1} --test-dir test/verify
         ;;

```

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/15630 to fix this.

**Review by marusak — APPROVED** [review]

**Pull request merged**
