### PR TITLE
Image refresh for fedora-36

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-36
 * [x] image-refresh fedora-36

### CODE REVIEW

**Comment by marusak** [comment]
New avc:
```
audit: type=1400 audit(1664408095.071:452): avc:  denied  { sys_admin } for  pid=2370 comm="mv" capability=21  scontext=system_u:system_r:NetworkManager_dispatcher_console_t:s0 tcontext=system_u:system_r:NetworkManager_dispatcher_console_t:s0 tclass=capability permissive=0
```

**Comment by martinpitt** [comment]
@marusak To spare you the search, this is https://bugzilla.redhat.com/show_bug.cgi?id=2122888 and needs to be updated in machine/machine_core/machine.py

**Comment by marusak** [comment]
Podman needs pixel update as it now pulls in `pause` container.

composer has some issues, @jkozol could you please take a look?

**Comment by jkozol** [comment]
Fixed here: https://github.com/osbuild/cockpit-composer/pull/1572

**Comment by jkozol** [comment]
This cockpit-composer failure is unrelated to this image refresh. It is being actively worked on. Some fixes will be in: https://github.com/osbuild/cockpit-composer/pull/1575 and some will be in a seperate test fix PR. Feel free to merge even with composer failing.

**Comment by jkozol** [comment]
To followup, several tests have been fixed in cockpit-composer. The remaining test failures for cockpit-composer are unrelated to the UI and are documented in this issue: https://github.com/osbuild/osbuild-composer/issues/3051

**Pull request merged**
