### PR TITLE
Image refresh for fedora-40

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-40
 * [x] image-refresh fedora-40
 * [x] https://github.com/cockpit-project/cockpit/pull/20204

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-40 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-40-20240318-225412

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-40-ddc79c7b-20240318-223715/log.html

**Comment by martinpitt** [comment]
Eww, tons of regressions -- we'll have lots to report and complain about.

**Comment by martinpitt** [comment]
The [ABRT failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6101-5605b494-20240318-225535-fedora-40-other-cockpit-project-cockpit/log.html#111-2) are :drum: SELinux. This is already reported at https://bugzilla.redhat.com/show_bug.cgi?id=2266786 , adding a naughty for it: #6113

**Comment by martinpitt** [comment]
The [kdump regressions](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6101-5605b494-20240318-225529-fedora-40-expensive-cockpit-project-cockpit/log.html): `kdump.service` fails because fails to rebuild the initrd, which fails:

```
# /usr/bin/kdumpctl start
kdump: No kdump initial ramdisk found.
kdump: Rebuilding /boot/initramfs-6.8.0-63.fc40.1.x86_64kdump.img
kdump: mkdumprd: failed to make kdump initrd
kdump: Starting kdump: [FAILED]
```

Even with `set -x` this doesn't give any useful info. Reported at https://bugzilla.redhat.com/show_bug.cgi?id=2270423 and filed known issue #6114.

**Comment by martinpitt** [comment]
`TestStorageScaling.testScaling` failure: The actual subvolume still exists:
```
# btrfs subvolume list /
ID 256 gen 78 top level 5 path root
ID 257 gen 76 top level 5 path home
ID 258 gen 78 top level 5 path var
ID 259 gen 76 top level 258 path var/lib/machines
```
and is also shown in the [screenshot](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6101-5605b494-20240318-225526-fedora-40-storage-cockpit-project-cockpit/TestStorageScaling-testScaling-fedora-40-127.0.0.2-2801-FAIL.png):

image

It's not mounted. But that's already the case in F39. The main difference is that F39 has an extra var/lib/portables subvolume (which is also not mounted), which apparently changes the hierarchy?

image

This was introduced in 1135fcb82b1f0842a45427. So this requires a test adjustment. I have it locally, I'll send it once I took a look at the remaining failure.

**Comment by martinpitt** [comment]
And finally, [TestStorageNBDE.testRootReboot](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6101-5605b494-20240318-225526-fedora-40-storage-cockpit-project-cockpit/log.html#33-2): The test fails on

> cp: cannot stat '/var/lib/package-sets/clevis/*': No such file or directory

It does exist on the original image:

```
# ls -l /var/lib/package-sets/clevis/
total 24
-rw-r--r--. 1 root root 11064 Mar 18 22:43 clevis-dracut-20-1.fc40.x86_64.rpm
-rw-r--r--. 1 root root 10974 Mar 18 22:43 clevis-systemd-20-1.fc40.x86_64.rpm
```

But I figure that may be related to `/var/` now being a separate subvolume? Indeed `/var` is fairly empty after calling encrypt_root(), presumably due to `--one-file-system`. :thinking:

**Comment by martinpitt** [comment]
Bah, [almost](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6101-5ce75243-20240320-124852-fedora-40-other-cockpit-project-cockpit/log.html#114-2) -- naughty pattern needs a little tweak.

**Pull request merged**
