### PR TITLE
Image refresh for rhel-9-0

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-9-0
 * [x] image-refresh rhel-9-0

### CODE REVIEW

**Comment by marusak** [comment]
[machines failed](https://logs.cockpit-project.org/logs/pull-2247-20210727-041814-bf079c16-rhel-9-0-cockpit-project-cockpit-machines/log.html#61-2) with UI saying that there is missing backend for isci-direct. There hasn't been any package removed. I'll re-run to make sure and then take a look.

**Comment by marusak** [comment]
Needs works, I will take a look

**Comment by martinpitt** [comment]
@marusak, @KKoukiou : iSCSI backend got intentionally removed, see https://bugzilla.redhat.com/show_bug.cgi?id=1975677 -- we need to somehow detect this in c-machines and not expose iSCSI storage pools on RHEL 9.

**Comment by KKoukiou** [comment]
> @marusak, @KKoukiou : iSCSI backend got intentionally removed, see https://bugzilla.redhat.com/show_bug.cgi?id=1975677 -- we need to somehow detect this in c-machines and not expose iSCSI storage pools on RHEL 9.

Right I have a ticket for it. https://bugzilla.redhat.com/show_bug.cgi?id=1985947
I have it in my plan for this week.

**Comment by KKoukiou** [comment]
> > @marusak, @KKoukiou : iSCSI backend got intentionally removed, see https://bugzilla.redhat.com/show_bug.cgi?id=1975677 -- we need to somehow detect this in c-machines and not expose iSCSI storage pools on RHEL 9.
> 
> Right I have a ticket for it. https://bugzilla.redhat.com/show_bug.cgi?id=1985947
> I have it in my plan for this week.

https://github.com/cockpit-project/cockpit-machines/pull/276

**Comment by marusak** [comment]
cockpit-project/cockpit-machines#276 landed, retrying

**Comment by marusak** [comment]
Hmm, or I'll rebase, to cleanup stats

**Review by marusak — APPROVED** [review]

**Pull request merged**
