### PR TITLE
WIP: 1-cockpit-8: [no-test] clean up BOTS vs. BASE directory

### PR DESCRIPTION
**Pull request by martinpitt**
* [ ] image-refresh centos-7
 * [x] naughty-prune

### CODE REVIEW

**Comment by martinpitt** [comment]
I triggered some tasks for self-testing, too.

**Comment by cockpituous** [comment]
naughty-prune in progress on 4-ci-srv-02.
Log: https://209.132.184.41:8493/logs/naughty-prune-35-20190927-111515/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-35-20190927-111616/

**Comment by martinpitt** [comment]
I tested this manually directly from the checkout (vm-run, image-prune, etc) and also with copying this into a cockpit checkout (again vm-run, npm-update, po-refresh), and it works fine for me. @Gundersanne, would be nice if you can confirm this for `$TEST_DATA`.

**Comment by martinpitt** [comment]
Ah, I forgot to replace one last thing in tests-invoke.

@Gundersanne : This also replaces the `$TEST_PROJECT` check. This only worked in the special case of tests-invoke, but we usually don't have this set anywhere else. Do you see any problem with that?

**Comment by cockpituous** [comment]
naughty-prune in progress on 4-ci-srv-02.
Log: https://209.132.184.41:8493/logs/naughty-prune-35-20190927-114444/

**Comment by martinpitt** [comment]
whee, tests found [a bug](https://209.132.184.41:8493/logs/pull-35-20190927-112323-24de7a22-mvollmer-subscription-manager--rhel-8-1/log.html)!

**Comment by martinpitt** [comment]
Fixed image-customize, and rebased to current master. Not re-running the issues tasks, as that only affects the external tests.

**Comment by martinpitt** [comment]
I discussed that with @Gundersanne on IRC, and we agreed on doing this differently. I don't like the "../.git" heuristics, it feels prone to get some corner cases wrong. Instead, let's assume that the cwd is always the project root that you want the bot to act on (including its own repo). IOW, let's change `TEST_DIR` → `.`

**Comment by martinpitt** [comment]
Reworked as above. I re-tested the same things from above, and in addition with a `ln -sf ../bots bots` symlink in my cockpit checkout. Let's re-run the issue tasks again, too.

**Comment by martinpitt** [comment]
Tests fail, apparently there is some non-current-cwd-ness with invoking tests:

    qemu-img: /build/tmp/run/06wsipzk.qcow2: Could not open '/build/tmp/run/test/images/fedora-30': No such file or directory

**Comment by martinpitt** [comment]
I created PR #37 to test this in isolation.

This was the command used for the above tests:
```
bots/make-checkout --verbose --base=master --repo=cockpit-project/cockpit --bots-ref=pull/35/head master && cd bots/make-checkout-workdir && GITHUB_BASE=cockpit-project/bots TEST_PROJECT=cockpit-project/cockpit TEST_NAME=pull-35-20190927-143434 TEST_REVISION=e6c5cfa09ec83067967ca74c565a19c6adca5508 bots/tests-invoke --pull-number=35  fedora-30/container-bastion ; cd ../..
```

Not sure where the /build/tmp comes from, the cwd ought to be something like /build/bots/make-checkout-workdir/cockpit/ ? But I'll prod this further next Monday.

**Comment by martinpitt** [comment]
Triggered a starter-kit test, as that's by far the fastest.

```
bots/make-checkout --verbose --base=master --repo=cockpit-project/starter-kit --bots-ref=pull/35/head master && cd bots/make-checkout-workdir && GITHUB_BASE=cockpit-project/bots TEST_PROJECT=cockpit-project/starter-kit TEST_NAME=pull-35-20190927-170606 TEST_REVISION=e6c5cfa09ec83067967ca74c565a19c6adca5508 bots/tests-invoke --pull-number=35  fedora-30 ; cd ../..
```

**Comment by martinpitt** [comment]
@Gundersanne : absolute paths work fine, so let's go with this for now. I'll look at why relative paths don't work when cleaning up the usage of these constants.

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-3nv71.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-35-20190927-155757/

**Comment by cockpituous** [comment]
naughty-prune in progress on 2-ci-srv-05.
Log: https://209.132.184.41:8493/logs/naughty-prune-35-20190927-155757/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-35-20190927-155757/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/bots/commits/image-refresh-centos-7-20190927-162525

**Pull request merged**
