### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-testing-20230808-230404.log

**Comment by jelly** [comment]
```
 libblockdev                x86_64  3.0.2-1.20230727074134605592.master.7.g1f0c5003.fc38 copr:copr.fedorainfracloud.org:group_storage:udisks-daily          94 k
 libblockdev-crypto         x86_64  3.0.2-1.20230727074134605592.master.7.g1f0c5003.fc38 copr:copr.fedorainfracloud.org:group_storage:udisks-daily          32 k
 libblockdev-fs             x86_64  3.0.2-1.20230727074134605592.master.7.g1f0c5003.fc38 copr:copr.fedorainfracloud.org:group_storage:udisks-daily          47 k
 libblockdev-loop           x86_64  3.0.2-1.20230727074134605592.master.7.g1f0c5003.fc38 copr:copr.fedorainfracloud.org:group_storage:udisks-daily          17 k
 libblockdev-lvm            x86_64  3.0.2-1.20230727074134605592.master.7.g1f0c5003.fc38 copr:copr.fedorainfracloud.org:group_storage:udisks-daily          39 k
 libblockdev-mdraid         x86_64  3.0.2-1.20230727074134605592.master.7.g1f0c5003.fc38 copr:copr.fedorainfracloud.org:group_storage:udisks-daily          23 k
 libblockdev-part           x86_64  3.0.2-1.20230727074134605592.master.7.g1f0c5003.fc38 copr:copr.fedorainfracloud.org:group_storage:udisks-daily          25 k
 libblockdev-swap           x86_64  3.0.2-1.20230727074134605592.master.7.g1f0c5003.fc38 copr:copr.fedorainfracloud.org:group_storage:udisks-daily          17 k
 libblockdev-utils          x86_64  3.0.2-1.20230727074134605592.master.7.g1f0c5003.fc38 copr:copr.fedorainfracloud.org:group_storage:udisks-daily          26 k
 libbytesize                x86_64  2.9-1.20230725071939803184.master.3.ge445fb1.fc38    copr:copr.fedorainfracloud.org:group_storage:udisks-daily          41 k
 libcomps                   x86_64  0.1.19-20230808005405.3.g2139b0f.fc38                copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly   77 k
 libdnf                     x86_64  0.70.2-20230808005409.0.g998efa8f.fc38               copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly  658 k
 libmodulemd                x86_64  2.15.0-20230808005403.0.gbfde7f2.fc38                copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly  239 k
 librepo                    x86_64  1.15.2-20230808005404.0.g1a0a5fd.fc38                copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly   95 k
 libsolv                    x86_64  0.7.24-20230808005400.11.g86717630.fc38              copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly  426 k
 libudisks2                 x86_64  2.11.0-8.20230808gitb4924ca8.fc38                    copr:copr.fedorainfracloud.org:group_storage:udisks-daily         221 k
 python3-dnf                noarch  4.16.2-20230808005411.1.g8e7ae4fc.fc38               copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly  558 k
 python3-dnf-plugins-core   noarch  4.4.2-20230808005413.0.g45a2907.fc38                 copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly  281 k
 python3-hawkey             x86_64  0.70.2-20230808005409.0.g998efa8f.fc38               copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly  104 k
 python3-libcomps           x86_64  0.1.19-20230808005405.3.g2139b0f.fc38                copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly   47 k
 python3-libdnf             x86_64  0.70.2-20230808005409.0.g998efa8f.fc38               copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly  818 k
 python3-librepo            x86_64  1.15.2-20230808005404.0.g1a0a5fd.fc38                copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly   50 k
 udisks2                    x86_64  2.11.0-8.20230808gitb4924ca8.fc38                    copr:copr.fedorainfracloud.org:group_storage:udisks-daily         513 k
 udisks2-iscsi              x86_64  2.11.0-8.20230808gitb4924ca8.fc38                    copr:copr.fedorainfracloud.org:group_storage:udisks-daily         198 k
 udisks2-lvm2               x86_64  2.11.0-8.20230808gitb4924ca8.fc38                    copr:copr.fedorainfracloud.org:group_storage:udisks-daily         213 k
 yum                        noarch  4.16.2-20230808005411.1.g8e7ae4fc.fc38               copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly   30 k
```

Updated packages, seems udisks broke a thing.

**Comment by mvollmer** [comment]
> @mvollmer do you mind taking a look? 

Yep, reproduced.

**Comment by mvollmer** [comment]
> > @mvollmer do you mind taking a look?
> 
> Yep, reproduced.

This is caused by https://github.com/storaged-project/udisks/commit/a2f26afe4ee806531cd55562b9b9a90e9436eced, I file a bug.

**Comment by mvollmer** [comment]
> > > @mvollmer do you mind taking a look?
> > 
> > 
> > Yep, reproduced.
> 
> This is caused by [storaged-project/udisks@a2f26af](https://github.com/storaged-project/udisks/commit/a2f26afe4ee806531cd55562b9b9a90e9436eced), I file a bug.

https://github.com/storaged-project/udisks/issues/1170

**Review by tomasmatus — APPROVED** [review]

**Pull request merged**
