### PR TITLE
Image refresh for fedora-34

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-34
 * [x] image-refresh fedora-34

### CODE REVIEW

**Comment by martinpitt** [comment]
@jkozol : Are the `TestImage.testOpenStack` timeouts known? Is that related to the new image?

**Comment by jkozol** [comment]
@martinpitt these test failures seem like flakes to me. [Here](https://github.com/osbuild/cockpit-composer/pull/1404) our rhel-8-6 test fails for the ostree commit and container. The 9.0 test fails the create image test. All tests runs passed the openstack image.

**Comment by martinpitt** [comment]
OK, trying for the third time.. :crossed_fingers:

**Comment by jkozol** [comment]
@martinpitt yep seems like it was a flake. But, I do know these are frequent flakes. I notified my team about the issues building some of these images. It seems to me that it is not a UI problem but a backend issue.

**Review by martinpitt — APPROVED** [review]

**Comment by martinpitt** [comment]
Thanks @jkozol !

**Pull request merged**
