### PR TITLE
images: Add rhel-8-2

### PR DESCRIPTION
**Pull request by martinpitt**
- [x] Declare new image: PR #184
 * [x] image-refresh rhel-8-2

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-185-20191027-201515/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-185-20191027-201515/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-185-20191027-201515/

**Comment by cockpituous** [comment]
image-refresh rhel-8-2 done: https://github.com/cockpituous/bots/commits/image-refresh-rhel-8-2-20191027-203333

**Comment by martinpitt** [comment]
This isn't being used anywhere yet, I'm preparing that in https://github.com/cockpit-project/cockpit/pull/13043 . So IMHO we should just land that as-is, so that we can unblock adding the cockpit test.

**Comment by martinpitt** [comment]
@marusak : There will be tons of failures, as master doesn't have https://github.com/cockpit-project/cockpit/pull/13043 yet. But sure, it should at least start and succeed *some* tests :)

**Comment by martinpitt** [comment]
Actually, we could land #13043 *first* and block this image addition on that. That would avoid having to land a red PR

**Pull request merged**
