### PR TITLE
images: Install updates repositories, install mock from RHEL 9 EPEL

### LINKED ISSUE #4645: Image refresh for rhel-9-0
Image refresh for rhel-9-0
 * [ ] image-refresh rhel-9-0

### LINKED ISSUE #4654: Image refresh for rhel-8-9
Image refresh for rhel-8-9
 * [ ] image-refresh rhel-8-9

### LINKED ISSUE #4655: Image refresh for rhel-9-0
Image refresh for rhel-9-0
 * [ ] image-refresh rhel-9-0

### PR DESCRIPTION
**Pull request by martinpitt**
z-stream updates are not part of the normal nightly repository, but get into a separate "updates" repository. This picks up        
our 8.6.z/9.0.z fixes for the login page, and thus obsoletes the sed hack from commit b686b706a7. Moreover, we actually want to test against z-stream updates, as that is the whole point of regularly rebuilding images for released RHEL versions.        
        
-----

I am not going to rebuild the full set of RHEL images here, as that's too painful. I'll do the current devel series and a stable one which is meaningful.

 * [x] image-refresh rhel-8-6
 * [x] image-refresh rhel-8-9
 * [x] image-refresh rhel-9-3
 * [x] image-refresh rhel-9-0

Closes #4654 
Closes #4655

### CODE REVIEW

**Comment by martinpitt** [comment]
Yes, that's what I want to see:

     cockpit-ws                               x86_64  264.2-1.el9_0                 RHEL-NIGHTLY-BaseOS-Updates     1.3 M

We previously had 264.1, which still had the login page bug.

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20230414-082408

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-0-20230414-082424.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-3-20230414-082626.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-6-20230414-082828.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-6-20230414-082929.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-6-20230414-084343.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-9-20230414-084545.log

**Comment by cockpituous** [comment]
image-refresh rhel-8-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-9-20230414-085817

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-9-20230414-085858.log

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-9-20230414-085858.log

**Comment by cockpituous** [comment]
image-refresh rhel-8-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-9-20230414-085939

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-9-20230414-085959.log

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20230414-093257

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-6-20230414-093232.log

**Comment by martinpitt** [comment]
Oh yeah, we get [two metric tons of updates](https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-6-20230414-093232.log) now!

**Comment by cockpituous** [comment]
image-refresh rhel-8-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-9-20230414-095754

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-9-20230414-095757.log

**Comment by cockpituous** [comment]
Failed. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-3-20230414-095959.log

**Comment by cockpituous** [comment]
image-refresh rhel-9-3 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-3-20230414-104848

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-3-20230414-104848.log

**Comment by cockpituous** [comment]
image-refresh rhel-9-0 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-9-0-20230414-111545

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-9-0-20230414-111515.log

**Comment by martinpitt** [comment]
Meh -- we test z-stream updates, we find lots of new [SELinux](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4647-20230414-111913-9f56f99d-rhel-9-0-candlepin-subscription-manager/log.html) [issues](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4647-20230414-111909-9f56f99d-rhel-8-6-candlepin-subscription-manager-subscription-manager-1.28/log.html), and an [insights regression](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4647-20230414-111906-9f56f99d-rhel-8-6-candlepin-subscription-manager-subscription-manager-1.28.29/log.html#5).

@ptoscano do these ring a bell for you? It seems we can all ignore them, as they are "just" unexpected messages.

**Comment by martinpitt** [comment]
The SELinux errors are just https://bugzilla.redhat.com/show_bug.cgi?id=2124550 and https://bugzilla.redhat.com/show_bug.cgi?id=2124549 , so we can safely ignore them on the old images. I'm a bit more concerned about these:
```
Error importing insights.client for pre_update as /var/lib/insights/newest.egg: No module named 'insights'
Error importing insights.client for update as /var/lib/insights/newest.egg: No module named 'insights'
Error importing insights.client for post_update as /var/lib/insights/newest.egg: No module named 'insights'
```
But the [log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4647-20230414-111906-9f56f99d-rhel-8-6-candlepin-subscription-manager-subscription-manager-1.28.29/TestSubscriptions-testSubAndInAndFail-rhel-8-6-127.0.0.2-2401-FAIL.log.gz) sounds like that's just recursive fallout -- the selinux issues get picked up and it apparently asks insights for, well, an insight about these, but insights isn't set up yet? That seems ignorable to me as well.

**Comment by ptoscano** [comment]
> The SELinux errors are just https://bugzilla.redhat.com/show_bug.cgi?id=2124550 and https://bugzilla.redhat.com/show_bug.cgi?id=2124549 , so we can safely ignore them on the old images.

Yes, or add a naughty for them (so we can track it, and drop it in the future) -- something like:
```
audit: type=1400 audit*: avc:  denied * name="(pubring.kbx|trustdb.gpg)" * scontext=system_u:system_r:gpg_t:*
```
BTW, folks in my team are working on these issues, although they can be only fixed partially in new egg releases: the code that validates signatures using gpg is both in the egg (which is automatically fetched by all the versions of `insights-client`), and in `insights-client` itself (which thus will be fixed only in newer versions).

Also, IIRC the SELinux to allow this was added in 8.7 and 9.1, that's why you see the failures in 8.6 and 9.0.

> ```
> Error importing insights.client for pre_update as /var/lib/insights/newest.egg: No module named 'insights'
> Error importing insights.client for update as /var/lib/insights/newest.egg: No module named 'insights'
> Error importing insights.client for post_update as /var/lib/insights/newest.egg: No module named 'insights'
> ```

Unfortunately these don't ring a bell; I remember they used to happen loooooong time ago, so I'm surprised to see them again.

**Review by KKoukiou — COMMENTED** [review]
THere are still some failures:

rhel-8-6@candlepin/subscription-manager/subscription-manager-1.28

rhel-8-6@candlepin/subscription-manager/subscription-manager-1.28.29

rhel-9-0@candlepin/subscription-manager

**Comment by martinpitt** [comment]
@KKoukiou : Yup, one of the messages was `{ read write }`, I relaxed the RE to catch them.

**Comment by martinpitt** [comment]
.. and once more with feeling!

**Comment by cockpituous** [comment]
image-refresh rhel-8-6 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-8-6-20230415-074035

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/rhel-8-6-20230415-074040.log

**Comment by martinpitt** [comment]
Ah, this is better! Previous build had a bad insights version. Triggering the tests for other images.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
