### PR TITLE
Image refresh for fedora-34

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-34
 * [x] image-refresh fedora-34

### CODE REVIEW

**Comment by skobyda** [comment]
Many CDP errors
https://logs.cockpit-project.org/logs/pull-1835-20210323-090938-6b19918b-fedora-34-cockpit-project-cockpit/log.html#235-2
https://logs.cockpit-project.org/logs/pull-1835-20210323-090938-6b19918b-fedora-34-cockpit-project-cockpit-machines-main/log.html#49-2

**Comment by skobyda** [comment]
So the 3 machines are failing because on this version of Fedora 34 the NFS server cannot be set up. I tried to fix it, but could not come up with work around nfs-mountd.service failing with error `Unable to watch /proc/fs/nfsd/clients: Permission denied`, so I reported the bug upstream (it could be cause by new update in kernel's NFS or systemd): 
https://bugzilla.redhat.com/show_bug.cgi?id=1943157

Since NFS servers are needed for some of our storage-pools or disk tests to run, I think only think which can be done here is to skip them until bug is resolved.

**Comment by skobyda** [comment]
Blocked on https://github.com/cockpit-project/cockpit-machines/pull/24/

**Comment by KKoukiou** [comment]
@skobyda @marusak the NFS issue is already fixed and in updates testing, maybe can we try just refreshing the image instead of introducing the test workaround?

**Comment by marusak** [comment]
Right, it was obsoleted by https://bodhi.fedoraproject.org/updates/FEDORA-2021-15b81d905c but lets give this time by Monday for sure, it is not that anyone is gonna fix it now.

**Comment by martinpitt** [comment]
Agreed -- let's wait for this to land in f-34 proper, then close this and let the bots build a new one.

**Comment by skobyda** [comment]
It seems that the update has been pushed to stable yesterday: https://bodhi.fedoraproject.org/updates/FEDORA-2021-15b81d905c
Is it good to rebuild the image now?

**Comment by marusak** [comment]
> Is it ok to rebuild the image now?

sure, we can try it out. Easiest would be to close this PR and do clean refresh

**Pull request closed without merging**
