### PR TITLE
Revert "machine: fix shell quoting on m.execute()"

### PR DESCRIPTION
**Pull request by marusak**
This reverts commit 13eff0d5743b75c3a7ea53ffd87ac081a947285e.

### CODE REVIEW

**Comment by marusak** [comment]
@allisonkarlitskaya btw as now master fails with: https://logs.cockpit-project.org/logs/pull-15234-20210129-062252-e208e601-fedora-32/log.html

**Review by martinpitt — DISMISSED** [review]
I suppose we need to fix the check-realms test a little harder, and then reapply this.

**Comment by martinpitt** [comment]
Sent check-realms fix in https://github.com/cockpit-project/cockpit/pull/15243 , it was pretty obvious after all (and also the correct thing to do).

**Comment by allisonkarlitskaya** [comment]
pitti fixed that with cockpit-project/cockpit#15243, just landed

**Pull request closed without merging**
