### PR TITLE
Image refresh for fedora-rawhide-boot

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-rawhide-boot
 * [x] image-refresh fedora-rawhide-boot

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-rawhide-boot done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-rawhide-boot-20240212-092448

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/fedora-rawhide-boot-20240212-092424.log

**Comment by KKoukiou** [comment]
Tests got detected as known issue https://cockpit-logs.us-east-1.linodeobjects.com/pull-172-20240212-145400-a27b82b8-fedora-rawhide-boot-bots-5900/log.html#25

Symlinked the fedora-rawhide-boot to fedora-40 to make this properly green.

**Comment by KKoukiou** [comment]
Tests running @ https://github.com/cockpit-project/bots/pull/5900

**Review by martinpitt — APPROVED** [review]
Thanks! Please merge both PRs when ready.

**Pull request merged**
