### PR TITLE
Image refresh for centos-10

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-10
 * [x] image-refresh centos-10

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh centos-10 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-10-20241220-225757

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-centos-10-2e847dda-20241220-223952/log.html

**Comment by martinpitt** [comment]
Breaks remote sessions. On first day of holidays, awesome :cry:

**Comment by martinpitt** [comment]
This is "fun":
```
File "/usr/lib/python3.12/site-packages/cockpit/beiboot.py", line 527, in <module>
   main()
File "/usr/lib/python3.12/site-packages/cockpit/beiboot.py", line 296, in __init__
     self.tmpdir = tempfile.TemporaryDirectory()

FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']

SELinux is preventing /usr/bin/python3.12 from write access on the directory var-tmp
```

**Comment by martinpitt** [comment]
Lazy holiday mode, closing and trying with the next auto refresh.

**Pull request closed without merging**
