### PR TITLE
images: Avoid conffile prompts in debian.setup

### LINKED ISSUE #335: Image refresh for debian-testing
Image refresh for debian-testing
 * [ ] FAIL: image-refresh debian-testing

### PR DESCRIPTION
**Pull request by martinpitt**
Always use the original config file instead of asking interactively.

Factorize the apt-get options into a new `$APT` variable.

Fixes #335

 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-389-20200103-073737/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-389-20200103-073737/

**Comment by martinpitt** [comment]
Some [weird libvirt failure](https://209.132.184.41:8493/logs/image-refresh-389-20200103-073737/log), retrying.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-389-20200103-085959/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/bots/commits/image-refresh-debian-testing-20200103-094040

**Pull request merged**
