### PR TITLE
images: Add appstream to ubuntu-2004's build chroot

### PR DESCRIPTION
**Pull request by martinpitt**
Ubuntu 20.04 still has gettext 0.19, which is too old to ship
`metainfo.its` yet. So add the `appstream` package which ships that.
This will be used for translating AppStream metainfo files, see
https://github.com/cockpit-project/cockpit/pull/17147

 * [x] image-refresh ubuntu-2004

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-3115-20220320-083434/

**Comment by cockpituous** [comment]
image-refresh ubuntu-2004 done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-2004-20220320-085151

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-01.
Log: https://logs.cockpit-project.org/logs/image-refresh-3115-20220320-090707/

**Review by marusak — APPROVED** [review]
Danke :)

**Pull request merged**
