### PR TITLE
images: Clean up old kernels on Fedora images

### PR DESCRIPTION
**Pull request by martinpitt**
Similar to commit 2a6b4291dd8b. This reduces image size, and also halves
the time for `fips-mode-setup`, as that regenerates the initrd for all
installed kernels.

 * [x] image-refresh fedora-36
 * [x] image-refresh fedora-35
 * https://github.com/cockpit-project/cockpit/pull/17279

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3293-20220424-062020/

**Comment by cockpituous** [comment]
image-refresh fedora-36 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-36-20220424-063737

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-3293-20220424-063737/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-02.
Log: https://logs.cockpit-project.org/logs/image-refresh-3293-20220424-063737/

**Comment by cockpituous** [comment]
image-refresh fedora-35 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-35-20220424-070202

**Comment by martinpitt** [comment]
New Fedora 35 broke CPU mitigations, needs work.

**Comment by martinpitt** [comment]
Adding and removing the `nosmt` option on Fedora 35 works fine. The issue is with our fake "42" kernel to test option propagation:
```
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
kernel-install add 42.0.0 /boot/vmlinuz-42.0.0
```
This installs the new fake kernel, and also makes it the default:
```
/boot/grub2/grubenv:saved_entry=a7173868d29543b4bf15bf4227230490-42.0.0
```

But removing it:
```
rm /boot/vmlinuz-42.0.0
kernel-install remove 42.0.0 /boot/vmlinuz-42.0.0
```
... does not clean up the default in `saved_entry`. It should go back to the previous `saved_entry=a7173868d29543b4bf15bf4227230490-5.16.20-200.fc35.x86_64`.

On the previous image, this was *also* the case, but curiously the  boot worked. Even after a reboot, the saved default is still wrong. The updated packages on this image are not particularly related to grub/kernel/booting, so this smells like some accidental thing.

I reported the underlying bug to https://bugzilla.redhat.com/show_bug.cgi?id=2078359. Looking for a workaround now.

**Comment by martinpitt** [comment]
Reported both bugs, and sent https://github.com/cockpit-project/cockpit/pull/17279 to work around them. Blocking on that PR.

**Review by jelly — APPROVED** [review]

**Pull request merged**
