### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos

### CODE REVIEW

**Comment by martinpitt** [comment]
All tests fail with

    fatal: The server refused to authenticate 'admin' using password authentication, and no other supported authentication methods are available.

It seems ssh disabled password auth by default now?

**Comment by martinpitt** [comment]
Ah, my hack works  for cockpit, but not for c-ostree.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-921-20200603-193333/

**Comment by cockpituous** [comment]
image-refresh fedora-coreos done: https://github.com/cockpituous/bots/commits/image-refresh-fedora-coreos-20200603-194444

**Pull request merged**
