### PR TITLE
Image refresh for fedora-coreos

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-coreos
 * [x] image-refresh fedora-coreos
 * [x] Skip NM-team tests: https://github.com/cockpit-project/cockpit/pull/13276
 * [x] Avoid netcat in metrics test: https://github.com/cockpit-project/cockpit/pull/13296

### CODE REVIEW

**Comment by martinpitt** [comment]
Oddly enough I can't reproduce the [podman restart errors](https://209.132.184.41:8493/logs/pull-305-20191205-074141-28be92c3-cockpit-project-cockpit--fedora-coreos/log.html#60-2) locally. BUt I can reproduce it manually with
```
podman container runlabel RUN cockpit/ws  -- --no-tls
podman restart lucid_leakey
```
which does fail with
```
Error: container '2e66874cc981e5f32b6cbdcfa6be8570b75f81df0feeba65eca951fad3b8e2b6' already exists: OCI runtime error
```

This looks very close to https://discussion.fedoraproject.org/t/toolbox-not-working-again/12744 (thanks @garrett for pointing it out this morning)

**Comment by martinpitt** [comment]
There is a fix upstream now for the `podman restart` regression, but it apparently still takes a while until that lands. I added a workaround for now.

**Comment by martinpitt** [comment]
[network teams](https://209.132.184.41:8493/logs/pull-305-20191211-094747-60ea2484-cockpit-project-cockpit--fedora-coreos/log.html#153-2) are still broken, I can reproduce locally.

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/13276 to skip the team tests. NetworkManager-team fell off the FCOS image.

**Comment by martinpitt** [comment]
[testMetrics failure](https://209.132.184.41:8493/logs/pull-305-20191211-165959-60ea2484-cockpit-project-cockpit--fedora-coreos/log.html), but that's most probably a flake.

**Comment by martinpitt** [comment]
[testMetrics](https://209.132.184.41:8493/logs/pull-305-20191211-215959-60ea2484-cockpit-project-cockpit--fedora-coreos/log.html) keeps failing, meh.

**Comment by Gundersanne** [comment]
@martinpitt it seems that whatever is generating the network traffic isn't doing so [screenshot](https://209.132.184.41:8493/logs/pull-305-20191211-215959-60ea2484-cockpit-project-cockpit--fedora-coreos/TestMetrics-testInternal-fedora-coreos-127.0.0.2-2801-FAIL.png)

**Comment by martinpitt** [comment]
I finally went back to this. The simple reason is that netcat isn't available on this image any more, it apparently fell out due to some dependency changes between F30 and 31.

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/13296 to avoid netcat in the metrics test.

**Pull request merged**
