### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-testing-20230515-230303.log

**Comment by martinpitt** [comment]
`pkcon: command not found` :roll_eyes:  Indeed `packagekit-tools` got removed. That was indeed
[changed in 1.2.6-4](https://tracker.debian.org/news/1429299/accepted-packagekit-126-4-source-into-unstable/). However, there was [another commit](https://salsa.debian.org/pkgutopia-team/packagekit/-/commit/95cd3a7d069865502ef9afd805a00f6b89d0d5c5) which (hopefully unintendedly) dropped `packagekit`'s recommendation for `packagekit-tools`.

I reported this to https://bugs.debian.org/1036153 and fixed it here.

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpit-project/bots/commits/image-refresh-debian-testing-20230516-060924

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-logs/debian-testing-20230516-060909.log

**Comment by martinpitt** [comment]
@allisonkarlitskaya In IT, anything > 3 years is "forever", right? :grin:

**Pull request merged**
