### PR TITLE
Image refresh for fedora-34

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-34
 * [x] image-refresh fedora-34

### CODE REVIEW

**Comment by martinpitt** [comment]
@jkozol , @henrywang : testOpenstack timed out six times in this run, and I already retried. (This also makes the whole test run time out). This check looks broken, can you please have a look?

**Comment by martinpitt** [comment]
testOpenstack succeeded in https://github.com/osbuild/cockpit-composer/pull/1395 and just takes 266s there. Here, the [screenshot](https://logs.cockpit-project.org/logs/pull-2892-20220204-050339-841563f4-fedora-34-osbuild-cockpit-composer/TestImage-testOpenStack-fedora-34-127.0.0.2-2201-FAIL.png) shows that image creation failed, and the [journal](https://logs.cockpit-project.org/logs/pull-2892-20220204-050339-841563f4-fedora-34-osbuild-cockpit-composer/TestImage-testOpenStack-fedora-34-127.0.0.2-2201-FAIL.log.gz) has:
```
osbuild-worker[9395]: Traceback (most recent call last):
osbuild-worker[9395]:   File "/usr/bin/osbuild", line 33, in <module>
osbuild-worker[9395]:     sys.exit(load_entry_point('osbuild==46', 'console_scripts', 'osbuild')())
osbuild-worker[9395]:   File "/usr/lib/python3.9/site-packages/osbuild/main_cli.py", line 158, in osbuild_cli
osbuild-worker[9395]:     manifest.download(object_store, monitor, args.libdir)
osbuild-worker[9395]:   File "/usr/lib/python3.9/site-packages/osbuild/pipeline.py", line 359, in download
osbuild-worker[9395]:     source.download(mgr, store, libdir)
osbuild-worker[9395]:   File "/usr/lib/python3.9/site-packages/osbuild/sources.py", line 38, in download
osbuild-worker[9395]:     reply = client.call_with_fds("download", args, fds)
osbuild-worker[9395]:   File "/usr/lib/python3.9/site-packages/osbuild/host.py", line 356, in call_with_fds
osbuild-worker[9395]:     raise error
osbuild-worker[9395]: osbuild.host.RemoteError: RuntimeError: curl: error downloading {'url': 'https://ftp-chi.osuosl.org/pub/fedora/linux/updates/34/Everything/x86_64/Packages/v/vim-data-8.2.4232-1.fc34.noarch.rpm'}: error code 22
osbuild-worker[9395]:    File "/usr/lib/python3.9/site-packages/osbuild/host.py", line 258, in serve
osbuild-worker[9395]:     reply, reply_fds = self._handle_message(msg, fds)
osbuild-worker[9395]:   File "/usr/lib/python3.9/site-packages/osbuild/host.py", line 291, in _handle_message
osbuild-worker[9395]:     ret, fds = self.dispatch(name, args, fds)
osbuild-worker[9395]:   File "/usr/lib/python3.9/site-packages/osbuild/sources.py", line 62, in dispatch
osbuild-worker[9395]:     r = self.download(items,
osbuild-worker[9395]:   File "/usr/lib/osbuild/sources/org.osbuild.curl", line 178, in download
osbuild-worker[9395]:     download(items, cache)
osbuild-worker[9395]:   File "/usr/lib/osbuild/sources/org.osbuild.curl", line 168, in download
osbuild-worker[9395]:     for _ in results:
osbuild-worker[9395]:   File "/usr/lib64/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
osbuild-worker[9395]:     for element in iterable:
osbuild-worker[9395]:   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
osbuild-worker[9395]:     yield fs.pop().result()
osbuild-worker[9395]:   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
osbuild-worker[9395]:     return self.__get_result()
osbuild-worker[9395]:   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
osbuild-worker[9395]:     raise self._exception
osbuild-worker[9267]: time="2022-02-04T05:15:09Z" level=warning msg="Job '66da501f-2899-4366-8933-7e4eeb6c5e28' (osbuild) failed: error decoding osbuild output: unexpected end of JSON input\nthe raw output:\n"
```

The second exception is a bug in osbuild; the curl download failure doesn't look related to the fedora-34 host image it's running on, but that it tries to bootstrap a new Fedora from a download.

There are not too many [package changes](https://logs.cockpit-project.org/logs/image-refresh-2892-20220204-015959/log) in this refresh:
```
  container-selinux (2:2.170.0-2.fc34 -> 2:2.173.1-1.fc34)
  distribution-gpg-keys (1.60-1.fc34 -> 1.62-1.fc34)
  dnsmasq (2.86-3.fc34 -> 2.86-4.fc34)
  glibc (2.33-20.fc34 -> 2.33-21.fc34)
  glibc-all-langpacks (2.33-20.fc34 -> 2.33-21.fc34)
  glibc-common (2.33-20.fc34 -> 2.33-21.fc34)
  glibc-doc (2.33-20.fc34 -> 2.33-21.fc34)
  glibc-langpack-en (2.33-20.fc34 -> 2.33-21.fc34)
  kernel-core (5.15.16-100.fc34 -> 5.15.18-100.fc34)
  libibverbs (37.0-1.fc34 -> 37.2-2.fc34)
  librdmacm (37.0-1.fc34 -> 37.2-2.fc34)
  libsmbclient (2:4.14.11-0.fc34 -> 2:4.14.12-0.fc34)
  libwbclient (2:4.14.11-0.fc34 -> 2:4.14.12-0.fc34)
  libxcrypt (4.4.27-1.fc34 -> 4.4.27-2.fc34)
  libxcrypt-compat (4.4.27-1.fc34 -> 4.4.27-2.fc34)
  pam (1.5.1-7.fc34 -> 1.5.1-8.fc34)
  python-unversioned-command (3.9.9-2.fc34 -> 3.9.10-1.fc34)
  python3 (3.9.9-2.fc34 -> 3.9.10-1.fc34)
  python3-libs (3.9.9-2.fc34 -> 3.9.10-1.fc34)
  samba-client-libs (2:4.14.11-0.fc34 -> 2:4.14.12-0.fc34)
  samba-common (2:4.14.11-0.fc34 -> 2:4.14.12-0.fc34)
  samba-common-libs (2:4.14.11-0.fc34 -> 2:4.14.12-0.fc34)
```

None of them immediately jump out as being plausible for this error..

**Comment by jkozol** [comment]
@martinpitt Thanks for the information. I will investigate.

**Comment by jkozol** [comment]
@martinpitt I believe this is a problem with the mirrorlist. The build fails because `https://ftp-chi.osuosl.org/pub/fedora/linux/updates/34/Everything/x86_64/Packages/v/vim-data-8.2.4232-1.fc34.noarch.rpm` does not exist. I assume at some point we will get pointed to a different mirror and this will succeed.

**Comment by martinpitt** [comment]
@jkozol : So you think that's random, and the two retries were just bad luck? https://github.com/osbuild/cockpit-composer/pull/1395 ran an hour or so later. Well, I'll retry once again.

**Comment by jkozol** [comment]
@martinpitt Hopefully. I reran the tests here: https://github.com/osbuild/cockpit-composer/pull/1393 and it passed and I don't see any package updates that would affect us. If it fails this time I will come back and look more thoroughly.

_Sidenote_: I am doing a release today.

**Comment by martinpitt** [comment]
@jkozol : Indeed, succeeded now.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
