### PR TITLE
images: Ubuntu 24.04 got released

### PR DESCRIPTION
**Pull request by martinpitt**
Drop the mantic → noble hack in the bootstrap, as noble is really the current stable now. With that we can also re-enable -proposed.

 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20240429-075020

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-stable-dfa6de5b-20240429-073654/log.html

**Comment by martinpitt** [comment]
noble-proposed got cleaned up now, trying again.

**Comment by martinpitt** [comment]
Erk, rhos-01-1 ran out of space, fixed.

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpit-project/bots/commits/image-refresh-ubuntu-stable-20240502-050304

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-ubuntu-stable-f233dc00-20240502-044906/log.html

**Review by jelly — APPROVED** [review]
yay for the quick turnaround

**Pull request merged**
