### PR TITLE
Image refresh for fedora-41

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-41
 * [x] image-refresh fedora-41

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-41 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-41-20241001-225845

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-41-ef8bbc6b-20241001-224049/log.html

**Comment by martinpitt** [comment]
This also hit the clevis regression discussed in https://bodhi.fedoraproject.org/updates/FEDORA-2024-5f97e1176b , see https://github.com/cockpit-project/cockpit/issues/21048

**Comment by mvollmer** [comment]
> This also hit the clevis regression discussed in https://bodhi.fedoraproject.org/updates/FEDORA-2024-5f97e1176b , see [cockpit-project/cockpit#21048](https://github.com/cockpit-project/cockpit/issues/21048)

Let's try again.

**Comment by cockpituous** [comment]
image-refresh fedora-41 done: https://github.com/cockpit-project/bots/commits/image-refresh-fedora-41-20241007-083037

**Comment by cockpituous** [comment]
Success. Log: https://cockpit-logs.us-east-1.linodeobjects.com/image-refresh-fedora-41-31d60bd1-20241007-074825/log.html

**Comment by mvollmer** [comment]
> Let's try again.

Nope, not yet. I'll close this and let the bot open a new one in a few days.

**Pull request closed without merging**
